import {
  defineLearningMasteryTopics,
  type LearningMasteryQuestionSeed,
  type LearningPlatform,
  type LearningQuestionDifficulty,
} from './learning-model'

const allPlatforms = ['Turing', 'Andela', 'Toptal'] as const

function question(
  prompt: string,
  correctOption: string,
  distractors: readonly [string, string, string],
  explanation: string,
  difficulty: LearningQuestionDifficulty,
  platforms: readonly LearningPlatform[] = allPlatforms,
): LearningMasteryQuestionSeed {
  return {
    prompt,
    options: [correctOption, ...distractors],
    correctOptionIndex: 0,
    explanation,
    difficulty,
    platforms,
  }
}

export const llmOpsProductionMasteryTopics = defineLearningMasteryTopics(
  'ai-engineering-core',
  'llmops-production-ai',
  [
    {
      id: 'release-control-and-delivery',
      title: 'Control and deliver AI releases',
      masteryLevel: 'L2',
      frequency: 'core',
      questionTarget: 15,
      questions: [
        question(
          'A support copilot produces worse answers after a release that changed its prompt, embedding model, and corpus. What artifact most directly enables a defensible diagnosis?',
          'An immutable release manifest binding the code, model, prompt, embedding, index, corpus, policy, tool, and evaluator versions',
          [
            'A Git tag for the application code without external artifact identifiers',
            'A dashboard showing only the currently configured model alias',
            'A copy of the latest prompt saved in the incident ticket',
          ],
          'AI behavior depends on independently changing artifacts beyond source code. A manifest lets the team replay the exact production combination, compare one component at a time, and roll back the responsible artifact without discarding unrelated improvements.',
          'medium',
        ),
        question(
          'A candidate model improves global answer accuracy by two points but lowers accuracy for Portuguese billing cases from 94% to 86%. How should the promotion gate respond?',
          'Block promotion because the critical slice violates its explicit regression budget despite the aggregate gain',
          [
            'Promote because aggregate accuracy is the only statistically useful release metric',
            'Promote to all users and ask Portuguese users to report incorrect answers',
            'Remove the Portuguese slice so future runs are less noisy',
          ],
          'Aggregate metrics can hide severe harm to an important cohort. A mature gate combines global goals with minimum safety and quality thresholds for critical slices, preserving case-level evidence for remediation or a documented, time-limited exception.',
          'hard',
        ),
        question(
          'Which CI/CD sequence gives the strongest evidence before an AI configuration serves live responses?',
          'Build immutable artifacts, run deterministic and versioned offline evaluations, sign a manifest, shadow traffic, then canary with automated stop conditions',
          [
            'Deploy the mutable model alias first, then run unit tests against whichever version is active',
            'Run a prompt linter, replace production immediately, and evaluate only after user complaints',
            'Canary unversioned prompt changes while skipping schema and security tests',
          ],
          'The sequence moves from cheap deterministic checks to behavioral evidence and finally bounded production exposure. Signing the complete manifest preserves provenance, while shadow and canary stages reveal integration and distribution failures without immediately exposing every user.',
          'medium',
        ),
        question(
          'A new claims-agent release must be shadow tested. Which setup preserves safety while producing useful comparative evidence?',
          'Replay eligible production inputs to the candidate with side effects disabled, equivalent redaction, a pinned manifest, and comparison against the control',
          [
            'Allow both control and candidate agents to issue claims payments, then compare totals',
            'Send synthetic health checks only and treat successful HTTP responses as a quality comparison',
            'Mirror raw requests to a developer account that has broader data access than production',
          ],
          'Shadowing should exercise the real read path without duplicating external effects. Equivalent privacy controls, immutable versions, and paired outcomes make the comparison meaningful while preventing the candidate from changing customer state.',
          'hard',
        ),
        question(
          'A prompt canary is assigned per HTTP request, and users report contradictory behavior within the same conversation. What rollout correction is most appropriate?',
          'Use sticky assignment by conversation and keep caches and traces partitioned by release manifest',
          [
            'Randomize the prompt again for every generated token to improve experiment balance',
            'Merge control and candidate cache entries so both cohorts receive consistent latency',
            'Disable manifest identifiers because they can reveal which version users received',
          ],
          'Multi-turn state assumes stable behavior across a conversation. Sticky assignment prevents version mixing, manifest-scoped caches prevent contamination, and trace identifiers preserve attribution for quality, latency, and cost comparisons.',
          'medium',
        ),
        question(
          'A canary has processed 120 requests with no failures, and a manager wants to move directly from 1% to 100%. What is the strongest engineering response?',
          'Require the predeclared minimum sample and observation window for critical slices before advancing through staged exposure',
          [
            'Approve the jump because any successful request proves the candidate is production safe',
            'Keep the canary at 1% forever because AI releases can never be evaluated sufficiently',
            'Advance based only on lower median latency, ignoring quality and safety signals',
          ],
          'A tiny sample may miss rare intents, delayed outcomes, and safety failures. Predeclared stage criteria prevent schedule pressure from changing the decision rule after results are visible and keep exposure proportional to accumulated evidence.',
          'hard',
        ),
        question(
          'During a 10% rollout, unsupported claims exceed the rollback threshold. The database schema is backward compatible, but the candidate also introduced a new prompt and index. What should automated rollback do?',
          'Route new traffic to the prior complete manifest and preserve candidate traces and artifacts for diagnosis',
          [
            'Change only the visible prompt text while leaving traffic on the candidate index and model',
            'Delete candidate telemetry immediately so it cannot affect production dashboards',
            'Wait for the rollout to reach 100% to confirm that the threshold remains exceeded',
          ],
          'The evaluated release unit is the complete configuration, not one guessed component. Returning traffic to the last known-good manifest limits harm and avoids an untested hybrid, while retained evidence supports root-cause analysis and a controlled follow-up.',
          'hard',
        ),
        question(
          'A hosted provider silently updates the model behind a mutable "latest" alias. Which production control best limits this risk?',
          'Resolve aliases to an approved immutable provider version in the release manifest and alert if runtime identity differs',
          [
            'Record the alias only because providers guarantee identical behavior behind friendly names',
            'Pin the application dependency lockfile and assume that also pins hosted inference',
            'Increase temperature so output changes are harder to attribute to provider updates',
          ],
          'A local lockfile cannot freeze a remote model. Resolving and verifying the provider revision makes drift observable; if immutable versions are unavailable, the team needs contractual change notice, continuous probes, and an explicit risk decision.',
          'medium',
        ),
        question(
          'Two evaluation runs disagree after only a prompt change, but each run used a different judge model and dataset snapshot. What conclusion is defensible?',
          'No causal comparison is possible until the candidate and control are rerun with pinned evaluator and dataset versions',
          [
            'The prompt caused the difference because prompts dominate every AI evaluation',
            'The run with the newer judge is automatically more accurate',
            'Average the two scores because version differences cancel statistically',
          ],
          'Changing multiple evaluation inputs confounds attribution. Paired runs against the same cases, rubric, judge, and sampling configuration isolate the prompt effect and allow uncertainty to be estimated rather than guessed.',
          'hard',
        ),
        question(
          'A release gate uses an LLM judge and fails intermittently on unchanged artifacts. What is the best first remediation?',
          'Measure judge repeatability, pin its configuration, use a specific rubric, and send threshold-near or disputed cases to calibrated review',
          [
            'Rerun the build until a passing score appears and discard failed reports',
            'Lower every threshold enough that judge variance cannot block a release',
            'Replace all deterministic validation with additional calls to the same judge',
          ],
          'A noisy gate cannot support reliable promotion decisions. Repeatability tests, pinned settings, clear rubrics, deterministic checks where possible, and adjudication near decision boundaries reduce flakiness without silently accepting regressions.',
          'hard',
        ),
        question(
          'An urgent prompt hotfix restores refusal behavior but was edited directly in production. What should happen next?',
          'Capture it as a new immutable manifest, run the risk-prioritized regression suite, obtain the required approval, and reconcile production through the normal pipeline',
          [
            'Leave it untracked because emergency changes should never appear in version history',
            'Overwrite the previous prompt artifact so both releases share one identifier',
            'Wait for the next scheduled release and avoid evaluating the active hotfix',
          ],
          'Emergency action may be justified, but it must not create permanent configuration drift. Recording the exact change and rapidly running the most consequential checks restores provenance, auditability, and a reproducible deployment state.',
          'medium',
        ),
        question(
          'A team wants every failed quality gate to be overridable by the release author. Which exception design is safer?',
          'Require an independent risk owner, documented evidence, narrow scope, monitoring and rollback conditions, and an expiry',
          [
            'Allow a permanent override flag in the repository with no named approver',
            'Permit overrides only when the candidate has a lower token price',
            'Delete the failed cases after approval so the next build passes cleanly',
          ],
          'Some releases may need explicit risk acceptance, but the exception must remain accountable and temporary. Independent approval, bounded exposure, compensating controls, and expiry prevent an override from quietly becoming the new standard.',
          'hard',
        ),
        question(
          'A retrieval release changes the embedding model but reuses the old vector index. Why should deployment be blocked?',
          'Stored vectors and query vectors may no longer share a compatible space, so the manifest must reference a rebuilt and evaluated index',
          [
            'Embedding models affect generation temperature but never retrieval ranking',
            'Vector databases automatically translate every vector between arbitrary embedding spaces',
            'Only the source document filenames need to match between embedding versions',
          ],
          'Similarity is meaningful only when document and query vectors use compatible representations and preprocessing. Rebuilding, validating recall by slice, and switching the index atomically prevents a technically healthy deployment from returning irrelevant evidence.',
          'medium',
        ),
        question(
          'Which production signal is most useful for deciding whether an AI release should automatically stop, beyond ordinary HTTP errors?',
          'A version-attributed breach of a task-specific safety or quality proxy with enough volume to satisfy the rollout rule',
          [
            'The number of source files changed in the release commit',
            'A single unverified negative comment without request or version attribution',
            'The candidate model having a different marketing name from the control',
          ],
          'AI systems can return HTTP 200 while failing the user task or violating policy. A stop signal should connect an actionable behavioral measure to the candidate version, include sample and window rules, and coexist with latency, cost, and provider-health guardrails.',
          'hard',
        ),
        question(
          'A rollback restores the prior model but leaves a newly written conversation state that the old agent cannot parse. Which release practice would have prevented this?',
          'Use backward-compatible state evolution or dual-read migration and test rollback against state created by the candidate',
          [
            'Store conversation state only inside the model context so schemas never exist',
            'Delete all active conversations whenever a model version changes',
            'Assume rollback compatibility because both releases use JSON',
          ],
          'Rollback is an end-to-end capability, not merely an artifact switch. Compatibility tests must cover durable state, tool effects, caches, and indexes created during the rollout so the previous release can safely resume service.',
          'hard',
        ),
      ],
    },
    {
      id: 'efficient-resilient-inference',
      title: 'Operate efficient and resilient inference',
      masteryLevel: 'L2',
      frequency: 'core',
      questionTarget: 15,
      questions: [
        question(
          'A gateway routes simple classification and complex policy synthesis. Which routing contract is most defensible?',
          'Route by declared task, risk, context, tool, quality, latency, and data-boundary requirements, then record the chosen immutable route',
          [
            'Send every request to the cheapest model until a user complains',
            'Choose a provider randomly without considering capability or data residency',
            'Let each client embed long-lived provider credentials and select arbitrary models',
          ],
          'Routing is a policy decision constrained by capability and consequence. An explicit contract supports predictable fallbacks, cost attribution, and audit, while immutable route identity makes incidents reproducible.',
          'medium',
        ),
        question(
          'The primary model times out after 2.8 seconds, leaving 700 ms in the end-to-end latency budget. When is a fallback model appropriate?',
          'Only when it can finish within the remaining budget and satisfies the task schema, safety, privacy, and minimum quality contract',
          [
            'Whenever it is hosted by a different provider, regardless of remaining latency',
            'Only after retrying the primary model without an attempt limit',
            'Whenever it produces fluent text, even if required tool calls are unsupported',
          ],
          'A fallback is useful only if it preserves bounded utility. Compatibility includes more than API shape: it must honor policy, data location, tools, output validation, and the remaining time budget rather than extending an outage into a slow incorrect answer.',
          'hard',
        ),
        question(
          'A safety classifier rejects a high-risk transaction. Should the gateway route around it to a provider with a less strict policy?',
          'No; hard safety and authorization failures should fail closed rather than use availability fallback',
          [
            'Yes, because every rejection is equivalent to a transient provider outage',
            'Yes, if the alternative model has a larger context window',
            'Yes, after removing the policy decision from the trace',
          ],
          'Fallback must not weaken the invariant that protects users or the business. Transient transport failures may justify compatible rerouting, but policy denials, failed authorization, or unsafe input require a controlled refusal or human path.',
          'medium',
        ),
        question(
          'An interactive service receives 30 requests per second. Each request averages 1,200 input tokens and 300 output tokens. What sustained token throughput should capacity planning start from before headroom?',
          'About 45,000 total tokens per second, separated into prompt and generation demand for benchmarking',
          [
            'About 1,500 total tokens per second because request rate does not affect token load',
            'About 36,000 total tokens per second because output tokens consume no serving capacity',
            'About 450,000 total tokens per second because every token must be multiplied by ten',
          ],
          'Each request processes about 1,500 tokens, and 30 multiplied by 1,500 is 45,000 tokens per second. Real sizing must separately benchmark prefill and decoding, then add burst, retry, and safety headroom.',
          'medium',
        ),
        question(
          'A hosted model charges $3 per million input tokens and $12 per million output tokens. A feature uses 80 million input and 20 million output tokens monthly. What is the model charge before other costs?',
          'About $480 per month',
          [
            'About $300 per month',
            'About $960 per month',
            'About $4,800 per month',
          ],
          'Input costs are 80 multiplied by $3, or $240. Output costs are 20 multiplied by $12, also $240, for a $480 total before retries, embeddings, retrieval, evaluation, networking, and platform charges.',
          'medium',
        ),
        question(
          'A team cuts maximum output from 800 to 300 tokens and sees cost fall but task completion also drop. What is the strongest next step?',
          'Measure required answer length by task and enforce task-specific limits with concise schemas rather than one global cap',
          [
            'Restore unlimited output for every task because token controls always harm quality',
            'Keep the lower cap and remove task-completion monitoring from the dashboard',
            'Increase prompt length until total token consumption returns to its previous level',
          ],
          'Token limits should follow the response contract. Classification may need a few tokens while a cited analysis needs more; per-task budgets and structured outputs reduce waste without truncating valid work.',
          'hard',
        ),
        question(
          'Which cache key is sufficient for a public documentation answer that may vary by locale and release?',
          'Normalized question plus locale, model, prompt, policy, corpus snapshot, retrieval settings, and generation settings',
          [
            'The raw question alone across every tenant, locale, and model version',
            'The user IP address without any content or artifact versions',
            'The model name alone because prompts and documents cannot affect an answer',
          ],
          'A valid key must include every factor that can change the permitted meaning of the response. Immutable versions make invalidation tractable and prevent a fast cache hit from silently serving obsolete or incompatible content.',
          'hard',
        ),
        question(
          'An entitlement assistant has many semantically similar questions but depends on live account state. What caching strategy is safest?',
          'Cache reusable public retrieval or prompt-prefix work, but bypass final-answer caching and read authorized account state on each request',
          [
            'Use semantic response caching across customers because their wording is similar',
            'Cache each final answer forever under the product name only',
            'Remove account authorization from the cache key to improve hit rate',
          ],
          'Semantic similarity does not prove equivalent permissions or current state. Reusing non-sensitive deterministic work can save cost, while the consequential personalized answer must remain tied to fresh, authorized data.',
          'hard',
        ),
        question(
          'A model call has 400 ms retrieval, 2.2 s time to first token, and 1.4 s generation, against a 3 s P95 SLO. Which optimization should be investigated first?',
          'Reduce the dominant model-start path through routing, prompt-prefix reuse, warm capacity, or a faster compatible model',
          [
            'Optimize retrieval from 400 ms to zero and assume the remaining 3.6 seconds meets the SLO',
            'Add an unbounded retry after 3 seconds to improve observed availability',
            'Increase maximum output tokens so generation occupies a larger share of latency',
          ],
          'The measured path is roughly four seconds, and time to first token is the largest component. Optimization should target the dominant span while preserving quality, then remeasure the end-to-end percentile under representative load.',
          'medium',
        ),
        question(
          'Why can aggressive continuous batching improve throughput while worsening an interactive chat SLO?',
          'Waiting to form or schedule larger batches can increase queueing and time to first token for individual requests',
          [
            'Batching makes every model output deterministic regardless of sampling',
            'Batching removes all accelerator memory limits by combining sequences',
            'Batching prevents prompt tokens from being processed by the model',
          ],
          'Batching amortizes compute and raises utilization, but users experience queue delay before generation starts. Batch policy should be tuned by workload class, with interactive latency protected from throughput-oriented batch jobs.',
          'medium',
        ),
        question(
          'A tenant exhausts its monthly token allowance halfway through a request whose maximum completion could exceed the remaining budget. Where should enforcement occur?',
          'At admission using reserved maximum cost, followed by reconciliation to actual usage and an explicit reduced or rejected response',
          [
            'After generation, because pre-request enforcement cannot prevent overspend',
            'Only in a monthly finance report after all provider charges settle',
            'Inside the prompt as a suggestion that the model should spend fewer tokens',
          ],
          'Admission control can reject or shrink work before cost is incurred. Reserving against the declared maximum prevents concurrent requests from oversubscribing the budget, while reconciliation returns unused allowance based on actual tokens.',
          'hard',
        ),
        question(
          'A sixfold burst fills the inference queue, and queued requests already exceed their client deadlines. What is the best overload behavior?',
          'Apply bounded priority queues, stop admitting work that cannot meet its deadline, and return a retryable or declared degraded response',
          [
            'Keep every request in an unbounded queue so none are visibly rejected',
            'Launch unlimited concurrent model calls until the provider quota resets',
            'Retry every timed-out request immediately at the front of the same queue',
          ],
          'Once queue delay exceeds the useful deadline, accepting more work converts overload into expensive timeouts. Backpressure and load shedding preserve capacity for requests that can still succeed and make degraded behavior explicit.',
          'hard',
        ),
        question(
          'Interactive chat and overnight summarization share one model quota, and batch jobs starve chat. Which control addresses the root cause?',
          'Partition quota and concurrency by workload class, reserve interactive capacity, and schedule batch work from its own bounded queue',
          [
            'Raise the chat timeout until all batch jobs finish',
            'Mix both workloads in one FIFO queue and remove priority metadata',
            'Disable chat monitoring so starvation no longer pages the team',
          ],
          'The workloads have different deadlines and business value. Separate budgets and queues prevent bulk throughput work from consuming latency-sensitive capacity, while still allowing deliberate borrowing when policy permits.',
          'medium',
        ),
        question(
          'Which telemetry set best explains why one AI release became slower and more expensive?',
          'Manifest-attributed traces with route, cache outcome, prompt and completion tokens, queue delay, retrieval spans, model latency, retries, tools, validation, and final outcome',
          [
            'Host CPU averaged across all services with no request or release identifier',
            'HTTP status totals without token, route, latency-span, or task-success data',
            'A monthly provider invoice containing no tenant, feature, or version attribution',
          ],
          'AI cost and latency emerge across the full request path. Versioned causal traces connect changes in routing, cache misses, token length, retries, and tool behavior to user outcomes while supporting aggregation by tenant and feature.',
          'hard',
        ),
        question(
          'A provider starts returning rate-limit responses. Which retry policy avoids amplifying the incident?',
          'Honor retry hints, use exponential backoff with jitter and a strict attempt budget, trip a circuit breaker, and admit only compatible fallback traffic',
          [
            'Retry immediately in a tight loop from every application instance',
            'Increase parallelism on each rate-limit response until one call succeeds',
            'Queue retries without deadlines or a maximum depth',
          ],
          'Coordinated immediate retries create a thundering herd and consume the same constrained quota. Jittered bounded retries, circuit breaking, and admission control reduce pressure; fallback remains conditional on capability and policy compatibility.',
          'hard',
        ),
      ],
    },
  ],
)

export const aiSystemDesignMasteryTopics = defineLearningMasteryTopics(
  'ai-engineering-core',
  'ai-system-design',
  [
    {
      id: 'requirements-and-architecture',
      title: 'Frame and structure an AI system',
      masteryLevel: 'L2',
      frequency: 'core',
      questionTarget: 20,
      questions: [
        question(
          'An interviewer asks you to design an AI support agent. What should you establish before choosing a model or vector database?',
          'The user job, autonomy boundary, quality and safety criteria, latency and availability SLOs, workload, data constraints, and budget',
          [
            'The largest context-window model currently advertised',
            'The vector database with the highest benchmark score regardless of corpus size',
            'The number of microservices shown in a reference architecture',
          ],
          'Architecture choices follow from measurable outcomes and constraints. Whether the system drafts a reply or issues a refund changes identity, approval, evaluation, reliability, and audit requirements before any product selection is credible.',
          'easy',
        ),
        question(
          'A customer says the assistant must be "accurate and fast." Which reformulation is most useful for design?',
          'At peak load, 95% of eligible questions receive a cited correct answer within three seconds, with explicit abstention and critical-slice thresholds',
          [
            'Use a state-of-the-art model and optimize it as much as possible',
            'Return every response quickly even when no evidence is available',
            'Measure one average quality score and one average latency after launch',
          ],
          'The reformulation names the workload condition, percentile, success event, evidence requirement, and failure behavior. Those details permit latency budgeting, capacity planning, evaluation, and tradeoff discussion.',
          'medium',
        ),
        question(
          'Which request path assigns responsibilities correctly for a multi-tenant RAG assistant with tools?',
          'Authenticate at the edge, authorize tenant-scoped retrieval and each tool server-side, assemble bounded evidence, invoke the model, validate the response, then emit an attributable trace',
          [
            'Let the model infer the tenant from conversation text and pass its choice to every dependency',
            'Retrieve across all tenants, generate an answer, and remove unauthorized citations afterward',
            'Give the browser provider credentials so it can call the model and tools directly',
          ],
          'Identity and authorization must be enforced before data or side effects cross a boundary. The model can propose behavior but cannot be the authority; validation and end-to-end tracing complete the controlled response path.',
          'hard',
        ),
        question(
          'A user asks an HR assistant for the current vacation balance and the company carryover policy. Which integration is appropriate?',
          'Retrieve the versioned policy as evidence and call an authorized HR tool for that user\'s live balance',
          [
            'Embed every employee balance nightly and treat the vector index as the source of truth',
            'Ask the model to estimate both answers from common workplace practices',
            'Use a write-capable payroll tool for both facts without checking user identity',
          ],
          'Retrieval suits governed document evidence, while a tool suits current structured state. The application must bind the tool call to the authenticated employee and cite the policy version used for the explanatory portion.',
          'medium',
        ),
        question(
          'A refund agent proposes calling issue_refund with an account ID supplied in the conversation. Where must authorization occur?',
          'In deterministic application or tool code using the authenticated principal, target resource, amount, and workflow state',
          [
            'Only in the system prompt because the model follows high-priority instructions',
            'In a generated explanation after the refund has already been issued',
            'In the vector database because similarity search establishes ownership',
          ],
          'Model-generated arguments are untrusted input. Server-side policy must bind identity to the resource and action, enforce limits and approvals, and log the decision before any side effect occurs.',
          'easy',
        ),
        question(
          'A design uses an agent for a fixed three-step extraction, validation, and database-write workflow. What should a senior engineer challenge?',
          'Whether deterministic orchestration with one bounded model step would be simpler, cheaper, and easier to test',
          [
            'Whether the agent can be given more tools to make the fixed workflow less predictable',
            'Whether every step can be hidden inside one unconstrained natural-language prompt',
            'Whether validation can be removed because the agent can reason about its own output',
          ],
          'Dynamic planning is justified only when the task requires it. A fixed workflow benefits from explicit states, typed contracts, idempotent effects, and narrow model use, reducing cost and failure modes without sacrificing useful AI capability.',
          'medium',
        ),
        question(
          'A legal research assistant needs high-quality analysis, a 12-second latency target, regional data residency, and no external retention. How should model selection begin?',
          'Evaluate approved models within the residency and retention boundary on representative legal tasks, then compare quality, latency, context, and cost',
          [
            'Choose the globally highest-scoring public model even if its data terms violate the boundary',
            'Choose the cheapest model first and treat legal quality as a post-launch metric',
            'Choose solely by parameter count because larger models always satisfy domain requirements',
          ],
          'Compliance constraints eliminate invalid options before benchmark comparison. Among feasible models, task-specific evidence and operational measurements support a defensible tradeoff rather than relying on generic rankings.',
          'hard',
        ),
        question(
          'A corpus contains product codes such as ZX-481 and natural-language troubleshooting descriptions. Which retrieval design is strongest?',
          'Use hybrid lexical and vector retrieval with metadata filters, then evaluate whether reranking improves the final candidate set',
          [
            'Use embeddings alone because semantic models always preserve exact identifiers',
            'Use lexical search alone because descriptions never require semantic matching',
            'Send the entire unfiltered corpus to the generator on every request',
          ],
          'Lexical search preserves exact rare terms while vectors capture paraphrases. Metadata filtering enforces scope and reduces noise, and reranking is justified only if measured relevance gains repay its latency and cost.',
          'medium',
        ),
        question(
          'A 200-page policy manual is chunked into arbitrary 200-token windows, and answers omit exceptions located beneath section headings. What is the best first redesign?',
          'Chunk by document structure, retain heading and parent context metadata, use measured overlap, and evaluate retrieval on exception questions',
          [
            'Increase generation temperature so the model invents likely exceptions',
            'Remove headings during ingestion because metadata increases index size',
            'Create one vector for the entire manual regardless of embedding input limits',
          ],
          'Chunk boundaries should preserve the units needed to answer real questions. Structural chunks with lineage make retrieval and citation coherent; an evaluation slice confirms whether the change actually restores the missing evidence.',
          'hard',
        ),
        question(
          'When is HNSW a defensible vector-index choice over a heavily compressed disk-oriented index?',
          'When the corpus and memory budget permit it and measured low-latency high-recall queries justify the larger memory footprint',
          [
            'Whenever exact nearest-neighbor results are legally mandatory because HNSW is exact',
            'Whenever memory is severely constrained because graph indexes require no resident structure',
            'Whenever the embedding model changes because HNSW avoids rebuilding vectors',
          ],
          'HNSW commonly offers strong interactive recall and latency at a memory and build-cost premium. Index selection should follow measured corpus size, update rate, filter behavior, recall target, and infrastructure constraints.',
          'hard',
        ),
        question(
          'A global assistant serves tenant documents in the US and EU under separate residency rules. What boundary is most defensible?',
          'Keep tenant data, indexes, logs, caches, and approved inference routes in the tenant\'s region, with region-aware identity and control-plane policy',
          [
            'Store vectors globally because embeddings can never reveal source information',
            'Centralize raw traces in one unrestricted region and delete only visible text fields',
            'Let the model choose a region from the user\'s prompt on each request',
          ],
          'Residency applies to derived data and operational copies as well as source documents. Region-aware routing and scoped observability prevent retrieval, inference, cache, or trace paths from bypassing the declared boundary.',
          'hard',
        ),
        question(
          'A shared vector collection filters by tenant ID supplied by the client. What additional control is essential?',
          'Derive tenant scope from the authenticated principal and enforce it in the retrieval service or storage policy, with cross-tenant tests',
          [
            'Trust the client field because vector search is read-only',
            'Ask the model to remove results that appear to belong to another tenant',
            'Hash tenant names while allowing queries to omit the tenant filter',
          ],
          'A caller-controlled filter is not authorization. The trusted service must bind identity to allowed partitions before search, and adversarial tests should prove that malformed queries and cache paths cannot cross tenant boundaries.',
          'medium',
        ),
        question(
          'Retrieved web content instructs an agent to upload secrets to an external URL. Which design contains the attack?',
          'Treat retrieved text as untrusted data, keep tool allowlists and authorization in code, restrict egress, and require approval for sensitive actions',
          [
            'Place the retrieved instruction after the system prompt so the model can decide whether it is safe',
            'Give the agent broader credentials so legitimate uploads are less likely to fail',
            'Remove output validation because the dangerous step occurs inside a tool',
          ],
          'Prompt hierarchy alone cannot enforce a security boundary. Least-privilege tools, server-side policy, network controls, and human approval limit what a compromised model decision can actually access or change.',
          'hard',
        ),
        question(
          'A medical assistant has insufficient evidence for a dosage question. What response contract is safest?',
          'Abstain clearly, state the evidence limitation, provide approved next steps, and avoid invoking action tools',
          [
            'Generate the most statistically likely dosage and add a generic disclaimer',
            'Retry with higher temperature until the model supplies a confident answer',
            'Return an old cached answer from a different patient with similar wording',
          ],
          'For high-consequence tasks, unsupported fluency is worse than reduced availability. The response layer should validate evidence and confidence conditions, fail closed, and direct the user to an accountable clinical path.',
          'medium',
        ),
        question(
          'The generation provider is unavailable, but retrieval remains healthy for a low-risk knowledge assistant. Which degradation preserves useful service?',
          'Return clearly labeled ranked sources or extracted passages with citations and omit unsupported synthesis',
          [
            'Return a fabricated summary so the interface remains visually unchanged',
            'Retry generation indefinitely while holding the user connection open',
            'Use stale cross-tenant answers from the response cache',
          ],
          'A retrieval-only mode can preserve evidence access without pretending that generation succeeded. The user-visible contract must disclose reduced capability, and authorization plus source freshness still apply.',
          'medium',
        ),
        question(
          'An agent may create a ticket and then times out before recording success. What reliability property is required before retrying?',
          'An idempotency key and durable operation state that can reconcile whether the external effect already occurred',
          [
            'A longer natural-language rationale from the model before every retry',
            'A different ticket title so the second attempt is distinguishable to the user',
            'A cache entry that assumes every timeout means the tool did nothing',
          ],
          'A timeout creates an unknown outcome, not proof of failure. Idempotency and reconciliation prevent duplicate side effects and allow the workflow to resume from durable state rather than relying on model memory.',
          'hard',
        ),
        question(
          'Which observability design supports both incident diagnosis and privacy for an AI request?',
          'Trace each boundary with request and manifest IDs, timing, token and outcome metadata, while redacting payloads and applying scoped access and retention',
          [
            'Store every raw prompt, secret, retrieved record, and tool credential indefinitely for all engineers',
            'Record only a global request count because detailed spans always violate privacy',
            'Log final model text without the retrieval, tool, policy, or version path',
          ],
          'Operators need causal metadata to locate slow, expensive, or unsafe behavior, but full payload capture can create a second sensitive-data store. Redaction, minimization, access control, sampling, and retention balance diagnostic value with exposure.',
          'medium',
        ),
        question(
          'A design promises 99.9% availability but requires three independent sequential dependencies, each at 99.9%. What should the review flag?',
          'The end-to-end path is about 99.7% available before other failures, so optional dependencies need bypasses or stronger budgets',
          [
            'The end-to-end path remains exactly 99.9% because dependency availability is inherited',
            'The end-to-end path becomes 99.9999999% because multiple services add redundancy',
            'Availability cannot be estimated until model token prices are known',
          ],
          'For mandatory independent hops, approximate path availability is the product: 0.999 cubed is about 0.997. The design must allocate realistic budgets, remove unnecessary synchronous dependencies, or define safe degradation.',
          'hard',
        ),
        question(
          'A response validator confirms JSON syntax but not whether cited evidence supports each claim. What architectural gap remains?',
          'Semantic and grounding validation tied to retrieved evidence, with abstention or review when support is insufficient',
          [
            'A larger HTTP response buffer because unsupported claims are caused by truncation',
            'A second JSON parser using the same schema and no evidence access',
            'A higher sampling temperature so citations vary across attempts',
          ],
          'Structural validity proves only that downstream code can parse the response. The product contract may also require supported claims, allowed actions, policy compliance, and citations that resolve to authorized source versions.',
          'hard',
        ),
        question(
          'A team proposes storing complete customer prompts indefinitely to improve future models. What is the strongest design response?',
          'Minimize collection, establish purpose and consent, classify and redact data, define retention and deletion, restrict access, and test whether safer samples meet the need',
          [
            'Accept the plan because model improvement automatically overrides privacy obligations',
            'Encrypt the data once and treat indefinite unrestricted retention as risk-free',
            'Replace customer IDs with sequential numbers while retaining every secret and message',
          ],
          'Training value does not remove privacy, contractual, or security obligations. Purpose limitation and data minimization reduce blast radius, while deletion coverage must include traces, caches, datasets, embeddings, and derived artifacts.',
          'hard',
        ),
      ],
    },
    {
      id: 'capacity-evaluation-and-rollout',
      title: 'Size, evaluate, and evolve an AI system',
      masteryLevel: 'L2',
      frequency: 'core',
      questionTarget: 20,
      questions: [
        question(
          'A copilot serves 240,000 requests per day with a peak factor of six over the daily average. What peak request rate should the first capacity model use before headroom?',
          'About 17 requests per second',
          [
            'About 3 requests per second',
            'About 100 requests per second',
            'About 1,440 requests per second',
          ],
          'The daily average is 240,000 divided by 86,400, or about 2.78 requests per second. Multiplying by six gives about 16.7 requests per second, after which retry, growth, and failure headroom should be added explicitly.',
          'medium',
        ),
        question(
          'At peak, 20 requests per second each use 2,000 input tokens and 500 output tokens. What token rates must the serving plan support before headroom?',
          'About 40,000 input tokens per second and 10,000 output tokens per second',
          [
            'About 2,000 input tokens per second and 500 output tokens per second',
            'About 50,000 input tokens per second and no output-token capacity',
            'About 400,000 input tokens per second and 100,000 output tokens per second',
          ],
          'Multiplying request rate by per-request lengths gives the separate prefill and decode demand. They should remain separate because hardware throughput, latency, batching, and provider quotas often differ for input and generated tokens.',
          'medium',
        ),
        question(
          'An endpoint sustains eight concurrent requests per replica at the required latency. Peak arrival is 12 requests per second and average service time is four seconds. What is the minimum replica estimate before headroom?',
          'Six replicas, because roughly 48 requests are concurrent and each replica safely handles eight',
          [
            'Two replicas, because only request arrival rate matters',
            'Four replicas, because service time should be subtracted from arrival rate',
            'Ninety-six replicas, because concurrency must be multiplied by per-replica capacity',
          ],
          'Arrival rate multiplied by service time gives about 12 times 4, or 48 concurrent requests. Dividing by eight safe concurrent requests per replica gives six, before adding failure tolerance, warm-up, burst, and growth capacity.',
          'hard',
        ),
        question(
          'A monthly workload has 60 million input tokens at $2 per million and 15 million output tokens at $8 per million. What inference cost should be budgeted before retries and other services?',
          'About $240 per month',
          [
            'About $135 per month',
            'About $600 per month',
            'About $2,400 per month',
          ],
          'Input costs $120 and output costs $120, totaling $240. A complete estimate then adds retry amplification, embeddings, reranking, storage, observability, evaluation, networking, and minimum provisioned capacity.',
          'medium',
        ),
        question(
          'A RAG service indexes 10 million chunks with 1,536 float32 dimensions. Approximately how much raw vector storage is required before index overhead, metadata, and replicas?',
          'About 61 GB',
          [
            'About 6 GB',
            'About 614 GB',
            'About 15 TB',
          ],
          'Each vector uses 1,536 multiplied by 4, or 6,144 bytes. Across 10 million chunks that is about 61.4 billion bytes, or roughly 61 GB decimal; the operational footprint can be much larger after graph structures, metadata, and replication.',
          'hard',
        ),
        question(
          'A document service ingests 2 million documents averaging 12 chunks each, then keeps two index replicas. How many stored chunk copies should capacity planning include?',
          'About 48 million chunk copies',
          [
            'About 12 million chunk copies',
            'About 24 million chunk copies',
            'About 96 million chunk copies',
          ],
          'The primary index contains 2 million multiplied by 12, or 24 million chunks. Two full replicas store about 48 million chunk copies before temporary rebuild indexes, backups, and metadata.',
          'medium',
        ),
        question(
          'A three-second end-to-end P95 budget allocates 150 ms to the edge, 350 ms to retrieval, 200 ms to validation, and 300 ms to safety margin. What remains for model queueing and inference?',
          'About 2,000 ms',
          [
            'About 2,300 ms',
            'About 2,700 ms',
            'About 3,000 ms',
          ],
          'The non-model allocations total 1,000 ms, leaving 2,000 ms. The model budget must include queue delay, time to first token, and completion time measured under the same peak-load and percentile assumptions.',
          'medium',
        ),
        question(
          'A provider quota is 600 requests per minute, while the product peak is 14 requests per second. What does the design need?',
          'At least 840 requests per minute of peak capacity, so it needs a quota increase, compatible routing, admission control, or reduced demand plus headroom',
          [
            'No change because 14 is numerically less than 600',
            'Exactly 600 requests per second because minute quotas convert directly to seconds',
            'Only a larger response cache after requests have already reached the provider',
          ],
          'Fourteen requests per second is 840 per minute, already above the quota before retries or growth. Capacity planning must use consistent units and define overload behavior rather than discovering the limit during a burst.',
          'easy',
        ),
        question(
          'Which evaluation dataset best supports a production launch decision for a multilingual finance assistant?',
          'Versioned representative cases with expected evidence and outcomes, critical language and risk slices, adversarial cases, provenance, and a protected holdout',
          [
            'A random set of English trivia questions with no finance or tool behavior',
            'Only examples the prompt author used while tuning the candidate',
            'Production thumbs-up responses without negative cases or selection-bias analysis',
          ],
          'Launch evidence must reflect intended users, consequential failures, and system boundaries. Provenance and holdouts reduce leakage and overfitting, while slice reporting prevents an acceptable aggregate from hiding a dangerous cohort failure.',
          'medium',
        ),
        question(
          'RAG answers are ungrounded because the needed policy section is rarely retrieved. Which metric and intervention should come first?',
          'Measure context recall and inspect failed queries, then adjust chunking, filters, query construction, or retrieval before tuning generation',
          [
            'Increase generator temperature because retrieval misses indicate insufficient creativity',
            'Measure only answer fluency and replace citations with model-generated URLs',
            'Add more output tokens while leaving the candidate evidence unchanged',
          ],
          'Generation cannot cite evidence it never receives. Separating retrieval recall from faithfulness localizes the fault and directs changes to the ingestion or search path instead of masking it with prompt tuning.',
          'medium',
        ),
        question(
          'Retrieval finds the correct policy, but the answer invents an exception absent from the context. Which evaluation dimension isolates the failure?',
          'Faithfulness or claim-level groundedness against the retrieved evidence',
          [
            'Vector index build duration',
            'Document ingestion throughput',
            'Provider request availability',
          ],
          'The evidence is present, so retrieval recall is not the primary issue. Claim-level support checks whether generation stays within the supplied sources and supports targeted prompt, model, or validation changes.',
          'easy',
        ),
        question(
          'An LLM judge prefers the first of two answers regardless of content. How should the evaluation be corrected?',
          'Randomize answer order, measure position bias against human-reviewed cases, and calibrate or replace the judge before gating',
          [
            'Always place the candidate first so the bias helps detect improvements',
            'Increase the judge temperature and assume bias disappears',
            'Hide pairwise failures and retain only the average preferred-answer rate',
          ],
          'Judge models are measurement instruments that require validation. Counterbalancing order exposes positional bias, and comparison with accountable human labels shows whether the rubric and judge are reliable enough for the decision.',
          'hard',
        ),
        question(
          'Offline task success improves from 81% to 83% on 100 cases. What should be checked before claiming a real improvement?',
          'Use paired case outcomes and uncertainty analysis, inspect slice effects, and run more representative cases if the interval includes no meaningful difference',
          [
            'Declare success because any positive point estimate is conclusive',
            'Duplicate the two improved cases until the aggregate increase is larger',
            'Ignore case pairing and compare only the rounded percentages',
          ],
          'A two-point change on a small sample may be noise or concentrated in one slice. Paired analysis uses the same cases for both systems, while confidence intervals and practical-effect thresholds prevent overclaiming.',
          'hard',
        ),
        question(
          'A customer-facing copilot will be A/B tested. Which primary outcome is stronger than thumbs-up rate alone?',
          'Verified task resolution or accepted work product, with safety, latency, cost, escalation, and critical-slice guardrails',
          [
            'The number of generated tokens because longer answers imply greater user value',
            'Provider HTTP success rate without checking whether the user task was completed',
            'Thumbs-up rate only, with users who give no feedback counted as successes',
          ],
          'Explicit feedback is selective and can reward style over correctness. A verified downstream outcome better represents value, while guardrails ensure the experiment does not buy that value through unsafe, slow, or unaffordable behavior.',
          'medium',
        ),
        question(
          'A new agent is ready for production after offline evaluation. Which rollout sequence is most defensible?',
          'Shadow with side effects disabled, canary low-risk sticky cohorts, expand in measured stages, and keep automatic rollback tied to the full manifest',
          [
            'Enable autonomous actions for all tenants at once because offline tests already passed',
            'Canary high-risk transactions first because they provide stronger failure signals',
            'Randomly switch versions within active workflows and share caches between them',
          ],
          'Progressive exposure discovers integration and distribution failures while limiting harm. Risk-based eligibility, sticky assignment, isolated state, minimum samples, and complete-manifest rollback make the evidence attributable and recovery practical.',
          'hard',
        ),
        question(
          'During rollout, p95 latency is stable but cost per resolved ticket doubles. Which action is strongest?',
          'Pause expansion and inspect version-attributed tokens, retries, cache misses, retrieval, and tool loops before changing the rollout decision',
          [
            'Continue because latency proves the release meets every operational requirement',
            'Remove cost telemetry so finance sees only the monthly aggregate',
            'Reduce the safety-evaluation sample until average cost returns to baseline',
          ],
          'Unit economics are a production quality constraint. Stable latency can hide extra model calls or longer contexts, so tracing cost per successful outcome identifies whether the candidate is viable and where optimization belongs.',
          'hard',
        ),
        question(
          'A model outage affects generation, but deterministic account lookup and document search remain available. How should the availability SLO treat a declared search-only response?',
          'According to the pre-agreed success definition for degraded mode, tracked separately from full-service success',
          [
            'Always as full success because any HTTP 200 response satisfies an AI SLO',
            'Always as total failure even if users explicitly value the documented degraded result',
            'Exclude the entire outage window so availability remains unchanged',
          ],
          'An SLO needs a user-centered success event decided before incidents. Separating full and degraded success keeps reporting honest while allowing a useful fallback to count according to its agreed product value.',
          'hard',
        ),
        question(
          'One tenant sends 55% of traffic to a shared AI service and raises latency for everyone. Which design addresses fairness?',
          'Enforce per-tenant token, concurrency, and queue budgets with weighted scheduling and explicit burst policy',
          [
            'Use one global FIFO queue and let the largest tenant consume capacity first',
            'Hide tenant identity from telemetry so all traffic appears equivalent',
            'Give every tenant unlimited retries during overload',
          ],
          'Request counts alone miss the large variation in token and tool cost. Tenant-aware admission and scheduling contain noisy neighbors, make commercial limits enforceable, and preserve a declared service floor for other tenants.',
          'medium',
        ),
        question(
          'A privacy deletion request covers a user whose content appears in source documents, vector indexes, traces, caches, and evaluation samples. What does complete deletion require?',
          'A lineage-aware workflow that removes or tombstones every governed copy and derived artifact, rebuilds affected indexes, and records verifiable completion',
          [
            'Delete the chat row in the primary database and assume derived systems update themselves',
            'Remove the user name from the interface while retaining unrestricted embeddings and traces',
            'Delete only model outputs because input data is never subject to retention rules',
          ],
          'AI systems replicate data across operational and evaluation paths. Provenance and lineage make those copies discoverable; deletion must respect legal holds while preventing stale indexes, backups, or caches from silently resurfacing governed content.',
          'hard',
        ),
        question(
          'A design review has covered components, capacity, security, and offline quality. What final operating plan is still necessary?',
          'Named SLOs and owners, dashboards and alerts, runbooks, versioned traces, incident and rollback procedures, drift review, and evaluation refresh',
          [
            'A promise that the model provider will resolve every application incident',
            'A diagram frozen at launch with no ownership or response thresholds',
            'A plan to inspect aggregate user feedback once per year',
          ],
          'Production readiness includes how the system will be understood and changed after launch. Ownership, actionable signals, rehearsed recovery, and continuous evaluation convert architecture from a static diagram into an operable service.',
          'medium',
        ),
      ],
    },
  ],
)