import {
  defineLearningMasteryTopics,
  type LearningMasteryQuestionSeed,
  type LearningPlatform,
  type LearningQuestionDifficulty,
} from './learning-model'

const allPlatforms = ['Turing', 'Andela', 'Toptal'] as const

function question(
  prompt: string,
  correctOption: string,
  distractors: readonly [string, string, string],
  explanation: string,
  difficulty: LearningQuestionDifficulty,
  platforms: readonly LearningPlatform[] = allPlatforms,
): LearningMasteryQuestionSeed {
  return {
    prompt,
    options: [correctOption, ...distractors],
    correctOptionIndex: 0,
    explanation,
    difficulty,
    platforms,
  }
}

export const ragMasteryTopics = defineLearningMasteryTopics(
  'ai-engineering-core',
  'rag',
  [
    {
      id: 'ingestion-and-indexing',
      title: 'Ingestion and indexing',
      masteryLevel: 'L2',
      frequency: 'core',
      questionTarget: 20,
      questions: [
        question(
          'A policy PDF contains headings, paragraphs, and tables whose rows depend on their column headers. What should the parser preserve for reliable RAG ingestion?',
          'Reading order, section hierarchy, and table structure together with the extracted text',
          [
            'Only the alphabetically sorted words from every page',
            'Only page screenshots without any machine-readable text',
            'The document title and total byte size but none of its internal structure',
          ],
          'Retrieval quality depends on preserving the relationships that give text meaning. Reading order and structural boundaries let later chunking keep headings with paragraphs and table values with their labels.',
          'medium',
        ),
        question(
          'An ingestion job extracts almost no text from scanned contracts even though the pages are visibly readable. What is the best next step?',
          'Detect image-only pages, run OCR, and validate the resulting text with confidence or quality checks',
          [
            'Embed the empty parser output because the vector model can infer the page contents',
            'Increase retrieval top-k until the missing contract language appears',
            'Replace every scanned page with the document file name',
          ],
          'A conventional text parser cannot recover characters that exist only as pixels. OCR is required, and quality checks are important because low-confidence recognition can silently corrupt names, numbers, and clauses.',
          'easy',
        ),
        question(
          'Repeated navigation menus and page footers dominate the nearest chunks for every query. Which ingestion change addresses the root cause?',
          'Remove repeated boilerplate while preserving meaningful headings, negations, identifiers, and body text',
          [
            'Delete every line that appears in more than one document',
            'Raise the generation temperature so the model ignores repetitive context',
            'Store each footer as a separate high-priority chunk',
          ],
          'Boilerplate creates nearly identical vectors and crowds out useful evidence. Cleaning should target known layout noise without broadly deleting repeated language that may carry policy meaning.',
          'medium',
        ),
        question(
          'A retry of the nightly ingestion pipeline creates duplicate chunks for unchanged documents. Which design makes ingestion safely repeatable?',
          'Use stable source and chunk identities plus content hashes to upsert unchanged material idempotently',
          [
            'Generate a new random chunk identifier on every retry',
            'Append every retry and rely on the language model to ignore duplicates',
            'Disable retries so duplicate records can never be written',
          ],
          'Stable identities and hashes let the pipeline recognize unchanged content, update changed chunks, and retry after partial failures without multiplying index entries.',
          'hard',
        ),
        question(
          'A handbook is organized into short sections, and many answers depend on the section heading. What is the strongest initial chunking strategy?',
          'Split on semantic section boundaries and carry the heading into each resulting chunk',
          [
            'Split at an arbitrary byte count without regard to character encoding',
            'Create one vector for the entire handbook regardless of its length',
            'Make every sentence an isolated chunk and discard all headings',
          ],
          'Structure-aware chunks are more likely to contain a coherent answer and its scope. Carrying the heading preserves context that may not be repeated in each paragraph.',
          'easy',
        ),
        question(
          'A 2,500-token document is split into chunks of at most 800 tokens with 100 tokens of overlap. Ignoring semantic-boundary adjustments, how many chunks are needed?',
          '4 chunks',
          [
            '3 chunks',
            '5 chunks',
            '8 chunks',
          ],
          'The effective stride is 800 minus 100, or 700 tokens. Chunks begin near tokens 0, 700, 1,400, and 2,100, so the fourth chunk contains the remaining content.',
          'medium',
        ),
        question(
          'What is the main tradeoff when chunk overlap is increased substantially?',
          'Boundary-spanning facts are less likely to be lost, but index size, embedding cost, and duplicate retrieval increase',
          [
            'Retrieval becomes exact while storage use always decreases',
            'Documents become fresher because overlapping chunks update themselves',
            'Authorization metadata is no longer needed on repeated text',
          ],
          'Overlap can preserve context across a split, but repeated tokens create more vectors and can fill top-k with near-duplicates. It should be tuned against measured retrieval gains and cost.',
          'medium',
        ),
        question(
          'Small chunks retrieve precisely, but the generator needs a larger surrounding section to interpret each hit. Which design best serves both needs?',
          'Index small child chunks for matching, then expand selected hits to their authorized parent sections',
          [
            'Embed only whole documents and return every document in full',
            'Concatenate the entire corpus after retrieving the first child chunk',
            'Discard child text and generate from metadata field names alone',
          ],
          'Parent-child retrieval separates the granularity used for matching from the granularity used for generation. Parent expansion must retain access checks and a bounded context budget.',
          'hard',
        ),
        question(
          'Which metadata is most useful for making an indexed chunk traceable and governable?',
          'Stable source ID, source version, section or page location, timestamps, and access-control attributes',
          [
            'Only the embedding vector length and no source reference',
            'Only the worker hostname that processed the document',
            'A random display color and the number of vowels in the chunk',
          ],
          'Provenance supports citations, updates, deletion, debugging, and authorization. Operational details can be logged separately, but they do not replace source and policy metadata.',
          'easy',
        ),
        question(
          'Documents were embedded with one model, but queries are now embedded with an unrelated model. Retrieval quality collapses. Why?',
          'The query and document vectors no longer share a compatible learned space',
          [
            'Vector databases require query text and documents to have equal character counts',
            'Every embedding model assigns identical meanings to different dimensions',
            'Query vectors can be compared only with other queries, never with documents',
          ],
          'Vector coordinates have meaning only within the representation learned by a compatible model setup. Switching one side independently makes similarity scores largely meaningless.',
          'medium',
        ),
        question(
          'A team changes from a 768-dimensional embedding model to a 1,536-dimensional model. What migration is required?',
          'Create a compatible index or vector field, re-embed the corpus, validate retrieval, and then cut traffic over',
          [
            'Pad only new query vectors with zeroes and keep every old document vector unchanged',
            'Rename the existing vector field because dimensions are inferred at query time',
            'Change the generator prompt without modifying the retrieval index',
          ],
          'The dimensions and learned space are both incompatible. A staged rebuild allows quality comparison and rollback while avoiding a mixed index that cannot be searched coherently.',
          'hard',
        ),
        question(
          'A support corpus and its queries span English, Spanish, and Japanese. How should the embedding model be selected?',
          'Evaluate multilingual candidates on representative query-document pairs from every important language and domain slice',
          [
            'Choose the model with the largest dimension without testing retrieval',
            'Translate only the document titles and assume body-text behavior is unchanged',
            'Select any English-only model because vector search removes language differences automatically',
          ],
          'Model suitability is empirical. A multilingual benchmark built from the actual domain reveals cross-language and within-language retrieval quality that model size alone cannot guarantee.',
          'medium',
        ),
        question(
          'A product already uses PostgreSQL, has 80,000 chunks, and expects modest query traffic. Which first vector-storage decision is most defensible?',
          'Benchmark a supported PostgreSQL vector extension before adding a separate vector database',
          [
            'Adopt a distributed vector database immediately because relational systems cannot store vectors',
            'Store vectors in log files and scan them in the application process',
            'Create one database server per document to guarantee isolation',
          ],
          'At this scale, the existing operational boundary may satisfy latency, filtering, and recall requirements with less complexity. A dedicated service is justified by measured scale or feature needs, not by category alone.',
          'hard',
        ),
        question(
          'Approximately how much raw storage do one million 1,536-dimensional float32 vectors require before index and metadata overhead?',
          'About 6.1 GB',
          [
            'About 0.6 GB',
            'About 61 GB',
            'About 614 GB',
          ],
          'Each float32 value uses 4 bytes, so 1,000,000 times 1,536 times 4 is 6,144,000,000 bytes, or about 6.1 GB in decimal units. The search index can add substantial overhead.',
          'medium',
        ),
        question(
          'An embedding API is rate-limited, and a million-document backfill often stops midway. Which pipeline design is most robust?',
          'Process bounded batches with checkpoints, idempotent writes, retry backoff, and a dead-letter path for persistent failures',
          [
            'Send every chunk in one request and restart the full corpus after any error',
            'Ignore failed batches so the job can report success quickly',
            'Run unlimited parallel workers without recording which chunks completed',
          ],
          'Checkpointed, idempotent batches bound the cost of retries and allow controlled throughput. Persistent failures remain visible for repair instead of silently creating holes in the index.',
          'hard',
        ),
        question(
          'A policy document is revised, but searches sometimes return chunks from both the old and new versions. What indexing behavior should be implemented?',
          'Publish the new version as a consistent set and retire all chunks belonging to the prior active version',
          [
            'Keep every version equally active and ask the model to guess which one applies',
            'Update only the first changed chunk because vector similarity will suppress the rest',
            'Delete the source document before parsing the replacement and accept an unbounded outage',
          ],
          'Version-aware publication prevents a partially updated document from becoming visible. Retiring the old version avoids contradictory evidence while retaining audit history outside active retrieval if required.',
          'hard',
        ),
        question(
          'A customer invokes a valid deletion request for a source document. What must the RAG system remove or invalidate?',
          'The source, derived text and chunks, vectors, caches, and any other retrievable replicas covered by the policy',
          [
            'Only the source-system hyperlink shown in citations',
            'Only the document title while retaining searchable body vectors indefinitely',
            'Nothing, because embeddings cannot reveal information about deleted text',
          ],
          'Deletion must follow the data lineage created during ingestion. Removing only the visible source leaves derived representations available for retrieval and can violate privacy or retention obligations.',
          'medium',
        ),
        question(
          'A parser occasionally emits empty text, broken character encoding, or a thousand-page chunk. How should ingestion handle these records?',
          'Validate outputs against explicit quality limits, quarantine failures, and expose them in ingestion metrics',
          [
            'Index every output so corpus row counts remain stable',
            'Replace malformed content with a generated summary that has no source evidence',
            'Hide the records from logs and retry them on every user query',
          ],
          'Boundary validation prevents bad parser output from contaminating retrieval. Quarantine plus observable failure reasons supports repair without claiming that incomplete material was indexed successfully.',
          'medium',
        ),
        question(
          'Evaluation shows that answers often require two sentences separated by a chunk boundary, and neither retrieved chunk contains the complete fact. What should be tested first?',
          'Structure-aware boundaries or a modest increase in chunk size or overlap, measured against retrieval quality and cost',
          [
            'A higher generation temperature with the same incomplete evidence',
            'Removing every chunk boundary and always sending the full corpus',
            'Sorting chunks alphabetically before embedding them',
          ],
          'The failure originates in how evidence is segmented. Boundary-aware splitting, larger chunks, or overlap may restore the complete unit, but each option should be evaluated for precision and context cost.',
          'hard',
        ),
        question(
          'The team must reproduce old indexes after changing parsers and embedding models. Which ingestion artifact makes this feasible?',
          'A versioned manifest linking immutable source versions to parser, cleaner, chunker, and embedding configurations',
          [
            'A dashboard screenshot showing the latest vector count',
            'The current prompt text without any ingestion configuration',
            'A mutable folder that always overwrites prior source files in place',
          ],
          'A lineage manifest records exactly which inputs and transformations produced an index. It enables deterministic rebuilds, comparison between versions, rollback, and targeted deletion.',
          'hard',
        ),
      ],
    },
    {
      id: 'retrieval-and-context',
      title: 'Retrieval and context construction',
      masteryLevel: 'L2',
      frequency: 'core',
      questionTarget: 20,
      questions: [
        question(
          'Document and query embeddings are all normalized to unit length. How do cosine similarity and dot-product ranking compare?',
          'They produce the same ranking because vector magnitudes are all one',
          [
            'Cosine ranks only exact keyword matches while dot product ranks semantic matches',
            'Dot product always reverses the cosine ranking',
            'Cosine cannot be computed for normalized vectors',
          ],
          'For unit vectors, the cosine denominator is one, so cosine similarity equals the dot product. The implementation should still use the metric recommended and tested for the embedding model.',
          'medium',
        ),
        question(
          'An embedding model was trained so vector magnitude carries confidence information. Which similarity decision deserves explicit validation?',
          'Whether dot product should preserve magnitude instead of normalizing vectors for cosine similarity',
          [
            'Whether BM25 can replace all vector arithmetic without changing behavior',
            'Whether vector dimensions should be sorted before every comparison',
            'Whether Euclidean distance should compare only the first coordinate',
          ],
          'Normalization removes magnitude information. When training made magnitude meaningful, dot product may be appropriate, but the choice should follow model guidance and retrieval evaluation rather than convention.',
          'hard',
        ),
        question(
          'Exact vector search misses the latency target on 50 million chunks. What is the soundest architecture change?',
          'Use an approximate nearest-neighbor index and tune it against measured recall and latency',
          [
            'Return a random sample because all semantic neighbors are interchangeable',
            'Remove the latency target and scan every vector for every request',
            'Search only the newest chunk regardless of the query',
          ],
          'ANN avoids exhaustive comparison and is the standard scale tradeoff. It can miss true neighbors, so index and query parameters must be chosen with a recall benchmark and service-level latency target.',
          'medium',
        ),
        question(
          'What usually happens when the HNSW search parameter controlling exploration is increased at query time?',
          'Recall generally improves while query latency and compute increase',
          [
            'Recall and latency both necessarily fall to zero',
            'Index construction becomes cheaper without affecting queries',
            'All metadata filters become unnecessary',
          ],
          'Exploring more graph candidates makes it more likely that search reaches the true nearest neighbors, but requires more distance computations. The useful setting is workload-specific.',
          'medium',
        ),
        question(
          'A team increases the HNSW graph connectivity parameter substantially. Which tradeoff should it expect?',
          'Potentially better recall, with more memory use and slower index construction',
          [
            'Guaranteed exact search with a smaller graph',
            'Lower vector dimensionality without re-embedding',
            'Automatic removal of stale source versions',
          ],
          'More graph links offer additional routes to nearby vectors, which can improve navigability and recall. Those links consume memory and take additional work to build and maintain.',
          'hard',
        ),
        question(
          'A frequently updated HNSW index accumulates many deleted and replaced vectors, and latency degrades. What should operations consider?',
          'Monitor tombstones and index health, then rebuild or compact according to the database behavior',
          [
            'Increase generation temperature to repair the graph',
            'Duplicate every deleted vector so graph connectivity remains constant',
            'Disable source updates permanently after the initial index build',
          ],
          'Deletion handling varies by vector store, and logical tombstones can leave inefficient structures. Monitoring plus planned compaction or rebuilds maintains predictable recall, memory, and latency.',
          'hard',
        ),
        question(
          'Users search for exact error code `ZX-491`, but semantic retrieval returns conceptually related troubleshooting pages that omit the code. Which retrieval method should be added?',
          'BM25 or another lexical search that rewards exact token matches',
          [
            'A larger text-generation model with no lexical index',
            'Random chunk selection weighted by document length',
            'Image OCR applied again at query time to every indexed document',
          ],
          'Sparse lexical retrieval is strong for rare identifiers, names, and exact phrases. BM25 complements embeddings, which can place semantically related text near the query without preserving a literal code.',
          'easy',
        ),
        question(
          'A user asks about “ending a subscription,” while the policy consistently says “account cancellation.” Which retriever is most likely to bridge that wording difference?',
          'A compatible embedding-based semantic retriever',
          [
            'An exact-match filter requiring every query token',
            'A date-range index with no text representation',
            'A checksum lookup over the complete query string',
          ],
          'Embeddings can place paraphrases near one another based on learned meaning. Lexical matching remains valuable for exact terms, but may miss this vocabulary mismatch on its own.',
          'easy',
        ),
        question(
          'A knowledge base contains both natural-language policies and exact product SKUs. Which retrieval architecture is strongest?',
          'Run lexical and vector retrieval, fuse their candidates, and validate the combined ranking',
          [
            'Use only vector search because exact identifiers never matter',
            'Use only BM25 because semantic paraphrases never matter',
            'Alternate randomly between lexical and vector search per request',
          ],
          'Hybrid retrieval combines complementary signals: sparse search captures literal terms while dense search captures semantic similarity. Evaluation determines fusion weights or rank strategy.',
          'medium',
        ),
        question(
          'BM25 scores and vector similarity scores have incompatible numeric scales across queries. Why is reciprocal rank fusion useful?',
          'It combines result positions without requiring raw scores to be directly calibrated',
          [
            'It converts every sparse vector into the same dense embedding',
            'It guarantees that the first lexical result always wins',
            'It removes duplicate source versions from the ingestion pipeline',
          ],
          'Reciprocal rank fusion gives decreasing credit based on rank in each result list. This avoids treating unlike raw scoring systems as though their values had the same meaning.',
          'hard',
        ),
        question(
          'A query is limited to tenant A, French content, and currently active policies. Where should those constraints be applied?',
          'As enforced metadata filters during candidate retrieval, using fields stored on every chunk',
          [
            'Only in a sentence asking the generator not to mention other tenants',
            'After displaying the generated answer to the user',
            'Only when the nearest vector score is below zero',
          ],
          'Known constraints should narrow the searchable candidate set before evidence reaches generation. This improves relevance and makes authorization part of retrieval rather than a prompt-level request.',
          'medium',
        ),
        question(
          'Why is retrieving globally and removing unauthorized chunks only after top-k unsafe and ineffective for tenant isolation?',
          'Sensitive candidates may enter downstream processing, and authorized results may be crowded out before filtering',
          [
            'Post-filtering changes float32 vectors into text automatically',
            'Global retrieval always returns documents in chronological order',
            'Tenant identifiers cannot be represented as metadata',
          ],
          'Authorization must be enforced before or within retrieval and repeated at access boundaries. Late filtering risks leakage through logs or prompts and can leave too few useful results because forbidden chunks consumed top-k.',
          'hard',
        ),
        question(
          'What is the likely effect of raising retrieval top-k from 5 to 50 without changing later stages?',
          'Recall may rise, but latency, reranking cost, and irrelevant or duplicate context may also rise',
          [
            'Precision must rise because every additional result is relevant',
            'The embedding model is retrained automatically on the extra results',
            'The source corpus becomes smaller because more chunks are returned',
          ],
          'A larger candidate set can recover evidence missed near the cutoff, but it also admits weaker matches. Top-k should be tuned with retrieval metrics and the downstream context budget.',
          'medium',
        ),
        question(
          'A low-cost retriever can fetch 100 candidates quickly, but only 8 chunks fit the generation budget. What pipeline is most appropriate?',
          'Retrieve broadly, rerank the candidates with a stronger model, and send the best diverse evidence that fits',
          [
            'Send the first 8 candidates in database insertion order',
            'Concatenate all 100 chunks and silently exceed the model context limit',
            'Generate an answer before retrieval and use candidates only for decoration',
          ],
          'Two-stage retrieval spends expensive relevance computation on a bounded candidate set. Selection should also remove redundant chunks so the final context covers more of the information need.',
          'medium',
        ),
        question(
          'Why can a cross-encoder reranker be more accurate but slower than a bi-encoder retriever?',
          'It jointly scores each query-document pair, so document representations cannot all be precomputed independently',
          [
            'It compares only document dates and ignores query text',
            'It requires every document to have exactly one token',
            'It searches no candidates and therefore evaluates the entire internet',
          ],
          'A cross-encoder lets attention model detailed interactions between the query and each candidate. That improves relevance estimates but costs an inference pass per pair, making it suitable for reranking rather than first-stage search.',
          'hard',
        ),
        question(
          'The top results contain three overlapping chunks from one paragraph and omit a second relevant section. How should context construction improve?',
          'Deduplicate or merge neighboring hits and select diverse evidence while retaining source provenance',
          [
            'Repeat the highest-scoring paragraph until the token budget is full',
            'Strip all source identifiers so repeated text cannot be detected',
            'Sort every chunk by character count and ignore relevance',
          ],
          'Near-duplicate hits waste context capacity and can overemphasize one fact. Merging adjacent text and selecting diverse evidence improves coverage while provenance keeps citations traceable.',
          'medium',
        ),
        question(
          'A model has an 8,000-token context limit. Instructions, conversation, and answer reserve 2,000 tokens, and each selected chunk averages 750 tokens. What is the maximum whole number of average chunks that fit?',
          '8 chunks',
          [
            '6 chunks',
            '10 chunks',
            '13 chunks',
          ],
          'The evidence budget is 8,000 minus 2,000, or 6,000 tokens. Dividing by 750 gives 8, before allowing any additional separator or citation overhead.',
          'easy',
        ),
        question(
          'A query rewriter expands “SLA for ZX-491 in EU” into a generic support question and retrieval quality falls. What should the rewrite stage preserve?',
          'Exact identifiers, user intent, and structured constraints such as region while adding only useful semantic variants',
          [
            'Only common words so the query matches as many chunks as possible',
            'The answer from the previous user even when the current subject changes',
            'A random region to make the query more specific',
          ],
          'Rewriting should improve recall without deleting high-value lexical terms or filters. Comparing original and rewritten retrieval on representative queries detects destructive expansions.',
          'hard',
        ),
        question(
          'A policy was updated in the index, but users still receive an old answer from a semantic response cache. What freshness design is needed?',
          'Include source or index version in cache validity and invalidate entries affected by changed evidence',
          [
            'Increase ANN exploration so cached text is searched more thoroughly',
            'Keep cached answers forever because generation already occurred',
            'Remove timestamps from documents to prevent version disagreement',
          ],
          'Fresh retrieval cannot repair an answer returned before retrieval runs. Version-aware keys or dependency-based invalidation connect response-cache lifetime to the evidence from which an answer was produced.',
          'hard',
        ),
        question(
          'Logs show that the correct policy chunk is ranked first, yet answers repeatedly add unsupported exceptions. What should be investigated first?',
          'Generation instructions, context use, and faithfulness behavior rather than only increasing retrieval top-k',
          [
            'The document parser, because the correct evidence was never indexed',
            'HNSW recall, because the correct chunk was not retrieved',
            'BM25 tokenization, because rank one proves an exact-code failure',
          ],
          'The retrieval stage supplied the required evidence, so the observed failure is downstream. Grounding instructions, conflicting context, model behavior, and answer validation are more direct diagnostic targets.',
          'hard',
        ),
      ],
    },
  ],
)

export const ragEvaluationMasteryTopics = defineLearningMasteryTopics(
  'ai-engineering-core',
  'rag-evaluation',
  [
    {
      id: 'retrieval-evaluation',
      title: 'Retrieval evaluation',
      masteryLevel: 'L2',
      frequency: 'core',
      questionTarget: 15,
      questions: [
        question(
          'What should a useful golden dataset for RAG retrieval contain beyond a list of user questions?',
          'Expected supporting evidence or relevance labels, metadata and access expectations, and meaningful evaluation slices',
          [
            'Only model-generated answers with no source review',
            'Only the shortest queries that the current retriever already handles',
            'Production document counts without any question-level judgments',
          ],
          'Retrieval cannot be scored without knowing which evidence should be found. Metadata, authorization, and slices make failures diagnosable across use cases instead of reducing evaluation to one opaque average.',
          'easy',
        ),
        question(
          'How should evaluation queries be sampled for a customer support RAG system?',
          'Represent common, rare, ambiguous, multilingual, no-answer, and permission-sensitive production cases',
          [
            'Use only synthetic questions whose wording exactly matches document headings',
            'Evaluate only the ten most frequent queries and ignore tail behavior',
            'Select queries after seeing which ones the candidate system answers correctly',
          ],
          'A representative dataset exposes the operating distribution and important risks. Convenient or post-selected examples inflate scores and hide failures in rare or protected slices.',
          'medium',
        ),
        question(
          'Three of the top five retrieved chunks are labeled relevant. What is precision at 5?',
          '0.60',
          [
            '0.40',
            '0.75',
            '1.67',
          ],
          'Precision at k is the number of relevant results among the k returned results. Here it is 3 divided by 5, which equals 0.60.',
          'easy',
        ),
        question(
          'A question has four known relevant chunks, and retrieval finds three of them in its top five. What is recall at 5?',
          '0.75',
          [
            '0.60',
            '0.80',
            '1.25',
          ],
          'Recall at k divides relevant items retrieved by all known relevant items. Three found out of four known relevant chunks gives 3 divided by 4, or 0.75.',
          'easy',
        ),
        question(
          'At k=5 a retriever finds 3 of 5 relevant chunks. At k=10 it finds 4 of those 5. How do precision and recall change?',
          'Precision falls from 0.60 to 0.40, while recall rises from 0.60 to 0.80',
          [
            'Precision rises from 0.60 to 0.80, while recall falls from 0.60 to 0.40',
            'Both precision and recall become 0.90',
            'Precision remains 0.60 and recall remains 0.60',
          ],
          'At k=10, four of ten returned chunks are relevant, so precision is 0.40. Four of five known relevant chunks were found, so recall is 0.80; larger k often creates this tradeoff.',
          'medium',
        ),
        question(
          'For three queries, the first relevant result appears at ranks 1, 2, and 4. What is the mean reciprocal rank?',
          'Approximately 0.58',
          [
            'Approximately 0.33',
            'Approximately 0.75',
            'Approximately 2.33',
          ],
          'MRR averages reciprocal ranks: (1/1 + 1/2 + 1/4) divided by 3 equals 1.75 divided by 3, or about 0.58. It rewards placing the first useful result early.',
          'medium',
        ),
        question(
          'Which ranking measure is especially useful when relevance is graded, such as highly relevant, partially relevant, and irrelevant?',
          'Normalized discounted cumulative gain, because it rewards graded relevance near the top of the ranking',
          [
            'Document count, because it ignores ordering and relevance labels',
            'Mean response length, because longer answers imply better retrieval',
            'Index build time, because it directly measures ranking quality',
          ],
          'NDCG discounts gains at lower ranks and supports multiple relevance levels, then normalizes against the ideal ordering. This captures ranking quality beyond the first relevant result.',
          'hard',
        ),
        question(
          'Context recall is low for questions whose answers span policy exceptions, while context precision is acceptable. What is the most likely next investigation?',
          'Whether chunking, query expansion, filters, or candidate depth are omitting required evidence',
          [
            'Whether the generator font size is too small',
            'Whether irrelevant chunks should be added to make context longer',
            'Whether every retrieved score should be rounded to an integer',
          ],
          'Low context recall means necessary evidence is absent from the retrieved context. The diagnostic path is therefore segmentation and retrieval coverage, not answer style or adding unrelated material.',
          'medium',
        ),
        question(
          'The required evidence is almost always retrieved, but most supplied chunks are unrelated and distract the generator. Which metric exposes this failure?',
          'Context precision',
          [
            'Context recall alone',
            'Indexing throughput',
            'Embedding vector dimension',
          ],
          'Context precision measures how much retrieved context is relevant. It can be poor even when recall is high, signaling a need for better ranking, filtering, deduplication, or a smaller final k.',
          'easy',
        ),
        question(
          'What does context relevance evaluate in a RAG test case?',
          'Whether the supplied passages directly help satisfy the information need expressed by the query',
          [
            'Whether every passage has the same token count',
            'Whether the final answer uses sophisticated vocabulary',
            'Whether index construction completed before midnight',
          ],
          'Context relevance connects retrieved evidence to the actual question. It identifies passages that are topically similar yet do not support the requested fact or decision.',
          'medium',
        ),
        question(
          'Why must a retrieval benchmark include questions that have no answer in the authorized corpus?',
          'To measure whether retrieval and the application can avoid presenting weak or unauthorized material as evidence',
          [
            'To make recall automatically equal one for every system',
            'To eliminate the need for abstention behavior',
            'To ensure every no-answer query retrieves the longest document',
          ],
          'Real users ask unsupported questions. No-answer cases test score thresholds, abstention, and false-positive retrieval instead of rewarding a system for always returning something.',
          'hard',
        ),
        question(
          'A retriever has strong average relevance but returns another tenant\'s relevant document in one test. How should that result be treated?',
          'As a critical isolation failure governed by a zero-tolerance security check, not averaged away',
          [
            'As a successful retrieval because the document answered the question',
            'As harmless if mean reciprocal rank remains above target',
            'As a generation issue that does not involve retrieval controls',
          ],
          'Authorization is a hard constraint rather than a relevance preference. Aggregate quality metrics cannot compensate for cross-tenant disclosure, so dedicated negative tests must gate release.',
          'hard',
        ),
        question(
          'Two retrieval configurations are being compared, but the generator is stochastic and changes between runs. How can retrieval quality be isolated?',
          'Score ranked chunks against fixed relevance labels while holding the query set, corpus version, and filters constant',
          [
            'Compare only the prose style of one generated answer from each system',
            'Change the corpus and embedding model simultaneously for every run',
            'Use generation latency as the only proxy for retrieval relevance',
          ],
          'Direct retrieval metrics remove generation variance from the comparison. Fixed inputs and labels let observed differences be attributed to the retriever configuration.',
          'medium',
        ),
        question(
          'A lexical retriever scores well because benchmark distractors are obviously unrelated. What addition would make the benchmark more discriminating?',
          'Hard negatives that share terminology with the query but do not contain the required answer',
          [
            'More duplicate copies of each relevant chunk',
            'Empty documents that no retriever could reasonably rank',
            'Queries copied verbatim from the answer sentence',
          ],
          'Hard negatives test whether ranking distinguishes true evidence from merely similar language. Easy random negatives can produce optimistic precision without representing production confusion.',
          'hard',
        ),
        question(
          'A new embedding model improves overall recall but reduces recall for Japanese queries from 0.82 to 0.61. What is the strongest release policy?',
          'Gate on agreed per-slice thresholds and investigate or route the regressed slice before release',
          [
            'Release solely because the global average improved',
            'Remove Japanese examples so the benchmark remains stable',
            'Replace recall with document count for that slice',
          ],
          'Aggregate gains can conceal material regressions for a user group. Versioned slice thresholds make the quality contract explicit and direct remediation to the failing segment.',
          'hard',
        ),
      ],
    },
    {
      id: 'answer-and-system-evaluation',
      title: 'Answer and system evaluation',
      masteryLevel: 'L2',
      frequency: 'frequent',
      questionTarget: 10,
      questions: [
        question(
          'What does faithfulness or groundedness measure for a generated RAG answer?',
          'Whether the answer\'s factual claims are supported by the supplied context',
          [
            'Whether the answer repeats every retrieved passage verbatim',
            'Whether the answer is longer than the user question',
            'Whether the retriever used an approximate index',
          ],
          'A faithful answer may summarize or synthesize, but each factual claim must be entailed by the evidence provided to the model. Correct-looking unsupported additions still fail this metric.',
          'easy',
        ),
        question(
          'An answer accurately summarizes a retrieved policy but never states the deadline the user asked for. Which quality dimension is weakest?',
          'Answer relevance',
          [
            'Embedding dimensionality',
            'Index freshness',
            'Parser throughput',
          ],
          'The response may be grounded yet fail to satisfy the information need. Answer relevance evaluates whether the response directly addresses the user request, not merely whether its statements are supported.',
          'easy',
        ),
        question(
          'The context says refunds are available within 30 days, but the answer claims premium members have 60 days with no supporting source. How should this be classified?',
          'A hallucinated, ungrounded claim',
          [
            'A retrieval recall success because a refund passage was present',
            'A harmless paraphrase of the 30-day rule',
            'A latency regression caused by reranking',
          ],
          'The premium exception is a factual addition not entailed by retrieved evidence. The presence of some relevant context does not make every generated claim faithful.',
          'medium',
        ),
        question(
          'In an evaluation of 200 answers, 18 contain at least one unsupported factual claim. What is the answer-level faithfulness pass rate?',
          '91%',
          [
            '9%',
            '82%',
            '109%',
          ],
          'There are 182 passing answers out of 200. Dividing 182 by 200 gives 0.91, or 91%; claim-level scoring may reveal additional detail hidden by this answer-level rate.',
          'easy',
        ),
        question(
          'A policy changes from 30 to 45 days, making several reference answers obsolete. How should the golden dataset be maintained?',
          'Version examples with the source policy, update affected labels through review, and retain history for reproducibility',
          [
            'Keep old references forever and classify every correct new answer as a regression',
            'Delete the entire evaluation suite whenever one source changes',
            'Let the candidate model silently rewrite references during scoring',
          ],
          'Golden data is governed data, not timeless truth. Linking cases to source versions supports auditable updates while preserving the ability to reproduce prior evaluation results.',
          'medium',
        ),
        question(
          'Which changes should trigger the RAG regression suite before release?',
          'Parser, chunking, embeddings, index settings, retrieval, reranking, prompt, model, and relevant source changes',
          [
            'Only user-interface color changes, never retrieval or model changes',
            'Only generator upgrades because ingestion cannot affect answers',
            'Only changes that reduce the number of source documents',
          ],
          'RAG behavior is an end-to-end product of data, retrieval, and generation. A change in any stage can alter evidence or answers, so stable component and end-to-end checks should run together.',
          'medium',
        ),
        question(
          'Before using an LLM judge as the primary groundedness scorer, what validation is most important?',
          'Compare it with rubric-based human labels, inspect disagreements, and test order, style, and self-preference bias',
          [
            'Assume a larger judge is perfectly objective and skip human review',
            'Give the judge only the answer and hide the supporting context',
            'Use a different rubric for every candidate so scores cannot be compared',
          ],
          'Model judges can be useful at scale but inherit systematic biases. Calibration against reviewed examples and stable rubrics establishes whether the score tracks the quality claim it is meant to represent.',
          'hard',
        ),
        question(
          'Retrieval takes 120 ms, reranking 180 ms, generation 900 ms, and other work 100 ms at P95. Against a 1.5-second P95 budget, how much headroom remains?',
          '200 ms',
          [
            '100 ms',
            '300 ms',
            '1,300 ms',
          ],
          'The sequential stages total 1,300 ms. Subtracting that from the 1,500 ms budget leaves 200 ms, assuming the percentile measurements can be combined appropriately for this estimate.',
          'medium',
        ),
        question(
          'A system serves 10,000 queries. Retrieval and reranking cost $0.004 per query, and generation costs $0.018 per query. What is the approximate total variable cost?',
          '$220',
          [
            '$22',
            '$180',
            '$2,200',
          ],
          'The per-query cost is $0.022. Multiplying by 10,000 gives $220, which can then be broken down by stage to identify the most valuable optimization.',
          'easy',
        ),
        question(
          'A new reranker improves grounded task success by two percentage points but breaches both the P95 latency SLO and per-query budget. What is the best architecture decision?',
          'Compare business value against the constraints and test a bounded cascade or smaller candidate set before deciding to ship',
          [
            'Ship it unconditionally because any offline quality gain dominates operational limits',
            'Reject all reranking permanently without testing cheaper configurations',
            'Hide latency and cost metrics from the release report so quality remains the only score',
          ],
          'Production evaluation is multi-objective. A cascade can reserve expensive reranking for uncertain queries, while candidate reduction or a smaller model may retain much of the gain within explicit latency and cost limits.',
          'hard',
        ),
      ],
    },
  ],
)