import {
  defineLearningMasteryTopics,
  type LearningMasteryQuestionSeed,
  type LearningPlatform,
  type LearningQuestionDifficulty,
} from './learning-model'

const allPlatforms = ['Turing', 'Andela', 'Toptal'] as const

function question(
  prompt: string,
  correctOption: string,
  distractors: readonly [string, string, string],
  explanation: string,
  difficulty: LearningQuestionDifficulty,
  platforms: readonly LearningPlatform[] = allPlatforms,
): LearningMasteryQuestionSeed {
  return {
    prompt,
    options: [correctOption, ...distractors],
    correctOptionIndex: 0,
    explanation,
    difficulty,
    platforms,
  }
}

export const systemDesignFundamentalsMasteryTopics = defineLearningMasteryTopics(
  'fde-system-delivery-core',
  'system-design-fundamentals',
  [
    {
      id: 'clarify-the-job',
      title: 'Clarify the job',
      masteryLevel: 'L2',
      frequency: 'core',
      questionTarget: 20,
      questions: [
        question(
          'A client asks for a scalable notification system. What should you establish before choosing a queue or database?',
          'The actors, main workflow, delivery guarantee, expected scale, and explicit exclusions',
          [
            'The cloud vendor and programming language',
            'The complete database schema and every future notification channel',
            'The number of microservices used by comparable companies',
          ],
          'Architecture choices follow from the job and constraints. Actors, workflow, guarantees, scale, and scope determine whether durable queues, ordering, or synchronous delivery are necessary.',
          'easy',
        ),
        question(
          'A retailer says its new inventory service must prevent overselling. Which statement is the strongest invariant?',
          'Confirmed reservations for an item must never exceed its sellable stock',
          [
            'Inventory pages should usually load quickly',
            'Every warehouse should use the same database engine',
            'The service should cache popular items during sales',
          ],
          'An invariant names a condition that must remain true. It is precise enough to guide concurrency and failure decisions without prescribing an implementation.',
          'easy',
        ),
        question(
          'Users upload videos that may take several minutes to process. Which clarification most directly determines whether the API should be asynchronous?',
          'Whether users need the finished video in the initial response or can track a processing job',
          [
            'Whether the team prefers REST or GraphQL',
            'Whether videos are stored under UUID file names',
            'Whether the worker is written in the same language as the API',
          ],
          'The required user-visible completion behavior determines the interaction model. Long work that can complete later should normally return a job identity instead of holding the request open.',
          'medium',
        ),
        question(
          'During discovery, two stakeholders use “real time” differently. What is the best next step?',
          'Ask for a concrete event, maximum acceptable delay, and consequence of missing that delay',
          [
            'Assume real time means under 100 milliseconds',
            'Design for the lowest latency technically possible',
            'Postpone latency discussion until production monitoring exists',
          ],
          'Terms such as real time are not measurable requirements. A scenario, threshold, and business consequence turn the phrase into a constraint the design can satisfy and test.',
          'medium',
        ),
        question(
          'A customer requests an “Uber-like” field-service platform. Which opening response shows the best system-design judgment?',
          'Identify the first user journey and ask which matching, tracking, payment, and safety outcomes are required',
          [
            'Copy the major components from a public ride-sharing architecture diagram',
            'Begin with global sharding because the reference product operates worldwide',
            'Select managed Kubernetes so every future service can scale',
          ],
          'A product analogy hides many possible jobs. Clarifying the first workflow and required outcomes prevents borrowing architecture built for constraints this customer may not have.',
          'medium',
        ),
        question(
          'Which item belongs in an explicit out-of-scope list for the first version of a flash-sale reservation service?',
          'Demand forecasting when the agreed job is only to reserve available stock during checkout',
          [
            'Reservation expiry behavior',
            'The rule that prevents confirmed reservations exceeding stock',
            'How checkout learns that a reservation failed',
          ],
          'Forecasting is adjacent but unnecessary to the stated reservation job. Expiry, the stock invariant, and failure communication are part of the core behavior and cannot be deferred safely.',
          'medium',
        ),
        question(
          'An interviewer gives no traffic numbers for a URL shortener. What should you do?',
          'State a reasonable workload assumption, explain which decision it affects, and invite correction',
          [
            'Refuse to continue until exact production metrics are supplied',
            'Assume internet scale and add every known scaling mechanism',
            'Ignore traffic because architecture should be independent of scale',
          ],
          'System-design interviews test reasoning under incomplete information. Explicit assumptions let the interviewer correct the model and make each later decision traceable.',
          'medium',
        ),
        question(
          'A payment request times out after reaching a provider. Which missing requirement creates the greatest correctness risk?',
          'Whether duplicate payment effects are allowed and how an unknown outcome is reconciled',
          [
            'Whether the endpoint path uses a plural noun',
            'Whether the provider dashboard uses the same currency symbol',
            'Whether application logs are retained for exactly one year',
          ],
          'A timeout does not prove that the provider did nothing. Duplicate-effect tolerance and reconciliation requirements determine the need for idempotency keys and a pending state.',
          'hard',
        ),
        question(
          'Which job statement is specific enough to guide an initial design?',
          'Allow a signed-in customer to submit one order and receive a durable order ID within two seconds, while fulfillment happens later',
          [
            'Build a modern and scalable commerce platform',
            'Use microservices to improve the shopping experience',
            'Create an order database with high performance',
          ],
          'The strong statement identifies the actor, action, observable result, timing boundary, and asynchronous work without prematurely selecting the architecture.',
          'easy',
        ),
        question(
          'When should clarification stop and design begin?',
          'When the core workflow, invariants, important constraints, assumptions, and first-version scope are clear enough to compare options',
          [
            'Only after every future feature and edge case has been decided',
            'As soon as a familiar architecture pattern comes to mind',
            'After the team has selected all cloud services and data stores',
          ],
          'Clarification should reduce decision-changing uncertainty, not eliminate every unknown. Remaining assumptions can be recorded and tested as the design evolves.',
          'hard',
        ),
        question(
          'A product team wants search results in under 100 ms while finance caps infrastructure at $2,000 per month. What should be clarified before proposing a design?',
          'Expected query volume, latency percentile, freshness needs, data size, and which target may move when the budget is exceeded',
          [
            'Only which search engine has the lowest advertised latency',
            'Only how many developers will implement the search page',
            'The final index schema before discussing traffic or freshness',
          ],
          'Performance, freshness, and cost constrain one another. Quantifying the workload and priority order exposes whether caching, delayed indexing, a managed service, or a relaxed target is appropriate.',
          'hard',
        ),
        question(
          'A healthcare intake service will collect symptoms and insurance information. Which discovery question can change the entire architecture?',
          'Who may access each data class, where it may be stored, how long it must be retained, and what consent or audit rules apply',
          [
            'Whether the form buttons should use icons or text',
            'Whether every field name should begin with the same prefix',
            'Whether the engineering team prefers classes or functions',
          ],
          'Sensitive-data classification, residency, retention, consent, and audit requirements affect boundaries, encryption, identity, deletion, and vendor selection before implementation details matter.',
          'hard',
        ),
        question(
          'A client asks to replace a nightly CSV export with a real-time integration. What should you establish first?',
          'Which business decision waits for the data, the maximum useful age, expected change volume, and behavior during disconnection',
          [
            'Which event-streaming product appears most often in architecture diagrams',
            'Whether CSV files can be renamed with a timestamp',
            'Whether both systems can be rewritten in the same language',
          ],
          'The consuming decision determines whether seconds, minutes, or hours are acceptable. Volume and outage behavior then determine whether CDC, events, polling, or improved batch transfer is justified.',
          'medium',
        ),
        question(
          'A customer requests active-active deployment in three regions on day one. Which response best tests whether that complexity is justified?',
          'Ask where users and regulated data reside, the cost of a regional outage, and the required recovery time and data-loss limit',
          [
            'Accept the request because more regions always improve every quality attribute',
            'Choose three regions based only on alphabetical order',
            'Delay all reliability discussion until after the first outage',
          ],
          'Multi-region operation adds consistency, routing, testing, and cost. User geography, residency, RTO, RPO, and outage impact reveal whether active-active, warm standby, or restore-from-backup is proportionate.',
          'hard',
        ),
        question(
          'A legacy order system must be replaced without stopping sales. Which requirement needs an explicit agreement before migration design?',
          'The cutover window, source of truth during transition, reconciliation rule, rollback trigger, and acceptable data lag',
          [
            'The naming convention for migration scripts',
            'The number of folders in the replacement repository',
            'The color used for the old system in diagrams',
          ],
          'A live migration can create two competing truths. Ownership, synchronization, reconciliation, rollback, and downtime constraints determine whether to use staged reads, dual writes, CDC, or a maintenance window.',
          'hard',
        ),
        question(
          'One tenant generates 70% of traffic in a shared analytics service. Which missing requirement matters most before scaling it?',
          'The isolation and fairness policy for per-tenant throughput, latency, quotas, and failure containment',
          [
            'Whether every tenant uses the same dashboard color',
            'Whether tenant names are sorted alphabetically',
            'Whether the busiest tenant has the shortest company name',
          ],
          'Aggregate capacity does not define multi-tenant behavior. Explicit fairness and isolation requirements guide quotas, partitioning, scheduling, and protection from noisy neighbors.',
          'medium',
        ),
        question(
          'An administrator can suspend 10,000 accounts in one action. Which clarification most affects the workflow design?',
          'Whether the action must be all-or-nothing or may report partial progress, resume safely, and produce an audit trail',
          [
            'Whether the confirmation dialog uses one or two buttons',
            'Whether account IDs contain uppercase letters',
            'Whether the operation is launched on a weekday',
          ],
          'Bulk operations need explicit atomicity, progress, retry, cancellation, and audit semantics. Those decisions determine whether one synchronous transaction or an asynchronous job is credible.',
          'hard',
        ),
        question(
          'A six-week launch plan contains twenty requested features. What is the strongest FDE response?',
          'Rank the smallest end-to-end user journey, its invariants and acceptance criteria, then name what will be deferred',
          [
            'Divide all features equally across the available days',
            'Build infrastructure for every possible future feature first',
            'Select the easiest features without checking whether they form a usable workflow',
          ],
          'A thin vertical outcome tests value and integration risk earlier than disconnected features. Explicit exclusions protect the deadline and make scope changes visible.',
          'medium',
        ),
        question(
          'A stakeholder says security alerts must never be missed. Which reformulation is most useful to engineering?',
          'Define qualifying events, detection coverage, delivery latency, durable retention, escalation, and acceptable false-positive and false-negative rates',
          [
            'Promise that no software defect or network outage can ever occur',
            'Send every application log line to every employee',
            'Choose the alerting vendor before defining what constitutes an alert',
          ],
          'Absolute language must become measurable detection and delivery behavior. Coverage, timeliness, retention, escalation, and error rates expose the controls and residual risk.',
          'hard',
        ),
        question(
          'A customer requests immediate deletion of chat history, while compliance requires retaining regulated conversations. What should happen next?',
          'Identify the governing data classes and authority, then agree deletion, legal hold, anonymization, audit, and user-visible semantics',
          [
            'Implement whichever request was made most recently',
            'Keep every record forever without telling users',
            'Delete the user-interface row while leaving unrestricted copies everywhere else',
          ],
          'Conflicting stakeholder statements cannot be solved by a storage choice. Data classification and accountable policy must distinguish deletable content, retained evidence, access restrictions, and truthful user communication.',
          'hard',
        ),
      ],
    },
    {
      id: 'quality-attributes',
      title: 'Name quality attributes',
      masteryLevel: 'L2',
      frequency: 'core',
      questionTarget: 20,
      questions: [
        question(
          'Which requirement is a measurable latency quality attribute?',
          'During normal peak load, 95% of checkout requests complete within 500 ms',
          [
            'Checkout should feel instant',
            'The checkout service should use a fast cache',
            'Users should rarely complain about checkout speed',
          ],
          'A useful quality attribute names the operation, operating condition, measured population, percentile, and target. It states the outcome without requiring a particular implementation.',
          'easy',
        ),
        question(
          'Why is average response time alone a weak latency target for an interactive API?',
          'A small number of very slow requests can be hidden by many fast requests',
          [
            'Average response time cannot be measured in production',
            'Averages are valid only for background jobs',
            'An average always equals the slowest request',
          ],
          'Users on the slow tail still experience poor service. Percentiles such as P95 or P99 reveal the latency below which a stated proportion of requests complete.',
          'easy',
        ),
        question(
          'A service has a 99.9% monthly availability target. Approximately how much unavailability does that allow in a 30-day month?',
          'About 43 minutes',
          [
            'About 4 minutes',
            'About 7 hours',
            'About 3 days',
          ],
          'A 30-day month has 43,200 minutes; 0.1% of that is 43.2 minutes. The exact measurement still needs a defined success event and exclusion policy.',
          'medium',
        ),
        question(
          'Which pair correctly describes disaster-recovery objectives?',
          'RTO limits acceptable recovery time; RPO limits acceptable data loss measured in time',
          [
            'RTO limits request latency; RPO limits requests per second',
            'RTO measures backup size; RPO measures restore cost',
            'RTO and RPO are two names for service availability',
          ],
          'Recovery Time Objective says how quickly service must return. Recovery Point Objective says how far back restored data may be, which drives backup or replication frequency.',
          'easy',
        ),
        question(
          'A recommendation service is optional to checkout. Which degradation requirement is strongest?',
          'If recommendations exceed 100 ms or fail, omit them and continue checkout while recording fallback use',
          [
            'Retry recommendations until one succeeds',
            'Return a generic 500 response whenever recommendations fail',
            'Keep the checkout request open while an operator investigates',
          ],
          'The requirement protects the critical checkout outcome, bounds waiting, defines fallback behavior, and makes degradation observable.',
          'medium',
        ),
        question(
          'Which change most clearly trades lower write latency for weaker durability?',
          'Acknowledging a write before it has reached durable replicated storage',
          [
            'Adding a read-only cache for catalog data',
            'Compressing static assets at build time',
            'Using cursor pagination for an event list',
          ],
          'Early acknowledgement can shorten the response path, but a failure before durable replication may lose a write the client believes succeeded.',
          'hard',
        ),
        question(
          'A team says every endpoint needs 99.999% availability. What should an FDE challenge first?',
          'Whether each workflow justifies the cost and complexity of that target',
          [
            'Whether five nines can be displayed on the status page',
            'Whether all endpoints can share one timeout value',
            'Whether the API is implemented with microservices',
          ],
          'Reliability targets should follow business impact. Applying an extreme target everywhere can multiply redundancy and operational cost without improving an important user outcome.',
          'medium',
        ),
        question(
          'Which metric directly measures throughput?',
          'Successfully processed orders per second',
          [
            'Milliseconds per order at P95',
            'Percentage of successful orders',
            'Gigabytes retained per month',
          ],
          'Throughput is completed work per unit of time. Latency measures time per operation, availability measures successful service, and retained bytes measure storage.',
          'easy',
        ),
        question(
          'Where should an end-user availability SLI usually be measured?',
          'At the boundary where the user-visible operation succeeds or fails',
          [
            'Only from whether the application process is running',
            'Only from database CPU utilization',
            'At whichever internal component reports the highest uptime',
          ],
          'A process can be alive while returning errors or incorrect responses. Measuring the complete user operation keeps the indicator aligned with delivered value.',
          'medium',
        ),
        question(
          'A product owner asks for low cost, zero downtime, strong consistency across regions, and instant writes. What is the best response?',
          'Explain the conflicts, rank the outcomes by business impact, and agree measurable targets',
          [
            'Promise all four and defer tradeoffs until implementation',
            'Select the most expensive database tier immediately',
            'Ignore cost because reliability is always more important',
          ],
          'Quality attributes compete. Strong cross-region coordination can increase latency and cost, so the design needs explicit priorities and acceptable degradation rather than absolute adjectives.',
          'hard',
        ),
        question(
          'An API handles 10 million requests in a month with a 99.9% successful-request SLO. What is its approximate monthly error budget?',
          '10,000 unsuccessful requests',
          [
            '1,000 unsuccessful requests',
            '100,000 unsuccessful requests',
            '999,000 unsuccessful requests',
          ],
          'A 99.9% success target permits 0.1% unsuccessful requests. Multiplying 10,000,000 by 0.001 gives an error budget of about 10,000 requests under the stated SLI.',
          'medium',
        ),
        question(
          'A checkout has a 500 ms P95 target. Gateway and network work consume 80 ms, the application consumes 120 ms, and 50 ms is reserved for variance. What dependency budget remains?',
          'About 250 ms at the matching percentile and load condition',
          [
            'About 300 ms because variance should not be budgeted',
            'About 500 ms because each component receives the full target',
            'About 130 ms because gateway time must be counted twice',
          ],
          'Sequential work consumes the end-to-end latency budget. Subtracting 80 ms, 120 ms, and a 50 ms safety allowance leaves roughly 250 ms for dependencies.',
          'medium',
        ),
        question(
          'A fraud check has a 150 ms P95 but a 4-second P99 that causes checkout abandonment. Which requirement improvement is most useful?',
          'Add a tail-latency target and define timeout or fallback behavior for the slowest requests',
          [
            'Keep only the P95 because it already describes every request',
            'Replace percentiles with one monthly average',
            'Increase the timeout without measuring abandonment or correctness',
          ],
          'A satisfactory P95 can hide a damaging tail. A P99 target plus explicit timeout and fallback behavior constrains the experience of users currently trapped in very slow requests.',
          'hard',
        ),
        question(
          'A storage service advertises eleven nines of durability and 99.9% availability. What does that mean?',
          'Stored data is extraordinarily unlikely to be lost, but the service may still be temporarily unreachable',
          [
            'Every read is guaranteed to finish with no latency',
            'The service may lose data frequently as long as requests succeed',
            'Durability and availability are interchangeable measurements',
          ],
          'Durability concerns preservation of committed data; availability concerns whether the service can be used now. Replicated durable data can remain intact during an access outage.',
          'medium',
        ),
        question(
          'Which statement turns read freshness into a measurable consistency requirement?',
          'After a successful profile update, the same user must read the new value within two seconds in every supported region',
          [
            'Profile data should be reasonably consistent',
            'The database should use replication',
            'Most users probably will not notice stale data',
          ],
          'The statement defines an event, observer, scope, and maximum staleness. That permits the team to compare synchronous replication, session routing, cache invalidation, and eventual consistency.',
          'medium',
        ),
        question(
          'Which requirement best expresses scalability without prescribing infrastructure?',
          'Sustain growth from 2,000 to 20,000 requests per second while preserving the agreed latency and error targets',
          [
            'Run exactly twenty application instances',
            'Use Kubernetes for every component',
            'Add a larger database whenever traffic changes',
          ],
          'Scalability is the ability to handle a stated workload change while maintaining service objectives. Instance counts and orchestration products are possible mechanisms, not the requirement.',
          'easy',
        ),
        question(
          'Which security quality attribute is sufficiently testable for privileged access?',
          'Every administrative action is authorized, recorded with actor and target, and queryable by security staff within five minutes',
          [
            'The administration system should be very secure',
            'Administrators should use a modern login page',
            'Security should be added before production',
          ],
          'A testable security target names the protected operation, required control, evidence, audience, and timing instead of relying on an adjective.',
          'medium',
        ),
        question(
          'Which target most directly measures deployability and recovery from a bad release?',
          'A verified previous version can be restored within ten minutes without losing committed customer data',
          [
            'Every release contains the same number of files',
            'Developers deploy only on Tuesdays',
            'The build server retains unlimited console output',
          ],
          'Rollback time and data compatibility are operational quality attributes. They force designs for immutable artifacts, backward-compatible changes, health signals, and rehearsed recovery.',
          'medium',
        ),
        question(
          'A user request requires three independent sequential services, each available 99.9% of the time. Ignoring other failures, what is the approximate request-path availability?',
          'About 99.7%',
          [
            'Exactly 99.9%',
            'About 99.9999999%',
            'About 97%',
          ],
          'For required independent dependencies, multiply availability: 0.999 cubed is about 0.997, or 99.7%. More mandatory hops can make the end-to-end target harder than any component target.',
          'hard',
        ),
        question(
          'A design meets latency and availability targets but costs four times the approved amount. What is the strongest engineering response?',
          'Treat cost as a quality constraint, identify the dominant cost drivers, and compare explicit reductions in scope, performance, retention, or redundancy',
          [
            'Hide the estimate until after launch',
            'Keep every technical choice and assume finance will expand the budget',
            'Remove observability first because it does not serve user traffic directly',
          ],
          'A system that cannot be afforded is not viable. Cost should be traced to workload and service choices so stakeholders can make a visible, informed tradeoff instead of accepting accidental risk.',
          'hard',
        ),
      ],
    },
    {
      id: 'estimate-load',
      title: 'Estimate load',
      masteryLevel: 'L2',
      frequency: 'core',
      questionTarget: 20,
      questions: [
        question(
          'A system receives 10 million events evenly over a day. What is the approximate average event rate?',
          '116 events per second',
          [
            '12 events per second',
            '1,160 events per second',
            '10,000 events per second',
          ],
          'A day has 86,400 seconds. Dividing 10,000,000 by 86,400 gives about 116 events per second before applying peak or retry factors.',
          'easy',
        ),
        question(
          'The 10-million-event workload peaks at eight times its daily average. Which rate should drive the first capacity test?',
          'About 930 events per second, plus stated headroom',
          [
            'Exactly 116 events per second',
            'Exactly 80 million events per second',
            'Eight events per second',
          ],
          'Eight times roughly 116 is 928. Capacity should be tested near the expected peak with additional headroom, not only at a daily average that hides bursts.',
          'medium',
        ),
        question(
          'Five million 2 KB records are retained each day for 30 days. What is the approximate primary-data growth before indexes, replicas, and backups?',
          '300 GB',
          [
            '30 GB',
            '3 TB',
            '300 TB',
          ],
          'Five million times 2 KB is about 10 GB per day; over 30 days that is about 300 GB. Real storage planning must add indexes, replication, backups, and metadata.',
          'medium',
        ),
        question(
          'An API sustains 100 requests per second and each request remains in flight for 200 ms on average. About how many requests are concurrently in flight?',
          '20 requests',
          [
            '2 requests',
            '100 requests',
            '500 requests',
          ],
          'Little’s Law gives concurrency as arrival rate times time in the system: 100 requests/s times 0.2 s equals about 20 concurrent requests.',
          'medium',
        ),
        question(
          'A download service sends 2,000 responses per second with an average payload of 25 KB. What outbound payload bandwidth does that imply?',
          'About 50 MB per second before protocol overhead',
          [
            'About 5 MB per second',
            'About 500 MB per second',
            'About 50 GB per second',
          ],
          'Multiplying 2,000 by 25 KB gives 50,000 KB, or roughly 50 MB per second. Network and encryption overhead should be budgeted separately.',
          'medium',
        ),
        question(
          'Why should reads and writes be estimated separately?',
          'They often use different paths, have different costs, and scale with different product actions',
          [
            'Only write traffic consumes infrastructure capacity',
            'Read and write rates are always equal in database systems',
            'Separating them removes the need to estimate payload size',
          ],
          'A read-heavy catalog and a write-heavy ingestion service stress different resources. Separate rates expose caching, indexing, replication, and transaction requirements.',
          'easy',
        ),
        question(
          'Which estimate is most likely to reveal a hot-partition risk hidden by global averages?',
          'Peak traffic for the busiest tenant or partition key',
          [
            'Total monthly traffic divided evenly across every key',
            'Average CPU across all development laptops',
            'The number of source files in the service',
          ],
          'Uneven key distribution can saturate one partition while fleet-wide averages look healthy. Capacity estimates should include the largest tenant and hottest keys.',
          'hard',
        ),
        question(
          'A rough estimate changes by 100 times depending on average attachment size. What should the team do next?',
          'Measure a representative attachment sample before committing the storage design',
          [
            'Use the midpoint and treat it as exact',
            'Ignore attachments because the estimate is uncertain',
            'Choose the largest database tier without measuring',
          ],
          'The most sensitive uncertain input deserves measurement. A small sample can retire more design risk than making the arithmetic look more precise.',
          'medium',
        ),
        question(
          'Why must storage estimates include amplification?',
          'Indexes, replicas, backups, and derived copies can consume multiples of the logical record size',
          [
            'Stored records become larger each time they are read',
            'Cloud providers always bill exactly twice the primary bytes',
            'Compression makes every record larger in production',
          ],
          'Logical payload size is only the starting point. Physical capacity and cost also include indexes, redundancy, backups, logs, and projections.',
          'medium',
        ),
        question(
          'What is the best way to present uncertain capacity estimates in a system-design interview?',
          'State assumptions, calculate a plausible range, identify the sensitive terms, and connect the result to a design decision',
          [
            'Give one exact number without showing assumptions',
            'Avoid arithmetic until production metrics exist',
            'List several large numbers without explaining their architectural effect',
          ],
          'The estimate is useful when its assumptions can be challenged and its order of magnitude changes a decision. False precision does not improve the design.',
          'hard',
        ),
        question(
          'A product receives 24 million requests per day, 80% during an eight-hour business window. What is the approximate average rate during that window?',
          'About 670 requests per second',
          [
            'About 280 requests per second',
            'About 2,400 requests per second',
            'About 6,700 requests per second',
          ],
          'Eighty percent of 24 million is 19.2 million requests. Dividing by 28,800 seconds in eight hours gives roughly 667 requests per second before a shorter peak factor is applied.',
          'medium',
        ),
        question(
          'A database holds 400 GB of primary data, keeps three total replicated copies, and retains one additional full backup. Roughly how much storage is required before indexes and logs?',
          'About 1.6 TB',
          [
            'About 800 GB',
            'About 1.2 TB',
            'About 4.8 TB',
          ],
          'Three total copies consume 1.2 TB, and one additional 400 GB backup brings the estimate to about 1.6 TB. Indexes, logs, snapshots, and growth headroom still need separate allowances.',
          'medium',
        ),
        question(
          'A stream receives 50,000 events per second at 200 bytes each and independently delivers every event to three consumer groups. What payload throughput crosses consumer boundaries?',
          'About 30 MB per second before protocol and replication overhead',
          [
            'About 10 MB per second because consumers do not add reads',
            'About 3 MB per second',
            'About 300 MB per second',
          ],
          'The source payload rate is about 10 MB/s. Three independent consumer groups each read that stream, producing roughly 30 MB/s of consumer delivery before overhead.',
          'hard',
        ),
        question(
          'A service receives 20,000 reads per second and its cache hit rate is 90%. Approximately how many reads per second still reach the database?',
          '2,000 reads per second',
          [
            '200 reads per second',
            '18,000 reads per second',
            '22,000 reads per second',
          ],
          'A 90% hit rate leaves a 10% miss rate. Ten percent of 20,000 is 2,000 database reads per second, before accounting for cache refreshes or failed lookups.',
          'easy',
        ),
        question(
          'A queue contains 180,000 jobs. Workers process 1,000 jobs per second while 600 new jobs per second continue arriving. How long will the backlog take to drain?',
          'About 7.5 minutes',
          [
            'About 3 minutes',
            'About 5 minutes',
            'About 30 minutes',
          ],
          'The net drain rate is 1,000 minus 600, or 400 jobs per second. Dividing 180,000 by 400 gives 450 seconds, which is 7.5 minutes.',
          'hard',
        ),
        question(
          'Two million persistent client connections require about 4 KB of application memory each. What is the minimum connection-state memory before runtime and operating-system overhead?',
          'About 8 GB',
          [
            'About 800 MB',
            'About 80 GB',
            'About 8 TB',
          ],
          'Two million times 4 KB is roughly 8 billion bytes, or about 8 GB. Real planning must add socket buffers, runtime objects, TLS state, uneven distribution, and failure headroom.',
          'medium',
        ),
        question(
          'A partition safely handles 5,000 writes per second. The forecast peak is 120,000 writes per second and the design requires 50% headroom. What is the minimum estimated partition count?',
          '36 partitions',
          [
            '24 partitions',
            '30 partitions',
            '60 partitions',
          ],
          'Adding 50% headroom raises planned capacity to 180,000 writes per second. Dividing by 5,000 gives 36 partitions, assuming keys distribute traffic evenly.',
          'hard',
        ),
        question(
          'A dependency receives 5,000 requests per second. Twenty percent fail, and every failed request is retried twice. What request rate can the dependency see during the incident?',
          'About 7,000 requests per second',
          [
            'About 5,200 requests per second',
            'About 6,000 requests per second',
            'About 15,000 requests per second',
          ],
          'The original load is 5,000 requests per second. Twenty percent is 1,000 failures, and two retries add 2,000 requests per second, producing about 7,000 in total if retries overlap the same interval.',
          'hard',
        ),
        question(
          'One million 5 MB objects arrive each day and are retained for 30 days. What is the approximate logical storage footprint?',
          'About 150 TB',
          [
            'About 15 TB',
            'About 1.5 PB',
            'About 150 GB',
          ],
          'One million times 5 MB is about 5 TB per day. Multiplying by 30 days gives roughly 150 TB before replication, metadata, versions, and temporary processing copies.',
          'medium',
        ),
        question(
          'Ten million monthly downloads each return 2 MB from a cloud region to users. What approximate internet egress volume should be priced?',
          'About 20 TB per month',
          [
            'About 2 TB per month',
            'About 200 TB per month',
            'About 20 GB per month',
          ],
          'Ten million multiplied by 2 MB is 20 million MB, or roughly 20 TB. Region, cache hit rate, compression, free allowances, and provider pricing determine the final cost.',
          'medium',
        ),
      ],
    },
    {
      id: 'system-boundaries',
      title: 'Draw system boundaries',
      masteryLevel: 'L2',
      frequency: 'frequent',
      questionTarget: 12,
      questions: [
        question(
          'What makes a system-boundary diagram useful beyond boxes and arrows?',
          'Ownership, trust zones, data exchanged, protocol, direction, and important failure behavior',
          [
            'A different color for every implementation class',
            'Every function and database column in the codebase',
            'Only the cloud product names used in deployment',
          ],
          'Boundary labels reveal contracts, trust changes, and failure assumptions. A component inventory alone does not show what each crossing requires.',
          'easy',
        ),
        question(
          'A booking service calls an external airline API. Which fact should be explicit at that boundary?',
          'The request may succeed remotely even if the local call times out',
          [
            'Both systems must use the same programming language',
            'The airline API belongs inside the booking service database',
            'A timeout proves that no booking was created',
          ],
          'Remote calls can produce an unknown outcome when responses are lost. The contract needs stable identifiers, timeout behavior, and reconciliation rather than assuming timeout means failure.',
          'medium',
        ),
        question(
          'Which boundary most clearly represents a trust transition?',
          'A public webhook entering a privately operated order service',
          [
            'A function calling another function in the same module',
            'A local variable being passed to a formatter',
            'A test fixture constructing an in-memory object',
          ],
          'Internet-originated webhook data crosses from an untrusted source into an internal system. Authentication, replay protection, validation, and authorization belong at that crossing.',
          'easy',
        ),
        question(
          'Two services update each other’s tables in one shared database. What boundary problem does this create?',
          'Neither service has clear data ownership, so schema and invariant changes require hidden coordination',
          [
            'The database cannot support transactions',
            'Shared tables automatically duplicate every row',
            'Network latency between the services becomes zero',
          ],
          'Direct cross-service writes bypass the owning contract. They couple deployments and let one service violate rules another service is supposed to protect.',
          'medium',
        ),
        question(
          'When is a new network service boundary least justified?',
          'The code changes with the same team, deploys together, and needs frequent transactional coordination',
          [
            'The workload needs independent scaling and fault isolation',
            'A regulated capability needs separate access controls and ownership',
            'A stable domain is released independently by another team',
          ],
          'A remote boundary adds latency, partial failure, versioning, and operations. If ownership, deployment, scaling, and data remain tightly coupled, an in-process module is usually simpler.',
          'hard',
        ),
        question(
          'A diagram shows “payment provider” but no labels on the connecting arrow. What key information is missing?',
          'Authentication, request identity, data sent, timeout, and response or callback semantics',
          [
            'The provider’s office location',
            'The variable names used in its SDK',
            'The number of developers employed by the provider',
          ],
          'The crossing is the contract. Labels should explain how the interaction is secured, correlated, bounded, and completed, especially when money can move after a timeout.',
          'medium',
        ),
        question(
          'Which component should own validation and durable state for an uploaded document?',
          'The service whose responsibility is the document lifecycle, exposed through its contract',
          [
            'Whichever client uploads the document first',
            'Every downstream consumer independently',
            'The load balancer in front of the API',
          ],
          'Ownership should align with the lifecycle and invariants of the data. Clients and consumers can validate their inputs, but one domain boundary must own the durable truth.',
          'medium',
        ),
        question(
          'Why should an external vendor normally remain outside your system boundary?',
          'You do not control its availability, releases, data handling, or recovery behavior',
          [
            'External vendors cannot use standard protocols',
            'Cloud services never belong on architecture diagrams',
            'Vendor calls are always asynchronous',
          ],
          'A separate ownership and failure domain needs an explicit contract. Treating it as an internal component hides operational and security risks the design must manage.',
          'easy',
        ),
        question(
          'A synchronous call crosses four internal services before returning to a user. What should the designer examine first?',
          'Whether each boundary is necessary and how latency or failure propagates across the chain',
          [
            'Whether every service uses the same logging library',
            'Whether a fifth service would make responsibilities clearer',
            'Whether all service names end with the word API',
          ],
          'Every synchronous hop consumes the user’s time budget and adds another failure dependency. Boundaries should earn that cost through ownership, isolation, or independent change.',
          'hard',
        ),
        question(
          'Which test best verifies a boundary contract with a third-party webhook sender?',
          'Send valid, invalid, duplicate, replayed, and delayed payloads through the real HTTP boundary',
          [
            'Unit-test only the internal success handler',
            'Confirm that the architecture diagram contains an arrow',
            'Mock every request and skip signature verification',
          ],
          'A boundary test should exercise transport, authentication, validation, duplicate handling, and timing behavior. Those are the risks hidden by a direct unit call.',
          'hard',
        ),
        question(
          'A support portal needs a customer name from CRM, but CRM also stores tax identifiers and bank details. What is the strongest boundary decision?',
          'Expose a purpose-specific contract containing only the support fields and keep sensitive CRM data behind its existing trust boundary',
          [
            'Give the portal direct read access to every CRM table',
            'Copy the complete CRM database into the portal each hour',
            'Move CRM into the portal repository so no network call is visible',
          ],
          'A boundary should enforce least privilege and data minimization. A narrow contract limits exposure, decouples schemas, and keeps sensitive-data policy with the owning system.',
          'hard',
        ),
        question(
          'Two teams must jointly deploy whenever either changes a shared service, and incidents cannot be assigned to one owner. What does this most strongly suggest?',
          'The boundary may not match ownership or change patterns and should be reevaluated with explicit contracts and accountability',
          [
            'The service needs a more colorful architecture diagram',
            'Both teams should deploy more frequently without changing ownership',
            'All services should be merged into one process regardless of domain',
          ],
          'A useful service boundary permits independent change and clear operational ownership. Persistent lockstep deployment and ambiguous incident responsibility are evidence that the current split may be misplaced.',
          'hard',
        ),
      ],
    },
    {
      id: 'data-model',
      title: 'Define the data model',
      masteryLevel: 'L2',
      frequency: 'frequent',
      questionTarget: 12,
      questions: [
        question(
          'What should drive an initial system-design data model?',
          'The facts to preserve, their identity, relationships, state transitions, invariants, and access patterns',
          [
            'The table names used by a previous employer',
            'The database product with the largest feature list',
            'The shape of one current user-interface screen',
          ],
          'A model represents durable domain truth. Technology and UI shape can change, while identity, valid state, constraints, and required reads determine what the model must preserve.',
          'easy',
        ),
        question(
          'Why should an order line store the price agreed at purchase time instead of only referencing the product’s current price?',
          'The order needs an immutable historical fact even when the catalog price changes',
          [
            'Foreign keys cannot reference changing records',
            'Catalog prices can only be stored in memory',
            'Duplicating any value always improves query performance',
          ],
          'The purchased price is a fact of the transaction, not a live product attribute. A snapshot preserves invoices, refunds, and audits after catalog changes.',
          'easy',
        ),
        question(
          'A booking system must prevent two confirmed reservations for the same room and night. Where should this invariant be protected?',
          'With a transactional allocation rule or uniqueness constraint at the authoritative data boundary',
          [
            'Only by disabling the submit button after one click',
            'Only with a read-before-write check in each client',
            'By allowing duplicates and removing one in a nightly report',
          ],
          'Concurrent requests can both pass an application-level read check. The authoritative store must serialize or reject conflicting allocations where the invariant is committed.',
          'hard',
        ),
        question(
          'Which state transition should a reservation model reject?',
          'An expired reservation becoming confirmed without a new inventory allocation',
          [
            'A held reservation becoming confirmed after payment succeeds',
            'A held reservation becoming expired when its deadline passes',
            'A confirmed reservation becoming cancelled under the cancellation policy',
          ],
          'Expiry releases the original claim on inventory. Confirming it later without allocating stock can violate availability, so valid transitions must encode that rule.',
          'medium',
        ),
        question(
          'When is normalization most valuable?',
          'When duplicated facts change independently and could otherwise disagree',
          [
            'When every read must avoid all joins regardless of data size',
            'When the application has no durable relationships',
            'When copies are guaranteed to synchronize themselves',
          ],
          'Normalization gives one owner to a fact and reduces conflicting updates. It is especially useful when the same mutable fact would otherwise be repeated across many records.',
          'easy',
        ),
        question(
          'A team creates a denormalized search projection from customer records. What obligation does that create?',
          'Define its source of truth, freshness target, update path, idempotent rebuild, and reconciliation process',
          [
            'Treat the projection as automatically strongly consistent',
            'Let each reader decide which copy is authoritative',
            'Disable updates to the source customer records',
          ],
          'Derived copies can lag or miss changes. Clear ownership and repair behavior make expected staleness manageable instead of allowing unexplained drift.',
          'hard',
        ),
        question(
          'Which index best supports listing one tenant’s newest events with stable pagination?',
          'A composite index beginning with tenant ID and continuing with event time and a unique ID',
          [
            'An index only on the event payload text',
            'A separate table with no tenant identifier',
            'An index on a random value generated for each query',
          ],
          'The index should match filtering and ordering. Tenant ID narrows the range, while time plus a unique ID provides deterministic ordering for a cursor.',
          'medium',
        ),
        question(
          'Why might a system keep both an append-only status history and a current-status field?',
          'The history supports audit and reconstruction while the current projection serves common reads efficiently',
          [
            'The two copies guarantee consistency without update logic',
            'Append-only records cannot be queried directly',
            'A current-status field removes the need for state-transition rules',
          ],
          'History answers how state changed; a projection answers what state is now. The system must update or rebuild the projection reliably from the authoritative events.',
          'medium',
        ),
        question(
          'Two users edit the same profile from version 7. What data-model feature helps prevent the second save from silently overwriting the first?',
          'A version field checked and incremented atomically with the update',
          [
            'A larger text column for the profile',
            'A read replica used for all writes',
            'A random delay before each save',
          ],
          'Optimistic concurrency updates only when the stored version still matches the caller’s version. A mismatch exposes the conflict instead of silently losing data.',
          'medium',
        ),
        question(
          'A user can belong to several teams, and each team has several users. What is the clean relational model?',
          'A membership entity linking user and team, with any role or join date stored on the membership',
          [
            'A comma-separated list of team IDs on every user row',
            'One team column copied into every activity record',
            'A separate user record duplicated for each team',
          ],
          'A join entity represents the many-to-many relationship and gives relationship-specific facts such as role one clear home, while keys can enforce uniqueness.',
          'easy',
        ),
        question(
          'A multi-tenant event store is queried almost always by tenant and time range. Which partitioning direction is the strongest starting point?',
          'Partition by tenant plus a time bucket, then verify that large tenants cannot create hot or oversized partitions',
          [
            'Partition only by event type even though queries do not begin there',
            'Choose a random partition for every event and require full-store scans',
            'Keep all tenants in one unbounded partition because the logical schema is simpler',
          ],
          'Partition keys should support dominant access patterns while distributing load and growth. Combining tenant and time can localize reads, but skew and large tenants still require measurement or salting.',
          'hard',
        ),
        question(
          'A user deletion request touches an account record, search index, cache, analytics copy, and immutable financial evidence. What should the data model define?',
          'Ownership and lineage for each copy, deletion or anonymization behavior, retained legal records, propagation deadlines, and proof of completion',
          [
            'Only a deleted boolean in the account table',
            'A nightly cache restart with no record of downstream copies',
            'One shared password that allows the user to delete every datastore directly',
          ],
          'Deletion is a lifecycle workflow across derived and authoritative data. Explicit lineage, policy exceptions, deadlines, and audit evidence prevent hidden copies from violating the intended semantics.',
          'hard',
        ),
      ],
    },
    {
      id: 'api-contracts',
      title: 'Design the API',
      masteryLevel: 'L2',
      frequency: 'frequent',
      questionTarget: 12,
      questions: [
        question(
          'What makes an API contract more than request and response JSON shapes?',
          'It also defines identity, authorization, errors, retries, concurrency, pagination, side effects, and completion semantics',
          [
            'It includes the provider’s internal table layout',
            'It requires every endpoint to use the same HTTP method',
            'It exposes every implementation class to callers',
          ],
          'Callers need behavioral guarantees to act safely. Shape alone does not say whether a retry duplicates work, an update can conflict, or a response means completion.',
          'easy',
        ),
        question(
          'A mobile app retries POST /payments after losing the response. Which design prevents a second logical charge?',
          'Require a caller-scoped idempotency key and persist it atomically with the payment result',
          [
            'Change the retry to a GET request with the same body',
            'Generate a new server request ID on every retry',
            'Ask users not to retry on unreliable networks',
          ],
          'The same idempotency key lets the server return the first operation’s result. Atomic persistence prevents a crash window between creating the charge and recording deduplication.',
          'hard',
        ),
        question(
          'What does a client-side timeout prove about a remote mutation?',
          'Only that the client stopped waiting; the mutation may have failed, completed, or still be running',
          [
            'The server definitely rolled the mutation back',
            'The server definitely completed the mutation',
            'The request never reached the remote network',
          ],
          'A response can be lost after work commits. Retry semantics, operation identity, status lookup, and reconciliation must account for an unknown outcome.',
          'medium',
        ),
        question(
          'Why is cursor pagination usually safer than offset pagination for a changing event feed?',
          'A cursor anchors the next page to a stable ordered position as rows are inserted or removed',
          [
            'A cursor guarantees every query is served from memory',
            'Offset pagination cannot return more than one page',
            'A cursor removes the need for deterministic ordering',
          ],
          'Offsets shift when earlier rows change, causing duplicates or skips. A cursor based on ordered immutable fields continues after a known item.',
          'medium',
        ),
        question(
          'Which HTTP behavior supports optimistic concurrency for updating a resource?',
          'Require the client’s known version in If-Match and reject a stale update',
          [
            'Accept every update in arrival order without checking state',
            'Use a longer URL for newer resource versions',
            'Retry every conflict automatically with the same old body',
          ],
          'A conditional request applies only to the version the caller read. Rejecting a mismatch lets the client review or merge concurrent changes.',
          'hard',
        ),
        question(
          'A report takes several minutes to generate. Which initial API response is most honest?',
          'Return 202 Accepted with a job resource the client can inspect',
          [
            'Return 200 OK with an empty report and no status',
            'Hold the connection open indefinitely',
            'Return 404 until the report happens to finish',
          ],
          'A 202 response says work was accepted but is incomplete. A job resource can expose pending, succeeded, and failed states without tying completion to one request.',
          'easy',
        ),
        question(
          'An order update is valid JSON but conflicts with an already-finalized order. Which response category best communicates the problem?',
          'A conflict response that identifies the current state preventing the operation',
          [
            'A success response that silently ignores the update',
            'An authentication challenge regardless of caller identity',
            'A generic server crash response with no stable error code',
          ],
          'The request is structurally valid, but current resource state prevents it. A stable conflict error lets the caller distinguish this from malformed input or a transient outage.',
          'medium',
        ),
        question(
          'Which API change is most likely to be backward compatible?',
          'Adding an optional response field that existing consumers ignore',
          [
            'Changing an identifier from a string to a nested object',
            'Removing a response field used by deployed clients',
            'Changing an optional request field to required immediately',
          ],
          'Tolerant clients can ignore a new optional field. Removing or changing existing meaning requires an overlap and migration plan for independently deployed consumers.',
          'easy',
        ),
        question(
          'Where must authorization for GET /tenants/{tenantId}/invoices/{invoiceId} be enforced?',
          'At the resource-access boundary by checking the authenticated principal against the requested tenant and invoice',
          [
            'Only by hiding the link in the user interface',
            'Only by verifying that tenantId has the right string format',
            'Only at account sign-in, regardless of the requested resource',
          ],
          'Authentication identifies a caller but does not authorize every resource named in a URL. The server must enforce tenant and object ownership on each access path.',
          'hard',
        ),
        question(
          'A public API rate-limits each request by source IP only. What practical concern should be raised?',
          'Many users may share one IP while one attacker can distribute requests across many IPs',
          [
            'IP addresses cannot be observed by network services',
            'Rate limits should never return a retry hint',
            'All API callers always have one permanent public IP',
          ],
          'The constrained principal should match the protected resource, often an account, API key, tenant, or operation. IP limits can be one layer but are a weak identity by themselves.',
          'medium',
        ),
        question(
          'An API must update 5,000 independent records and some may fail validation. Which contract is most honest and operable?',
          'Start a bulk job with an idempotency key, expose job status, and return per-item outcomes with resumable retry semantics',
          [
            'Hold one HTTP connection until every downstream system finishes',
            'Return 200 immediately and provide no way to discover failures',
            'Claim the operation is atomic even though the stores cannot coordinate a transaction',
          ],
          'A long partial-success operation needs explicit acceptance, progress, result, retry, and idempotency semantics. A job resource makes those states observable without pretending distributed atomicity.',
          'hard',
        ),
        question(
          'A service needs to rename a response field used by unknown external clients. What is the safest contract evolution?',
          'Add the new field compatibly, measure adoption, publish deprecation timing, and remove the old field only through a versioned breaking change',
          [
            'Rename the field in place and rely on clients to infer its meaning',
            'Return one field name at random so clients support both',
            'Freeze the entire API forever because evolution is impossible',
          ],
          'Additive evolution preserves existing clients while telemetry and a deprecation policy guide migration. Removing or changing meaning requires an explicit compatibility boundary.',
          'medium',
        ),
      ],
    },
    {
      id: 'load-balancing-stateless-services',
      title: 'Load balancing & stateless services',
      masteryLevel: 'L2',
      frequency: 'frequent',
      questionTarget: 12,
      questions: [
        question(
          'What is the primary job of a load balancer?',
          'Accept traffic on a stable endpoint and distribute it across healthy service instances',
          [
            'Store the application’s durable business records',
            'Guarantee that every request finishes successfully',
            'Replace authentication and authorization in each service',
          ],
          'A load balancer routes connections or requests across available backends. It improves distribution and availability, but backend correctness and durable state remain separate concerns.',
          'easy',
        ),
        question(
          'What does a stateless application instance mean in a horizontally scaled service?',
          'Any healthy instance can handle the next request because durable session and business state live in shared systems',
          [
            'The overall application stores no data anywhere',
            'The instance may keep all user sessions only in its own memory',
            'Every request must be sent to the first instance that handled the user',
          ],
          'Statelessness applies to interchangeable request handlers, not the whole system. Durable state belongs in databases, object stores, queues, or shared session systems.',
          'easy',
        ),
        question(
          'A web app keeps shopping carts in each server’s memory. What happens when a load balancer sends the next request to another instance?',
          'The cart appears missing unless state is moved to a shared store or affinity is used as a temporary workaround',
          [
            'The load balancer automatically copies process memory',
            'The second instance reads the first instance’s variables through DNS',
            'The cart becomes durable because two instances exist',
          ],
          'Load balancers do not replicate application memory. Shared durable cart state makes instances replaceable; affinity can mask the issue but weakens failover and even distribution.',
          'medium',
        ),
        question(
          'Which statement correctly compares common Layer 4 and Layer 7 load balancing?',
          'Layer 4 routes using connection information, while Layer 7 can route HTTP requests by host, path, or headers',
          [
            'Layer 4 understands URL paths while Layer 7 only sees IP addresses',
            'Layer 7 can route only UDP traffic',
            'Layer 4 always terminates HTTP and applies web application firewall rules',
          ],
          'Transport-level balancing works with connection metadata such as address and port. HTTP-aware balancing can inspect application-layer request details and apply richer routing.',
          'medium',
        ),
        question(
          'Which current cloud mapping is accurate for an HTTP application that needs path-based routing?',
          'Use Azure Application Gateway or AWS Application Load Balancer; use their Layer 4 products when connection-level routing is the requirement',
          [
            'Use object storage because it performs health-based HTTP routing',
            'Use Azure Load Balancer for path rules because it is an HTTP reverse proxy',
            'Use AWS Network Load Balancer to rewrite application URL paths',
          ],
          'Azure Application Gateway and AWS Application Load Balancer operate at the HTTP application layer. Azure Load Balancer and AWS Network Load Balancer serve transport-level scenarios.',
          'medium',
        ),
        question(
          'Why should a readiness check fail while an instance is still warming required dependencies?',
          'It keeps normal traffic away until the instance can serve requests correctly',
          [
            'It forces the process to restart continuously',
            'It permanently removes the instance from autoscaling',
            'It proves every downstream dependency will remain healthy',
          ],
          'Readiness controls traffic eligibility. It should reflect whether the instance can currently serve, while liveness separately answers whether restarting the process may help.',
          'easy',
        ),
        question(
          'A service adds ten API instances, but throughput does not increase because every request waits on one database lock. What is the right conclusion?',
          'The serialized database section is the bottleneck, so adding stateless instances cannot raise end-to-end throughput',
          [
            'The load balancer needs a different logo',
            'Horizontal scaling works only with exactly two instances',
            'The API should keep more user state in local memory',
          ],
          'A system scales only when its limiting resource scales. More capacity in a nonlimiting tier can increase contention without moving the bottleneck.',
          'hard',
        ),
        question(
          'When can least-connections routing be more useful than simple round robin?',
          'When request or connection durations vary enough that instance load becomes uneven',
          [
            'When every request has identical cost and duration',
            'When no backend health information exists',
            'When the application needs to store durable files on the balancer',
          ],
          'Round robin distributes arrivals, not ongoing work. Least-connections can better balance long-lived or uneven connections, though the chosen signal still may not represent CPU or downstream cost.',
          'medium',
        ),
        question(
          'Why can sticky sessions reduce resilience?',
          'A user becomes dependent on one instance, creating uneven load and disruption when that instance fails',
          [
            'They prevent TLS from encrypting requests',
            'They force all users onto one global instance',
            'They make health checks impossible to configure',
          ],
          'Affinity can preserve local session state temporarily, but it weakens interchangeability. Shared state or self-contained session tokens usually provide cleaner scaling and failover.',
          'medium',
        ),
        question(
          'What should trigger autoscaling for workers that spend most of their time waiting for queued jobs?',
          'A work signal such as queue depth or oldest-message age, bounded by downstream capacity',
          [
            'Only the number of source-code lines in each worker',
            'Only API server CPU even when worker backlog grows',
            'A fixed daily restart regardless of demand',
          ],
          'The scaling signal should represent pending work and user delay. Scaling must also respect database or vendor limits so extra workers do not overwhelm the next dependency.',
          'hard',
        ),
        question(
          'During deployment, instances are removed while requests are still in flight, causing intermittent errors. What capability is missing?',
          'Connection draining with readiness removal, a bounded grace period, and termination behavior matched to request duration',
          [
            'Randomly terminating more instances at the same time',
            'Making health checks less frequent so shutdown is hidden',
            'Persisting every HTTP connection in the application database',
          ],
          'A retiring instance should stop receiving new work before it is terminated and finish or explicitly hand off bounded in-flight work. Load balancer and process shutdown timing must agree.',
          'medium',
        ),
        question(
          'A chat service uses long-lived WebSocket connections. Which scaling concern differs most from ordinary short HTTP requests?',
          'Connection count, rebalance behavior, per-connection state location, and reconnect storms matter in addition to request rate',
          [
            'A load balancer is never useful for persistent connections',
            'Every message must be stored in a browser cookie',
            'Horizontal scaling automatically transfers live sockets between instances',
          ],
          'Persistent sockets bind clients to instances for longer periods. Capacity and recovery planning must account for connection memory, uneven lifetimes, state routing, draining, and mass reconnects.',
          'hard',
        ),
      ],
    },
    {
      id: 'absorb-bursts',
      title: 'Absorb bursts',
      masteryLevel: 'L2',
      frequency: 'frequent',
      questionTarget: 12,
      questions: [
        question(
          'What does a durable queue provide during a short traffic burst?',
          'It accepts work quickly and lets bounded consumers process the backlog at a sustainable rate',
          [
            'It creates unlimited downstream processing capacity',
            'It guarantees every message is processed exactly once',
            'It makes all asynchronous work complete immediately',
          ],
          'A queue shifts excess work in time and decouples producer rate from consumer rate. It preserves accepted work but does not remove capacity or latency limits.',
          'easy',
        ),
        question(
          'A campaign produces 60,000 email jobs and the provider accepts 200 per second. What is the minimum drain time if no new jobs arrive?',
          'About 5 minutes',
          [
            'About 5 seconds',
            'About 30 minutes',
            'About 50 hours',
          ],
          'Dividing 60,000 jobs by 200 jobs per second gives 300 seconds, or five minutes. Retries and new arrivals would increase the real drain time.',
          'easy',
        ),
        question(
          'Why should operators monitor oldest-message age as well as queue depth?',
          'A stable or small depth can still contain work that is stuck and violating its latency promise',
          [
            'Message age determines the programming language of consumers',
            'Queue depth cannot be measured on managed services',
            'Oldest-message age guarantees the exact future arrival rate',
          ],
          'Depth measures quantity, while age reveals user-visible delay and stalled partitions. Both are needed to distinguish a healthy flowing queue from stuck work.',
          'medium',
        ),
        question(
          'Why must an at-least-once queue consumer be idempotent?',
          'A message can be delivered again after processing succeeds but acknowledgement is lost',
          [
            'Idempotency makes every message execute faster',
            'Queues reject consumers that use transactions',
            'At-least-once delivery prevents all duplicate messages',
          ],
          'Delivery and acknowledgement are separate steps. Recording a stable message or operation identity with the business effect prevents a redelivery from repeating that effect.',
          'hard',
        ),
        question(
          'Which message belongs in a dead-letter or quarantine path?',
          'A permanently invalid payload that continues to fail after the allowed attempts',
          [
            'Every message before its first processing attempt',
            'A valid message waiting behind older work',
            'A transiently failed message with retries still available',
          ],
          'Poison messages should stop consuming normal retry capacity. Quarantine preserves evidence for inspection, correction, replay, or explicit discard.',
          'medium',
        ),
        question(
          'What is the best retry policy after a queue consumer receives a transient 503 from a vendor?',
          'Use bounded exponential backoff with jitter and retain the same operation identity',
          [
            'Retry immediately without a limit from every worker',
            'Generate a new business operation ID for each attempt',
            'Discard the job immediately without recording the failure',
          ],
          'Backoff gives the dependency time to recover, jitter avoids synchronized retry waves, a bound controls backlog, and stable identity protects against duplicate effects.',
          'hard',
        ),
        question(
          'The arrival rate remains above consumer capacity for hours. What does the growing queue mean?',
          'The system has sustained overload and needs more safe capacity, admission control, reduced work, or a changed service promise',
          [
            'The queue has solved the capacity problem permanently',
            'Consumers should hide queue-age metrics',
            'The producer and consumer rates no longer matter',
          ],
          'Buffering handles temporary imbalance. Under sustained overload, backlog and completion latency grow until retention, storage, or user promises fail.',
          'hard',
        ),
        question(
          'Which managed services can a developer use for ordinary durable queueing in current Azure and AWS systems?',
          'Azure Service Bus queues or Azure Queue Storage, and Amazon SQS on AWS',
          [
            'Azure DNS and Amazon Route 53',
            'Azure Front Door and AWS CloudFront',
            'Azure App Configuration and AWS Certificate Manager',
          ],
          'These services persist messages for asynchronous consumers. The choice depends on required ordering, delivery features, transactions, throughput, and operational constraints.',
          'easy',
        ),
        question(
          'When is a queue a poor fit for the core interaction?',
          'The user needs an immediate authoritative answer before safely continuing the workflow',
          [
            'Work can finish later and exposes a job status',
            'A downstream provider has a bounded request rate',
            'A short producer spike exceeds steady consumer capacity',
          ],
          'Asynchronous queues introduce delay and eventual completion. A workflow that requires an immediate decision may need a synchronous authoritative path, even if later side effects use queues.',
          'medium',
        ),
        question(
          'Which overload control protects a queue from accepting work that will expire before processing?',
          'Bound backlog by age or capacity and reject, defer, or shed work according to an explicit policy',
          [
            'Accept every job indefinitely and hide estimated delay',
            'Increase message retention without monitoring drain rate',
            'Retry expired work more aggressively than current work',
          ],
          'Admission control keeps accepted work within a credible service promise. Work that is no longer valuable should expire or be rejected visibly rather than consume scarce capacity.',
          'hard',
        ),
        question(
          'Events for each order must remain ordered, but different orders may process in parallel. Which queue design fits best?',
          'Partition by order ID and preserve ordering within each partition while processing partitions concurrently',
          [
            'Use one global consumer for all orders forever',
            'Assign every event a random partition on each retry',
            'Sort events only by payload size',
          ],
          'Keyed partitioning provides per-entity order without imposing global serialization. The design must still handle skew, poison events, and partition ownership changes.',
          'medium',
        ),
        question(
          'One tenant floods a shared queue and delays every other tenant. Which control most directly restores fairness?',
          'Apply per-tenant admission or quotas and schedule from isolated tenant partitions with bounded concurrency',
          [
            'Increase the retention period without changing scheduling',
            'Allow the busiest tenant unlimited worker concurrency',
            'Remove tenant identity before enqueueing work',
          ],
          'A single FIFO backlog lets a noisy tenant monopolize capacity. Tenant-aware admission and scheduling preserve isolation while allowing deliberate borrowing of unused capacity.',
          'hard',
        ),
      ],
    },
    {
      id: 'failure-paths',
      title: 'Design failure paths',
      masteryLevel: 'L2',
      frequency: 'core',
      questionTarget: 20,
      questions: [
        question(
          'A remote payment call times out. What is the safest immediate interpretation?',
          'The result is unknown until the operation is queried or reconciled using its stable identity',
          [
            'The payment definitely failed and can be recreated immediately',
            'The payment definitely succeeded and should be marked complete',
            'The network automatically reversed any provider-side work',
          ],
          'A timeout describes the caller’s wait, not the remote outcome. An explicit pending state and reconciliation avoid both duplicate charges and false failure claims.',
          'easy',
        ),
        question(
          'Which operation is generally safest to retry automatically?',
          'A transiently failed read or an idempotent mutation with a stable operation key',
          [
            'An unkeyed request that charges a card',
            'A validation failure caused by a malformed payload',
            'A request rejected because the caller lacks permission',
          ],
          'Retries fit transient failures only when repeating the operation cannot create a second business effect. Invalid or unauthorized requests need correction, not repetition.',
          'easy',
        ),
        question(
          'How can retries turn one dependency incident into a larger outage?',
          'Many callers retry together, increasing load on a dependency that is already failing',
          [
            'Retries permanently reduce request volume',
            'Backoff always increases database consistency',
            'A retry removes the original request from telemetry',
          ],
          'Unbounded or synchronized retries amplify traffic and consume threads, connections, and queues. Limits, backoff, jitter, and retry budgets contain that pressure.',
          'medium',
        ),
        question(
          'What problem does a circuit breaker address?',
          'It stops repeated calls to a dependency that is currently failing and probes for recovery later',
          [
            'It guarantees the dependency never fails again',
            'It stores durable application data during an outage',
            'It replaces authorization checks on remote calls',
          ],
          'Opening the circuit fails fast, protects caller resources, and gives the dependency recovery space. The system still needs a fallback or clear error path.',
          'medium',
        ),
        question(
          'When is serving stale cached data an unsafe fallback?',
          'When stale data could violate a financial, authorization, inventory, or safety invariant',
          [
            'When the data is a noncritical product description',
            'When the response clearly includes its freshness time',
            'When the business has approved bounded staleness',
          ],
          'Fallbacks must preserve the core invariant. Stale catalog copy may be acceptable, while stale permissions, balances, or stock can create harmful incorrect actions.',
          'hard',
        ),
        question(
          'What is the purpose of bulkhead isolation?',
          'Keep one failing workload or dependency from exhausting resources needed by unrelated critical work',
          [
            'Force every request through one shared connection pool',
            'Replicate every database row across all services',
            'Make all service timeouts identical',
          ],
          'Separate pools, queues, or concurrency limits bound the blast radius. Optional slow work should not consume every worker or connection serving the critical path.',
          'medium',
        ),
        question(
          'A local order is pending because the provider response was lost. What should a reconciliation job do?',
          'Query by the stable provider request ID and transition local state only from authoritative evidence',
          [
            'Create a fresh provider order every minute',
            'Mark every old pending order successful without checking',
            'Delete the local order so the mismatch is hidden',
          ],
          'Reconciliation resolves uncertain distributed outcomes. Stable correlation and idempotent transitions let it converge local state without repeating the business action.',
          'hard',
        ),
        question(
          'Which telemetry is most useful for investigating one failed request across an API, queue, worker, and vendor?',
          'A propagated correlation ID plus operation IDs, attempt counts, states, and timestamps',
          [
            'One generic error message with no request context',
            'Only average CPU for the entire month',
            'A screenshot of the successful user interface',
          ],
          'Stable identifiers connect each stage and distinguish repeated attempts from duplicate operations. State and timing reveal where completion became uncertain.',
          'medium',
        ),
        question(
          'A malformed event has failed 20 times. What is the strongest next action?',
          'Stop normal retries, quarantine it with failure context, and alert the owning workflow',
          [
            'Retry continuously with no delay',
            'Block the entire queue until the payload becomes valid',
            'Silently discard it and report success',
          ],
          'A permanent failure needs ownership and evidence, not more load. Quarantine prevents one poison event from consuming the processing path while preserving it for repair.',
          'medium',
        ),
        question(
          'How should a team verify that its failure-path design works?',
          'Inject timeouts, errors, duplicate responses, and dependency loss, then assert user behavior, invariants, telemetry, and recovery',
          [
            'Review only the happy-path architecture diagram',
            'Wait for an uncontrolled production outage',
            'Confirm that every catch block returns the same message',
          ],
          'Failure behavior is executable system behavior. Focused fault tests reveal unsafe retries, resource leaks, broken fallbacks, and missing operational evidence before an incident does.',
          'hard',
        ),
        question(
          'A dependency becomes very slow but still returns success. API CPU remains normal while connections and request queues fill. What response best contains this brownout?',
          'Use a bounded downstream timeout, concurrency limit, and load shedding or fallback before caller resources are exhausted',
          [
            'Wait indefinitely because successful responses are not failures',
            'Add retries immediately without limiting attempts or concurrency',
            'Increase the public request timeout at every layer',
          ],
          'Slow success can exhaust sockets, threads, memory, and caller deadlines before error rates rise. Time budgets and concurrency bounds fail fast enough to preserve useful capacity.',
          'hard',
        ),
        question(
          'Three nested service layers each make up to three total attempts. In the worst case, how many calls can reach the deepest dependency for one original request?',
          '27 calls',
          [
            '3 calls',
            '6 calls',
            '9 calls',
          ],
          'Independent retries multiply across layers: three attempts cubed is 27 deepest calls. A shared retry budget or retries at one responsible boundary avoids this amplification.',
          'hard',
        ),
        question(
          'A product page requires price data but recommendations are optional. The recommendation service is failing. What is the strongest user-facing behavior?',
          'Return the authoritative product and price response without recommendations, while recording the degraded dependency',
          [
            'Fail the entire page because every dependency has equal importance',
            'Invent recommendation results and report full health',
            'Retry recommendations until the user request has no remaining deadline',
          ],
          'Graceful degradation preserves the critical invariant and removes optional work from the failure path. The degraded state should remain observable even when users receive a useful response.',
          'medium',
        ),
        question(
          'An order workflow reserves inventory, charges payment, then fails to create shipment. A distributed transaction is unavailable. What should the design do?',
          'Persist workflow state and apply an idempotent compensation or manual-recovery policy for the completed steps',
          [
            'Forget the successful steps and restart the workflow with new identifiers',
            'Mark shipment complete locally even though no shipment exists',
            'Assume every earlier side effect rolls back when the final call fails',
          ],
          'A multi-step workflow needs durable state and explicit semantics for partial completion. Compensation may release inventory or refund payment, while exceptional cases remain visible for reconciliation.',
          'hard',
        ),
        question(
          'A primary region fails after acknowledging orders, but its asynchronous replica may be five minutes behind. What must be decided before directing writes to the replica region?',
          'The permitted RPO, authoritative write history, duplicate prevention, reconciliation plan, and later failback procedure',
          [
            'Only the DNS record time to live',
            'Only whether the secondary region has the same instance names',
            'Nothing, because replication lag cannot affect acknowledged writes',
          ],
          'Failover can lose acknowledged data or create conflicting histories when replication is behind. Recovery objectives and write authority determine whether automatic failover is safe and how divergence is repaired.',
          'hard',
        ),
        question(
          'A team takes daily database backups but has never restored one. What evidence is still missing?',
          'A timed restore drill that verifies integrity, dependencies, credentials, runbooks, and the resulting RTO and RPO',
          [
            'The number of backup files listed in the console',
            'A promise that managed storage can never fail',
            'A larger retention period without any recovery test',
          ],
          'Backup creation does not prove recoverability. A restore exercise validates that usable data and the surrounding service can return within the promised recovery objectives.',
          'medium',
        ),
        question(
          'A failed dependency has recovered, but sending the full queued and live workload immediately may knock it down again. What is the safest recovery approach?',
          'Probe with limited traffic, ramp concurrency gradually, and drain backlog under current-work and dependency-capacity limits',
          [
            'Release every retry and queued item at once',
            'Keep the dependency permanently disabled after one failure',
            'Delete all queued work before checking its age or value',
          ],
          'Recovery traffic can create a second outage. Controlled probes, gradual ramp-up, jitter, and bounded backlog draining let the system verify capacity while protecting fresh critical work.',
          'hard',
        ),
        question(
          'A service is overloaded and cannot preserve every operation. Which shedding policy is strongest?',
          'Protect authenticated critical writes, reject low-value optional work early, and return explicit retry or degradation signals',
          [
            'Randomly kill requests after they perform expensive downstream work',
            'Give background exports priority over interactive safety actions',
            'Accept unlimited work and let every request time out',
          ],
          'Overload policy should reflect business value and shed work before scarce resources are consumed. Explicit responses make degraded behavior visible and prevent futile retry pressure.',
          'hard',
        ),
        question(
          'A rolling deployment sends traffic to old and new application versions while a database field is being replaced. Which migration sequence best limits failure?',
          'Add the new schema compatibly, deploy code that tolerates both forms, migrate data, switch reads and writes, then remove the old form later',
          [
            'Drop the old field first and deploy compatible code afterward',
            'Require every instance and client to restart at exactly the same instant',
            'Write only the new form while old instances still require the old form',
          ],
          'Expand-and-contract sequencing preserves compatibility during mixed-version operation and rollback. Destructive schema changes become safe only after old readers and writers are gone.',
          'hard',
        ),
        question(
          'A workflow emits no errors, but thousands of jobs remain in processing state for hours. Which signal most directly detects this failure?',
          'Count and age of jobs in each state, with an SLO-based alert on stale in-progress work',
          [
            'Only successful HTTP response count at job submission',
            'Only host CPU averaged across the month',
            'Only the number of lines written to application logs',
          ],
          'A lost transition or worker can create silent noncompletion without an exception. State age and end-to-end completion measures detect work that was accepted but stopped progressing.',
          'medium',
        ),
      ],
    },
  ],
)