import {
  defineSoftwareMasteryTopics,
  type SoftwareMasteryTopicBlueprint,
} from './software-core-mastery-builder'

const debuggingBlueprints = [
  {
    id: 'debugging-hypotheses',
    title: 'Hypothesis-Driven Debugging',
    questionTarget: 20,
    principle: 'Debugging should proceed through falsifiable hypotheses and discriminating observations rather than unstructured changes',
    scenario: 'An engineer changes timeouts, retries, and caching together because requests sometimes fail.',
    action: 'State one causal hypothesis, predict an observable difference, and run the cheapest test that could disprove it',
    failure: 'Several variables change at once and a temporary improvement is mistaken for root cause evidence',
    evidence: 'Record symptom, hypothesis, prediction, experiment, observed result, and the next narrowed possibility',
    boundary: 'multiple contributing causes can coexist, so disproving one hypothesis does not identify the complete cause',
    tradeoff: 'Disciplined experiments can feel slower initially but prevent broad speculative fixes and repeated incidents',
    verification: 'Recreate the failure with the suspected cause present and remove it while holding other conditions constant',
    outcome: 'Each investigation step reduces uncertainty and produces evidence another engineer can challenge',
    misconception: 'The most experienced debugger should trust intuition and patch the most likely cause immediately',
    operation: 'Preserve investigation timelines and disproven hypotheses for complex incidents',
    review: 'What observation would prove this hypothesis wrong, and is the experiment isolated enough to matter?',
  },
  {
    id: 'debugging-reproduction',
    title: 'Reproduction & Environment Capture',
    questionTarget: 20,
    principle: 'A reliable reproduction includes the smallest known inputs, sequence, state, and environment that trigger the symptom',
    scenario: 'A production-only failure cannot be reproduced because local runtime, feature flags, and data shape differ.',
    action: 'Capture the failing request and relevant versions, configuration, flags, dependency state, and sanitized data characteristics',
    failure: 'Investigators test a different system and conclude that an intermittent or environment-specific defect is fixed',
    evidence: 'Compare code and artifact identity, configuration, request sequence, data, dependency versions, region, and timing',
    boundary: 'private data and secrets must be minimized or transformed while preserving the behaviorally relevant shape',
    tradeoff: 'High-fidelity reproduction accelerates diagnosis but must balance production similarity with safety and cost',
    verification: 'Run the documented reproduction repeatedly in a clean environment and observe the same signature',
    outcome: 'The failure becomes an executable case rather than a story tied to one machine or moment',
    misconception: 'Matching the source commit is enough to reproduce a production environment',
    operation: 'Attach artifact, configuration, trace, and sanitized input identifiers to incident records',
    review: 'Which environmental or state difference could explain why the symptom appears only in one context?',
  },
  {
    id: 'debugging-minimization',
    title: 'Case Minimization & Bisection',
    questionTarget: 20,
    principle: 'Removing irrelevant inputs, steps, and changes reveals the smallest condition that still produces a failure',
    scenario: 'A crash occurs on a large import file containing thousands of records and many optional fields.',
    action: 'Systematically divide records and simplify fields while preserving the exact crash signature',
    failure: 'The minimized case loses the original cause or investigators spend time reasoning about unrelated complexity',
    evidence: 'Track each reduction, retained symptom, input difference, and the smallest causal combination found',
    boundary: 'order-dependent and multi-factor defects may require preserving a sequence or combination rather than one item',
    tradeoff: 'Minimization costs experiment time but sharply reduces the code and state that require explanation',
    verification: 'Show that adding or removing the final minimal condition toggles the failure predictably',
    outcome: 'A complex incident becomes a focused regression case and a clearer causal path',
    misconception: 'The smallest input that crashes must contain only one causal factor',
    operation: 'Save minimal reproductions with version and environment metadata for future regressions',
    review: 'What can be removed while preserving the same failure mechanism and signature?',
  },
  {
    id: 'errors-stack-traces',
    title: 'Errors, Exceptions & Stack Traces',
    questionTarget: 20,
    principle: 'An error should be read from its originating cause and contextual chain, not only from the final surface message',
    scenario: 'A request returns a generic internal error after three wrapped exceptions, and the team investigates only the controller frame.',
    action: 'Follow the cause chain to the first domain-relevant failure and inspect values and assumptions at that frame',
    failure: 'The visible wrapper is fixed or suppressed while the originating invalid state remains',
    evidence: 'Collect full stack, nested causes, error type, message, locals where safe, request context, and artifact version',
    boundary: 'async boundaries, minified builds, source maps, and cross-service propagation can obscure the original frame',
    tradeoff: 'Rich error context accelerates diagnosis but must avoid exposing secrets or high-cardinality private data',
    verification: 'Trigger the cause intentionally and confirm the error retains actionable context without leaking sensitive values',
    outcome: 'Investigators can connect a user-facing failure to the operation and violated assumption that produced it',
    misconception: 'The top line of a stack trace is always the location where the defect was introduced',
    operation: 'Group errors by stable fingerprint while preserving causes and deployment identity',
    review: 'Which frame first shows the system diverging from its contract, and what value reached it?',
  },
  {
    id: 'structured-logs',
    title: 'Structured Logs & Correlation',
    questionTarget: 16,
    principle: 'Logs should record queryable events with stable names, severity, and correlation across one operation',
    scenario: 'A request crosses four services, but each emits unrelated prose logs with no shared identifier.',
    action: 'Propagate a correlation or trace identifier and emit structured boundary events with outcome and duration',
    failure: 'Investigators cannot reconstruct one request or distinguish expected rejection from system failure',
    evidence: 'Inspect event schema, timestamps, levels, correlation fields, sampling, redaction, and service boundaries',
    boundary: 'background work and message fan-out need causation links rather than assuming one synchronous request ID',
    tradeoff: 'Detailed structured logs improve diagnosis but increase cost, privacy risk, and noise without deliberate schemas',
    verification: 'Trace a success and failure across services using only retained production-safe fields',
    outcome: 'Operators can reconstruct relevant chronology without searching arbitrary text from every host',
    misconception: 'Logging every variable at debug level guarantees enough information for production diagnosis',
    operation: 'Monitor log volume, dropped events, schema drift, redaction, and cardinality',
    review: 'Can this event be queried and connected to the operation while remaining safe to retain?',
  },
  {
    id: 'debugger-tools',
    title: 'Breakpoints, Watches & Stepping',
    questionTarget: 16,
    principle: 'Interactive debugging should stop at a discriminating point and inspect state transitions without accidentally changing timing or values',
    scenario: 'A developer steps through every line from program start while looking for a late incorrect balance.',
    action: 'Set a conditional breakpoint near the first violated invariant and watch the values that determine it',
    failure: 'The session produces too much noise or the debugger changes timing enough to hide the defect',
    evidence: 'Inspect call stack, locals, watches, breakpoint conditions, thread state, and values before and after the transition',
    boundary: 'race conditions and optimized code can behave differently when paused or may not expose expected variables',
    tradeoff: 'Breakpoints provide precise state inspection but are intrusive and difficult to apply across distributed production paths',
    verification: 'Confirm the same state transition through nonintrusive logs, traces, or a deterministic test',
    outcome: 'The debugger answers a focused question about where valid state becomes invalid',
    misconception: 'Stepping through more lines always provides more useful evidence',
    operation: 'Avoid attaching intrusive debuggers to sensitive production workloads without approved controls',
    review: 'At which exact statement can the competing hypotheses produce different observable state?',
  },
  {
    id: 'state-control-flow',
    title: 'State and Control-Flow Tracing',
    questionTarget: 20,
    principle: 'A state defect is isolated by tracing the value and branch decisions backward from the first incorrect observation',
    scenario: 'A discount becomes zero deep in checkout even though it was loaded correctly earlier.',
    action: 'Trace assignments, transformations, branch conditions, and aliases backward until the last known correct value',
    failure: 'Investigation starts at the final symptom and overlooks an earlier mutation or unexpected branch',
    evidence: 'Record value provenance, function inputs and outputs, assignments, condition outcomes, and shared references',
    boundary: 'mutable aliases, closures, retries, and asynchronous callbacks can change state outside the apparent local flow',
    tradeoff: 'Detailed tracing is powerful for one case but should become a focused assertion or instrumentation once the path is understood',
    verification: 'Re-run with a guard at the identified transition and confirm it catches the first invalid state',
    outcome: 'The investigation identifies the operation that changed correct state into the observed defect',
    misconception: 'The line where an invalid value is read is necessarily the line that created it',
    operation: 'Add durable invariant checks at high-value boundaries rather than retaining noisy temporary tracing',
    review: 'Where was this value last correct, and which assignment or branch can explain the transition?',
  },
  {
    id: 'change-isolation',
    title: 'Change and History Isolation',
    questionTarget: 16,
    principle: 'When behavior regresses, compare known good and bad versions and narrow the introducing change with a stable predicate',
    scenario: 'An API slows after a month of releases, and the team scans all recent pull requests manually.',
    action: 'Define a repeatable latency check and bisect deployed or reproducible revisions between known states',
    failure: 'A correlation with the latest visible change is treated as cause without controlling environment and data',
    evidence: 'Collect good and bad artifact IDs, configuration, benchmark inputs, history, and predicate results',
    boundary: 'database growth, feature flags, and external changes can create a regression without a source-code commit',
    tradeoff: 'History bisection is efficient for monotonic code regressions but less useful when the environment is the changing variable',
    verification: 'Apply or remove the candidate change under the same conditions and reproduce the performance difference',
    outcome: 'The introducing change or non-code transition is identified through repeatable comparison',
    misconception: 'The most recent commit before an incident is the most likely root cause',
    operation: 'Retain deploy manifests connecting source, artifact, configuration, flags, and migration versions',
    review: 'What known state separates good from bad, and is the classification independent of unrelated drift?',
  },
  {
    id: 'configuration-dependencies',
    title: 'Configuration and Dependency Diagnosis',
    questionTarget: 16,
    principle: 'Runtime behavior depends on resolved configuration and dependency identity, not only source code',
    scenario: 'One environment fails TLS requests because it loads a different certificate bundle despite running the same commit.',
    action: 'Diff effective non-secret configuration, runtime, dependency graph, trust store, and startup diagnostics',
    failure: 'A source patch masks an environment mismatch or changes a default without identifying the divergent input',
    evidence: 'Compare effective values and provenance, package locks, loaded modules, service endpoints, credentials metadata, and runtime flags',
    boundary: 'layered defaults, stale process state, dynamic configuration, and architecture-specific binaries can hide differences',
    tradeoff: 'Capturing effective configuration improves diagnosis but must redact secrets and avoid uncontrolled configuration dumps',
    verification: 'Change only the suspected resolved input and confirm the symptom follows it across environments',
    outcome: 'Environment-specific behavior is traced to a concrete versioned or observable runtime input',
    misconception: 'Two deployments of the same commit are equivalent environments',
    operation: 'Expose safe configuration fingerprints and dependency versions in health and deploy metadata',
    review: 'Which resolved input differs at runtime, and where did that value originate?',
  },
  {
    id: 'concurrency-debugging',
    title: 'Race Conditions & Concurrency Defects',
    questionTarget: 16,
    principle: 'Concurrency defects must be explained through a specific interleaving, shared state, and missing synchronization guarantee',
    scenario: 'Two workers both observe an unpaid invoice and each sends a charge before either marks it paid.',
    action: 'Capture the interleaving and enforce one atomic claim or idempotent transition around the shared invoice state',
    failure: 'Adding sleeps changes probability but does not remove the unsafe check-then-act sequence',
    evidence: 'Collect task and thread IDs, timestamps, locks, transaction boundaries, reads, writes, and side-effect keys',
    boundary: 'memory visibility, distributed workers, retries, and process crashes require different synchronization mechanisms',
    tradeoff: 'Stronger serialization simplifies correctness but can reduce throughput and increase contention',
    verification: 'Force the failing interleaving with barriers and repeat it after the synchronization fix',
    outcome: 'The system preserves its invariant for all relevant execution orders rather than one favorable schedule',
    misconception: 'A race is fixed when increasing a delay makes it stop appearing in tests',
    operation: 'Monitor duplicate effects, contention, retries, and invariant violations by operation identity',
    review: 'Which read and write can interleave, and what atomic guarantee prevents both actors from proceeding?',
  },
  {
    id: 'cpu-latency-profiling',
    title: 'CPU and Latency Profiling',
    questionTarget: 16,
    principle: 'Performance diagnosis should measure where representative elapsed and CPU time are actually spent before optimizing',
    scenario: 'A team rewrites a loop that looks inefficient, but requests spend most time waiting on repeated database calls.',
    action: 'Profile representative requests and separate CPU work, waits, call counts, and percentile latency',
    failure: 'An optimization targets visually complex code while the dominant cost remains elsewhere or shifts to another resource',
    evidence: 'Use profiles, traces, flame graphs, query timings, allocation data, throughput, and p50 through tail latency',
    boundary: 'debug builds, sampling bias, cold starts, cache state, and coordinated omission can distort measurements',
    tradeoff: 'Detailed profiling adds overhead, so production sampling and controlled load should match the question being answered',
    verification: 'Repeat the same workload before and after and compare total resource use and latency distribution',
    outcome: 'Optimization effort reduces a measured bottleneck without degrading correctness or another workload',
    misconception: 'The function with the longest source code is the most likely performance hotspot',
    operation: 'Track service-level percentiles and retain comparable profiles for major releases',
    review: 'What measured resource dominates user latency, and does the proposed change reduce that total cost?',
  },
  {
    id: 'memory-resource-debugging',
    title: 'Memory Leaks & Resource Exhaustion',
    questionTarget: 8,
    principle: 'Resource leaks are diagnosed by showing retained ownership or unclosed lifecycle across repeated equivalent work',
    scenario: 'Process memory grows after each completed request and does not return to a stable plateau.',
    action: 'Compare heap snapshots and allocation paths to identify objects retained by an unintended long-lived owner',
    failure: 'Memory, connections, files, or tasks accumulate until latency rises or the process is terminated',
    evidence: 'Inspect allocation rate, retained size, ownership graph, pool usage, open handles, garbage collections, and request count',
    boundary: 'allocator caching and legitimate warm caches can raise resident memory without being unbounded leaks',
    tradeoff: 'Detailed allocation tracing provides ownership evidence but can add high runtime overhead',
    verification: 'Repeat a fixed workload and demonstrate stable resource counts or bounded plateau after the fix',
    outcome: 'Completed work releases or bounds every resource according to an explicit lifecycle',
    misconception: 'Any process whose resident memory does not immediately fall has a memory leak',
    operation: 'Alert on sustained growth, pool saturation, open-handle counts, and termination reason',
    review: 'What object owns the resource after work completes, and why is that ownership still reachable?',
  },
  {
    id: 'database-debugging',
    title: 'Database and Query Diagnosis',
    questionTarget: 16,
    principle: 'Database incidents require separating query shape, plan, contention, data distribution, and infrastructure limits',
    scenario: 'A query becomes slow only for one tenant and the same SQL remains fast for small tenants.',
    action: 'Compare actual plans and row estimates for representative tenant parameters and inspect skew and blocking',
    failure: 'A global index or timeout change treats a parameter-specific plan, lock wait, or data-shape problem as generic slowness',
    evidence: 'Collect query fingerprint, actual plan, parameters, rows, I/O, waits, locks, statistics, and connection-pool state',
    boundary: 'cached plans and warm buffers can make the first diagnostic run differ from the incident path',
    tradeoff: 'Capturing full parameters improves reproduction but requires strict handling of sensitive query values',
    verification: 'Replay a sanitized representative workload and confirm both plan and total work improve',
    outcome: 'The database bottleneck is linked to a measured access path, wait, or capacity constraint',
    misconception: 'Every slow query needs another index',
    operation: 'Monitor slow fingerprints, plan regressions, lock waits, pool saturation, and replication lag',
    review: 'Is time spent executing, waiting, transferring, or acquiring a connection, and what evidence separates them?',
  },
  {
    id: 'distributed-debugging',
    title: 'Network and Distributed Failures',
    questionTarget: 16,
    principle: 'Distributed diagnosis should locate the failing boundary and distinguish timeout, rejection, loss, duplication, and partial completion',
    scenario: 'A caller times out, retries, and creates two orders because the first server completed after the connection closed.',
    action: 'Correlate both attempts and use idempotent operation identity while tracing client, proxy, server, and persistence timing',
    failure: 'A generic network error hides whether work was never received, still running, completed, or acknowledged late',
    evidence: 'Collect trace spans, DNS and connection timing, retry metadata, status, queueing, server logs, and side-effect identity',
    boundary: 'clock skew, sampling, proxy retries, region routing, and asynchronous work complicate chronological reconstruction',
    tradeoff: 'Longer timeouts may reduce visible failures but consume resources and delay recovery from genuinely stuck work',
    verification: 'Inject loss, delay, reset, duplicate delivery, and partial availability and assert bounded safe behavior',
    outcome: 'Failures are attributed to a specific boundary and uncertain completion does not corrupt state',
    misconception: 'A client timeout proves the server did not complete the operation',
    operation: 'Monitor boundary-specific error rates, retry amplification, saturation, and trace gaps',
    review: 'What does each participant know about completion, and which identifier links all attempts?',
  },
  {
    id: 'incident-stabilization',
    title: 'Incident Stabilization & Rollback',
    questionTarget: 20,
    principle: 'During an incident, first reduce user harm and prevent amplification before pursuing complete causal explanation',
    scenario: 'A release drives database saturation while investigators continue profiling it under full production traffic.',
    action: 'Pause rollout or disable the feature, shed noncritical load, and restore capacity before deeper diagnosis',
    failure: 'Diagnostic activity delays mitigation and escalating retries or queues expand the blast radius',
    evidence: 'Track user impact, saturation, error and latency rates, deployment changes, mitigation actions, and recovery trend',
    boundary: 'rollback may be unsafe after incompatible migrations or external effects and can require a forward mitigation',
    tradeoff: 'Mitigation can remove evidence or defer learning, so capture essential state without allowing harm to continue',
    verification: 'Confirm guardrail recovery after each mitigation and watch for delayed queue or data consequences',
    outcome: 'Service impact is bounded quickly while enough evidence remains for disciplined follow-up',
    misconception: 'Root cause must be known before traffic can be reduced or a release rolled back',
    operation: 'Assign incident command, log decisions, define stop conditions, and communicate current impact clearly',
    review: 'Which reversible action most quickly lowers harm without creating a worse consistency problem?',
  },
  {
    id: 'observability-debugging',
    title: 'Metrics, Traces & Observability',
    questionTarget: 16,
    principle: 'Metrics reveal aggregate change, traces connect one distributed path, and logs explain discrete events; diagnosis combines them intentionally',
    scenario: 'A latency dashboard rises, but no route, tenant, dependency, or release dimension can narrow the affected population.',
    action: 'Use bounded dimensions to segment the metric, then inspect representative traces and correlated events',
    failure: 'Telemetry is abundant but cannot answer who is affected, where time is spent, or what changed',
    evidence: 'Inspect service indicators, dimensions, exemplars, trace coverage, event schema, sampling, and deployment markers',
    boundary: 'high-cardinality identifiers belong in traces or logs rather than unbounded metric labels',
    tradeoff: 'More telemetry increases diagnostic power but also cost, privacy exposure, and operational complexity',
    verification: 'Start a controlled failure and confirm dashboards detect it and lead to the responsible boundary',
    outcome: 'Operators move from impact signal to causal evidence without instrumenting blindly during every incident',
    misconception: 'Collecting all logs provides the same diagnostic capability as metrics and distributed traces',
    operation: 'Monitor telemetry loss, ingestion delay, sampling, cardinality, cost, and schema ownership',
    review: 'Which question does this signal answer, and can it connect impact to a specific operation and version?',
  },
  {
    id: 'root-cause-analysis',
    title: 'Root-Cause and Contributing-Factor Analysis',
    questionTarget: 20,
    principle: 'A useful root-cause analysis explains the causal chain and systemic conditions that allowed impact, not only the triggering action',
    scenario: 'An incident report says an engineer deployed bad code and stops without examining missing validation or rollout controls.',
    action: 'Build an evidence-backed timeline and ask why safeguards failed across design, review, testing, delivery, and response',
    failure: 'The organization blames the last actor, applies a local patch, and leaves the same class of failure available',
    evidence: 'Use timelines, code and config changes, system signals, decisions, defenses, detection gaps, and counterfactual tests',
    boundary: 'several necessary causes can combine, and not every correlated condition is causally relevant',
    tradeoff: 'Deep analysis consumes time but should focus on high-leverage prevention rather than exhaustive narrative',
    verification: 'Test whether removing each claimed causal factor would have prevented or materially reduced the observed impact',
    outcome: 'Follow-up work strengthens system defenses and decision quality instead of assigning individual fault',
    misconception: 'The root cause is always the single code change closest in time to the incident',
    operation: 'Assign prioritized actions with owners and verify completion and effectiveness later',
    review: 'Which defenses should have prevented, detected, or limited this event, and why did each fail?',
  },
  {
    id: 'regression-prevention',
    title: 'Regression Prevention',
    questionTarget: 20,
    principle: 'A fix is complete when it corrects the cause and adds proportionate protection against recurrence',
    scenario: 'A parser crash is patched for one payload but no boundary test, validation, or production signal is added.',
    action: 'Create a minimal failing regression, fix the general invalid-state path, and add a signal for related failures',
    failure: 'The exact example works while nearby inputs or another entry point reproduce the same defect class',
    evidence: 'Compare original reproduction, generalized invariant, fix scope, regression tests, static checks, and operational detection',
    boundary: 'overly broad prevention can reject valid inputs or add expensive checks to every request',
    tradeoff: 'Layered prevention costs maintenance but can stop defects earlier and shorten detection if one defense fails',
    verification: 'Reintroduce the defect or mutate the relevant condition and confirm the new defenses fail visibly',
    outcome: 'The repaired system detects or prevents the underlying failure class at an appropriate boundary',
    misconception: 'Once the reported input passes, the debugging task is finished',
    operation: 'Track recurrence and related error signatures to evaluate whether corrective actions work',
    review: 'Does this change prevent the causal class or only special-case the observed example?',
  },
  {
    id: 'postmortems-runbooks',
    title: 'Postmortems & Runbooks',
    questionTarget: 12,
    principle: 'Postmortems preserve causal learning, while runbooks turn likely operational decisions into tested executable guidance',
    scenario: 'An incident document lists a timeline but no detection gap, decision rationale, owner, or updated response procedure.',
    action: 'Document impact and causes, prioritize actions, and update a runbook with signals, commands, safeguards, and escalation',
    failure: 'Knowledge remains with responders and the next incident repeats slow or unsafe diagnostic steps',
    evidence: 'Review impact measures, timeline sources, causal analysis, action ownership, runbook rehearsal, and revision date',
    boundary: 'a runbook must include stop conditions and escalation when an automated action can worsen state',
    tradeoff: 'Detailed documentation adds upkeep, so it should focus on high-risk decisions and verifiable procedures',
    verification: 'Have an uninvolved engineer execute the runbook in a simulation and record ambiguities or unsafe steps',
    outcome: 'Incident learning changes future system behavior and response rather than becoming an archived narrative',
    misconception: 'A postmortem is complete when it identifies who made the triggering change',
    operation: 'Review overdue actions and rehearse critical runbooks after architecture or ownership changes',
    review: 'Could an on-call engineer recognize this condition and act safely using only the current runbook?',
  },
  {
    id: 'nondeterministic-debugging',
    title: 'Nondeterministic & Timing-Sensitive Defects',
    questionTarget: 16,
    principle: 'Nondeterministic defects become tractable when random seeds, schedules, time, order, and external state are captured or controlled',
    scenario: 'A test fails only in CI under parallel load and disappears whenever extensive logging is enabled.',
    action: 'Capture order and seed, control synchronization, vary load systematically, and use low-overhead event tracing',
    failure: 'Instrumentation changes the schedule or repeated retries obscure the condition that triggers the defect',
    evidence: 'Collect seed, execution order, scheduler and thread state, timestamps, resource pressure, and the minimal failure signature',
    boundary: 'observer effects and rare multi-event sequences may require stress plus deterministic replay',
    tradeoff: 'Deterministic control may require test-only seams, while production sampling preserves realism with less certainty',
    verification: 'Replay the captured condition reliably and show the fix survives stress across varied schedules',
    outcome: 'An intermittent symptom is converted into a repeatable causal schedule or state transition',
    misconception: 'A failure that cannot be reproduced on demand is probably environmental noise rather than a product defect',
    operation: 'Persist seeds, orders, trace IDs, and quarantine ownership for every intermittent failure',
    review: 'Which uncontrolled source changes between passing and failing runs, and how can it be recorded or forced?',
  },
] satisfies readonly SoftwareMasteryTopicBlueprint[]

export const debuggingMasteryTopics = defineSoftwareMasteryTopics(
  'debugging',
  debuggingBlueprints,
)