import {
  defineLearningMasteryTopics,
  type LearningMasteryTopicSeed,
} from './learning-model'

const allPlatforms = ['Turing', 'Andela', 'Toptal'] as const

const programmingFundamentalsTopics = [
  {
    id: 'variables',
    title: 'Variables',
    masteryLevel: 'L1',
    frequency: 'frequent',
    questionTarget: 10,
    questions: [
      {
        prompt: 'What does assignment do in Python when `attempts = 3` runs?',
        options: [
          'It binds the name attempts to the integer value 3',
          'It permanently declares attempts as an integer',
          'It copies 3 into a fixed memory slot named attempts',
          'It converts any previous value of attempts into an integer',
        ],
        correctOptionIndex: 0,
        explanation: 'Python assignment binds a name to an object. A later assignment can rebind the same name to another object or type.',
        difficulty: 'easy',
        platforms: allPlatforms,
      },
      {
        prompt: 'Which name best communicates a timeout value measured in seconds?',
        options: ['t', 'delay', 'timeout_seconds', 'timeoutValue'],
        correctOptionIndex: 2,
        explanation: 'A domain name that includes the unit prevents ambiguity and seconds-versus-milliseconds defects.',
        difficulty: 'easy',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'After `first = second = []` and `first.append(7)`, what is `second`?',
        options: ['[]', '[7]', '7', 'A NameError is raised'],
        correctOptionIndex: 1,
        explanation: 'Both names are bound to the same mutable list, so mutation through either name is visible through the other.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'What are `left` and `right` after `left, right = right, left`?',
        options: [
          'Their previous values are swapped',
          'Both contain the previous value of left',
          'Both contain the previous value of right',
          'Python rejects simultaneous assignment',
        ],
        correctOptionIndex: 0,
        explanation: 'Python evaluates the right-hand side first and then unpacks those values into the names on the left.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'A service handles concurrent requests. Where should a request-specific `tenant_id` normally live?',
        options: [
          'In a module-level variable',
          'In the request scope and explicit function arguments',
          'In a class variable shared by every handler',
          'In the imported settings module',
        ],
        correctOptionIndex: 1,
        explanation: 'Request-scoped state prevents one request from overwriting state used by another and makes dependencies visible.',
        difficulty: 'medium',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'What does `print(previous)` output after `current = 10; previous = current; current = 11`?',
        options: ['10', '11', 'None', 'A NameError is raised'],
        correctOptionIndex: 0,
        explanation: 'Rebinding current to a new integer does not change the object still referenced by previous.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'What are the values after `head, *middle, tail = [1, 2, 3, 4]`?',
        options: [
          '`head == 1`, `middle == [2, 3]`, and `tail == 4`',
          '`head == 1`, `middle == (2, 3)`, and `tail == 4`',
          '`head == [1]`, `middle == [2, 3]`, and `tail == [4]`',
          'The assignment raises ValueError',
        ],
        correctOptionIndex: 0,
        explanation: 'A starred assignment target collects the unmatched values into a new list.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'What runtime guarantee does `count: int = "3"` provide in ordinary Python execution?',
        options: [
          'It converts the string to an integer',
          'It raises TypeError immediately',
          'It stores the string; the annotation is not runtime enforcement by itself',
          'It prevents count from being rebound',
        ],
        correctOptionIndex: 2,
        explanation: 'Type annotations support tools and documentation but do not enforce assignments during ordinary execution.',
        difficulty: 'medium',
        platforms: allPlatforms,
      },
      {
        prompt: 'What happens when `del token` is followed by an attempt to evaluate `token` in the same scope?',
        options: [
          'The previous value is returned',
          'The name is no longer bound, so evaluating it raises NameError',
          'The name automatically becomes None',
          'The value is converted to an empty string',
        ],
        correctOptionIndex: 1,
        explanation: '`del` removes the binding from that scope; it does not assign a replacement value.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'Which name best follows Python convention for a module-level value that callers should treat as constant?',
        options: ['maxRetries', 'max_retries', 'MAX_RETRIES', '_MaxRetries'],
        correctOptionIndex: 2,
        explanation: 'Uppercase words separated by underscores conventionally signal a constant, though Python does not enforce immutability.',
        difficulty: 'easy',
        platforms: ['Andela', 'Toptal'],
      },
    ],
  },
  {
    id: 'data-types',
    title: 'Data types',
    masteryLevel: 'L1',
    frequency: 'core',
    questionTarget: 15,
    questions: [
      {
        prompt: 'Which value is a floating-point number in Python?',
        options: ['"4.5"', '4', '4.5', 'False'],
        correctOptionIndex: 2,
        explanation: '`4.5` is a float; quotes would make it a string and `4` is an integer.',
        difficulty: 'easy',
        platforms: allPlatforms,
      },
      {
        prompt: 'Why should an API amount received as `"125.50"` be converted before arithmetic?',
        options: [
          'Strings use more memory than numbers in every case',
          'Its external representation does not yet guarantee numeric behavior or validity',
          'Python automatically rounds all strings',
          'Conversion makes validation unnecessary',
        ],
        correctOptionIndex: 1,
        explanation: 'External text must be validated and converted so internal logic receives a value with the required numeric meaning.',
        difficulty: 'medium',
        platforms: allPlatforms,
      },
      {
        prompt: 'Which statement about `None` is correct?',
        options: [
          'It is the same value as zero',
          'It is an empty string alias',
          'It is a singleton commonly used to represent absence',
          'It is equal to every falsy value',
        ],
        correctOptionIndex: 2,
        explanation: '`None` has its own type and represents absence; it is distinct from zero, false, and empty collections.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'Which value can safely be used as a dictionary key?',
        options: ['[1, 2]', '{"id": 1}', '{1, 2}', '(1, 2)'],
        correctOptionIndex: 3,
        explanation: 'Dictionary keys must be hashable. A tuple of integers is hashable, while lists, dictionaries, and sets are mutable and unhashable.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'What is the safest boundary check for a required non-negative integer quantity?',
        options: [
          'Use the incoming value directly because JSON is typed',
          'Call `int(value)` and accept every result',
          'Validate presence and representation, convert it, then verify the numeric range',
          'Check only whether the value is truthy',
        ],
        correctOptionIndex: 2,
        explanation: 'Boundary validation must distinguish absence, malformed input, and invalid ranges before trusted business logic runs.',
        difficulty: 'hard',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'What does `type(True).__name__` return?',
        options: ['"int"', '"bool"', '"truth"', '"object"'],
        correctOptionIndex: 1,
        explanation: '`True` is an instance of Python\'s bool type.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'What is the result of `bool("False")`?',
        options: ['False', 'True', 'None', 'A ValueError is raised'],
        correctOptionIndex: 1,
        explanation: 'Any nonempty string is truthy; bool does not parse the text as a boolean word.',
        difficulty: 'easy',
        platforms: allPlatforms,
      },
      {
        prompt: 'What value and type result from `5 / 2` in Python 3?',
        options: ['The integer 2', 'The float 2.5', 'The integer 3', 'A TypeError is raised'],
        correctOptionIndex: 1,
        explanation: 'The `/` operator performs true division and returns a float for these integer operands.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'What is the result of `5 // 2`?',
        options: ['2', '2.5', '3', '0'],
        correctOptionIndex: 0,
        explanation: 'Floor division returns the greatest integer not exceeding the mathematical quotient.',
        difficulty: 'easy',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'What happens when Python evaluates `3 + "4"`?',
        options: ['It returns 7', 'It returns "34"', 'It raises TypeError', 'It returns 3.0'],
        correctOptionIndex: 2,
        explanation: 'Python does not implicitly choose numeric addition or string concatenation for mixed int and str operands.',
        difficulty: 'easy',
        platforms: allPlatforms,
      },
      {
        prompt: 'What does `int("08")` return when no base argument is supplied?',
        options: ['8', '0', 'The string "8"', 'A ValueError is raised'],
        correctOptionIndex: 0,
        explanation: 'With the default base 10, leading zeroes do not make this string invalid.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Why can `0.1 + 0.2 == 0.3` evaluate to False?',
        options: [
          'Float addition is random',
          'Most decimal fractions are approximated in binary floating-point',
          'Equality cannot compare floats',
          'Python rounds every float to an integer',
        ],
        correctOptionIndex: 1,
        explanation: 'Binary floating-point approximations can introduce a small representation difference in exact comparisons.',
        difficulty: 'medium',
        platforms: allPlatforms,
      },
      {
        prompt: 'Which construction best preserves an exact decimal amount supplied as the text `"19.99"`?',
        options: [
          '`Decimal("19.99")`',
          '`Decimal(19.99)`',
          '`float("19.99")`',
          '`round(19.99)`',
        ],
        correctOptionIndex: 0,
        explanation: 'Constructing Decimal from the original text avoids first importing a binary float approximation.',
        difficulty: 'medium',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'A network client returns bytes known to be UTF-8 text. Which operation produces a Python string?',
        options: [
          '`payload.decode("utf-8")`',
          '`payload.encode("utf-8")`',
          '`bytes(payload)`',
          '`payload.to_string()`',
        ],
        correctOptionIndex: 0,
        explanation: 'Decoding interprets a byte sequence using the specified character encoding and returns str.',
        difficulty: 'medium',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'What does `isinstance(True, int)` return in Python?',
        options: ['True', 'False', 'None', 'It raises TypeError'],
        correctOptionIndex: 0,
        explanation: 'bool is a subclass of int in Python, even though bool remains its own distinct type.',
        difficulty: 'hard',
        platforms: ['Turing', 'Toptal'],
      },
    ],
  },
  {
    id: 'strings',
    title: 'Strings',
    masteryLevel: 'L1',
    frequency: 'frequent',
    questionTarget: 10,
    questions: [
      {
        prompt: 'What is the result of `"interview"[0:5]`?',
        options: ['inter', 'interv', 'nterv', 'view'],
        correctOptionIndex: 0,
        explanation: 'A slice includes the start index and excludes the stop index, producing the first five characters.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'Why can `name[0] = "A"` not update a Python string?',
        options: [
          'Strings are unordered',
          'Strings are immutable',
          'String indexes start at one',
          'Only numeric strings support indexing',
        ],
        correctOptionIndex: 1,
        explanation: 'Strings cannot be changed in place. Build and bind a new string when a transformed value is required.',
        difficulty: 'easy',
        platforms: allPlatforms,
      },
      {
        prompt: 'Which expression efficiently combines `words` with one space between items?',
        options: ['words.join(" ")', '`" ".join(words)`', 'str(words)', 'words + " "'],
        correctOptionIndex: 1,
        explanation: '`separator.join(iterable)` expresses the operation directly and avoids repeated string concatenation.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'What does `"  paid  ".strip()` return?',
        options: ['"paid"', '"  paid"', '"paid  "', '"  paid  "'],
        correctOptionIndex: 0,
        explanation: '`strip` returns a new string with leading and trailing whitespace removed.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'Which formatting choice most clearly produces `Invoice INV-7: $12.50` from an ID and numeric amount?',
        options: [
          '`f"Invoice {invoice_id}: ${amount:.2f}"`',
          '`"Invoice " + invoice_id + amount`',
          '`str(invoice_id, amount)`',
          '`"Invoice %s" % (invoice_id, amount)`',
        ],
        correctOptionIndex: 0,
        explanation: 'An f-string names the inserted values and `.2f` makes the two-decimal display requirement explicit.',
        difficulty: 'medium',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'What does `"contract"[-1]` return?',
        options: ['"c"', '"t"', '"contract"', 'An IndexError is raised'],
        correctOptionIndex: 1,
        explanation: 'Index -1 addresses the final character of a nonempty sequence.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'What is the result of `"a,b,c".split(",", 1)`?',
        options: ['["a", "b", "c"]', '["a", "b,c"]', '["a,b", "c"]', '["a,b,c"]'],
        correctOptionIndex: 1,
        explanation: 'A maxsplit of 1 performs only the first split and leaves the remaining separator in the second item.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'After `text = "one one"; changed = text.replace("one", "two")`, what are the values?',
        options: [
          '`text == "one one"` and `changed == "two two"`',
          '`text == "two two"` and `changed == "two two"`',
          '`text == "one one"` and `changed == "two one"`',
          'replace raises because strings are immutable',
        ],
        correctOptionIndex: 0,
        explanation: 'replace returns a new string and, without a count limit, replaces every nonoverlapping occurrence.',
        difficulty: 'medium',
        platforms: allPlatforms,
      },
      {
        prompt: 'Which method is designed for aggressive caseless comparison of user text across writing systems?',
        options: ['casefold()', 'capitalize()', 'swapcase()', 'center()'],
        correctOptionIndex: 0,
        explanation: 'casefold performs stronger Unicode case normalization than lower and is intended for caseless matching.',
        difficulty: 'medium',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'How does `text.find("missing")` differ from `text.index("missing")`?',
        options: [
          'find returns -1, while index raises ValueError',
          'find raises ValueError, while index returns -1',
          'Both return None',
          'Both append the missing text',
        ],
        correctOptionIndex: 0,
        explanation: 'find uses -1 as its not-found result, whereas index treats absence as an error.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
    ],
  },
  {
    id: 'lists',
    title: 'Lists',
    masteryLevel: 'L1',
    frequency: 'core',
    questionTarget: 15,
    questions: [
      {
        prompt: 'What is `values` after `values = [1, 2]` followed by `values.append([3, 4])`?',
        options: ['[1, 2, 3, 4]', '[1, 2, [3, 4]]', '[[1, 2], [3, 4]]', '[3, 4]'],
        correctOptionIndex: 1,
        explanation: '`append` adds its argument as one new element; `extend` would add each element from the iterable.',
        difficulty: 'easy',
        platforms: allPlatforms,
      },
      {
        prompt: 'Given `copy = original[:]`, which statement is correct?',
        options: [
          'copy and original are the same list object',
          'copy is a shallow new list whose nested objects may still be shared',
          'copy is a recursively deep copy',
          'The slice empties original',
        ],
        correctOptionIndex: 1,
        explanation: 'A full slice creates a shallow list copy. It separates the outer list but does not recursively copy nested mutable values.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Which operation is usually most expensive as a Python list grows?',
        options: [
          'Reading `items[-1]`',
          'Appending one item at the end',
          'Inserting one item at index zero',
          'Checking the list length',
        ],
        correctOptionIndex: 2,
        explanation: 'Front insertion shifts existing references and is linear, while indexed access and length are constant time and append is amortized constant time.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Which comprehension returns the squares of only even values in `numbers`?',
        options: [
          '`[number ** 2 for number in numbers if number % 2 == 0]`',
          '`[number for number ** 2 in numbers]`',
          '`[if number % 2 == 0: number ** 2]`',
          '`[number % 2 == 0 for number ** 2 in numbers]`',
        ],
        correctOptionIndex: 0,
        explanation: 'The expression comes first, followed by iteration and then the filtering condition.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'A queue repeatedly removes its oldest item. Which design avoids costly `list.pop(0)` shifts?',
        options: [
          'Sort the list before each removal',
          'Use `collections.deque` and `popleft()`',
          'Reverse the list after every append',
          'Convert every item to a tuple',
        ],
        correctOptionIndex: 1,
        explanation: 'A deque supports efficient operations at both ends and communicates queue semantics directly.',
        difficulty: 'medium',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'After `items = [1, 2, 3]; removed = items.pop()`, what are `items` and `removed`?',
        options: [
          '`items == [1, 2]` and `removed == 3`',
          '`items == [2, 3]` and `removed == 1`',
          '`items == [1, 2, 3]` and `removed == 3`',
          '`items == [1, 2]` and `removed is None`',
        ],
        correctOptionIndex: 0,
        explanation: 'With no index, pop removes and returns the final list element.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'What is assigned to `result` by `result = numbers.sort()`?',
        options: ['The sorted list', 'A tuple of sorted values', 'None', 'The original unsorted list'],
        correctOptionIndex: 2,
        explanation: 'list.sort mutates the list in place and returns None to make that side effect explicit.',
        difficulty: 'easy',
        platforms: allPlatforms,
      },
      {
        prompt: 'Which expression returns sorted values without changing the original list `records`?',
        options: ['`sorted(records)`', '`records.sort()`', '`records.reverse()`', '`records.append(sorted)`'],
        correctOptionIndex: 0,
        explanation: 'sorted consumes an iterable and returns a new list, leaving the source list unchanged.',
        difficulty: 'easy',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Why is `grid = [[0] * 2] * 3` unsafe when rows must be updated independently?',
        options: [
          'It creates three references to the same inner list',
          'It creates immutable rows',
          'It produces only two rows',
          'It fills each row with strings',
        ],
        correctOptionIndex: 0,
        explanation: 'Repeating the outer list copies references, so mutating one row is visible through every row alias.',
        difficulty: 'medium',
        platforms: allPlatforms,
      },
      {
        prompt: 'What is `values` after `values = [1, 4]; values[1:1] = [2, 3]`?',
        options: ['[1, 2, 3, 4]', '[1, [2, 3], 4]', '[2, 3]', '[1, 4, 2, 3]'],
        correctOptionIndex: 0,
        explanation: 'Assigning to an empty slice inserts each replacement element at that position.',
        difficulty: 'medium',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'What is the average-case time complexity of testing `target in items` for a general Python list?',
        options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
        correctOptionIndex: 2,
        explanation: 'List membership may compare the target with each element in sequence, so its cost grows linearly.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Which expression returns a reversed shallow copy of `items`?',
        options: ['`items[::-1]`', '`items[-1]`', '`items[1:]`', '`items.reverse`'],
        correctOptionIndex: 0,
        explanation: 'A slice with step -1 traverses the sequence backward into a new list.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'What does `items.remove(value)` do when value occurs more than once?',
        options: [
          'Removes the first equal occurrence',
          'Removes every equal occurrence',
          'Removes the final list element',
          'Returns a new filtered list',
        ],
        correctOptionIndex: 0,
        explanation: 'remove mutates the list by deleting the first matching value and raises ValueError if none exists.',
        difficulty: 'easy',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Why can repeatedly executing `result = result + [item]` become quadratic while building a large list?',
        options: [
          'Each concatenation copies the accumulated elements into a new list',
          'List addition sorts both operands',
          'Single-item lists cannot be allocated efficiently',
          'The operation scans every object in memory',
        ],
        correctOptionIndex: 0,
        explanation: 'Repeatedly copying an ever-growing prefix accumulates quadratic work; append avoids those full copies.',
        difficulty: 'hard',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'What is returned by `[1, 2][10:20]`?',
        options: ['[]', 'None', '[2]', 'An IndexError is raised'],
        correctOptionIndex: 0,
        explanation: 'An out-of-range slice is clipped to valid boundaries and returns an empty list here.',
        difficulty: 'medium',
        platforms: allPlatforms,
      },
    ],
  },
  {
    id: 'tuples',
    title: 'Tuples',
    masteryLevel: 'L1',
    frequency: 'targeted',
    questionTarget: 5,
    questions: [
      {
        prompt: 'Which expression creates a one-item tuple?',
        options: ['(7)', '(7,)', '[7]', '{7}'],
        correctOptionIndex: 1,
        explanation: 'The comma creates a tuple; parentheses alone only group the expression.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'What happens in `status, code = ("ok", 200)`?',
        options: [
          'The tuple is unpacked into two names',
          'Both names receive the full tuple',
          'Only status is assigned',
          'A tuple cannot be unpacked',
        ],
        correctOptionIndex: 0,
        explanation: 'Iterable unpacking binds corresponding tuple elements to the names on the left.',
        difficulty: 'easy',
        platforms: allPlatforms,
      },
      {
        prompt: 'When is a tuple a stronger choice than a list?',
        options: [
          'When items must be appended frequently',
          'When the ordered record should have a fixed, non-mutating shape',
          'When every item must be unique',
          'When values need lookup by named key',
        ],
        correctOptionIndex: 1,
        explanation: 'A tuple communicates that its ordered collection is fixed rather than an evolving sequence.',
        difficulty: 'easy',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'Which tuple can be used as a set member?',
        options: ['([1], 2)', '({1}, 2)', '({"id": 1}, 2)', '((1, 2), 3)'],
        correctOptionIndex: 3,
        explanation: 'A tuple is hashable only when every element it contains is hashable; nested tuples of integers satisfy that rule.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'A function executes `return total, count`. What does the caller receive?',
        options: ['Two separate return operations', 'A two-item tuple', 'A list', 'A generator'],
        correctOptionIndex: 1,
        explanation: 'Comma-separated return values are packaged as a tuple, which the caller may unpack.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
    ],
  },
  {
    id: 'sets',
    title: 'Sets',
    masteryLevel: 'L1',
    frequency: 'frequent',
    questionTarget: 10,
    questions: [
      {
        prompt: 'What is the main behavioral guarantee of a set?',
        options: [
          'Values remain sorted',
          'Values are unique',
          'Values are accessed by numeric index',
          'Values may be unhashable',
        ],
        correctOptionIndex: 1,
        explanation: 'A set contains unique hashable values and is designed for membership and set-algebra operations.',
        difficulty: 'easy',
        platforms: allPlatforms,
      },
      {
        prompt: 'Which expression finds IDs present in both `active_ids` and `paid_ids`?',
        options: ['active_ids | paid_ids', 'active_ids - paid_ids', 'active_ids & paid_ids', 'active_ids ^ paid_ids'],
        correctOptionIndex: 2,
        explanation: 'Set intersection with `&` returns values shared by both sets.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'Why is a set useful for detecting duplicate transaction IDs in one pass?',
        options: [
          'It sorts each ID automatically',
          'It provides average constant-time membership checks',
          'It stores a count for every ID',
          'It accepts mutable IDs',
        ],
        correctOptionIndex: 1,
        explanation: 'Check whether an ID has already been seen, then add it. Average constant-time membership supports a linear scan overall.',
        difficulty: 'medium',
        platforms: allPlatforms,
      },
      {
        prompt: 'Which value cannot be added to a set?',
        options: ['"client-7"', '42', '(4, 2)', '[4, 2]'],
        correctOptionIndex: 3,
        explanation: 'Set members must be hashable. A mutable list is unhashable, while the other values are hashable.',
        difficulty: 'easy',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'A report needs unique email addresses in first-seen order. What is the safest approach?',
        options: [
          'Convert directly to a set and rely on its display order',
          'Track a seen set while appending first occurrences to a list',
          'Sort a set and claim it preserves arrival order',
          'Use only a tuple because tuples remove duplicates',
        ],
        correctOptionIndex: 1,
        explanation: 'The set provides membership checks while the list explicitly preserves first-seen order.',
        difficulty: 'medium',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'Which expression returns every value present in either set `left` or set `right`?',
        options: ['`left | right`', '`left & right`', '`left - right`', '`left <= right`'],
        correctOptionIndex: 0,
        explanation: 'The union operator returns the distinct members found in either operand.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'What does `expected - received` represent when both names refer to sets?',
        options: [
          'Values required by expected but absent from received',
          'Values shared by both sets',
          'Values present only in received',
          'All values from both sets',
        ],
        correctOptionIndex: 0,
        explanation: 'Set difference keeps members of the left operand that are not in the right operand.',
        difficulty: 'easy',
        platforms: allPlatforms,
      },
      {
        prompt: 'Which expression creates an empty set?',
        options: ['`set()`', '`{}`', '`[]`', '`()`'],
        correctOptionIndex: 0,
        explanation: 'Empty braces create a dictionary, so an empty set requires the set constructor.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'Which operation removes `user_id` from a set without raising if it is already absent?',
        options: ['`user_ids.discard(user_id)`', '`user_ids.remove(user_id)`', '`user_ids.pop(user_id)`', '`del user_ids[user_id]`'],
        correctOptionIndex: 0,
        explanation: 'discard is a no-op for a missing member, while remove raises KeyError.',
        difficulty: 'medium',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'When is `frozenset` preferable to `set`?',
        options: [
          'When the collection must be hashable and remain immutable',
          'When members need numeric indexes',
          'When duplicate members must be preserved',
          'When values must be appended in order',
        ],
        correctOptionIndex: 0,
        explanation: 'A frozenset cannot be mutated and can therefore serve as a mapping key or another set member when its elements are hashable.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
    ],
  },
  {
    id: 'dictionaries',
    title: 'Dictionaries',
    masteryLevel: 'L1',
    frequency: 'core',
    questionTarget: 15,
    questions: [
      {
        prompt: 'What is the key difference between `record["email"]` and `record.get("email")` when the key is absent?',
        options: [
          'Both always raise KeyError',
          'Indexing raises KeyError while get returns None by default',
          'get raises KeyError while indexing returns None',
          'Both insert the missing key',
        ],
        correctOptionIndex: 1,
        explanation: 'Direct indexing requires the key. `get` permits a missing key and returns its optional default.',
        difficulty: 'easy',
        platforms: allPlatforms,
      },
      {
        prompt: 'What does assigning `prices["pro"] = 25` do when `"pro"` already exists?',
        options: [
          'Adds a second pro key',
          'Raises DuplicateKeyError',
          'Replaces the value for the existing key',
          'Leaves the dictionary unchanged',
        ],
        correctOptionIndex: 2,
        explanation: 'Dictionary keys are unique; assigning an existing key updates its associated value.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'Which loop directly receives both keys and values from `counts`?',
        options: [
          '`for key, value in counts.items():`',
          '`for key, value in counts:`',
          '`for key in counts.values():`',
          '`for value in counts.keys():`',
        ],
        correctOptionIndex: 0,
        explanation: '`items()` yields key-value pairs suitable for unpacking in each iteration.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'How can a reconciliation job avoid scanning every local transaction for each provider row?',
        options: [
          'Index local transactions in a dictionary by provider ID',
          'Convert every transaction to a string',
          'Use a nested loop and break later',
          'Reverse both input lists',
        ],
        correctOptionIndex: 0,
        explanation: 'A dictionary index trades memory for direct average constant-time lookup, reducing nested linear scans.',
        difficulty: 'medium',
        platforms: allPlatforms,
      },
      {
        prompt: 'Which expression counts a new event type without first checking whether its key exists?',
        options: [
          '`counts[event] = counts.get(event, 0) + 1`',
          '`counts[event] + 1`',
          '`counts.get(event) += 1`',
          '`counts[event].append(1)`',
        ],
        correctOptionIndex: 0,
        explanation: '`get(event, 0)` supplies the initial zero while preserving the same update expression for existing keys.',
        difficulty: 'medium',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'What does the expression `"id" in record` test for a dictionary?',
        options: [
          'Whether "id" is a key',
          'Whether "id" is a value',
          'Whether every key equals "id"',
          'Whether the dictionary is ordered',
        ],
        correctOptionIndex: 0,
        explanation: 'Dictionary membership tests keys unless a values or items view is requested explicitly.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'What ordering does iterating over a Python dictionary preserve?',
        options: [
          'Key insertion order',
          'Alphabetical key order',
          'Hash-value order',
          'Descending value order',
        ],
        correctOptionIndex: 0,
        explanation: 'Modern Python dictionaries preserve insertion order as part of the language specification.',
        difficulty: 'easy',
        platforms: allPlatforms,
      },
      {
        prompt: 'What is `{"a": 1, "b": 2} | {"b": 9, "c": 3}` in Python 3.9 or later?',
        options: [
          '`{"a": 1, "b": 9, "c": 3}`',
          '`{"a": 1, "b": 2, "c": 3}`',
          '`{"b": 9}`',
          'A duplicate-key error is raised',
        ],
        correctOptionIndex: 0,
        explanation: 'Dictionary union creates a new mapping and the right operand wins when a key appears in both.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Which expression maps each name in `names` to its character count?',
        options: [
          '`{name: len(name) for name in names}`',
          '`[name: len(name) for name in names]`',
          '`{len(name) for name in names}`',
          '`dict(name, len(name) for name in names)`',
        ],
        correctOptionIndex: 0,
        explanation: 'A dictionary comprehension places the key expression before the colon and the value expression after it.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'Why can adding a new key to a dictionary while iterating directly over it fail?',
        options: [
          'Changing its size during iteration can raise RuntimeError',
          'Dictionary keys become immutable during iteration',
          'New keys are always inserted twice',
          'Iteration converts the dictionary to a tuple',
        ],
        correctOptionIndex: 0,
        explanation: 'A dictionary iterator expects the mapping size to remain stable; iterate over a deliberate snapshot when resizing is required.',
        difficulty: 'medium',
        platforms: allPlatforms,
      },
      {
        prompt: 'What does `record.pop("status", "unknown")` return when status is absent?',
        options: ['"unknown"', 'None', '"status"', 'A KeyError is raised'],
        correctOptionIndex: 0,
        explanation: 'The supplied default is returned when the key is missing, avoiding KeyError.',
        difficulty: 'easy',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Which mapping is most direct for grouping many values under each key without manual initialization?',
        options: [
          '`collections.defaultdict(list)`',
          '`collections.Counter()`',
          '`types.MappingProxyType({})`',
          '`dict.fromkeys(keys, [])`',
        ],
        correctOptionIndex: 0,
        explanation: 'A defaultdict with list as its factory creates a separate empty list when each missing key is first accessed.',
        difficulty: 'medium',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'What does `groups.setdefault("new", []).append(7)` do when `"new"` is absent?',
        options: [
          'Stores a new list under "new" and appends 7 to it',
          'Raises KeyError before append runs',
          'Stores the integer 7 directly under "new"',
          'Appends "new" to every existing list',
        ],
        correctOptionIndex: 0,
        explanation: 'setdefault inserts and returns the default for a missing key, so append mutates that stored list.',
        difficulty: 'medium',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'How many entries remain after `mapping = {True: "yes"}; mapping[1] = "one"`?',
        options: ['1', '2', '0', 'A TypeError is raised'],
        correctOptionIndex: 0,
        explanation: 'True and 1 compare equal and have the same hash, so the second assignment updates the existing entry.',
        difficulty: 'hard',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'After `keys = record.keys()`, what happens if a new key is later added to record?',
        options: [
          'The new key appears in keys because it is a dynamic view',
          'keys remains a fixed list snapshot',
          'keys becomes None',
          'Adding the key raises because a view exists',
        ],
        correctOptionIndex: 0,
        explanation: 'Dictionary view objects reflect subsequent changes to their underlying mapping.',
        difficulty: 'medium',
        platforms: ['Andela', 'Toptal'],
      },
    ],
  },
  {
    id: 'conditions',
    title: 'Conditions',
    masteryLevel: 'L1',
    frequency: 'core',
    questionTarget: 15,
    questions: [
      {
        prompt: 'An inventory quantity may validly be zero. Which check detects only a missing value?',
        options: ['if not quantity:', 'if quantity is None:', 'if quantity == False:', 'if bool(quantity) is False:'],
        correctOptionIndex: 1,
        explanation: 'An identity check for None distinguishes absence from valid falsy values such as zero.',
        difficulty: 'easy',
        platforms: allPlatforms,
      },
      {
        prompt: 'What is the result of `1 < score <= 10` when score is 10?',
        options: ['True', 'False', '10', 'A syntax error'],
        correctOptionIndex: 0,
        explanation: 'Python supports chained comparisons; both `1 < 10` and `10 <= 10` are true.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'Why is `user is not None and user.is_admin` safe when user is None?',
        options: [
          'Python calls is_admin on None safely',
          'and short-circuits after the first false operand',
          'None always has an is_admin field',
          'The second operand runs in a background thread',
        ],
        correctOptionIndex: 1,
        explanation: 'Boolean `and` stops evaluation when the result is already known to be false.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Which structure makes invalid input easiest to see before the main operation?',
        options: [
          'Deeply nest the happy path inside several if blocks',
          'Use guard clauses that reject invalid states early',
          'Catch every exception after the operation',
          'Replace conditions with global flags',
        ],
        correctOptionIndex: 1,
        explanation: 'Guard clauses make preconditions explicit and keep the valid path at a shallow indentation level.',
        difficulty: 'medium',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'Which condition accurately allows checkout only for a nonempty cart with authorized payment?',
        options: [
          '`if cart or payment_authorized:`',
          '`if cart and payment_authorized:`',
          '`if not cart and payment_authorized:`',
          '`if cart is payment_authorized:`',
        ],
        correctOptionIndex: 1,
        explanation: 'Both business requirements must hold, so the condition uses logical conjunction.',
        difficulty: 'easy',
        platforms: allPlatforms,
      },
      {
        prompt: 'Given `left = [1]` and `right = [1]`, which statement is true?',
        options: [
          '`left == right` is True and `left is right` is False',
          '`left == right` is False and `left is right` is True',
          'Both comparisons are True',
          'Both comparisons are False',
        ],
        correctOptionIndex: 0,
        explanation: 'Equality compares list values, while is tests whether both names reference the same object.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Which condition correctly accepts a role equal to either `"admin"` or `"owner"`?',
        options: [
          '`role in {"admin", "owner"}`',
          '`role == "admin" or "owner"`',
          '`role is "admin" or "owner"`',
          '`role == ("admin" or "owner")`',
        ],
        correctOptionIndex: 0,
        explanation: 'Membership explicitly compares role with both allowed values; a bare nonempty string would be truthy on its own.',
        difficulty: 'easy',
        platforms: allPlatforms,
      },
      {
        prompt: 'Which conditional expression assigns `"ok"` when code is below 400 and `"error"` otherwise?',
        options: [
          '`status = "ok" if code < 400 else "error"`',
          '`status = if code < 400 then "ok" else "error"`',
          '`status = code < 400 ? "ok" : "error"`',
          '`status = "ok" when code < 400 otherwise "error"`',
        ],
        correctOptionIndex: 0,
        explanation: 'Python places the value for the true branch before if and the fallback after else.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'Why does checking `score >= 60` before `score >= 90` misclassify a score of 95 in an `if`/`elif` chain?',
        options: [
          'The broader first branch matches, so the more specific branch is never reached',
          'elif conditions run before the initial if',
          'Python compares numeric conditions alphabetically',
          'A score cannot be compared more than once',
        ],
        correctOptionIndex: 0,
        explanation: 'Only the first matching branch runs, so overlapping thresholds should normally be ordered from most specific to broadest.',
        difficulty: 'medium',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'Which condition is equivalent to `not (ready and paid)`?',
        options: [
          '`not ready or not paid`',
          '`not ready and not paid`',
          '`ready or paid`',
          '`ready and not paid`',
        ],
        correctOptionIndex: 0,
        explanation: 'De Morgan\'s law negates each operand and changes conjunction to disjunction.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'What are `all([])` and `any([])`?',
        options: [
          '`True` and `False`',
          '`False` and `True`',
          '`False` and `False`',
          'Both raise ValueError',
        ],
        correctOptionIndex: 0,
        explanation: 'all has a vacuously true empty result, while any finds no true element and returns false.',
        difficulty: 'hard',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Why can `result = cached_value or load_value()` be wrong when zero is a valid cached value?',
        options: [
          'Zero is falsy, so load_value runs even though the cache contains a valid result',
          'or always evaluates both operands',
          'Functions cannot return zero',
          'Zero is identical to None',
        ],
        correctOptionIndex: 0,
        explanation: 'Truthiness-based fallback conflates valid falsy data with absence; an explicit sentinel check preserves zero.',
        difficulty: 'medium',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'What value does `"ready" and 0` produce?',
        options: ['0', 'True', 'False', '"ready"'],
        correctOptionIndex: 0,
        explanation: 'Boolean operators return an operand; and returns the first falsy operand or the final operand.',
        difficulty: 'medium',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'Does `if -3:` enter its branch?',
        options: ['Yes, because every nonzero integer is truthy', 'No, because negative integers are falsy', 'No, because only 1 is truthy', 'It raises ValueError'],
        correctOptionIndex: 0,
        explanation: 'Numeric truth testing treats zero as false and every nonzero value, including negatives, as true.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'What is the result of `True or False and False`?',
        options: ['True', 'False', 'None', 'A syntax error'],
        correctOptionIndex: 0,
        explanation: 'and has higher precedence than or, so the expression is evaluated as `True or (False and False)`.',
        difficulty: 'medium',
        platforms: allPlatforms,
      },
    ],
  },
  {
    id: 'loops',
    title: 'Loops',
    masteryLevel: 'L1',
    frequency: 'core',
    questionTarget: 15,
    questions: [
      {
        prompt: 'Which values are produced by `range(1, 5)`?',
        options: ['1, 2, 3, 4', '1, 2, 3, 4, 5', '0, 1, 2, 3, 4', '2, 3, 4, 5'],
        correctOptionIndex: 0,
        explanation: '`range` includes its start and excludes its stop value.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'Which loop obtains each list item and its zero-based position without manual counter updates?',
        options: [
          '`for index, item in enumerate(items):`',
          '`for index in items.index():`',
          '`for item, index in items:`',
          '`while item in items:`',
        ],
        correctOptionIndex: 0,
        explanation: '`enumerate` yields index-item pairs and avoids separate mutable counter state.',
        difficulty: 'easy',
        platforms: allPlatforms,
      },
      {
        prompt: 'When does the `else` block on a Python `for` loop execute?',
        options: [
          'After every iteration',
          'When the loop finishes without a break',
          'Only when the iterable is a list',
          'Only when an exception occurs',
        ],
        correctOptionIndex: 1,
        explanation: 'Loop `else` represents normal completion; a `break` skips it.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'What is a loop invariant?',
        options: [
          'A value that must change on every iteration',
          'A statement that remains true before and after each iteration',
          'The final return value of the loop',
          'A rule that every loop must be infinite',
        ],
        correctOptionIndex: 1,
        explanation: 'An invariant supports correctness reasoning by describing valid partial progress throughout the loop.',
        difficulty: 'medium',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'Why is removing items from a list while iterating over that same list risky?',
        options: [
          'Lists become immutable during iteration',
          'Index shifts can cause elements to be skipped',
          'Every removal creates a syntax error',
          'Iteration automatically rolls back mutations',
        ],
        correctOptionIndex: 1,
        explanation: 'Changing list length shifts later indexes under the iterator. Build a filtered result or iterate over a deliberate copy instead.',
        difficulty: 'medium',
        platforms: allPlatforms,
      },
      {
        prompt: 'What does `continue` do inside a loop?',
        options: [
          'Skips the rest of the current iteration and starts the next one',
          'Terminates the loop immediately',
          'Restarts the entire function',
          'Pauses until another loop begins',
        ],
        correctOptionIndex: 0,
        explanation: 'continue advances control to the loop\'s next iteration without executing the remaining body for the current item.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'What does `break` affect when executed inside the inner of two nested loops?',
        options: [
          'Only the innermost loop containing it',
          'Every active loop in the function',
          'Only the outer loop',
          'The entire Python process',
        ],
        correctOptionIndex: 0,
        explanation: 'break exits its nearest enclosing loop; outer loops continue unless separate control flow stops them.',
        difficulty: 'easy',
        platforms: allPlatforms,
      },
      {
        prompt: 'How many pairs does `zip([1, 2, 3], ["a", "b"])` produce?',
        options: ['2', '3', '5', 'It raises ValueError'],
        correctOptionIndex: 0,
        explanation: 'By default, zip stops when its shortest input iterable is exhausted.',
        difficulty: 'easy',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Which values are produced by `range(5, 0, -2)`?',
        options: ['5, 3, 1', '5, 3, 1, -1', '0, 2, 4', '5, 4, 3, 2, 1'],
        correctOptionIndex: 0,
        explanation: 'A negative step moves downward, and the stop value zero remains exclusive.',
        difficulty: 'medium',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'How many times does `while remaining > 0:` run when remaining starts at zero?',
        options: ['0', '1', 'It runs forever', 'It raises NameError'],
        correctOptionIndex: 0,
        explanation: 'A while loop tests its condition before entering the body, so an initially false condition executes zero iterations.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'What is the time complexity of two nested loops that each visit all `n` items?',
        options: ['O(1)', 'O(n)', 'O(n log n)', 'O(n^2)'],
        correctOptionIndex: 3,
        explanation: 'The inner loop performs n iterations for each of n outer iterations, producing n squared work.',
        difficulty: 'medium',
        platforms: allPlatforms,
      },
      {
        prompt: 'A loop should sum all prices, but `total = 0` is inside the loop body before `total += price`. What is the defect?',
        options: [
          'The accumulator is reset on every iteration, so only the final price remains',
          'The loop adds every price twice',
          'The list is sorted before summing',
          'The accumulator becomes a tuple',
        ],
        correctOptionIndex: 0,
        explanation: 'Accumulator initialization belongs before the loop so each iteration can build on prior progress.',
        difficulty: 'easy',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'After `for item in [4, 5]: pass`, what value does item have?',
        options: ['5', '4', 'None', 'The name is unavailable outside the loop'],
        correctOptionIndex: 0,
        explanation: 'A Python for-loop does not create a separate block scope, so its target remains bound to the last item.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Why can `sum(transform(item) for item in records)` use less peak memory than summing a list comprehension?',
        options: [
          'The generator yields transformed values incrementally instead of building the full list',
          'Generators store every result twice',
          'sum ignores generator values after the first',
          'List comprehensions always write results to disk',
        ],
        correctOptionIndex: 0,
        explanation: 'A generator expression feeds one value at a time to sum, avoiding a separate list of all transformed values.',
        difficulty: 'medium',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'Which loop header processes `items` in slices of `batch_size`?',
        options: [
          '`for start in range(0, len(items), batch_size):`',
          '`for start in range(batch_size, items):`',
          '`for start in items[batch_size]:`',
          '`while start in len(items, batch_size):`',
        ],
        correctOptionIndex: 0,
        explanation: 'Stepping start by the batch size supports slices such as `items[start:start + batch_size]`.',
        difficulty: 'medium',
        platforms: ['Andela', 'Toptal'],
      },
    ],
  },
  {
    id: 'functions',
    title: 'Functions',
    masteryLevel: 'L2',
    frequency: 'core',
    questionTarget: 20,
    questions: [
      {
        prompt: 'What is the difference between `return value` and `print(value)` inside a function?',
        options: [
          'They are interchangeable',
          'return gives a value to the caller; print writes a representation to output',
          'print gives a value to the caller; return only logs it',
          'return can be used only with strings',
        ],
        correctOptionIndex: 1,
        explanation: 'Returning participates in the function contract, while printing is an output side effect and normally returns None.',
        difficulty: 'easy',
        platforms: allPlatforms,
      },
      {
        prompt: 'Why is `def add_item(item, items=[]):` usually a defect?',
        options: [
          'Lists cannot be parameters',
          'The same default list is reused across calls',
          'Default arguments are evaluated after every return',
          'Python requires tuple defaults',
        ],
        correctOptionIndex: 1,
        explanation: 'Default argument expressions run once at function definition, so mutations persist into later calls. Use None and create a list per call.',
        difficulty: 'medium',
        platforms: allPlatforms,
      },
      {
        prompt: 'What do `*args` and `**kwargs` collect?',
        options: [
          'Required and optional types',
          'Additional positional arguments and additional keyword arguments',
          'Only integer and string arguments',
          'Return values and raised exceptions',
        ],
        correctOptionIndex: 1,
        explanation: '`*args` is a tuple of extra positional arguments and `**kwargs` is a dictionary of extra keyword arguments.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Which contract is most complete for a function that charges a payment?',
        options: [
          'It accepts two values',
          'It accepts validated cents and an idempotency key, returns a receipt, and documents domain and availability failures',
          'It usually works and prints errors',
          'It calls the provider SDK internally',
        ],
        correctOptionIndex: 1,
        explanation: 'A useful contract covers semantic input rules, output, side effects, repeat behavior, and failure modes, not only parameter types.',
        difficulty: 'hard',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'Why separate a pure subtotal calculation from database and payment calls?',
        options: [
          'Pure functions always run asynchronously',
          'The calculation becomes deterministic, easier to test, and reusable across effectful workflows',
          'Database calls cannot occur in Python functions',
          'It guarantees the payment provider never fails',
        ],
        correctOptionIndex: 1,
        explanation: 'Separating deterministic policy from effects narrows tests and makes integration failures easier to isolate.',
        difficulty: 'hard',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'Given `def connect(host, *, timeout=5): ...`, which call is valid?',
        options: [
          '`connect("api.example", timeout=10)`',
          '`connect("api.example", 10)`',
          '`connect(host="api.example", 10)`',
          '`connect(timeout=10, "api.example")`',
        ],
        correctOptionIndex: 0,
        explanation: 'Parameters after a bare asterisk are keyword-only, making the timeout argument explicit at the call site.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'What does the slash mean in `def parse(text, /): ...`?',
        options: [
          'text must be supplied positionally',
          'text must be supplied by keyword',
          'text is optional',
          'text accepts only strings',
        ],
        correctOptionIndex: 0,
        explanation: 'Parameters before `/` are positional-only and cannot be named by callers.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Why does `sorted(words, key=len)` use `len` rather than `len()`?',
        options: [
          'The key parameter needs the function object to call for each word',
          'len() returns a faster version of len',
          'Parentheses would convert words to a tuple',
          'sorted accepts only built-in function names',
        ],
        correctOptionIndex: 0,
        explanation: 'A callback is passed as a callable object; invoking len immediately would require an argument and pass its result instead.',
        difficulty: 'medium',
        platforms: allPlatforms,
      },
      {
        prompt: 'If `area(width, height)` accepts two positional arguments, what does `area(*[3, 4])` do?',
        options: [
          'Calls area with width 3 and height 4',
          'Passes one list argument',
          'Multiplies the list by area',
          'Raises because lists cannot be unpacked',
        ],
        correctOptionIndex: 0,
        explanation: 'A starred iterable in a call expands its elements into positional arguments.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'Which task can a Python lambda express directly?',
        options: [
          'Return one expression such as `lambda value: value * 2`',
          'Run a sequence of assignment statements',
          'Contain a try/except statement block',
          'Declare multiple def statements in its body',
        ],
        correctOptionIndex: 0,
        explanation: 'A lambda creates a small anonymous function whose body is exactly one expression.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'What prevents a recursive function from calling itself indefinitely on valid input?',
        options: [
          'A reachable base case that stops recursion',
          'A module-level global variable in every case',
          'The print function',
          'Automatic conversion to a loop',
        ],
        correctOptionIndex: 0,
        explanation: 'Each recursive step must progress toward a base case that returns without another recursive call.',
        difficulty: 'easy',
        platforms: allPlatforms,
      },
      {
        prompt: 'What does calling a function containing `yield` return?',
        options: ['A generator object', 'A fully populated list', 'The first yielded value immediately', 'Always None'],
        correctOptionIndex: 0,
        explanation: 'Calling a generator function creates a generator; its body advances as values are requested.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'A function executes `items.append(3)` on a list supplied by its caller. What can the caller observe?',
        options: [
          'The original list now includes 3',
          'No change because parameters are deep-copied',
          'The caller variable becomes None',
          'A list cannot cross a function boundary',
        ],
        correctOptionIndex: 0,
        explanation: 'The parameter and caller can reference the same mutable list, so in-place mutation is externally visible.',
        difficulty: 'medium',
        platforms: allPlatforms,
      },
      {
        prompt: 'A function executes `items = [3]` where items is a parameter. What happens to the caller\'s variable?',
        options: [
          'It remains bound to its original object',
          'It is rebound to [3]',
          'It is deleted',
          'It becomes a tuple containing 3',
        ],
        correctOptionIndex: 0,
        explanation: 'Reassigning a local parameter changes only that local binding; it does not rebind the caller\'s name.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'What is the benefit of calling `format_name(last="Lovelace", first="Ada")` with keyword arguments?',
        options: [
          'Arguments bind by parameter name, so their written order need not match the signature',
          'The function receives the names in a set',
          'Keyword arguments bypass parameter validation',
          'The call becomes asynchronous',
        ],
        correctOptionIndex: 0,
        explanation: 'Keyword arguments make binding explicit and can improve readability when parameter names carry meaning.',
        difficulty: 'easy',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'Where must a function docstring appear for tools to recognize it as `function.__doc__`?',
        options: [
          'As the first statement in the function body',
          'After the final return statement',
          'Before the def line as a comment',
          'Inside every except block',
        ],
        correctOptionIndex: 0,
        explanation: 'A leading string literal in the body becomes the function docstring and is exposed through __doc__.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'What makes a function higher-order?',
        options: [
          'It accepts a function or returns one',
          'It has more than ten parameters',
          'It is defined at module scope',
          'It raises only custom exceptions',
        ],
        correctOptionIndex: 0,
        explanation: 'Higher-order functions treat functions as values by receiving or producing callables.',
        difficulty: 'medium',
        platforms: allPlatforms,
      },
      {
        prompt: 'Why pass a clock function into code that checks expiration times?',
        options: [
          'Tests can supply deterministic times without changing production logic',
          'It makes wall-clock time stop globally',
          'It guarantees the system clock is always correct',
          'Python functions cannot otherwise read time',
        ],
        correctOptionIndex: 0,
        explanation: 'Dependency injection separates time retrieval from policy and lets tests control that external input.',
        difficulty: 'hard',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'When is memoizing a function result safest?',
        options: [
          'When outputs depend only on hashable inputs and the function has no relevant side effects',
          'When every call must write a new database row',
          'When results depend on untracked global state',
          'When arguments are mutated during the call',
        ],
        correctOptionIndex: 0,
        explanation: 'Stable input-to-output behavior makes cached results reusable without skipping required effects or observing stale hidden state.',
        difficulty: 'hard',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Why should a decorator usually apply `functools.wraps` to its wrapper function?',
        options: [
          'It preserves metadata such as the wrapped function\'s name and docstring',
          'It makes every decorated call run in parallel',
          'It converts positional arguments to strings',
          'It prevents the wrapped function from returning',
        ],
        correctOptionIndex: 0,
        explanation: 'wraps copies identifying metadata and exposes the wrapped function for introspection and tooling.',
        difficulty: 'hard',
        platforms: ['Turing', 'Toptal'],
      },
    ],
  },
  {
    id: 'scope',
    title: 'Scope',
    masteryLevel: 'L2',
    frequency: 'frequent',
    questionTarget: 10,
    questions: [
      {
        prompt: 'In which order does Python normally resolve an unqualified name?',
        options: [
          'Global, local, built-in, enclosing',
          'Local, enclosing, global, built-in',
          'Built-in, global, enclosing, local',
          'Enclosing, built-in, local, global',
        ],
        correctOptionIndex: 1,
        explanation: 'Python follows LEGB: local, enclosing, global, then built-in scope.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Why can reading `count` before `count += 1` inside a function raise UnboundLocalError when a global count exists?',
        options: [
          'Integers cannot be incremented',
          'Assignment makes count local to that function unless declared otherwise',
          'Global names are deleted on function entry',
          'The += operator works only in loops',
        ],
        correctOptionIndex: 1,
        explanation: 'Because the function assigns to count, Python treats it as local throughout that function; the read occurs before the local binding.',
        difficulty: 'hard',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'What does `nonlocal` allow an inner function to do?',
        options: [
          'Import a module-level name',
          'Rebind a name in the nearest enclosing function scope',
          'Create a process-wide global',
          'Bypass all access controls',
        ],
        correctOptionIndex: 1,
        explanation: '`nonlocal` targets an existing binding in an enclosing function scope rather than creating a new local binding.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Why should mutable request state not be kept in a module global?',
        options: [
          'Module globals are always immutable',
          'Requests in the same process can observe or overwrite shared state',
          'Python reloads every module for every function call',
          'Global values cannot be logged',
        ],
        correctOptionIndex: 1,
        explanation: 'Module state is shared within the process and can outlive a request, creating contamination and concurrency defects.',
        difficulty: 'medium',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'A closure created in a loop uses the loop variable later. How can each closure retain its current value?',
        options: [
          'Use the loop variable as a default argument when defining the closure',
          'Declare the loop variable global',
          'Delete the variable after each iteration',
          'Convert the closure into a set',
        ],
        correctOptionIndex: 0,
        explanation: 'Binding the current value as a default argument avoids late lookup of the final loop-variable value.',
        difficulty: 'hard',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'What does `global retries` allow a function to do?',
        options: [
          'Rebind the retries name in module scope',
          'Create a variable shared across every Python process',
          'Import retries from any installed package',
          'Make retries immutable',
        ],
        correctOptionIndex: 0,
        explanation: 'A global declaration directs assignments to the module-level binding instead of creating a local name.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'In Python 3, what happens to the name `item` after `[item * 2 for item in values]`?',
        options: [
          'The comprehension variable does not leak into the surrounding scope',
          'item remains bound to the final value',
          'item becomes the resulting list',
          'The surrounding scope is deleted',
        ],
        correctOptionIndex: 0,
        explanation: 'Comprehensions execute with their own implicit scope, keeping the iteration variable local to the comprehension.',
        difficulty: 'medium',
        platforms: allPlatforms,
      },
      {
        prompt: 'Given module `label = "module"` and a class with `label = "class"`, what does an unqualified `return label` inside an ordinary method resolve to?',
        options: [
          'The module-level label',
          'The class attribute automatically',
          'The instance attribute automatically',
          'A syntax error',
        ],
        correctOptionIndex: 0,
        explanation: 'A class namespace is not an enclosing lexical scope for method bodies; class data requires access such as self.label or type(self).label.',
        difficulty: 'hard',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Why is assigning `list = []` in a scope usually a poor choice?',
        options: [
          'It shadows the built-in list constructor in that scope',
          'Python forbids names that match built-ins',
          'It makes the new list immutable',
          'It changes the list built-in in every process',
        ],
        correctOptionIndex: 0,
        explanation: 'The local binding hides the built-in name, so later code such as `list(values)` can fail or become confusing.',
        difficulty: 'easy',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'Why is an exception name from `except ValueError as error:` unavailable after the handler finishes?',
        options: [
          'Python clears the handler target to help break exception traceback reference cycles',
          'ValueError names are always global',
          'The handler executes in a new process',
          'Exception objects cannot be assigned to names',
        ],
        correctOptionIndex: 0,
        explanation: 'Python deletes the exception target at the end of the except suite rather than retaining it in the surrounding local scope.',
        difficulty: 'hard',
        platforms: ['Turing', 'Toptal'],
      },
    ],
  },
  {
    id: 'exceptions',
    title: 'Exceptions',
    masteryLevel: 'L2',
    frequency: 'core',
    questionTarget: 15,
    questions: [
      {
        prompt: 'Why should code catch the narrowest exception it can handle meaningfully?',
        options: [
          'Specific exceptions execute faster in every case',
          'It avoids hiding unrelated defects and documents the expected failure',
          'Broad exceptions cannot be logged',
          'Python forbids catching Exception',
        ],
        correctOptionIndex: 1,
        explanation: 'A narrow handler responds only to understood failure modes while unexpected defects remain visible.',
        difficulty: 'medium',
        platforms: allPlatforms,
      },
      {
        prompt: 'Which block runs whether the protected operation succeeds or raises?',
        options: ['except', 'else', 'finally', 'raise'],
        correctOptionIndex: 2,
        explanation: '`finally` is designed for cleanup that must occur across normal and exceptional exits.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'What does `raise PaymentUnavailable() from error` preserve?',
        options: [
          'Only the new exception message',
          'The causal relationship to the original exception',
          'A successful return value',
          'The original exception while suppressing the new one',
        ],
        correctOptionIndex: 1,
        explanation: 'Explicit exception chaining translates an error at a boundary while retaining diagnostic context about its cause.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Which failure is a reasonable candidate for bounded retry?',
        options: [
          'A malformed email address',
          'A transient provider timeout on an idempotent request',
          'A missing required field',
          'A deterministic division by zero defect',
        ],
        correctOptionIndex: 1,
        explanation: 'Retries fit transient failures only when repeating the operation is safe and attempts are limited with backoff.',
        difficulty: 'medium',
        platforms: allPlatforms,
      },
      {
        prompt: 'What is the risk of `except Exception: pass` around business logic?',
        options: [
          'It converts every exception into a warning automatically',
          'It can hide failed work and let the system report false success',
          'It retries the operation forever',
          'It forces the process to exit',
        ],
        correctOptionIndex: 1,
        explanation: 'Swallowing unknown failures removes the error signal and may leave callers and operators believing incomplete work succeeded.',
        difficulty: 'hard',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'When does the `else` suite of a `try` statement run?',
        options: [
          'When the try suite completes without raising an exception',
          'Only after an exception is caught',
          'Whether or not an exception occurs',
          'Only when finally is absent',
        ],
        correctOptionIndex: 0,
        explanation: 'try/else keeps success-only work separate from the statements whose expected failures are being handled.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'What does a bare `raise` do inside an active exception handler?',
        options: [
          'Reraises the exception currently being handled',
          'Raises a new generic Exception with no context',
          'Returns the exception to the caller as a value',
          'Silently clears the exception',
        ],
        correctOptionIndex: 0,
        explanation: 'A bare raise propagates the active exception while preserving its traceback.',
        difficulty: 'medium',
        platforms: allPlatforms,
      },
      {
        prompt: 'Which declaration creates a conventional application exception?',
        options: [
          '`class InvalidOrderError(Exception): pass`',
          '`def InvalidOrderError(exception): pass`',
          '`class InvalidOrderError(list): pass`',
          '`InvalidOrderError = except Exception`',
        ],
        correctOptionIndex: 0,
        explanation: 'Application exceptions normally subclass Exception directly or through a domain-specific exception hierarchy.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'Which handler catches either `ValueError` or `TypeError`?',
        options: [
          '`except (ValueError, TypeError):`',
          '`except ValueError or TypeError:`',
          '`except [ValueError, TypeError]:`',
          '`except ValueError and TypeError:`',
        ],
        correctOptionIndex: 0,
        explanation: 'An exception tuple lets one handler cover any of the listed exception classes.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'Why must `except FileNotFoundError:` appear before `except OSError:` when they need different handling?',
        options: [
          'FileNotFoundError is an OSError subclass, so the broader handler would otherwise catch it first',
          'Python sorts handlers alphabetically',
          'OSError can be caught only after finally',
          'FileNotFoundError is not an exception',
        ],
        correctOptionIndex: 0,
        explanation: 'Handlers are tested in source order, so a superclass handler placed first makes a later subclass handler unreachable.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Why is `with open(path) as file:` preferable to manually closing the file only after successful work?',
        options: [
          'The context manager closes the file during both normal and exceptional exits',
          'It keeps every file open for reuse',
          'It suppresses every exception from the body',
          'It loads the file entirely into memory',
        ],
        correctOptionIndex: 0,
        explanation: 'The context manager guarantees its exit protocol runs, centralizing resource cleanup across all exits.',
        difficulty: 'medium',
        platforms: allPlatforms,
      },
      {
        prompt: 'What happens when a function raises an exception and has no matching handler?',
        options: [
          'The exception propagates up the call stack until handled or the program terminates',
          'The function automatically returns None',
          'Python retries the function once',
          'The exception becomes a warning',
        ],
        correctOptionIndex: 0,
        explanation: 'Unhandled exceptions unwind callers, running applicable cleanup, until a matching handler is found.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'Why should `assert user_is_authorized` not enforce an API authorization boundary?',
        options: [
          'Assertions can be disabled and are intended for internal invariants, not required validation',
          'Assertions cannot inspect booleans',
          'Assertions always expose a password',
          'Python permits assertions only in tests',
        ],
        correctOptionIndex: 0,
        explanation: 'Optimization can remove assert statements, so security and input checks require explicit control flow and exceptions.',
        difficulty: 'hard',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'Which logging call inside an exception handler records the current traceback by default?',
        options: ['`logger.exception("request failed")`', '`logger.info("request failed")`', '`print("request failed")`', '`logger.debug(None)`'],
        correctOptionIndex: 0,
        explanation: 'logger.exception emits an error-level message with information for the exception currently being handled.',
        difficulty: 'medium',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'A database transaction fails after one write. What should the exception path normally do before propagating the failure?',
        options: [
          'Roll back the transaction and preserve the error signal',
          'Commit the partial write and return success',
          'Catch every exception and continue silently',
          'Retry forever without checking idempotency',
        ],
        correctOptionIndex: 0,
        explanation: 'Rollback restores transactional consistency, while propagation lets the caller and operators observe the failed operation.',
        difficulty: 'hard',
        platforms: ['Andela', 'Toptal'],
      },
    ],
  },
  {
    id: 'modules',
    title: 'Modules',
    masteryLevel: 'L2',
    frequency: 'targeted',
    questionTarget: 5,
    questions: [
      {
        prompt: 'What is the purpose of `if __name__ == "__main__":`?',
        options: [
          'Run selected code only when the file is executed as the main program',
          'Prevent all imports from the file',
          'Declare the module public',
          'Install the module dependencies',
        ],
        correctOptionIndex: 0,
        explanation: 'Imported modules receive their module name, while the directly executed module receives `__main__`.',
        difficulty: 'easy',
        platforms: allPlatforms,
      },
      {
        prompt: 'Why are network calls at module import time risky?',
        options: [
          'Imports can never execute statements',
          'They make importing slow, failure-prone, and difficult to test or configure',
          'Network calls are automatically cached forever',
          'They force every imported function to be async',
        ],
        correctOptionIndex: 1,
        explanation: 'Import should establish definitions predictably. External effects during import couple startup to environment and dependency availability.',
        difficulty: 'medium',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'What is a common root cause of a circular import?',
        options: [
          'Two modules depend directly or indirectly on each other during initialization',
          'A module contains more than one function',
          'An import uses an alias',
          'A package includes an `__init__.py` file',
        ],
        correctOptionIndex: 0,
        explanation: 'Mutual initialization dependencies can encounter partially initialized modules and often reveal misplaced shared responsibilities.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Which module design gives callers the clearest stable contract?',
        options: [
          'Expose every internal helper',
          'Keep a small documented public surface and hide replaceable details',
          'Require callers to mutate module globals',
          'Execute the CLI whenever imported',
        ],
        correctOptionIndex: 1,
        explanation: 'A small public surface reduces coupling and lets internal structure evolve without breaking callers.',
        difficulty: 'medium',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'Where should reusable email-delivery behavior live?',
        options: [
          'Behind an explicit function or class called by application code',
          'As an automatic side effect of importing the module',
          'Inside a module-level infinite loop',
          'In every caller as copied code',
        ],
        correctOptionIndex: 0,
        explanation: 'An explicit callable makes invocation, inputs, failures, and testing controllable while avoiding import-time effects.',
        difficulty: 'easy',
        platforms: ['Andela', 'Toptal'],
      },
    ],
  },
  {
    id: 'json',
    title: 'JSON',
    masteryLevel: 'L2',
    frequency: 'frequent',
    questionTarget: 10,
    questions: [
      {
        prompt: 'Which Python function parses a JSON string into Python values?',
        options: ['json.dumps', 'json.loads', 'json.dump', 'json.read'],
        correctOptionIndex: 1,
        explanation: '`json.loads` deserializes a string, while `json.dumps` serializes Python values to a string.',
        difficulty: 'easy',
        platforms: allPlatforms,
      },
      {
        prompt: 'Which value has no native JSON representation?',
        options: ['A string', 'A number', 'A boolean', 'A datetime object'],
        correctOptionIndex: 3,
        explanation: 'JSON supports strings, numbers, booleans, null, arrays, and objects. Datetimes need an agreed string or numeric representation.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'What restriction applies to keys in a JSON object?',
        options: [
          'They must be strings',
          'They must be integers',
          'They can be lists',
          'They must be globally unique across the document',
        ],
        correctOptionIndex: 0,
        explanation: 'JSON object member names are strings, even if a source-language mapping permits other key types.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'Why is successful JSON parsing insufficient validation for an API request?',
        options: [
          'Parsing validates all business rules automatically',
          'Syntactically valid JSON can still have missing fields, wrong shapes, or invalid domain values',
          'JSON parsing accepts only trusted traffic',
          'Parsed values are always immutable',
        ],
        correctOptionIndex: 1,
        explanation: 'Parsing establishes syntax, not the application contract. Shape, types, ranges, and relationships still require validation.',
        difficulty: 'medium',
        platforms: allPlatforms,
      },
      {
        prompt: 'How should a service normally serialize a timezone-aware timestamp in a JSON API?',
        options: [
          'As the language-specific datetime object',
          'As an explicitly documented UTC ISO 8601 string',
          'Using the server local timezone without an offset',
          'By omitting the timestamp type from the contract',
        ],
        correctOptionIndex: 1,
        explanation: 'A documented UTC ISO 8601 representation is portable and avoids ambiguous server-local time interpretation.',
        difficulty: 'medium',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'Which Python function serializes a dictionary to a JSON string?',
        options: ['json.dumps', 'json.loads', 'json.load', 'json.parse'],
        correctOptionIndex: 0,
        explanation: '`json.dumps` serializes supported Python values and returns the resulting JSON text.',
        difficulty: 'easy',
        platforms: ['Turing', 'Andela'],
      },
      {
        prompt: 'What Python value does `json.loads("null")` return?',
        options: ['None', '"null"', '0', 'False'],
        correctOptionIndex: 0,
        explanation: 'The JSON null literal maps to Python None during deserialization.',
        difficulty: 'easy',
        platforms: allPlatforms,
      },
      {
        prompt: 'What happens when a standards-compliant JSON parser reads `{"id": 7,}`?',
        options: [
          'It rejects the trailing comma as invalid JSON syntax',
          'It silently removes the comma in every implementation',
          'It adds a null field',
          'It converts the object to an array',
        ],
        correctOptionIndex: 0,
        explanation: 'Unlike some programming-language literals, standard JSON does not permit trailing commas.',
        difficulty: 'medium',
        platforms: ['Turing', 'Toptal'],
      },
      {
        prompt: 'Why use `json.dumps(value, allow_nan=False)` when producing interoperable JSON?',
        options: [
          'It rejects NaN and infinity values that are outside the JSON number grammar',
          'It converts every number to null',
          'It permits comments in the output',
          'It sorts arrays numerically',
        ],
        correctOptionIndex: 0,
        explanation: 'Disabling nonstandard floating-point tokens makes serialization fail instead of emitting values strict JSON consumers may reject.',
        difficulty: 'hard',
        platforms: ['Andela', 'Toptal'],
      },
      {
        prompt: 'How should an integer identifier larger than some consumers can represent exactly be transported in a cross-runtime JSON API?',
        options: [
          'As a documented decimal string',
          'As a rounded floating-point number',
          'As an unquoted hexadecimal comment',
          'As JSON NaN',
        ],
        correctOptionIndex: 0,
        explanation: 'A decimal string preserves every identifier digit when a consumer\'s numeric type has a smaller exact integer range.',
        difficulty: 'hard',
        platforms: ['Andela', 'Toptal'],
      },
    ],
  },
] satisfies readonly LearningMasteryTopicSeed[]

export const programmingFundamentalsMasteryTopics = defineLearningMasteryTopics(
  'software-engineering-core',
  'programming-fundamentals',
  programmingFundamentalsTopics,
)