import {
  defineSoftwareMasteryTopics,
  type SoftwareMasteryTopicBlueprint,
} from './software-core-mastery-builder'

const sqlDatabaseBlueprints = [
  {
    id: 'relational-modeling',
    title: 'Relational Modeling & Normalization',
    questionTarget: 20,
    principle: 'A relational model should store each fact at a clear grain and separate facts that change independently',
    scenario: 'Every order row repeats the current customer address, causing old orders to change meaning when the customer moves.',
    action: 'Separate customer data from order snapshots and define which address facts belong to each lifecycle',
    failure: 'One update requires changing many rows or the same real-world fact has conflicting stored values',
    evidence: 'List each table grain, functional dependency, update path, and invariant the schema is expected to preserve',
    boundary: 'historical snapshots intentionally preserve a value that differs from the current referenced entity',
    tradeoff: 'Normalization reduces anomalies while selective denormalization can improve read paths at the cost of synchronization',
    verification: 'Exercise create, update, delete, and historical queries and confirm that each fact has one intended owner',
    outcome: 'Independent facts can change without duplication anomalies or accidental loss of historical meaning',
    misconception: 'A normalized schema must split every attribute into a separate table',
    operation: 'Monitor data-quality violations and reconciliation differences in intentionally duplicated projections',
    review: 'What is the grain of each row, and which real-world fact does every column depend on?',
  },
  {
    id: 'keys-constraints',
    title: 'Keys, Constraints & Referential Integrity',
    questionTarget: 20,
    principle: 'Database keys and constraints make identity and invariants durable across every writer',
    scenario: 'Two concurrent registrations both pass an application email check and insert the same normalized address.',
    action: 'Enforce normalized email uniqueness in the database and handle the resulting constraint conflict',
    failure: 'Duplicate identities, orphaned references, invalid states, or impossible values appear despite application validation',
    evidence: 'Inspect DDL constraints, failing rows, write concurrency, and the exact keys used by relationships',
    boundary: 'nullable references, soft deletion, composite identity, and cascading actions change the intended invariant',
    tradeoff: 'Strong constraints reject bad writes consistently but require deliberate migration and error-handling paths',
    verification: 'Attempt valid and invalid inserts and updates concurrently through more than one application path',
    outcome: 'Critical data rules remain true even when callers race, fail, or bypass one application layer',
    misconception: 'Application validation makes database constraints redundant',
    operation: 'Track constraint violations by rule and investigate repeated conflicts rather than suppressing them',
    review: 'Which invariant must survive every writer, and is it encoded by the strongest appropriate constraint?',
  },
  {
    id: 'select-filter-order',
    title: 'SELECT, Predicates, Ordering & Limits',
    questionTarget: 20,
    principle: 'A query must define the rows, columns, and deterministic order required by the result contract',
    scenario: 'A query uses LIMIT 10 without ORDER BY and tests intermittently receive a different first page.',
    action: 'Add an ordering that fully resolves ties and select only the columns required by the consumer',
    failure: 'A query returns the wrong population, nondeterministic rows, or excessive data because its predicate or ordering is incomplete',
    evidence: 'Compare the intended result set with predicate truth, sort keys, ties, limit placement, and actual rows',
    boundary: 'NULL values, inclusive ranges, collation, equal sort keys, and an empty result change intuitive comparisons',
    tradeoff: 'Broader projections and flexible predicates can simplify callers while increasing transfer and reducing index efficiency',
    verification: 'Use fixtures around every predicate boundary and tied ordering value, then assert the exact ordered rows',
    outcome: 'The query returns a stable minimal result that matches the stated selection contract',
    misconception: 'Rows have a reliable natural order when ORDER BY is omitted',
    operation: 'Measure result size, scanned rows, latency, and rejected or slow filter combinations',
    review: 'Does each predicate express the intended boundary, and does the ordering uniquely determine limited results?',
  },
  {
    id: 'joins-cardinality',
    title: 'Joins & Cardinality',
    questionTarget: 20,
    principle: 'Join choice and join keys must match relationship cardinality and whether unmatched rows belong in the result',
    scenario: 'Joining orders to order items makes customer revenue double because another one-to-many table is joined before aggregation.',
    action: 'Define the desired grain, aggregate each many-side appropriately, and join on the complete relationship key',
    failure: 'Rows disappear, multiply, or match the wrong entity after a join',
    evidence: 'Count rows and distinct keys before and after each join and inspect unmatched records from both sides',
    boundary: 'duplicate keys, NULL join values, missing relationships, and multiple one-to-many joins interact',
    tradeoff: 'Joining rich detail in one query can reduce round trips but may multiply data and complicate the result grain',
    verification: 'Test zero, one, and many matches on both sides and assert row counts plus aggregate totals',
    outcome: 'Every result row represents the intended entity without silent loss or multiplication',
    misconception: 'An INNER JOIN and LEFT JOIN are interchangeable when the selected columns look the same',
    operation: 'Watch join cardinality estimates, actual row counts, and data-quality exceptions on relationship keys',
    review: 'What is the row grain before and after this join, and can either side match more than once?',
  },
  {
    id: 'grouping-aggregation',
    title: 'Grouping, Aggregation & HAVING',
    questionTarget: 20,
    principle: 'Aggregation is correct only after the grouping grain and input row population are explicit',
    scenario: 'A report filters aggregate totals in WHERE and also counts duplicated rows introduced by a detail join.',
    action: 'Fix the pre-aggregation grain, use WHERE for input rows, and use HAVING for aggregate groups',
    failure: 'Totals are inflated, groups are split unexpectedly, or a filter runs at the wrong stage',
    evidence: 'Inspect source rows, group keys, aggregate inputs, NULL handling, and results before HAVING',
    boundary: 'empty groups, NULL values, duplicate joined rows, and conditional aggregates affect the total',
    tradeoff: 'Pre-aggregation can simplify cardinality and improve speed but may remove detail needed by later calculations',
    verification: 'Construct groups with zero, one, duplicate, NULL, included, and excluded rows and calculate expected totals by hand',
    outcome: 'Each aggregate reports the intended measure once at the intended business grain',
    misconception: 'COUNT(column) and COUNT(*) include exactly the same rows in every query',
    operation: 'Reconcile aggregate reports against source totals and monitor unexplained grain changes',
    review: 'What rows enter each aggregate, what defines one group, and where should each filter execute?',
  },
  {
    id: 'subqueries-ctes-sets',
    title: 'Subqueries, CTEs & Set Operations',
    questionTarget: 16,
    principle: 'Query composition should make intermediate sets and duplicate semantics explicit without changing the intended result',
    scenario: 'A NOT IN subquery containing one NULL causes a query to return no rows unexpectedly.',
    action: 'Use a NULL-safe anti-join such as NOT EXISTS with a correlated equality predicate',
    failure: 'A rewrite changes duplicate handling, NULL behavior, correlation, or materialization cost',
    evidence: 'Compare intermediate row sets, NULLs, duplicate counts, correlation keys, and the execution plan',
    boundary: 'UNION removes duplicates, UNION ALL preserves them, and recursive CTEs can revisit cycles',
    tradeoff: 'CTEs can improve reasoning and reuse, but optimization and materialization behavior depend on the database',
    verification: 'Test empty, duplicate, NULL-containing, correlated, and overlapping input sets',
    outcome: 'Complex logic remains decomposable while preserving precise set and bag semantics',
    misconception: 'A CTE always stores its result once and is therefore faster than a subquery',
    operation: 'Monitor plans and row estimates after database upgrades or large changes in intermediate set size',
    review: 'Does this construct preserve duplicates, NULL semantics, and correlation exactly as the contract requires?',
  },
  {
    id: 'window-functions',
    title: 'Window Functions',
    questionTarget: 16,
    principle: 'A window function computes across a defined partition and order while retaining individual result rows',
    scenario: 'A latest-order query uses ROW_NUMBER without a tie-breaking column and chooses different rows across runs.',
    action: 'Partition by customer and order by timestamp plus a unique stable key before filtering rank one',
    failure: 'Ranks, running totals, or prior-row comparisons cross groups or vary because partition and order clauses are incomplete',
    evidence: 'Inspect partition keys, ordering ties, frame boundaries, and computed values on a small ordered fixture',
    boundary: 'equal order values and the difference between ROWS and RANGE frames alter which rows participate',
    tradeoff: 'Windows avoid self-joins and preserve detail, but sorting large partitions can consume substantial memory',
    verification: 'Trace a fixture with several partitions, tied values, gaps, and explicit frame endpoints',
    outcome: 'Analytical values are calculated at the correct relationship to neighboring rows without collapsing detail',
    misconception: 'PARTITION BY has the same effect as GROUP BY and removes detail rows',
    operation: 'Observe sort spills, partition sizes, memory grants, and latency for large windows',
    review: 'Are partition, order, tie-breaking, and frame semantics all explicit for this calculation?',
  },
  {
    id: 'indexes',
    title: 'Indexes & Access Paths',
    questionTarget: 20,
    principle: 'An index should support a measured access path with column order and coverage matched to real predicates and ordering',
    scenario: 'A composite index on created_at then tenant_id is not used efficiently for queries filtering one tenant by recent time.',
    action: 'Evaluate an index beginning with tenant_id and then created_at against the actual query plan and workload',
    failure: 'Queries scan excessive rows or writes slow down under unused and overlapping indexes',
    evidence: 'Inspect query predicates, selectivity, ordering, actual plans, row counts, writes, and index usage statistics',
    boundary: 'low-selectivity values, expressions, leading wildcards, NULLs, and range predicates affect usable index prefixes',
    tradeoff: 'Indexes reduce selected read work while consuming storage and adding maintenance to every affected write',
    verification: 'Compare realistic plans and timings before and after the index across both reads and writes',
    outcome: 'Important queries locate and order a small relevant row set without unnecessary table work',
    misconception: 'Adding an index on every queried column always improves database performance',
    operation: 'Track index usage, size, write amplification, fragmentation where relevant, and plan regressions',
    review: 'Which exact predicate and order does this index serve, and what write cost does it introduce?',
  },
  {
    id: 'query-plans',
    title: 'Query Plans & Performance Diagnosis',
    questionTarget: 20,
    principle: 'Database performance work should start from the actual execution plan and measured row flow rather than query appearance',
    scenario: 'A query expected to return ten rows estimates one row but actually processes two million after a join.',
    action: 'Find the first major estimate divergence and check statistics, predicates, and join cardinality at that operator',
    failure: 'A query scans, sorts, spills, or repeats work far beyond the rows required by its result',
    evidence: 'Use an actual plan with estimated and actual rows, timings, I/O, spills, loops, and wait information',
    boundary: 'parameter-sensitive plans, stale statistics, cached plans, and warm buffers make one measurement misleading',
    tradeoff: 'A targeted rewrite or index can improve one workload while making another parameter shape or write path worse',
    verification: 'Benchmark representative parameter distributions and compare total work, not only one elapsed time',
    outcome: 'Performance changes address the measured bottleneck and remain effective across realistic inputs',
    misconception: 'A sequential scan is always evidence that the optimizer made a bad choice',
    operation: 'Capture slow-query trends, plan changes, resource waits, and representative parameter shapes',
    review: 'Which operator dominates work, and does the proposed fix improve actual row flow for the full workload?',
  },
  {
    id: 'transactions-acid',
    title: 'Transactions & ACID',
    questionTarget: 20,
    principle: 'A transaction defines one durable consistency boundary whose changes commit together or remain unapplied',
    scenario: 'A transfer debits one account, then a process failure occurs before the credit is committed.',
    action: 'Perform both balance changes and invariant checks inside one database transaction',
    failure: 'Observers see a partially applied business operation or committed data violates a stated invariant',
    evidence: 'Trace transaction begin, reads, writes, constraints, commit or rollback, and values visible to other sessions',
    boundary: 'external calls and messages cannot normally participate atomically in the same local database transaction',
    tradeoff: 'Larger transactions simplify atomic invariants but increase lock duration, contention, and retry cost',
    verification: 'Inject errors at every statement and commit boundary and assert either the complete result or no result',
    outcome: 'Related durable changes preserve their invariant through failures and concurrent access',
    misconception: 'A transaction makes external HTTP calls roll back when the database rolls back',
    operation: 'Monitor transaction duration, aborts, retries, lock waits, and invariant violations',
    review: 'Does the transaction boundary match one business invariant without including avoidable slow work?',
  },
  {
    id: 'transaction-isolation',
    title: 'Isolation Levels & Concurrency Anomalies',
    questionTarget: 20,
    principle: 'Isolation determines which concurrent observations are possible, so it must match the invariant enforced by the transaction',
    scenario: 'Two doctors each observe the other on call and concurrently mark themselves off, leaving nobody available.',
    action: 'Use an isolation strategy or explicit lock that detects the write-skew conflict and retry one transaction',
    failure: 'Concurrent transactions each appear valid alone but together produce lost updates, phantoms, skew, or invalid state',
    evidence: 'Write the interleaving of reads, writes, snapshots, locks, and commits under the configured isolation level',
    boundary: 'a predicate invariant spans multiple rows even though transactions update different rows',
    tradeoff: 'Stronger isolation simplifies reasoning but can increase blocking, aborts, and retry requirements',
    verification: 'Run deterministic concurrent schedules that target each relevant anomaly and assert the invariant',
    outcome: 'Concurrent execution preserves the same business rule expected from a valid serial order',
    misconception: 'Read committed isolation makes every multi-statement decision safe from concurrent change',
    operation: 'Track serialization failures, retry success, lock waits, and anomaly-related invariant alerts',
    review: 'Which anomaly can break this invariant, and does the selected isolation or lock prevent it?',
  },
  {
    id: 'locks-deadlocks',
    title: 'Locks & Deadlocks',
    questionTarget: 16,
    principle: 'Locks coordinate conflicting access, while consistent acquisition order and short transactions reduce deadlock risk',
    scenario: 'One transfer locks account A then B while another locks B then A and both wait forever until one is aborted.',
    action: 'Acquire account locks in a stable global order and retry transactions chosen as deadlock victims',
    failure: 'Sessions wait in a cycle or broad locks block unrelated work for excessive time',
    evidence: 'Inspect the wait-for graph, held and requested locks, transaction statements, and lock duration',
    boundary: 'range locks, lock escalation, implicit foreign-key checks, and long user think time expand contention',
    tradeoff: 'Pessimistic locking prevents conflicting progress early but reduces concurrency and can create waits',
    verification: 'Force opposite operation orders concurrently and confirm bounded waits, victim handling, and invariant safety',
    outcome: 'Conflicting writes serialize predictably without indefinite blocking or corrupted state',
    misconception: 'A deadlock means the database is permanently stuck and must be restarted',
    operation: 'Capture deadlock graphs, lock-wait duration, victim statements, and transaction age',
    review: 'Can concurrent paths acquire the same resources in different orders or hold locks across slow work?',
  },
  {
    id: 'schema-migrations',
    title: 'Schema Migrations',
    questionTarget: 16,
    principle: 'A production schema change should remain compatible with every application version that can run during rollout',
    scenario: 'A migration renames a column before old application instances have stopped reading the original name.',
    action: 'Expand with the new shape, backfill and dual-read or write as needed, switch callers, then contract later',
    failure: 'A migration locks critical tables, breaks mixed versions, loses data, or cannot be resumed safely',
    evidence: 'Inspect table size, lock behavior, application version overlap, backfill progress, and rollback limitations',
    boundary: 'large backfills, new NOT NULL rules, uniqueness cleanup, and irreversible transformations require staged handling',
    tradeoff: 'Multi-step migrations take longer and carry temporary complexity but sharply reduce deployment coupling and downtime',
    verification: 'Rehearse forward and rollback paths on production-like volume while old and new code run together',
    outcome: 'Data and application versions evolve without a synchronized outage or an unsafe one-way operation',
    misconception: 'A migration is safe when it completes quickly on an empty development database',
    operation: 'Monitor lock waits, backfill rate, errors, replication lag, and adoption of the new schema path',
    review: 'What happens while versions overlap, and how can each migration step stop, resume, or roll back?',
  },
  {
    id: 'n-plus-one',
    title: 'N+1 Queries & Batching',
    questionTarget: 16,
    principle: 'Related data for a collection should be loaded with bounded set-based access rather than one round trip per item',
    scenario: 'Rendering 100 orders issues one order query followed by 100 separate customer queries.',
    action: 'Collect the needed customer keys and load them in one bounded query or deliberate join',
    failure: 'Latency and database load grow with result count because each parent triggers another query',
    evidence: 'Count database calls and repeated query shapes per request and correlate them with collection size',
    boundary: 'very large key sets, pagination, duplicate keys, authorization filters, and over-fetching affect the batching strategy',
    tradeoff: 'Batching reduces round trips but may load more data at once and requires mapping results back to callers',
    verification: 'Assert a bounded query count while varying the number of parent records and missing relationships',
    outcome: 'Collection latency grows with useful data rather than with avoidable network round trips',
    misconception: 'Fast individual queries cannot form an N+1 performance problem',
    operation: 'Track queries per request, repeated fingerprints, database time, and loaded row volume',
    review: 'Does any loop, serializer, or resolver perform data access once for every parent item?',
  },
  {
    id: 'database-pagination',
    title: 'Database Pagination & Stable Ordering',
    questionTarget: 12,
    principle: 'Database pagination needs a total stable order and a continuation condition that matches that order',
    scenario: 'A cursor uses only created_at, so rows sharing the last timestamp are skipped on the next page.',
    action: 'Order by created_at and unique ID and encode both values in the continuation predicate',
    failure: 'Rows are duplicated or skipped as data changes or sort values tie between page requests',
    evidence: 'Trace order keys, cursor values, inserted and deleted rows, and page boundaries across sequential requests',
    boundary: 'descending order, NULL sort values, changed sort keys, and deleted cursor rows alter continuation logic',
    tradeoff: 'Keyset pagination scales and remains stable for traversal, while offset pagination makes arbitrary page numbers simpler',
    verification: 'Page through tied values while inserting and deleting rows and compare the complete visited identity set',
    outcome: 'Large changing result sets can be traversed with predictable cost and no accidental gaps',
    misconception: 'A timestamp alone is always a unique and stable pagination cursor',
    operation: 'Observe deep-page latency, invalid cursor errors, duplicate reports, and sort-key distribution',
    review: 'Does the cursor contain every ordering key and use the correct comparison direction for ties?',
  },
  {
    id: 'database-types',
    title: 'Data Types, Precision, Dates & Time Zones',
    questionTarget: 16,
    principle: 'Database types should preserve domain meaning, precision, range, and time semantics without ambiguous conversion',
    scenario: 'Currency stored as binary floating point produces a total that differs by a cent after repeated additions.',
    action: 'Use an exact decimal or integer minor-unit representation with explicit currency and rounding rules',
    failure: 'Values round, overflow, compare, or shift time differently from the domain contract',
    evidence: 'Inspect stored type, conversion path, precision, timezone, locale, and boundary values from write to read',
    boundary: 'daylight-saving transitions, leap dates, values beyond range, and currencies with different minor units occur',
    tradeoff: 'Richer domain types preserve meaning but may require explicit conversion and indexing decisions',
    verification: 'Round-trip maximum, minimum, high-precision, timezone-transition, and ambiguous local-time values',
    outcome: 'Persisted values retain the same business meaning across calculations, systems, and time zones',
    misconception: 'A timestamp without timezone contains enough information to identify every real-world instant',
    operation: 'Alert on conversion failures, out-of-range values, and mismatched timezone or currency metadata',
    review: 'Does the selected type preserve the required units, precision, timezone, and valid range?',
  },
  {
    id: 'null-semantics',
    title: 'NULL, Defaults & Three-Valued Logic',
    questionTarget: 16,
    principle: 'NULL represents missing or unknown information and participates in SQL comparisons through three-valued logic',
    scenario: 'A predicate uses status != archived and unexpectedly excludes rows whose status is NULL.',
    action: 'Define the intended NULL meaning and handle it explicitly with IS NULL or a justified normalization',
    failure: 'Predicates, uniqueness, aggregates, or defaults treat unknown values as ordinary equal values',
    evidence: 'Evaluate each predicate for true, false, and unknown and inspect when defaults are applied',
    boundary: 'NULL in NOT IN, outer joins, unique constraints, aggregates, and composite expressions changes results',
    tradeoff: 'Allowing NULL distinguishes unknown from a value but adds semantics every query and invariant must handle',
    verification: 'Include NULL on each relevant side of comparisons, joins, aggregates, constraints, and inserts',
    outcome: 'Missing information has a deliberate representation and queries do not silently discard or misclassify it',
    misconception: 'The expression column = NULL tests whether a SQL value is missing',
    operation: 'Measure unexpected NULL rates and data paths that bypass intended defaults or backfills',
    review: 'What does NULL mean for this column, and how does every predicate and constraint treat that meaning?',
  },
  {
    id: 'database-programmability',
    title: 'Views, Triggers & Stored Routines',
    questionTarget: 8,
    principle: 'Database-side logic should have explicit ownership, side effects, security, and deployment behavior',
    scenario: 'Updating one table silently fires a trigger that writes another table and makes a retry fail unexpectedly.',
    action: 'Document and test the trigger side effect or move the workflow to an explicit owned boundary',
    failure: 'Hidden database behavior surprises application transactions, permissions, performance, or migration order',
    evidence: 'Trace invoked routines, trigger timing, changed rows, execution identity, plans, and recursive effects',
    boundary: 'bulk updates, recursion, disabled triggers, definer rights, and exceptions produce different behavior',
    tradeoff: 'Database logic centralizes rules near data but can hide control flow and couple behavior to one engine',
    verification: 'Exercise direct and application writes, bulk operations, failures, permissions, and migration sequencing',
    outcome: 'Shared data behavior remains enforceable without becoming invisible or operationally surprising',
    misconception: 'A view always stores a separate copy of its query results',
    operation: 'Observe routine latency, trigger failures, affected-row volume, and privilege use',
    review: 'Who owns this database behavior, when does it execute, and can callers discover its side effects?',
  },
  {
    id: 'database-recovery',
    title: 'Replication, Backups & Recovery',
    questionTarget: 12,
    principle: 'Durability planning must define acceptable data loss and recovery time and prove restoration regularly',
    scenario: 'A team has nightly backup files but has never restored one and assumes the recovery objective is met.',
    action: 'Run a timed restore drill and verify application consistency at the required recovery point',
    failure: 'Backups are corrupt, replicas repeat destructive writes, or failover serves stale or inconsistent data',
    evidence: 'Inspect backup completion, restore tests, replication lag, failover history, and measured recovery time and point',
    boundary: 'regional loss, credential loss, accidental deletion, point-in-time gaps, and schema-version mismatch occur',
    tradeoff: 'Lower recovery time and data loss objectives require more redundancy, automation, and cost',
    verification: 'Restore into an isolated environment, validate invariants, and rehearse failover plus application reconnection',
    outcome: 'The service can recover verified usable data within explicit business tolerances',
    misconception: 'A read replica is a backup because it contains another copy of current data',
    operation: 'Alert on backup age, failed restore checks, replication lag, and unmet recovery objectives',
    review: 'When was the last successful restore, and what data and time are lost in each failure scenario?',
  },
  {
    id: 'database-scaling',
    title: 'Partitioning, Sharding & Storage-Model Choice',
    questionTarget: 12,
    principle: 'Data distribution should follow measured scale, access patterns, consistency needs, and a stable routing key',
    scenario: 'A tenant-based shard key sends most traffic to one shard because one tenant is far larger than all others.',
    action: 'Measure skew and choose a distribution or sub-partitioning strategy that handles hot tenants explicitly',
    failure: 'One partition becomes hot, cross-shard operations dominate, or a chosen store cannot support required queries and consistency',
    evidence: 'Analyze data and request distribution, hot keys, cross-partition queries, growth, and rebalance cost',
    boundary: 'global uniqueness, transactions across shards, tenant moves, resharding, and uneven growth complicate routing',
    tradeoff: 'Distribution increases capacity but adds routing, coordination, operational, and query complexity',
    verification: 'Load realistic key distributions and exercise failover, rebalance, cross-partition queries, and growth limits',
    outcome: 'Storage scales along the dominant access pattern without sacrificing required correctness invisibly',
    misconception: 'Sharding is the first performance fix for any slow relational query',
    operation: 'Track per-partition size, throughput, latency, hot keys, rebalance progress, and cross-shard work',
    review: 'What measured limit requires distribution, and which operations become harder after this partition choice?',
  },
] satisfies readonly SoftwareMasteryTopicBlueprint[]

export const sqlDatabasesMasteryTopics = defineSoftwareMasteryTopics(
  'sql-databases',
  sqlDatabaseBlueprints,
)