import {
  defineSoftwareMasteryTopics,
  type SoftwareMasteryTopicBlueprint,
} from './software-core-mastery-builder'

const testingBlueprints = [
  {
    id: 'test-purpose-oracles',
    title: 'Test Purpose, Oracles & Assertions',
    questionTarget: 20,
    principle: 'A useful test states one meaningful behavior and compares observed results with an independent source of truth',
    scenario: 'A test reproduces the production formula inside its expected-value calculation and passes when both contain the same defect.',
    action: 'Express the expected outcome from the requirement with fixed examples or a simpler independent oracle',
    failure: 'A test passes without detecting broken behavior or fails without identifying which contract changed',
    evidence: 'Inspect the test name, setup, operation, observable assertion, and independence of the expected result',
    boundary: 'nondeterministic output and approximate numeric results require explicit tolerances or invariant-based oracles',
    tradeoff: 'Broad assertions catch more change but often diagnose poorly and couple unrelated behavior',
    verification: 'Introduce a representative defect and confirm the test fails for the intended reason',
    outcome: 'Failures provide credible evidence that a user-visible or system contract no longer holds',
    misconception: 'A test is valuable whenever it executes code without throwing an exception',
    operation: 'Review escaped defects to identify missing or weak oracles rather than only increasing test count',
    review: 'What specific contract does this assertion prove, and could the implementation and oracle share the same mistake?',
  },
  {
    id: 'unit-boundaries',
    title: 'Unit Test Boundaries',
    questionTarget: 20,
    principle: 'A unit test should isolate a coherent behavior boundary and replace only collaborators irrelevant to that behavior',
    scenario: 'A service unit test mocks every internal method and breaks whenever a private helper is renamed.',
    action: 'Exercise the public behavior and substitute only slow or nondeterministic external collaborators',
    failure: 'Tests mirror implementation structure, miss real collaboration, or become slow despite being labeled unit tests',
    evidence: 'Inspect the public contract, dependency ownership, test doubles, runtime, and reasons for failure after refactoring',
    boundary: 'pure functions may need no substitutes, while orchestration code needs observable collaborator effects',
    tradeoff: 'Narrow units give fast diagnosis but cannot prove integration contracts or production wiring',
    verification: 'Refactor internals without changing behavior and confirm the tests remain meaningful and stable',
    outcome: 'Developers receive fast focused feedback about one behavior without coupling tests to private structure',
    misconception: 'A unit test must test exactly one class with every dependency mocked',
    operation: 'Track unit-suite duration and brittle failures caused only by internal refactoring',
    review: 'Is this boundary coherent, and are substitutes used because of behavior needs rather than habit?',
  },
  {
    id: 'integration-testing',
    title: 'Integration Testing',
    questionTarget: 20,
    principle: 'Integration tests should exercise real contracts between components where configuration, protocol, or persistence defects can occur',
    scenario: 'Repository tests mock the database driver and miss that the production query uses an unsupported column type.',
    action: 'Run the repository against a representative database with real migrations and isolated test data',
    failure: 'Components pass alone but fail together because schemas, serialization, transactions, or configuration disagree',
    evidence: 'Inspect the real components included, environment parity, boundary inputs, persisted state, and cleanup behavior',
    boundary: 'external paid services may require a faithful local implementation plus separate provider contract checks',
    tradeoff: 'Real integrations improve fidelity but cost more setup, runtime, isolation, and failure diagnosis',
    verification: 'Break the interface deliberately and confirm the integration suite detects the mismatch',
    outcome: 'Important component boundaries are proven with the implementations and configuration used in delivery',
    misconception: 'An integration test must call every service in the complete production system',
    operation: 'Pin test-service versions and monitor setup failures separately from product failures',
    review: 'Which real boundary risk does this test cover that a unit test cannot?',
  },
  {
    id: 'end-to-end-testing',
    title: 'End-to-End & System Testing',
    questionTarget: 12,
    principle: 'End-to-end tests should protect a small set of critical journeys through the deployed system from a user-observable boundary',
    scenario: 'Hundreds of browser tests duplicate every validation rule and make the release pipeline slow and flaky.',
    action: 'Keep representative critical journeys end to end and move detailed rule combinations to lower test layers',
    failure: 'The suite is too brittle to trust or omits the few workflows whose cross-system wiring matters most',
    evidence: 'Map business-critical journeys to tests, involved services, runtime, failure rate, and unique defects found',
    boundary: 'third-party outages and asynchronous completion require controlled dependencies and observable waiting conditions',
    tradeoff: 'System tests provide high-confidence wiring evidence but are slower and less diagnostic than focused tests',
    verification: 'Run the journey in a production-like deployment and confirm failures identify the broken user outcome',
    outcome: 'A concise suite proves that the system can complete its highest-value workflows as assembled',
    misconception: 'More end-to-end tests always provide more confidence than lower-level tests',
    operation: 'Track runtime, flake rate, failure ownership, and critical-journey coverage',
    review: 'Does this test uniquely prove an important assembled-system outcome?',
  },
  {
    id: 'test-strategy',
    title: 'Test Strategy & Pyramid',
    questionTarget: 16,
    principle: 'Test layers should be chosen by risk, feedback speed, fidelity, and diagnostic value rather than fixed quotas',
    scenario: 'A team tests all business rules only through the browser because those tests seem closest to users.',
    action: 'Place deterministic rules in fast focused tests and retain higher-level checks for integration and journey risk',
    failure: 'Feedback is slow, duplicated, fragile, or blind to a boundary because all checks use one layer',
    evidence: 'Inventory risks, defect history, test layer, runtime, flakiness, and unique confidence supplied by each suite',
    boundary: 'legacy coupling may justify characterization tests before smaller seams can be introduced',
    tradeoff: 'Lower tests are fast and diagnostic; higher tests add realism but cost time and stability',
    verification: 'Map every important risk to the cheapest test capable of detecting it with adequate fidelity',
    outcome: 'The test portfolio returns useful confidence quickly and reserves expensive checks for real boundary risk',
    misconception: 'The test pyramid prescribes one universal percentage for every layer',
    operation: 'Remove redundant low-value tests and track confidence, duration, and escaped defects by layer',
    review: 'Is this the lowest-cost test boundary that can credibly detect the targeted failure?',
  },
  {
    id: 'boundary-analysis',
    title: 'Boundaries & Equivalence Partitions',
    questionTarget: 20,
    principle: 'Inputs should be partitioned by behavior and tested at values where the system changes state or interpretation',
    scenario: 'An age rule allows 18 and above, but tests cover only 25 and 12 and miss an off-by-one defect.',
    action: 'Test immediately below, at, and above the boundary, plus distinct invalid and absent input classes',
    failure: 'Representative happy examples pass while defects remain at limits, transitions, and special categories',
    evidence: 'Derive partitions and boundaries from validation rules, types, state transitions, and downstream limits',
    boundary: 'inclusive limits, empty collections, Unicode, numeric overflow, and time transitions create additional classes',
    tradeoff: 'Partitioning reduces redundant examples but depends on correctly identifying behaviorally distinct inputs',
    verification: 'Mutate each comparison boundary and confirm at least one focused case fails',
    outcome: 'A compact set of cases covers the points most likely to expose condition and representation defects',
    misconception: 'Random middle values cover boundary conditions adequately when enough are tested',
    operation: 'Add newly discovered production input classes to the partition model and regression suite',
    review: 'At which exact values does behavior change, and is each side of every boundary represented?',
  },
  {
    id: 'failure-paths',
    title: 'Success, Failure & Exception Paths',
    questionTarget: 20,
    principle: 'Tests should prove both intended success and safe behavior when each meaningful dependency or invariant fails',
    scenario: 'Checkout tests cover successful payment but not a timeout after the provider may have accepted the charge.',
    action: 'Simulate ambiguous timeout, duplicate delivery, rejection, and persistence failure and assert safe recovery behavior',
    failure: 'An exception leaks resources, loses context, duplicates side effects, or leaves partial state',
    evidence: 'List failure points, resulting state, emitted errors, cleanup, retries, and externally observable side effects',
    boundary: 'failure after a remote side effect but before local acknowledgement requires reconciliation rather than blind retry',
    tradeoff: 'Failure-path tests add setup complexity but target cases with disproportionate user and operational impact',
    verification: 'Inject faults before and after each state transition and assert invariants and retry behavior',
    outcome: 'The system fails predictably without corrupting state or amplifying an uncertain operation',
    misconception: 'Catching an exception is enough evidence that a failure path is correct',
    operation: 'Use production failure modes and incident data to prioritize new fault scenarios',
    review: 'What state and side effects remain if this exact operation fails at each boundary?',
  },
  {
    id: 'parameterized-tests',
    title: 'Parameterized & Table-Driven Tests',
    questionTarget: 16,
    principle: 'Table-driven tests should express many examples of one behavior with readable case data and shared execution logic',
    scenario: 'Twenty copied validation tests differ only in input and expected error and drift during maintenance.',
    action: 'Create named cases containing input and expected observable result while keeping exceptional behavior separate',
    failure: 'Dense parameter tables hide intent, share the wrong setup, or make one failed row difficult to diagnose',
    evidence: 'Inspect case names, columns, behavior similarity, failure output, and whether setup truly belongs to every case',
    boundary: 'cases requiring different control flow or assertions may deserve focused tests rather than more table flags',
    tradeoff: 'Parameterization reduces repetition but can turn tests into an unreadable mini-language',
    verification: 'Run one case at a time and confirm its failure message identifies the scenario and expected contract',
    outcome: 'Equivalent examples remain consistent, concise, and independently diagnosable',
    misconception: 'Every similar-looking test should be combined into one parameterized function',
    operation: 'Keep generated case identifiers stable enough for CI reruns and failure tracking',
    review: 'Do all rows exercise the same behavior shape, and can a failed case explain itself?',
  },
  {
    id: 'fixtures-isolation',
    title: 'Fixtures, Builders & Data Isolation',
    questionTarget: 16,
    principle: 'Test data setup should expose relevant differences, isolate state, and make invalid combinations difficult to create accidentally',
    scenario: 'A shared mutable fixture accumulates records, so tests pass alone but fail in a different suite order.',
    action: 'Create fresh owned data per test with builders that provide valid defaults and explicit overrides',
    failure: 'Tests depend on execution order, hidden global state, stale data, or unrelated fixture details',
    evidence: 'Inspect setup ownership, cleanup, transaction boundaries, unique identifiers, defaults, and parallel execution',
    boundary: 'database commits, worker processes, caches, and external resources may escape ordinary rollback cleanup',
    tradeoff: 'Rich shared fixtures reduce setup code but increase coupling and obscure which facts matter to a test',
    verification: 'Run tests repeatedly, shuffled, and in parallel against a clean environment',
    outcome: 'Every test controls its preconditions and remains stable regardless of neighboring execution',
    misconception: 'A global fixture is safe when tests only read most of its fields',
    operation: 'Detect leaked resources and make cleanup failures visible rather than silently ignoring them',
    review: 'Which setup values matter to this behavior, and can another test mutate or retain them?',
  },
  {
    id: 'test-doubles',
    title: 'Mocks, Stubs, Fakes & Spies',
    questionTarget: 20,
    principle: 'Choose a test double by the behavior needed: supplied answers, recorded interaction, or a lightweight working implementation',
    scenario: 'A mock database accepts a query shape that the real database rejects, so all repository tests pass falsely.',
    action: 'Use a real database integration test for query compatibility and reserve doubles for controlled collaborator behavior',
    failure: 'A double lies about a contract, over-specifies call mechanics, or carries behavior different from production',
    evidence: 'Inspect why the double exists, what contract it implements, interaction assertions, and validation against the real dependency',
    boundary: 'network failures, time, randomness, and rare provider responses may require programmable substitutes even with integration coverage',
    tradeoff: 'Doubles make tests fast and deterministic but can reduce fidelity and increase implementation coupling',
    verification: 'Run contract examples against both the substitute and real implementation where interchangeability matters',
    outcome: 'Tests control difficult collaborators without inventing a false version of production behavior',
    misconception: 'Mock is the generic name and best implementation for every substituted dependency',
    operation: 'Update provider contract checks when SDKs or external APIs change',
    review: 'What risk does this double remove, and what real contract evidence prevents it from lying?',
  },
  {
    id: 'behavior-assertions',
    title: 'Behavior vs Implementation Assertions',
    questionTarget: 20,
    principle: 'Tests should assert stable observable contracts and only inspect interactions when the interaction itself is required behavior',
    scenario: 'A test asserts the exact sequence of private helper calls for a calculation whose returned value is the real contract.',
    action: 'Assert the result and meaningful side effects, removing expectations tied only to the current implementation path',
    failure: 'Safe refactors break tests while genuine behavior regressions remain hidden behind satisfied call expectations',
    evidence: 'Classify each assertion as user result, durable state, external effect, protocol obligation, or private mechanism',
    boundary: 'audit events and idempotency-key propagation are interactions that can be part of the public contract',
    tradeoff: 'Interaction assertions can precisely protect protocols but are more coupled than state or result assertions',
    verification: 'Replace the internal algorithm with an equivalent implementation and confirm contract tests still pass',
    outcome: 'Tests support refactoring while remaining strict about behavior consumers depend on',
    misconception: 'Verifying every collaborator call makes a unit test more complete',
    operation: 'Use test-change frequency during refactors to identify over-coupled suites',
    review: 'Would a consumer care about this assertion if the implementation changed but behavior did not?',
  },
  {
    id: 'deterministic-seams',
    title: 'Deterministic Seams for Time and Randomness',
    questionTarget: 16,
    principle: 'Time, randomness, identifiers, and scheduling should enter testable logic through controllable boundaries',
    scenario: 'An expiry test sleeps until a token ages and occasionally fails on a slow CI worker.',
    action: 'Inject or pass a clock, advance it explicitly, and assert behavior immediately around the expiry instant',
    failure: 'Tests depend on wall-clock delay, random chance, global state, or machine scheduling',
    evidence: 'Find direct time and random reads, sleeps, generated IDs, seeds, and concurrency waits in the tested path',
    boundary: 'monotonic duration and civil calendar time have different semantics and should not share one careless clock abstraction',
    tradeoff: 'Controllable seams add explicit dependencies but make rare states fast and reproducible',
    verification: 'Replay the same seed and timestamps and test immediately before, at, and after temporal boundaries',
    outcome: 'Tests can reproduce time- and randomness-dependent behavior without waiting or chance',
    misconception: 'Using a shorter sleep makes a timing test deterministic enough',
    operation: 'Log reproducible seeds and simulated timestamps whenever generated cases fail',
    review: 'Which uncontrolled source can make this test produce a different result on the same code?',
  },
  {
    id: 'async-concurrency-tests',
    title: 'Async & Concurrency Testing',
    questionTarget: 16,
    principle: 'Concurrency tests should coordinate meaningful interleavings and await observable completion instead of relying on timing guesses',
    scenario: 'A race test starts two tasks, sleeps 100 milliseconds, and assumes both reached the critical section.',
    action: 'Use barriers or controlled hooks to place both tasks at the conflict and then release them in the target order',
    failure: 'A test passes without exercising the race or flakes because scheduler timing differs',
    evidence: 'Record task lifecycle, synchronization points, awaited results, shared-state transitions, and uncaught errors',
    boundary: 'cancellation, timeout, partial completion, repeated delivery, and resource cleanup require distinct schedules',
    tradeoff: 'Controlled schedules are more code than sleeps but produce deterministic evidence about specific races',
    verification: 'Repeat the forced interleaving and assert invariant, completion, exception propagation, and cleanup',
    outcome: 'Tests reliably expose concurrency defects rather than hoping the scheduler produces them',
    misconception: 'Running a test many times is equivalent to controlling the interleaving it must verify',
    operation: 'Capture task dumps and scheduler context for failed stress tests and preserve the reproducing schedule',
    review: 'Does this test force the conflicting state, and does it await every relevant asynchronous result?',
  },
  {
    id: 'database-tests',
    title: 'Database & Transaction Testing',
    questionTarget: 16,
    principle: 'Database tests should use the real engine semantics for queries, constraints, transactions, and concurrency they claim to verify',
    scenario: 'Tests use an in-memory substitute that ignores production isolation and foreign-key behavior.',
    action: 'Run focused tests against the production database engine with migrations and isolated transaction scenarios',
    failure: 'Queries, constraints, locks, precision, or rollback behavior differ only after deployment',
    evidence: 'Inspect engine and version, schema creation, transaction boundaries, committed visibility, and cleanup',
    boundary: 'a rollback-per-test pattern cannot isolate behavior performed by separate worker connections',
    tradeoff: 'Real database tests cost startup and cleanup time but provide semantics that mocks cannot reproduce faithfully',
    verification: 'Exercise constraint failures, commit and rollback, concurrent sessions, and migration compatibility',
    outcome: 'Persistence behavior is verified under the same rules that protect production data',
    misconception: 'A repository mock proves that SQL and database constraints are correct',
    operation: 'Keep test engine versions aligned and rebuild environments from migrations regularly',
    review: 'Which database-specific guarantee does this test need, and is the actual engine providing it?',
  },
  {
    id: 'api-contract-tests',
    title: 'API & Contract Testing',
    questionTarget: 16,
    principle: 'Contract tests should protect request, response, error, and compatibility expectations at service boundaries',
    scenario: 'A provider renames a response field and deploys before its consumer is updated.',
    action: 'Validate provider output and consumer expectations against a versioned shared contract before independent release',
    failure: 'Services remain internally correct but disagree about schema, status, serialization, or optional fields',
    evidence: 'Inspect contract versions, representative payloads, error cases, compatibility rules, and provider verification results',
    boundary: 'unknown fields, absent optional values, enum expansion, and asynchronous events require explicit evolution policy',
    tradeoff: 'Contract tests catch interface drift quickly but cannot prove full business behavior or production networking',
    verification: 'Run consumer examples against the provider implementation and test backward-compatible and breaking changes',
    outcome: 'Independently deployed components evolve without surprising existing consumers',
    misconception: 'Matching an OpenAPI schema proves every API behavior and semantic guarantee',
    operation: 'Publish contract versions and prevent incompatible provider changes until consumer support is known',
    review: 'Which consumer assumption could this change violate even if the payload remains syntactically valid?',
  },
  {
    id: 'property-based-tests',
    title: 'Property-Based & Invariant Testing',
    questionTarget: 12,
    principle: 'Property-based tests explore generated input space against invariants that should hold for every valid case',
    scenario: 'A parser passes hand-picked examples but fails on a nested escaped input no developer anticipated.',
    action: 'Generate valid structured inputs and assert round-trip, normalization, and non-crash properties with shrinking',
    failure: 'A weak property is always true, a generator misses important shapes, or invalid cases dominate useful exploration',
    evidence: 'Inspect generator distribution, preconditions, invariant strength, seed, shrunk counterexample, and coverage labels',
    boundary: 'stateful systems and constrained structures need model-based generators rather than arbitrary bytes alone',
    tradeoff: 'Generated exploration finds surprising cases but requires careful properties and does not replace concrete business examples',
    verification: 'Seed known defects into the implementation and confirm generation finds a minimal counterexample',
    outcome: 'Broad input classes receive repeatable automated exploration beyond examples authors happened to imagine',
    misconception: 'Property-based testing simply generates many random values and checks that code does not crash',
    operation: 'Persist failing seeds and minimal examples as regression cases and monitor generator coverage',
    review: 'Is the property strong, the generator representative, and the counterexample reproducible?',
  },
  {
    id: 'flaky-tests',
    title: 'Flaky Test Diagnosis',
    questionTarget: 20,
    principle: 'A flaky test is a real reliability defect whose nondeterministic dependency must be identified, not hidden by retries',
    scenario: 'A CI test fails one run in fifty and the pipeline is configured to retry until green.',
    action: 'Capture failing state, vary order and load, isolate shared resources, and replace timing assumptions with observable synchronization',
    failure: 'Retries normalize intermittent failures, increasing noise and allowing product races to escape',
    evidence: 'Collect seed, order, timing, worker, resource state, logs, ownership, and failure signature across runs',
    boundary: 'the flaky signal may reveal a production race rather than only a defective test',
    tradeoff: 'Quarantining can restore signal temporarily but reduces coverage and requires an owner and deadline',
    verification: 'Reproduce under the identified condition and run repeated ordered and parallel checks after the fix',
    outcome: 'The suite gives stable evidence and intermittent product defects become actionable',
    misconception: 'A test that passes on retry is safe to ignore because the code eventually works',
    operation: 'Track flake rate, quarantine age, retries, ownership, and lost engineering time as quality metrics',
    review: 'Which uncontrolled dependency changes the result, and could the same race affect users?',
  },
  {
    id: 'coverage-mutation',
    title: 'Coverage & Mutation Testing',
    questionTarget: 12,
    principle: 'Coverage shows executed structure, while mutation testing probes whether assertions detect plausible behavioral changes',
    scenario: 'A module reports 100 percent line coverage even after its central comparison is reversed.',
    action: 'Inspect branch and mutation results, then add a contract assertion that kills the surviving comparison mutation',
    failure: 'Teams optimize a percentage while tests execute code without checking meaningful outcomes',
    evidence: 'Review uncovered risks, branch paths, surviving mutations, equivalent mutations, and defects found by the suite',
    boundary: 'generated code and defensive impossible branches can distort both coverage and mutation scores',
    tradeoff: 'Mutation analysis gives stronger signal than line counts but consumes compute and requires triage',
    verification: 'Introduce representative logic changes and confirm focused tests fail for the correct contract reason',
    outcome: 'Coverage metrics guide investigation while assertion strength determines confidence',
    misconception: 'One hundred percent line coverage guarantees complete behavior testing',
    operation: 'Trend risk-focused coverage and surviving mutations without making raw percentages a release goal',
    review: 'What important defect could survive despite these lines being executed?',
  },
  {
    id: 'regression-tdd',
    title: 'Regression Tests & TDD',
    questionTarget: 16,
    principle: 'A regression test should reproduce a defect before the fix, while test-driven development uses small failing contracts to guide design',
    scenario: 'A bug fix is committed with a test that was written afterward and never shown to fail on the broken code.',
    action: 'Reproduce the failure in a focused test, verify it fails, implement the fix, and retain the test',
    failure: 'The test covers a nearby example but cannot distinguish the defective implementation from the corrected one',
    evidence: 'Record the original symptom, failing assertion, minimal input, fix diff, and passing result',
    boundary: 'a production incident may need an initial characterization test before code can be safely reorganized',
    tradeoff: 'Test-first work adds an explicit feedback step but limits speculative implementation and protects future change',
    verification: 'Run the regression against the parent revision or temporarily reverse the fix and confirm failure',
    outcome: 'Every corrected defect leaves executable evidence that prevents the same behavior from returning',
    misconception: 'A test added in the same commit automatically proves it would catch the original bug',
    operation: 'Link incidents and defects to focused regression tests and remove only when the protected contract no longer exists',
    review: 'Did this exact test fail for the original behavior before the implementation changed?',
  },
  {
    id: 'snapshot-approval-tests',
    title: 'Snapshot, Golden & Approval Tests',
    questionTarget: 8,
    principle: 'Approval tests are useful for complex stable output only when changes are reviewed semantically rather than accepted wholesale',
    scenario: 'A large UI snapshot changes after a component edit and the author updates it without inspecting the diff.',
    action: 'Reduce the snapshot to meaningful stable output and review each changed region against intended behavior',
    failure: 'Snapshots become noisy change detectors that hide regressions in large routine updates',
    evidence: 'Inspect snapshot size, unstable fields, diff readability, reviewer behavior, and unique defects detected',
    boundary: 'timestamps, generated IDs, locale, and rendering-engine changes require normalization or a different assertion style',
    tradeoff: 'Golden outputs cheaply cover rich structures but diagnose poorly and can encourage uncritical regeneration',
    verification: 'Introduce a meaningful output defect and confirm the review diff is focused enough to identify it',
    outcome: 'Complex output receives broad regression protection without turning expected files into unreadable noise',
    misconception: 'Updating a snapshot after any intentional code change is sufficient review',
    operation: 'Track oversized or frequently regenerated snapshots and replace them with focused assertions where value declines',
    review: 'Can a reviewer understand every changed snapshot line and connect it to intended behavior?',
  },
] satisfies readonly SoftwareMasteryTopicBlueprint[]

export const testingMasteryTopics = defineSoftwareMasteryTopics(
  'testing',
  testingBlueprints,
)