import {
  defineSoftwareMasteryTopics,
  type SoftwareMasteryTopicBlueprint,
} from './software-core-mastery-builder'

const gitDevelopmentBlueprints = [
  {
    id: 'git-object-model',
    title: 'Working Tree, Index & Commit Model',
    questionTarget: 20,
    principle: 'Git records snapshots addressed by content while the working tree, index, and current commit represent distinct states',
    scenario: 'A developer edits two files, stages only one, and assumes both changes will appear in the next commit.',
    action: 'Inspect working-tree and staged diffs separately, then stage exactly the coherent change intended for the commit',
    failure: 'A commit contains missing, unintended, or stale content because index state was confused with working-tree state',
    evidence: 'Compare HEAD, the index, the working tree, and untracked files with status and scoped diffs',
    boundary: 'partially staged files and generated changes make one path contain content in more than one state',
    tradeoff: 'An explicit staging area adds a step but lets developers construct focused snapshots from mixed local work',
    verification: 'Inspect the cached diff immediately before committing and the resulting commit immediately afterward',
    outcome: 'Each commit records the exact intended snapshot without discarding unrelated local work',
    misconception: 'Git commit automatically includes every modified file in the working directory',
    operation: 'Use clean-tree checks in automation and preserve recovery references before risky history operations',
    review: 'Does the staged snapshot stand alone as the change described by the commit message?',
  },
  {
    id: 'git-inspection',
    title: 'Status, Diff & Log Inspection',
    questionTarget: 16,
    principle: 'Safe Git work begins by inspecting the exact state and history before applying a modifying command',
    scenario: 'A developer wants to discard a change but has not determined whether it is unstaged, staged, or already committed.',
    action: 'Use status and the relevant working, staged, and commit diffs to locate the change first',
    failure: 'A command changes the wrong state because the developer acted on an assumed repository condition',
    evidence: 'Read branch tracking, status categories, scoped diffs, commit graph, authorship, and path history',
    boundary: 'renames, ignored files, submodules, merge state, and detached HEAD alter ordinary output interpretation',
    tradeoff: 'Detailed inspection takes moments but avoids broad recovery work and preserves unrelated changes',
    verification: 'Run the same inspection after the operation and compare the intended paths and references',
    outcome: 'Repository actions are chosen from evidence about current state rather than memory or guesswork',
    misconception: 'git diff always shows every change that would be included in the next commit',
    operation: 'Capture relevant commit IDs and diffs in incident or release records where reproducibility matters',
    review: 'Which repository layer and reference does this command read or modify?',
  },
  {
    id: 'atomic-commits',
    title: 'Atomic Commits',
    questionTarget: 16,
    principle: 'One commit should represent one coherent behavior change that can be reviewed, tested, and reverted independently',
    scenario: 'A commit mixes a schema migration, unrelated formatting, and a bug fix in one large diff.',
    action: 'Separate the work into ordered commits whose messages explain one purpose and whose states remain buildable',
    failure: 'Reviewers cannot isolate intent and reverting one change removes unrelated valid work',
    evidence: 'Inspect diff scope, dependency order, tests, commit message, and whether each snapshot is internally consistent',
    boundary: 'a refactor may be inseparable from behavior only when no stable intermediate state can preserve the contract',
    tradeoff: 'Smaller commits improve review and recovery but excessive fragmentation can hide one logical change across noise',
    verification: 'Check out or inspect each commit and run the focused checks relevant to its stated purpose',
    outcome: 'History becomes a sequence of understandable decisions that supports review, bisect, and revert',
    misconception: 'An atomic commit means changing only one file',
    operation: 'Keep generated artifacts and migrations aligned with the commit that requires them',
    review: 'Can this commit be explained and reverted without pulling an unrelated concern with it?',
  },
  {
    id: 'branches-refs-head',
    title: 'Branches, References & HEAD',
    questionTarget: 16,
    principle: 'A branch is a movable reference to a commit, while HEAD identifies the currently checked-out reference or commit',
    scenario: 'A developer commits while HEAD points directly to a commit and later cannot find the work on any branch.',
    action: 'Create or move a named branch to the detached commit before switching away',
    failure: 'Work becomes hard to locate or a branch moves unexpectedly because references and commits were treated as the same thing',
    evidence: 'Inspect HEAD, branch references, reflog entries, commit parents, and the decorated commit graph',
    boundary: 'detached HEAD, force updates, deleted branches, and remote-tracking references require different recovery reasoning',
    tradeoff: 'Lightweight branches make parallel work cheap, but their names are movable pointers rather than permanent commit identities',
    verification: 'Resolve each relevant reference to its commit before and after the operation and confirm reachability',
    outcome: 'Developers can predict how commits and branch names move through checkout, commit, merge, and reset operations',
    misconception: 'Creating a Git branch copies every file into a separate directory',
    operation: 'Use protected shared references and retain reflogs or remote history long enough for practical recovery',
    review: 'Which reference will move, which commit will it identify, and where will HEAD point afterward?',
  },
  {
    id: 'merge-vs-rebase',
    title: 'Merge vs Rebase',
    questionTarget: 20,
    principle: 'Merge combines histories with a new relationship, while rebase recreates commits on a new parent and changes their identities',
    scenario: 'A developer rebases commits that teammates already pulled and then force pushes the shared branch.',
    action: 'Preserve published history with a merge or coordinate an explicit rewrite before anyone builds on it',
    failure: 'Shared work is duplicated, lost, or difficult to reconcile after rewritten commit identities are published',
    evidence: 'Inspect the before-and-after graph, published references, commit identities, and downstream branches',
    boundary: 'a local unshared branch can be rewritten safely while a protected shared branch generally cannot',
    tradeoff: 'Rebase creates a linear story but rewrites identity; merge preserves historical topology but adds merge commits',
    verification: 'Compare tree content and run tests after conflict resolution regardless of which integration method is used',
    outcome: 'Teams integrate current work while choosing history shape and collaboration risk deliberately',
    misconception: 'Rebase and merge produce identical commit history because final files can match',
    operation: 'Protect shared branches from unreviewed force pushes and document the chosen integration policy',
    review: 'Has this history been published, and does preserving its existing identities matter to collaborators?',
  },
  {
    id: 'conflict-resolution',
    title: 'Conflict Resolution',
    questionTarget: 20,
    principle: 'A conflict must be resolved by reconstructing intended behavior from the base and both changes, not by selecting text mechanically',
    scenario: 'Two branches change the same validation function for different business rules and Git cannot combine them.',
    action: 'Understand both intents, write the combined correct behavior, and run focused tests before completing integration',
    failure: 'The merge compiles but silently drops one branch intent or preserves incompatible assumptions',
    evidence: 'Compare base, ours, theirs, surrounding call sites, tests, requirements, and the resolved diff',
    boundary: 'renames, generated files, schema changes, and semantic conflicts may not produce ordinary conflict markers',
    tradeoff: 'Resolving with full context takes longer than choosing one side but prevents subtle regression in apparently valid code',
    verification: 'Run tests covering behavior from both branches and inspect the final staged merge result',
    outcome: 'The integrated code preserves compatible intent and explicitly decides incompatible behavior',
    misconception: 'Accept ours is safe whenever the current branch passed tests before the merge',
    operation: 'Record non-obvious conflict decisions in the commit or pull request so later diagnosis has context',
    review: 'What behavior did each side intend, and which test proves the resolution preserves the chosen combination?',
  },
  {
    id: 'git-remotes',
    title: 'Remotes, Fetch, Pull & Push',
    questionTarget: 16,
    principle: 'Remote operations exchange objects and update references; local and remote-tracking branches remain distinct',
    scenario: 'A developer runs pull without inspecting incoming commits and receives an unexpected merge on a dirty branch.',
    action: 'Fetch first, inspect the tracking difference, then choose and perform the intended integration on a clean state',
    failure: 'Local history diverges or an unexpected merge, rejection, or overwrite follows an incorrect assumption about remote state',
    evidence: 'Inspect configured upstreams, fetch results, ahead and behind counts, and the local versus remote commit graph',
    boundary: 'force pushes, deleted remote branches, shallow clones, and multiple remotes change ordinary synchronization',
    tradeoff: 'Convenient combined pull operations save steps, while separate fetch and integrate make review and intent clearer',
    verification: 'Confirm local and remote references identify the expected commits after synchronization',
    outcome: 'Developers exchange work without confusing fetched knowledge with integrated local history',
    misconception: 'git fetch changes the files in the current working tree to match the remote branch',
    operation: 'Use protected branches, explicit upstreams, and force-with-lease when a coordinated rewrite is unavoidable',
    review: 'Which local and remote references change, and is integration or publication part of this command?',
  },
  {
    id: 'pull-request-design',
    title: 'Pull Request Design',
    questionTarget: 16,
    principle: 'A pull request should make purpose, scope, risk, evidence, and rollout behavior easy for another engineer to evaluate',
    scenario: 'A large pull request says update code and provides no tests, screenshots, migration notes, or risk explanation.',
    action: 'Narrow the change and describe the problem, approach, important decisions, verification, deployment, and rollback',
    failure: 'Reviewers must reverse-engineer intent or cannot assess user impact, compatibility, and operational risk',
    evidence: 'Compare stated scope with the diff, linked requirement, test results, artifacts, migration, and monitoring plan',
    boundary: 'security-sensitive or incident fixes may limit public detail but still need an appropriate review record',
    tradeoff: 'Smaller focused pull requests increase throughput and confidence but may require deliberate sequencing across dependencies',
    verification: 'Have a reviewer follow the description to reproduce the change and its checks without private context',
    outcome: 'Review time focuses on correctness and tradeoffs instead of discovering what the change is meant to do',
    misconception: 'A self-explanatory diff does not need a pull request description or verification record',
    operation: 'Connect rollout metrics, incidents, and follow-up work back to the reviewed change',
    review: 'Could a new maintainer understand why this changed, its risk, and how it was verified?',
  },
  {
    id: 'code-review',
    title: 'Code Review',
    questionTarget: 20,
    principle: 'Code review should prioritize correctness, contracts, security, operability, and maintainability according to risk',
    scenario: 'A reviewer comments on spacing but misses an unbounded retry loop around a non-idempotent payment call.',
    action: 'Review behavior and failure paths first, use automation for style, and explain the concrete risk of the retry loop',
    failure: 'Approval focuses on cosmetic consistency while hidden defects, assumptions, or missing tests remain',
    evidence: 'Trace inputs, state changes, boundaries, concurrency, failure recovery, tests, deployment, and observability',
    boundary: 'urgent fixes still require proportionate review of the highest-risk behavior and a follow-up path',
    tradeoff: 'Thorough review reduces escape risk but must stay focused and timely enough not to become batch approval theater',
    verification: 'Reproduce important behavior, run focused checks, and confirm comments are resolved in the final diff',
    outcome: 'A second engineer can challenge assumptions and improve the safety of a change before users depend on it',
    misconception: 'Code review quality is measured by the number of comments left on a pull request',
    operation: 'Use escaped defects and review latency to improve checklists and automation without blaming individuals',
    review: 'What is the highest-impact way this change could be wrong, and what evidence addresses it?',
  },
  {
    id: 'git-recovery',
    title: 'Restore, Reset, Revert & Reflog',
    questionTarget: 20,
    principle: 'Recovery commands differ by whether they change files, the index, references, or shared history',
    scenario: 'A bad commit is already on a shared production branch and must be undone without erasing subsequent history.',
    action: 'Create and verify a revert commit that applies the inverse change to shared history',
    failure: 'A broad reset or restore discards unrelated local work or rewrites history collaborators still reference',
    evidence: 'Determine whether the target change is working, staged, committed, published, and recoverable through reflog',
    boundary: 'merge commits, untracked files, expired reflogs, and later dependent commits need special handling',
    tradeoff: 'Revert preserves auditability and shared identity, while reset is concise for controlled local reference movement',
    verification: 'Inspect status, graph, and diff and rerun behavior checks after the recovery operation',
    outcome: 'Mistakes can be corrected at the right repository layer while preserving unrelated work and collaboration',
    misconception: 'reset, restore, and revert are interchangeable ways to undo any Git change',
    operation: 'Create a temporary reference before complex recovery and avoid destructive commands on an uncertain state',
    review: 'Is the change published, what other work depends on it, and which state must be preserved?',
  },
  {
    id: 'interactive-rebase',
    title: 'Interactive Rebase & Commit Cleanup',
    questionTarget: 12,
    principle: 'Interactive rebase can reorganize unshared commits into a clearer review sequence by recreating their identities',
    scenario: 'A feature branch has fixup commits and misleading messages but has not been shared with another developer.',
    action: 'Use interactive rebase to squash corrections, reorder dependencies, and rewrite messages before review',
    failure: 'Cleanup rewrites commits already used by others or produces intermediate commits that no longer build',
    evidence: 'Inspect branch publication, upstream graph, commit dependency order, and the rebased diff',
    boundary: 'merge commits, signed commits, conflict repetition, and already reviewed commit IDs may make rewriting costly',
    tradeoff: 'A curated history improves comprehension but can erase useful chronology and creates new identities',
    verification: 'Compare the final tree to the pre-rebase tree and test the rewritten commit sequence',
    outcome: 'Reviewers see a coherent progression instead of incidental local correction history',
    misconception: 'Interactive rebase edits commits in place without changing their hashes',
    operation: 'Keep a backup reference until the rewritten branch and its checks are confirmed',
    review: 'Is every commit being rewritten private, and does the new sequence preserve complete behavior?',
  },
  {
    id: 'git-bisect',
    title: 'Regression Isolation with Bisect',
    questionTarget: 16,
    principle: 'Bisection finds the first bad revision efficiently when a reliable good-or-bad predicate exists',
    scenario: 'A latency regression appeared somewhere across hundreds of commits and manual inspection has not isolated it.',
    action: 'Identify known good and bad commits and automate a deterministic threshold check for each midpoint',
    failure: 'The search identifies the wrong commit because the test is flaky, the environment differs, or some revisions cannot be classified',
    evidence: 'Record tested commit, environment, predicate output, skipped revisions, and the final introducing diff',
    boundary: 'build-breaking commits, merge-heavy history, nondeterministic tests, and external service drift complicate binary classification',
    tradeoff: 'Bisect reduces the number of revisions tested but depends on setup cost and a trustworthy regression predicate',
    verification: 'Confirm the candidate commit is bad, its parent is good, and reverting or correcting its change removes the regression',
    outcome: 'A broad regression window becomes one evidence-backed introducing change with logarithmic search',
    misconception: 'git bisect diagnoses the root cause automatically once it names a commit',
    operation: 'Preserve the automated predicate as a regression test where practical',
    review: 'Can every tested revision be classified consistently under the same environment and input?',
  },
  {
    id: 'cherry-pick',
    title: 'Cherry-Pick & Selective Integration',
    questionTarget: 8,
    principle: 'Cherry-pick recreates selected changes on another parent and should be used with awareness of dependency and duplicate-history risk',
    scenario: 'A production fix commit depends on an earlier refactor that is not present on the release branch.',
    action: 'Identify the minimal dependency set or create a release-specific fix rather than applying the dependent commit blindly',
    failure: 'A selected commit does not build, duplicates an eventual merge, or omits behavior hidden in neighboring commits',
    evidence: 'Inspect the chosen patch, parent context, dependencies, target history, and equivalent existing changes',
    boundary: 'merge commits, conflict resolution, later full-branch integration, and reordered migrations affect the result',
    tradeoff: 'Selective integration can deliver an urgent fix quickly but creates parallel history and maintenance obligations',
    verification: 'Run release-branch tests and compare the intended fix behavior rather than relying on matching commit messages',
    outcome: 'A necessary isolated change reaches another line without unintentionally importing the whole branch',
    misconception: 'Cherry-picking preserves the original commit identity on the target branch',
    operation: 'Record the source commit and follow-up merge strategy in the release change',
    review: 'What does this commit depend on, and how will duplicate application be avoided later?',
  },
  {
    id: 'tags-releases',
    title: 'Tags, Releases & Semantic Versions',
    questionTarget: 8,
    principle: 'A release should identify immutable source and communicate compatibility impact through a documented versioning policy',
    scenario: 'A team moves an existing production tag to a different commit after artifacts have already been published.',
    action: 'Create a new corrected version and preserve the original tag and artifact provenance',
    failure: 'The same version name resolves to different source or consumers cannot infer breaking compatibility',
    evidence: 'Link tag object, commit, build provenance, changelog, artifact digest, and compatibility classification',
    boundary: 'pre-releases, reverted breaking changes, monorepos, and versioned APIs require an explicit policy',
    tradeoff: 'Immutable releases improve reproducibility but require publishing a new version for every correction',
    verification: 'Rebuild or attest artifacts from the tagged commit and test the claimed compatibility surface',
    outcome: 'Operators and consumers can identify exactly what runs and assess upgrade risk',
    misconception: 'A Git tag automatically guarantees that the referenced artifact is reproducible and trusted',
    operation: 'Protect release tags and retain provenance, checksums, notes, and rollback artifacts',
    review: 'Does this version accurately describe compatibility and resolve immutably to the released source?',
  },
  {
    id: 'repository-hygiene',
    title: 'Secrets, Ignore Rules & Repository Hygiene',
    questionTarget: 20,
    principle: 'Repositories should contain reviewable source and required metadata, never active secrets or local generated state',
    scenario: 'An API token is committed and then removed in a later commit while the repository remains accessible.',
    action: 'Revoke and rotate the token immediately, then assess history cleanup and exposure according to repository reach',
    failure: 'Credentials, private data, large artifacts, build output, or machine-specific configuration enter version history',
    evidence: 'Scan tracked content and history, secret usage logs, ignore rules, artifact size, and environment setup documentation',
    boundary: 'a secret remains compromised after deletion because prior commits, forks, caches, and clones retain it',
    tradeoff: 'Aggressive history rewriting can reduce exposure in controlled repositories but disrupts clones and never replaces rotation',
    verification: 'Run secret and artifact checks on the full diff and confirm clean setup from a fresh clone',
    outcome: 'The repository is safe to share with intended collaborators and reproducible without private machine state',
    misconception: 'Adding a leaked file to .gitignore removes it from existing Git history',
    operation: 'Run automated secret scanning and dependency or artifact policies before protected branches accept changes',
    review: 'Does this file belong in durable source history, and could any value grant access outside the repository?',
  },
  {
    id: 'continuous-integration',
    title: 'CI Checks & Branch Protection',
    questionTarget: 16,
    principle: 'Continuous integration should reproduce required quality gates on trusted inputs before changes enter protected history',
    scenario: 'A pull request passes local tests but fails after merge because CI used a different dependency graph and skipped the production build.',
    action: 'Lock dependencies and require types, tests, lint, and the real production build before merge',
    failure: 'Protected history receives changes that were never checked in a reproducible target-like environment',
    evidence: 'Inspect workflow triggers, dependency installation, cache keys, required checks, artifacts, permissions, and branch rules',
    boundary: 'forked contributions, stale approvals, skipped jobs, cache poisoning, and path filters can bypass intended gates',
    tradeoff: 'More gates improve confidence but add feedback time and maintenance, so checks should be risk-based and parallel where possible',
    verification: 'Create controlled failing changes for every required gate and confirm merge remains blocked',
    outcome: 'The shared branch represents changes that passed a consistent minimum evidence standard',
    misconception: 'A green CI badge proves the application has no defects',
    operation: 'Track queue time, flaky jobs, bypasses, permissions, and escaped failures to refine the pipeline',
    review: 'Can this change merge while a relevant check is absent, stale, skipped, or running against different inputs?',
  },
  {
    id: 'branching-strategies',
    title: 'Branching & Integration Strategies',
    questionTarget: 12,
    principle: 'A branching strategy should minimize divergence and match release cadence, review needs, and support obligations',
    scenario: 'Feature branches remain open for months and repeatedly conflict with a rapidly changing main branch.',
    action: 'Decompose work into small integrable slices and use flags or inactive paths for incomplete user-facing behavior',
    failure: 'Long-lived branches accumulate incompatible assumptions, delayed feedback, and risky batch integration',
    evidence: 'Measure branch age, change size, conflict rate, merge queue time, release cadence, and supported versions',
    boundary: 'regulated releases and maintained release lines may require controlled long-lived branches with backport policy',
    tradeoff: 'Frequent trunk integration reduces divergence but depends on strong automation and safe incomplete-feature controls',
    verification: 'Simulate urgent fixes and concurrent features and confirm the strategy gives an unambiguous integration path',
    outcome: 'Changes reach shared feedback quickly without sacrificing required release isolation',
    misconception: 'One branching model is optimal for every team and release process',
    operation: 'Review stale branches, merge queues, backport status, and flag cleanup as routine delivery health',
    review: 'How does this strategy limit divergence while supporting the actual deployment and maintenance model?',
  },
  {
    id: 'reproducible-development',
    title: 'Reproducible Builds & Dependency Locks',
    questionTarget: 12,
    principle: 'The same declared source and inputs should resolve to traceable dependencies and equivalent build output',
    scenario: 'Two clean machines install different transitive versions and only one produces a working application.',
    action: 'Commit the supported lockfile, use deterministic installation, and pin the runtime and build toolchain',
    failure: 'A build outcome depends on machine state, current registry resolution, undeclared tools, or mutable external artifacts',
    evidence: 'Compare runtime versions, lock resolution, environment variables, build commands, artifact hashes, and network inputs',
    boundary: 'native dependencies, timestamps, platform-specific binaries, and mutable container tags can still vary output',
    tradeoff: 'Pinning improves repeatability but requires a deliberate process to receive security and compatibility updates',
    verification: 'Build from fresh environments more than once and compare behavior, dependency graph, and artifact provenance',
    outcome: 'Developers and CI can recreate a release without depending on an undocumented workstation state',
    misconception: 'A package manifest with version ranges is enough to guarantee identical installations',
    operation: 'Automate lockfile integrity, dependency updates, provenance, and fresh-build checks',
    review: 'Which build input remains mutable, undeclared, or fetched without a verifiable identity?',
  },
  {
    id: 'release-management',
    title: 'Release Changes, Flags & Rollback',
    questionTarget: 12,
    principle: 'A release should limit exposure, preserve compatibility, emit useful signals, and have a tested path to stop or reverse impact',
    scenario: 'A new recommendation engine is enabled for every user with no flag, baseline metric, or rollback procedure.',
    action: 'Deploy inactive, enable for a small measured cohort, compare guardrails, and retain a fast disable path',
    failure: 'A bad change reaches the full population before detection or cannot be disabled without another risky deployment',
    evidence: 'Inspect artifact identity, rollout cohort, health metrics, feature state, schema compatibility, and rollback timing',
    boundary: 'irreversible data writes and external side effects may not be undone by rolling application code back',
    tradeoff: 'Progressive delivery reduces blast radius but adds flag lifecycle, monitoring, and mixed-state complexity',
    verification: 'Rehearse enable, disable, rollback, and forward-fix paths with old and new versions against the same data',
    outcome: 'Changes gain production evidence gradually while operators retain control over user impact',
    misconception: 'Rolling back application binaries automatically reverses every effect of a release',
    operation: 'Monitor guardrail metrics by cohort and assign owners and expiry dates to release flags',
    review: 'What detects harm, limits exposure, and restores service if code or data has already changed?',
  },
  {
    id: 'development-workflow',
    title: 'Work Decomposition & Definition of Done',
    questionTarget: 12,
    principle: 'Engineering work should be split into independently verifiable outcomes with explicit completion criteria',
    scenario: 'A task titled build billing has no acceptance cases, dependency notes, rollout plan, or observable finish condition.',
    action: 'Clarify the user outcome and constraints, then sequence small vertical changes with acceptance and operational checks',
    failure: 'Work appears nearly complete for long periods, hidden dependencies surface late, or implementation passes without solving the need',
    evidence: 'Inspect acceptance criteria, dependency map, risk, working increments, test evidence, documentation, and release state',
    boundary: 'research spikes should time-box uncertainty and produce a decision or evidence rather than pretend to be delivery',
    tradeoff: 'Smaller slices improve feedback and predictability but require careful interfaces to avoid temporary incoherent states',
    verification: 'Demonstrate each acceptance criterion in a representative environment and confirm operational ownership',
    outcome: 'Stakeholders and engineers share an observable standard for progress and completion',
    misconception: 'Work is done when the main code path compiles on the author workstation',
    operation: 'Compare planned and completed outcomes, escaped follow-up work, and cycle time to improve future decomposition',
    review: 'What user-visible or system outcome proves this slice is complete and safe to operate?',
  },
] satisfies readonly SoftwareMasteryTopicBlueprint[]

export const gitDevelopmentMasteryTopics = defineSoftwareMasteryTopics(
  'git-software-development',
  gitDevelopmentBlueprints,
)