import {
  defineSoftwareMasteryTopics,
  type SoftwareMasteryTopicBlueprint,
} from './software-core-mastery-builder'

const engineeringFundamentalsBlueprints = [
  {
    id: 'requirements-acceptance',
    title: 'Requirements & Acceptance Criteria',
    questionTarget: 20,
    principle: 'A requirement should describe an observable outcome, constraints, and acceptance boundaries without prematurely dictating implementation',
    scenario: 'A ticket says make search fast but defines no users, workload, percentile, data size, or acceptable result behavior.',
    action: 'Clarify the user goal and specify representative load, correctness, latency target, and excluded cases',
    failure: 'Implementation appears complete while stakeholders and engineers apply different definitions of success',
    evidence: 'Inspect user need, examples, edge cases, constraints, acceptance tests, performance target, and unresolved decisions',
    boundary: 'conflicting stakeholder goals and unknown feasibility should be surfaced as explicit tradeoffs or discovery work',
    tradeoff: 'Detailed acceptance reduces ambiguity but excessive prescription can block simpler valid designs',
    verification: 'Demonstrate each criterion with representative inputs and confirm the outcome with the responsible stakeholder',
    outcome: 'The team can distinguish done from incomplete using shared observable evidence',
    misconception: 'A technically detailed implementation task is automatically a clear product requirement',
    operation: 'Connect acceptance criteria to release checks and revise them when validated assumptions change',
    review: 'Who receives value, what observable result is required, and which boundary remains ambiguous?',
  },
  {
    id: 'problem-decomposition',
    title: 'Problem Decomposition & Scope',
    questionTarget: 20,
    principle: 'Complex work should be decomposed into coherent, independently verifiable slices that retire the largest uncertainty early',
    scenario: 'A six-month platform rewrite has no usable intermediate outcome and postpones integration until the final milestone.',
    action: 'Identify the riskiest assumption and deliver a thin end-to-end slice through the real boundaries first',
    failure: 'Components look locally complete but cannot integrate, or hidden dependencies surface only near delivery',
    evidence: 'Map outcomes, dependencies, unknowns, integration points, reversible decisions, and evidence produced by each slice',
    boundary: 'foundational work may precede user-visible value but still needs a concrete consumer and validation condition',
    tradeoff: 'Vertical slices expose integration early but can involve temporary duplication or narrower initial capability',
    verification: 'Run each slice through its real input and output boundary before starting a larger dependent batch',
    outcome: 'Progress produces usable evidence and limits the amount of unintegrated work at risk',
    misconception: 'Decomposition means assigning each architecture layer to a separate team and integrating later',
    operation: 'Track blocked dependencies, aging work, and assumptions retired by completed slices',
    review: 'Does this slice produce an independently testable outcome and reduce a material uncertainty?',
  },
  {
    id: 'tradeoff-decisions',
    title: 'Tradeoff Analysis & Decisions',
    questionTarget: 20,
    principle: 'An engineering decision should compare viable options against explicit requirements, risks, and reversibility',
    scenario: 'A team selects a distributed event platform because it is industry standard without measuring its need or operating cost.',
    action: 'Define decision criteria, compare simpler alternatives, test the uncertain constraint, and record why the choice fits now',
    failure: 'Technology preference substitutes for evidence and the system inherits complexity unrelated to its workload',
    evidence: 'Document options, constraints, measurements, failure modes, cost, team capability, reversibility, and review trigger',
    boundary: 'an irreversible or high-blast-radius choice needs stronger evidence than an inexpensive replaceable decision',
    tradeoff: 'More analysis lowers uncertainty but delays learning from implementation, so depth should match decision cost',
    verification: 'Test the assumption most likely to reverse the ranking of options and revisit when its threshold changes',
    outcome: 'The chosen design is defensible under current constraints and can be reevaluated when evidence changes',
    misconception: 'A best-practice technology is the correct choice independent of context',
    operation: 'Keep architectural decisions linked to current metrics, owners, and explicit reconsideration conditions',
    review: 'Which requirement differentiates the options, and what new evidence would change the decision?',
  },
  {
    id: 'system-boundaries',
    title: 'System Boundaries & Dependency Direction',
    questionTarget: 16,
    principle: 'System boundaries should align ownership and change while dependencies point toward stable domain contracts',
    scenario: 'Business rules import framework request objects and database records directly, making every interface change cross the system.',
    action: 'Define domain-facing inputs and ports and keep framework and persistence translation at the boundary',
    failure: 'A small external change propagates through unrelated logic or separate owners must coordinate every release',
    evidence: 'Inspect dependency graph, change history, data ownership, contracts, cycles, deployment coupling, and team responsibility',
    boundary: 'an abstraction that has only one stable implementation may add ceremony without reducing meaningful coupling',
    tradeoff: 'Clear boundaries improve replaceability and testing but add translation and can duplicate representations',
    verification: 'Change or substitute one external adapter and confirm core behavior and neighboring modules remain stable',
    outcome: 'Volatile infrastructure changes remain localized and domain behavior retains a clear owner',
    misconception: 'More interfaces and services always create better separation of concerns',
    operation: 'Watch cross-boundary change frequency, cyclic dependencies, and coordinated deployment requirements',
    review: 'Which concept owns this rule, and does the dependency direction protect it from volatile details?',
  },
  {
    id: 'scalability-bottlenecks',
    title: 'Scalability & Bottleneck Analysis',
    questionTarget: 16,
    principle: 'Scalability work should identify the resource that saturates as workload grows and change that limiting relationship',
    scenario: 'A team adds application instances while all requests still contend on one serialized database lock.',
    action: 'Measure queueing and utilization across the path and address the serialized database section first',
    failure: 'More capacity is added to a nonlimiting tier while latency and throughput remain bounded elsewhere',
    evidence: 'Collect workload shape, throughput, latency distribution, utilization, queues, contention, and per-resource limits',
    boundary: 'hot keys and uneven tenants can saturate one partition while global averages remain healthy',
    tradeoff: 'Horizontal distribution adds capacity but introduces coordination, consistency, and operational complexity',
    verification: 'Load test through and beyond the target rate and confirm the expected bottleneck moves or gains headroom',
    outcome: 'The system meets growth targets with known limits and proportionate architecture',
    misconception: 'Horizontal scaling of stateless servers removes every system bottleneck',
    operation: 'Track saturation and queue depth by resource and key distribution, not only average CPU',
    review: 'Which finite resource limits throughput now, and what evidence shows the proposed change affects it?',
  },
  {
    id: 'performance-capacity',
    title: 'Performance Budgets & Capacity',
    questionTarget: 16,
    principle: 'Performance requires explicit user-facing budgets translated into component limits and tested under representative load',
    scenario: 'Each service meets its own average latency target but the composed request misses the user response objective.',
    action: 'Allocate an end-to-end percentile budget across calls, queueing, retries, and client work with reserved headroom',
    failure: 'Local averages hide tail amplification and the system has no capacity margin for traffic or dependency variance',
    evidence: 'Inspect p50 through tail latency, concurrency, service demand, queue time, fan-out, retry rate, and forecast growth',
    boundary: 'cold starts, burst traffic, cache misses, and dependency degradation require scenarios beyond steady averages',
    tradeoff: 'More headroom improves resilience but increases cost, while tight utilization increases queueing risk',
    verification: 'Run realistic burst and steady workloads at target data size and confirm every budget plus correctness',
    outcome: 'Capacity and latency are managed against explicit limits before users discover saturation',
    misconception: 'Low average latency proves the service meets a high-percentile user objective',
    operation: 'Forecast headroom and alert on budget consumption, queue growth, and tail latency',
    review: 'How does each component consume the end-to-end budget under peak and degraded conditions?',
  },
  {
    id: 'reliability-degradation',
    title: 'Reliability & Graceful Degradation',
    questionTarget: 20,
    principle: 'Reliable systems preserve critical outcomes and bound failure when dependencies slow, reject, or disappear',
    scenario: 'A recommendation dependency outage causes checkout to fail even though recommendations are optional.',
    action: 'Apply a short timeout, isolate dependency resources, omit recommendations, and keep checkout available',
    failure: 'A noncritical dependency consumes shared resources and turns a partial failure into a complete outage',
    evidence: 'Map critical paths, dependency failure modes, time budgets, shared pools, fallback correctness, and recovery behavior',
    boundary: 'a fallback that returns stale or partial data must not violate financial, authorization, or safety invariants',
    tradeoff: 'Redundancy and isolation improve availability but add cost, state coordination, and operational testing',
    verification: 'Inject latency, errors, and unavailability and confirm critical outcomes and recovery objectives',
    outcome: 'The system loses optional capability predictably instead of cascading into broad failure',
    misconception: 'Retries make a system reliable regardless of dependency state and operation semantics',
    operation: 'Monitor dependency budgets, fallback use, saturation, error amplification, and recovery time',
    review: 'Which capability is truly critical, and how is its resource path isolated from optional failures?',
  },
  {
    id: 'distributed-semantics',
    title: 'Distributed Consistency, Ordering & Delivery',
    questionTarget: 16,
    principle: 'Distributed workflows must state consistency, ordering, deduplication, and convergence guarantees instead of assuming one global transaction',
    scenario: 'An event is delivered twice and an account credit is applied twice because consumers assume exactly-once delivery.',
    action: 'Use a durable event identity and atomically record consumption with the credit transition',
    failure: 'Retries, reordering, delay, or partial completion create duplicate effects or permanently divergent state',
    evidence: 'Trace message identity, producer transaction, ordering key, attempts, consumer state, acknowledgment, and reconciliation',
    boundary: 'global order is often unavailable or unnecessary, while per-entity order may be both sufficient and achievable',
    tradeoff: 'Stronger coordination simplifies reads but increases latency, coupling, and reduced availability during partitions',
    verification: 'Inject duplicate, delayed, missing, and reordered messages and assert invariant and eventual convergence',
    outcome: 'The workflow remains correct under the delivery behaviors the infrastructure actually provides',
    misconception: 'A message broker generally guarantees that every business effect occurs exactly once',
    operation: 'Track lag, duplicates, dead letters, reconciliation differences, and age of inconsistent state',
    review: 'Which invariant needs immediate consistency, which can converge, and how are retries made safe?',
  },
  {
    id: 'security-threat-modeling',
    title: 'Security & Threat Modeling',
    questionTarget: 20,
    principle: 'Security design starts from assets, trust boundaries, attacker capabilities, abuse cases, and proportionate controls',
    scenario: 'An internal export endpoint trusts a tenant ID from the request and returns another customer’s data.',
    action: 'Authorize the requested resource against the authenticated principal at the data-access boundary',
    failure: 'A valid identity crosses a trust boundary and performs an action or reads data it is not authorized to access',
    evidence: 'Map assets, identities, data flows, trust transitions, entry points, privileges, abuse scenarios, controls, and logs',
    boundary: 'administrative support, background jobs, and service identities need explicit scoping rather than implicit trust',
    tradeoff: 'Defense in depth adds checks and operational work but reduces reliance on one perfect perimeter',
    verification: 'Test cross-tenant, privilege escalation, replay, injection, and denied-path behavior from each entry point',
    outcome: 'High-impact abuse paths are identified early and guarded by testable least-privilege controls',
    misconception: 'Authentication proves a caller may access every resource named in its request',
    operation: 'Monitor denied actions, privilege changes, anomalous access, secret use, and control failures',
    review: 'What asset crosses which trust boundary, and how could a legitimate or malicious caller abuse that path?',
  },
  {
    id: 'privacy-data-lifecycle',
    title: 'Privacy & Data Lifecycle',
    questionTarget: 12,
    principle: 'Systems should collect the minimum necessary personal data and govern purpose, access, retention, deletion, and derived copies',
    scenario: 'A deleted profile disappears from the primary table but remains indefinitely in exports, logs, search, and analytics.',
    action: 'Map every copy and propagate a verifiable deletion or approved retention policy across downstream systems',
    failure: 'Data outlives its purpose, is exposed to excessive readers, or cannot be found and removed when required',
    evidence: 'Inventory fields, purpose, consent or basis, owners, access, transfers, retention, backups, and deletion propagation',
    boundary: 'legal retention and fraud prevention may require restricted preservation rather than immediate physical deletion',
    tradeoff: 'Additional data can improve products and diagnosis but increases breach impact, obligations, and user risk',
    verification: 'Trace one synthetic subject through collection, export, retention, deletion, backup, and downstream confirmation',
    outcome: 'Personal data remains purposeful, discoverable, access-controlled, and removable according to policy',
    misconception: 'Deleting the primary database row completes every privacy deletion request',
    operation: 'Audit retention jobs, access logs, deletion backlog, and unclassified new data flows',
    review: 'Why is this data needed, where does every copy go, and when and how is it removed?',
  },
  {
    id: 'service-objectives',
    title: 'Observability, SLIs & SLOs',
    questionTarget: 20,
    principle: 'Service objectives should measure user-relevant successful outcomes and guide risk, alerting, and reliability investment',
    scenario: 'A server reports 99.99 percent uptime while users receive invalid responses from a broken dependency.',
    action: 'Define a success indicator at the user boundary including correctness and latency, then set an objective and error budget',
    failure: 'Teams optimize healthy infrastructure signals that do not reflect whether users can complete important work',
    evidence: 'Inspect critical journeys, valid events, total events, latency threshold, measurement point, exclusions, and budget policy',
    boundary: 'low-volume services and long-window batch outcomes need indicators that remain statistically and operationally useful',
    tradeoff: 'Tighter objectives improve reliability pressure but increase cost and reduce room for product change',
    verification: 'Replay known user failures and confirm the indicator, alert, and budget all reflect the impact',
    outcome: 'Reliability decisions use a shared quantitative measure of delivered user value',
    misconception: 'Machine CPU and process uptime are sufficient service-level indicators for every product',
    operation: 'Review budget burn at multiple windows and connect policy to rollout and reliability work',
    review: 'Does the indicator count the outcome users care about at the boundary where they experience it?',
  },
  {
    id: 'release-engineering',
    title: 'Releases, Feature Flags & Rollbacks',
    questionTarget: 16,
    principle: 'Releases should separate deployment from exposure, preserve mixed-version compatibility, and include a tested recovery path',
    scenario: 'A new schema and application are released together, and rolling code back fails because old code cannot read the migrated data.',
    action: 'Use an expand-compatible migration, deploy compatible code, shift exposure gradually, and contract later',
    failure: 'A release is all-or-nothing, hard to observe, or irreversible after data and external effects change',
    evidence: 'Review artifact identity, dependency compatibility, cohort, flags, migrations, guardrails, and rollback or forward-fix steps',
    boundary: 'flags that alter writes need state compatibility and cleanup, not only a UI off switch',
    tradeoff: 'Progressive delivery reduces blast radius but creates temporary mixed states and flag maintenance',
    verification: 'Rehearse old and new versions together plus enable, disable, rollback, and recovery under production-like data',
    outcome: 'Operators can control exposure and recover without coupling every change to one irreversible moment',
    misconception: 'A feature flag automatically makes any database or side-effect change safe to roll back',
    operation: 'Track rollout health by cohort and enforce owners, purpose, and expiry for every temporary flag',
    review: 'What state survives a disable or rollback, and can every running version interpret it safely?',
  },
  {
    id: 'configuration-environments',
    title: 'Configuration, Environments & Secrets',
    questionTarget: 16,
    principle: 'Configuration should be validated, traceable, environment-specific, and separated from code and secret material',
    scenario: 'A production process starts with a misspelled variable and silently uses an unsafe development default.',
    action: 'Validate typed required configuration at startup and reject missing or invalid production values',
    failure: 'Behavior depends on undocumented defaults, stale process state, leaked credentials, or configuration that cannot be traced',
    evidence: 'Inspect schema, source and precedence, safe fingerprint, secret store, rotation, deployment binding, and startup output',
    boundary: 'dynamic configuration changes need versioning and rollback because instances may observe different values temporarily',
    tradeoff: 'Centralized dynamic configuration enables fast control but adds dependency and mixed-state risk',
    verification: 'Test absent, malformed, rotated, stale, and conflicting values in each deployment class',
    outcome: 'Every runtime starts with intentional validated inputs without embedding credentials in source or artifacts',
    misconception: 'Environment variables are inherently secure because they are not committed to source',
    operation: 'Audit access, rotation, configuration drift, failed validation, and version adoption',
    review: 'Where does this effective value originate, who can change it, and how does the system reject an unsafe value?',
  },
  {
    id: 'system-evolution',
    title: 'Backward Compatibility & System Evolution',
    questionTarget: 16,
    principle: 'Systems evolve safely when producers and consumers tolerate planned overlap and incompatible removal follows measured adoption',
    scenario: 'An API replaces a field and removes the old one while mobile clients with long upgrade cycles still require it.',
    action: 'Add the new field, support both meanings, measure client adoption, communicate deprecation, then remove deliberately',
    failure: 'Independently released components disagree during rollout or old data can no longer be interpreted',
    evidence: 'Inventory consumers, versions, contract use, stored data, rollout order, deprecation signals, and migration progress',
    boundary: 'security vulnerabilities may require accelerated breaking change with explicit user communication and fallback planning',
    tradeoff: 'Compatibility enables independent evolution but retains temporary complexity and constrains interface cleanup',
    verification: 'Run old and new producers and consumers in every supported combination against representative data',
    outcome: 'Interfaces and data models change without requiring impossible synchronized deployment',
    misconception: 'Adding a field is always backward compatible regardless of validation and consumer behavior',
    operation: 'Measure use of deprecated contracts and assign deadlines and owners for removal',
    review: 'Which older component or stored record encounters this change, and how does it interpret it?',
  },
  {
    id: 'technical-communication',
    title: 'Documentation, Runbooks & Technical Communication',
    questionTarget: 16,
    principle: 'Technical communication should help a defined audience make a decision or perform a task with current verifiable information',
    scenario: 'A setup guide lists commands but omits prerequisites, expected output, failure recovery, and supported versions.',
    action: 'State audience and goal, add prerequisites and verification, and test the guide from a clean environment',
    failure: 'Documentation is technically present but readers cannot act safely or distinguish current truth from stale assumptions',
    evidence: 'Inspect owner, audience, last validation, version scope, examples, decision rationale, and links to executable sources',
    boundary: 'sensitive operational detail needs controlled access rather than omission from all responder guidance',
    tradeoff: 'Comprehensive prose ages quickly, while concise docs linked to automation are easier to verify and maintain',
    verification: 'Have an intended reader complete the task or decision without private author context',
    outcome: 'Knowledge becomes repeatable team capability rather than memory held by one engineer',
    misconception: 'Documentation is complete when it accurately describes the code at the time it was written',
    operation: 'Assign owners and validate critical documents during releases, incidents, and architecture changes',
    review: 'What must the reader decide or do, and how can they verify success or stop safely?',
  },
  {
    id: 'estimation-risk',
    title: 'Estimation, Uncertainty & Risk',
    questionTarget: 16,
    principle: 'Engineering estimates should expose uncertainty, assumptions, dependencies, and ranges rather than present false precision',
    scenario: 'A team commits to ten days before investigating an unfamiliar provider integration and migration path.',
    action: 'Separate known implementation from discovery, identify assumptions, run a bounded spike, and provide a range with confidence',
    failure: 'A single date hides unresolved work and turns new information into surprise rather than updated planning',
    evidence: 'List scope, comparable work, unknowns, dependencies, risks, confidence, range, and conditions that trigger re-estimation',
    boundary: 'high uncertainty may call for limiting exposure or sequencing a decision rather than estimating the full project',
    tradeoff: 'Discovery delays a commitment but can prevent much larger planning error and sunk implementation',
    verification: 'Compare forecast ranges and assumptions with completed outcomes and calibrate future estimates',
    outcome: 'Stakeholders can make risk-aware scope and sequencing decisions with honest uncertainty',
    misconception: 'A senior engineer should be able to give one accurate delivery date before investigating unknown dependencies',
    operation: 'Track estimate calibration and recurring sources of variance without using estimates as individual performance scores',
    review: 'Which assumption dominates the range, and what is the cheapest evidence that would narrow it?',
  },
  {
    id: 'operational-ownership',
    title: 'Ownership, Operations & Feedback',
    questionTarget: 16,
    principle: 'Teams that build a service should receive production feedback and own its reliability, maintenance, and lifecycle decisions',
    scenario: 'A feature launches without an on-call owner, dashboard, support path, or plan for failed background jobs.',
    action: 'Assign service ownership and define indicators, alerts, runbooks, escalation, maintenance, and user feedback before broad release',
    failure: 'Operational problems fall between teams and recurring toil never influences product or design priorities',
    evidence: 'Inspect ownership map, alerts, runbooks, support signals, toil, incidents, dependency contacts, and maintenance backlog',
    boundary: 'shared platforms need clear responsibility split between platform guarantees and consuming-team configuration',
    tradeoff: 'End-to-end ownership improves feedback but requires capacity allocation and guardrails against constant interruption',
    verification: 'Run a failure exercise and confirm the alert reaches an empowered owner with a safe response path',
    outcome: 'Production evidence continuously improves design and users have a clear route when behavior fails',
    misconception: 'Operational ownership begins only after a separate operations team receives the deployment',
    operation: 'Review alert quality, toil, incident actions, dependency health, and ownership gaps routinely',
    review: 'Who can detect, decide, and act when this capability degrades outside business hours?',
  },
  {
    id: 'cost-build-buy',
    title: 'Cost, Resource Efficiency & Build-vs-Buy',
    questionTarget: 12,
    principle: 'Engineering cost includes development, operation, risk, switching, and resource use across the expected lifecycle',
    scenario: 'A team builds a custom queue to avoid subscription fees without estimating reliability work or on-call burden.',
    action: 'Compare total lifecycle cost and differentiating requirements with managed and simpler existing options',
    failure: 'A low initial price produces higher ongoing labor, idle capacity, lock-in, or reliability risk',
    evidence: 'Model workload units, pricing, utilization, engineering time, operations, compliance, failure cost, and exit path',
    boundary: 'strategic differentiation or unusual regulation can justify ownership even when direct cost is higher',
    tradeoff: 'Buying accelerates delivery and transfers some operation, while building offers control at permanent maintenance cost',
    verification: 'Run a representative proof and sensitivity analysis for the assumptions that dominate total cost',
    outcome: 'Resource and sourcing choices support product value without hiding long-term engineering obligations',
    misconception: 'Open-source or internally built software has no material acquisition cost',
    operation: 'Track unit cost, idle resources, vendor growth, support effort, and forecast thresholds',
    review: 'Which requirement is truly differentiating, and what is the full cost of owning this capability?',
  },
  {
    id: 'accessibility-ethics',
    title: 'Accessibility & Ethical Boundary Cases',
    questionTarget: 8,
    principle: 'Engineering quality includes equitable access and deliberate consideration of users harmed by assumptions, defaults, or automated decisions',
    scenario: 'A hiring tool rejects candidates when a camera-based check cannot recognize some disabilities and skin tones reliably.',
    action: 'Provide an accessible alternative, test performance across affected groups, and require human review for consequential uncertainty',
    failure: 'A system technically functions for an average path while excluding users or scaling an unjustified proxy decision',
    evidence: 'Evaluate user groups, assistive paths, error distribution, data provenance, decision impact, appeal, and human oversight',
    boundary: 'a statistically accurate model can still be inappropriate when errors create severe or unequal consequences',
    tradeoff: 'Inclusive alternatives and review add delivery cost but reduce exclusion, legal exposure, and irreversible user harm',
    verification: 'Test with assistive technology and representative affected users, including failure and appeal paths',
    outcome: 'The product remains usable and contestable across real human variation and high-impact edge cases',
    misconception: 'Passing the average automated accuracy target proves a consequential feature is fair and accessible',
    operation: 'Monitor accessibility failures, outcome disparities, complaints, overrides, and unresolved appeals',
    review: 'Who may be excluded or harmed when this assumption fails, and what safe alternative exists?',
  },
  {
    id: 'reviewable-changes',
    title: 'Reviewable Change Design',
    questionTarget: 16,
    principle: 'A change should be shaped so another engineer can understand intent, isolate risk, verify behavior, and reverse it if needed',
    scenario: 'A pull request combines framework upgrade, behavior change, formatting, migration, and cleanup across hundreds of files.',
    action: 'Sequence mechanical preparation, compatible migration, focused behavior, and cleanup into evidence-backed changes',
    failure: 'Reviewers cannot distinguish semantic changes or identify which part caused a regression',
    evidence: 'Inspect scope, diff noise, commit sequence, contract changes, tests, migration, rollout, and rollback',
    boundary: 'an urgent security fix may be larger but still needs explicit risk hotspots and independent verification',
    tradeoff: 'Smaller changes reduce review and rollback risk but require temporary compatibility and sequencing discipline',
    verification: 'Have a reviewer explain the behavior delta and run the documented focused checks from the final diff',
    outcome: 'Change risk is visible and bounded enough for meaningful review and operational control',
    misconception: 'A large change is reviewable when every individual line is straightforward',
    operation: 'Measure review size, lead time, rollback rate, and escaped defects to improve change shaping',
    review: 'Can the semantic change be separated from mechanics, and what is the smallest independently safe unit?',
  },
] satisfies readonly SoftwareMasteryTopicBlueprint[]

export const engineeringFundamentalsMasteryTopics = defineSoftwareMasteryTopics(
  'engineering-fundamentals',
  engineeringFundamentalsBlueprints,
)