import {
  defineSoftwareMasteryTopics,
  type SoftwareMasteryTopicBlueprint,
} from './software-core-mastery-builder'

const apiBackendBlueprints = [
  {
    id: 'http-semantics',
    title: 'HTTP Semantics & Methods',
    questionTarget: 20,
    principle: 'HTTP methods communicate safety, idempotency, cache behavior, and the intent of an operation to clients and intermediaries',
    scenario: 'A GET endpoint charges a stored payment method whenever a crawler follows its URL.',
    action: 'Move the state-changing operation to POST and keep GET side-effect free',
    failure: 'A safe-looking request changes server state or an idempotent method creates a new effect on every retry',
    evidence: 'Compare the documented method contract with state changes observed across an initial request and a retry',
    boundary: 'a connection ends before the client learns whether the server completed the operation',
    tradeoff: 'Strict method semantics may require a more explicit resource model, but they make retries, caching, and automation safer',
    verification: 'Exercise each endpoint twice and assert that safe and idempotent methods preserve their promised effects',
    outcome: 'Clients and infrastructure can retry, prefetch, and cache requests without inventing hidden business effects',
    misconception: 'POST is for large payloads while GET is for small payloads',
    operation: 'Monitor method, route, status, latency, and resulting state changes together',
    review: 'Does the selected method match the operation semantics under retries and intermediary behavior?',
  },
  {
    id: 'status-error-contracts',
    title: 'Status Codes & Error Contracts',
    questionTarget: 16,
    principle: 'A response should classify success and failure precisely enough for a client to choose its next action',
    scenario: 'An API returns 200 with an error string when a submitted version conflicts with the current record.',
    action: 'Return a documented conflict status and a stable machine-readable error body',
    failure: 'Unrelated failures collapse into one status or clients must parse prose to decide whether to retry',
    evidence: 'Inspect status distributions, error codes, retry behavior, and representative response bodies',
    boundary: 'a request is syntactically valid but conflicts with current resource state',
    tradeoff: 'A richer error taxonomy improves client behavior but creates a compatibility contract that must remain stable',
    verification: 'Test success, validation, authorization, conflict, dependency, and unexpected failure responses separately',
    outcome: 'Clients can distinguish corrections, retries, conflicts, and server incidents without guessing',
    misconception: 'Every application failure should return 500 because the request did not succeed',
    operation: 'Aggregate failures by stable error code while retaining a correlation identifier for diagnosis',
    review: 'Can a client make a deterministic recovery decision from the status and error schema?',
  },
  {
    id: 'resource-modeling',
    title: 'Resource Modeling & URL Design',
    questionTarget: 12,
    principle: 'API resources should represent stable domain concepts and relationships rather than current user-interface actions',
    scenario: 'A team proposes endpoints named clickApproveButton and openCustomerScreen for a workflow API.',
    action: 'Model customers, approvals, and state transitions with stable nouns and explicit operations',
    failure: 'Routes mirror screen controls, expose storage tables directly, or require callers to coordinate domain invariants',
    evidence: 'Map routes to domain ownership, lifecycle, identifiers, and the actions callers actually need',
    boundary: 'an operation does not fit cleanly into create, read, update, or delete semantics',
    tradeoff: 'Resource-oriented contracts improve longevity but may use explicit action subresources for genuine domain commands',
    verification: 'Walk several client workflows through the contract without relying on private implementation details',
    outcome: 'The API can evolve its interface and persistence internals while preserving a coherent public model',
    misconception: 'A REST-style API must expose one endpoint for every database table and no domain operations',
    operation: 'Track route adoption and deprecate obsolete resource shapes with measured client usage',
    review: 'Will these resource names and transitions still make sense if the UI and database schema change?',
  },
  {
    id: 'validation-serialization',
    title: 'Validation, Parsing & Serialization',
    questionTarget: 20,
    principle: 'Untrusted wire data must be parsed and validated at the boundary before domain code relies on its shape or meaning',
    scenario: 'A typed handler assumes that a JSON amount is a finite non-negative number because its TypeScript parameter says number.',
    action: 'Validate the runtime payload, convert it once, and pass a trusted domain value inward',
    failure: 'Malformed, ambiguous, or lossy values reach business logic and fail after partial work has begun',
    evidence: 'Capture the raw payload, content type, parser result, validation errors, and serialized response',
    boundary: 'unknown fields, missing fields, numeric overflow, invalid dates, and structurally valid but impossible domain values occur',
    tradeoff: 'Strict validation rejects ambiguous clients earlier, while permissive coercion may ease migration but hides data defects',
    verification: 'Use table-driven tests for valid values, malformed syntax, wrong types, omitted fields, and domain limits',
    outcome: 'Internal code operates on explicit trusted values and failures occur before durable side effects',
    misconception: 'Static types validate JSON received over the network at runtime',
    operation: 'Measure validation failures by field and error code without logging sensitive payload contents',
    review: 'Where does untrusted data become a validated domain value, and can any path bypass that boundary?',
  },
  {
    id: 'auth-access-control',
    title: 'Authentication, Authorization & Tenant Isolation',
    questionTarget: 20,
    principle: 'Authentication establishes identity, while authorization checks the requested action and resource within the correct tenant boundary',
    scenario: 'A valid user can request another tenant record by changing the identifier in the URL.',
    action: 'Scope the resource lookup to the authenticated tenant and enforce the required permission server-side',
    failure: 'Possessing a valid token grants unintended actions or identifiers allow cross-tenant object access',
    evidence: 'Trace identity claims, resource ownership, policy decisions, and denied access for the exact request',
    boundary: 'an administrator, service identity, or shared resource legitimately crosses an ordinary tenant boundary',
    tradeoff: 'Central policies improve consistency, but resource-specific authorization still needs enough context to make the correct decision',
    verification: 'Test allowed and denied actions across owners, roles, tenants, missing claims, and revoked credentials',
    outcome: 'Every protected operation is permitted according to current identity, action, resource, and tenant context',
    misconception: 'A request is authorized once its token signature is valid',
    operation: 'Audit sensitive allow and deny decisions with actor, action, resource, tenant, and correlation context',
    review: 'Is authorization enforced on the server for this specific resource rather than inferred from the client route?',
  },
  {
    id: 'api-versioning',
    title: 'Versioning & Backward Compatibility',
    questionTarget: 16,
    principle: 'API evolution should preserve documented behavior for existing consumers or provide a deliberate migration path',
    scenario: 'A service renames a required response field while old mobile clients remain in use for months.',
    action: 'Add the new representation compatibly, measure adoption, and remove the old field only through a published deprecation',
    failure: 'A deployment breaks clients that were valid against the previous contract',
    evidence: 'Compare schemas, consumer usage, compatibility tests, and mixed-version traffic before release',
    boundary: 'old and new producers and consumers operate concurrently during a rolling migration',
    tradeoff: 'Compatibility adds temporary complexity, but abrupt cleanup transfers deployment control and failure risk to consumers',
    verification: 'Run consumer contracts against both the current and proposed provider implementation',
    outcome: 'Providers can improve the API without forcing synchronized releases across independent clients',
    misconception: 'Adding a new required field is backward compatible because existing fields did not change',
    operation: 'Record version or capability use and alert on traffic that still depends on a planned removal',
    review: 'Which existing requests and responses change meaning, and how will each consumer migrate?',
  },
  {
    id: 'pagination-filtering-sorting',
    title: 'Pagination, Filtering & Sorting',
    questionTarget: 16,
    principle: 'Collection APIs need bounded pages, deterministic ordering, and filters with explicit semantics',
    scenario: 'Offset pagination skips and duplicates events while new rows are inserted between page requests.',
    action: 'Use a stable unique ordering and an opaque cursor tied to the last observed position',
    failure: 'Clients see duplicate, missing, unbounded, or unpredictably ordered results',
    evidence: 'Replay adjacent page requests while inserting tied and out-of-order records between them',
    boundary: 'multiple records share the primary sort value or the referenced cursor row is deleted',
    tradeoff: 'Cursor pagination is stable and scalable for traversal, while offsets support arbitrary page jumps more easily',
    verification: 'Test first, middle, final, empty, changed-data, and equal-sort-key pages with strict limits',
    outcome: 'Clients traverse large changing collections predictably without loading them all at once',
    misconception: 'A LIMIT clause alone guarantees deterministic pagination',
    operation: 'Measure page sizes, scan cost, invalid cursors, and repeated traversal failures',
    review: 'Is the ordering total and stable, and are all filter combinations bounded and indexed appropriately?',
  },
  {
    id: 'idempotency',
    title: 'Idempotency & Duplicate Requests',
    questionTarget: 20,
    principle: 'Repeated delivery of one logical operation should not create additional effects when the contract promises idempotency',
    scenario: 'A payment client times out after submission and retries before learning whether the charge succeeded.',
    action: 'Accept a client operation key, atomically store its request identity and result, and return the original result on retry',
    failure: 'Retries create duplicate payments, orders, messages, or conflicting responses for one logical action',
    evidence: 'Correlate operation keys, durable writes, side effects, responses, and concurrent duplicate attempts',
    boundary: 'the same key arrives concurrently with a different payload or after its retention period expires',
    tradeoff: 'Durable deduplication consumes storage and coordination, but it makes uncertain network retries safe',
    verification: 'Send identical and conflicting duplicates sequentially and concurrently while injecting failures around commit boundaries',
    outcome: 'Clients can recover from ambiguous network outcomes without multiplying business effects',
    misconception: 'Using POST means a request cannot or should not be made idempotent',
    operation: 'Track duplicate-key hits, conflicts, retention expiry, and downstream side-effect identifiers',
    review: 'What identifies one logical operation, and is deduplication atomic with the effect it protects?',
  },
  {
    id: 'retry-policies',
    title: 'Timeouts, Retries, Backoff & Jitter',
    questionTarget: 20,
    principle: 'Retries should target transient failures, respect an end-to-end deadline, and avoid synchronizing load on a struggling dependency',
    scenario: 'Hundreds of workers immediately retry a timed-out dependency three times and amplify an outage.',
    action: 'Set bounded timeouts, retry only safe transient failures, and use exponential backoff with jitter within a total budget',
    failure: 'A retry storm increases saturation, duplicates effects, or keeps work alive beyond the caller deadline',
    evidence: 'Inspect attempt counts, per-attempt latency, final outcomes, dependency saturation, and remaining deadline',
    boundary: 'the original attempt may have succeeded even though its response was lost',
    tradeoff: 'Retries can mask brief faults but add load, latency, and duplicate risk during sustained failures',
    verification: 'Inject transient, permanent, slow, and ambiguous failures and assert bounded attempts and total duration',
    outcome: 'Brief dependency faults recover without turning into unbounded latency or cascading overload',
    misconception: 'More retries always make a distributed operation more reliable',
    operation: 'Publish attempt, exhaustion, timeout, and recovered-request metrics by dependency and operation',
    review: 'Which failures are retryable, is the operation safe to repeat, and what is the complete deadline budget?',
  },
  {
    id: 'resilience-patterns',
    title: 'Circuit Breakers & Bulkheads',
    questionTarget: 8,
    principle: 'Resilience boundaries stop repeated failing work and prevent one dependency from consuming every shared resource',
    scenario: 'A slow optional vendor API exhausts the shared connection pool and blocks unrelated checkout requests.',
    action: 'Give the dependency a bounded resource pool and open a circuit after a measured failure threshold',
    failure: 'One degraded dependency consumes all workers, sockets, or queues and spreads failure across the service',
    evidence: 'Compare dependency failure rate, circuit state, pool saturation, rejected work, and unrelated request latency',
    boundary: 'a half-open probe must determine whether recovery is real without releasing a new traffic surge',
    tradeoff: 'Failing fast protects capacity but may reject requests that could have succeeded during a brief fluctuation',
    verification: 'Drive the dependency through closed, open, and half-open states while checking isolation of other work',
    outcome: 'Partial dependency failure remains contained and the service preserves capacity for healthy paths',
    misconception: 'A circuit breaker retries every failed request until the dependency recovers',
    operation: 'Alert on circuit transitions, sustained rejection, and bulkhead saturation with dependency labels',
    review: 'Are thresholds, recovery probes, fallbacks, and resource pools defined from measured behavior?',
  },
  {
    id: 'rate-limiting',
    title: 'Rate Limiting & Backpressure',
    questionTarget: 16,
    principle: 'Admission control should protect finite capacity fairly and tell callers when work cannot be accepted',
    scenario: 'One API key sends a burst that fills a global queue and delays every other tenant.',
    action: 'Apply a documented per-principal limiter and bound the downstream queue with explicit rejection or slowdown',
    failure: 'Queues grow without limit, one caller monopolizes capacity, or overload appears only as timeouts',
    evidence: 'Measure arrival rate, accepted and rejected work, queue depth, service time, and principal distribution',
    boundary: 'legitimate bursts, distributed limiter state, clock skew, and retries after a 429 response occur',
    tradeoff: 'Stricter limits protect latency and fairness but can reject useful bursts unless capacity and burst allowance are chosen deliberately',
    verification: 'Generate steady, bursty, and multi-tenant load and assert limits, fairness, headers, and recovery',
    outcome: 'The service remains responsive under overload and callers receive predictable admission behavior',
    misconception: 'Rate limiting increases service capacity by making requests execute faster',
    operation: 'Monitor saturation, queue delay, limiter decisions, and top constrained principals',
    review: 'What resource is protected, who is limited, and how does the client know when to retry?',
  },
  {
    id: 'http-caching',
    title: 'Caching & Conditional Requests',
    questionTarget: 16,
    principle: 'A cache is correct only when freshness, identity, invalidation, and authorization semantics are explicit',
    scenario: 'A shared cache serves one authenticated customer response to another customer.',
    action: 'Define a safe cache key and scope, set explicit freshness, and use validators such as ETag where appropriate',
    failure: 'Clients receive stale, cross-user, or invalid data because the key or invalidation model omits a dependency',
    evidence: 'Inspect cache keys, hit source, age, validators, invalidations, and the authorization context of responses',
    boundary: 'content varies by identity, locale, encoding, feature flag, or a concurrent update',
    tradeoff: 'Longer caching lowers latency and origin load while increasing staleness and invalidation complexity',
    verification: 'Test hits, misses, expiry, conditional requests, updates, and isolation across every varying dimension',
    outcome: 'Repeated reads become cheaper without violating freshness or data-isolation guarantees',
    misconception: 'Caching a GET response is safe whenever the status is 200',
    operation: 'Track hit ratio, age, revalidation, invalidation lag, and origin load without hiding correctness failures',
    review: 'What exact dimensions form the key, and what event makes a cached representation no longer valid?',
  },
  {
    id: 'webhooks',
    title: 'Webhooks & Delivery Guarantees',
    questionTarget: 12,
    principle: 'Webhook delivery should be authenticated, retryable, observable, and safe for receivers to process more than once',
    scenario: 'A receiver performs the side effect but times out before acknowledging the webhook.',
    action: 'Retry with the same event identifier, sign the request, and require idempotent receiver processing',
    failure: 'Events are forged, silently lost, duplicated into extra effects, or delivered with no diagnosable history',
    evidence: 'Follow event creation, durable enqueue, signature, attempts, acknowledgements, and receiver result by event ID',
    boundary: 'events arrive more than once, out of order, after secret rotation, or after the receiver was unavailable for hours',
    tradeoff: 'At-least-once delivery avoids silent loss but requires deduplication and careful ordering semantics',
    verification: 'Test valid and invalid signatures, duplicate and reordered events, retry schedules, and terminal failure handling',
    outcome: 'Integrations can recover from network failure without trusting or applying the same event blindly',
    misconception: 'A successful TCP connection proves that the receiver durably processed the event',
    operation: 'Expose attempt history, next retry, terminal status, and replay controls for each event',
    review: 'How are authenticity, duplicate delivery, ordering, secret rotation, and dead-letter recovery handled?',
  },
  {
    id: 'concurrent-updates',
    title: 'Concurrent Updates & Optimistic Control',
    questionTarget: 16,
    principle: 'A write based on previously read state must detect whether that state changed before the write commits',
    scenario: 'Two editors load version 4, make different changes, and the second save silently overwrites the first.',
    action: 'Include the expected version in the conditional update and return a conflict when it no longer matches',
    failure: 'Concurrent valid requests produce lost updates, impossible transitions, or last-writer-wins data loss',
    evidence: 'Trace read versions, write predicates, affected-row counts, commit order, and conflict responses',
    boundary: 'two updates touch disjoint fields, a retry uses stale state, or conflict resolution itself changes data',
    tradeoff: 'Optimistic control avoids long locks under low contention but shifts conflict handling to callers',
    verification: 'Run controlled interleavings from the same version and assert one commit plus an explicit conflict',
    outcome: 'Concurrent edits cannot silently erase accepted work based on newer state',
    misconception: 'A database transaction automatically prevents every lost update at any isolation level',
    operation: 'Measure conflict rates and repeated retries to detect contention or poor edit boundaries',
    review: 'What proves that the state used to make this decision is still current at commit time?',
  },
  {
    id: 'service-transactions',
    title: 'Transaction Boundaries & Partial Failure',
    questionTarget: 16,
    principle: 'Related state changes need an explicit atomic or recoverable boundary that matches the business invariant',
    scenario: 'An order commits locally, then publishing its fulfillment event fails before the request returns.',
    action: 'Commit the order and an outbox record atomically, then deliver the event from the durable outbox',
    failure: 'A multi-step operation leaves durable state that claims success while a required side effect is missing',
    evidence: 'Trace each durable commit, external call, retry record, compensation, and visible business state',
    boundary: 'a process stops between local commit and external delivery or compensation also fails',
    tradeoff: 'Local atomicity is simple within one store, while cross-system consistency requires delayed delivery, compensation, or reconciliation',
    verification: 'Inject failure before and after every commit boundary and assert a valid recoverable state',
    outcome: 'Partial failure is represented explicitly and eventually resolves without hidden half-completed work',
    misconception: 'One application-level try block makes writes to several independent systems atomic',
    operation: 'Monitor pending outbox work, compensation failures, reconciliation age, and invariant violations',
    review: 'Where are the irreversible boundaries, and what repairs each possible interruption?',
  },
  {
    id: 'async-workflows',
    title: 'Queues, Jobs & Async Workflows',
    questionTarget: 12,
    principle: 'Asynchronous work needs explicit delivery, ownership, retry, ordering, and terminal-failure semantics',
    scenario: 'A worker crashes after sending an email but before acknowledging the queue message.',
    action: 'Make processing idempotent, acknowledge only after durable completion, and define retry and dead-letter behavior',
    failure: 'Jobs disappear, run twice with extra effects, remain stuck forever, or block unrelated queue partitions',
    evidence: 'Trace message ID, enqueue time, lease, attempts, acknowledgement, side effects, and dead-letter state',
    boundary: 'a job exceeds its visibility timeout, poison work repeats, or messages for one entity arrive out of order',
    tradeoff: 'Async processing improves responsiveness and buffering but replaces immediate completion with eventual state and operational complexity',
    verification: 'Crash workers at each lifecycle step and test duplicates, ordering, retry exhaustion, and replay',
    outcome: 'Long-running or bursty work progresses reliably without tying its lifetime to an HTTP request',
    misconception: 'Putting work on a queue guarantees exactly-once execution',
    operation: 'Track queue age, depth, processing latency, attempts, dead letters, and worker saturation',
    review: 'Who owns the job after each transition, and how can an operator recover terminal failures?',
  },
  {
    id: 'api-observability',
    title: 'Observability & API Error Diagnosis',
    questionTarget: 12,
    principle: 'API telemetry should connect a client-visible outcome to the internal work and dependency calls that produced it',
    scenario: 'Users report intermittent 502 responses, but logs contain only the text request failed.',
    action: 'Add structured request context, dependency spans, stable error codes, and latency metrics around the failing path',
    failure: 'Operators can see that requests failed but cannot identify the affected operation, dependency, tenant, or stage',
    evidence: 'Correlate route metrics, traces, structured logs, deployment version, and dependency outcomes for one request ID',
    boundary: 'sampling, asynchronous handoffs, retries, and privacy rules can break or constrain correlation',
    tradeoff: 'Richer telemetry speeds diagnosis but adds cost and requires disciplined redaction and sampling',
    verification: 'Trigger known failures and confirm an operator can locate cause and impact from emitted signals',
    outcome: 'A production symptom can be narrowed to the responsible request stage without reproducing it locally first',
    misconception: 'Verbose text logs alone make an API observable',
    operation: 'Define dashboards and alerts around rates, errors, latency, saturation, and key dependency health',
    review: 'Can the team answer what failed, where, for whom, since when, and after which release?',
  },
  {
    id: 'api-security',
    title: 'API Security Boundaries',
    questionTarget: 16,
    principle: 'Every external value and outbound capability must be constrained according to its trust boundary and intended authority',
    scenario: 'An endpoint fetches any URL supplied by a caller from a server with access to private cloud metadata.',
    action: 'Allow only required destinations and protocols, resolve and validate addresses, and isolate outbound network authority',
    failure: 'Untrusted input changes a query, reaches private services, exposes secrets, or performs an action with ambient server privilege',
    evidence: 'Map input sources to interpreters, outbound calls, credentials, data sinks, and authorization checks',
    boundary: 'redirects, encoded input, alternate IP forms, DNS changes, and browser credential behavior bypass a simple check',
    tradeoff: 'Strict allowlists reduce integration flexibility but sharply reduce injection and server-side request forgery exposure',
    verification: 'Use adversarial tests for injection, origin policy, request forgery, secret exposure, and privilege escalation',
    outcome: 'Caller-controlled data cannot silently acquire the authority of the server or another user',
    misconception: 'Escaping HTML protects an API from every form of injection and request forgery',
    operation: 'Alert on denied targets, unusual egress, repeated validation failures, and privileged endpoint access',
    review: 'Which interpreter or privileged capability receives this value, and what constrains it before use?',
  },
  {
    id: 'api-contract-testing',
    title: 'API Contract Compatibility',
    questionTarget: 12,
    principle: 'Integration tests should verify the observable contract at real boundaries where independent assumptions can diverge',
    scenario: 'Provider unit tests pass after a field becomes nullable, but a consumer crashes when it receives null.',
    action: 'Add a consumer-relevant contract case and run it against the provider representation before release',
    failure: 'Each component passes alone while serialization, schema, protocol, or dependency behavior fails when combined',
    evidence: 'Compare the published contract, real request and response, consumer assumptions, and provider compatibility results',
    boundary: 'optional fields, unknown fields, error bodies, timeouts, version skew, and serialization defaults differ',
    tradeoff: 'Real integrations provide confidence but cost more to provision and maintain than isolated unit tests',
    verification: 'Run representative success and failure contracts against realistic infrastructure with controlled dependencies',
    outcome: 'Breaking integration assumptions are found before independently deployed components meet in production',
    misconception: 'Mocking the client library proves that the real provider contract is compatible',
    operation: 'Track contract suite failures by consumer and block incompatible provider changes',
    review: 'Which boundary assumptions remain mocked, and what test proves the actual wire representation?',
  },
  {
    id: 'gateways-negotiation',
    title: 'Proxies, Gateways & Content Negotiation',
    questionTarget: 8,
    principle: 'Intermediaries and representation negotiation must preserve client intent, trusted origin context, and consistent routing semantics',
    scenario: 'An application trusts any X-Forwarded-For value and treats an external caller as an internal address.',
    action: 'Trust forwarding headers only from configured proxies and normalize the effective request context once',
    failure: 'Routing, scheme, client identity, caching, or representation changes unexpectedly across an intermediary',
    evidence: 'Compare client headers, gateway transformations, upstream request context, route match, and selected representation',
    boundary: 'multiple proxies, duplicated headers, unsupported media types, large payloads, and streaming responses occur',
    tradeoff: 'A gateway centralizes cross-cutting policy but can become a bottleneck and hide application-specific semantics',
    verification: 'Test trusted and untrusted forwarding chains, route rewrites, media negotiation, limits, and direct access',
    outcome: 'Applications receive a normalized trustworthy request while clients get a supported representation',
    misconception: 'Forwarded headers are trustworthy because their names are standardized',
    operation: 'Observe gateway and upstream status, transformations, rejected media, route latency, and correlation IDs',
    review: 'Which headers and routing decisions are authoritative, and what happens when no representation is acceptable?',
  },
] satisfies readonly SoftwareMasteryTopicBlueprint[]

export const apiBackendMasteryTopics = defineSoftwareMasteryTopics(
  'apis-backend',
  apiBackendBlueprints,
)