import { account, openService, resourceGroup, usRegion } from './common'
import { lines, pt, type LabSeed } from './types'

export const scaleLabs: readonly LabSeed[] = [
  {
    slug: 'load-balancer',
    title: 'Put a load balancer in front',
    mission: 'Give users one public HTTPS address. Send traffic only to healthy servers.',
    concept: [
      'A load balancer is the single front door. Users talk to it, it talks to your servers.',
      'A health probe calls /health every few seconds. A server that fails gets no traffic.',
      'HTTPS ends at the load balancer, so certificates live in one place.',
    ],
    build: ['Public HTTPS load balancer', 'Backend pool', 'Health probe on /health'],
    architecture: ['dev', 'registry', 'network', 'users', 'lb', 'vm'],
    steps: [
      {
        title: 'Open load balancing',
        screen: 'Home',
        instruction: pt('Open "Application gateways".', 'Open "Load Balancers".', 'Open "Load balancing".'),
        why: pt(
          'Application Gateway is a layer 7 (HTTP) load balancer. It understands URLs and HTTPS. Azure Load Balancer is layer 4 (TCP) only.',
          'An Application Load Balancer (ALB) is layer 7 (HTTP). It understands URLs and HTTPS. A Network Load Balancer is layer 4 (TCP) only.',
          'The Application Load Balancer is layer 7 (HTTP). It understands URLs and HTTPS. The Network Load Balancer is layer 4 (TCP) only.',
        ),
        task: openService('lb'),
        result: 'Load balancing opened.',
      },
      {
        title: 'Choose the type',
        screen: pt('Home > Application gateways > Create', 'EC2 > Load balancers > Create load balancer', 'Load balancing > Create load balancer'),
        instruction: 'Pick the load balancer type for a web API.',
        why: 'Web apps need a layer 7 load balancer. It can read the URL path, end HTTPS, and plug in a web firewall (Lab 10).',
        task: {
          kind: 'choice',
          question: 'Which type for an HTTPS web API?',
          options: [
            { label: pt('Application Gateway (layer 7, HTTP/HTTPS)', 'Application Load Balancer (layer 7)', 'Application Load Balancer (HTTP/HTTPS)'), correct: true, feedback: 'Correct. HTTP-aware, HTTPS, path routing, WAF support.' },
            { label: pt('Load Balancer (layer 4, TCP/UDP)', 'Network Load Balancer (layer 4)', 'Network Load Balancer (TCP/UDP)'), feedback: 'Layer 4 is for raw TCP/UDP, like games or databases. It cannot read URLs.' },
          ],
        },
        result: 'Layer 7 load balancer selected.',
      },
      {
        title: 'Configure the front door',
        screen: pt('Home > Application gateways > Create application gateway', 'EC2 > Load balancers > Create Application Load Balancer', 'Load balancing > Create Application Load Balancer'),
        instruction: 'Name it lb-shop, make it internet-facing in the public subnet, and spread it across zones.',
        why: 'The load balancer is the only public part of your system. Spreading it over 2–3 zones means one data-center fire does not take it down.',
        task: {
          kind: 'form',
          tabs: pt(['Basics', 'Frontends', 'Backends', 'Configuration', 'Tags', 'Review + create'], ['Basic configuration', 'Network mapping', 'Security groups', 'Listeners and routing'], ['Frontend configuration', 'Backend configuration', 'Routing rules', 'Review and finalize']),
          fields: [
            account,
            resourceGroup,
            { kind: 'text', label: 'Name', placeholder: 'lb-shop', accept: '^lb-shop$', hint: 'Type lb-shop.' },
            { kind: 'fixed', label: 'Region', value: usRegion, platforms: ['azure', 'aws'] },
            {
              kind: 'select',
              label: pt('Frontend IP type', 'Scheme', 'Public facing or internal'),
              options: [
                { label: pt('Public', 'Internet-facing', 'Public facing (external)'), feedback: 'Correct. Users on the internet must reach it.' },
                { label: pt('Private', 'Internal', 'Internal only'), feedback: 'Internal load balancers are for traffic inside your network only.' },
              ],
              correct: 0,
              hint: 'Users are on the internet.',
            },
            {
              kind: 'select',
              label: pt('Subnet', 'Subnets', 'Network'),
              platforms: ['azure', 'aws'],
              options: [
                { label: 'public (10.0.1.0/24)', feedback: 'Correct. The public subnet is for the front door.' },
                { label: 'app (10.0.2.0/24)', feedback: 'The app subnet has no internet route. Keep it private.' },
              ],
              correct: 0,
              hint: 'The front door lives in the public subnet.',
            },
            {
              kind: 'select',
              label: pt('Availability zones', 'Availability Zones', 'Scope'),
              options: [
                { label: pt('Zone 1 only', 'us-east-1a only', 'Regional, single zone'), feedback: 'One zone failing would take the whole site down.' },
                { label: pt('Zones 1, 2, 3', 'us-east-1a, 1b, 1c', 'Global (anycast, all zones)'), feedback: 'Correct. Survives the loss of a zone.' },
              ],
              correct: 1,
              hint: 'Survive a full zone outage.',
            },
          ],
          submit: 'Next',
        },
        result: 'Front door configured.',
      },
      {
        title: 'Listener and certificate',
        screen: pt('Application gateway > Configuration > Add a routing rule > Listener', 'Create ALB > Listeners and routing', 'Create load balancer > Frontend configuration'),
        instruction: 'Listen on HTTPS 443 with a managed certificate. Redirect HTTP to HTTPS.',
        why: 'HTTPS encrypts traffic so no one on the Wi-Fi can read passwords or tokens. A managed certificate renews itself, so it never expires by surprise.',
        task: {
          kind: 'form',
          fields: [
            {
              kind: 'select',
              label: 'Protocol / port',
              options: [
                { label: 'HTTP / 80', feedback: 'Plain HTTP sends everything unencrypted.' },
                { label: 'HTTPS / 443', feedback: 'Correct. Encrypted traffic.' },
              ],
              correct: 1,
              hint: 'Encrypt everything users send.',
            },
            {
              kind: 'select',
              label: 'Certificate',
              options: [
                { label: 'Upload a self-signed certificate', feedback: 'Browsers will show a big red warning.' },
                { label: pt('Key Vault certificate (auto-renew)', 'AWS Certificate Manager: api.shop.com', 'Google-managed certificate: api.shop.com'), feedback: 'Correct. Trusted and renews by itself.' },
              ],
              correct: 1,
              hint: 'Trusted and auto-renewing.',
            },
            {
              kind: 'select',
              label: 'Port 80 (HTTP)',
              options: [
                { label: 'Redirect to HTTPS', feedback: 'Correct. Old links still work, but traffic is always encrypted.' },
                { label: 'Serve the app on HTTP too', feedback: 'Users could log in over plain HTTP by mistake.' },
              ],
              correct: 0,
              hint: 'Never serve the app unencrypted.',
            },
          ],
          submit: 'Save listener',
        },
        result: 'HTTPS on 443 with an auto-renewing certificate.',
      },
      {
        title: 'Backend pool and health probe',
        screen: pt('Application gateway > Backend pools + Health probes', 'EC2 > Target groups > Create target group', 'Load balancing > Backend service > Health check'),
        instruction: 'Add vm-shop-1 on port 3000 and set the health check.',
        why: 'The probe is how the load balancer knows a server is alive. If /health fails a few times in a row, that server stops getting users until it recovers.',
        task: {
          kind: 'form',
          fields: [
            { kind: 'fixed', label: pt('Backend pool', 'Target group', 'Backend'), value: 'vm-shop-1 (10.0.2.4) : 3000' },
            { kind: 'text', label: 'Health check path', placeholder: '/health', accept: '^/health$', hint: 'Type /health (the endpoint from Lab 1).' },
            {
              kind: 'select',
              label: 'Check every',
              options: [
                { label: '1 second', feedback: 'Too noisy. Many servers × many checks = wasted load.' },
                { label: '10 seconds', feedback: 'Correct. Fast enough to catch problems, light on servers.' },
                { label: '5 minutes', feedback: 'Users would hit a dead server for minutes.' },
              ],
              correct: 1,
              hint: 'Fast detection without spamming the server.',
            },
            {
              kind: 'select',
              label: 'Unhealthy after',
              options: [
                { label: '1 failed check', feedback: 'One slow reply would remove a good server.' },
                { label: '3 failed checks in a row', feedback: 'Correct. Ignores one-off blips, removes real failures in ~30 s.' },
              ],
              correct: 1,
              hint: 'Avoid removing servers for one slow reply.',
            },
          ],
          submit: 'Create',
        },
        cli: pt(
          'az network application-gateway probe create -g rg-shop-prod \\\n  --gateway-name lb-shop -n health --protocol Http --path /health \\\n  --interval 10 --threshold 3 --host-name-from-http-settings true',
          'aws elbv2 create-target-group --name tg-shop --protocol HTTP --port 3000 \\\n  --vpc-id vpc-0a1b2c --health-check-path /health \\\n  --health-check-interval-seconds 10 --unhealthy-threshold-count 3',
          'gcloud compute health-checks create http hc-shop --port=3000 \\\n  --request-path=/health --check-interval=10s --unhealthy-threshold=3',
        ),
        result: 'Backend pool with health probe ready.',
      },
      {
        title: 'Point the domain at it',
        screen: pt('Home > DNS zones > shop.com > + Record set', 'Route 53 > Hosted zones > shop.com > Create record', 'Cloud DNS > shop-com > Add standard'),
        instruction: 'Create the DNS record so api.shop.com goes to the load balancer.',
        why: 'DNS turns a name into an address. Pointing at the load balancer (not a VM) means you can add, remove, or replace servers and the name never changes.',
        task: {
          kind: 'form',
          fields: [
            { kind: 'text', label: 'Name', placeholder: 'api', accept: '^api$', hint: 'Type api (for api.shop.com).' },
            {
              kind: 'select',
              label: 'Points to',
              options: [
                { label: 'vm-shop-1 private IP 10.0.2.4', feedback: 'A private IP cannot be reached from the internet.' },
                { label: pt('lb-shop public IP (alias)', 'Alias → lb-shop ALB', 'lb-shop frontend IP'), feedback: 'Correct. Users always arrive at the front door.' },
              ],
              correct: 1,
              hint: 'Users should always arrive at the front door.',
            },
          ],
          submit: 'Save record',
        },
        result: 'api.shop.com → lb-shop.',
      },
      {
        title: 'Test it, then break it',
        screen: 'Browser',
        instruction: 'Call the API, then stop the only VM and watch what happens.',
        why: 'With one server, the load balancer has nowhere to send users when it fails. This is a single point of failure. You fix it in the next lab.',
        task: {
          kind: 'simulate',
          action: 'Run test',
          url: 'https://api.shop.com/health',
          frames: [
            { log: 'GET https://api.shop.com/health → 200 OK (42 ms)', tone: 'ok' },
            { log: 'Certificate valid: api.shop.com, auto-renews', tone: 'ok' },
            { log: 'Stopping vm-shop-1…', tone: 'warn' },
            { log: 'Health probe: 1/3 failed, 2/3 failed, 3/3 failed', tone: 'warn' },
            { log: 'vm-shop-1 marked Unhealthy. Healthy backends: 0', tone: 'bad' },
            { log: 'GET https://api.shop.com/health → 502 Bad Gateway', tone: 'bad' },
          ],
        },
        result: 'The site went down because there was only one server.',
      },
    ],
  },
  {
    slug: 'autoscale',
    title: 'Scale out across zones',
    mission: 'Replace the single VM with a group that adds and removes servers by itself and survives a zone outage.',
    concept: [
      'Scale out = add more servers. Scale up = make one server bigger. Scale out has no ceiling and no single point of failure.',
      'A VM group creates every server from the same template, then keeps the count you ask for.',
      'Autoscale watches CPU or requests and adds servers when busy, removes them when quiet.',
    ],
    build: ['VM template', 'VM group in 3 zones', 'Autoscale rule: 2 to 20 VMs'],
    architecture: ['dev', 'registry', 'network', 'users', 'lb', 'scaleSet'],
    steps: [
      {
        title: 'Open the VM group service',
        screen: 'Home',
        instruction: pt('Open "Virtual machine scale sets".', 'Open "Auto Scaling groups".', 'Open "Instance groups".'),
        why: 'You will never create servers one by one again. The group does it from a template.',
        task: openService('scale'),
        result: 'VM group service opened.',
      },
      {
        title: 'Template + group',
        screen: pt('Home > Virtual machine scale sets > Create', 'EC2 > Launch templates + Auto Scaling groups > Create', 'Compute Engine > Instance templates + Instance groups > Create'),
        instruction: 'Use the same settings as vm-shop-1, spread over 3 zones, and join the load balancer.',
        why: 'The template holds everything from Lab 4: image, size, subnet, identity, startup script. Every new VM is an exact copy, so any of them can serve any user.',
        task: {
          kind: 'form',
          tabs: pt(['Basics', 'Spot', 'Disks', 'Networking', 'Scaling', 'Management', 'Health', 'Advanced'], ['Choose launch template', 'Choose instance launch options', 'Integrate with other services', 'Configure group size and scaling'], ['Instance template', 'Location', 'Autoscaling', 'Autohealing']),
          fields: [
            account,
            resourceGroup,
            { kind: 'text', label: 'Name', placeholder: 'vmss-shop', accept: '^(vmss|asg|mig)-shop$', hint: pt('Type vmss-shop.', 'Type asg-shop.', 'Type mig-shop.') },
            { kind: 'fixed', label: pt('Image + size + script', 'Launch template', 'Instance template'), value: pt('Same as vm-shop-1 (Lab 4)', 'lt-shop v1 (from vm-shop-1)', 'it-shop-v1 (from vm-shop-1)') },
            {
              kind: 'select',
              label: pt('Availability zones', 'Subnets', 'Location'),
              options: [
                { label: pt('Zone 1', 'subnet-app-a (us-east-1a)', 'Single zone: us-central1-a'), feedback: 'All servers would die with that one zone.' },
                { label: pt('Zones 1, 2, 3', 'subnet-app-a, -b, -c (3 zones)', 'Multiple zones: us-central1-a, b, c'), feedback: 'Correct. Servers are spread so a zone outage only removes a third.' },
              ],
              correct: 1,
              hint: 'Survive the loss of a full zone.',
            },
            {
              kind: 'select',
              label: pt('Load balancing', 'Attach to load balancer', 'Load balancing'),
              options: [
                { label: 'None', feedback: 'New servers would never get traffic.' },
                { label: pt('lb-shop backend pool', 'Target group tg-shop', 'Backend service lb-shop'), feedback: 'Correct. Each new VM joins the load balancer automatically.' },
              ],
              correct: 1,
              hint: 'New servers must get traffic automatically.',
            },
            {
              kind: 'select',
              label: pt('Automatic repairs', 'Health check type', 'Autohealing'),
              options: [
                { label: pt('Off', 'EC2 (VM is powered on)', 'No health check'), feedback: 'A VM can be on while the app inside is dead. The group would not notice.' },
                { label: pt('On, using the load balancer probe', 'ELB (app answers /health)', 'hc-shop (/health), initial delay 120 s'), feedback: 'Correct. A broken VM is replaced automatically.' },
              ],
              correct: 1,
              hint: 'Replace VMs whose app stops answering.',
            },
          ],
          submit: 'Next',
        },
        result: 'Group defined.',
      },
      {
        title: 'Autoscale rule',
        screen: pt('Virtual machine scale set > Scaling', 'Auto Scaling group > Configure group size and scaling', 'Instance group > Autoscaling'),
        instruction: 'Set min, max, and the signal that adds servers.',
        why: 'Min 2 keeps the site up if one VM dies. Max 20 protects your bill from runaway scaling. 60% CPU leaves headroom: new VMs need ~2 minutes to boot, so you scale before you are full.',
        task: {
          kind: 'form',
          fields: [
            {
              kind: 'select',
              label: 'Minimum servers',
              options: [
                { label: '0', feedback: 'With 0 servers at night, the first user waits minutes for a VM to boot.' },
                { label: '1', feedback: 'One server is a single point of failure again.' },
                { label: '2', feedback: 'Correct. Always one spare, in two different zones.' },
              ],
              correct: 2,
              hint: 'Never fewer than enough to survive one failure.',
            },
            {
              kind: 'select',
              label: 'Maximum servers',
              options: [
                { label: '20', feedback: 'Correct. A safety cap for your bill. Raise it when you plan bigger events.' },
                { label: 'No limit', feedback: 'A bug or an attack could start thousands of VMs and a huge bill.' },
              ],
              correct: 0,
              hint: 'Always cap the bill.',
            },
            {
              kind: 'select',
              label: 'Scale out when',
              options: [
                { label: 'Average CPU > 60% (target tracking)', feedback: 'Correct. Leaves room while new VMs boot.' },
                { label: 'Average CPU > 95%', feedback: 'Users already feel slowness before new VMs are ready.' },
                { label: 'Memory > 10%', feedback: 'Too low. You would always be at max servers.' },
              ],
              correct: 0,
              hint: 'Scale before you are full; boot takes time.',
            },
            {
              kind: 'select',
              label: 'Scale in (remove servers)',
              options: [
                { label: 'Immediately when CPU drops', feedback: 'Traffic bounces up and down. You would add and remove VMs all day (flapping).' },
                { label: 'After 10 minutes below target (cool-down)', feedback: 'Correct. Avoids flapping.' },
              ],
              correct: 1,
              hint: 'Avoid adding and removing servers all day.',
            },
          ],
          submit: 'Create',
        },
        cli: pt(
          'az vmss create -g rg-shop-prod -n vmss-shop --image Ubuntu2404 \\\n  --vm-sku Standard_B2s --zones 1 2 3 --instance-count 2 \\\n  --vnet-name vnet-shop --subnet snet-app --app-gateway lb-shop \\\n  --assign-identity --custom-data cloud-init.sh\naz monitor autoscale create -g rg-shop-prod --resource vmss-shop \\\n  --resource-type Microsoft.Compute/virtualMachineScaleSets \\\n  --min-count 2 --max-count 20 --count 2\naz monitor autoscale rule create -g rg-shop-prod --autoscale-name vmss-shop \\\n  --condition "Percentage CPU > 60 avg 5m" --scale out 2',
          'aws autoscaling create-auto-scaling-group --auto-scaling-group-name asg-shop \\\n  --launch-template LaunchTemplateName=lt-shop --min-size 2 --max-size 20 \\\n  --vpc-zone-identifier "subnet-app-a,subnet-app-b,subnet-app-c" \\\n  --target-group-arns $TG_ARN --health-check-type ELB --health-check-grace-period 120\naws autoscaling put-scaling-policy --auto-scaling-group-name asg-shop \\\n  --policy-name cpu60 --policy-type TargetTrackingScaling \\\n  --target-tracking-configuration file://cpu60.json',
          'gcloud compute instance-groups managed create mig-shop --region=us-central1 \\\n  --template=it-shop-v1 --size=2 --health-check=hc-shop --initial-delay=120\ngcloud compute instance-groups managed set-autoscaling mig-shop \\\n  --region=us-central1 --min-num-replicas=2 --max-num-replicas=20 \\\n  --target-cpu-utilization=0.6 --cool-down-period=120',
        ),
        result: 'Autoscale: 2 to 20 VMs at 60% CPU.',
      },
      {
        title: 'Load test',
        screen: 'Load test > 20,000 virtual users',
        instruction: 'Send a traffic spike and watch the group react.',
        why: 'Never trust autoscale until you see it work. A load test shows how fast new servers arrive and if users feel slowness.',
        task: {
          kind: 'simulate',
          action: 'Start load test',
          metrics: [
            { label: 'Requests / s', unit: '', max: 6000 },
            { label: 'Average CPU', unit: '%', max: 100 },
            { label: 'Servers', unit: '', max: 20 },
            { label: 'p95 latency', unit: 'ms', max: 800 },
          ],
          frames: [
            { log: 'Baseline: 2 servers, quiet traffic', tone: 'info', values: [300, 22, 2, 90] },
            { log: 'Spike starts: 4,000 requests/s', tone: 'warn', values: [4000, 88, 2, 610] },
            { log: 'CPU above 60% for 2 minutes → autoscale adds 4 servers', tone: 'info', values: [4000, 85, 6, 540] },
            { log: 'New VMs booted, passed /health, joined the load balancer', tone: 'ok', values: [4500, 58, 6, 160] },
            { log: 'Traffic keeps rising → 10 servers', tone: 'info', values: [5800, 59, 10, 140] },
            { log: 'Spike ends. After 10 min cool-down → back to 2', tone: 'ok', values: [350, 21, 2, 88] },
          ],
        },
        result: 'Scaled from 2 to 10 and back with no errors.',
      },
      {
        title: 'Zone outage drill',
        screen: 'Chaos test > Zone 1 power loss',
        instruction: 'Simulate a full zone outage.',
        why: 'Zones are separate data centers with their own power and cooling. Spreading servers means a zone outage only removes some capacity.',
        task: {
          kind: 'simulate',
          action: 'Fail zone 1',
          frames: [
            { log: 'Zone 1 lost power. 2 of 6 servers gone.', tone: 'bad' },
            { log: 'Load balancer probes fail → zone 1 servers removed from rotation', tone: 'warn' },
            { log: 'Users served by zones 2 and 3 (no errors, latency +40 ms)', tone: 'ok' },
            { log: 'Group replaces lost capacity in zones 2 and 3', tone: 'ok' },
          ],
        },
        result: 'The site stayed up during a full zone outage.',
      },
      {
        title: 'Spot the new problem',
        screen: 'Bug report',
        instruction: 'Users say: "I get logged out at random, and my cart sometimes empties." Why?',
        why: 'With many servers, each request can land on a different one. Anything kept in one server\'s memory is lost on the next request.',
        task: {
          kind: 'choice',
          question: 'What is the real cause?',
          options: [
            { label: 'The servers are too small', feedback: 'Size does not cause lost logins.' },
            { label: 'Sessions and carts are stored in each server\'s memory', correct: true, feedback: 'Correct. Servers must be stateless. Shared state moves to Redis in the next lab.' },
            { label: 'Turn on sticky sessions and forget it', feedback: 'It hides the bug, but when that server is removed by scale-in, users still lose their cart.' },
          ],
        },
        result: 'Next: move shared state to Redis.',
      },
    ],
  },
  {
    slug: 'redis-and-database',
    title: 'Add Redis and a private database',
    mission: 'Move sessions and hot data to managed Redis, and store orders in a managed, highly available database, both only reachable on the private network.',
    concept: [
      'Stateless servers keep nothing in memory between requests. Any server can handle any user.',
      'Redis is a very fast in-memory store for sessions, cache, and rate limits.',
      'The database is the source of truth. Managed means the cloud does backups, patches, and failover.',
    ],
    build: ['Managed Redis (zone-redundant)', 'Managed PostgreSQL with standby', 'Private endpoints in the data subnet'],
    architecture: ['dev', 'registry', 'network', 'users', 'lb', 'scaleSet', 'redis', 'db'],
    steps: [
      {
        title: 'Open managed Redis',
        screen: 'Home',
        instruction: pt('Open "Azure Managed Redis".', 'Open "ElastiCache".', 'Open "Memorystore".'),
        why: 'Running Redis yourself means patching, failover, and backups at 3 a.m. Managed Redis does that for you.',
        task: openService('redis'),
        result: 'Managed Redis opened.',
      },
      {
        title: 'Create the Redis cache',
        screen: pt('Home > Azure Managed Redis > Create', 'ElastiCache > Redis OSS caches > Create', 'Memorystore > Redis > Create instance'),
        instruction: 'Create redis-shop, private only, replicated across zones, with TLS.',
        why: 'If Redis dies, every user is logged out. A replica in another zone takes over in seconds. TLS + private access keeps session data off the internet.',
        task: {
          kind: 'form',
          tabs: pt(['Basics', 'Networking', 'Advanced', 'Tags', 'Review + create'], ['Cluster settings', 'Connectivity', 'Security', 'Backup'], ['Instance', 'Connections', 'Configuration']),
          fields: [
            account,
            resourceGroup,
            { kind: 'text', label: 'Name', placeholder: 'redis-shop', accept: '^redis-shop$', hint: 'Type redis-shop.' },
            {
              kind: 'select',
              label: pt('Performance / high availability', 'Multi-AZ', 'Tier'),
              options: [
                { label: pt('No high availability (dev/test)', 'Disabled', 'Basic (no replica)'), feedback: 'One node: if it fails, everyone is logged out.' },
                { label: pt('High availability, zone redundant', 'Enabled, automatic failover', 'Standard (replica in another zone)'), feedback: 'Correct. A replica in another zone takes over automatically.' },
              ],
              correct: 1,
              hint: 'Losing Redis logs everyone out.',
            },
            {
              kind: 'select',
              label: pt('Connectivity', 'Subnet group', 'Connections'),
              options: [
                { label: pt('Public endpoint', 'Public subnets', 'Any network'), feedback: 'Session data would be reachable from outside.' },
                { label: pt('Private endpoint in data subnet', 'data subnets (3 zones)', 'Private service access on vpc-shop'), feedback: 'Correct. Only your network can reach it.' },
              ],
              correct: 1,
              hint: 'Keep it on the private network.',
            },
            {
              kind: 'select',
              label: 'Encryption in transit (TLS)',
              options: [
                { label: 'Enabled', feedback: 'Correct. Even inside your network, traffic is encrypted.' },
                { label: 'Disabled', feedback: 'Session tokens would travel in clear text.' },
              ],
              correct: 0,
              hint: 'Encrypt everywhere.',
            },
          ],
          submit: 'Create',
        },
        cli: pt(
          'az redisenterprise create -g rg-shop-prod -n redis-shop \\\n  --sku Balanced_B1 --zones 1 2 3 --public-network-access Disabled',
          'aws elasticache create-replication-group --replication-group-id redis-shop \\\n  --engine redis --cache-node-type cache.r7g.large --num-cache-clusters 2 \\\n  --multi-az-enabled --automatic-failover-enabled \\\n  --transit-encryption-enabled --cache-subnet-group-name data',
          'gcloud redis instances create redis-shop --region=us-central1 \\\n  --tier=standard --size=5 --network=vpc-shop \\\n  --connect-mode=private-service-access --transit-encryption-mode=server-authentication',
        ),
        result: 'redis-shop: private, zone-redundant, TLS.',
      },
      {
        title: 'Create the database',
        screen: pt('Home > Azure Database for PostgreSQL > Create flexible server', 'RDS > Databases > Create database', 'Cloud SQL > Create instance > PostgreSQL'),
        instruction: 'Create db-shop with a standby in another zone, private access, and backups.',
        why: 'Orders and payments live here. A standby in another zone takes over if the main one fails. Point-in-time backups let you undo a bad delete.',
        task: {
          kind: 'form',
          tabs: pt(['Basics', 'Networking', 'Security', 'Tags', 'Review + create'], ['Engine options', 'Availability', 'Settings', 'Connectivity', 'Backup'], ['Instance info', 'Choose region and zonal availability', 'Connections', 'Data protection']),
          fields: [
            account,
            resourceGroup,
            { kind: 'text', label: 'Server name', placeholder: 'db-shop', accept: '^db-shop$', hint: 'Type db-shop.' },
            { kind: 'fixed', label: 'Engine', value: 'PostgreSQL 16' },
            {
              kind: 'select',
              label: pt('High availability', 'Availability and durability', 'Zonal availability'),
              options: [
                { label: pt('Disabled', 'Single DB instance', 'Single zone'), feedback: 'If that zone fails, you lose all orders until it returns.' },
                { label: pt('Zone redundant (standby in another zone)', 'Multi-AZ DB instance', 'Multiple zones (highly available)'), feedback: 'Correct. Automatic failover in ~1–2 minutes.' },
              ],
              correct: 1,
              hint: 'Orders must survive a zone outage.',
            },
            {
              kind: 'select',
              label: pt('Connectivity method', 'Public access', 'Instance IP assignment'),
              options: [
                { label: pt('Public access (allowed IP addresses)', 'Yes', 'Public IP'), feedback: 'Databases on the internet are a top cause of data breaches.' },
                { label: pt('Private access (VNet integration) — data subnet', 'No (data subnets only)', 'Private IP on vpc-shop'), feedback: 'Correct. Only the app subnet can reach it (Lab 3 rules).' },
              ],
              correct: 1,
              hint: 'No public address for data.',
            },
            {
              kind: 'select',
              label: 'Backups',
              options: [
                { label: '1 day', feedback: 'A bad delete found on Monday would be gone.' },
                { label: '7 days, point-in-time restore', feedback: 'Correct. Restore to any second in the last week.' },
              ],
              correct: 1,
              hint: 'You need time to notice mistakes.',
            },
          ],
          submit: 'Create',
        },
        cli: pt(
          'az postgres flexible-server create -g rg-shop-prod -n db-shop --version 16 \\\n  --high-availability ZoneRedundant --vnet vnet-shop --subnet snet-data \\\n  --backup-retention 7',
          'aws rds create-db-instance --db-instance-identifier db-shop --engine postgres \\\n  --engine-version 16 --db-instance-class db.r7g.large --multi-az \\\n  --no-publicly-accessible --db-subnet-group-name data --backup-retention-period 7 \\\n  --manage-master-user-password',
          'gcloud sql instances create db-shop --database-version=POSTGRES_16 \\\n  --region=us-central1 --availability-type=REGIONAL --no-assign-ip \\\n  --network=vpc-shop --enable-point-in-time-recovery --retained-backups-count=7',
        ),
        result: 'db-shop: private, zone-redundant, 7-day backups.',
      },
      {
        title: 'Use Redis in the code',
        surface: 'local',
        screen: 'shop-api > src/products.js',
        instruction: 'Fill the blanks: read from Redis first, fall back to the database, then save to Redis with an expiry.',
        why: 'This is the cache-aside pattern. Most reads never touch the database. The expiry (TTL) means stale data fixes itself after a few minutes.',
        task: {
          kind: 'code',
          file: 'src/products.js',
          code: lines(
            'export async function getProduct(id) {',
            '  const key = `product:${id}`',
            '  const cached = await redis.[[0]](key)',
            '  if (cached) return JSON.parse(cached)',
            '',
            '  const product = await db.query(\'SELECT * FROM products WHERE id = $1\', [id])',
            '  await redis.set(key, JSON.stringify(product), { EX: [[1]] })',
            '  return product',
            '}',
            '',
            '// sessions: store in Redis, not in server memory',
            'app.use(session({ store: [[2]] }))',
          ),
          blanks: [
            {
              options: [
                { label: 'get', feedback: 'Correct. Try the fast cache first.' },
                { label: 'del', feedback: 'That would delete the cache on every read.' },
              ],
              correct: 0,
            },
            {
              options: [
                { label: '300', feedback: 'Correct. 5 minutes: fresh enough, and most reads hit the cache.' },
                { label: 'none (never expire)', feedback: 'Price changes would never show up.' },
              ],
              correct: 0,
            },
            {
              options: [
                { label: 'new MemoryStore()', feedback: 'Memory store is per server. This is the logout bug.' },
                { label: 'new RedisStore({ client: redis })', feedback: 'Correct. Every server sees the same sessions.' },
              ],
              correct: 1,
            },
          ],
        },
        result: 'App is stateless. Shared state lives in Redis.',
      },
      {
        title: 'Connect without passwords in code',
        screen: 'Design decision',
        instruction: 'How do servers get the Redis and database addresses and credentials?',
        why: 'Settings change per environment. Secrets must never be in the image. You will move them into a secret vault in Lab 10.',
        task: {
          kind: 'choice',
          question: 'How should the app get DB_HOST and the password?',
          options: [
            { label: 'Hard-code them in config.js', feedback: 'Every copy of the code now holds the password.' },
            { label: 'Environment variables loaded at boot from a secret store, via the VM identity', correct: true, feedback: 'Correct. Image stays clean, secrets rotate without a rebuild.' },
          ],
        },
        result: 'Configuration is outside the image.',
      },
      {
        title: 'Measure the result',
        screen: 'Load test > 20,000 virtual users',
        instruction: 'Run the same load test again with Redis in place.',
        why: 'Caching is only worth it if numbers improve. Watch the cache hit rate and the database load.',
        task: {
          kind: 'simulate',
          action: 'Run load test',
          metrics: [
            { label: 'Cache hit rate', unit: '%', max: 100 },
            { label: 'Database CPU', unit: '%', max: 100 },
            { label: 'p95 latency', unit: 'ms', max: 400 },
            { label: 'Servers needed', unit: '', max: 20 },
          ],
          frames: [
            { log: 'Before Redis: every read goes to the database', tone: 'warn', values: [0, 92, 380, 10] },
            { log: 'Cache warming up…', tone: 'info', values: [55, 60, 190, 8] },
            { log: 'Steady state: 94% of reads served from Redis', tone: 'ok', values: [94, 18, 45, 4] },
            { log: 'Server scale-in removed a VM — no users logged out', tone: 'ok', values: [94, 18, 46, 3] },
          ],
        },
        result: 'Same traffic, 3 servers instead of 10, p95 45 ms, no lost sessions.',
      },
    ],
  },
]
