import { account, openService, registryHost, resourceGroup, usRegion } from './common'
import { lines, pt, type LabSeed } from './types'

const regionOptions = [
  { label: usRegion, feedback: 'Correct. Same region as your servers: fast image pulls and no cross-region transfer cost.' },
  { label: pt('Australia East', 'ap-southeast-2', 'australia-southeast1'), feedback: 'Too far from your servers. Every image pull would cross the world and cost extra.' },
]

export const foundationLabs: readonly LabSeed[] = [
  {
    slug: 'build-and-containerize',
    title: 'Build the app and put it in a container',
    mission: 'You have a small shop API on your laptop. Package it so it runs the same way on any server.',
    concept: [
      'A container image holds your code, the runtime, and all libraries in one package.',
      'If it runs in the container on your laptop, it runs the same way on a cloud VM.',
      'You build the image once and ship that exact image everywhere.',
    ],
    build: ['Dockerfile', 'Image shop-api:1.0', 'Running container on your laptop'],
    architecture: ['dev'],
    steps: [
      {
        title: 'Write the Dockerfile',
        surface: 'local',
        screen: 'shop-api > Dockerfile',
        instruction: 'Fill the 3 blanks in the Dockerfile. The app listens on port 3000.',
        why: 'A Dockerfile is the recipe for your image. A fixed base version and "npm ci" give you the same image every time. Running as the "node" user, not root, limits damage if someone breaks in.',
        task: {
          kind: 'code',
          file: 'Dockerfile',
          code: lines(
            'FROM node:[[0]]',
            'WORKDIR /app',
            'COPY package*.json ./',
            'RUN [[1]]',
            'COPY . .',
            'USER node',
            'EXPOSE [[2]]',
            'CMD ["node", "server.js"]',
          ),
          blanks: [
            {
              options: [
                { label: '22-alpine', feedback: 'Good: a fixed major version on a small base image.' },
                { label: 'latest', feedback: '"latest" changes without warning. Your build can break next month with no code change.' },
              ],
              correct: 0,
            },
            {
              options: [
                { label: 'npm install', feedback: '"npm install" can pick new versions and installs dev tools you do not need in production.' },
                { label: 'npm ci --omit=dev', feedback: 'Good: exact versions from the lock file, no dev tools.' },
              ],
              correct: 1,
            },
            {
              options: [
                { label: '80', feedback: 'The app code listens on 3000, not 80.' },
                { label: '3000', feedback: 'Matches the port in server.js.' },
              ],
              correct: 1,
            },
          ],
        },
        result: 'Your recipe is ready.',
      },
      {
        title: 'Build the image',
        surface: 'local',
        screen: 'Terminal > shop-api',
        instruction: 'Run the build command.',
        why: 'Build turns the recipe into an image. Each Dockerfile line becomes a layer. Docker reuses layers that did not change, so the next build is much faster.',
        task: {
          kind: 'terminal',
          command: 'docker build -t shop-api:1.0 .',
          output: [
            '[+] Building 18.4s (10/10) FINISHED',
            ' => [1/5] FROM docker.io/library/node:22-alpine',
            ' => [3/5] RUN npm ci --omit=dev',
            ' => [5/5] COPY . .',
            ' => exporting to image',
            ' => naming to docker.io/library/shop-api:1.0',
          ],
        },
        result: 'Image shop-api:1.0 exists on your laptop (148 MB).',
      },
      {
        title: 'Run the container',
        surface: 'local',
        screen: 'Terminal > shop-api',
        instruction: 'Start the container and connect laptop port 8080 to container port 3000.',
        why: 'A container is isolated. Nothing can reach it unless you map a port. "-p 8080:3000" means: traffic to my laptop on 8080 goes into the container on 3000.',
        task: {
          kind: 'terminal',
          command: 'docker run -d -p 8080:3000 --name shop shop-api:1.0',
          output: [
            '7c1e9d0b4a2f8e6d3c5b1a09f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9',
            '$ docker ps',
            'CONTAINER ID  IMAGE         STATUS        PORTS',
            '7c1e9d0b4a2f  shop-api:1.0  Up 3 seconds  0.0.0.0:8080->3000/tcp',
          ],
        },
        result: 'The container is running.',
      },
      {
        title: 'Check the health endpoint',
        surface: 'local',
        screen: 'Browser',
        instruction: 'Open the health check URL in the browser.',
        why: 'A /health endpoint lets machines check your app. Later, the load balancer calls it every few seconds to decide if a server should get traffic.',
        task: {
          kind: 'simulate',
          action: 'Open in browser',
          url: 'http://localhost:8080/health',
          frames: [
            { log: 'GET /health', tone: 'info' },
            { log: '200 OK  {"status":"ok","version":"1.0"}', tone: 'ok' },
          ],
        },
        result: 'Your app works inside a container.',
      },
      {
        title: 'Where does the database password go?',
        surface: 'local',
        screen: 'Code review',
        instruction: 'A teammate asks where to put the database password.',
        why: 'Anyone who can pull an image can read every file in it. Secrets must come in at runtime, never be baked into the image or Git.',
        task: {
          kind: 'choice',
          question: 'Where should the database password go?',
          options: [
            { label: 'Inside the Dockerfile with ENV DB_PASSWORD=...', feedback: 'Anyone who pulls the image can read it with "docker inspect".' },
            { label: 'In a .env file committed to Git', feedback: 'Git history keeps it forever, even after you delete the file.' },
            { label: 'Given to the container at runtime from a secret store', correct: true, feedback: 'Correct. The image stays clean. In Lab 10 you will load it from a cloud secret vault.' },
          ],
        },
        result: 'Rule learned: images contain code, never secrets.',
      },
    ],
  },
  {
    slug: 'push-to-registry',
    title: 'Push the image to a cloud registry',
    mission: 'Cloud servers cannot see your laptop. Put the image in a private cloud registry.',
    concept: [
      'A container registry is a private store for images.',
      'Your servers and your pipeline pull images from it.',
      'Each image gets a unique tag, so you always know which code is running.',
    ],
    build: ['Private container registry', 'Image pushed with a version tag'],
    architecture: ['dev', 'registry'],
    steps: [
      {
        title: 'Open the registry service',
        screen: 'Home',
        instruction: pt('Open "Container registries".', 'Open "Elastic Container Registry".', 'Open "Artifact Registry".'),
        why: 'Every cloud has a managed registry. You do not run or patch the storage servers yourself.',
        task: openService('registry'),
        cli: pt('az acr --help', 'aws ecr help', 'gcloud artifacts --help'),
        result: 'Registry service opened.',
      },
      {
        title: 'Create the registry',
        screen: pt('Home > Container registries > Create container registry', 'ECR > Private registry > Create repository', 'Artifact Registry > Repositories > Create repository'),
        instruction: pt(
          'Name the registry "shopregistry", put it in the same region as your servers, and pick the right tier.',
          'Name the repository "shop-api" and turn on the safety options.',
          'Name the repository "shop", use Docker format, and put it in your server region.',
        ),
        why: pt(
          'Premium costs more but adds private network access and copies in other regions. You need both later (Lab 9 and Lab 10).',
          'Immutable tags stop anyone from overwriting a released image. Scan on push finds known security holes before you deploy.',
          'Repositories hold one format. A regional repo next to your servers gives fast pulls. Scanning finds known security holes.',
        ),
        task: {
          kind: 'form',
          tabs: pt(['Basics', 'Networking', 'Encryption', 'Tags', 'Review + create'], ['General settings', 'Image scan settings', 'Encryption settings'], ['Repository details']),
          activeTab: 0,
          fields: [
            account,
            resourceGroup,
            {
              kind: 'text',
              label: pt('Registry name', 'Repository name', 'Name'),
              placeholder: pt('shopregistry', 'shop-api', 'shop'),
              accept: pt('^shopregistry$', '^shop-api$', '^shop$'),
              hint: pt('Type shopregistry (letters and numbers only).', 'Type shop-api.', 'Type shop.'),
            },
            {
              kind: 'select',
              label: pt('Location', 'Region', 'Region'),
              options: regionOptions,
              correct: 0,
              hint: 'Put the registry in the same region as the servers that pull from it.',
              platforms: ['azure', 'gcp'],
            },
            {
              kind: 'select',
              label: 'Pricing plan',
              platforms: ['azure'],
              options: [
                { label: 'Basic', feedback: 'Fine for learning, but no private endpoint and no geo-replication.' },
                { label: 'Standard', feedback: 'More storage, but still no private endpoint or geo-replication.' },
                { label: 'Premium', feedback: 'Correct for production: private endpoint + copies in other regions.' },
              ],
              correct: 2,
              hint: 'You will need private network access and a copy in Europe later.',
            },
            {
              kind: 'select',
              label: 'Tag immutability',
              platforms: ['aws'],
              options: [
                { label: 'Disabled', feedback: 'Someone could push a different image with the same tag.' },
                { label: 'Enabled', feedback: 'Correct. A released tag can never change.' },
              ],
              correct: 1,
              hint: 'A released version must never change.',
            },
            {
              kind: 'select',
              label: 'Scan on push',
              platforms: ['aws'],
              options: [
                { label: 'Enabled', feedback: 'Correct. Every new image is checked for known vulnerabilities.' },
                { label: 'Disabled', feedback: 'You would deploy images with known security holes and not know it.' },
              ],
              correct: 0,
              hint: 'Find security holes before deploy, not after.',
            },
            {
              kind: 'select',
              label: 'Format',
              platforms: ['gcp'],
              options: [
                { label: 'Docker', feedback: 'Correct. You are storing container images.' },
                { label: 'npm', feedback: 'npm repos store JavaScript packages, not container images.' },
                { label: 'Maven', feedback: 'Maven repos store Java packages.' },
              ],
              correct: 0,
              hint: 'You are storing container images.',
            },
            {
              kind: 'select',
              label: 'Vulnerability scanning',
              platforms: ['gcp'],
              options: [
                { label: 'Enabled', feedback: 'Correct. New images are scanned automatically.' },
                { label: 'Disabled', feedback: 'You would not know about known security holes in your image.' },
              ],
              correct: 0,
              hint: 'Find security holes before deploy, not after.',
            },
          ],
          submit: pt('Review + create', 'Create repository', 'Create'),
        },
        cli: pt(
          'az acr create -g rg-shop-prod -n shopregistry --sku Premium --location eastus',
          'aws ecr create-repository --repository-name shop-api \\\n  --image-tag-mutability IMMUTABLE \\\n  --image-scanning-configuration scanOnPush=true',
          'gcloud artifacts repositories create shop \\\n  --repository-format=docker --location=us-central1',
        ),
        result: 'Registry created.',
      },
      {
        title: 'Log in, tag, and push',
        surface: 'local',
        screen: 'Terminal > shop-api',
        instruction: 'Log Docker in to the registry, tag the image with the commit ID, and push it.',
        why: 'The tag is the full address of the image: registry/name:version. Using the Git commit ID as the version tells you exactly which code is running.',
        task: {
          kind: 'terminal',
          command: pt(
            lines('az acr login -n shopregistry', `docker tag shop-api:1.0 ${registryHost.azure}:3f9c2ab`, `docker push ${registryHost.azure}:3f9c2ab`),
            lines('aws ecr get-login-password | docker login --username AWS \\', '  --password-stdin 123456789012.dkr.ecr.us-east-1.amazonaws.com', `docker tag shop-api:1.0 ${registryHost.aws}:3f9c2ab`, `docker push ${registryHost.aws}:3f9c2ab`),
            lines('gcloud auth configure-docker us-central1-docker.pkg.dev', `docker tag shop-api:1.0 ${registryHost.gcp}:3f9c2ab`, `docker push ${registryHost.gcp}:3f9c2ab`),
          ),
          output: [
            'Login Succeeded',
            'The push refers to repository [shop-api]',
            '5f70bf18a086: Pushed',
            'e2eb06d8af82: Pushed',
            '3f9c2ab: digest: sha256:9b2c41e7d0f3... size: 1784',
          ],
        },
        result: 'Image shop-api:3f9c2ab is in the cloud registry.',
      },
      {
        title: 'Pick a tagging rule',
        screen: 'Team decision',
        instruction: 'Your pipeline will build a new image on every commit. Choose the tag.',
        why: 'When something breaks at 2 a.m., you must know which version is running and roll back to the one before it. A unique tag per build makes that possible.',
        task: {
          kind: 'choice',
          question: 'Which tag should each new build use?',
          options: [
            { label: 'Always "latest"', feedback: 'You cannot tell which code is running, and rollback means guessing.' },
            { label: 'The Git commit ID, e.g. shop-api:3f9c2ab', correct: true, feedback: 'Correct. Each build is unique and traceable to the exact code.' },
            { label: 'Today\'s date', feedback: 'Two builds on the same day would overwrite each other.' },
          ],
        },
        result: 'Every image now has a unique, traceable version.',
      },
    ],
  },
  {
    slug: 'private-network',
    title: 'Create a private network',
    mission: 'Before any server exists, build the private network it will live in, with walls between the parts.',
    concept: [
      'A virtual network is your private piece of the cloud. Only you decide what can talk to what.',
      'Subnets split the network by job: public entry, app servers, and data.',
      'Firewall rules decide which traffic can pass. Block everything, then allow only what is needed.',
    ],
    build: ['Network 10.0.0.0/16', '3 subnets: public, app, data', 'Firewall rules'],
    architecture: ['dev', 'registry', 'network'],
    steps: [
      {
        title: 'Open networking',
        screen: 'Home',
        instruction: pt('Open "Virtual networks".', 'Open "VPC".', 'Open "VPC network".'),
        why: 'Networking comes first. Servers, databases, and load balancers all need a network to live in.',
        task: openService('network'),
        result: 'Network service opened.',
      },
      {
        title: 'Create the network',
        screen: pt('Home > Virtual networks > Create virtual network', 'VPC > Your VPCs > Create VPC', 'VPC network > Create VPC network'),
        instruction: 'Name it vnet-shop (or vpc-shop) and give it the address range 10.0.0.0/16.',
        why: pt(
          '10.0.0.0/16 is a private range with 65,536 addresses. It never touches the internet. Pick it carefully: later networks must not overlap with it.',
          '10.0.0.0/16 is a private range with 65,536 addresses. A VPC lives in one region and spans all of its zones.',
          'In Google Cloud a VPC is global. You add subnets per region. Custom mode means you decide exactly which ranges exist.',
        ),
        task: {
          kind: 'form',
          tabs: pt(['Basics', 'Security', 'IP addresses', 'Tags', 'Review + create'], ['VPC settings'], ['Details', 'Subnets', 'Firewall rules']),
          fields: [
            account,
            resourceGroup,
            {
              kind: 'text',
              label: 'Name',
              placeholder: pt('vnet-shop', 'vpc-shop', 'vpc-shop'),
              accept: '^(vnet|vpc)-shop$',
              hint: pt('Type vnet-shop.', 'Type vpc-shop.', 'Type vpc-shop.'),
            },
            {
              kind: 'fixed',
              label: 'Region',
              value: usRegion,
              platforms: ['azure', 'aws'],
            },
            {
              kind: 'text',
              label: pt('IPv4 address space', 'IPv4 CIDR', 'IPv4 range (first subnet)'),
              placeholder: '10.0.0.0/16',
              accept: '^10\\.0\\.0\\.0/16$',
              platforms: ['azure', 'aws'],
              hint: 'Type 10.0.0.0/16. It gives 65,536 private addresses with room to grow.',
            },
            {
              kind: 'select',
              label: 'Subnet creation mode',
              platforms: ['gcp'],
              options: [
                { label: 'Automatic', feedback: 'Auto mode creates subnets in every region, including ones you never use. Hard to control.' },
                { label: 'Custom', feedback: 'Correct. You choose each subnet and its range.' },
              ],
              correct: 1,
              hint: 'You want full control over ranges.',
            },
          ],
          submit: pt('Review + create', 'Create VPC', 'Create'),
        },
        cli: pt(
          'az network vnet create -g rg-shop-prod -n vnet-shop \\\n  --address-prefix 10.0.0.0/16 --location eastus',
          'aws ec2 create-vpc --cidr-block 10.0.0.0/16 \\\n  --tag-specifications "ResourceType=vpc,Tags=[{Key=Name,Value=vpc-shop}]"',
          'gcloud compute networks create vpc-shop --subnet-mode=custom',
        ),
        result: 'Private network created.',
      },
      {
        title: 'Add three subnets',
        screen: pt('Home > vnet-shop > Subnets > + Subnet', 'VPC > Subnets > Create subnet', 'VPC network > vpc-shop > Add subnet'),
        instruction: 'Create the public, app, and data subnets with the ranges below.',
        why: pt(
          'Split by job. Only the load balancer sits in the public subnet. App and data subnets have no path from the internet. Each /24 gives 251 usable addresses (Azure keeps 5).',
          'Split by job. In AWS a subnet lives in one zone, so in production you make each subnet once per zone (a, b, c). We show zone a here.',
          'Split by job. In Google Cloud subnets are regional and cover all zones in that region automatically.',
        ),
        task: {
          kind: 'form',
          fields: [
            { kind: 'text', label: 'Public subnet (load balancer)', placeholder: '10.0.1.0/24', accept: '^10\\.0\\.1\\.0/24$', hint: 'Type 10.0.1.0/24.' },
            { kind: 'text', label: 'App subnet (servers)', placeholder: '10.0.2.0/24', accept: '^10\\.0\\.2\\.0/24$', hint: 'Type 10.0.2.0/24.' },
            { kind: 'text', label: 'Data subnet (Redis, database)', placeholder: '10.0.3.0/24', accept: '^10\\.0\\.3\\.0/24$', hint: 'Type 10.0.3.0/24.' },
          ],
          submit: 'Save subnets',
        },
        cli: pt(
          'az network vnet subnet create -g rg-shop-prod --vnet-name vnet-shop \\\n  -n snet-app --address-prefixes 10.0.2.0/24',
          'aws ec2 create-subnet --vpc-id vpc-0a1b2c --cidr-block 10.0.2.0/24 \\\n  --availability-zone us-east-1a',
          'gcloud compute networks subnets create snet-app \\\n  --network=vpc-shop --region=us-central1 --range=10.0.2.0/24',
        ),
        result: 'Three subnets: public 10.0.1.0/24, app 10.0.2.0/24, data 10.0.3.0/24.',
      },
      {
        title: 'Set the firewall rules',
        screen: pt('Home > Network security groups > nsg-app > Inbound security rules', 'VPC > Security groups > sg-app > Edit inbound rules', 'VPC network > Firewall > Create firewall rule'),
        instruction: 'Decide who may reach each part. Allow only what is needed.',
        why: pt(
          'A network security group (NSG) is a list of allow/deny rules on a subnet or VM. Start closed, open only the exact port to the exact source.',
          'A security group is a firewall around each server. You can say "allow from the load balancer\'s security group" instead of IP ranges.',
          'Firewall rules apply to VMs by network tag (e.g. "shop-app"). Start closed, open only the exact port to the exact source.',
        ),
        task: {
          kind: 'form',
          fields: [
            {
              kind: 'select',
              label: 'Load balancer: open to the internet on',
              options: [
                { label: '443 (HTTPS)', feedback: 'Correct. Encrypted web traffic only.' },
                { label: '22 (SSH)', feedback: 'SSH is admin access. Never open it to the internet.' },
                { label: 'All ports', feedback: 'Every open port is a door for attackers.' },
              ],
              correct: 0,
              hint: 'Users only need encrypted web traffic.',
            },
            {
              kind: 'select',
              label: 'App servers: port 3000 allowed from',
              options: [
                { label: 'Anywhere (0.0.0.0/0)', feedback: 'Attackers could skip the load balancer and hit servers directly.' },
                { label: pt('Public subnet 10.0.1.0/24 only', 'Security group sg-alb only', 'Load balancer ranges + tag shop-app only'), feedback: 'Correct. Only the load balancer can talk to the app.' },
              ],
              correct: 1,
              hint: 'Only the load balancer should reach the app.',
            },
            {
              kind: 'select',
              label: 'Database: port 5432 allowed from',
              options: [
                { label: 'Anywhere', feedback: 'Databases exposed to the internet are a top cause of data breaches.' },
                { label: 'App subnet 10.0.2.0/24 only', feedback: 'Correct. Only your app servers can reach data.' },
              ],
              correct: 1,
              hint: 'Only the app needs the database.',
            },
            {
              kind: 'select',
              label: 'Admin access (SSH)',
              options: [
                { label: 'Port 22 open to the internet', feedback: 'Bots scan for open SSH all day long.' },
                { label: 'Port 22 open to my home IP', feedback: 'Better, but IPs change and it is still a public door.' },
                { label: pt('Closed. Use Azure Bastion', 'Closed. Use Session Manager', 'Closed. Use IAP TCP forwarding'), feedback: 'Correct. Admins log in through the cloud with identity + MFA. No open port.' },
              ],
              correct: 2,
              hint: 'The safest door is no door.',
            },
          ],
          submit: 'Save rules',
        },
        cli: pt(
          'az network nsg rule create -g rg-shop-prod --nsg-name nsg-app -n allow-lb \\\n  --priority 100 --source-address-prefixes 10.0.1.0/24 \\\n  --destination-port-ranges 3000 --protocol Tcp --access Allow',
          'aws ec2 authorize-security-group-ingress --group-id sg-app \\\n  --protocol tcp --port 3000 --source-group sg-alb',
          'gcloud compute firewall-rules create allow-lb-to-app --network=vpc-shop \\\n  --allow=tcp:3000 --source-ranges=130.211.0.0/22,35.191.0.0/16 \\\n  --target-tags=shop-app',
        ),
        result: 'Firewall rules saved. Everything else is denied.',
      },
      {
        title: 'Test the walls',
        screen: pt('Home > vnet-shop > Network Watcher > Connection troubleshoot', 'VPC > Reachability Analyzer', 'Network Intelligence > Connectivity tests'),
        instruction: 'Run the connectivity tests.',
        why: 'Never trust firewall rules you have not tested. Each cloud has a tool that traces a packet and tells you which rule allowed or blocked it.',
        task: {
          kind: 'simulate',
          action: 'Run connectivity tests',
          frames: [
            { log: 'Internet → load balancer :443 — ALLOWED', tone: 'ok' },
            { log: 'Internet → app server :3000 — BLOCKED (no public IP, rule denies)', tone: 'ok' },
            { log: 'Internet → app server :22 — BLOCKED', tone: 'ok' },
            { log: 'Load balancer → app server :3000 — ALLOWED', tone: 'ok' },
            { log: 'App server → database :5432 — ALLOWED', tone: 'ok' },
            { log: 'Internet → database :5432 — BLOCKED', tone: 'ok' },
          ],
        },
        result: 'All 6 tests match the plan.',
      },
    ],
  },
  {
    slug: 'deploy-vm',
    title: 'Create a VM and deploy the container',
    mission: 'Create your first server in the app subnet and make it run your image on boot.',
    concept: [
      'A VM is a computer you rent by the hour. You pick its size, its network, and its identity.',
      'A startup script installs Docker and runs your image, so no one has to log in by hand.',
      'The VM gets an identity, so it can pull images and read secrets without passwords.',
    ],
    build: ['vm-shop-1 in the app subnet', 'Startup script', 'VM identity'],
    architecture: ['dev', 'registry', 'network', 'vm'],
    steps: [
      {
        title: 'Open the VM service',
        screen: 'Home',
        instruction: pt('Open "Virtual machines".', 'Open "EC2".', 'Open "Compute Engine".'),
        why: 'Compute is where your code actually runs.',
        task: openService('vm'),
        result: 'Compute service opened.',
      },
      {
        title: 'Basics: size and image',
        screen: pt('Home > Virtual machines > Create a virtual machine', 'EC2 > Instances > Launch an instance', 'Compute Engine > VM instances > Create an instance'),
        instruction: 'Name the VM vm-shop-1, choose Ubuntu, a small size, and SSH key login.',
        why: 'Start small. A small VM costs a few dollars a month. When traffic grows, you add more VMs (Lab 6) instead of buying one huge one.',
        task: {
          kind: 'form',
          tabs: pt(['Basics', 'Disks', 'Networking', 'Management', 'Advanced', 'Review + create'], ['Name and tags', 'Application and OS', 'Instance type', 'Key pair', 'Network settings', 'Advanced details'], ['Machine configuration', 'OS and storage', 'Networking', 'Security', 'Advanced']),
          activeTab: 0,
          fields: [
            account,
            resourceGroup,
            { kind: 'text', label: pt('Virtual machine name', 'Name', 'Name'), placeholder: 'vm-shop-1', accept: '^vm-shop-1$', hint: 'Type vm-shop-1.' },
            { kind: 'fixed', label: 'Region', value: usRegion },
            {
              kind: 'select',
              label: pt('Availability zone', 'Availability Zone', 'Zone'),
              options: [{ label: pt('Zone 1', 'us-east-1a', 'us-central1-a') }, { label: pt('Zone 2', 'us-east-1b', 'us-central1-b') }, { label: pt('Zone 3', 'us-east-1c', 'us-central1-c') }],
              correct: [0, 1, 2],
              hint: 'Any zone works for one VM.',
            },
            {
              kind: 'select',
              label: pt('Image', 'Amazon Machine Image (AMI)', 'Boot disk image'),
              options: [
                { label: 'Ubuntu Server 24.04 LTS', feedback: 'Correct. Long-term support Linux, great for containers.' },
                { label: 'Windows Server 2025', feedback: 'Costs more for a license, and your app is a Linux container.' },
              ],
              correct: 0,
              hint: 'Your container is Linux-based.',
            },
            {
              kind: 'select',
              label: pt('Size', 'Instance type', 'Machine type'),
              options: [
                { label: pt('Standard_B1ls — 1 vCPU, 0.5 GiB', 't3.nano — 2 vCPU, 0.5 GiB', 'e2-micro — 2 vCPU (shared), 1 GB'), feedback: 'Too little memory for Node.js plus Docker.' },
                { label: pt('Standard_B2s — 2 vCPU, 4 GiB', 't3.medium — 2 vCPU, 4 GiB', 'e2-medium — 2 vCPU, 4 GB'), feedback: 'Correct. Enough for one app container, cheap, and you will scale out later.' },
                { label: pt('Standard_D16s_v5 — 16 vCPU, 64 GiB', 'm7i.4xlarge — 16 vCPU, 64 GiB', 'n2-standard-16 — 16 vCPU, 64 GB'), feedback: 'You pay for 16 CPUs that sit idle. Scale out with more small VMs instead.' },
              ],
              correct: 1,
              hint: 'Small and cheap. More VMs later, not one giant VM.',
            },
            {
              kind: 'select',
              label: pt('Authentication type', 'Key pair (login)', 'SSH keys'),
              options: [
                { label: 'SSH public key', feedback: 'Correct. Keys cannot be guessed like passwords.' },
                { label: 'Password', feedback: 'Passwords can be guessed by bots.' },
              ],
              correct: 0,
              hint: 'Keys are much stronger than passwords.',
            },
          ],
          submit: pt('Next : Disks >', 'Continue', 'Continue'),
        },
        result: 'Basics saved.',
      },
      {
        title: 'Networking: private only',
        screen: pt('Home > Virtual machines > Create a virtual machine', 'EC2 > Instances > Launch an instance', 'Compute Engine > VM instances > Create an instance'),
        instruction: 'Place the VM in the app subnet with no public IP and the app firewall rules.',
        why: 'A server with a public IP is visible to the whole internet. Your VM only needs to receive traffic from the load balancer, so it stays private.',
        task: {
          kind: 'form',
          tabs: pt(['Basics', 'Disks', 'Networking', 'Management', 'Advanced', 'Review + create'], ['Name and tags', 'Application and OS', 'Instance type', 'Key pair', 'Network settings', 'Advanced details'], ['Machine configuration', 'OS and storage', 'Networking', 'Security', 'Advanced']),
          activeTab: pt(2, 4, 2),
          fields: [
            { kind: 'fixed', label: pt('Virtual network', 'VPC', 'Network'), value: pt('vnet-shop', 'vpc-shop', 'vpc-shop') },
            {
              kind: 'select',
              label: 'Subnet',
              options: [
                { label: 'public (10.0.1.0/24)', feedback: 'The public subnet is for the load balancer only.' },
                { label: 'app (10.0.2.0/24)', feedback: 'Correct. App servers live in the app subnet.' },
                { label: 'data (10.0.3.0/24)', feedback: 'The data subnet is for Redis and the database.' },
              ],
              correct: 1,
              hint: 'Servers go in the app subnet.',
            },
            {
              kind: 'select',
              label: pt('Public IP', 'Auto-assign public IP', 'External IPv4 address'),
              options: [
                { label: pt('(new) vm-shop-1-ip', 'Enable', 'Ephemeral'), feedback: 'This exposes the VM to the internet.' },
                { label: pt('None', 'Disable', 'None'), feedback: 'Correct. The VM stays private.' },
              ],
              correct: 1,
              hint: 'The load balancer will be the only public entry.',
            },
            {
              kind: 'select',
              label: pt('NIC network security group', 'Firewall (security groups)', 'Network tags'),
              options: [
                { label: pt('Basic: allow SSH (22), HTTP (80)', 'Create new: allow SSH from anywhere', 'http-server, https-server, ssh'), feedback: 'This opens admin and web ports to everyone.' },
                { label: pt('Advanced: nsg-app (from Lab 3)', 'Select existing: sg-app', 'shop-app'), feedback: 'Correct. Uses the tight rules you built in Lab 3.' },
              ],
              correct: 1,
              hint: 'Reuse the rules you made in Lab 3.',
            },
          ],
          submit: pt('Next : Management >', 'Continue', 'Continue'),
        },
        result: 'Networking saved.',
      },
      {
        title: 'Identity: give the VM its own login',
        screen: pt('Home > Virtual machines > Create a virtual machine', 'EC2 > Instances > Launch an instance', 'Compute Engine > VM instances > Create an instance'),
        instruction: 'Give the VM an identity with only the permissions it needs.',
        why: 'The VM must pull images and later read secrets. With a cloud identity it gets short-lived tokens automatically. No keys or passwords sit on the disk.',
        task: {
          kind: 'form',
          tabs: pt(['Basics', 'Disks', 'Networking', 'Management', 'Advanced', 'Review + create'], ['Name and tags', 'Application and OS', 'Instance type', 'Key pair', 'Network settings', 'Advanced details'], ['Machine configuration', 'OS and storage', 'Networking', 'Security', 'Advanced']),
          activeTab: pt(3, 5, 3),
          fields: [
            {
              kind: 'select',
              label: pt('System assigned managed identity', 'IAM instance profile', 'Service account'),
              options: [
                { label: pt('Off', 'None', 'Compute Engine default service account (Editor)'), feedback: pt('Without an identity, you would need to store a registry password on the VM.', 'Without a role, you would need to store access keys on the VM.', 'The default account has Editor rights on the whole project. Far too much power.') },
                { label: pt('On (role: AcrPull on shopregistry)', 'shop-app-role (pull from ECR only)', 'shop-app@shop-prod (Artifact Registry Reader only)'), feedback: 'Correct. The VM can pull images and nothing else.' },
              ],
              correct: 1,
              hint: 'Least privilege: only what the app needs.',
            },
          ],
          submit: pt('Next : Advanced >', 'Continue', 'Continue'),
        },
        result: 'Identity saved.',
      },
      {
        title: 'Startup script',
        screen: pt('Advanced > Custom data (cloud-init)', 'Advanced details > User data', 'Advanced > Automation > Startup script'),
        instruction: 'Fill the blanks so the VM installs Docker, logs in with its identity, and runs your image.',
        why: 'The script runs on every new VM automatically. When you have 10 VMs (Lab 6), each one sets itself up the same way. No manual work.',
        task: {
          kind: 'code',
          file: pt('cloud-init.sh', 'user-data.sh', 'startup.sh'),
          code: pt(
            lines('#!/bin/bash', 'apt-get update && apt-get install -y docker.io azure-cli', '[[0]]', 'docker run -d --restart [[1]] -p 3000:3000 \\', `  ${registryHost.azure}:[[2]]`),
            lines('#!/bin/bash', 'apt-get update && apt-get install -y docker.io awscli', '[[0]]', 'docker run -d --restart [[1]] -p 3000:3000 \\', `  ${registryHost.aws}:[[2]]`),
            lines('#!/bin/bash', 'apt-get update && apt-get install -y docker.io', '[[0]]', 'docker run -d --restart [[1]] -p 3000:3000 \\', `  ${registryHost.gcp}:[[2]]`),
          ),
          blanks: [
            {
              options: [
                { label: 'docker login -u admin -p MyP@ssw0rd', feedback: 'Anyone who can read VM settings can read this password.' },
                { label: pt('az login --identity && az acr login -n shopregistry', 'aws ecr get-login-password | docker login -u AWS --password-stdin $REGISTRY', 'gcloud auth configure-docker us-central1-docker.pkg.dev --quiet'), feedback: 'Correct. Uses the VM identity. No password in the script.' },
              ],
              correct: 1,
            },
            {
              options: [
                { label: 'always', feedback: 'Correct. If the app crashes or the VM reboots, Docker starts it again.' },
                { label: 'no', feedback: 'After a crash or reboot the app would stay down.' },
              ],
              correct: 0,
            },
            {
              options: [
                { label: 'latest', feedback: 'You would not know which version is running.' },
                { label: '3f9c2ab', feedback: 'Correct. The exact version you pushed in Lab 2.' },
              ],
              correct: 1,
            },
          ],
        },
        cli: pt(
          'az vm create -g rg-shop-prod -n vm-shop-1 --image Ubuntu2404 \\\n  --size Standard_B2s --zone 1 --vnet-name vnet-shop --subnet snet-app \\\n  --public-ip-address "" --nsg nsg-app --assign-identity \\\n  --custom-data cloud-init.sh --generate-ssh-keys',
          'aws ec2 run-instances --image-id ami-ubuntu-2404 --instance-type t3.medium \\\n  --subnet-id subnet-app-a --security-group-ids sg-app \\\n  --no-associate-public-ip-address \\\n  --iam-instance-profile Name=shop-app-role --user-data file://user-data.sh',
          'gcloud compute instances create vm-shop-1 --zone=us-central1-a \\\n  --machine-type=e2-medium --image-family=ubuntu-2404-lts-amd64 \\\n  --image-project=ubuntu-os-cloud --subnet=snet-app --no-address \\\n  --tags=shop-app --service-account=shop-app@shop-prod.iam.gserviceaccount.com \\\n  --metadata-from-file=startup-script=startup.sh',
        ),
        result: 'Startup script ready.',
      },
      {
        title: 'Create the VM',
        screen: pt('Home > Virtual machines > vm-shop-1', 'EC2 > Instances > vm-shop-1', 'Compute Engine > VM instances > vm-shop-1'),
        instruction: pt('Click Create and watch the deployment.', 'Click Launch instance and watch it start.', 'Click Create and watch it start.'),
        why: 'The cloud finds a physical host, attaches a disk and a network card, boots the OS, and runs your script. This usually takes 1–2 minutes.',
        task: {
          kind: 'simulate',
          action: pt('Create', 'Launch instance', 'Create'),
          frames: [
            { log: 'Creating OS disk (30 GB SSD)…', tone: 'info' },
            { log: 'Attaching network card in subnet app → private IP 10.0.2.4', tone: 'info' },
            { log: 'Booting Ubuntu 24.04…', tone: 'info' },
            { log: 'Startup script: installing Docker', tone: 'info' },
            { log: 'Logged in to registry with VM identity', tone: 'ok' },
            { log: 'Pulled shop-api:3f9c2ab and started container', tone: 'ok' },
            { log: 'vm-shop-1 is Running. GET http://10.0.2.4:3000/health → 200', tone: 'ok' },
          ],
        },
        result: 'vm-shop-1 is running your app on 10.0.2.4.',
      },
      {
        title: 'How will users reach it?',
        screen: 'Design decision',
        instruction: 'The VM has no public IP. Decide how users will reach the app.',
        why: 'One public entry point gives you one place for HTTPS, health checks, and security. Servers stay private behind it.',
        task: {
          kind: 'choice',
          question: 'Users cannot reach vm-shop-1. What do you add?',
          options: [
            { label: 'Give the VM a public IP', feedback: 'It works, but each server is exposed, and when it dies the site dies.' },
            { label: 'A load balancer in the public subnet', correct: true, feedback: 'Correct. That is the next lab.' },
            { label: 'Open port 3000 to the internet', feedback: 'Still needs a public IP and exposes the app directly.' },
          ],
        },
        result: 'Next: a load balancer.',
      },
    ],
  },
]
