import type { IQ } from "./interview-data";

export const BANK_F: IQ[] = [

  // ── INFERENCE & DEPLOYMENT (50) ──────────────────────────────────────────

  { id:"inf-001", group:"inference", difficulty:"medium", type:"short",
    question:"What is the difference between prefill and decode phases in LLM inference?",
    answer:"Prefill: process the entire input prompt in a single parallel forward pass — all input tokens computed at once. Compute-bound: utilises GPU FLOPS fully. Decode: generate tokens one at a time, each requires one forward pass. Memory-bandwidth bound: must load the full model weights and KV cache every step but only performs a small computation per step. Time for prefill: O(N² + N×P) for N input tokens, P parameters. Time for decode: nearly constant per token ≈ (model_size_bytes)/(memory_bandwidth GB/s).",
    explanation:"Practical implication: a 70B model on 1 A100 (80GB HBM, ~2TB/s bandwidth): decode throughput ≈ 2TB/s ÷ 140GB = 14 tokens/second single-batch. Adding more sequences to the batch doesn't help past the memory-bandwidth ceiling until FLOPS become the bottleneck. This is why batching during decode is crucial for throughput but has diminishing returns.",
    tags:["toptal","frequently-tested"] },

  { id:"inf-002", group:"inference", difficulty:"medium", type:"short",
    question:"What is quantisation and what are INT8, INT4, and GPTQ?",
    answer:"Quantisation: reduce weight precision from FP32/BF16 to lower-bit integer format. INT8 (W8A8): 8-bit weights and activations. ~2× memory reduction, 1.5-2× faster on supported hardware (LLM.int8, bitsandbytes). INT4 (W4A16): 4-bit weights, 16-bit activations. ~4× memory reduction, minimal quality loss with calibration. GPTQ (post-training quantisation for LLMs): uses calibration data + approximate second-order Hessian information to find optimal 4-bit values — best quality among 4-bit methods, one-shot (no retraining).",
    explanation:"bitsandbytes INT8: decomposes weight matrices into an 8-bit component (absorbs most of the range) and a 16-bit outlier component (for large values that would overflow INT8). Works on any LLM without calibration. GPTQ: sequential layer-by-layer quantisation minimising per-layer output error. GGUF (llama.cpp): flexible quantisation format (Q4_K_M, Q5_K_S etc.) for CPU inference. AWQ (Activation-aware Weight Quantisation): considers activation magnitude to protect important weights.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"inf-003", group:"inference", difficulty:"medium", type:"short",
    question:"What is throughput vs. latency in LLM serving and how do they trade off?",
    answer:"Throughput: tokens generated per second across all concurrent users (system-level metric). Latency: time for a single request — TTFT (time to first token) and TPOT (time per output token). Trade-off: higher batch sizes increase throughput (more efficient GPU use) but increase per-request latency (each request waits for others in the batch). Optimising for throughput: large batches, continuous batching. Optimising for latency: small batch size (or batch=1), smaller models, tensor parallelism to reduce time per step.",
    explanation:"Production: different SLAs for different use cases. Chat: p50 TTFT < 500ms, TPOT < 50ms. Batch jobs: maximise throughput (latency doesn't matter). Streaming: TTFT dominates user experience (users see first token quickly, tolerate slower completion). Adaptive batching: set a max queue time, add requests to the batch until the timeout — balances latency and throughput.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"inf-004", group:"inference", difficulty:"hard", type:"short",
    question:"What is tensor parallelism and how does it reduce inference latency for large LLMs?",
    answer:"Tensor parallelism: split individual weight matrices across multiple GPUs. For an attention layer with weight W ∈ ℝ^{d×d}: split into W_1,...,W_G column-wise. Each GPU holds d/G columns and processes the corresponding output. After the partial outputs are computed, an AllReduce sums across GPUs. Latency reduction: each GPU performs only 1/G of the compute and loads only 1/G of the weights per step — ideal for decode where compute is small but weight loading is the bottleneck.",
    explanation:"Megatron-LM style tensor parallelism: split Q,K,V attention projection along the head dimension (each GPU handles d_model/G total heads), split FFN along the intermediate dimension. Two AllReduce ops per transformer layer (one after attention, one after FFN). Efficient only when AllReduce communication << compute time — requires high-bandwidth inter-GPU connections (NVLink). Within a node: TP=4 or 8 GPUs. Across nodes: use pipeline parallelism.",
    tags:["toptal","frequently-tested"] },

  { id:"inf-005", group:"inference", difficulty:"medium", type:"short",
    question:"What is vLLM and what makes it the dominant open-source LLM serving framework?",
    answer:"vLLM (Kwon et al., 2023): open-source LLM inference server with two key innovations: (1) PagedAttention: KV cache managed as fixed-size pages (like OS virtual memory), allocated on demand. Eliminates KV cache fragmentation (from ~60% waste to <4%). (2) Continuous batching: at each decode step, completed sequences are replaced with new requests from the queue — maximises GPU utilisation. Result: 10-24× throughput improvement vs. naive static batching (HuggingFace Transformers).",
    explanation:"Additional vLLM features: speculative decoding, prefix caching (shared system prompt KV cache), tensor parallelism (multi-GPU), AWQ/GPTQ quantisation support, OpenAI-compatible API. The openAI-compatible API means any system using the OpenAI SDK can switch to a self-hosted vLLM endpoint by changing one URL.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"inf-006", group:"inference", difficulty:"medium", type:"short",
    question:"What is speculative decoding and what speedup can be expected?",
    answer:"Speculative decoding: a small draft model generates k token candidates (1 forward pass each — cheap). The large target model verifies all k tokens in one parallel forward pass (attending causally across the k positions). Accept token i if target agrees with draft; on first disagreement, sample from the corrected distribution, reject remaining. Guaranteed same output distribution as pure target sampling. Speedup: depends on the speculation acceptance rate α. If α=0.8 and k=4: expected accepted tokens per step = (1-0.8^5)/(1-0.8) = 4.1. Each target model step produces ~4 tokens instead of 1 — ~4× speedup.",
    explanation:"Draft model choices: a much smaller version of the same model (LLaMA-3-8B drafts for LLaMA-3-70B), Medusa heads (parallel FC heads on the target model itself — no separate model), or n-gram lookup (match recently generated n-grams as draft — zero cost, works for repetitive text). In production: 2-3× typical speedup for chat applications with 70-90% acceptance rates.",
    tags:["toptal","frequently-tested"] },

  { id:"inf-007", group:"inference", difficulty:"hard", type:"short",
    question:"What is model compilation (torch.compile / TensorRT) and how does it accelerate inference?",
    answer:"PyTorch eager mode: each op is a Python-level dispatch — overhead per op, suboptimal kernel fusion. torch.compile (PyTorch 2.0, Triton backend): traces the computation graph, fuses multiple ops into custom CUDA kernels (e.g., LayerNorm + GELU + linear → single kernel), eliminates Python overhead. 20-40% speedup for transformer inference. TensorRT (NVIDIA): compiles PyTorch/ONNX model to TensorRT engine — aggressive kernel fusion, FP16/INT8 quantisation, layer fusion, constant folding. 3-5× speedup vs. eager mode, especially for fixed input shapes.",
    explanation:"Flash Attention is itself a custom fused kernel: Q,K,V → attention output in one pass through SRAM, avoiding materialising the N×N matrix. This is the most impactful single kernel fusion for LLMs. Triton (OpenAI): Python-like language for writing custom CUDA kernels without C++ — used to implement Flash Attention, fused softmax, and other LLM-critical kernels.",
    tags:["toptal"] },

  { id:"inf-008", group:"inference", difficulty:"medium", type:"short",
    question:"What is the KV cache size for a given model and context length?",
    answer:"KV cache size = 2 × n_layers × n_kv_heads × d_head × context_length × bytes_per_float. For LLaMA-3-8B (BF16): 2 × 32 × 8 × 128 × 128k × 2 bytes = 2 × 32 × 8 × 128 × 131072 × 2 ≈ 17.2 GB for 128k context. For LLaMA-3-70B at 128k: 2 × 80 × 8 × 128 × 131072 × 2 ≈ 43 GB. The KV cache can be larger than the model itself (140GB for 70B) for long contexts.",
    explanation:"KV cache growing with context_length is why long-context serving is challenging. Solutions: (1) GQA (fewer KV heads — LLaMA-3 uses 8 KV heads not 64). (2) KV cache quantisation to INT8 or INT4 (2-4× reduction). (3) SnapKV: identify and cache only the 'important' KV entries (20-30% of full cache). (4) StreamingLLM: keep only attention sink tokens + sliding window KV.",
    tags:["toptal"] },

  { id:"inf-009", group:"inference", difficulty:"medium", type:"short",
    question:"What is TTFT (time to first token) and why does it matter?",
    answer:"TTFT: the elapsed time from the user submitting a query until the first token of the response appears. Determines perceived responsiveness — users expect TTFT < 1-2 seconds for interactive use. TTFT depends on: prefill time (processing the prompt), queuing time (waiting for GPU), network latency. Optimisation: prefix caching (avoid re-prefilling cached system prompts), chunked prefill (don't block decode with long prefill), smaller context (shorter prompt reduces prefill time), faster interconnects.",
    explanation:"Time per output token (TPOT): time for each subsequent generated token after the first. TPOT determines the generation speed experienced by the user during streaming. Total time = TTFT + (n_tokens - 1) × TPOT. For a 200-token response: TTFT=500ms + 199 × 20ms = 4.5 seconds. Streaming makes this acceptable — users see tokens appearing progressively.",
    tags:["toptal","andela"] },

  { id:"inf-010", group:"inference", difficulty:"hard", type:"short",
    question:"What is disaggregated prefill-decode and why is it emerging for large-scale serving?",
    answer:"Standard serving: same GPU handles both prefill (compute-intensive) and decode (memory-bandwidth-intensive). They compete for resources — a long prefill from one request delays decode for all others. Disaggregated serving: separate machines/GPUs for prefill and decode. Prefill nodes: optimised for compute (high FLOPS, FP16 tensor cores). Decode nodes: optimised for memory bandwidth. KV cache transferred from prefill node to decode node after prefill completes. Each phase independently scaled and optimised.",
    explanation:"Used by: Google (TPU serving), Alibaba (DualPipe), MoonCake. Requires fast interconnect for KV cache transfer (InfiniBand or NVLink across nodes). Benefit: eliminates prefill-decode interference, enables separate autoscaling of each phase (prefill scales with input token volume, decode scales with output token volume), reduces TTFT and improves TPOT simultaneously.",
    tags:["toptal"] },

  { id:"inf-011", group:"inference", difficulty:"medium", type:"short",
    question:"What is model sharding across GPUs and what are the three types used in LLM serving?",
    answer:"Data parallelism (DP): replicate the full model on each GPU, split different requests across GPUs. Scales throughput, requires model to fit on one GPU. Tensor parallelism (TP): split weight matrices within each layer across GPUs — reduces per-GPU memory, reduces per-step latency. Requires high-bandwidth interconnect (NVLink). Pipeline parallelism (PP): assign different layers to different GPUs — processes micro-batches in a pipeline. Lower bandwidth requirement, introduces pipeline bubble latency.",
    explanation:"Serving a 70B model that doesn't fit on one A100 (80GB, model=140GB BF16): use TP=2 across 2 GPUs — each GPU holds 70GB of weights and communicates every layer. TP=2 on NVLink: communication ≈ 10-15% of compute time — efficient. TP=2 across nodes (InfiniBand): communication ≈ 30-50% — less efficient. In practice: TP within a node (up to 8 GPUs per NVLink switch), PP across nodes.",
    tags:["toptal"] },

  { id:"inf-012", group:"inference", difficulty:"medium", type:"short",
    question:"What is continuous batching (iteration-level scheduling) and why does it improve GPU utilisation?",
    answer:"Static batching: a batch of N requests runs from start to completion. If some requests finish early, GPU idles waiting for the longest request. At N=10 requests with lengths [10, 10, 10, ..., 1000]: 9 requests complete at step 10, GPU processes steps 11-1000 with only 1 sequence — 90% waste. Continuous batching: at each step, completed sequences are immediately removed and new requests from the queue are inserted. Batch composition changes per step but batch size stays constant. GPU is always fully loaded.",
    explanation:"orca (2022, the original paper), vLLM (implementation). Implementation: at each decode step, check which sequences have reached EOS or max_length. Remove them, add new sequences from the queue (their KV cache starts fresh). Requires PagedAttention for efficient KV cache management when batch composition changes. Result: 10-24× throughput improvement for variable-length workloads.",
    tags:["toptal","frequently-tested"] },

  { id:"inf-013", group:"inference", difficulty:"medium", type:"short",
    question:"What is dynamic quantisation vs. static quantisation and which is used for LLMs?",
    answer:"Static quantisation: calibrate quantisation parameters (scale, zero-point) on a calibration dataset before deployment. Activations are quantised with fixed scales — fast at inference, no overhead. Dynamic quantisation: compute quantisation parameters at runtime based on each activation's actual range. More accurate (adapts to input distribution) but slower (quantisation overhead per step). For LLMs: GPTQ and AWQ are static PTQ methods. bitsandbytes INT8 (LLM.int8) uses a hybrid: weights are static INT8, activations are dynamic (computed per-token).",
    explanation:"The motivation for dynamic activation quantisation in LLMs: LLM activations have 'outlier' features (a few dimensions have very large values, most are small). Static quantisation with a large scale quantises the small values too coarsely — large accuracy loss. Dynamic quantisation adapts the scale per token/row — handles outliers without sacrificing precision for the majority.",
    tags:["toptal"] },

  { id:"inf-014", group:"inference", difficulty:"medium", type:"short",
    question:"What is the 'model serving' stack and what are the layers?",
    answer:"Layer 1 — Compute infrastructure: GPUs/TPUs, memory, networking. Layer 2 — Model runtime: CUDA kernels, cuBLAS, Flash Attention, quantisation kernels. Layer 3 — Inference framework: vLLM, TensorRT-LLM, SGLang, TGI — handles batching, scheduling, KV cache, multi-GPU parallelism. Layer 4 — Serving API: FastAPI/Triton Inference Server — HTTP endpoints, request routing, authentication, rate limiting. Layer 5 — Load balancing / gateway: route requests across multiple inference servers, implement SLAs, handle failover.",
    explanation:"OpenAI-compatible API: most inference frameworks implement the same API surface as OpenAI (POST /v1/chat/completions, POST /v1/embeddings) — any client using the OpenAI SDK can switch to a self-hosted server by changing the base_url. This enables: cost reduction (self-host open-source model), privacy (no external API calls), and customisation.",
    tags:["toptal","andela"] },

  { id:"inf-015", group:"inference", difficulty:"medium", type:"short",
    question:"What is structured pruning for inference efficiency and how is it different from unstructured pruning?",
    answer:"Unstructured pruning: set individual weights to zero (arbitrary sparsity pattern). Reduces model size but doesn't help with standard dense matrix operations on GPU — sparse matrix multiply requires special sparse kernels that are often slower than dense ops for moderate sparsity (<90%). Structured pruning: remove entire neurons, attention heads, or layers. Results in a smaller dense model that runs faster on standard hardware: pruning 30% of attention heads → 30% fewer attention computations, still uses dense matmul.",
    explanation:"Attention head pruning: measure each head's importance (gradient magnitude, Taylor expansion, or random probing — Michel et al., 2019). Prune unimportant heads. LLM results: 70-80% of heads can be pruned with <5% quality loss. Combined with layer dropping: remove less critical transformer layers. LLM-Pruner (2023): removes entire neurons + attention heads + layers with calibration recovery fine-tuning.",
    tags:["toptal"] },

  { id:"inf-016", group:"inference", difficulty:"medium", type:"short",
    question:"What is the difference between online and offline inference for LLMs?",
    answer:"Online inference: real-time, latency-sensitive. User sends a request, expects response in <1-5 seconds. Requirements: low TTFT, low TPOT, high availability. Architecture: continuously running inference servers with load balancers. Offline inference: batch processing with no real-time requirement. Run inference on millions of documents, embeddings, or generation tasks overnight. Requirements: high throughput, low cost per token. Architecture: batch jobs on spot instances, can restart on failure. vLLM offline mode: process large queues with maximum throughput.",
    explanation:"Offline inference patterns: embedding entire knowledge bases (RAG ingestion), generating training data for other models, bulk document summarisation, classification at scale. For offline: use maximum batch size that fits in memory, sort inputs by length (avoids padding waste), use quantised models (4-bit for maximum throughput), run on spot instances with checkpointing.",
    tags:["toptal","andela"] },

  { id:"inf-017", group:"inference", difficulty:"hard", type:"short",
    question:"What is CUDA graph capture and how does it speed up decode?",
    answer:"During decode (batch_size=1 or small batch): each forward pass has the same computation graph — all ops are the same, only the data (new token, KV cache) changes. Without CUDA graphs: Python overhead for launching each CUDA kernel per step. CUDA graph capture: run the forward pass once to record a CUDA graph (a fixed graph of CUDA operations). Subsequently, replay the graph by feeding new inputs directly to GPU memory — eliminates all Python/CUDA launch overhead. Results in 2-4× faster decode for small batch sizes.",
    explanation:"Limitation: CUDA graphs are captured for a specific batch size and input shape. Need separate graphs for different batch sizes (e.g., capture for batch=1,2,4,8,...,64). vLLM uses CUDA graph capture for small batches during decode. Not applicable during prefill (variable input shapes). Flash Attention compatible with CUDA graphs.",
    tags:["toptal"] },

  { id:"inf-018", group:"inference", difficulty:"medium", type:"short",
    question:"What is model distillation for inference and how is it different from pruning and quantisation?",
    answer:"Pruning: remove parts of the existing model (weights, neurons, layers). Quantisation: reduce the precision of existing weights. Distillation: train a smaller new model (student) to mimic the larger model (teacher). The student starts from scratch (or from a pretrained checkpoint) — it's a genuinely different, smaller model. Inference benefit: the student is 2-10× smaller, faster, and cheaper to serve. Quality: well-distilled students can approach 95-97% of teacher quality. DistilBERT: 40% smaller, 60% faster, 97% of BERT quality.",
    explanation:"LLM distillation in 2026: distillation from frontier models (GPT-4, Claude 3 Opus) to smaller open-source models has become common. Phi-3 (3.8B) achieves near-GPT-3.5 quality via training on GPT-4-generated synthetic data. Speculative decoding combines all three: the small draft model (distilled from the large one) is fast due to its size and may be further quantised.",
    tags:["toptal","andela"] },

  { id:"inf-019", group:"inference", difficulty:"medium", type:"short",
    question:"What is batching in LLM inference and what are the batch size trade-offs?",
    answer:"Batching: process multiple requests in the same forward pass. Benefits: matrix multiply efficiency — batch of N requests uses the same weight loads as batch of 1 but performs N× more computations (amortises the memory bandwidth cost). Batch_size=1: fully memory-bandwidth-bound (the arithmetic intensity — FLOPS/byte — is very low). Batch_size=256: approaches the model's peak FLOPS utilisation. Trade-offs: larger batch → higher throughput, higher per-request latency (must wait for the batch to fill), more memory needed for activations and KV caches.",
    explanation:"Arithmetic intensity (FLOPS/byte) for decode: model_params × 2 (multiply+add) per token / (model_params × bytes_per_param). For BF16: 2/2 = 1 FLOP/byte — extremely low. The A100 peak is ~300 FLOPS/byte compute-to-memory ratio. So batch=1 decode is bandwidth-limited; batch=300 would approach compute saturation. Continuous batching dynamically targets the optimal batch size.",
    tags:["toptal","andela"] },

  { id:"inf-020", group:"inference", difficulty:"medium", type:"short",
    question:"What is the difference between beam search and sampling for LLM generation in production?",
    answer:"Beam search: maintain B partial sequences (beams), expand each, keep top-B by cumulative log-probability. Deterministic, finds high-probability completions, tends toward safe generic text. Problems at scale: computationally expensive (B forward passes conceptually), prone to length bias (shorter sequences), generates repetitive text. Sampling: stochastic, diverse, creative. Temperature/top-p for control. Problems: may generate low-quality outliers. In production LLMs (ChatGPT, Claude): use sampling with temperature=0.7, top-p=0.9 — empirically better user experience than beam search.",
    explanation:"Why beam search fails for dialogue: it finds the statistically most likely response, which is often the safest/most generic answer ('I don't know', 'It depends'). Sampling allows more informative, diverse responses. For structured generation (constrained JSON output, translation): beam search still used because exact adherence to format is more important than diversity.",
    tags:["toptal","andela"] },

  { id:"inf-021", group:"inference", difficulty:"hard", type:"short",
    question:"What is int4/fp8 mixed precision inference and which hardware supports it?",
    answer:"FP8 (E4M3 or E5M2): 8-bit floating point with 4 or 5 exponent bits and 3 or 2 mantissa bits. Supported natively on H100 (Hopper) and H200 GPUs. Provides 2× memory reduction vs BF16 with near-BF16 quality. INT4: 4-bit integer, 4× memory reduction vs BF16. Mixed precision: weights in INT4 (smallest memory), accumulate in FP16/BF16 (higher precision). Most LLM serving frameworks: FP8 for weights + activations on H100 (NVFP8 mode in TensorRT-LLM), INT4/INT8 on older GPUs (A100, A10G).",
    explanation:"FP8 training (H100): NVIDIA has shown FP8 training of LLMs with comparable quality to BF16 (requires careful treatment of gradient outliers). FP8 inference: nearly lossless for INT8-quality models. The hardware support for FP8 in H100 enables 2× the throughput of BF16 at the same memory — critical for cost reduction at scale.",
    tags:["toptal"] },

  { id:"inf-022", group:"inference", difficulty:"medium", type:"short",
    question:"What is TorchServe / Triton Inference Server and when would you use each?",
    answer:"TorchServe (PyTorch/AWS): serves PyTorch models. Handles: model loading, multi-model serving, REST/gRPC APIs, model versioning, batch aggregation. Best for: PyTorch-specific models, single-model production serving, integration with AWS SageMaker. Triton Inference Server (NVIDIA): framework-agnostic (PyTorch, ONNX, TensorRT, TF). Advanced batching (dynamic batching, sequence batching for LLMs), model ensembles (chain models), GPU sharing, Prometheus metrics. Best for: mixed-framework environments, performance-critical serving, NVIDIA GPU deployment.",
    explanation:"For LLMs specifically: neither TorchServe nor Triton fully handles LLM-specific optimisations out of the box. vLLM and TGI (Text Generation Inference by HuggingFace) are LLM-native serving frameworks with PagedAttention, continuous batching, and speculative decoding. TGI is used in HuggingFace Inference Endpoints; vLLM is dominant for self-hosted open-source LLM deployment.",
    tags:["toptal","andela"] },

  { id:"inf-023", group:"inference", difficulty:"medium", type:"short",
    question:"What is prompt caching and how does it reduce cost for LLM APIs?",
    answer:"Prompt caching: when the same prefix (system prompt + few-shot examples + document) is used across many requests, the provider caches the KV cache for that prefix. Subsequent requests using the same prefix skip the prefill computation for the cached portion — saving compute and billing. Anthropic API: cached tokens cost 10% of input token price ($0.03/Mtok cached vs $0.30/Mtok uncached for Claude 3.5 Sonnet). OpenAI: similar automatic caching for shared prefixes. Savings: if system prompt = 1000 tokens and 10k requests/day: caching saves 90% of 10M tokens/day.",
    explanation:"Using prompt caching effectively: (1) Keep the system prompt at the beginning (always the same prefix). (2) Put the few-shot examples before the variable user message. (3) Order: system prompt → examples → retrieved context → user message. Cache hits occur when the prefix up to the cache point is byte-for-byte identical. Temperature and other sampling params don't affect caching.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"inf-024", group:"inference", difficulty:"medium", type:"short",
    question:"What is the effect of sequence length on LLM inference cost?",
    answer:"Input tokens (prompt): each token adds O(N) cost to the prefill (attention grows quadratically, but is parallelisable). Total prefill compute ≈ 2×P×N (where P = model params). Doubling input length ≈ doubles prefill cost but doesn't affect decode speed per token. Output tokens (generated): each token requires one full decode step — cost linear in number of output tokens. KV cache grows with total processed tokens (input + output). Cost: proportional to total tokens processed = input + output tokens (most API pricing models).",
    explanation:"Flash Attention reduces the memory of the N×N matrix during prefill to O(N) but doesn't reduce the O(N²) compute. For long inputs (32k+ tokens), prefill becomes the latency bottleneck. Chunked prefill can overlap this with decode. For billing: OpenAI charges input and output tokens separately (output = 3-5× more expensive per token, reflecting the sequential decode cost).",
    tags:["toptal","andela"] },

  { id:"inf-025", group:"inference", difficulty:"medium", type:"short",
    question:"What is a model ensemble in inference and when does it help?",
    answer:"Model ensemble: run multiple models on the same input and combine predictions. For classification: majority vote or average probabilities. For generation: select the output from the model that scores highest (e.g., via a reward model) or use self-consistency (majority vote on the final answer across samples). Benefits: lower variance, improved accuracy (especially for edge cases), better calibration. Costs: N× inference compute and latency.",
    explanation:"Self-consistency ensembling (Wang et al., 2022): sample 5-10 reasoning chains from the same model (with temperature > 0), take the majority vote on the final answer. No multiple models — just multiple samples. Achieves 5-15% improvement on GSM8K, MATH over greedy decoding. The 'free' ensemble via repeated sampling is particularly useful for agentic tasks where a single high-quality answer justifies the compute.",
    tags:["toptal"] },

  { id:"inf-026", group:"inference", difficulty:"medium", type:"short",
    question:"What is AWQ (Activation-Aware Weight Quantisation) and how does it improve on GPTQ?",
    answer:"GPTQ: minimises per-layer quantisation error using calibration data and Hessian information — good quality but treats all weights equally. AWQ observation: not all weights are equally important — weights that multiply large activations have larger impact. AWQ: find the 1% of weights that correspond to the largest activation magnitudes; don't quantise these weights (keep in full precision); quantise the rest to INT4. The key insight: by protecting ~1% of important weights, quality is preserved almost as well as keeping all weights in full precision.",
    explanation:"AWQ also scales weights before quantisation using per-channel scaling factors derived from the activation statistics — reduces quantisation error for the important weights. AWQ produces models that are slightly larger than GPTQ (due to protected weights) but faster to quantise (no Hessian computation) and often higher quality for LLMs. AutoAWQ library: simple API, supports Llama, Mistral, Qwen, all major architectures.",
    tags:["toptal"] },

  { id:"inf-027", group:"inference", difficulty:"medium", type:"short",
    question:"What is FP16 vs BF16 and which is preferred for LLM inference?",
    answer:"FP16 (IEEE 754 half-precision): 1 sign + 5 exponent + 10 mantissa bits. Range: ±65504. BF16 (Brain Float 16): 1 sign + 8 exponent + 7 mantissa bits. Range: same as FP32 (±3.4×10³⁸). Same memory (2 bytes). BF16 advantages: no overflow for LLM weights/activations that can have large values (FP16 overflows above ~65k). No gradient scaling needed in training. Preferred for LLM training and inference on GPUs that support it (A100, H100 natively, V100 software emulation).",
    explanation:"FP16 inference: use loss scaling during training to avoid underflow/overflow. FP16 models may have numerical instability on very deep models. BF16 inference: numerically safe, no special treatment needed, matches training precision. For older GPUs without BF16 Tensor Cores (V100, P100): FP16 with careful model training. Modern deployment: always BF16 when hardware supports it.",
    tags:["toptal","andela"] },

  { id:"inf-028", group:"inference", difficulty:"medium", type:"short",
    question:"What is FlashDecoding and how does it speed up long-context inference?",
    answer:"Standard FlashAttention: parallelises across batch and head dimensions. During decode (batch=1, one new token), the attention computation over the KV cache is over a sequence of N keys and values — parallelisation across N is limited. FlashDecoding (Dao et al., 2023): parallelises the attention computation across the K/V sequence dimension during decode. Splits the KV cache into chunks, each processed by different GPU threads; partial results are accumulated. This increases GPU utilisation during long-context decode where the standard FlashAttention is memory-bandwidth-bound with low parallelism.",
    explanation:"FlashDecoding speedup: 8-50× for single-batch decode with long context (8k-100k tokens). Critical for: chatbots with long conversation histories, document Q&A, code completion for large codebases. Integrated in FlashAttention-2 and FlashAttention-3 as the default decode mode. Also enables Flash-Decoding++ with additional optimisations for MHA and GQA.",
    tags:["toptal"] },

  { id:"inf-029", group:"inference", difficulty:"medium", type:"short",
    question:"What is LoRA inference and how can LoRA adapters be served efficiently?",
    answer:"LoRA inference: add ΔW = AB to the frozen base weight W for each adapted layer. Naive: load base model + all LoRA adapters — separate forward pass per adapter (doesn't share compute). Efficient multi-LoRA serving (S-LoRA, Punica): serve many fine-tuned LoRA variants from a single base model instance in the same batch. Each request carries a LoRA adapter ID. The base model computation is shared (one copy of base weights); LoRA deltas are batched as a sparse tensor — GPU kernel computes base forward pass + LoRA delta simultaneously for all adapters in the batch.",
    explanation:"S-LoRA (Sheng et al., 2023): stores 1000s of LoRA adapters in CPU/GPU memory, dynamically swaps the needed adapters into the GPU for each batch. The base model parameters are loaded once and shared. This enables serving thousands of fine-tuned variants of a model without needing thousands of GPU replicas — fundamental for multi-tenant LLM serving (one model per enterprise customer, one GPU cluster).",
    tags:["toptal"] },

  { id:"inf-030", group:"inference", difficulty:"medium", type:"short",
    question:"What is the role of ONNX in model deployment?",
    answer:"ONNX (Open Neural Network Exchange): a standard format for representing neural network models as a computation graph. Models trained in PyTorch, TF, JAX can be exported to ONNX and deployed with any ONNX-compatible runtime: ONNX Runtime (cross-platform, CPU/GPU), TensorRT (NVIDIA, high performance), OpenVINO (Intel CPU/GPU). Benefits: framework-agnostic deployment, hardware portability, runtime optimisations (operator fusion, layout optimisation). Process: PyTorch → torch.onnx.export() → model.onnx → OnnxRuntime / TensorRT.",
    explanation:"ONNX for LLMs: exporting LLMs to ONNX enables deployment on non-PyTorch runtimes (edge devices, embedded, CPU servers). Microsoft's ONNX Runtime has specialised optimisations for transformer inference (fused attention, GQA support). LLaMA ONNX models can run on ONNX Runtime Mobile for edge deployment. Limitation: dynamic shapes (variable sequence length) require careful ONNX export configuration.",
    tags:["toptal","andela"] },

  { id:"inf-031", group:"inference", difficulty:"easy", type:"mcq",
    options:["Compute the full N×N attention matrix in HBM (slow memory)",
             "Tile the Q, K, V matrices to keep computations in SRAM (fast memory)",
             "Reduce the number of attention heads to lower memory",
             "Skip attention for tokens with low importance scores"],
    question:"What does Flash Attention do to reduce memory usage during transformer inference?",
    answer:"Tile the Q, K, V matrices to keep computations in SRAM (fast memory)",
    explanation:"Flash Attention avoids materialising the full N×N attention matrix in HBM (high-bandwidth memory, which is slow relative to SRAM). By tiling and computing attention block-by-block entirely within the GPU's SRAM, it achieves the same result without ever writing the large intermediate matrix to HBM. This reduces memory from O(N²) to O(N) and speeds up attention 2-4×.",
    tags:["turing","andela"] },

  { id:"inf-032", group:"inference", difficulty:"medium", type:"short",
    question:"What is the memory hierarchy in GPU inference and why does it matter for LLMs?",
    answer:"GPU memory hierarchy (fastest to slowest, smallest to largest): Registers (per thread, ~256KB per SM, ~TB/s bandwidth) → L1 cache/SRAM (~1MB per SM, ~10TB/s) → L2 cache (~32MB, ~4TB/s on A100) → HBM (80GB A100, ~2TB/s). LLM inference is memory-bandwidth bound at decode: each step loads the full model weights from HBM (~140GB for 70B BF16) → ~70ms on A100 at 2TB/s. Flash Attention keeps attention computations in SRAM (no HBM for N×N matrix). CUDA graphs: reuse existing GPU operations without CPU re-launch overhead.",
    explanation:"Memory bandwidth is the critical resource for LLM inference at small batch sizes. Compute (TFLOPS) is secondary until batch sizes are large enough to saturate computation. This is why model size and batch size are the primary knobs for LLM inference throughput, not the raw FLOPS of the GPU.",
    tags:["toptal"] },

  { id:"inf-033", group:"inference", difficulty:"medium", type:"short",
    question:"What is KV cache quantisation and how does it reduce memory during long-context inference?",
    answer:"KV cache quantisation: store the K and V tensors in lower precision (INT8, FP8, INT4) instead of BF16. KV cache memory = 2 × n_layers × n_kv_heads × d_head × seq_len × bytes. INT8 reduces this 2×, INT4 reduces 4×. Methods: KIVI (2024): per-channel quantisation of K/V to INT2 or INT4. Gear (2024): quantise most tokens to INT4 but keep recent tokens in full precision (recent tokens are more likely to be attended to, need higher precision). Quality loss: minimal at INT8, small at INT4 with per-channel quantisation.",
    explanation:"Practical impact for LLaMA-3-70B at 128k context: BF16 KV cache = 43GB. INT8 KV cache = 21GB. INT4 = 10.5GB. This determines how many concurrent long-context requests can be served simultaneously. KV cache quantisation is now integrated in vLLM (fp8 kv cache) and TensorRT-LLM. Combined with GQA (fewer KV heads), can achieve 8-16× memory reduction for the KV cache.",
    tags:["toptal"] },

  { id:"inf-034", group:"inference", difficulty:"hard", type:"short",
    question:"What is the LM-Deployment challenge for edge devices and what techniques address it?",
    answer:"Edge deployment constraints: limited memory (4-16GB), limited compute (CPU or mobile GPU), no FP16/BF16 hardware support, thermal limits. Techniques: (1) Aggressive quantisation: INT4/INT2 weights (llama.cpp GGUF on Mac, Android). (2) Model pruning: remove layers, attention heads, neurons. (3) Distillation: use a small student model (Phi-3-mini, Gemma-2-2B). (4) Selective layer offloading: keep hot layers in GPU, cold layers in RAM. (5) Speculative decoding with tiny draft models. (6) Depth reduction: remove every other layer in small-model variants.",
    explanation:"llama.cpp enables running quantised LLMs on CPU (Mac M1/M2, Windows, Linux). Q4_K_M (4-bit mixed quantisation): Llama-3-8B runs at ~3 tokens/sec on an M2 MacBook Pro — usable for local inference. Apple MLX framework: optimised for Apple Silicon with Metal GPU backend. The 2024 trend: small but powerful models (Phi-3-mini 3.8B, Gemma-2-2B) that can run locally with acceptable quality.",
    tags:["toptal"] },

  { id:"inf-035", group:"inference", difficulty:"medium", type:"short",
    question:"What is the cost per token for LLM API calls and how do you estimate production costs?",
    answer:"Typical costs (2025): GPT-4o: $2.50/1M input tokens, $10.00/1M output tokens. GPT-4o-mini: $0.15/$0.60. Claude 3.5 Sonnet: $3.00/$15.00. Claude 3 Haiku: $0.25/$1.25. Self-hosted Llama-3-70B on 2×H100 ($5/hr): ~1000 tokens/sec → $5/3.6M tokens ≈ $1.4/1M tokens (at full utilisation). Cost estimation: monthly_tokens = queries_per_day × 365/12 × avg_tokens_per_query. Annual cost = monthly_tokens × 12 × price_per_million / 1,000,000.",
    explanation:"Optimisation strategies: (1) Use cheaper models for simple queries (routing: classify query complexity, use mini for simple, full for hard). (2) Cache common queries (exact match or semantic cache). (3) Reduce prompt size (compression, selective context). (4) Batch offline queries. (5) Self-host for high-volume workloads. Break-even for self-hosting vs API: typically at 10M+ tokens/day for a 7B model.",
    tags:["toptal","andela"] },

  { id:"inf-036", group:"inference", difficulty:"medium", type:"short",
    question:"What is a semantic cache for LLM responses and how does it work?",
    answer:"Exact cache: return a cached response if the query is identical byte-for-byte. Hit rate: very low for diverse queries. Semantic cache: embed the query, search a cache of past queries by cosine similarity. If a past query is similar enough (threshold, e.g., 0.95), return the cached response. Hit rate: much higher for queries that are semantically similar but worded differently. Reduces LLM calls by 20-60% for applications with many similar queries (FAQ bots, documentation assistants).",
    explanation:"GPTCache (open-source): implements semantic caching with pluggable embedding models and vector stores. Implementation: (1) For each new query, embed it. (2) Search cache for similar past queries. (3) If similarity > threshold, return cached response. (4) Otherwise, call LLM and store (query_embedding, response) in cache. TTL: expire cache entries based on time or on source document updates.",
    tags:["toptal","andela"] },

  { id:"inf-037", group:"inference", difficulty:"medium", type:"short",
    question:"What is multi-GPU inference scaling efficiency and what limits it?",
    answer:"Ideal scaling: 2 GPUs = 2× throughput (linear). In practice: tensor parallelism introduces AllReduce communication per layer. At TP=2: communication overhead ≈ 5-15% → ~90% scaling efficiency. At TP=8: communication overhead ≈ 20-40% → ~70-80% efficiency. Beyond one NVLink domain (>8 GPUs same node): inter-node communication via InfiniBand → 200Gb/s vs NVLink's 900GB/s → communication becomes dominant → efficiency drops to 50-70%.",
    explanation:"Scaling LLM inference: within-node tensor parallelism scales well (NVLink). Cross-node pipeline parallelism: each node holds some layers, passes activations to the next — communication is smaller (one layer's activation, not the full model), scales to many nodes. Data parallelism: most efficient but requires model to fit on one node. Best practice: TP within node, DP across nodes for throughput scaling.",
    tags:["toptal"] },

  { id:"inf-038", group:"inference", difficulty:"medium", type:"short",
    question:"What is text-to-image diffusion model inference pipeline and what determines its speed?",
    answer:"Diffusion inference: start with Gaussian noise x_T, iteratively denoise: x_{t-1} = denoise(x_t, t, conditioning). Each step is one forward pass through the UNet/DiT. Number of steps: 50 (DDPM), 20 (DDIM), 4-8 (SDXL Turbo, LCM-LoRA). Speed determinants: (1) Number of denoising steps (linear). (2) Image resolution (quadratic in attention). (3) UNet size. Optimisations: fewer steps (DDIM, DPM-Solver++), smaller UNet (distillation via consistency training), compile UNet with torch.compile, quantise UNet to FP16/INT8.",
    explanation:"Stable Diffusion XL with 20 DDIM steps: ~5 seconds on A10G GPU. With SDXL Turbo (4 steps): ~1 second. With torch.compile + xFormers attention: 2× speedup. Distill the UNet with consistency model (CM): 1-4 steps at high quality. For video generation: multiply steps × video_frames × spatial attention — very expensive (Sora-scale requires massive compute).",
    tags:["toptal","andela"] },

  { id:"inf-039", group:"inference", difficulty:"hard", type:"short",
    question:"What is MoE inference efficiency and what are the challenges in serving Mixture of Experts models?",
    answer:"MoE inference: only k/E of the FFN parameters are active per token (e.g., k=2, E=8 → 25% active FFN). But all E expert weights must be in GPU memory for routing. Challenge: expert routing causes irregular memory access patterns — the GPU cannot predict which expert each token needs, making batching across experts irregular. Low utilisation: if batch has 8 tokens and E=8 experts, each expert handles 1 token on average — the expert's FFN is run for 1 token (poor parallelism) vs. the attention which is batched over all 8 tokens.",
    explanation:"Expert load imbalance during inference: for a diverse batch, each expert may get 0-5 tokens — very uneven. Solutions: expert replication (replicate the most-loaded experts on additional GPUs), capacity factor (each expert has a max token capacity, overflow is routed to the next expert). MoE inference is typically 30-50% slower per token than a dense model of the same active parameter count due to routing overhead and expert load imbalance.",
    tags:["toptal"] },

  { id:"inf-040", group:"inference", difficulty:"medium", type:"short",
    question:"What is inference monitoring and what metrics should you track in production?",
    answer:"Key metrics: (1) Throughput: tokens/second, requests/second. (2) Latency: TTFT p50/p95/p99, TPOT p50/p95. (3) GPU utilisation: should be >80% for throughput-optimised serving. (4) GPU memory utilisation: track KV cache fill rate. (5) Error rate: model errors, timeout rate, OOM errors. (6) Cost per token: total GPU cost / tokens generated. (7) Queue depth: requests waiting for a GPU slot. (8) Cache hit rate: prefix cache and semantic cache efficiency.",
    explanation:"Alerting: TTFT p99 > SLA → add capacity or reduce batch size. GPU OOM → reduce max batch size or max context length. Throughput drop → check for upstream traffic changes or model degradation. Cost spike → check for unusual request patterns (very long contexts). Tools: Prometheus + Grafana for metrics, structured logging for per-request tracing. vLLM exposes OpenMetrics endpoint for direct Prometheus scraping.",
    tags:["toptal","andela"] },

  { id:"inf-041", group:"inference", difficulty:"medium", type:"short",
    question:"What is AutoGPTQ and how does it make LLM quantisation accessible?",
    answer:"AutoGPTQ: Python library implementing GPTQ quantisation for any GPTQ-compatible LLM architecture. Workflow: (1) Load full-precision model. (2) Run calibration dataset (C4, WikiText-2, ~128 sequences). (3) Layer-by-layer GPTQ quantisation (minimise output error using Hessian). (4) Save quantised model in safe-tensors format. The resulting 4-bit model has minimal quality degradation and loads in ~1/4 the memory. Compatible with HuggingFace Transformers for inference.",
    explanation:"AutoGPTQ vs bitsandbytes: GPTQ requires calibration (few minutes), produces better quality at same bitwidth, static (no runtime overhead). bitsandbytes INT8: no calibration, dynamic quantisation, slightly lower quality, higher runtime overhead. In 2026: most quantised LLMs on HuggingFace Hub use AutoGPTQ (GPTQ) or llama.cpp (GGUF) format. GPTQ on H100: can use exllamaV2 backend for significantly faster decoding.",
    tags:["toptal"] },

  { id:"inf-042", group:"inference", difficulty:"medium", type:"short",
    question:"What is request queuing and what strategies are used for LLM serving?",
    answer:"Request queuing: new requests are buffered when the GPU is at capacity. Strategies: (1) FCFS (First Come First Served): simple, fair, but long requests block short ones (convoy effect). (2) Shortest Job First (SJF): serve shortest requests first — but sequence lengths are unknown before generation. (3) Preemption: pause a long request to serve a short urgent one (save/restore KV cache to CPU). (4) Priority queues: premium users get lower latency. (5) Longest Queue Drops: drop oldest queued requests when queue is too long (better than blocking indefinitely).",
    explanation:"In vLLM: default FCFS scheduling. Preemption via KV cache swapping to CPU: when a new high-priority request arrives, swap a low-priority request's KV cache to CPU RAM, free the GPU memory, admit the high-priority request. The preempted request is re-queued. CPU-GPU bandwidth (~16-32 GB/s on PCIe) limits how fast swapping can occur.",
    tags:["toptal"] },

  { id:"inf-043", group:"inference", difficulty:"medium", type:"short",
    question:"What is the difference between LLM serving on cloud vs on-premise and when does each make sense?",
    answer:"Cloud (AWS, GCP, Azure, API): no capital cost, instant scaling, managed infrastructure, pay per token/hour. Makes sense for: variable traffic, early stage, compliance with SOC2/GDPR possible with private endpoints. On-premise (own GPU servers): high upfront cost ($50k-$1M for H100 cluster), but lower per-token cost at high volume, full data privacy, no API limits. Makes sense for: high volume (>50M tokens/day), strict data privacy (no third-party API), custom model that can't be deployed on cloud.",
    explanation:"Break-even analysis (rough): AWS g5.xlarge (A10G, 24GB) at $1/hr: ~100 tokens/sec for 7B → $10/1M tokens. OpenAI GPT-4o-mini: $0.60/1M output tokens. Self-hosting is cheaper for simple tasks only if running LLaMA-3-8B at high utilisation. For GPT-4-class capability: self-hosting an 8×H100 cluster ($2M upfront, $30/hr) breaks even vs GPT-4 API at ~500M tokens/day.",
    tags:["toptal","andela"] },

  { id:"inf-044", group:"inference", difficulty:"medium", type:"short",
    question:"What is a model registry and what role does it play in ML deployment?",
    answer:"Model registry: a centralised store for trained model artefacts with versioning, metadata, and lifecycle management. Stores: model weights, ONNX exports, configuration files, performance metrics, training run ID, dataset version. Lifecycle: registered → staged → production → archived. Enables: reproducible deployments (exact model version), rollback (revert to previous version if new model degrades), A/B testing (route % of traffic to new version), compliance audit trail.",
    explanation:"Tools: MLflow Model Registry (open-source), AWS SageMaker Model Registry, Google Vertex AI Model Registry, HuggingFace Hub (for LLMs). Best practices: tag models with evaluation metrics before promoting to production, require approval for production promotion, store all hyperparameters and training metadata with each version. The registry is the bridge between ML training and production serving infrastructure.",
    tags:["toptal","andela"] },

  { id:"inf-045", group:"inference", difficulty:"medium", type:"short",
    question:"What is shadow mode deployment and why is it used for LLMs?",
    answer:"Shadow mode: run the new model in parallel with the production model for the same requests. Both process the request; only the production model's response is returned to the user. The shadow model's responses are logged for offline evaluation — no user impact. Uses: (1) Validate new model quality before exposing to users. (2) Compare latency of new model at production scale. (3) Collect enough data for a meaningful A/B test decision. (4) Detect unexpected failure modes in real traffic distribution.",
    explanation:"Shadow mode for LLMs: send 10% of live traffic to both current model and the new model. Log both responses. Use LLM-as-judge or human evaluation offline to compare. Only promote the new model if quality is statistically significantly better and latency SLAs are met. The shadow model must handle the same traffic rate as production — requires adequate GPU capacity for the shadow fleet.",
    tags:["toptal"] },

  { id:"inf-046", group:"inference", difficulty:"medium", type:"short",
    question:"What is the SGLang (Structured Generation Language) framework for LLM inference?",
    answer:"SGLang (LMSYS, 2024): an inference framework and programming language for efficient LLM programs. Features: (1) RadixAttention: prefix sharing in the KV cache across requests and within a single request's multiple generations (reuse the same prompt prefix for different generation branches). (2) Constrained decoding for structured generation. (3) Batching across multiple parallel generations within one 'program' (e.g., generate 4 candidates in parallel). (4) Multi-call LLM programs with full backend optimisation.",
    explanation:"RadixAttention (the core insight): represent the KV cache as a prefix tree (trie). Requests sharing a prefix share the same KV cache memory. This works not just across requests (like vLLM prefix caching) but within a single request — if you fork the generation (explore multiple paths), the shared prefix is cached. Useful for: tree-of-thought, self-consistency sampling, few-shot chains.",
    tags:["toptal"] },

  { id:"inf-047", group:"inference", difficulty:"hard", type:"short",
    question:"What is the roofline model and how does it diagnose LLM inference bottlenecks?",
    answer:"Roofline model: visualise whether a compute kernel is compute-bound or memory-bandwidth-bound. X-axis: arithmetic intensity (FLOPS/byte). Y-axis: FLOPS/sec achieved. Roof: max achievable FLOPS, limited by min(peak_compute, peak_bandwidth × arithmetic_intensity). LLM decode (batch=1): 2 FLOPS per weight byte loaded → arithmetic intensity = 1 FLOP/byte. A100 peak: 312 TFLOPS (BF16) but bandwidth roof: 2TB/s → 2TFLOPS at AI=1. Decode is memory-bandwidth bound. LLM prefill (large batch): AI = batch_size — at batch=256, fully compute-bound.",
    explanation:"Using the roofline: if measured throughput = bandwidth_roof × arithmetic_intensity, you're memory-bound. If measured throughput = peak_compute, you're compute-bound. To improve: if memory-bound → reduce model size (quantise), increase batch size, increase memory bandwidth (NVLink). If compute-bound → more GPUs, better FLOPS efficiency (FP8), reduce model FLOPs (pruning, MoE).",
    tags:["toptal"] },

  { id:"inf-048", group:"inference", difficulty:"medium", type:"short",
    question:"What is a serving rate limit and how do you implement one for LLM APIs?",
    answer:"Rate limiting: restrict how many requests or tokens a client can consume per time window. Types: (1) RPM (requests per minute). (2) TPM (tokens per minute) — more meaningful for LLMs since request cost varies with token count. (3) Concurrent request limit. Implementation: token bucket algorithm — a bucket fills at rate R tokens/sec, each request consumes tokens proportional to its token count. If bucket empty, reject with 429. Sliding window log: track timestamps of past requests, count those within the window.",
    explanation:"LLM-specific considerations: the token count is known only after generation (output tokens are unknown upfront). Solution: rate limit on input tokens + estimated output, then adjust post-response. Or: use a conservative estimate and credit unused tokens. Redis is the standard backend for distributed rate limiting across multiple inference servers (token counter in Redis, atomic decrement with Lua script).",
    tags:["toptal","andela"] },

  { id:"inf-049", group:"inference", difficulty:"medium", type:"short",
    question:"What is embedding inference vs. generation inference and how do they differ in hardware requirements?",
    answer:"Embedding inference: encode a text into a fixed-size vector (BERT, E5, OpenAI embeddings). One forward pass, no decoding loop. Compute: O(N²) for attention (sequence length N), parallelisable over batch. Memory: relatively small models (0.3-7B) — fits on a single GPU. High batch throughput: can process 1000s of texts per second. Generation inference: autoregressively generate tokens one at a time. Memory-bandwidth bound. Large models (7-405B). KV cache grows. Much lower throughput (tokens/second) vs. embedding.",
    explanation:"For RAG ingestion: embedding 1M documents (avg 200 tokens each) on a single A10G GPU (E5-large at batch=256): ~2000 chunks/sec, ~28 hours total. For 10M documents: ~280 hours — need multiple GPUs in parallel. This is why large-scale RAG ingestion uses distributed batch processing across many GPU nodes, not a single server.",
    tags:["toptal","andela"] },

  { id:"inf-050", group:"inference", difficulty:"medium", type:"short",
    question:"What is the difference between synchronous and asynchronous LLM inference and when should each be used?",
    answer:"Synchronous: the client sends a request and blocks until the full response is ready. Simple, easy to implement. Good for: short responses, non-interactive use cases, batch jobs. Latency = TTFT + full generation time. Asynchronous (streaming): the server starts sending tokens as they're generated (SSE or WebSocket). Client receives and displays tokens progressively. Good for: interactive chat (users see text appearing immediately — better UX), long responses, latency-sensitive applications. Implementation: server sends text/event-stream with delta chunks.",
    explanation:"Async in production: use async HTTP (aiohttp, httpx) for the LLM API call — don't block the event loop. Server-Sent Events (SSE): lightweight, HTTP compatible, one-directional server→client streaming. WebSocket: bidirectional, more complex but enables client-side interruption. OpenAI API: stream=True parameter. HuggingFace TGI: uses SSE. vLLM: OpenAI-compatible streaming via FastAPI async generators.",
    tags:["toptal","andela"] },
];
