// iq-bank-i.ts  — Platform-confirmed questions + critical gaps
// Sources: toptal.com/machine-learning/interview-questions (official),
//          Glassdoor Turing ML Engineer reviews, Andela HackerRank format,
//          Turing.com/interview-questions/machine-learning (official)
import type { IQ } from "./interview-data";

export const BANK_I: IQ[] = [

  // ── TOPTAL OFFICIAL PUBLISHED QUESTIONS (toptal.com/machine-learning/interview-questions) ──

  { id:"tp-001", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is stratified cross-validation and when should we use it? [Toptal official question]",
    answer:"Stratified k-fold: each fold preserves the exact class ratio of the full dataset. In regular k-fold, random splits can accidentally put most rare-class examples in one fold, making validation scores unreliable. Use it whenever the dataset is imbalanced (one class < 20-30% of data) or when any class is small enough that a fold might contain zero examples of it. In sklearn: StratifiedKFold(n_splits=5). Always use stratified for classification; regular k-fold is fine for regression.",
    explanation:"Example: 1000 samples, 5% positive class = 50 positives. With k=5, regular k-fold might put 0 positives in a fold by chance. Stratified ensures exactly 10 positives in every fold. This matters enormously for F1, AUC-PR, and recall metrics.",
    tags:["toptal","confirmed-toptal","frequently-tested","core"] },

  { id:"tp-002", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"Why do ensemble models typically have higher scores than individual models? [Toptal official question]",
    answer:"Three reasons: (1) Variance reduction — if N uncorrelated models each have error ε, the average error is ε/√N (by law of large numbers). (2) Bias reduction (boosting) — sequentially correcting residuals progressively lowers systematic error. (3) Error diversity — individual models make different mistakes; voting or averaging cancels out idiosyncratic errors. The key condition: individual models must be better than random AND their errors must not be perfectly correlated. This is why Random Forest adds feature randomness — to decorrelate the trees.",
    explanation:"The ideal ensemble: diverse models that are each decent. A homogeneous ensemble of identical models offers zero benefit. In practice: XGBoost ≈ gradient boosting on bias, Random Forest ≈ variance reduction via bagging. Stacking combines both strategies: trains a meta-learner on out-of-fold predictions of diverse base models.",
    tags:["toptal","confirmed-toptal","frequently-tested"] },

  { id:"tp-003", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What are some factors that explain the recent success and rise of deep learning? [Toptal official question]",
    answer:"Three converging factors: (1) Data: internet-scale labelled datasets (ImageNet, Common Crawl) — deep learning requires far more data than classical ML. (2) Compute: GPU acceleration made training 100-1000× faster; modern LLMs need clusters of thousands of GPUs. (3) Algorithms: ReLU solved vanishing gradients, dropout regularised, batch norm stabilised training, residual connections enabled depth, attention enabled sequence modelling. Additional: open-source frameworks (PyTorch, TensorFlow) democratised access; pre-trained models enabled transfer learning.",
    explanation:"No single factor alone would have worked: GPUs without data = undertrained models; data without GPUs = too slow to train; GPUs + data without algorithmic advances (BatchNorm, ReLU, residuals) = unstable training of deep networks. The 2012 AlexNet breakthrough combined all three: CNN on ImageNet with CUDA.",
    tags:["toptal","confirmed-toptal","frequently-tested"] },

  { id:"tp-004", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is data augmentation? Can you give examples for images, text, and tabular data? [Toptal official question]",
    answer:"Data augmentation: artificially expands training data by applying label-preserving transformations. Image: random crop, horizontal flip, colour jitter, rotation, CutMix, MixUp, Gaussian noise. Text/NLP: back-translation (EN→FR→EN), synonym replacement, random deletion, EDA (Easy Data Augmentation), paraphrasing with LLMs. Tabular: SMOTE (interpolate minority class), Gaussian noise to continuous features, random swap of similar-class rows. Purpose: reduces overfitting, improves generalisation, reduces data requirements, makes model robust to real-world variations.",
    explanation:"CutMix (2019): paste a random rectangle from another image and linearly interpolate labels. MixUp: blend two images and labels linearly. Both outperform basic augmentation on ImageNet. For LLMs: few-shot generation of synthetic training examples is now the dominant augmentation strategy.",
    tags:["toptal","confirmed-toptal","frequently-tested"] },

  { id:"tp-005", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What are convolutional neural networks and where can we use them? [Toptal official question]",
    answer:"CNNs exploit spatial locality: a filter (small weight matrix) slides across the input, computing a dot product at each position — learning to detect local features (edges, textures, shapes). Key properties: (1) Weight sharing — same filter applied everywhere, far fewer parameters than FC layers. (2) Translation equivariance — detected feature moves with the object in the image. (3) Hierarchical features — early layers: edges; mid-layers: textures; deep layers: objects. Use cases: image classification (ResNet), object detection (YOLO), segmentation (U-Net), medical imaging, video understanding, audio (spectrograms treated as 2D images), time series (1D conv).",
    explanation:"Modern vision transformers (ViT) have partially replaced CNNs for image classification but CNNs still dominate: (1) object detection (YOLO, DETR), (2) segmentation (U-Net for medical), (3) mobile/edge (MobileNet, EfficientNet), (4) any task where spatial locality matters and training data is limited.",
    tags:["toptal","confirmed-toptal","frequently-tested"] },

  { id:"tp-006", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is model extrapolation and what are its pitfalls? [Toptal official question]",
    answer:"Extrapolation: making predictions for inputs outside the range of the training data distribution. Pitfalls: (1) ML models are interpolators — they learn the function inside the training distribution, not outside it. (2) Linear regression extrapolates linearly even when the true function is non-linear. (3) Tree-based models return the prediction of the closest leaf — constant extrapolation. (4) Neural networks produce overconfident wrong predictions outside training distribution. (5) The model has no signal (no training examples) to learn from in the extrapolation region.",
    explanation:"Safe extrapolation requires domain knowledge or explicit uncertainty estimation. Bayesian models quantify uncertainty: their confidence intervals widen outside the training range. Gaussian processes are the classical tool for principled extrapolation. In production: detect distribution shift (input monitoring) to flag likely extrapolation at inference time.",
    tags:["toptal","confirmed-toptal"] },

  { id:"tp-007", group:"evaluation", difficulty:"medium", type:"short",
    question:"How can we visualise more than three dimensions of data in a single chart? [Toptal official question]",
    answer:"Techniques: (1) Dimensionality reduction: PCA → 2D/3D scatter plot (linear, fast); t-SNE → 2D/3D (non-linear, preserves local structure, best for clusters); UMAP (faster than t-SNE, better global structure). (2) Additional visual channels: colour for 4th dimension, size for 5th, shape for 6th, animation for 7th. (3) Parallel coordinates plot: each axis is a dimension, each line is a sample — handles 10+ dimensions. (4) Scatter plot matrix (SPLOM): pairwise 2D plots for all dimension pairs. (5) Heatmap: correlation matrix for many features.",
    explanation:"t-SNE vs UMAP: t-SNE: best for small-medium datasets, clusters clearly separated; UMAP: faster (O(N log N) vs O(N²)), better preserves global structure, supports new point projection. For production dashboards with many features: PCA for overview, UMAP for cluster exploration, parallel coords for feature relationships.",
    tags:["toptal","confirmed-toptal"] },

  { id:"tp-008", group:"training", difficulty:"medium", type:"short",
    question:"What is data validation in the ML pipeline and why is it critical? [Toptal official question]",
    answer:"Data validation: systematically checking that incoming data matches expected schema, statistics, and distributions before it enters the model. Checks: (1) Schema: correct column names, dtypes, no new/missing columns. (2) Statistics: mean, std, min, max within expected ranges. (3) Distribution: no significant shift from training distribution (using KS test or Jensen-Shannon divergence). (4) Completeness: no unexpected nulls. (5) Referential integrity: categories match expected set. Why critical: 'garbage in, garbage out' — a model serving corrupted data produces silent failures (wrong predictions with high confidence).",
    explanation:"Tools: TensorFlow Data Validation (TFDV), Great Expectations, Evidently AI. In production MLOps: run data validation as the first step in every inference pipeline. If validation fails, raise an alert and fallback to a safe default rather than serving bad predictions silently.",
    tags:["toptal","confirmed-toptal"] },

  // ── TURING CONFIRMED QUESTIONS (Glassdoor + turing.com/interview-questions/machine-learning) ──

  { id:"tu-001", group:"evaluation", difficulty:"medium", type:"short",
    question:"You are building a rare anomaly detector (0.1% positive rate). How do you choose between Precision, Recall, and F1? [Turing confirmed]",
    answer:"Context determines the choice: (1) High recall priority (catch all anomalies, false alarms okay): use Recall = TP/(TP+FN). Example: medical screening, security alerts. (2) High precision priority (every flagged anomaly must be real, missing some is okay): use Precision = TP/(TP+FP). Example: surgical intervention, costly investigation. (3) Balance: F1 = harmonic mean of P and R — good general balance metric. (4) For rare classes: prefer PR-AUC (area under precision-recall curve) over ROC-AUC. ROC-AUC is optimistic on imbalanced data because TN is large. PR-AUC focuses on the minority class only.",
    explanation:"Key insight: with 0.1% positives, predicting all-negative gives 99.9% accuracy, 0% recall, undefined precision. Never use accuracy for this. Always ask: what is the cost of a false negative vs. false positive? That cost ratio determines whether to optimise Recall, Precision, or their harmonic mean.",
    tags:["turing","confirmed-turing","frequently-tested"] },

  { id:"tu-002", group:"neural-networks", difficulty:"medium", type:"short",
    question:"Describe CNN architecture and explain how pooling layers affect spatial dimensionality and translation invariance. [Turing confirmed]",
    answer:"CNN architecture: Input → [Conv → Activation → Pool] × N → FC → Output. Spatial dimensionality: each conv layer with valid padding shrinks output by (kernel-1). Max pooling with 2×2 kernel, stride 2 halves each spatial dimension: 224×224 → 112×112. After 5 such pools: 224 → 7. Translation invariance from pooling: max pooling returns the maximum in each 2×2 region regardless of exact position — a feature detected slightly left or right of its expected position still produces the same max. Translation equivariance from conv: the feature map shifts proportionally with the object. Pooling converts equivariance into invariance.",
    explanation:"Stride in conv layers also reduces spatial size: output_size = ⌊(W - F)/S⌋ + 1. Global Average Pooling collapses the entire feature map to a single value per channel — maximum translation invariance, used in ResNet classification head. Modern architectures sometimes skip pooling, using strided convolutions instead (more learnable, similar downsampling).",
    tags:["turing","confirmed-turing","frequently-tested"] },

  { id:"tu-003", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"Explain the bias-variance tradeoff. How do L1 and L2 regularisation mathematically affect model weights? [Turing confirmed]",
    answer:"Total error = Bias² + Variance + Irreducible noise. High complexity → low bias, high variance (overfit). Low complexity → high bias, low variance (underfit). L1 (Lasso): loss = L + λΣ|wᵢ|. Gradient: ∂/∂wᵢ = λ·sign(wᵢ). Sign of gradient is constant — pushes small weights to exactly zero (soft-thresholding). Produces sparse models. L2 (Ridge): loss = L + λΣwᵢ². Gradient: 2λwᵢ — proportional to weight magnitude. Large weights shrink fast; small weights shrink slowly. Never exactly zero. Effect: L2 shrinks all weights smoothly; L1 eliminates irrelevant features.",
    explanation:"Geometric intuition: L1 constraint is a diamond — optimal solution often at a corner (one weight = 0). L2 constraint is a sphere — optimal solution on the surface but never at a point where any coordinate is exactly zero. This is why Lasso performs feature selection and Ridge does not.",
    tags:["turing","confirmed-turing","frequently-tested"] },

  { id:"tu-004", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"How do you handle missing values in a Pandas DataFrame? What are the trade-offs of each approach? [Turing coding round]",
    answer:"df.isnull().sum() — find missing counts. Approaches: (1) Drop: df.dropna() — simple, but loses data; bad if >5% missing. (2) Mean/median/mode fill: df.fillna(df.mean()) — fast, but distorts variance. Median is robust to outliers. Use mode for categoricals. (3) Forward/backward fill: df.fillna(method='ffill') — appropriate for time series. (4) KNN imputation: fills with weighted mean of k-nearest neighbours — best quality, slow O(N²). (5) Model-based: train a model to predict missing values — best for MCAR/MAR data. (6) Indicator column: add binary flag for 'was_missing' alongside the fill — lets the model learn the missingness pattern.",
    explanation:"MCAR (Missing Completely At Random): safe to drop rows. MAR (Missing At Random conditional on observed data): imputation appropriate. MNAR (Missing Not At Random): the missingness itself is informative — always add indicator column. In sklearn: SimpleImputer, KNNImputer, IterativeImputer (MICE algorithm).",
    tags:["turing","confirmed-turing"] },

  { id:"tu-005", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"Write NumPy code to normalise a tensor to zero mean and unit variance. Why is this different from min-max scaling? [Turing coding round]",
    answer:"import numpy as np\n\ndef standardise(X: np.ndarray) -> np.ndarray:\n    mean = X.mean(axis=0)       # per-feature mean\n    std = X.std(axis=0) + 1e-8  # avoid division by zero\n    return (X - mean) / std\n\nMin-max scaling: (x - min)/(max - min) → output ∈ [0,1]. Sensitive to outliers (one extreme value compresses all others). Standardisation: (x - μ)/σ → mean=0, std=1. More robust to outliers. Outliers still exist but don't compress the scale. Use standardisation when: outliers are likely, input to gradient-based models (equal step sizes per feature), PCA (variance-based). Use min-max when: bounded input required (image pixels 0-255→0-1), neural net with sigmoid/tanh outputs.",
    explanation:"Critical bug to avoid: fit the scaler on training data only, apply to test: scaler = StandardScaler(); scaler.fit(X_train); X_test_scaled = scaler.transform(X_test). If you fit on X_test, you have data leakage.",
    tags:["turing","confirmed-turing"] },

  { id:"tu-006", group:"training", difficulty:"medium", type:"short",
    question:"Why is NumPy vectorisation faster than a Python loop? Quantify the difference. [Turing coding round]",
    answer:"NumPy vectorisation: underlying C/Fortran code, SIMD (Single Instruction Multiple Data) CPU instructions process multiple floats simultaneously, no Python interpreter overhead per element, contiguous memory layout (cache-friendly). Python loop: each iteration: bytecode interpretation, dynamic type checking, boxing/unboxing Python objects — ~50-100 operations per element vs 1-2 for NumPy. Typical speedup: 10-200× for simple element-wise operations. Example: sum of 10M elements — Python loop: ~3 seconds; np.sum: ~10ms — 300× faster.",
    explanation:"When to use Python loops anyway: (1) When logic can't vectorise (complex conditionals, string ops). (2) Small arrays (<1000 elements) where overhead is negligible. (3) Debugging: loops are easier to step through. Pandas: df.apply(lambda row: ..., axis=1) is slow — prefer df['col'].str.method() or np.where for element-wise ops.",
    tags:["turing","confirmed-turing"] },

  { id:"tu-007", group:"training", difficulty:"medium", type:"short",
    question:"Write a SQL query to compute a 7-day rolling average of daily sales. [Turing SQL round]",
    answer:"SELECT\n    date,\n    sales,\n    AVG(sales) OVER (\n        ORDER BY date\n        ROWS BETWEEN 6 PRECEDING AND CURRENT ROW\n    ) AS rolling_7day_avg\nFROM daily_sales\nORDER BY date;\n\nKey: ROWS BETWEEN 6 PRECEDING AND CURRENT ROW includes 7 rows (current + 6 before). RANGE BETWEEN would use date values, not row counts — important distinction for irregular time series. For partitioned rolling average (per product): add PARTITION BY product_id before ORDER BY.",
    explanation:"Common SQL ML interview patterns: (1) ROW_NUMBER() OVER (PARTITION BY group ORDER BY score DESC) for ranking. (2) LAG(value, 1) OVER (ORDER BY date) for day-over-day change. (3) NTILE(4) OVER (ORDER BY score) for quartiles. (4) PERCENT_RANK() for percentile scores. SQL window functions are heavily tested at Turing for data analyst and ML engineer roles.",
    tags:["turing","confirmed-turing"] },

  { id:"tu-008", group:"classical-ml", difficulty:"medium", type:"short",
    question:"Implement gradient descent for linear regression from scratch in Python. [Turing/Andela coding round]",
    answer:"import numpy as np\n\ndef linear_regression_gd(X, y, lr=0.01, n_iters=1000):\n    n, d = X.shape\n    w = np.zeros(d)\n    b = 0.0\n    for _ in range(n_iters):\n        y_pred = X @ w + b\n        error = y_pred - y\n        dw = (2/n) * X.T @ error   # gradient w.r.t. weights\n        db = (2/n) * error.sum()   # gradient w.r.t. bias\n        w -= lr * dw\n        b -= lr * db\n    return w, b\n\nMSE loss = (1/n)Σ(ŷ - y)². Gradient ∂MSE/∂w = (2/n)Xᵀ(Xw + b - y). The factor 2/n: 2 from derivative of squared error, 1/n for averaging over samples.",
    explanation:"Common interview follow-ups: (1) How to add L2 regularisation? Add λw to dw. (2) Why normalise features first? Unnormalised features → different gradient scales → slow convergence. (3) How to detect convergence? Track loss change between iterations; stop when |Δloss| < 1e-6.",
    tags:["turing","andela","confirmed-turing","frequently-tested"] },

  { id:"tu-009", group:"classical-ml", difficulty:"medium", type:"short",
    question:"Implement K-Means clustering from scratch in Python. [Turing/Andela coding round]",
    answer:"import numpy as np\n\ndef kmeans(X, k, n_iters=100):\n    # Initialise centroids (random samples)\n    idx = np.random.choice(len(X), k, replace=False)\n    centroids = X[idx].copy()\n    labels = np.zeros(len(X), dtype=int)\n    for _ in range(n_iters):\n        # Assign: each point → nearest centroid\n        dists = np.linalg.norm(X[:, None] - centroids[None], axis=2)  # (N, K)\n        new_labels = dists.argmin(axis=1)\n        if (new_labels == labels).all():  # converged\n            break\n        labels = new_labels\n        # Update: recompute centroids\n        centroids = np.array([X[labels == j].mean(axis=0) for j in range(k)])\n    return labels, centroids",
    explanation:"Key edge cases to mention: (1) Empty cluster: if a centroid gets no points, reinitialise it. (2) K-Means++ init: choose centroids with probability proportional to squared distance from existing centroids — much better than random. (3) Run multiple times, keep lowest inertia. (4) Convergence: labels don't change OR centroid movement < threshold.",
    tags:["turing","andela","confirmed-turing"] },

  { id:"tu-010", group:"ml-fundamentals", difficulty:"easy", type:"short",
    question:"What is the difference between shallow copy and deep copy in Python? Why does it matter for ML? [Turing MCQ topic]",
    answer:"Shallow copy: copy.copy(obj) — creates a new container, but elements inside are references to the same objects. Deep copy: copy.deepcopy(obj) — recursively copies all nested objects. ML relevance: (1) If you shallow-copy a numpy array X_train and modify it, you corrupt the original. (2) Deep copying model weights before fine-tuning preserves the original model. (3) Pandas: df.copy() is a deep copy (default); slice assignment on views modifies original (use .copy() to avoid SettingWithCopyWarning). Practical: always use .copy() for NumPy arrays and Pandas DataFrames before modifying.",
    explanation:"Python default: list2 = list1 creates a reference (not a copy at all). list2 = list1[:] or list(list1) creates a shallow copy. For nested structures (list of lists, dicts), always deepcopy if you'll modify. NumPy: arr2 = arr1.copy() is always a deep copy.",
    tags:["turing","confirmed-turing"] },

  { id:"tu-011", group:"classical-ml", difficulty:"medium", type:"short",
    question:"Find the contiguous subarray with the largest sum (Kadane's Algorithm). [Turing coding challenge]",
    answer:"def max_subarray(nums):\n    max_sum = current_sum = nums[0]\n    for n in nums[1:]:\n        current_sum = max(n, current_sum + n)  # extend or restart\n        max_sum = max(max_sum, current_sum)\n    return max_sum\n\nTime: O(N). Space: O(1). Key insight: at each position, the optimal subarray ending here is either just the current element (restart) or the best previous subarray extended by current element. This is a DP problem — current_sum is the dp state.",
    explanation:"Turing coding pattern: they ask classic algorithm problems that have ML relevance. Kadane's pattern appears in: sequence alignment, finding the best window of training data, profit maximisation in sequential decisions. Variant: also return the start/end indices of the maximum subarray.",
    tags:["turing","confirmed-turing"] },

  { id:"tu-012", group:"evaluation", difficulty:"medium", type:"short",
    question:"Calculate Pandas percentile scores and normalise a column. [Turing Pandas coding round]",
    answer:"import pandas as pd\nimport numpy as np\n\n# Percentile rank (0-100)\ndf['score_percentile'] = df['score'].rank(pct=True) * 100\n\n# Z-score normalisation\ndf['score_zscore'] = (df['score'] - df['score'].mean()) / df['score'].std()\n\n# Min-max to [0, 1]\ndf['score_minmax'] = (df['score'] - df['score'].min()) / (df['score'].max() - df['score'].min())\n\n# Robust scaling (IQR-based, outlier resistant)\nq25, q75 = df['score'].quantile([0.25, 0.75])\ndf['score_robust'] = (df['score'] - q25) / (q75 - q25)",
    explanation:"Interview follow-up: which scaling to use when? Z-score: gradient descent, PCA, SVM. Min-max: bounded inputs (image pixels, neural net outputs). Percentile rank: non-parametric, handles any distribution. Robust: when outliers are present and you can't remove them.",
    tags:["turing","confirmed-turing"] },

  // ── ANDELA CONFIRMED FORMAT — HackerRank DSA + Applied ML ──

  { id:"an-001", group:"classical-ml", difficulty:"medium", type:"short",
    question:"Implement a binary search that returns the insertion position if the target is not found. [Andela HackerRank style]",
    answer:"def search_insert(nums, target):\n    lo, hi = 0, len(nums)\n    while lo < hi:\n        mid = (lo + hi) // 2\n        if nums[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid\n    return lo  # insertion position\n\nTime: O(log N). Space: O(1). This is bisect_left from Python's bisect module. ML relevance: binary search over hyperparameter ranges, finding optimal threshold, lookup in sorted feature arrays.",
    explanation:"Andela HackerRank: 45-60 minutes for 2-3 problems, ~60-70% pass threshold. Typical difficulty: easy-medium LeetCode. Other common patterns: string manipulation, hash map (two-sum), stack-based (balanced parentheses), simple DP (fibonacci, coin change).",
    tags:["andela","confirmed-andela"] },

  { id:"an-002", group:"ml-fundamentals", difficulty:"easy", type:"short",
    question:"What is the difference between correlation and causation? Give a concrete ML example. [Andela technical interview]",
    answer:"Correlation: A and B move together statistically. Causation: A directly causes B. They are not equivalent. Classic spurious correlation: ice cream sales correlate with drowning deaths — both caused by hot weather, not each other. ML example: a model trained on hospital data finds high temperature and pneumonia correlate with survival — because critically ill patients with those symptoms get more aggressive treatment (selection bias/confounding). Causation requires: randomised controlled experiments, instrumental variables, difference-in-differences, or causal DAGs (Pearl's framework). ML models learn correlations, not causation.",
    explanation:"Why it matters in production: a model recommending an action (ad targeting, treatment, pricing) implicitly assumes causation. If it only learned correlation, the action may have zero effect. Solution: A/B tests to establish causation before acting on model recommendations.",
    tags:["andela","confirmed-andela","frequently-tested"] },

  { id:"an-003", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is selection bias and how can it affect a trained ML model? [Andela technical interview]",
    answer:"Selection bias: the training data is not a representative sample of the population the model will be applied to. Examples: (1) Medical model trained on hospital patients — doesn't represent healthy population. (2) Search ranking model trained on clicked results — never learns from non-clicked good results (position bias). (3) Loan approval model trained on approved loans — can't learn from rejected applicants. Consequence: model systematically fails on the under-represented segment. Fix: importance weighting, collect data from the missing segment, counterfactual reasoning.",
    explanation:"Historical hiring model example: trained on accepted candidates (selected by biased humans), the model learns and amplifies the human bias. The feedback loop worsens over time. Solution: collect data on rejected candidates' outcomes (A/B test some rejections), or use counterfactual models that estimate what would have happened.",
    tags:["andela","confirmed-andela","frequently-tested"] },

  { id:"an-004", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is the ROC curve and how do you use it to choose a decision threshold? [Andela confirmed topic]",
    answer:"ROC (Receiver Operating Characteristic): plot TPR (recall) vs FPR (1-specificity) at every possible classification threshold. AUC-ROC: area under the curve — 0.5 = random, 1.0 = perfect. Threshold selection: (1) Equal-cost: choose threshold at knee of ROC curve (maximise TPR-FPR distance = Youden's J). (2) Cost-sensitive: if FP costs more than FN, choose threshold with lower FPR even at lower TPR. (3) Use precision-recall curve instead when positive class is very rare.",
    explanation:"Code: fpr, tpr, thresholds = sklearn.metrics.roc_curve(y_true, y_scores). Optimal threshold: idx = np.argmax(tpr - fpr); best_threshold = thresholds[idx]. In production: choose threshold in a business context — medical: maximise recall even at lower precision; spam filter: maximise precision (users hate false positives).",
    tags:["andela","confirmed-andela","frequently-tested"] },

  // ── GAP-FILLING: Confirmed missing topics across all platforms ──

  { id:"gp-001", group:"training", difficulty:"hard", type:"short",
    question:"What is the vanishing gradient problem in deep networks and name three solutions with their mechanisms.",
    answer:"Vanishing gradients: backpropagation multiplies Jacobians across layers. Sigmoid derivative ≤ 0.25 → after 10 layers: gradient × 0.25^10 ≈ 10⁻⁶ → earlier layers get nearly zero gradient → don't learn. Three solutions: (1) ReLU activation: gradient is 1 for x>0, not compressed. Allows arbitrary depth. (2) Residual connections (ResNets): output = F(x)+x → direct gradient path ∂Loss/∂x always has a +1 term regardless of F. (3) Batch Normalisation: normalises activations → prevents them from saturating sigmoid/tanh → gradients flow through activation derivatives near 1.",
    explanation:"Fourth solution: LSTM gates — forget/input/output gates use sigmoid, but the cell state has a direct gradient path through addition (not multiplication), similar to residual connections. This is why LSTMs don't suffer vanishing gradients over sequence length the way vanilla RNNs do.",
    tags:["turing","toptal","andela","frequently-tested"] },

  { id:"gp-002", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is the difference between a model's parameters and hyperparameters?",
    answer:"Parameters: learned from training data — the model's internal weights. Examples: weights and biases in neural networks, split thresholds in decision trees, support vectors in SVM. Optimised by the training algorithm (gradient descent, etc.). Hyperparameters: set before training, not learned from data — control the training process or model structure. Examples: learning rate, number of layers, dropout rate, k in KNN, C and gamma in SVM, max_depth in tree. Optimised by: grid search, random search, Bayesian optimisation on validation set.",
    explanation:"Common confusion: some things feel like parameters but are hyperparameters. Number of neurons per layer: hyperparameter. Values of neuron weights: parameters. λ in L2 regularisation: hyperparameter. The regularised weight values: parameters.",
    tags:["turing","andela","core"] },

  { id:"gp-003", group:"training", difficulty:"medium", type:"short",
    question:"What is the difference between batch size 1, small batch (32-256), and full-batch gradient descent in terms of noise, speed, and generalisation?",
    answer:"Batch size 1 (SGD): maximum noise, can escape local minima, poor GPU utilisation (no parallelism), slow wall-clock. Small batch (32-256): good GPU utilisation, moderate noise, fast in practice. Full batch: minimum noise (deterministic), very slow per update (must process all data), converges to sharp local minima that generalise worse. Counterintuitive finding (Keskar et al.): large batches converge to sharper minima with worse test accuracy. Noise from small batches is a useful regulariser — it finds flatter, wider minima that generalise better.",
    explanation:"Practical rule: use the largest batch size that fits in GPU memory while keeping validation accuracy acceptable. If quality degrades with large batch: use learning rate warmup, linear scaling rule (scale LR proportionally with batch size), or gradient accumulation to simulate large batches with small memory.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"gp-004", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is the difference between Type I and Type II errors in hypothesis testing? How does this map to ML classification?",
    answer:"Type I error (false positive, α): rejecting a true null hypothesis. In ML: predicting positive when truly negative. Example: flagging a legitimate email as spam. Type II error (false negative, β): failing to reject a false null hypothesis. In ML: predicting negative when truly positive. Example: missing a fraudulent transaction. Statistical power = 1-β. In hypothesis testing: choose α (significance level) to control Type I. In ML: adjust decision threshold to control the tradeoff between FP and FN based on costs.",
    explanation:"Medical testing: H₀='patient is healthy'. Type I = diagnosing a healthy patient as sick (unnecessary treatment). Type II = missing a real disease (patient goes untreated). Medical tests minimise Type II (high sensitivity/recall) and accept some Type I. Security systems similarly minimise Type II (missed intrusions).",
    tags:["toptal","andela","frequently-tested"] },

  { id:"gp-005", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is overfitting, how do you diagnose it, and what are five ways to fix it?",
    answer:"Overfitting: model memorises training data, fails to generalise. Diagnosis: training loss << validation loss (large gap); validation loss starts rising while training loss still falls (learning curves). Fixes: (1) Get more training data. (2) Reduce model complexity (fewer layers, smaller width, shallower tree). (3) Regularisation: L1/L2 weight penalty, dropout. (4) Early stopping: stop when validation loss stops improving. (5) Data augmentation: expand effective training set with transformations. (6) Ensemble: average multiple models (variance cancels). (7) Feature selection: remove irrelevant noisy features.",
    explanation:"Diagnosing via learning curves: plot train and val loss vs training set size. If gap is constant regardless of data size → high bias (underfitting). If gap shrinks as more data is added → high variance (overfitting). More data won't help underfitting — you need a more complex model.",
    tags:["turing","andela","confirmed-turing","core"] },

  { id:"gp-006", group:"classical-ml", difficulty:"medium", type:"short",
    question:"Explain the difference between linear and logistic regression. When would you choose each?",
    answer:"Linear regression: predicts a continuous value y ∈ (-∞, +∞). Loss: MSE. Output: raw real number. Assumes: linear relationship, normally distributed residuals, homoscedasticity. Logistic regression: predicts probability P(y=1|x) ∈ (0,1). Uses sigmoid to squash linear output. Loss: binary cross-entropy. Output: probability thresholded to a class. Use linear regression for: predicting price, temperature, sales volume. Use logistic regression for: predicting probability of outcome, binary classification (spam/not spam, fraud/not fraud).",
    explanation:"Common trap: logistic regression's name contains 'regression' but it's a classification algorithm. The regression refers to the underlying linear model — we regress to a probability before applying a threshold. Multi-class: multinomial logistic regression (softmax instead of sigmoid).",
    tags:["turing","toptal","andela","confirmed-toptal","frequently-tested"] },

  { id:"gp-007", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is the difference between precision and recall? In which cases is each used? [Toptal data analysis official question]",
    answer:"Precision = TP/(TP+FP): of all predicted positives, what fraction is actually positive? Use when false positives are costly: spam detection (legitimate email in spam folder is bad), medical interventions (unnecessary surgery). Recall = TP/(TP+FN): of all actual positives, what fraction did we catch? Use when false negatives are costly: cancer screening (missing a cancer is catastrophic), fraud detection (letting fraud through is costly), security alerts. F1 = 2·P·R/(P+R): harmonic mean, good default when cost of FP ≈ cost of FN.",
    explanation:"Precision-recall trade-off: lowering the classification threshold → more positives predicted → higher recall, lower precision. The threshold should be set based on the cost ratio: if FN costs 10× more than FP, set threshold to maximise recall even at lower precision.",
    tags:["toptal","turing","andela","confirmed-toptal","frequently-tested"] },

  { id:"gp-008", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"Why do we need both a validation set and a test set? What is the difference between them?",
    answer:"Validation set: used during development to tune hyperparameters and select the best model. You can look at it as many times as you want. Test set: used only once at the end — final unbiased estimate of generalisation performance. If you tune hyperparameters based on test performance (even indirectly), the test set is contaminated — it gives an optimistic, unreliable estimate. The test set must be truly held-out: no model decisions should be made based on it.",
    explanation:"With only train/test: every time you try a new hyperparameter and check test performance, you're effectively 'fitting' to the test set. After 100 experiments, your test performance is optimistic by multiple hypothesis testing. With validation set: tune on validation, report test once. This is why Kaggle has a private leaderboard revealed only at the end.",
    tags:["toptal","turing","andela","confirmed-toptal","frequently-tested"] },

  { id:"gp-009", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is regularisation and what are three common examples? [Toptal official question]",
    answer:"Regularisation: techniques that reduce model complexity to prevent overfitting, typically by adding a penalty to the loss function or constraining the model. Examples: (1) L2 (Ridge/weight decay): adds λΣw² to loss — shrinks all weights toward zero proportionally. Most common for neural networks (AdamW). (2) L1 (Lasso): adds λΣ|w| — produces sparse weights (feature selection). (3) Dropout: randomly zero out p% of neurons during training — prevents co-adaptation, approximates ensemble. (4) Early stopping: stop training when validation loss stops improving. (5) Data augmentation: effectively increases training set size — a form of regularisation.",
    explanation:"Elastic Net: L1 + L2 combined. Controls sparsity (L1) and stability (L2). Best of both when you have many correlated features. In LLMs: weight decay (L2) is universal; dropout is common in attention layers (p=0.1); gradient clipping prevents gradient explosion which is a different problem.",
    tags:["toptal","turing","andela","confirmed-toptal","frequently-tested"] },

  { id:"gp-010", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is an imbalanced dataset? List four ways to deal with it. [Toptal official question]",
    answer:"Imbalanced dataset: one class has far more examples than another. Mild: 80/20. Severe: 99/1 (fraud, rare disease). Four approaches: (1) Resampling: oversample minority (SMOTE creates synthetic examples) or undersample majority. (2) Class-weighted loss: set class_weight='balanced' in sklearn — multiplies loss contribution of minority class. (3) Change metric: use F1, AUC-PR, MCC instead of accuracy. (4) Threshold adjustment: lower the classification threshold from 0.5 to get higher recall for the minority class. (5) Collect more minority-class data (best but expensive).",
    explanation:"SMOTE (Synthetic Minority Oversampling): for each minority sample, find k nearest minority neighbours, interpolate a new point on the line between them. Creates diverse synthetic examples, not just duplicates. Risk: if the minority class is inherently noisy, SMOTE can create noisy synthetic samples.",
    tags:["toptal","turing","andela","confirmed-toptal","frequently-tested"] },

  { id:"gp-011", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is the difference between supervised, unsupervised, and reinforcement learning? [Toptal official question + Turing MCQ topic]",
    answer:"Supervised: labelled training data (x, y) — model learns mapping x→y. Examples: classification, regression. Unsupervised: no labels — model finds structure in x. Examples: clustering (K-Means), dimensionality reduction (PCA), density estimation, anomaly detection. Reinforcement learning: agent takes actions in an environment, receives rewards, learns a policy that maximises cumulative reward. No fixed dataset — agent generates its own experience. Examples: game playing (AlphaGo), robotics, RLHF for LLMs. Self-supervised: labels derived from the data itself (predict masked token, next token). Used in LLM pretraining.",
    explanation:"Boundary cases: semi-supervised (small labelled + large unlabelled), few-shot (very few labelled examples + meta-learning), active learning (model queries for labels on most informative examples). In industry: 95% of production ML is supervised or self-supervised. Reinforcement learning is common in recommendation systems and LLM alignment (RLHF).",
    tags:["toptal","turing","andela","confirmed-toptal","core"] },

  { id:"gp-012", group:"training", difficulty:"medium", type:"short",
    question:"What are convolutional neural networks used for besides image classification? [Toptal official question]",
    answer:"CNNs beyond image classification: (1) Object detection: YOLO, SSD, Faster R-CNN — predict bounding boxes and class labels. (2) Semantic segmentation: U-Net (medical imaging) — classify every pixel. (3) 1D convolution for time series: sliding window over temporal data, used in ECG analysis, speech processing, sensor fusion. (4) NLP: TextCNN — 1D conv over token embeddings to extract n-gram features. (5) Recommender systems: convolve over user history sequences. (6) Audio: convert waveform to spectrogram (2D image) and apply 2D CNN. (7) Graph neural networks: generalised convolution over arbitrary graph structure.",
    explanation:"Why 1D CNN beats LSTM for some time series: (1) Fully parallelisable (no sequential dependency). (2) Explicit local receptive field (LSTM mixes all history). (3) Much faster to train. TCN (Temporal Convolutional Network) with dilated 1D convolutions is now competitive with LSTMs on most sequence tasks.",
    tags:["toptal","turing","confirmed-toptal"] },

  { id:"gp-013", group:"ml-fundamentals", difficulty:"hard", type:"short",
    question:"What is the curse of dimensionality? List four ways to deal with it. [Toptal official question]",
    answer:"As dimensionality d increases: (1) Volume grows exponentially — data becomes sparse (need 10^d samples for fixed density). (2) Distance metrics lose discrimination — all points become equidistant. (3) Hyperplanes can separate any dataset (too easy to overfit). (4) Most volume is near the surface of the hypercube. Four solutions: (1) Feature selection (remove irrelevant features). (2) Dimensionality reduction (PCA, autoencoders, UMAP). (3) Regularisation (penalise complexity). (4) Domain knowledge to engineer fewer, more informative features. (5) Distance metric learning (learn which dimensions matter for similarity).",
    explanation:"Concrete example: nearest neighbour on 100 random uniform features: the closest and farthest neighbours are nearly the same distance (all distances converge to d^0.5). KNN fails entirely. This is why high-dimensional data needs feature engineering before KNN, and why embeddings (dimensionality reduction + semantic structure) are essential for vector search.",
    tags:["toptal","turing","confirmed-toptal","frequently-tested"] },

  { id:"gp-014", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is data leakage in ML? Give three examples and explain how to prevent each.",
    answer:"Data leakage: information from outside the training set contaminates training, producing falsely optimistic results. (1) Preprocessing leakage: fitting scaler/imputer on train+test combined. Fix: fit only on train, transform test. (2) Target leakage: feature that encodes the target (e.g., 'treatment_given' predicting 'outcome' when treatment is given because of outcome). Fix: careful feature review with domain experts. (3) Temporal leakage: using future data to predict past events (e.g., using December sales to predict whether a November marketing campaign succeeded). Fix: strict time-based splits. (4) Duplicate leakage: same example in train and test (common in Kaggle with augmented data). Fix: deduplicate before splitting.",
    explanation:"Leakage is the most common cause of suspiciously high validation accuracy. If your model achieves near-perfect performance, suspect leakage first. Check: feature correlations with target, temporal ordering of data, preprocessing pipeline order.",
    tags:["toptal","turing","andela","confirmed-toptal","frequently-tested"] },

  { id:"gp-015", group:"evaluation", difficulty:"medium", type:"short",
    question:"Explain sensitivity and specificity. How are they different from precision and recall?",
    answer:"Sensitivity = Recall = TPR = TP/(TP+FN): of all actual positives, how many did we catch? Specificity = TNR = TN/(TN+FP): of all actual negatives, how many did we correctly reject? Precision = TP/(TP+FP): of all predicted positives, what fraction is correct? Recall = sensitivity (same formula). The difference: precision depends on the prior probability of positives (base rate), while sensitivity/specificity do not. ROC curve plots sensitivity vs (1-specificity). PR curve plots precision vs recall. In imbalanced datasets, PR curve is more informative.",
    explanation:"Clinical diagnostic test language: sensitivity/specificity. ML classifier language: precision/recall. They measure the same underlying quantities but are framed differently. SnNout: high sensitivity → rules OUT (negative test = not sick). SpPin: high specificity → rules IN (positive test = definitely sick).",
    tags:["turing","andela","frequently-tested"] },

  { id:"gp-016", group:"training", difficulty:"medium", type:"short",
    question:"What is transfer learning and when should you use fine-tuning vs. feature extraction?",
    answer:"Transfer learning: use a model pretrained on a large dataset (ImageNet, Common Crawl) as a starting point for a different task. Feature extraction: freeze all pretrained weights, only train a new classification head. Use when: small dataset (fine-tuning would overfit), target task is similar to source task. Fine-tuning: unfreeze some or all layers and continue training on new task. Use when: larger dataset available, target task differs significantly from source. Gradual unfreezing: freeze bottom layers, train top, then unfreeze progressively — good balance. LoRA: efficient fine-tuning of LLMs by adding trainable rank-decomposition matrices.",
    explanation:"Rule of thumb: dataset size × task similarity → strategy. Small data + similar task: feature extraction. Large data + different task: full fine-tuning. Medium data: fine-tune top N layers only. In NLP: BERT fine-tuning on downstream tasks requires only 3-5 epochs of data with 10x lower LR than pretraining.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"gp-017", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is the difference between gradient boosting (XGBoost) and a random forest? Which is better and when?",
    answer:"Random Forest: independent trees, bagging + feature randomness, parallel training, reduces variance. Strong on noisy datasets, robust to outliers, easy to tune. XGBoost: sequential trees each correcting residuals of previous ensemble, reduces bias, requires careful tuning (learning rate, depth, subsample). Better on clean, structured data, typically wins on Kaggle tabular competitions. RF is better when: training speed matters, data is noisy, few hyperparameters to tune, you need a reasonable baseline fast. XGBoost is better when: maximum accuracy on tabular data, you have time to tune, validation set available for early stopping.",
    explanation:"Modern comparison: LightGBM (histogram-based GBM) is 3-10× faster than XGBoost with similar accuracy. CatBoost handles categorical features natively without encoding. For tabular data: try LightGBM first (fastest), then XGBoost for fine-tuning, RF as baseline.",
    tags:["turing","toptal","andela","frequently-tested"] },

  { id:"gp-018", group:"training", difficulty:"medium", type:"short",
    question:"What is the Adam optimiser? When would you use SGD with momentum instead?",
    answer:"Adam: adaptive per-parameter learning rates using first moment (momentum, β₁=0.9) and second moment (velocity, β₂=0.999). Normalises step size by √(second moment) — large/consistent gradients get normal steps; small/noisy gradients get amplified. Pro: faster convergence, less learning rate tuning. Con: can converge to sharper minima → worse generalisation in some cases. SGD + momentum: fixed learning rate for all parameters, momentum accumulates gradient direction. Pro: better generalisation in vision models (empirically). Con: sensitive to learning rate, needs careful tuning. Use Adam for: LLMs (universal), fast prototyping, NLP tasks. Use SGD+momentum for: production vision models when best test accuracy matters.",
    explanation:"AdamW (Adam + decoupled weight decay) is the current standard for LLM training. The decoupling is important: Adam applies weight decay differently from L2 regularisation — AdamW corrects this, giving better regularisation. Llama, GPT-4, Gemini all use AdamW.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"gp-019", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is the F1 score and when is it a better metric than accuracy?",
    answer:"F1 = 2 × (Precision × Recall) / (Precision + Recall) = 2TP / (2TP + FP + FN). Harmonic mean — lower than arithmetic mean, punishes extreme imbalance between P and R. Better than accuracy when: (1) Class imbalance — accuracy can be high by predicting only the majority class. (2) Both FP and FN matter — F1 considers both types of error equally. (3) Comparing models on imbalanced problems where accuracy is misleading. Macro F1: average F1 per class (treats all classes equally). Micro F1: aggregate TP/FP/FN across all classes (biased toward frequent classes). Weighted F1: average weighted by class frequency.",
    explanation:"F1 is not the right metric for all tasks: if FP costs more than FN, optimise precision; if FN costs more, optimise recall. F1 assumes equal cost — use it when that assumption holds. For multi-label classification, you need to specify averaging strategy explicitly.",
    tags:["turing","andela","confirmed-turing","frequently-tested"] },

  { id:"gp-020", group:"ml-fundamentals", difficulty:"easy", type:"short",
    question:"What is the difference between a parameter and a hyperparameter? Give examples for a neural network.",
    answer:"Parameters: learned automatically from data during training. Optimised by the training algorithm (gradient descent). Examples: weights W and biases b in each layer, embedding vectors, batch norm γ and β. Hyperparameters: set manually before training, not updated by gradient descent. Optimised by trial and error, grid search, or Bayesian optimisation using validation performance. Examples: learning rate, number of layers, hidden size (model width), dropout rate, batch size, L2 lambda, number of attention heads, optimizer choice, weight decay.",
    explanation:"Grey area: batch normalisation γ and β are technically parameters (learned by gradient descent) but could be seen as hyperparameters conceptually. The test: if gradient flows through it during backprop and it gets updated by the optimiser — it's a parameter. If you set it before training and it doesn't change — it's a hyperparameter.",
    tags:["turing","andela","core"] },

  { id:"gp-021", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is a confusion matrix? Derive Accuracy, Precision, Recall, F1, and Specificity from it.",
    answer:"Confusion matrix (binary):\n             Predicted +    Predicted -\nActual +       TP              FN\nActual -       FP              TN\n\nAccuracy = (TP+TN)/(TP+TN+FP+FN) — overall correctness\nPrecision = TP/(TP+FP) — of predicted positives, how many correct\nRecall/Sensitivity = TP/(TP+FN) — of actual positives, how many caught\nSpecificity = TN/(TN+FP) — of actual negatives, how many correctly rejected\nF1 = 2·TP/(2·TP+FP+FN) — harmonic mean of P and R\nMCC = (TP·TN-FP·FN)/√((TP+FP)(TP+FN)(TN+FP)(TN+FN))",
    explanation:"MCC (Matthews Correlation Coefficient) is the best single metric for imbalanced binary classification — it takes all four cells into account equally and gives a score from -1 (inverse) to 0 (random) to 1 (perfect). More robust than F1 for highly imbalanced datasets.",
    tags:["turing","andela","confirmed-turing","core","frequently-tested"] },

  { id:"gp-022", group:"training", difficulty:"medium", type:"short",
    question:"What is cross-entropy loss and why is it used for classification instead of MSE?",
    answer:"Cross-entropy: L = -Σᵢ yᵢ log(p̂ᵢ). For binary: L = -[y·log(p) + (1-y)·log(1-p)]. Three reasons to prefer over MSE: (1) Probabilistic interpretation — cross-entropy is the negative log-likelihood of the multinomial distribution. (2) Gradient magnitude — cross-entropy gradient ∂L/∂p ∝ (p-y)/p(1-p) is larger when the model is very wrong (far from correct), giving stronger learning signal. (3) MSE with sigmoid has vanishing gradients when model is very wrong: ∂MSE/∂w = (p-y)·p·(1-p)·x — near 0 when p≈0 or p≈1. Cross-entropy avoids this.",
    explanation:"Numerical stability: never compute log(p) directly when p could be 0. In practice: use log-softmax + NLLLoss, or nn.CrossEntropyLoss (combines softmax and log internally in a numerically stable way). Log-sum-exp trick prevents overflow in softmax: subtract max before exponentiation.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"gp-023", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is model calibration? How do you detect and fix a poorly calibrated model?",
    answer:"Calibration: a well-calibrated model's predicted probability matches the actual frequency. If a model predicts 70% probability for 1000 examples, ~700 should actually be positive. Detection: reliability diagram (calibration plot) — bin predictions, compare mean predicted prob vs actual positive rate. ECE (Expected Calibration Error) quantifies the gap. Fixing: (1) Temperature scaling: divide logits by T (learned scalar on validation set). (2) Platt scaling: logistic regression on model outputs. (3) Isotonic regression: non-parametric calibration. Neural networks tend to be overconfident (high confidence, wrong); random forests are often underconfident.",
    explanation:"Why calibration matters: (1) Risk-aware decisions (should I act on this 85% confidence prediction?). (2) Combining multiple models (uncalibrated probabilities can't be averaged meaningfully). (3) Cost-sensitive decision thresholds depend on calibrated probabilities. Ensembles tend to be better calibrated than single models.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"gp-024", group:"classical-ml", difficulty:"medium", type:"short",
    question:"Implement logistic regression from scratch in Python. [Implementation round]",
    answer:"import numpy as np\n\ndef sigmoid(z): return 1 / (1 + np.exp(-z))\n\nclass LogisticRegression:\n    def __init__(self, lr=0.01, n_iters=1000):\n        self.lr, self.n_iters = lr, n_iters\n        self.w, self.b = None, None\n\n    def fit(self, X, y):\n        n, d = X.shape\n        self.w = np.zeros(d); self.b = 0\n        for _ in range(self.n_iters):\n            p = sigmoid(X @ self.w + self.b)\n            dw = (1/n) * X.T @ (p - y)\n            db = (1/n) * (p - y).sum()\n            self.w -= self.lr * dw\n            self.b -= self.lr * db\n\n    def predict_proba(self, X):\n        return sigmoid(X @ self.w + self.b)\n\n    def predict(self, X, thr=0.5):\n        return (self.predict_proba(X) >= thr).astype(int)",
    explanation:"The gradient of binary cross-entropy w.r.t. w is (1/n)Xᵀ(p-y) — the same formula as linear regression but with probabilities p instead of raw outputs. This elegant result comes from the derivative of the sigmoid cancelling with the log in cross-entropy.",
    tags:["turing","andela","confirmed-turing"] },

  { id:"gp-025", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is Principal Component Analysis (PCA) and how do you decide how many components to keep?",
    answer:"PCA: linear dimensionality reduction. Steps: (1) Centre data (subtract mean). (2) Compute covariance matrix C = XᵀX/(n-1). (3) Eigendecompose: C = VΛVᵀ. (4) Sort eigenvectors by eigenvalue descending. (5) Project: X_reduced = X·V[:,:k]. How many components: (1) Explained variance threshold: keep k components explaining ≥ 90-95% cumulative variance. (2) Elbow in scree plot: find where eigenvalues stop dropping steeply. (3) Task-based: try k=2 for visualisation, k chosen by downstream task performance.",
    explanation:"PCA assumes linear structure — if data has non-linear manifold structure, use UMAP or autoencoders. PCA is sensitive to scale — always standardise before applying. Sklearn: PCA(n_components=0.95) keeps enough components for 95% explained variance automatically.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"gp-026", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is the difference between parametric and non-parametric tests in statistics? When does it matter for ML?",
    answer:"Parametric tests: assume data follows a specific distribution (usually normal). Examples: t-test, ANOVA, Pearson correlation. Require: normality, equal variance (homoscedasticity). Non-parametric tests: no distributional assumption — use ranks or permutations. Examples: Mann-Whitney U, Wilcoxon, Spearman correlation, Kruskal-Wallis. ML relevance: (1) Comparing model performances (paired t-test or Wilcoxon signed-rank for paired evaluations). (2) Feature selection (non-parametric tests for ordinal or skewed features). (3) Statistical significance of A/B test results. Use non-parametric when: small sample, non-normal distribution, ordinal data.",
    explanation:"McNemar's test: compare two classifiers on the same test set (binary classification). More powerful than paired t-test for comparing classifier accuracy. Friedman test: non-parametric ANOVA for comparing multiple classifiers across multiple datasets.",
    tags:["toptal"] },

  { id:"gp-027", group:"training", difficulty:"medium", type:"short",
    question:"What are the differences between batch normalisation and layer normalisation? When do you use each?",
    answer:"BatchNorm: normalise across the batch dimension (mean and std of each feature across all batch samples). Issues: requires large batch (fails at batch=1), different train/inference behaviour (running stats), hard to use with variable-length sequences. LayerNorm: normalise across the feature dimension (mean and std of all features for each individual sample). No batch dependency — works for batch=1, same train/inference behaviour, natural for variable-length sequences. Use BatchNorm: CNNs, vision models (large fixed-size batches). Use LayerNorm: transformers, LLMs, RNNs, any NLP task.",
    explanation:"InstanceNorm: normalise each spatial location in each sample independently (used in style transfer — removes instance-level statistics). GroupNorm: normalise within groups of channels (works with small batches, used in object detection). RMSNorm: simplified LayerNorm (skip mean subtraction, only scale by RMS) — used in Llama, slightly faster.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"gp-028", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is a p-value? How do you interpret it in the context of A/B testing for ML models?",
    answer:"P-value: probability of observing results as extreme as the data, assuming the null hypothesis is true. It is NOT the probability that the null hypothesis is true. In A/B testing: H₀ = 'model A and model B have the same performance'. p < 0.05 means: if models were truly equal, we'd see this performance difference less than 5% of the time. We reject H₀ and accept the difference is real. Practical significance ≠ statistical significance: a tiny improvement (0.01% AUC) can be statistically significant with large enough samples but practically meaningless. Always report effect size alongside p-value.",
    explanation:"Multiple testing problem: if you test 20 metrics simultaneously, expect 1 false positive even if all null hypotheses are true (0.05 × 20 = 1). Correction: Bonferroni (divide α by number of tests), Benjamini-Hochberg (controls false discovery rate). In ML: when comparing many models, adjust significance threshold accordingly.",
    tags:["toptal","andela"] },

  { id:"gp-029", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is the difference between AUC-ROC and AUC-PR? When should you use each?",
    answer:"AUC-ROC: area under TPR vs FPR curve. Ranges 0.5 (random) to 1.0 (perfect). Interpretation: probability that a randomly chosen positive ranks higher than a randomly chosen negative. AUC-PR: area under Precision vs Recall curve. No random baseline — depends on class balance. Ranges near 0 (random ≈ prevalence) to 1.0 (perfect). When to use each: AUC-ROC: balanced datasets, comparing ranking quality of two models. AUC-PR: imbalanced datasets (fraud detection, rare disease, medical diagnosis) — more informative about minority class performance. With 1% positives: a random model gets AUC-ROC≈0.5 and AUC-PR≈0.01 — PR curve is more discriminative.",
    explanation:"AUC-ROC can be misleadingly optimistic on severely imbalanced data because TN (the dominant cell) inflates specificity. AUC-PR ignores TN entirely — focuses only on positive class performance. Always report AUC-PR alongside AUC-ROC for any imbalanced problem.",
    tags:["toptal","turing","andela","frequently-tested"] },

  { id:"gp-030", group:"training", difficulty:"medium", type:"short",
    question:"What is the learning rate and how do you choose a good one? What happens with too high or too low?",
    answer:"Learning rate (η): step size for each gradient update. θ = θ - η·∇L. Too high: loss oscillates or diverges — updates overshoot the minimum, gradient explodes. Too low: training is extremely slow, gets stuck in local minima. Finding a good LR: (1) LR range test (Smith, 2017): increase LR exponentially over training, plot loss vs LR, pick LR just before loss starts rising. (2) Warmup + cosine decay: start at 1e-7, increase linearly to peak (1e-4 to 1e-3), then decay. (3) Typical starting points: Adam: 1e-3 to 3e-4. SGD: 0.01 to 0.1. Transformers: 1e-4 to 3e-4.",
    explanation:"The 3× rule of thumb: start at a reasonable LR, train for a few steps, if loss doesn't decrease within 10 steps, reduce LR by 3×. Repeat until loss decreases. Learning rate is the most important hyperparameter — it has the largest effect on training stability and final model quality.",
    tags:["turing","andela","core"] },

  { id:"gp-031", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is the difference between content-based and collaborative filtering recommendation systems?",
    answer:"Content-based filtering: recommends items similar to what the user has liked before, based on item attributes (genre, director, keywords). Doesn't need other users' data. Cold start: works for new users if they provide initial preferences. Example: 'you liked Inception → you'll like Interstellar (same director)'. Collaborative filtering: recommends based on what similar users liked. User-based: find similar users, recommend what they liked. Item-based: find items that co-occur in similar users' histories. Cold start problem: needs user history — can't recommend to new users. Matrix factorisation (SVD, ALS) learns latent user/item embeddings. Hybrid: combine both.",
    explanation:"Modern recommendation systems: two-tower neural networks (learn user and item embeddings separately, dot product for scoring), or LLM-based (use text descriptions for zero-shot recommendations). Most production systems are hybrid: retrieval (collaborative filtering or ANN search on embeddings) → ranking (content-based features + user history).",
    tags:["turing","andela"] },

  { id:"gp-032", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What are the key assumptions of linear regression and how do you check them?",
    answer:"Six assumptions: (1) Linearity: relationship between X and y is linear. Check: scatter plot X vs y, residual vs fitted plot (should show no pattern). (2) Independence: observations are independent. (3) Homoscedasticity: constant variance of residuals. Check: residual vs fitted (should be a horizontal band). (4) Normality of residuals. Check: Q-Q plot, Shapiro-Wilk test. (5) No multicollinearity. Check: VIF > 10 is problematic. (6) No influential outliers. Check: Cook's distance.",
    explanation:"Violations and fixes: (1) Non-linearity: add polynomial features or use non-linear models. (2) Heteroscedasticity: log-transform target, use weighted regression. (3) Multicollinearity: remove correlated features or use Ridge. (4) Non-normal residuals: usually fine with large N (CLT), otherwise use robust regression. These assumptions matter more for inference (confidence intervals) than prediction accuracy.",
    tags:["toptal","andela"] },

  { id:"gp-033", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is the difference between bagging, boosting, and stacking?",
    answer:"Bagging: train B models independently on bootstrap samples (random rows with replacement), average/vote predictions. Reduces variance. Example: Random Forest. Boosting: train models sequentially, each fitting the residuals (errors) of the previous ensemble. Reduces bias. Example: XGBoost, AdaBoost, LightGBM. Stacking (stacked generalisation): train diverse base models, use their out-of-fold predictions as features to train a meta-learner. Combines different model families. Reduces both bias and variance. More complex to implement correctly (need OOF predictions to avoid leakage).",
    explanation:"Stacking correctly: (1) Split training data into K folds. (2) For each fold, train base models on other K-1 folds, predict on held-out fold. (3) After K folds, each training example has predictions from all base models. (4) Train meta-learner on these stacked predictions. (5) For test: average base model predictions (trained on all training data), feed to meta-learner.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"gp-034", group:"training", difficulty:"medium", type:"short",
    question:"What is weight decay and how is it different from L2 regularisation in the context of adaptive optimisers?",
    answer:"L2 regularisation (standard): adds λ‖w‖² to loss function. Gradient: ∂L/∂w += 2λw. With Adam: the adaptive learning rate scales this penalty non-uniformly — parameters with large gradients get less regularisation, parameters with small gradients get proportionally more. Weight decay (AdamW): directly subtract λw from parameters after the Adam update, independently of adaptive learning rate. Effect: uniform shrinkage across all parameters regardless of gradient scale. Loshchilov & Hutter (2017): AdamW significantly outperforms Adam+L2 for LLM training. L2 = weight decay only when using SGD (no adaptive scaling).",
    explanation:"Practical impact: using Adam+L2 regularisation (common mistake) is not the same as AdamW. The adaptive scaling in Adam effectively changes the regularisation strength per parameter in a way that is hard to control. AdamW decouples regularisation from the update rule, restoring the intended behaviour. Use AdamW for all transformer training.",
    tags:["toptal","frequently-tested"] },

  { id:"gp-035", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is BLEU score and what are its limitations for evaluating NLP models?",
    answer:"BLEU (Bilingual Evaluation Understudy): measures n-gram overlap between generated text and reference translations. Score = geometric mean of 1-gram to 4-gram precision × brevity penalty. Range: 0 (no overlap) to 1 (exact match). Limitations: (1) N-gram matching misses semantic equivalence — 'the cat sat' vs 'a feline rested' scores 0 despite same meaning. (2) Penalises valid paraphrases. (3) Single reference can't capture all valid translations. (4) Doesn't measure fluency or coherence. (5) Correlates poorly with human judgement for open-ended generation. Better alternatives: ROUGE (recall-based, for summarisation), BERTScore (semantic similarity via embeddings), human evaluation for highest-stakes tasks.",
    explanation:"BLEU is still used as a fast, reproducible benchmark for machine translation because of its historical prevalence. For LLM evaluation: prefer task-specific metrics (HumanEval for code, exact-match for QA), LLM-as-judge for open-ended generation, or human evaluation.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"gp-036", group:"agents", difficulty:"medium", type:"short",
    question:"What is the difference between zero-shot, one-shot, and few-shot prompting for LLMs, and which platforms test this? [Turing + Toptal confirmed topic]",
    answer:"Zero-shot: no examples, just task description. 'Translate to French: [text]'. One-shot: one example provided before the task. Few-shot (2-10 examples): the model uses examples to learn the task format. In-context learning (ICL) is the general term. Performance typically improves with more examples, up to a point limited by context window. Few-shot is often competitive with fine-tuning on small datasets — but only for models above ~7B parameters (smaller models don't generalise well from examples). Chain-of-thought few-shot: include reasoning steps in examples — dramatically improves multi-step reasoning tasks.",
    explanation:"Order matters in few-shot: put the most representative examples first (or last — recency bias). Diversity matters: examples should cover the range of expected inputs. Don't include misleading examples. Auto-CoT: automatically generate chain-of-thought examples by clustering similar questions and generating reasoning for each cluster.",
    tags:["turing","toptal","andela","confirmed-turing","frequently-tested"] },

  { id:"gp-037", group:"transformers", difficulty:"medium", type:"short",
    question:"What is the attention mechanism and why was it proposed? What problem does it solve in sequence models?",
    answer:"Problem it solves: in seq2seq models (encoder-decoder RNN), the encoder compresses the entire input sequence into a single fixed-size vector — information bottleneck for long sequences. Attention (Bahdanau, 2014): at each decoder step, compute a weighted sum over all encoder hidden states, where weights reflect relevance to the current output step. The decoder can 'look back' at any part of the input directly — no fixed-size bottleneck. Transformer attention (Vaswani, 2017): scale this to be the primary mechanism (no RNN at all), using Q, K, V matrices and dot-product scoring.",
    explanation:"Before attention: machine translation quality degraded sharply for sentences > 30 tokens. With attention: flat performance across long sentences. This was the key breakthrough leading to transformers. The transformer removed the recurrence entirely — attention is the only mechanism, enabling full parallelisation and much longer context.",
    tags:["turing","toptal","andela","frequently-tested"] },

  { id:"gp-038", group:"training", difficulty:"hard", type:"short",
    question:"What is the difference between pre-training, instruction tuning (SFT), and RLHF? [Confirmed across all three platforms]",
    answer:"Pre-training: train on massive raw text (billions of tokens) with next-token prediction objective. Learns language, knowledge, and reasoning. Very expensive ($M). Instruction tuning (SFT): fine-tune on (instruction, ideal response) pairs — teaches the model to follow instructions, be helpful, format answers. Medium cost ($k-$100k). Requires high-quality human-written demonstrations. RLHF: (1) Collect human preference comparisons (A vs B). (2) Train reward model. (3) Optimise with PPO to maximise reward while staying close to SFT model. Goes beyond imitation — learns what humans actually prefer, not just what they demonstrate. Most expensive alignment step.",
    explanation:"DPO is a simpler alternative to RLHF: directly optimise preference pairs without a reward model or PPO. More stable, easier to implement. Most open-source models (Llama, Mistral) use SFT + DPO rather than PPO-RLHF. GPT-4 and Claude use more complex RLHF variants with additional safety components.",
    tags:["toptal","turing","andela","confirmed-toptal","confirmed-turing","frequently-tested"] },

  { id:"gp-039", group:"llms", difficulty:"medium", type:"short",
    question:"What are embeddings and why are they fundamental to modern NLP and recommendation systems?",
    answer:"Embedding: dense vector representation of a discrete entity (word, sentence, user, item) in a continuous space. Dense vectors (e.g., 768-dimensional) carry semantic information — similar concepts have similar vectors. Word2Vec: train skip-gram or CBOW to predict context words — results in semantic arithmetic (king - man + woman ≈ queen). Sentence embeddings (SBERT, E5, OpenAI text-embedding): entire sentence → one vector for semantic search. Why fundamental: (1) Convert sparse discrete objects to continuous inputs for neural networks. (2) Enable semantic similarity search (RAG, recommendation). (3) Pretrained embeddings transfer knowledge to downstream tasks. (4) Bridge modalities (CLIP aligns image and text embeddings).",
    explanation:"Embedding quality: measured by semantic similarity tasks (STS benchmark), retrieval recall (BEIR benchmark), and downstream task performance. OpenAI text-embedding-3-small (1536d) vs large (3072d): larger embeddings give ~5% better retrieval but 4× more memory. For production: balance quality vs cost vs latency.",
    tags:["turing","toptal","andela","frequently-tested"] },

  { id:"gp-040", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What are the differences between a time series and a regular dataset, and what special ML considerations apply?",
    answer:"Time series differences: (1) Temporal ordering matters — future depends on past, not vice versa. (2) Autocorrelation: nearby observations are correlated (violates i.i.d. assumption). (3) Seasonality and trend: long-range patterns. (4) Distribution shift: the pattern may change over time. ML considerations: (1) No random train/test split — must use time-based split (train on past, test on future). (2) No k-fold CV — use walk-forward validation (train on 1...t, test on t+1, retrain on 1...t+1, ...). (3) Features: lag features, rolling statistics, date features (day of week, month). (4) Target: may need differencing to make stationary.",
    explanation:"Common time series models: ARIMA (statistical, interpretable), Prophet (trend + seasonality + holidays), LightGBM with lag features (often best in practice), N-BEATS/PatchTST (neural architectures). The biggest mistake: using random cross-validation on time series — it leaks future into training and gives optimistic estimates.",
    tags:["toptal","andela"] },

  { id:"gp-041", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is learning curve analysis and what does it tell you about model behaviour?",
    answer:"Learning curves: plot training error and validation error vs. training set size. Patterns: (1) High bias (underfitting): both curves plateau at high error level regardless of data size. Adding more data won't help — need more complex model or better features. (2) High variance (overfitting): large gap between train and val error that shrinks as data grows. Adding more data will help. (3) Good fit: train and val error converge at a low error level. (4) Noise: val error is noisy/spiky — increase validation set size. Also: plot error vs training iterations (epochs) to detect when overfitting starts (early stopping point).",
    explanation:"Actionable decisions from learning curves: (1) Gap narrows → add more data. (2) Both errors high → more complex model or better features. (3) Gap constant regardless of data → regularise, get different data. In practice: learning curves are the most diagnostically useful plot for any ML model.",
    tags:["toptal","andela"] },

  { id:"gp-042", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is the Universal Approximation Theorem and what are its practical limitations?",
    answer:"UAT: a feedforward neural network with at least one hidden layer and a non-linear activation can approximate any continuous function on a compact domain to arbitrary precision, given enough hidden units. Practical limitations: (1) 'Enough units' can be exponential in input dimensions — unfeasible. (2) Existence ≠ learnability: gradient descent may not find the approximating weights. (3) Doesn't account for data efficiency — may need huge amounts of data. (4) Doesn't bound computational cost. (5) Approximation on training data ≠ generalisation.",
    explanation:"The theorem guarantees width (one wide layer) but deep networks can approximate functions exponentially more efficiently than wide shallow networks. Depth is more parameter-efficient for hierarchical functions (images, language). The theorem is theoretically important but gives little practical guidance on architecture choice.",
    tags:["toptal"] },

  { id:"gp-043", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is the difference between hard and soft voting in ensemble models?",
    answer:"Hard voting: each model votes for a class, the majority class wins. Only works with class labels. Soft voting: each model outputs a probability, probabilities are averaged, the class with highest average probability wins. Generally better because: (1) Uses confidence information — a model that's 99% sure counts more than one that's 51% sure. (2) Probability averaging is differentiable and more informative than majority vote. (3) Handles calibration better. Use hard voting when: models don't output calibrated probabilities (SVM, hard decision trees without Platt scaling).",
    explanation:"Calibration matters for soft voting: if model A always outputs 0.9 when model B outputs 0.6 for the same confidence level, their average is skewed. Calibrate all models first with Platt scaling or temperature scaling before soft voting for best results.",
    tags:["toptal","andela"] },

  { id:"gp-044", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is semi-supervised learning and when is it useful?",
    answer:"Semi-supervised learning: train with a small amount of labelled data + a large amount of unlabelled data. Methods: (1) Self-training/pseudo-labelling: train on labelled, predict unlabelled, add high-confidence predictions as labels, retrain. (2) Consistency regularisation: augmented versions of unlabelled samples should get the same prediction (FixMatch, UDA). (3) Contrastive learning: pull similar samples together in embedding space, push dissimilar apart (SimCLR, MoCo). (4) Graph-based: propagate labels through similarity graph. When useful: labelling is expensive (medical images, legal text) but unlabelled data is abundant.",
    explanation:"Modern self-supervised pre-training (BERT, GPT, SimCLR) can be seen as semi-supervised: first learn representations from unlabelled data, then fine-tune on small labelled set. This is the dominant paradigm in 2026: pre-train on internet-scale data, fine-tune on task-specific labelled examples.",
    tags:["toptal","andela"] },

  { id:"gp-045", group:"training", difficulty:"medium", type:"short",
    question:"What is catastrophic forgetting in neural networks and what are the main solutions?",
    answer:"Catastrophic forgetting: when a neural network is trained on a new task, it rapidly forgets previously learned tasks — new gradients overwrite weights encoding old knowledge. Solutions: (1) Elastic Weight Consolidation (EWC): identify important weights for previous tasks (via Fisher information), add penalty for changing them. (2) Progressive Networks: add new network columns for new tasks, freeze old weights, use lateral connections. (3) Replay/rehearsal: mix old task data with new task data during training. (4) Parameter isolation: use different subsets of weights per task. (5) LoRA fine-tuning: only update small adapters, freeze base model weights.",
    explanation:"Relevant for LLM fine-tuning: aggressive fine-tuning on domain data can make the model forget general capabilities. Fix: (1) Low learning rate. (2) LoRA. (3) Mix domain-specific fine-tuning data with general instruction data (e.g., 80% domain, 20% general). (4) Merge LoRA weights carefully with the base model.",
    tags:["toptal","frequently-tested"] },

  { id:"gp-046", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is the difference between a generative and discriminative model? Give examples of each.",
    answer:"Discriminative: models P(y|x) — the conditional probability of label given input. Only learns the boundary between classes, not the data distribution. Examples: logistic regression, SVM, neural classifiers, BERT (encoder), gradient boosting. Generative: models P(x,y) = P(x|y)P(y) — the joint distribution. Can generate new samples. Examples: Naive Bayes, VAE, GAN, diffusion models, GPT, Llama. For classification: discriminative models generally outperform generative ones when data is abundant. Generative models can: (1) generate new data, (2) handle missing data naturally, (3) model uncertainty better.",
    explanation:"Modern nuance: GPT-style autoregressive language models are generative (model P(x)) but can be used discriminatively for classification via prompting. BERT is discriminative but can fill in masked tokens (a limited form of generation). The distinction blurs in practice — what matters is the training objective.",
    tags:["toptal","andela"] },

  { id:"gp-047", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is statistical significance in A/B testing? How long should you run an A/B test?",
    answer:"Statistical significance: p-value < α (typically 0.05) means we reject H₀ of no difference. Power (1-β, typically 0.8): probability of detecting a real difference if it exists. Sample size calculation: n = 2σ²(z_α + z_β)²/δ², where δ is the minimum detectable effect, σ² is variance. Run the test until you hit the pre-calculated sample size — stopping early ('peeking') inflates Type I error rate (p-hacking). Sequential testing (optional stopping) requires corrected methods (SPRT, mSPRT). For ML model comparison: want at least 1000-10000 predictions per variant for stable estimates.",
    explanation:"Common mistakes: (1) Stopping early when result looks significant. (2) Running multiple simultaneous tests without multiple comparison correction. (3) Testing on a segment and generalising to all users. (4) Ignoring novelty effect — new UI gets more engagement initially. (5) Not accounting for network effects in social platforms.",
    tags:["toptal","andela"] },

  { id:"gp-048", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is the difference between batch gradient descent, stochastic gradient descent, and mini-batch gradient descent?",
    answer:"Batch GD: compute gradient over the entire dataset per update. Accurate gradient, slow (one update per full pass), memory intensive, deterministic. SGD (pure): one random sample per update. Very noisy gradient, fast updates, can escape local minima via noise, poor GPU utilisation (no parallelism). Mini-batch GD: gradient over B samples (typical B=32-512). Balance: better gradient estimate than SGD, parallelisable on GPU, most common in practice. In reality, 'SGD' in deep learning frameworks means mini-batch SGD.",
    explanation:"Effect of mini-batch size on gradient quality: by central limit theorem, standard error of mini-batch gradient = σ/√B. Doubling batch size halves gradient noise — but requires doubling the learning rate (linear scaling rule) to maintain the same effective learning rate per sample. Very large batches need careful LR tuning.",
    tags:["turing","andela","core","frequently-tested"] },

  { id:"gp-049", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is a support vector machine (SVM) and what is the 'maximum margin' principle?",
    answer:"SVM: find the hyperplane that maximises the margin between the two classes. Margin = distance from hyperplane to nearest training points (support vectors) of each class = 2/‖w‖. Training objective: minimise ‖w‖² (equivalently, maximise 2/‖w‖) subject to: yᵢ(wᵀxᵢ + b) ≥ 1 for all i. The maximum-margin solution is unique and has the best theoretical generalisation bound (by VC theory). Soft margin SVM: allow some misclassifications controlled by C (penalty parameter). Large C: hard margin (few violations, may overfit). Small C: soft margin (more violations, more regularised).",
    explanation:"Why maximum margin? By VC theory, the generalisation bound depends on the margin — larger margin → smaller effective VC dimension → better generalisation. This is why SVM was theoretically the most principled classification method before deep learning empirically outperformed it at scale.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"gp-050", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is the 'no free lunch' theorem and what does it imply for ML practitioners?",
    answer:"No Free Lunch (NFL) theorem (Wolpert & Macready, 1997): averaged over all possible data-generating distributions, every learning algorithm has the same expected performance. No single algorithm is universally best. Implication: algorithm choice must be guided by assumptions about the problem. Prior knowledge about the data distribution determines which algorithm to use. For practitioners: (1) Always try multiple algorithms. (2) Use domain knowledge to constrain model choice. (3) Cross-validate to empirically find the best algorithm for your specific data. (4) Don't believe claims of universally 'best' algorithms.",
    explanation:"NFL is often misunderstood: it doesn't mean all algorithms are equal in practice — it means they're equal in expectation over all possible problems. For any specific real-world problem with structure, some algorithms will vastly outperform others. The theorem justifies not committing to a single algorithm before understanding the data.",
    tags:["toptal"] },
];
