import type { IQ } from "./interview-data";

export const BANK_G: IQ[] = [

  // ── EVALUATION (50) ──────────────────────────────────────────────────────

  { id:"ev-001", group:"evaluation", difficulty:"easy", type:"short",
    question:"What is the difference between precision, recall, and F1-score?",
    answer:"Precision: of all positive predictions, what fraction are correct? TP/(TP+FP). Recall (sensitivity): of all actual positives, what fraction did the model find? TP/(TP+FN). F1: harmonic mean of precision and recall: 2×P×R/(P+R). Harmonic mean penalises imbalance — if either P or R is very low, F1 is low. Use precision when false positives are costly (spam filter: don't mark real emails as spam). Use recall when false negatives are costly (cancer detection: don't miss cases).",
    explanation:"F1 is always ≤ min(P,R). If P=0.9, R=0.1: arithmetic mean=0.5 (misleadingly high), F1=0.18 (correctly low). Micro vs macro F1: macro F1 = average F1 per class (treats all classes equally regardless of support); micro F1 = global precision and recall (weights classes by frequency). For imbalanced datasets: macro F1 is usually more informative.",
    tags:["turing","andela","core","frequently-tested"] },

  { id:"ev-002", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is AUC-ROC and what does an AUC of 0.85 mean?",
    answer:"ROC curve: plots True Positive Rate (recall) vs False Positive Rate (1-specificity) at all classification thresholds. AUC (Area Under the Curve): probability that the model ranks a randomly chosen positive example higher than a randomly chosen negative example. AUC=0.85: for a random positive-negative pair, the model correctly ranks the positive higher 85% of the time. AUC=0.5: random (no discriminative power). AUC=1.0: perfect classifier. AUC=0.0: perfectly wrong (flip predictions).",
    explanation:"AUC is threshold-independent — evaluates overall ranking quality, not a specific decision threshold. Use AUC when: class balance doesn't matter for the metric, you want to evaluate the model's overall discriminative ability across all operating points. Limitation: AUC can be high even if calibration is poor (confidently wrong). Use Brier Score or log-loss for calibration.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"ev-003", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is the precision-recall curve and when do you use it instead of ROC-AUC?",
    answer:"PR curve: plots precision vs recall at all classification thresholds. AUC-PR: area under the PR curve. Use PR curve when: (1) Class imbalance is severe — ROC-AUC is optimistic for imbalanced datasets because a classifier that predicts 'negative' always has low FPR. (2) You care about positive class performance (rare event detection, anomaly detection, fraud). AUC-PR baseline: equal to the prevalence rate (fraction of positive class), not 0.5.",
    explanation:"Imbalanced example (1% positives): a classifier that labels everything negative has ROC-AUC=0.5 (bad), but a model that just labels the 100 most suspicious examples positive might achieve AUC-PR=0.7 (good). The PR curve shows whether the model can find positives precisely — much more informative for rare events than ROC-AUC.",
    tags:["toptal","andela"] },

  { id:"ev-004", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is the confusion matrix and what does each cell represent?",
    answer:"A 2×2 matrix for binary classification: True Positive (TP): model predicts positive, label is positive — correct. True Negative (TN): model predicts negative, label is negative — correct. False Positive (FP, Type I error): model predicts positive, label is negative — wrong, false alarm. False Negative (FN, Type II error): model predicts negative, label is positive — wrong, missed detection. Precision = TP/(TP+FP). Recall = TP/(TP+FN). Specificity = TN/(TN+FP). NPV = TN/(TN+FN).",
    explanation:"Reading a confusion matrix: rows = actual class, columns = predicted class (or vice versa — always check labelling). Off-diagonal elements are errors. Diagonal elements are correct predictions. For multi-class: N×N matrix where cell (i,j) = number of class-i examples predicted as class-j. Row normalisation shows per-class recall.",
    tags:["turing","andela","core"] },

  { id:"ev-005", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is cross-validation and why is it important for model evaluation?",
    answer:"K-fold cross-validation: split data into k folds. Train on k-1 folds, evaluate on the held-out fold. Repeat k times rotating the test fold. Average performance across k evaluations. Benefits: (1) Uses all data for both training and evaluation. (2) Reduces variance of the performance estimate (uses multiple train/test splits). (3) Detects overfitting to one particular split. Common choices: k=5 or k=10 (bias-variance tradeoff — small k: high variance, high bias; large k: low variance, low bias, computationally expensive).",
    explanation:"Stratified k-fold: preserve the class proportion in each fold — important for imbalanced datasets. Leave-one-out (LOO): k=N — maximum use of data, very high variance for small N. Nested cross-validation: outer loop evaluates generalisation, inner loop selects hyperparameters — unbiased estimate when also doing hyperparameter tuning. Group k-fold: keep all samples from one group in the same fold — prevents data leakage when samples within a group are correlated.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"ev-006", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is data leakage and how does it create artificially high evaluation metrics?",
    answer:"Data leakage: information from the test set leaks into the training process, causing the model to 'see the answer' — inflated performance that doesn't generalise. Types: (1) Target leakage: features derived from the future (after the label is determined). Example: including tomorrow's features to predict today's event. (2) Train-test contamination: normalisation statistics (mean, std) computed on the entire dataset (including test) and used to normalise training data. (3) Temporal leakage: using future data to predict the past in time-series tasks.",
    explanation:"Common leakage mistakes: (1) Fitting a scaler on all data before train/test split (correct: fit only on train). (2) Using patient outcomes data collected after diagnosis as features. (3) Near-duplicate samples in both train and test. (4) Using a feature that causally depends on the target. Symptom: perfect train/val performance that fails at deployment. Always maintain a strict temporal or logical separation between what the model can observe and what it predicts.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"ev-007", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is model calibration and how is it measured?",
    answer:"A well-calibrated model: when it predicts 80% confidence, the actual frequency of being correct is 80%. Calibration measures agreement between predicted probabilities and empirical frequencies. Reliability diagram: group predictions by confidence bins (e.g., 0-10%, 10-20%,...), plot average confidence vs average accuracy per bin. Perfectly calibrated: diagonal line. Overconfident: above diagonal. Underconfident: below diagonal. Quantitative metric: Expected Calibration Error (ECE) = Σ|B_m|/N × |acc(B_m) - conf(B_m)|.",
    explanation:"Why calibration matters: in medical diagnosis, a model that says '90% cancer' when it means 60% leads to over-treatment. In risk systems, calibrated probabilities enable correct decision thresholds. Tree-based models and deep networks are typically overconfident without calibration. Calibration methods: Platt scaling (logistic regression on model output), isotonic regression, temperature scaling for neural nets.",
    tags:["toptal","andela"] },

  { id:"ev-008", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is the difference between offline and online (A/B test) evaluation?",
    answer:"Offline evaluation: evaluate model on a static held-out test set before deployment. Fast, reproducible, no user impact. Limitation: test set may not represent production distribution; doesn't capture feedback loops or long-term user behaviour changes. Online A/B test: split live traffic randomly between model A (control) and model B (treatment). Measure real business metrics (CTR, revenue, retention). Gold standard for measuring true business impact. Limitations: takes time (statistical significance), needs infrastructure, may expose users to a worse model.",
    explanation:"Statistical considerations in A/B tests: required sample size = 16σ²/δ² per variant (for 80% power, 5% significance, effect size δ, variance σ²). For large δ (big expected improvement): few thousand users needed. For small δ (marginal improvement): millions needed — slow. Multi-armed bandit: dynamically allocates more traffic to the better-performing variant while still exploring — faster learning, less exposure to inferior model.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"ev-009", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is BLEU score and what are its limitations for evaluating text generation?",
    answer:"BLEU (Bilingual Evaluation Understudy): measures n-gram overlap between generated text and reference translations. Score: geometric mean of 1-gram through 4-gram precision, multiplied by a brevity penalty (penalises short outputs). Range: 0-1. Originally designed for machine translation. Limitations: (1) Penalises paraphrases — different words with same meaning score zero. (2) Doesn't capture semantics — only exact n-gram matches. (3) Poor correlation with human judgement for open-ended generation. (4) Can be gamed by repeating common n-grams.",
    explanation:"Alternatives: ROUGE (recall-oriented, used for summarisation), METEOR (includes stemming and synonyms), BERTScore (semantic similarity via BERT embeddings — better correlation with humans), MoverScore (earth mover's distance in embedding space), BLEURT (trained metric on human judgements). In 2026: human evaluation or LLM-as-judge is preferred for open-ended text generation; BLEU/ROUGE for constrained tasks (translation).",
    tags:["toptal","andela","frequently-tested"] },

  { id:"ev-010", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is ROUGE and how does it differ from BLEU?",
    answer:"ROUGE (Recall-Oriented Understudy for Gisting Evaluation): recall-oriented n-gram overlap. ROUGE-N: n-gram recall between generated and reference. ROUGE-1: unigram recall. ROUGE-2: bigram recall. ROUGE-L: longest common subsequence-based recall. Standard for summarisation evaluation. BLEU is precision-oriented (how much of the generated text appears in the reference). ROUGE is recall-oriented (how much of the reference appears in the generated text). For summarisation: want high recall (capture the key points) — ROUGE is appropriate.",
    explanation:"ROUGE-L: finds the longest common subsequence — rewards in-order matching without requiring consecutive matches. More flexible than ROUGE-2 for paraphrase. Practical use: ROUGE-1 and ROUGE-2 for abstractive summarisation evaluation (CNN/DailyMail dataset uses ROUGE). ROUGE scores have moderate correlation with human judgement (0.6-0.7) — better than BLEU for summarisation, but still imperfect.",
    tags:["toptal","andela"] },

  { id:"ev-011", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is BERTScore and why does it better correlate with human judgement?",
    answer:"BERTScore: compute token embeddings for generated and reference text using a pretrained BERT model. Match each reference token to its most similar generated token (and vice versa) by cosine similarity. Score = average of recall (reference→generated), precision (generated→reference), and F1. Captures semantic similarity — 'car' and 'automobile' are similar in embedding space even though they're different n-grams. Roberta or DeBERTa layers give best results. Correlation with human judgements: substantially better than BLEU/ROUGE for open-ended text.",
    explanation:"BERTScore layers: which BERT layer gives the best results depends on the task. Upper layers: more semantic. Lower layers: more syntactic. Optimal layer varies by task (typically layer 9-12 for English BERT-base). IDF weighting: weight token scores by inverse document frequency — rare, task-specific words count more than common function words. BERTScore is the standard reference-based LLM evaluation metric in NLP research papers.",
    tags:["toptal"] },

  { id:"ev-012", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is human evaluation for LLMs and what scales are used?",
    answer:"Human evaluation: human judges rate or compare LLM outputs. Methods: (1) Likert scale: rate responses 1-5 on dimensions (helpfulness, harmlessness, accuracy). (2) Pairwise comparison: which of two responses (A or B) is better? More reliable than Likert (reduces individual rating biases). (3) Elo rating: aggregate pairwise comparisons to a continuous skill rating (Chatbot Arena model). Dimensions: factual accuracy, coherence, relevance, safety, helpfulness, verbosity. Annotation guidelines must define each dimension precisely.",
    explanation:"Inter-annotator agreement: κ (Cohen's kappa) or Krippendorff's α. Kappa > 0.7: good agreement. Kappa < 0.4: poor agreement — rethink task definition or train annotators better. Pairwise comparisons: typically higher agreement than Likert scale (binary choice is simpler than a 5-point scale). Chatbot Arena: crowdsourced pairwise evaluation by the public — millions of comparisons, well-calibrated Elo ratings.",
    tags:["toptal","andela"] },

  { id:"ev-013", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is Goodhart's Law in ML evaluation and why does it matter?",
    answer:"Goodhart's Law: 'When a measure becomes a target, it ceases to be a good measure.' In ML: once you optimise directly for an evaluation metric, the model finds ways to maximise the metric that don't correspond to genuine improvement. Examples: BLEU gaming (generate texts with common n-grams regardless of content), RLHF reward model gaming (generate verbose responses that humans rate highly regardless of accuracy), benchmark contamination (training on test set data inflates scores).",
    explanation:"Practical examples: (1) A student model fine-tuned to maximise BLEU learns to copy n-grams from the source, not to translate. (2) An LLM trained with RLHF learns to produce long, confident-sounding answers that humans rate highly regardless of factual accuracy. (3) Models 'test on training data' via pretraining contamination inflating benchmark scores. Mitigation: use diverse, hard-to-game metrics; use human evaluation; regularly update benchmarks.",
    tags:["toptal","andela"] },

  { id:"ev-014", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is a train-val-test split and how should proportions be chosen?",
    answer:"Standard split: 70-15-15 or 80-10-10 (train-val-test). Train: model learns from this. Val: model selection, hyperparameter tuning — can look at this repeatedly. Test: one-time final evaluation of the chosen model — must never influence any model or pipeline decision. Small datasets (<1000): use cross-validation (no separate test set is large enough). Large datasets (>1M): even 1% test = 10k samples, which is plenty for statistical significance.",
    explanation:"Temporal split for time-series: split by time, not randomly. Random split leaks future information into training (a sample from time T in training can inform prediction at time T-1 in test). Correct: train on data up to 2023-01, validate on 2023-01 to 2023-06, test on 2023-06 onwards. Group split: if samples belong to groups (patients, users), ensure no group appears in both train and test — prevents leakage of group-level features.",
    tags:["turing","andela","core"] },

  { id:"ev-015", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is the Matthew Correlation Coefficient (MCC) and when should you use it?",
    answer:"MCC: a balanced metric for binary classification that accounts for all four quadrants of the confusion matrix. MCC = (TP×TN - FP×FN) / √((TP+FP)(TP+FN)(TN+FP)(TN+FN)). Range: -1 to +1. MCC=1: perfect. MCC=0: no better than random. MCC=-1: perfectly wrong. Advantages over F1 and accuracy: equally sensitive to changes in TP, TN, FP, FN — not fooled by class imbalance. A classifier that predicts all negative: MCC=0 (correctly shows no discrimination ability).",
    explanation:"When to use MCC: imbalanced binary classification where accuracy and even F1 can be misleading. Example: 99% negative, 1% positive. A model predicting all negative: accuracy=99%, F1=0 (undefined), MCC=0. MCC is the most honest single metric for binary classification. Limitation: no natural extension to multi-class (use macro-averaged MCC or Cohen's kappa instead).",
    tags:["toptal","andela"] },

  { id:"ev-016", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is bias-variance tradeoff in model evaluation and how do you diagnose each?",
    answer:"Bias: error from underfitting — the model is too simple to capture the data's true patterns. Symptom: high train AND test error. Fix: more complex model, more features, less regularisation. Variance: error from overfitting — the model captures noise rather than signal. Symptom: low train error, high test error (large gap). Fix: more data, regularisation (L1/L2, dropout), simpler model, data augmentation. Total expected error = Bias² + Variance + Irreducible noise.",
    explanation:"Diagnosing from learning curves: plot train and val error vs. training set size. High bias: both curves converge to a high value (adding more data doesn't help much). High variance: large gap between train and val errors (adding more data helps, gap narrows). Perfectly balanced: both curves converge to a low value with a small gap.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"ev-017", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is PERPLEXITY as a metric for language models?",
    answer:"Perplexity = exp(average negative log-probability per token) = exp(L) where L is cross-entropy loss. Intuition: the effective vocabulary size the model is 'confused between' at each step. Perplexity=7.4 means the model is choosing between ~7 equally likely next tokens on average. Lower is better. Baseline: unigram model (just predicts the most common tokens) has perplexity ≈ vocabulary size. Good LLM on English text: perplexity < 20.",
    explanation:"Perplexity is computed on a held-out test set, not the training set. It measures how well the model generalises. Perplexity is dataset-dependent — can't compare across datasets (a model trained on formal text will have higher perplexity on casual Twitter text). For domain adaptation evaluation: compute perplexity on the target domain text before and after fine-tuning.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"ev-018", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is a holdout set vs. test set and why should the test set be used only once?",
    answer:"Holdout/validation set: used during development for model selection, hyperparameter tuning, early stopping — can be used multiple times. Each use 'costs' some information (you implicitly tune toward the validation set). Test set: reserved entirely for final performance estimation — used exactly once, at the very end. Why only once: every time you look at the test set and adjust based on it, you're implicitly fitting to it — test set performance becomes an overestimate of true generalisation (multiple comparisons problem).",
    explanation:"Multiple testing problem: if you evaluate 100 models on the same test set and pick the best, the best model will likely be better than it would be on new data due to chance. This is why Kaggle competitions use a separate private leaderboard. In practice: use the test set only to report final published numbers. All tuning goes on the validation set.",
    tags:["toptal","andela","core"] },

  { id:"ev-019", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is statistical significance in ML experiments and how do you establish it?",
    answer:"Statistical significance: the probability that the observed performance difference is due to chance rather than a genuine model improvement. t-test: for comparing two means (e.g., two model's accuracy across k cross-validation folds). McNemar's test: specifically for comparing classifiers on the same test set (compares which examples each model gets right/wrong). Bootstrap confidence intervals: resample the test set with replacement, compute metric each time — the 95% CI gives the uncertainty in the metric estimate.",
    explanation:"In practice: run 5-10 random seeds per model, report mean ± std. If the error bars don't overlap, the difference is likely significant. For small improvements (<1%), require explicit significance testing. For large improvements (>5% on diverse benchmarks), statistical significance is less critical. Common mistake: reporting only one run's result without variance — cherry-picking a lucky seed.",
    tags:["toptal","andela"] },

  { id:"ev-020", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is benchmark contamination and how does it affect LLM evaluation?",
    answer:"Benchmark contamination: test set examples from the benchmark appear in the LLM's pretraining data. The model has 'seen the answer' during training — test performance is inflated and doesn't reflect true generalisation. Sources: MMLU, GSM8K, HumanEval examples were present in CommonCrawl before LLMs were trained — models may memorise them. Detection: n-gram overlap between training data and test examples, canary sequences, held-out private benchmarks.",
    explanation:"Mitigation: (1) Use private benchmarks with controlled access (GPQA, LMSYS Arena). (2) Dynamic benchmarks that update regularly (LiveBench). (3) Membership inference attacks to detect contamination. (4) Report both contaminated and decontaminated scores. In 2026: GSM8K and MMLU are largely saturated and contaminated — the field has moved to harder benchmarks (AIME, GPQA, LiveCodeBench) that are harder to contaminate.",
    tags:["toptal","frequently-tested"] },

  { id:"ev-021", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is the Chatbot Arena (LMSYS) and how does its Elo rating system work?",
    answer:"Chatbot Arena: a platform where users compare two anonymous LLM responses to the same prompt and vote for the better one. Thousands of crowdsourced pairwise comparisons per model. Elo rating: start each model at 1000, update based on outcomes: if model A beats model B: A gains K×(1-Ea) points, B loses K×Eb points, where Ea = expected win probability. Expected probability: Ea = 1/(1 + 10^{(Rb-Ra)/400}). K=32 is the learning rate. Result: continuous, well-calibrated skill rating for LLMs based on real human preferences.",
    explanation:"Chatbot Arena is considered the gold standard for LLM ranking because: (1) Real users, real queries, not synthetic benchmarks. (2) Pairwise comparison is more reliable than absolute ratings. (3) Very large sample size (millions of votes). (4) Models can't 'cheat' — they don't know they're being evaluated. Limitation: users skew toward tech-savvy demographics; their preferences may not represent all use cases.",
    tags:["toptal","andela"] },

  { id:"ev-022", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is mean reciprocal rank (MRR) and how is it used in information retrieval evaluation?",
    answer:"MRR = (1/Q) × Σ_q (1/rank_q), where rank_q is the position of the first relevant document in the ranked list for query q. Example: queries return relevant docs at positions [1, 3, 5] → MRR = (1/3)×(1/1 + 1/3 + 1/5) = 0.51. MRR focuses on the position of the first relevant result — appropriate when users care about finding at least one good result quickly. Used for: QA (does the correct answer appear in top-k?), recommendation (is the relevant item in the first results?).",
    explanation:"Mean Average Precision (MAP): average precision across all relevant documents in the ranked list, then averaged over queries. More comprehensive than MRR — measures whether all relevant documents are ranked highly, not just the first. NDCG (Normalised Discounted Cumulative Gain): assigns higher credit to relevant documents in top positions (logarithmic discount). Standard metric for search engine and recommendation system evaluation.",
    tags:["toptal","andela"] },

  { id:"ev-023", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is NDCG (Normalised Discounted Cumulative Gain) and when is it used?",
    answer:"DCG@k: sum of relevance scores, discounted by log₂(position+1). DCG@k = Σᵢ₌₁ᵏ rel_i/log₂(i+1). NDCG@k = DCG@k / ideal_DCG@k, normalised to [0,1]. Handles: multiple relevance levels (0=not relevant, 1=somewhat, 2=very relevant), position-aware (top results matter more). Logarithmic discount: rank-1 gets no discount, rank-2 discounted by log₂(3)≈1.58, rank-10 discounted by log₂(11)≈3.46. Standard metric for: web search ranking, recommendation systems, information retrieval.",
    explanation:"NDCG@10 for web search: measures quality of the top 10 results. An ideal ranked list has all most-relevant results first. If NDCG@10=0.85, the system achieves 85% of the ideal ranking quality. NDCG is preferred over MAP for: graded relevance (not just binary), position sensitivity. Limitation: requires relevance judgements for each query-document pair — expensive to collect.",
    tags:["toptal","andela"] },

  { id:"ev-024", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is FAccT (Fairness, Accountability, and Transparency) evaluation for ML models?",
    answer:"Fairness evaluation: measure whether model performance is equal across demographic groups (gender, race, age). Fairness metrics: (1) Demographic parity: P(Ŷ=1|A=0) = P(Ŷ=1|A=1) — same positive rate across groups. (2) Equal opportunity: P(Ŷ=1|Y=1,A=0) = P(Ŷ=1|Y=1,A=1) — same recall/true positive rate across groups. (3) Equalised odds: both recall and specificity equal across groups. (4) Calibration: same accuracy at each predicted score level across groups.",
    explanation:"Impossibility theorem (Chouldechova, 2017): you cannot simultaneously achieve calibration + equal positive predictive value + equal false positive rate when base rates differ across groups. This means perfect fairness is mathematically impossible — must choose which fairness criterion is most important for the application. COMPAS recidivism tool controversy: debate over whether to equate FPR or PPV across racial groups.",
    tags:["toptal","andela"] },

  { id:"ev-025", group:"evaluation", difficulty:"hard", type:"short",
    question:"What is TruthfulQA and why was it designed to test LLM truthfulness differently?",
    answer:"TruthfulQA (Lin et al., 2022): 817 questions across 38 categories designed to test whether LLMs generate truthful responses. Questions are adversarial — they target common human misconceptions that LLMs often mimic from training data (e.g., 'What happens if you swallow watermelon seeds?'). Scoring: percentage of truthful responses. Key finding: larger LLMs are sometimes less truthful (more likely to reproduce plausible-sounding false claims from the internet). Unlike MMLU (knowledge recall), TruthfulQA tests whether models confidently state falsehoods.",
    explanation:"Design principle: if a claim is commonly believed but false (e.g., 'Napoleon was short for his time' — he was actually average height), LLMs trained on human-generated text will likely reproduce the false claim. TruthfulQA forces models to distinguish between 'commonly stated' and 'actually true'. Models with high TruthfulQA scores learn to say 'I don't know' or qualify uncertain claims rather than confidently stating falsehoods.",
    tags:["toptal"] },

  { id:"ev-026", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is MT-Bench and how does it use LLM-as-judge evaluation?",
    answer:"MT-Bench (Zheng et al., 2023): 80 multi-turn conversation questions across 8 categories (writing, roleplay, reasoning, math, coding, extraction, STEM, humanities). Each question has a follow-up question. LLM-as-judge: GPT-4 scores each response on a 1-10 scale based on helpfulness, relevance, accuracy, depth, creativity. The model score is the average across all 80 questions. Advantages: more representative of real use cases than single-turn benchmarks, evaluates multi-turn consistency, scales without human annotators.",
    explanation:"MT-Bench correlation with human preferences: ~0.8, making it a reliable automated proxy. Known biases: GPT-4 as judge has self-preference bias (rates GPT-4 responses higher), length bias (prefers longer responses). Mitigation: swap response order and average scores, use multiple judges. MT-Bench scores: GPT-4: 8.99, LLaMA-3-70B-Instruct: ~8.2, LLaMA-3-8B-Instruct: ~7.9.",
    tags:["toptal","andela"] },

  { id:"ev-027", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is perplexity on a domain-specific test set and how is it used for model comparison?",
    answer:"Perplexity measures how well the model predicts a test set from a specific domain. Lower perplexity = model is better adapted to that domain. Uses: (1) Comparing base model vs. domain-fine-tuned model on domain text. (2) Selecting the best fine-tuning checkpoint. (3) Monitoring training stability (perplexity should decrease monotonically with healthy training). Domain-specific perplexity is more informative than general benchmark scores for specialised applications (medical, legal, code generation).",
    explanation:"Limitation: perplexity doesn't directly measure task performance. A model with lower perplexity on medical text isn't guaranteed to answer medical questions correctly — it may be better at predicting common medical vocabulary without understanding clinical reasoning. Use perplexity as one signal; complement with task-specific accuracy metrics on the target application.",
    tags:["toptal","andela"] },

  { id:"ev-028", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is bias evaluation in LLMs and what benchmarks are used?",
    answer:"Bias evaluation: measure whether LLMs produce different outputs based on demographic attributes that should be irrelevant (race, gender, religion, nationality). Benchmarks: (1) WinoBias: pronoun coreference resolution in gender-stereotyped scenarios. (2) StereoSet: completion preferences for stereotyped vs. non-stereotyped associations. (3) BBQ (Bias Benchmark for QA): ambiguous QA that requires using stereotypes without context. (4) BOLD: model completions for demographic groups. (5) HONEST: harmful language for different social groups.",
    explanation:"Types of bias: representation bias (underrepresentation of certain groups in training → weaker performance for those groups), stereotyping (reproducing social stereotypes from training data), toxicity (higher toxicity for outputs about certain groups). Evaluating bias is challenging: measuring one type may introduce another. Mitigation: diverse training data, RLHF with fairness criteria, red teaming specific demographic groups.",
    tags:["toptal","andela"] },

  { id:"ev-029", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is the difference between intrinsic and extrinsic evaluation of NLP models?",
    answer:"Intrinsic evaluation: measure properties of the model directly, independent of a downstream task. Examples: perplexity (LM quality), embedding analogy accuracy (word2vec 'king-man+woman=queen'), probing tasks (classify syntactic/semantic properties from embeddings). Fast, cheap, informative about the model's internal representations. Extrinsic evaluation: evaluate on downstream task performance. Examples: MMLU accuracy, code generation (pass@k), QA F1, translation BLEU. More relevant to practical use but slower and task-specific.",
    explanation:"Intrinsic evaluation is useful for: comparing pretrained models before fine-tuning, understanding what properties a model has learned, identifying potential failure modes. Extrinsic evaluation is the ground truth — a model that scores well intrinsically should perform well extrinsically, but this correlation is imperfect. Best practice: use both. Intrinsic evaluation during training (perplexity), extrinsic at checkpoints (downstream task benchmarks).",
    tags:["toptal"] },

  { id:"ev-030", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is the pass@k metric for code generation evaluation?",
    answer:"pass@k: probability that at least one of k generated code samples passes all test cases. Computation: sample n solutions (n > k), count c solutions that pass. Unbiased estimator: pass@k = 1 - C(n-c, k)/C(n, k). HumanEval benchmark: 164 programming problems, pass@1 (greedy), pass@10, pass@100. GPT-4: pass@1 ≈ 85%. Claude 3.5 Sonnet: pass@1 ≈ 93%. pass@1 measures the quality of the best single generation; pass@k at higher k measures whether the correct solution is achievable with sampling.",
    explanation:"pass@k interpretation: pass@1 = typical user experience (one shot). pass@10 = developer uses a code generation tool and picks the best of 10 suggestions. pass@100 = upper bound on what the model can achieve with repeated sampling. High pass@1 but low pass@10/100 suggests a model that rarely generates working code. High pass@100 but low pass@1 suggests the model can solve the problem but needs many tries.",
    tags:["toptal","frequently-tested"] },

  { id:"ev-031", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is the difference between accuracy and balanced accuracy?",
    answer:"Accuracy: (TP + TN) / (TP + TN + FP + FN). Misleading for imbalanced datasets — a model that predicts all 'negative' on a 99% negative dataset has 99% accuracy. Balanced accuracy: average recall per class = (recall_positive + recall_negative) / 2 = (TP/(TP+FN) + TN/(TN+FP)) / 2. A model predicting all negative: 0% recall on positive class → balanced accuracy = 50%. For multi-class: average per-class recall.",
    explanation:"When to use each: balanced accuracy or macro-averaged metrics for imbalanced datasets where each class is equally important. Accuracy for balanced datasets or when majority class performance is the primary concern. Medical diagnosis: almost always use balanced accuracy or sensitivity/specificity separately — missing a disease (low recall) is much worse than a false alarm (low precision).",
    tags:["toptal","andela"] },

  { id:"ev-032", group:"evaluation", difficulty:"easy", type:"mcq",
    options:["Precision", "Recall", "F1-score", "AUC-ROC"],
    question:"Which metric is most appropriate when the cost of false negatives is very high (e.g., cancer detection)?",
    answer:"Recall",
    explanation:"Recall = TP/(TP+FN) measures how many actual positives the model correctly identifies. When missing a positive (false negative) is very costly — a missed cancer diagnosis — maximising recall is the priority, even at the expense of lower precision (more false alarms). The clinical strategy: high-recall screening test followed by high-precision confirmation test.",
    tags:["turing","andela"] },

  { id:"ev-033", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is the difference between micro, macro, and weighted averaging for multi-class metrics?",
    answer:"Micro averaging: aggregate TP, FP, FN across all classes, then compute metric. Treats each sample equally — dominated by majority class. Macro averaging: compute metric per class, take unweighted average. Treats all classes equally regardless of support — sensitive to minority class performance. Weighted averaging: compute metric per class, take support-weighted average. Balances between micro and macro — accounts for class size but gives more weight to larger classes.",
    explanation:"Example (binary, imbalanced: 990 negative, 10 positive, model has 100% accuracy on negative, 70% recall on positive): Micro recall = (990+7)/(990+10) = 99.7%. Macro recall = (100% + 70%)/2 = 85%. Weighted recall = (990×100% + 10×70%)/1000 = 99.7%. Micro and weighted are both distorted by class imbalance. For imbalanced datasets: always report macro or per-class metrics alongside overall accuracy.",
    tags:["toptal","andela"] },

  { id:"ev-034", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is a learning curve and what diagnostic information does it provide?",
    answer:"Learning curve: plot training metric and validation metric vs. number of training examples (or training steps). Shapes: (1) High bias (underfitting): both train and val performance are similar but poor — adding more data doesn't help. (2) High variance (overfitting): large gap between train (good) and val (poor) — adding more data helps (gap narrows, val improves). (3) Good fit: both converge to good performance with small gap. (4) Noisy data: val loss high and erratic even with simple model — data quality issue.",
    explanation:"Practical use: when val performance plateaus but is below acceptable level: if high-bias, make the model more complex; if high-variance, get more data or regularise. When train accuracy is perfect but val is poor: classic overfitting — regularise, use dropout, early stopping, more data. Plot with logarithmic x-axis (data size) to show learning efficiently across orders of magnitude.",
    tags:["toptal","andela"] },

  { id:"ev-035", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is FActScore and how does it evaluate LLM factual accuracy?",
    answer:"FActScore (Min et al., 2023): evaluation framework for factual precision of LLM-generated text. Process: (1) LLM generates a response. (2) A parser (another LLM) decomposes the response into atomic facts (individual claim statements). (3) Each atomic fact is independently verified against a knowledge source (Wikipedia) using a retrieval + NLI pipeline. (4) FActScore = fraction of atomic facts supported by the knowledge source. Measures factual precision — how much of what the model claims is actually true.",
    explanation:"FActScore findings: on biographical generation tasks, GPT-3.5 has FActScore ≈ 55% (only 55% of claims are supported). GPT-4: ~73%. Claude 3: ~78%. These surprisingly low numbers reflect that even frontier LLMs frequently confabulate supporting details. FActScore is more granular than just 'right or wrong' — it pinpoints which facts are unsupported.",
    tags:["toptal"] },

  { id:"ev-036", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is the ROC curve and how do you set the classification threshold?",
    answer:"ROC curve: plots TPR vs FPR at all thresholds from 0 to 1. At threshold=0: predict positive for all → TPR=1, FPR=1 (top-right). At threshold=1: predict positive for none → TPR=0, FPR=0 (bottom-left). The curve shows the trade-off between sensitivity (recall) and specificity (1-FPR) at every threshold. Setting the threshold: choose based on business cost of FP vs FN. Youden's J statistic: maximise TPR-FPR. F1-maximising threshold: find threshold that maximises F1 on the validation set.",
    explanation:"Different applications require different thresholds: fraud detection: set low threshold (high recall, accept more false alarms — blocking a real transaction costs money but is recoverable). Medical screening: low threshold (missing a positive is very costly). Spam filter: high threshold (false positive — marking real email as spam — is very costly). Always tune the threshold on the validation set, never the test set.",
    tags:["toptal","andela"] },

  { id:"ev-037", group:"evaluation", difficulty:"hard", type:"short",
    question:"What is GPQA (Graduate-Level Google-Proof QA) and why was it created?",
    answer:"GPQA (Rein et al., 2023): 448 multiple-choice questions in biology, chemistry, and physics at graduate PhD level, written by domain experts. 'Google-proof': questions are specifically designed so that searching Google for the answer doesn't help — they require genuine expert reasoning, not memorisation. Motivation: most benchmarks (MMLU, TriviaQA) are too easy for frontier models (saturated at 85%+) or can be solved by web search. GPQA is genuinely hard — non-expert humans who can search freely score only ~34%. PhD experts score ~65%. GPT-4: ~50%, Claude 3 Opus: ~60%, o3: ~87.7%.",
    explanation:"GPQA represents a new generation of benchmarks designed to remain challenging as models improve. The expert-level difficulty means: (1) No contamination advantage (answers aren't on the web). (2) Tests deep reasoning, not memorisation. (3) Provides clear signal even for the best models. Similar ultra-hard benchmarks: ARC-AGI (abstract reasoning), FrontierMath (unpublished math research problems).",
    tags:["toptal","frequently-tested"] },

  { id:"ev-038", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is the difference between semantic and lexical evaluation metrics?",
    answer:"Lexical metrics (n-gram based): BLEU, ROUGE, METEOR. Compare the exact words and n-grams. Fast, deterministic, no model needed. Limitations: 'the movie was great' and 'the film was excellent' score 0 overlap even though they're semantically equivalent. Semantic metrics (embedding-based): BERTScore, MoverScore, BLEURT. Encode text with a language model, compare in embedding space. Handle synonyms, paraphrases, and semantic equivalence. Slower (requires LM inference), may have their own biases.",
    explanation:"In practice: lexical metrics are standard for constrained generation tasks (translation, structured extraction) where exact term matching matters. Semantic metrics are better for open-ended generation (dialogue, summarisation, creative writing). Combine both for a comprehensive evaluation. For LLM evaluation: LLM-as-judge (using GPT-4 to score) is increasingly replacing both, especially for subjective tasks.",
    tags:["toptal","andela"] },

  { id:"ev-039", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is held-out evaluation and how is it different from cross-validation?",
    answer:"Held-out evaluation: a fixed, single split — some percentage of data set aside from the beginning, never used for training or model selection. Final model evaluated once on this held-out set. Simple, fast, but wasteful of data and has higher variance (results depend on which samples ended up in the test set). Cross-validation: multiple train-test splits, average performance. Uses all data, lower variance, but takes k× as long. Use held-out for: large datasets, when training is expensive (LLMs). Use CV for: small datasets, when test set would be too small for reliable estimation.",
    explanation:"Test set size for reliable estimation: with N=1000 test samples and 95% accuracy, the 95% CI is ±1.35% (by the normal approximation). With N=100: ±4.3%. To detect a 1% improvement reliably: need ~4000 test samples. For LLM benchmarks like MMLU (14,000 questions): each subject has 100-1000 questions — moderate statistical power.",
    tags:["andela","core"] },

  { id:"ev-040", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is the difference between a proxy metric and a true objective metric?",
    answer:"True objective: what you actually care about (user satisfaction, revenue, health outcome). Hard to measure directly or in real-time. Proxy metric: something measurable that correlates with the true objective. Examples: click-through rate (proxy) vs long-term user satisfaction (true), loss on validation set (proxy) vs real-world accuracy (true), BLEU score (proxy) vs translation quality as judged by native speakers (true). The risk: proxy metrics and true objectives diverge — Goodhart's Law.",
    explanation:"Proxy metric selection: choose proxies that correlate strongly with the true objective and are hard to game. Examples of bad proxies: session time (users might be confused and spend more time — negative engagement), number of recommendations clicked (optimising CTR leads to clickbait). Good proxies: carefully validated against the true objective via surveys or causal studies, updated when misalignment is detected.",
    tags:["toptal","andela"] },

  { id:"ev-041", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is Recall@K and Precision@K in information retrieval?",
    answer:"For a query with k retrieved results and ground truth of n relevant documents: Precision@K: fraction of retrieved docs that are relevant = |retrieved ∩ relevant| / k. Recall@K: fraction of relevant docs that were retrieved = |retrieved ∩ relevant| / n. Example: k=5, n=10, 3 retrieved docs are relevant: P@5 = 3/5 = 60%, R@5 = 3/10 = 30%. Hit rate@K (for RAG): binary — is at least one relevant document in the top K? More meaningful for RAG than precise recall.",
    explanation:"For RAG evaluation: Recall@K measures whether the necessary information for answering the question was retrieved. If Recall@10 = 80%, 80% of queries had their answer in the top-10 retrieved chunks. The remaining 20% will likely produce incorrect answers regardless of LLM quality. Increasing k improves recall but pollutes context with irrelevant chunks — use reranking to maintain precision after high-k retrieval.",
    tags:["toptal","andela"] },

  { id:"ev-042", group:"evaluation", difficulty:"hard", type:"short",
    question:"What is AlpacaEval and how does it measure instruction-following LLMs?",
    answer:"AlpacaEval (Li et al., 2023): automated instruction-following evaluation. 805 diverse instruction-following queries from multiple human evaluation datasets. LLM-as-judge: use GPT-4 (or GPT-4-turbo) to compare each model's response to a reference response (from text-davinci-003). Win rate: % of queries where the evaluated model's response is preferred by the judge. AlpacaEval 2: uses length-controlled win rate to correct for verbosity bias — adjusts the win rate for the observed length difference between responses.",
    explanation:"AlpacaEval ranking correlation with Chatbot Arena: very high (~0.9). Makes it a reliable automated proxy for real user preferences. Key: the length-controlled win rate is critical — without it, models that generate longer responses achieve inflated scores. AlpacaEval 2 LC (length-controlled) is now the standard version. Scores in 2026: GPT-4 Turbo: ~50% (reference baseline is GPT-4-level), Claude 3.5 Sonnet: ~57%, LLaMA-3-70B-Instruct: ~34%.",
    tags:["toptal"] },

  { id:"ev-043", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is distribution shift and how does it affect model evaluation?",
    answer:"Distribution shift: the data distribution at inference time differs from the training/test distribution. Types: (1) Covariate shift: P(X) changes but P(Y|X) stays the same. (2) Label shift (prior probability shift): P(Y) changes but P(X|Y) stays the same. (3) Concept drift: P(Y|X) changes — the relationship between features and labels changes. Why it matters: a model that performs well on the test set (same distribution as train) may fail badly in production (different distribution). Test set performance is an overestimate of production performance when there's distribution shift.",
    explanation:"Detection: monitor the distribution of model inputs over time (compare feature statistics to training distribution, use MMD or KL divergence). Monitor model confidence distribution — if predictions shift toward lower confidence, inputs may be out-of-distribution. Detection → trigger retraining or fallback. For LLMs: changes in user query distribution (new topics, languages, formats) cause distribution shift — monitor token distributions and task success rates.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"ev-044", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is error analysis and how do you do it systematically for ML models?",
    answer:"Error analysis: systematic examination of model mistakes to identify patterns and root causes. Steps: (1) Sample N errors from the validation set (100-200 is typically enough for pattern detection). (2) Manually inspect each error, assign a category ('wrong label', 'ambiguous example', 'model confusion about X'). (3) Estimate % of errors in each category. (4) Prioritise fixing categories that account for most errors and are fixable. (5) Measure improvement after each fix.",
    explanation:"Error categories for classifiers: mislabelled training data (fix: re-label), ambiguous examples (fix: clearer definition), edge cases the model hasn't seen (fix: collect more data), specific feature pattern the model misses (fix: add feature or more examples). For LLMs: categories might include factual errors, formatting errors, refusals of valid requests, hallucinations, reasoning errors. Error analysis is the fastest path to meaningful model improvement — faster than trying random improvements.",
    tags:["toptal","andela"] },

  { id:"ev-045", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is ablation study and why is it important in ML research?",
    answer:"Ablation study: systematically remove (ablate) individual components of a system and measure the impact on performance. Tells you which components actually contribute to performance and which are unnecessary. Example: RAG system with (dense retrieval + reranker + query rewriting + HyDE). Ablation: remove each component individually — 'ablating HyDE reduces recall@5 by 12%, ablating reranker reduces precision@5 by 18%, ablating query rewriting has no significant effect'.",
    explanation:"Ablation vs. feature importance: ablation measures the contribution of entire components (full removal), feature importance measures the contribution of individual features (can be partial). In NLP papers: ablation of attention heads, training objectives, data augmentation techniques. In system papers: ablation of each component of a complex pipeline. Without ablation: you don't know if your fancy component is actually doing anything.",
    tags:["toptal","andela"] },

  { id:"ev-046", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is the difference between classification and regression evaluation metrics?",
    answer:"Classification metrics: accuracy, precision, recall, F1, AUC-ROC, MCC, log-loss. For predicting discrete classes. Regression metrics: MAE (mean absolute error), MSE (mean squared error), RMSE, R² (coefficient of determination), MAPE (mean absolute percentage error). For predicting continuous values. R²: proportion of variance explained by the model. R²=0: model predicts the mean. R²=1: perfect. R²<0: model is worse than just predicting the mean (can happen with severe distribution shift).",
    explanation:"RMSE vs MAE: RMSE penalises large errors quadratically — use when large errors are much worse than small ones. MAE: equal penalty per unit error — use when all errors are proportionally equally bad. MAPE: percentage error — use when you care about relative error rather than absolute. Limitation of MAPE: undefined when y=0, biased toward underestimation. Symmetric MAPE (SMAPE) addresses the zero issue.",
    tags:["toptal","andela","core"] },

  { id:"ev-047", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is calibration error and how is it corrected for neural networks?",
    answer:"ECE (Expected Calibration Error): bins predictions by confidence, measures |accuracy - average confidence| per bin, weighted by bin size. A perfectly calibrated model: accuracy matches confidence in each bin. Neural networks are typically overconfident after softmax — they output high-confidence probabilities even for incorrect predictions. Temperature scaling: divide logits by T before softmax; T>1 reduces confidence. Calibrate T on validation set by minimising NLL. Platt scaling: a logistic regression layer trained on validation set to calibrate raw scores.",
    explanation:"Post-hoc calibration methods: (1) Temperature scaling: one parameter, strong regularisation, works well for NNs. (2) Isotonic regression: non-parametric, more flexible, needs more data. (3) Histogram binning: bin predictions, replace with empirical accuracy. RLHF-tuned LLMs: better calibrated than base LLMs (human preference optimisation indirectly improves calibration). LLM calibration: measure how often 'I'm 90% confident' answers are correct — well-calibrated LLMs are 90% correct on these.",
    tags:["toptal"] },

  { id:"ev-048", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is the difference between in-distribution and out-of-distribution (OOD) evaluation?",
    answer:"In-distribution (ID) evaluation: test set from the same distribution as training data. Measures how well the model generalises within the training domain. Standard train-val-test split is ID evaluation. Out-of-distribution (OOD) evaluation: test set from a different distribution — different domain, style, time period, language. Measures robustness and generalisation beyond training distribution. ID performance can be high while OOD performance is poor — the model has memorised distributional patterns rather than learning underlying concepts.",
    explanation:"OOD benchmarks for NLP: WINOGRANDE (commonsense reasoning, different from training distribution), ANLI (adversarially filtered NLI — hard for models). For medical ML: model trained on hospital A's data, evaluated on hospital B's data — common OOD scenario. OOD performance should always be reported for models deployed in diverse real-world settings.",
    tags:["toptal","andela"] },

  { id:"ev-049", group:"evaluation", difficulty:"medium", type:"short",
    question:"What is the difference between macro and micro averaged metrics in NLP evaluation?",
    answer:"Macro average: compute the metric independently for each class, then take the unweighted mean across classes. Gives equal weight to each class regardless of how many examples it has. Macro F1 = (F1_class1 + F1_class2 + ... + F1_classN) / N. Micro average: aggregate counts across all classes (pool all TP, FP, FN), then compute the metric once. Identical to accuracy for multi-class classification. Weights by class frequency.",
    explanation:"When to use: Macro F1 for tasks where each class is equally important regardless of frequency (e.g., named entity recognition with rare entity types). Micro F1 when you want overall correctness regardless of class distribution. For highly imbalanced multi-class: macro F1 better reflects performance on rare classes. For balanced classes: both give similar results.",
    tags:["toptal","andela"] },

  { id:"ev-050", group:"evaluation", difficulty:"hard", type:"short",
    question:"What is SWE-bench Verified and what performance reveals about LLM software engineering ability?",
    answer:"SWE-bench Verified (2024): 500 GitHub issues from Python repositories, manually verified to have unambiguous test coverage. Measures: can the LLM + agentic scaffolding produce a code patch that resolves the real GitHub issue and passes all tests? Reveals: real software engineering requires: (1) Understanding a large codebase context (many files). (2) Planning multi-file changes. (3) Debugging based on test failure messages. (4) Iterating until tests pass. Performance: Claude 3.5 Sonnet (Oct 2024): ~49% resolve rate. GPT-4o: ~33%. Raw LLM without scaffolding: <5%.",
    explanation:"The gap between 'raw LLM' (<5%) and 'LLM + agentic tools' (~49%) shows that the task requires iterative tool use (file editing, test execution, error reading) — not just one-shot code generation. The ~51% failure rate on SWE-bench Verified reflects that many real software engineering tasks require: understanding complex existing code, debugging non-obvious errors, and multi-step planning that remains challenging.",
    tags:["toptal"] },
];
