import type { IQ } from "./interview-data";

export const BANK_A: IQ[] = [

  // ── ML FUNDAMENTALS (50) ──────────────────────────────────────────────────

  { id:"mf-001", group:"ml-fundamentals", difficulty:"easy", type:"short",
    question:"What is the bias-variance tradeoff?",
    answer:"Bias is systematic error from wrong model assumptions (underfitting); variance is sensitivity to training-set fluctuations (overfitting). Total error = bias² + variance + irreducible noise. Increasing model complexity reduces bias but raises variance; the goal is the sweet spot that minimises total test error.",
    explanation:"Regularisation, cross-validation, and ensemble methods all manage this tradeoff. A useful mental model: bias = how wrong your average prediction is; variance = how much predictions scatter around that average.",
    tags:["turing","toptal","andela","core","frequently-tested"] },

  { id:"mf-002", group:"ml-fundamentals", difficulty:"easy", type:"short",
    question:"A model scores 99% on training data but 60% on the test set. What is wrong and how do you fix it?",
    answer:"The model is overfitting — it memorised training patterns instead of learning general rules. Fixes: add regularisation (L1/L2/dropout), get more training data, reduce model complexity, use cross-validation to detect it early, apply early stopping.",
    explanation:"The gap between training and validation accuracy is the primary signal. A 39-point gap here is severe — start with the simplest fix (regularisation or data augmentation) before reducing architecture size.",
    tags:["turing","andela","core"] },

  { id:"mf-003", group:"ml-fundamentals", difficulty:"easy", type:"short",
    question:"What is k-fold cross-validation and why is it preferred over a single train/test split?",
    answer:"The dataset is split into k equal folds. The model trains on k-1 folds and validates on the remaining fold, repeated k times; final performance is the mean across all k scores. It uses all data for both training and validation, giving a lower-variance performance estimate than any single split.",
    explanation:"k=5 or k=10 are standard. Stratified k-fold preserves class proportions in each fold — essential for imbalanced datasets. LOOCV (k=N) is unbiased but expensive for large N.",
    tags:["toptal","andela","core"] },

  { id:"mf-004", group:"ml-fundamentals", difficulty:"medium", type:"mcq",
    options:["L1 (Lasso)","L2 (Ridge)","Dropout","Batch Normalisation"],
    question:"Which regularisation technique produces sparse weight vectors by driving some weights to exactly zero?",
    answer:"L1 (Lasso)",
    explanation:"L1's absolute-value penalty creates a diamond-shaped constraint region whose corners lie on the axes — the optimum frequently falls on a corner where one or more weights are zero. L2's circular constraint has no corners, so weights shrink but rarely reach zero.",
    tags:["toptal","andela","core"] },

  { id:"mf-005", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is the difference between L1 and L2 regularisation mathematically and practically?",
    answer:"L1 adds λΣ|wᵢ| to the loss; L2 adds λΣwᵢ². L1 produces sparse models (feature selection), is non-differentiable at zero, and is robust to outliers. L2 shrinks all weights smoothly, is differentiable everywhere, handles correlated features well, and is equivalent to a Gaussian prior on weights (MAP estimation).",
    explanation:"Elastic Net combines both. Use L1 when you believe many features are irrelevant; use L2 when all features contribute; use Elastic Net when features are correlated and you still want sparsity.",
    tags:["toptal","andela","core"] },

  { id:"mf-006", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is data leakage? Give two concrete examples.",
    answer:"Leakage occurs when information from outside the training distribution (usually the test set or future) contaminates training, causing falsely optimistic performance. Example 1: fitting a StandardScaler on the full dataset before splitting — the scaler has seen test statistics. Example 2: including a post-event feature (e.g., 'loan was defaulted' flag) to predict whether a loan will default.",
    explanation:"Always fit preprocessors (scalers, imputers, encoders) on training data only, then transform validation/test. Use sklearn Pipelines to enforce this automatically.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"mf-007", group:"ml-fundamentals", difficulty:"easy", type:"truefalse",
    options:["True","False"],
    question:"True or False: A model with lower training loss always generalises better than one with higher training loss.",
    answer:"False",
    explanation:"Lower training loss often indicates overfitting. The model that generalises best minimises validation/test loss, not training loss. Regularised models deliberately accept higher training loss to achieve better test performance.",
    tags:["turing","andela"] },

  { id:"mf-008", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"Name three strategies for handling severe class imbalance in binary classification.",
    answer:"1) Resampling — oversample the minority class with SMOTE (synthetic interpolation) or undersample the majority. 2) Class-weighted loss — assign a higher penalty to minority-class misclassifications (class_weight='balanced' in sklearn). 3) Change the evaluation metric — use F1, AUC-PR, or Matthews Correlation Coefficient instead of accuracy, which is misleading when one class dominates.",
    explanation:"Threshold tuning is a fourth option: lower the decision threshold to increase recall at the cost of precision. The right strategy depends on the relative cost of false positives vs. false negatives in the business context.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"mf-009", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is the difference between a parametric and a non-parametric model?",
    answer:"Parametric models have a fixed number of parameters regardless of dataset size (linear regression, logistic regression, neural networks). Non-parametric models grow in complexity with data (KNN, kernel SVM, decision trees, Gaussian Processes). Parametric models are faster and need less memory; non-parametric models are more flexible but can be slow at inference.",
    explanation:"'Non-parametric' does not mean 'no parameters' — it means the effective number of parameters is not fixed before seeing data. A fully grown decision tree has as many leaves as training samples in the extreme case.",
    tags:["toptal","core"] },

  { id:"mf-010", group:"ml-fundamentals", difficulty:"hard", type:"short",
    question:"Explain the curse of dimensionality and its practical implications for ML models.",
    answer:"As dimensionality grows, volume increases exponentially — data becomes sparse and all pairwise distances converge, making distance metrics meaningless. Practical implications: distance-based models (KNN, SVM with RBF) degrade sharply above ~20 features; you need exponentially more data to maintain sample density; overfitting risk rises with feature count; many features increase irrelevant noise.",
    explanation:"Solutions: dimensionality reduction (PCA, UMAP, autoencoders), feature selection, regularisation. Rule of thumb: KNN works reliably up to about 20 features; beyond that, apply PCA first.",
    tags:["toptal","frequently-tested"] },

  { id:"mf-011", group:"ml-fundamentals", difficulty:"easy", type:"short",
    question:"What is the difference between supervised, unsupervised, and self-supervised learning?",
    answer:"Supervised: labelled (input, output) pairs — model learns the mapping. Unsupervised: no labels — model finds structure (clustering, compression, density estimation). Self-supervised: labels derived automatically from the data (predict masked tokens in BERT, predict the next token in GPT) — no human labelling, but a supervised-style loss.",
    explanation:"Self-supervised pretraining followed by supervised fine-tuning is the dominant paradigm in NLP and vision (BERT, GPT, MAE). The self-supervised stage learns rich representations from cheap unlabelled data.",
    tags:["turing","andela","core"] },

  { id:"mf-012", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is the No Free Lunch theorem and what does it mean for practitioners?",
    answer:"Averaged over all possible data distributions, every learning algorithm performs equally — no single algorithm is universally best. In practice: you must choose algorithms based on assumptions about your specific problem domain. Always try multiple algorithms and select based on cross-validated performance on your dataset.",
    explanation:"This theorem is often misused as an excuse not to choose. In practice, tree-based ensembles dominate tabular data, transformers dominate text/images, and CNNs still excel for fixed-size image tasks — these are strong empirical priors even if no theoretical guarantee exists.",
    tags:["toptal"] },

  { id:"mf-013", group:"ml-fundamentals", difficulty:"easy", type:"short",
    question:"When is feature scaling necessary and when is it not?",
    answer:"Necessary for: KNN (distance-based), SVM (margin-based), gradient descent (equal gradient magnitudes across features), PCA (variance-sensitive), logistic/linear regression with regularisation. Not necessary for: tree-based models (Random Forest, XGBoost, LightGBM) — splits are scale-invariant.",
    explanation:"StandardScaler: (x-mean)/std → zero mean, unit variance. MinMaxScaler: (x-min)/(max-min) → [0,1]. Always fit scalers on training data only; transform validation/test with the same fit.",
    tags:["turing","andela","core"] },

  { id:"mf-014", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"Why must the test set remain completely unseen until final evaluation?",
    answer:"Every decision made after looking at test performance — hyperparameter tuning, architecture changes, feature engineering — causes the model to implicitly overfit the test set. Even indirect use (stopping when test accuracy improves) makes test performance an optimistic estimate of true generalisation. The test set must be used exactly once, after all modelling decisions are finalised.",
    explanation:"This is why Kaggle competitions use a private leaderboard revealed only at submission close, and why proper ML pipelines have a three-way split: train / validation / test.",
    tags:["toptal","frequently-tested"] },

  { id:"mf-015", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is the difference between generative and discriminative models?",
    answer:"Discriminative: models P(y|x) — the conditional probability of the label given input. Examples: logistic regression, SVM, neural classifiers. Generative: models the joint P(x,y) = P(x|y)P(y) — can generate new samples and handle missing data. Examples: Naive Bayes, VAEs, GANs, diffusion models.",
    explanation:"For classification with abundant data, discriminative models generally outperform generative ones (they solve a simpler problem). Generative models shine when you need sampling, density estimation, or must handle missing inputs.",
    tags:["toptal","andela"] },

  { id:"mf-016", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is the difference between MLE and MAP estimation?",
    answer:"MLE finds parameters θ that maximise P(data|θ) — uses observed data only. MAP finds θ that maximises P(θ|data) ∝ P(data|θ)×P(θ) — incorporates a prior belief P(θ). MAP with a Gaussian prior on weights is mathematically equivalent to L2 regularisation; MAP with a Laplace prior is equivalent to L1 regularisation.",
    explanation:"Full Bayesian inference maintains a posterior distribution over θ rather than collapsing to a single estimate. MAP is a point estimate of the Bayesian posterior — it's a middle ground between MLE and full Bayes.",
    tags:["toptal"] },

  { id:"mf-017", group:"ml-fundamentals", difficulty:"easy", type:"short",
    question:"What is stratified sampling and when is it critical?",
    answer:"Stratified sampling ensures each class appears in the same proportion in train/test/validation splits as in the original dataset. Critical for imbalanced datasets: random splits can accidentally place all rare-class examples in one partition. In sklearn: train_test_split(..., stratify=y) and StratifiedKFold for cross-validation.",
    explanation:"For a dataset with 1% positive class and N=1000: random splitting to a 100-sample test set might get 0-5 positives purely by chance. Stratification guarantees ~1 positive per 100 samples consistently.",
    tags:["andela","core"] },

  { id:"mf-018", group:"ml-fundamentals", difficulty:"hard", type:"short",
    question:"What is the difference between bagging and boosting? Give one algorithm for each.",
    answer:"Bagging (Bootstrap AGGregating): train many models independently on random data subsets with replacement, aggregate by voting/averaging. Reduces variance. Example: Random Forest. Boosting: train models sequentially, each correcting errors of the previous. Reduces bias. Example: XGBoost. Bagging is parallelisable; boosting is sequential. Boosting typically achieves higher accuracy but overfits more if not regularised.",
    explanation:"Gradient Boosting generalises AdaBoost: instead of reweighting samples, fit each new tree to the gradient of the loss function. XGBoost adds second-order gradients, regularisation, column subsampling, and efficient split-finding.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"mf-019", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is SMOTE and what are its limitations?",
    answer:"SMOTE (Synthetic Minority Oversampling TEchnique): for each minority sample, find its K nearest minority neighbours and create a new synthetic sample by interpolating between them. Limitations: creates synthetic samples between real ones but doesn't consider the decision boundary; can introduce noise if minority samples overlap with the majority class; only applies to numerical features; must not be applied to validation/test data.",
    explanation:"SMOTE should be inside the cross-validation loop (applied only to each training fold) to prevent information leakage from synthetic samples. ADASYN is an adaptive variant that focuses synthesis on harder-to-classify regions.",
    tags:["toptal","andela"] },

  { id:"mf-020", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is a learning curve and what does it tell you about your model?",
    answer:"A learning curve plots training error and validation error against the size of the training set. High bias (underfitting): both errors plateau high regardless of data size — add features or increase model capacity. High variance (overfitting): training error is low but validation error is much higher — the gap narrows with more data, suggesting collecting more examples will help.",
    explanation:"Learning curves distinguish between 'need more data' (high variance) and 'need a better model' (high bias) — the two most common failure modes. They also show the point of diminishing returns for data collection.",
    tags:["andela","core"] },

  { id:"mf-021", group:"ml-fundamentals", difficulty:"hard", type:"short",
    question:"What is the VC dimension and what does it measure?",
    answer:"The VC (Vapnik-Chervonenkis) dimension of a hypothesis class H is the maximum number of points that H can shatter (correctly classify in all 2^N possible label assignments). It measures the capacity/expressiveness of the model family. PAC learning bounds link generalisation error to VC dimension and sample size: more expressive models need more data for reliable generalisation.",
    explanation:"Linear classifiers in d dimensions have VC dim = d+1. SVMs with RBF kernel have infinite VC dimension but still generalise well due to the margin maximisation principle. In practice, empirical cross-validation is more useful than VC bounds for finite datasets.",
    tags:["toptal"] },

  { id:"mf-022", group:"ml-fundamentals", difficulty:"easy", type:"short",
    question:"What is the difference between model parameters and hyperparameters?",
    answer:"Parameters: learned from data during training (weights, biases). Hyperparameters: set by the practitioner before training and control the learning process (learning rate, batch size, number of layers, regularisation strength, tree depth). Hyperparameters are chosen via grid search, random search, or Bayesian optimisation on the validation set — never on the test set.",
    explanation:"Meta-learning (learning to learn) and AutoML systems try to automate hyperparameter selection. Bayesian optimisation (using Gaussian Processes to model the validation loss landscape) is significantly more efficient than random search for expensive models.",
    tags:["turing","andela","core"] },

  { id:"mf-023", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is overfitting in terms of model capacity vs data size?",
    answer:"Overfitting occurs when model capacity (number of parameters, depth, flexibility) far exceeds what the training data can support. The model memorises idiosyncratic details of training examples — noise, outliers, random patterns — rather than the underlying distribution. Regularisation artificially constrains capacity; more data increases the data's ability to support higher capacity.",
    explanation:"Rough heuristic: you need roughly 10× as many training examples as free parameters for reliable generalisation with a simple model. Deep networks violate this heuristic (billions of params, millions of examples) but rely on implicit regularisation from SGD noise, overparameterisation, and inductive biases in architecture.",
    tags:["turing","andela"] },

  { id:"mf-024", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is multicollinearity and how does it affect model performance?",
    answer:"Multicollinearity: two or more features are highly correlated. Effect on linear models: coefficient estimates become unstable — small data changes cause large coefficient swings (high variance). The model still predicts well in-distribution but coefficients lose interpretability. Detection: Variance Inflation Factor (VIF > 10 is problematic). Fix: remove correlated features, use PCA, or apply Ridge regression (L2 handles collinearity naturally by shrinking unstable coefficients).",
    explanation:"Collinearity does not hurt prediction accuracy when new data has the same correlation structure, but it destroys interpretability. In feature importance analysis, collinear features 'split' importance between them — both appear less important than either alone.",
    tags:["toptal"] },

  { id:"mf-025", group:"ml-fundamentals", difficulty:"easy", type:"short",
    question:"What is early stopping and how does it regularise a model?",
    answer:"Early stopping monitors validation loss during training. When validation loss stops improving for 'patience' epochs, training halts and weights from the best epoch are restored. It's implicit regularisation — it stops training before the model memorises training noise. No modification to the loss function is needed.",
    explanation:"Practical tip: use patience=10-20 for deep networks with noisy validation loss. Combine with a learning rate schedule: reduce LR on plateau before stopping, as sometimes a lower LR is all that's needed to continue improving.",
    tags:["andela","core"] },

  { id:"mf-026", group:"ml-fundamentals", difficulty:"hard", type:"short",
    question:"What is Bayesian hyperparameter optimisation and why is it more efficient than random search?",
    answer:"Bayesian optimisation builds a probabilistic model (typically a Gaussian Process) of the mapping from hyperparameters to validation performance. An acquisition function (e.g., Expected Improvement) guides the next trial to balance exploration (uncertain regions) and exploitation (promising regions). It finds good hyperparameters in fewer trials than random search because it learns from previous evaluations.",
    explanation:"Tools: Optuna (TPE sampler), Hyperopt, Ray Tune, BOHB. Bayesian optimisation shines for expensive models (hours per trial). For cheap models, random search with enough trials is often sufficient and simpler.",
    tags:["toptal"] },

  { id:"mf-027", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is the difference between online learning and batch learning?",
    answer:"Batch learning: train on the entire dataset at once, deploy a static model, retrain periodically. Online learning: update the model continuously as new data arrives (one sample or mini-batch at a time). Online learning adapts to distribution shift and requires less memory. Challenge: catastrophic forgetting — updates for new data can overwrite old knowledge.",
    explanation:"Online learning is critical for fraud detection (fraud patterns change), recommendations (user preferences evolve), and any scenario with concept drift. SGD is naturally an online algorithm — just feed one example at a time.",
    tags:["toptal"] },

  { id:"mf-028", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is feature importance and what are three ways to compute it?",
    answer:"Feature importance quantifies each feature's contribution to model predictions. Methods: 1) Tree-based impurity importance — average decrease in node impurity (Gini/entropy) across all splits on that feature (fast but biased toward high-cardinality features). 2) Permutation importance — randomly shuffle one feature's values and measure the drop in validation performance (model-agnostic, unbiased). 3) SHAP values — theoretically sound Shapley-value-based attribution that sums to the prediction difference from baseline.",
    explanation:"Impurity-based importance from sklearn's feature_importances_ is biased and should be paired with permutation importance for verification. SHAP is the gold standard for interpretability but requires more compute.",
    tags:["toptal","andela"] },

  { id:"mf-029", group:"ml-fundamentals", difficulty:"easy", type:"short",
    question:"What is the train/validation/test split and what is each set used for?",
    answer:"Training set: fit model parameters (weights). Validation set: tune hyperparameters and select between models — used many times during development. Test set: final unbiased evaluation of the chosen model — used exactly once. Without a separate validation set, hyperparameter tuning on the test set contaminates the final evaluation.",
    explanation:"Common splits: 60/20/20 or 70/15/15. For small datasets, use k-fold cross-validation instead of a fixed validation split. The test set must remain sealed until all modelling decisions are finalised.",
    tags:["turing","andela","core"] },

  { id:"mf-030", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is concept drift and how do you detect it in production?",
    answer:"Concept drift: the statistical relationship between features and the target changes over time (P(y|x) changes). Example: a fraud model trained before COVID-19 sees different spending patterns post-pandemic. Detection: monitor model performance metrics (accuracy, F1) on recent batches; use statistical tests (Kolmogorov-Smirnov, Population Stability Index) on input feature distributions; track prediction distribution shifts.",
    explanation:"Types of drift: covariate shift (P(x) changes), label drift (P(y) changes), concept drift (P(y|x) changes). Solutions: periodic retraining, online learning, drift-adaptive windows, or ensemble models trained on different time windows.",
    tags:["toptal","andela"] },

  { id:"mf-031", group:"ml-fundamentals", difficulty:"hard", type:"short",
    question:"What is calibration and why does it matter for probabilistic classifiers?",
    answer:"A calibrated classifier produces probabilities that match empirical frequencies: if the model says P=0.8 for a class, approximately 80% of those predictions should be correct. Poorly calibrated models can be overconfident or underconfident. Calibration matters for: risk scoring (loan default probability), medical diagnosis, decision-making under uncertainty. Assessment: reliability diagrams (calibration curves). Fixes: Platt scaling (logistic regression on top of scores), isotonic regression.",
    explanation:"Neural networks and SVMs are typically overconfident (predicted probabilities too extreme). Naive Bayes is often poorly calibrated in the opposite direction. Random forests and gradient boosters have reasonable but not perfect calibration.",
    tags:["toptal"] },

  { id:"mf-032", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is the Matthews Correlation Coefficient (MCC) and when should you use it?",
    answer:"MCC = (TP×TN - FP×FN) / √((TP+FP)(TP+FN)(TN+FP)(TN+FN)). It returns a value in [-1,1] where +1 is perfect prediction, 0 is random, and -1 is perfectly inverse. MCC is considered one of the best single metrics for binary classification because it accounts for all four confusion matrix cells and is meaningful even with severe class imbalance.",
    explanation:"Unlike F1, MCC is symmetric — it gives equal weight to both classes. The FDA recommends MCC for evaluating binary classifiers in clinical settings. Use it alongside AUC-PR for imbalanced datasets.",
    tags:["toptal"] },

  { id:"mf-033", group:"ml-fundamentals", difficulty:"easy", type:"short",
    question:"What is the purpose of normalisation vs standardisation and when do you choose each?",
    answer:"Normalisation (Min-Max): scales to [0,1]. Use when you need bounded outputs (e.g., neural network inputs, distance-based algorithms) and the distribution doesn't have heavy outliers. Standardisation (Z-score): mean=0, std=1. Use when the data follows an approximately Gaussian distribution or outliers are present (outliers affect Min-Max dramatically). Standardisation is generally more robust and is the default choice.",
    explanation:"Both assume linear scaling. For highly skewed distributions, apply a log transform before standardisation. RobustScaler (scales by median and IQR) is best when outliers are present and cannot be removed.",
    tags:["andela","core"] },

  { id:"mf-034", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What are three strategies for handling missing data?",
    answer:"1) Deletion — remove rows/columns with missing values (only if data is missing completely at random and the proportion is small, <5%). 2) Imputation — fill with mean/median/mode (simple), model-based imputation (kNN, MICE), or learned embeddings. 3) Indicator encoding — add a binary flag indicating whether the value was missing (preserves the information that missingness itself may be predictive), then impute for the model that needs a value.",
    explanation:"Modern gradient boosting (XGBoost, LightGBM, CatBoost) handles missing values natively by learning the optimal direction for NaN splits. For neural networks, imputation plus a missingness indicator is standard.",
    tags:["toptal","andela"] },

  { id:"mf-035", group:"ml-fundamentals", difficulty:"hard", type:"short",
    question:"What is the difference between Type I and Type II errors in hypothesis testing, and how do they map to ML classification?",
    answer:"Type I error (false positive, α): rejecting the null hypothesis when it is true. Type II error (false negative, β): failing to reject the null when it is false. In ML binary classification: false positive = Type I (model predicts positive but it's negative); false negative = Type II (model misses a true positive). Precision controls Type I rate; recall controls Type II rate. The tradeoff between them is the precision-recall tradeoff.",
    explanation:"Statistical power = 1 - β = recall. Setting a threshold closer to 0 reduces false negatives (increases recall/power) at the cost of more false positives. The optimal threshold depends on the relative costs of each error type in the application.",
    tags:["toptal"] },

  { id:"mf-036", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is data augmentation and when is it most useful?",
    answer:"Data augmentation: artificially expand the training set by creating modified copies of existing examples. For images: random crops, flips, rotations, colour jitter, CutMix. For text: back-translation, synonym replacement, random deletion/swap. For tabular: Mixup (interpolate between samples). Most useful when: labelled data is scarce, the model is overfitting, and the augmented examples are realistic and reflect true data variability.",
    explanation:"Augmentation is a form of regularisation — it prevents the model from over-relying on spurious features (exact pixel values, word order). TTA (Test-Time Augmentation): apply augmentations at inference and average predictions for a free accuracy boost.",
    tags:["andela","core"] },

  { id:"mf-037", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is the ROC curve and how do you interpret AUC=0.5 vs AUC=0.9?",
    answer:"ROC curve: True Positive Rate (recall) vs. False Positive Rate (1-specificity) at all classification thresholds. AUC=0.5: model is no better than random chance — the ROC curve is the diagonal line. AUC=0.9: there is a 90% probability that a randomly chosen positive sample is scored higher by the model than a randomly chosen negative sample — strong discrimination ability.",
    explanation:"AUC-ROC is threshold-independent and class-imbalance-robust (evaluates over all thresholds). For highly imbalanced datasets, AUC-PR (precision-recall curve) is more informative because AUC-ROC can look high even when precision is very low.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"mf-038", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is transfer learning and when is it useful?",
    answer:"Transfer learning: initialise a model with weights pretrained on a large dataset (e.g., ImageNet, Common Crawl), then fine-tune on your smaller target dataset. Useful when: your dataset is small (hundreds to thousands of examples), your target task is similar to the pretraining task, and training from scratch would overfit or be computationally prohibitive.",
    explanation:"Feature extraction mode: freeze pretrained layers, only train a new head (fastest, works when tasks are similar). Fine-tuning mode: unfreeze some/all pretrained layers with a low learning rate (better when tasks differ moderately). Both approaches vastly outperform training from scratch with small data.",
    tags:["toptal","andela"] },

  { id:"mf-039", group:"ml-fundamentals", difficulty:"easy", type:"mcq",
    options:["Reduces bias","Reduces variance","Eliminates irreducible noise","Increases model capacity"],
    question:"What effect does increasing the amount of training data primarily have on a model with high variance?",
    answer:"Reduces variance",
    explanation:"More training data exposes the model to more of the true data distribution, reducing its sensitivity to the particular samples it was trained on. High-bias models (underfit) do not benefit much from more data — the model is wrong in a systematic way that more examples cannot fix.",
    tags:["turing","andela"] },

  { id:"mf-040", group:"ml-fundamentals", difficulty:"hard", type:"short",
    question:"What is knowledge distillation and how does it produce smaller, faster models?",
    answer:"A small 'student' model is trained to mimic a large 'teacher' model's soft output probabilities rather than hard labels. The soft probabilities (e.g., [0.88, 0.09, 0.03]) carry 'dark knowledge' — the teacher's learned similarity structure between classes. Loss = α × cross-entropy(hard labels) + (1-α) × KL-divergence(soft teacher outputs, temperature T). The student learns a richer signal than one-hot labels alone.",
    explanation:"DistilBERT: 66% of BERT size, 97% of performance, 60% faster — achieved via distillation. Temperature T > 1 softens the teacher's distribution, revealing more inter-class relationships. Distillation also works from ensembles: train one model to match ensemble predictions.",
    tags:["toptal","frequently-tested"] },

  { id:"mf-041", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is label smoothing and why is it used in training classifiers?",
    answer:"Label smoothing replaces hard one-hot labels (0 or 1) with soft labels: y_smooth = (1-ε)×y + ε/K where K is the number of classes and ε is typically 0.1. This prevents the model from becoming overconfident (pushing logits to ±∞), improves calibration, and acts as a regulariser. Widely used in image classification (ViT, EfficientNet) and NMT training.",
    explanation:"Hard labels implicitly assume infinite confidence in annotations, which is unrealistic. Label smoothing is equivalent to adding a uniform distribution over all classes as noise to the target distribution.",
    tags:["toptal"] },

  { id:"mf-042", group:"ml-fundamentals", difficulty:"easy", type:"short",
    question:"What is the confusion matrix and how do you read it?",
    answer:"A confusion matrix is an N×N table where rows represent actual classes and columns represent predicted classes. The diagonal contains correct predictions; off-diagonal entries are errors. For binary classification: TP (top-left), FP (top-right), FN (bottom-left), TN (bottom-right). High FP in column j: model is over-predicting class j. High FN in row i: model is missing class i.",
    explanation:"The confusion matrix reveals patterns of class confusion (e.g., model confuses cats with dogs but not cats with cars) that aggregate metrics like accuracy hide. Always inspect it for imbalanced datasets — overall accuracy can be 95% while the rare class has 0% recall.",
    tags:["turing","andela","core"] },

  { id:"mf-043", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is the difference between interpolation and extrapolation in the context of ML generalisation?",
    answer:"Interpolation: making predictions within the range of training data (covered by the training distribution). Extrapolation: making predictions outside the training distribution. ML models generally interpolate well (this is what generalisation means) but extrapolate poorly — a model trained on house prices in one city will fail in a city with different price ranges. Neural networks are particularly bad at extrapolation despite being very good interpolators.",
    explanation:"Distribution shift (train/test distribution mismatch) is the most common real-world failure mode — it's extrapolation in disguise. Domain adaptation and domain generalisation research specifically addresses this.",
    tags:["toptal"] },

  { id:"mf-044", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is a validation curve and what does it show?",
    answer:"A validation curve plots training and validation scores against a single hyperparameter controlling model complexity (e.g., max_depth, C in SVM, n_estimators). Underfitting zone (left): both scores are low and similar. Sweet spot (middle): validation score peaks. Overfitting zone (right): training score continues rising but validation score drops. Use it to select the optimal value for a single hyperparameter while holding others fixed.",
    explanation:"Validation curves and learning curves together give a complete picture of the bias-variance tradeoff for your model. sklearn has plot_validation_curve utility for this.",
    tags:["andela"] },

  { id:"mf-045", group:"ml-fundamentals", difficulty:"hard", type:"short",
    question:"What is the bootstrap method and how is it used in bagging?",
    answer:"Bootstrap: draw N samples with replacement from a dataset of N examples. On average, each bootstrap sample contains ~63.2% unique examples (≈1-1/e) — about 36.8% of examples are out-of-bag (OOB). Bagging trains each tree on a bootstrap sample; OOB examples serve as a built-in validation set. OOB error approximates cross-validation error with no extra computation, making it an efficient training monitor.",
    explanation:"The 63.2% figure comes from lim_{N→∞}(1-1/N)^N = 1/e ≈ 0.368 duplicated, so 0.632 unique. Random Forest uses OOB error to compute feature importances and as a stopping criterion — often within 1% of 5-fold CV accuracy.",
    tags:["toptal"] },

  { id:"mf-046", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is Occam's Razor in machine learning?",
    answer:"Among models that explain the training data equally well, prefer the simpler one. Simpler models are less likely to overfit, are more interpretable, and tend to generalise better. This is the principle behind regularisation: add a complexity penalty to the loss function so the optimiser prefers simpler solutions. In practice: start with simple baselines (linear/logistic regression) before complex models.",
    explanation:"Minimum Description Length (MDL) formalises Occam's Razor: the best model is the one that provides the shortest description of the data (model + residuals). L1 regularisation is an MDL-inspired approach — it prefers descriptions with fewer non-zero features.",
    tags:["toptal"] },

  { id:"mf-047", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is semi-supervised learning and give a practical example?",
    answer:"Semi-supervised learning uses a small amount of labelled data together with a large amount of unlabelled data. The unlabelled data provides structural information about the input distribution. Example: pseudo-labelling — train a model on labelled data, predict labels for unlabelled examples with high confidence, add those to the training set and retrain. Used extensively in image classification when labelling is expensive.",
    explanation:"Other methods: consistency regularisation (predictions should be similar under data augmentation), graph-based methods (propagate labels through a similarity graph). Self-supervised pretraining followed by supervised fine-tuning is the modern large-scale version of this idea.",
    tags:["toptal","andela"] },

  { id:"mf-048", group:"ml-fundamentals", difficulty:"hard", type:"short",
    question:"What is the difference between frequentist and Bayesian approaches to uncertainty quantification?",
    answer:"Frequentist: uncertainty comes from repeated sampling — a 95% confidence interval means 95% of such intervals contain the true parameter across repeated experiments. Does not give a probability that the parameter is in this specific interval. Bayesian: uncertainty is a probability distribution over parameters — a 95% credible interval means P(parameter in interval | data) = 0.95. Allows incorporating prior beliefs, updating with new data, and making probabilistic statements about unknowns.",
    explanation:"In ML: frequentist → cross-validated confidence intervals, bootstrap confidence intervals. Bayesian → Gaussian Processes, Bayesian Neural Networks, probabilistic programming (PyMC, Stan). Bayesian methods are more interpretable for decision-making but computationally expensive.",
    tags:["toptal"] },

  { id:"mf-049", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is gradient descent and what are its three variants?",
    answer:"Gradient descent iteratively updates parameters in the direction of the negative gradient of the loss: θ ← θ - η∇L. Variants: 1) Batch GD: gradient over entire dataset — stable but slow per update, gets stuck in flat regions. 2) SGD: gradient over one sample — fast, noisy, good at escaping local minima. 3) Mini-batch SGD: gradient over a batch (32-512) — best of both, standard in deep learning. 'SGD' in deep learning frameworks almost always means mini-batch SGD.",
    explanation:"The noise in mini-batch SGD is not merely a compromise — it helps find flatter minima that generalise better. Very large batches converge to sharper minima with worse generalisation (Keskar et al., 2017), which is why LLM training uses gradient accumulation rather than simply enlarging the batch.",
    tags:["turing","andela","core","frequently-tested"] },

  { id:"mf-050", group:"ml-fundamentals", difficulty:"medium", type:"short",
    question:"What is the precision-recall tradeoff and how do you set the decision threshold?",
    answer:"In binary classification, the probability threshold (default 0.5) determines the class boundary. Lowering the threshold increases recall (catches more positives) but decreases precision (more false positives). Raising it increases precision but misses more positives. Optimal threshold depends on business cost: medical screening → maximise recall (minimise missed cases); spam filtering → maximise precision (minimise good emails deleted). Choose threshold by optimising F-beta or by directly specifying acceptable false-negative/positive rates.",
    explanation:"Plot the precision-recall curve and pick the threshold at the operating point that satisfies your business constraint. Do this on the validation set — never tune the threshold using test data.",
    tags:["toptal","andela","frequently-tested"] },

  // ── CLASSICAL ML (50) ─────────────────────────────────────────────────────

  { id:"cm-001", group:"classical-ml", difficulty:"easy", type:"short",
    question:"What are the four assumptions of linear regression (OLS)?",
    answer:"1) Linearity: the relationship between X and y is linear. 2) Independence: observations are independent of each other. 3) Homoscedasticity: residuals have constant variance across all levels of X. 4) Normality of residuals: residuals are approximately normally distributed (for valid hypothesis tests and confidence intervals). Violations: use robust regression, transformation, or generalised least squares.",
    explanation:"Heteroscedasticity (non-constant variance) is the most common violation. Detect with residual plots (residuals vs fitted values should be random scatter). Fix with log-transform of y or weighted least squares.",
    tags:["toptal","andela","core"] },

  { id:"cm-002", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is R² (coefficient of determination) and what does R²=0.85 mean?",
    answer:"R² = 1 - SS_residual/SS_total. It measures the proportion of variance in y explained by the model. R²=0.85 means the model explains 85% of the variation in the target — 15% remains unexplained (residual noise). R²=0 means the model is no better than predicting the mean; R²=1 means perfect fit. Adjusted R² penalises extra predictors: Adj-R² = 1 - (1-R²)(N-1)/(N-p-1).",
    explanation:"R² alone can be misleading: always inspect residual plots. A model can have high R² but violate OLS assumptions (non-random residuals, heteroscedasticity), making inference invalid. For non-linear relationships, R² from a linear fit is also misleading.",
    tags:["toptal","andela"] },

  { id:"cm-003", group:"classical-ml", difficulty:"medium", type:"short",
    question:"Why is logistic regression called 'regression' if it's a classifier?",
    answer:"Logistic regression regresses log-odds (logit) of the class probability against the feature vector: log(p/(1-p)) = wᵀx + b. Applying the inverse logit (sigmoid) gives P(y=1|x) = σ(wᵀx+b). The output is a probability (continuous), which is then thresholded at 0.5 (or another value) to produce a class label. So it truly is a regression model of the log-odds, used for classification.",
    explanation:"The coefficients in logistic regression are log-odds ratios: e^w_i is the odds multiplier for a one-unit increase in feature i. This gives logistic regression strong interpretability advantages over black-box models.",
    tags:["turing","andela","core"] },

  { id:"cm-004", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is the SVM margin and what are support vectors?",
    answer:"The SVM decision boundary is a hyperplane wᵀx+b=0. The margin is the distance between this hyperplane and the nearest training points from each class: 2/‖w‖. Support vectors are the training points that lie on the margin boundaries (wᵀx+b = ±1). The SVM objective maximises the margin (minimises ‖w‖²), which is equivalent to maximising the minimum distance to the decision boundary.",
    explanation:"Only support vectors matter for the final decision boundary — the rest of the training data can be removed without changing the model. This makes SVMs robust to non-support-vector outliers and memory-efficient at inference.",
    tags:["toptal","andela"] },

  { id:"cm-005", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is the C parameter in SVM and how does it affect bias/variance?",
    answer:"C is the inverse regularisation strength in the SVM soft-margin formulation. Large C: small tolerance for misclassification — tight margin, complex boundary (low bias, high variance, may overfit). Small C: allows more misclassifications for a wider margin (high bias, lower variance, more regularised). C=∞ gives the hard-margin SVM which requires perfect separation.",
    explanation:"The γ parameter in RBF-SVM controls kernel bandwidth: large γ → narrow Gaussian → high-variance, wiggly boundary. Small γ → wide Gaussian → smooth, underfitting boundary. Jointly tune C and γ via cross-validated grid search.",
    tags:["toptal","andela"] },

  { id:"cm-006", group:"classical-ml", difficulty:"hard", type:"short",
    question:"Explain the kernel trick: why can an SVM classify non-linearly separable data?",
    answer:"The kernel trick computes the inner product φ(x)·φ(z) in a high-dimensional (potentially infinite) feature space without explicitly computing φ(x). The SVM dual problem only requires inner products, so replacing x·z with K(x,z) implicitly works in the feature space. RBF kernel K(x,z) = exp(-γ‖x-z‖²) corresponds to an infinite-dimensional feature space — any classification problem is linearly separable in infinite dimensions.",
    explanation:"Common kernels: Linear K=xᵀz (no transformation), Polynomial K=(xᵀz+c)^d, RBF (Gaussian), Sigmoid. The kernel matrix must be positive semi-definite (Mercer's condition) for the dual problem to be convex.",
    tags:["toptal","frequently-tested"] },

  { id:"cm-007", group:"classical-ml", difficulty:"easy", type:"short",
    question:"What criterion does a decision tree use to select the best split?",
    answer:"At each node, it evaluates all possible feature thresholds and picks the split maximising information gain (entropy reduction) or minimising the weighted Gini impurity of child nodes. Gini = 1 - Σpᵢ²; Entropy = -Σpᵢlog₂pᵢ. Both measure node impurity — 0 means pure (one class only). In practice, Gini and entropy give nearly identical results; Gini is computationally cheaper (no log).",
    explanation:"Regression trees use mean squared error (MSE) reduction as the split criterion — the split that maximises the reduction in weighted MSE of the child nodes. This is equivalent to finding the split that minimises the sum of squared residuals.",
    tags:["turing","andela","core"] },

  { id:"cm-008", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is pruning in decision trees and what are the two types?",
    answer:"Pruning reduces tree size to prevent overfitting. Pre-pruning (early stopping): stop splitting when a criterion is met (max_depth, min_samples_split, min_samples_leaf, min_impurity_decrease). Post-pruning: grow the full tree, then remove branches that don't improve generalisation — cost-complexity pruning in sklearn (ccp_alpha parameter) removes branches whose impurity improvement doesn't justify their complexity cost.",
    explanation:"Post-pruning generally outperforms pre-pruning because it sees the global tree before deciding what to remove, but it's more expensive. The optimal ccp_alpha is found via cross-validation on a range of values.",
    tags:["toptal","andela"] },

  { id:"cm-009", group:"classical-ml", difficulty:"medium", type:"short",
    question:"How does Random Forest achieve lower variance than a single decision tree?",
    answer:"Random Forest trains B trees, each on a bootstrap sample with a random subset of features (√p features per split for classification, p/3 for regression) considered at each node. Averaging B independent predictions reduces variance by factor 1/B if trees are uncorrelated. Feature randomness decorrelates trees — without it, all trees would choose the same dominant features and be highly correlated, negating the benefit of averaging.",
    explanation:"Random Forest also provides free OOB error estimates and variable importance. It's robust to outliers, doesn't require feature scaling, and handles mixed feature types. Often the best baseline for tabular data without hyperparameter tuning.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"cm-010", group:"classical-ml", difficulty:"hard", type:"short",
    question:"What are the key differences between Random Forest and XGBoost?",
    answer:"Random Forest: bagging (parallel training), averaging predictions, reduces variance, robust to overfitting, less sensitive to hyperparameters. XGBoost: gradient boosting (sequential training), each tree fits residuals of the ensemble, reduces bias, higher accuracy potential but requires careful regularisation. XGBoost adds: second-order gradient approximation, L1/L2 regularisation on leaf weights, column/row subsampling, efficient split-finding via histogram binning.",
    explanation:"In practice: RF is more forgiving and a great first model. XGBoost typically achieves higher accuracy with tuning. LightGBM is faster than XGBoost (leaf-wise growth, histogram binning) and often matches or exceeds it. CatBoost handles categorical features natively without encoding.",
    tags:["toptal","frequently-tested"] },

  { id:"cm-011", group:"classical-ml", difficulty:"easy", type:"short",
    question:"What is the time complexity of KNN prediction and why is it slow?",
    answer:"For N training samples and D features, each query requires computing distance to all N training points: O(N×D) per prediction. For Q queries: O(Q×N×D). No training phase — all computation is at inference time. Slow because it's a lazy learner: KNN stores the entire training set and does all computation at prediction time. ANN (approximate nearest neighbour) algorithms like HNSW reduce this to O(D log N) with ~95-99% recall.",
    explanation:"KNN has zero training time but scales poorly at inference. Contrast with neural networks: expensive training, O(D×H) inference per example regardless of training set size. For production use, always use HNSW, ball trees, or KD-trees instead of brute-force KNN.",
    tags:["turing","andela"] },

  { id:"cm-012", group:"classical-ml", difficulty:"medium", type:"short",
    question:"How do you choose the optimal K in KNN?",
    answer:"Use cross-validation: for each K in a candidate range (e.g., 1 to √N), compute cross-validated accuracy/F1 and select the K with the best validation score. Rule of thumb starting point: K=√N. Small K: high variance (decision boundary jagged, sensitive to noise). Large K: high bias (over-smoothed boundary). Odd K is preferred for binary classification to avoid ties.",
    explanation:"KNN with K=1 is the most sensitive case: the decision boundary passes between each pair of points from different classes. K=N always predicts the majority class. The optimal K balances these extremes based on the local density of the training data.",
    tags:["andela"] },

  { id:"cm-013", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What are the limitations of K-Means clustering?",
    answer:"1) Must specify K in advance. 2) Assumes spherical, equal-variance clusters — fails for elongated, irregular, or density-varying shapes. 3) Sensitive to outliers (outliers pull centroids). 4) Non-deterministic: results depend on initialisation (use K-Means++ for better init). 5) Assumes clusters of similar size. 6) Euclidean distance only — not suited for categorical or mixed data. 7) Local optimum convergence — may need multiple restarts.",
    explanation:"Alternatives: DBSCAN (arbitrary shapes, finds outliers automatically), GMM (soft assignments, handles elliptical clusters), Agglomerative clustering (dendrogram shows the hierarchy, no K needed upfront), Spectral clustering (non-convex clusters via graph structure).",
    tags:["toptal","andela"] },

  { id:"cm-014", group:"classical-ml", difficulty:"medium", type:"short",
    question:"How does K-Means++ differ from random initialisation?",
    answer:"K-Means++ initialises centroids spread across the data: pick the first centroid uniformly at random, then pick each subsequent centroid with probability proportional to D(x)² — the squared distance from x to the nearest existing centroid. This ensures centroids are spread out, avoiding the 'all centroids in a dense region' failure of random init. Result: faster convergence (fewer iterations) and higher quality solutions.",
    explanation:"K-Means++ is the default initialisation in sklearn (init='k-means++'). It makes the expected solution within O(log K) of the optimal clustering cost, whereas random initialisation has no such guarantee.",
    tags:["toptal"] },

  { id:"cm-015", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is PCA and what does it mean that principal components are orthogonal?",
    answer:"PCA finds linear directions (principal components) of maximum variance in the data. PC1 captures the most variance, PC2 captures the most remaining variance orthogonal to PC1, etc. Orthogonal means the components are uncorrelated — projections onto different PCs are independent. This is useful for: removing collinearity (each PC is independent), dimensionality reduction (keep top-k components explaining 95% of variance).",
    explanation:"PCA is a linear transformation; it doesn't capture non-linear structure (use UMAP or t-SNE for non-linear embeddings). It's unsupervised — doesn't use labels. Whitening (scaling each PC to unit variance) further decorrelates features, useful before distance-based algorithms.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"cm-016", group:"classical-ml", difficulty:"hard", type:"short",
    question:"What is the difference between PCA, t-SNE, and UMAP?",
    answer:"PCA: linear, preserves global variance structure, deterministic, fast, interpretable components. t-SNE: non-linear, preserves local neighbourhood structure, stochastic, O(N²) naive (O(N log N) with Barnes-Hut), only 2-3D output, great for visualisation but not for downstream ML features (no out-of-sample extension). UMAP: non-linear, preserves both local and global structure better than t-SNE, faster (O(N^1.14)), supports arbitrary output dimensions, has out-of-sample transform.",
    explanation:"In 2026: UMAP has largely replaced t-SNE for exploratory data visualisation due to speed and better global structure preservation. PCA remains the default for dimensionality reduction when preserving linear structure or when you need interpretable components.",
    tags:["toptal","frequently-tested"] },

  { id:"cm-017", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is Naive Bayes and why is it effective despite its 'naive' assumption?",
    answer:"Naive Bayes assumes all features are conditionally independent given the class: P(x₁,...,xₙ|y) = ΠP(xᵢ|y). This is almost never true, but the model performs well on text classification because: even with incorrect absolute probabilities, the relative ranking of class probabilities is often correct, and the argmax (predicted class) remains accurate. It's fast, requires very little data, and handles high-dimensional sparse features (text) efficiently.",
    explanation:"Variants: Gaussian NB (continuous features, assumes Gaussian P(xᵢ|y)), Multinomial NB (word counts, standard for text), Bernoulli NB (binary feature presence). Multinomial NB with TF-IDF features was the standard text classifier before neural networks.",
    tags:["andela","core"] },

  { id:"cm-018", group:"classical-ml", difficulty:"hard", type:"short",
    question:"What is gradient boosting at an algorithmic level?",
    answer:"Gradient boosting builds an additive ensemble F(x) = Σhₘ(x). At each step m: compute pseudo-residuals rᵢ = -∂L/∂F(xᵢ) (negative gradient of the loss w.r.t. current predictions). Fit a weak learner hₘ to these pseudo-residuals. Update: F_m(x) = F_{m-1}(x) + η×hₘ(x). For MSE loss, pseudo-residuals = actual residuals. For log-loss, pseudo-residuals = yᵢ - p̂ᵢ. The process greedily descends the functional gradient of the loss in the space of functions.",
    explanation:"XGBoost extends this with second-order Taylor expansion of the loss — using both gradient and Hessian gives better split quality estimates, allows L1/L2 regularisation terms in the objective, and leads to the XGBoost split gain formula: Gain = ½[G_L²/(H_L+λ) + G_R²/(H_R+λ) - (G_L+G_R)²/(H_L+H_R+λ)] - γ.",
    tags:["toptal","frequently-tested"] },

  { id:"cm-019", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is DBSCAN and what are its advantages over K-Means?",
    answer:"DBSCAN (Density-Based Spatial Clustering): a point is 'core' if it has ≥ minPts neighbours within radius ε. Core points form clusters by connecting if within ε; border points join the nearest core cluster; outliers are labelled noise. Advantages over K-Means: discovers arbitrary-shaped clusters, automatically determines K, identifies outliers explicitly, not sensitive to initialisation.",
    explanation:"DBSCAN parameters: ε (neighbourhood radius) and minPts (minimum neighbours for core point). Choosing ε: plot k-distance graph (distance to k-th nearest neighbour) — ε is at the 'knee' of the curve. Weakness: struggles with varying-density clusters and high-dimensional data.",
    tags:["toptal","andela"] },

  { id:"cm-020", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is the elbow method for choosing K in K-Means?",
    answer:"Plot the within-cluster sum of squares (WCSS / inertia) against K for K=1..N. As K increases, WCSS decreases — more clusters always reduces within-cluster variance. The optimal K is at the 'elbow' — the point of diminishing returns where adding another cluster provides minimal benefit. If no clear elbow, use the silhouette score (measures both cohesion and separation) or gap statistic instead.",
    explanation:"Silhouette coefficient for sample i: s(i) = (b-a)/max(a,b), where a is the mean intra-cluster distance and b is the mean distance to the nearest other cluster. Silhouette ∈ [-1,1]; higher is better. Average over all samples gives the overall clustering quality.",
    tags:["andela"] },

  { id:"cm-021", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is AdaBoost and how does it differ from gradient boosting?",
    answer:"AdaBoost (Adaptive Boosting): at each step, increase weights of misclassified examples and decrease weights of correctly classified ones. Train the next weak learner on re-weighted data. Final prediction: weighted vote of all learners (weights proportional to their accuracy). Gradient Boosting generalises this: instead of re-weighting samples, it fits the gradient of the loss — AdaBoost is gradient boosting with exponential loss.",
    explanation:"AdaBoost is sensitive to noisy data and outliers (re-weights them aggressively). Gradient boosting with shrinkage and subsampling is more robust. In 2026, XGBoost/LightGBM are used almost exclusively; AdaBoost is mainly taught for historical context.",
    tags:["andela"] },

  { id:"cm-022", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is the OOB (Out-of-Bag) error in Random Forest?",
    answer:"Each tree in Random Forest is trained on a bootstrap sample (~63.2% of data). The remaining ~36.8% (out-of-bag samples) are not seen by that tree. OOB error: for each training sample, aggregate predictions from all trees that did NOT see that sample. This gives an unbiased validation estimate without needing a separate validation set — equivalent to leave-one-out cross-validation in expectation.",
    explanation:"OOB error makes Random Forest self-validating, which is especially useful for small datasets. Enable in sklearn with oob_score=True. OOB feature importance is computed similarly: permute each feature in OOB samples and measure the drop in OOB accuracy.",
    tags:["toptal"] },

  { id:"cm-023", group:"classical-ml", difficulty:"hard", type:"short",
    question:"What is SVD (Singular Value Decomposition) and how is it related to PCA?",
    answer:"SVD: any matrix X = UΣVᵀ where U and V are orthogonal matrices and Σ is diagonal with singular values. PCA of X: compute SVD of the centred data matrix X̃; the right singular vectors V (columns) are the principal components and the squared singular values σᵢ² / (N-1) are the eigenvalues of the covariance matrix. SVD is numerically more stable than computing the covariance matrix explicitly (avoids squaring condition number).",
    explanation:"SVD has broad applications: PCA, LSA (Latent Semantic Analysis) for text, collaborative filtering (matrix factorisation), pseudo-inverse, low-rank approximation (Eckart-Young theorem). sklearn's PCA uses randomised SVD for efficiency on large datasets.",
    tags:["toptal"] },

  { id:"cm-024", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is the difference between Lasso and Elastic Net regression?",
    answer:"Lasso (L1): penalty λΣ|wᵢ|. Produces sparse solutions, selects features, but arbitrarily selects one feature from correlated groups. Elastic Net: penalty α×L1 + (1-α)×L2 = αΣ|wᵢ| + (1-α)Σwᵢ². Combines sparsity (from L1) with grouping effect (from L2 — correlated features get similar weights). Better than Lasso when features are correlated. Ridge: pure L2, no sparsity.",
    explanation:"The l1_ratio parameter in sklearn's ElasticNet controls the mix: l1_ratio=1 is Lasso, l1_ratio=0 is Ridge. ElasticNet is the recommended default when you expect some irrelevant features but aren't sure which, or when features may be correlated.",
    tags:["toptal"] },

  { id:"cm-025", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is the Gini impurity vs entropy as a split criterion — which should you use?",
    answer:"Gini: 1-Σpᵢ². Entropy: -Σpᵢlog₂pᵢ. Both measure node impurity (0=pure). Gini is computationally cheaper (no log), tends to isolate the most frequent class. Entropy is more symmetric and can make slightly better splits in some cases. In practice: the choice rarely matters — performance differences are <0.1% across most datasets. sklearn defaults to Gini; use 'entropy' if you want an information-theoretic motivation.",
    explanation:"More impactful than the criterion choice: max_depth, min_samples_split, whether you're using a single tree vs. an ensemble. Spend hyperparameter budget on these instead of criterion selection.",
    tags:["andela"] },

  { id:"cm-026", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is collinear feature and how does it affect tree-based models vs. linear models?",
    answer:"Collinear features are highly correlated. Effect on linear models: coefficient estimates become unstable and uninterpretable (high variance), though predictions may still be accurate. Effect on tree-based models: collinear features 'split' importance between them — both appear less important than either alone, making importance scores unreliable for interpretation. Predictions are not affected because the tree can use either feature interchangeably.",
    explanation:"For linear models, Ridge regression handles collinearity gracefully by shrinking correlated coefficients together. For trees, the prediction is unaffected but use permutation importance (not impurity importance) for reliable feature interpretability when collinearity is present.",
    tags:["toptal"] },

  { id:"cm-027", group:"classical-ml", difficulty:"easy", type:"short",
    question:"What is the difference between hard and soft classification margins in SVM?",
    answer:"Hard margin SVM: requires perfect linear separation — no training errors allowed. Only works when data is linearly separable; fails (infeasible) with noise or overlap. Soft margin SVM (C-SVM): allows some misclassifications with a slack variable ξᵢ. The objective minimises ‖w‖²/2 + C×Σξᵢ. C controls the tradeoff between maximising margin and minimising training errors. Most real-world SVMs are soft-margin.",
    explanation:"Hard margin SVM is equivalent to soft margin with C→∞. Soft margin with small C gives a wider margin with more violations — more regularised. Large C mimics hard margin but is more sensitive to noisy points near the boundary.",
    tags:["toptal","andela"] },

  { id:"cm-028", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is multiclass classification with SVM and what are the two common strategies?",
    answer:"SVMs are inherently binary classifiers. Multiclass strategies: 1) One-vs-Rest (OvR): train K binary classifiers, each distinguishing class k from all others. Predict: argmax of signed distances. 2) One-vs-One (OvO): train K(K-1)/2 binary classifiers for every pair. Predict: majority vote. OvO is more common in practice (each binary problem is easier, fewer samples per classifier), but OvR scales better for large K.",
    explanation:"sklearn's SVC uses OvO by default. For large K (100+ classes), OvR is more practical. For neural networks, multi-class classification is handled directly with softmax — no OvR/OvO needed.",
    tags:["andela"] },

  { id:"cm-029", group:"classical-ml", difficulty:"hard", type:"short",
    question:"What is the Gaussian Mixture Model (GMM) and how does EM training work?",
    answer:"GMM: data is modelled as a mixture of K Gaussian distributions, each with its own mean μₖ and covariance Σₖ. EM (Expectation-Maximisation): E-step: compute soft assignment probabilities rᵢₖ = P(cluster k | xᵢ) using current parameters. M-step: update μₖ, Σₖ, and mixing weights πₖ using the weighted sufficient statistics. Repeat until convergence. GMM gives soft (probabilistic) cluster assignments and handles elliptical clusters, unlike K-Means (hard assignments, spherical only).",
    explanation:"GMM reduces to K-Means when all covariances are fixed to σ²I and assignments are made hard. GMM is also used for density estimation (compute P(x) for a new point) and outlier detection (low-probability points are anomalies).",
    tags:["toptal"] },

  { id:"cm-030", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is feature selection and what are the three main approaches?",
    answer:"1) Filter methods: select features by statistical properties (correlation with target, mutual information, chi-squared) independent of the model. Fast, model-agnostic, but ignores feature interactions. 2) Wrapper methods: use model performance to evaluate feature subsets (RFE — Recursive Feature Elimination). Expensive but considers interactions. 3) Embedded methods: feature selection during training (Lasso's zero weights, tree feature importance). Efficient and model-integrated.",
    explanation:"RFECV (RFE with cross-validation) is the most reliable wrapper method in sklearn. Lasso (L1 regularisation) is the most common embedded method for linear models. For tree ensembles, SHAP values provide model-integrated importance that handles interactions.",
    tags:["toptal","andela"] },

  { id:"cm-031", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is one-hot encoding and when should you use target encoding instead?",
    answer:"One-hot encoding: convert a categorical feature with K unique values into K binary columns. Suitable for nominal categories with low cardinality (K < 20) and linear models. Target encoding: replace each category value with the mean target value for that category (optionally smoothed to prevent overfitting for rare categories). Suitable for high-cardinality categories (city names, zip codes, user IDs) with tree-based models.",
    explanation:"Target encoding risk: leakage if computed on the training set without a held-out encoding set or cross-fitting scheme. sklearn's TargetEncoder (v1.3+) uses cross-fitting to prevent leakage. CatBoost handles categorical features natively using its ordered target statistics.",
    tags:["toptal","andela"] },

  { id:"cm-032", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is regularisation in the context of decision trees, and how does max_depth regularise?",
    answer:"Regularisation in decision trees limits tree complexity to prevent overfitting. max_depth: maximum depth of tree — deeper trees have more splits and can memorise training data. min_samples_split: minimum samples needed to make a split. min_samples_leaf: minimum samples in a leaf. These prevent the tree from making splits that are specific to very few samples. Cost-complexity pruning (ccp_alpha) removes branches whose impurity gain doesn't justify their complexity.",
    explanation:"A tree of depth d can have at most 2^d leaves. depth=1 is a decision stump (just one split). depth=∞ on training data gives zero training error. Optimal depth depends on data complexity and sample size, found via cross-validation.",
    tags:["andela"] },

  { id:"cm-033", group:"classical-ml", difficulty:"hard", type:"short",
    question:"How does LightGBM differ from XGBoost in its tree-building strategy?",
    answer:"XGBoost: level-wise tree growth (grows all nodes at same depth before going deeper) — balanced but wastes splits on low-gain nodes. LightGBM: leaf-wise growth (splits the leaf with maximum gain, regardless of depth) — asymmetric trees, higher accuracy per split, converges faster. LightGBM also uses: Gradient-based One-Side Sampling (GOSS, keeps high-gradient samples), Exclusive Feature Bundling (EFB, bundles mutually exclusive features), histogram-based split finding. Result: 10-100× faster than XGBoost on large datasets.",
    explanation:"LightGBM is more prone to overfitting with small datasets (leaf-wise can go very deep quickly). Use min_child_samples (min_data_in_leaf) to regularise. For datasets with >10k samples, LightGBM is typically the best starting point for tabular data in 2026.",
    tags:["toptal","frequently-tested"] },

  { id:"cm-034", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is the difference between bagging and pasting in ensemble methods?",
    answer:"Bagging: each model is trained on a bootstrap sample (sampling with replacement). Some training examples appear multiple times; ~36.8% are excluded from each sample. Pasting: sampling without replacement — each subset is a unique sample of the training data with no repeats. Bagging is more common because bootstrap sampling introduces diversity even with small datasets. Pasting can be useful when you want each model to see genuinely different data.",
    explanation:"Both approaches then aggregate predictions (majority vote for classification, averaging for regression). Bagging provides extra regularisation because the bootstrap samples have higher variance than the true distribution, which helps models generalise.",
    tags:["toptal"] },

  { id:"cm-035", group:"classical-ml", difficulty:"easy", type:"short",
    question:"What is a precision-recall curve and when is it more informative than ROC?",
    answer:"A precision-recall curve plots precision vs. recall across all classification thresholds. It's more informative than ROC when the positive class is rare (imbalanced datasets). The random classifier baseline in PR space is at precision = fraction_positive (e.g., 0.01 for 1% positive rate), not 0.5. A model achieving AUC-PR of 0.3 vs. baseline 0.01 shows the true discriminative power, whereas AUC-ROC would still look high (above 0.9) for a model that simply ranks all negatives above positives.",
    explanation:"AUC-PR summarises the curve as a single number. For fraud detection, disease screening, or information retrieval (ranked search results), AUC-PR is the standard metric. F1 is the harmonic mean of precision and recall at a single threshold — AUC-PR integrates over all thresholds.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"cm-036", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is the difference between KD-Tree and Ball Tree for KNN search?",
    answer:"KD-Tree: partitions space with axis-aligned splits, builds a binary tree. Efficient in low dimensions (D<20), degrades to O(N×D) brute force in high dimensions as pruning becomes ineffective. Ball Tree: partitions data into nested hyperspheres. Uses triangle inequality to prune. More efficient than KD-Tree in medium dimensions (D=10-50) because spherical boundaries are tighter than axis-aligned boxes in high dimensions. Both are exact KNN; for D>50, use approximate methods (HNSW).",
    explanation:"sklearn's KNeighborsClassifier defaults to 'auto' which chooses KD-Tree for D<20 and Ball Tree for D≥20. For embedding-based retrieval (D=768+), use FAISS or HNSW instead of sklearn.",
    tags:["toptal"] },

  { id:"cm-037", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is hierarchical clustering and what are linkage criteria?",
    answer:"Hierarchical clustering builds a tree of clusters (dendrogram) by iteratively merging (agglomerative) or splitting (divisive) clusters. Linkage criteria define the distance between two clusters: Single linkage (min distance between any two points, creates chains), Complete linkage (max distance, creates compact clusters), Average linkage (mean pairwise distance, balance of both), Ward linkage (minimise within-cluster variance, tends to create equal-sized clusters, default in sklearn).",
    explanation:"Agglomerative clustering doesn't require specifying K upfront — choose K by 'cutting' the dendrogram at a height. Inspect the dendrogram to find natural cluster structure (large jumps in merge height suggest good cut points). O(N²) time complexity for most linkages.",
    tags:["andela"] },

  { id:"cm-038", group:"classical-ml", difficulty:"hard", type:"short",
    question:"What is the curse of dimensionality's specific effect on KNN?",
    answer:"In high dimensions, all pairwise distances converge: max_dist/min_dist → 1 as D→∞. The K nearest neighbours become as far as the farthest points — 'nearest' loses meaning. Empirically: KNN accuracy peaks around D=5-20 features and degrades sharply above D=50. The volume of a D-dimensional hypersphere relative to the bounding hypercube → 0 exponentially with D, meaning most of the space is in corners far from training data.",
    explanation:"Fix: apply PCA or UMAP to reduce dimensions before KNN. If using embeddings for KNN (e.g., RAG retrieval at D=768 or 1536), the problem is mitigated because embeddings concentrate in lower-dimensional manifolds — semantic similarity still works despite high nominal dimensionality.",
    tags:["toptal"] },

  { id:"cm-039", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is the VIF (Variance Inflation Factor) and how is it used?",
    answer:"VIF measures how much the variance of a coefficient estimate is inflated due to collinearity with other features. VIF of feature j = 1 / (1 - R²_j), where R²_j is the R² from regressing feature j on all other features. VIF=1: no collinearity. VIF=5: moderate (some caution). VIF>10: problematic collinearity — consider removing or combining features.",
    explanation:"VIF is a diagnostic, not a fix. After identifying high-VIF features: remove the most redundant, use PCA to create uncorrelated components, or apply Ridge regression which handles collinearity by shrinking unstable coefficients.",
    tags:["toptal"] },

  { id:"cm-040", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is heteroscedasticity and how do you detect and fix it in regression?",
    answer:"Heteroscedasticity: the variance of residuals is not constant across all levels of the predictor (violates OLS assumption 3). Detection: plot residuals vs. fitted values — a funnel pattern (residuals spread as fitted values increase) indicates heteroscedasticity; Breusch-Pagan test for formal testing. Fix: log-transform the target (common for right-skewed targets like price, count), use Weighted Least Squares, or use robust standard errors (HC3) for inference.",
    explanation:"Heteroscedasticity doesn't bias coefficient estimates but makes standard errors and confidence intervals incorrect. For predictive ML (not inference), heteroscedasticity has less impact — but it can indicate a missing feature or the need for a non-linear model.",
    tags:["toptal"] },

  { id:"cm-041", group:"classical-ml", difficulty:"easy", type:"mcq",
    options:["Training time increases; inference time stays same",
             "Training time stays same; inference time increases",
             "Both training and inference time increase",
             "No change; trees are scale-invariant"],
    question:"What happens to a Random Forest when you double the number of trees (n_estimators)?",
    answer:"Training time increases; inference time stays same",
    explanation:"More trees means more independent training runs — linear increase in training time. At inference, predictions from additional trees are averaged, which is also linear in n_estimators — so inference does roughly double too. However, the key practical point is that more trees monotonically improves performance (reduces variance) with diminishing returns after ~200-500 trees, and there is no overfitting from adding more trees.",
    tags:["andela"] },

  { id:"cm-042", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is the purpose of cross_val_score vs cross_validate in sklearn?",
    answer:"cross_val_score: returns an array of scores for each fold — simplest API, good for single-metric evaluation. cross_validate: returns a dict with test scores, train scores, fit times, and score times for each fold. Also supports multiple metrics. cross_validate is preferred when you need: training scores (to detect overfitting), multiple metrics, or timing information. Both use StratifiedKFold by default for classification.",
    explanation:"Common pitfall: running cross_val_score on data that was preprocessed (scaled, imputed) before splitting causes leakage. Always use Pipeline to ensure preprocessing is fitted only on training folds: Pipeline([('scaler', StandardScaler()), ('clf', SVC())]).",
    tags:["andela"] },

  { id:"cm-043", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is the silhouette score and how do you interpret it?",
    answer:"Silhouette coefficient for sample i: s(i) = (b-a)/max(a,b), where a = mean intra-cluster distance, b = mean distance to nearest other cluster. Range: [-1, +1]. s≈+1: well-clustered (far from other clusters). s≈0: near decision boundary between clusters. s≈-1: probably mis-clustered. Average over all samples gives global clustering quality. Use to compare different K values or clustering algorithms.",
    explanation:"Silhouette score requires distance computation between all pairs — O(N²) — which is expensive for large N. Use Davies-Bouldin index (also internal, lower is better) or Calinski-Harabasz score as faster alternatives.",
    tags:["andela"] },

  { id:"cm-044", group:"classical-ml", difficulty:"hard", type:"short",
    question:"What is isotonic regression and when is it used?",
    answer:"Isotonic regression fits a non-parametric, piecewise-constant monotonically increasing function to data. Unlike linear regression (assumes a specific slope), isotonic regression only assumes monotonicity and fits the best monotone step function. Main use in ML: probability calibration — apply isotonic regression to classifier scores to produce well-calibrated probabilities. More flexible than Platt scaling (logistic regression calibration) but requires more data.",
    explanation:"CalibratedClassifierCV in sklearn supports both Platt scaling and isotonic regression. Isotonic regression overfits with small calibration sets (<1000 samples) — use Platt scaling for small sets, isotonic for large.",
    tags:["toptal"] },

  { id:"cm-045", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is feature hashing (hashing trick) and why is it used for high-cardinality categoricals?",
    answer:"Feature hashing maps high-cardinality categorical values to a fixed-size vector using a hash function: h(value) % n_features → set that bit. No vocabulary required, O(1) memory regardless of cardinality. Suitable for: online learning (streaming data with new categories), very high-cardinality features (user IDs, IP addresses), and memory-constrained environments. Collision (different values map to same index) is a minor concern — increase n_features to reduce it.",
    explanation:"sklearn: HashingVectorizer for text. The hashing trick is fundamental to large-scale ML systems (e.g., Vowpal Wabbit). Unlike one-hot encoding, it avoids the out-of-vocabulary problem — new categories at inference time are simply hashed, not ignored.",
    tags:["toptal"] },

  { id:"cm-046", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is the difference between accuracy and balanced accuracy?",
    answer:"Accuracy = (TP+TN) / (TP+TN+FP+FN). Balanced accuracy = average of per-class recall = (Recall_class1 + Recall_class2) / 2 (for binary) = (1/K) Σ Recall_k. Balanced accuracy gives equal weight to each class regardless of support. For a 95%/5% class split, a model predicting only the majority class gets 95% accuracy but 50% balanced accuracy (recall for minority = 0, majority = 1, average = 50%).",
    explanation:"Balanced accuracy is equivalent to accuracy on a class-balanced dataset. Use it whenever class imbalance exists and you care equally about all classes. sklearn: balanced_accuracy_score(y_true, y_pred).",
    tags:["andela"] },

  { id:"cm-047", group:"classical-ml", difficulty:"hard", type:"short",
    question:"What is the difference between model-based and model-agnostic interpretability methods?",
    answer:"Model-based (intrinsic): interpretability built into the model structure. Examples: linear regression coefficients, decision tree rules, logistic regression log-odds ratios. Fast and exact but limited to specific model families. Model-agnostic (post-hoc): applied after training to any model. Examples: SHAP, LIME, partial dependence plots, permutation importance. Flexible but approximations — SHAP is exact for tree models (TreeSHAP) but approximate for neural networks.",
    explanation:"LIME (Local Interpretable Model-agnostic Explanations): fit a local linear model around each prediction. Fast, intuitive, but unstable (perturbation sampling is stochastic) and doesn't sum to the total prediction. SHAP is theoretically grounded (Shapley values satisfy fairness axioms) and the current standard for ML interpretability.",
    tags:["toptal"] },

  { id:"cm-048", group:"classical-ml", difficulty:"easy", type:"short",
    question:"What is a regression tree and how does it differ from a classification tree?",
    answer:"A regression tree predicts a continuous target value. Split criterion: minimise weighted MSE of child nodes (instead of Gini/entropy). Leaf value: mean target value of training samples reaching that leaf. Classification tree: predicts a class label. Leaf value: majority class or class probability distribution. Everything else is identical: greedy split selection, pruning, ensemble methods (Random Forest Regressor, GBM Regressor).",
    explanation:"Regression trees are piecewise constant — they output a constant value for each leaf region. They approximate any function but require deep trees for smooth functions. Gradient boosting regression trees achieve state-of-the-art performance on tabular regression tasks.",
    tags:["turing","andela"] },

  { id:"cm-049", group:"classical-ml", difficulty:"medium", type:"short",
    question:"What is the difference between hard voting and soft voting in ensemble classifiers?",
    answer:"Hard voting: each model predicts a class label, final prediction is the majority class. Ignores confidence. Soft voting: each model predicts class probabilities, final prediction is the argmax of the averaged probabilities. Soft voting is generally better because it weights confident predictions more than uncertain ones. Requires all models to produce calibrated probabilities.",
    explanation:"sklearn: VotingClassifier(voting='soft'). For soft voting to work well, component models should be calibrated — SVM and decision trees may need CalibratedClassifierCV wrapping before including in soft voting.",
    tags:["andela"] },

  { id:"cm-050", group:"classical-ml", difficulty:"hard", type:"short",
    question:"What is stacking (stacked generalisation) and how does it extend simple ensembling?",
    answer:"Stacking: train diverse base learners (Level 0), then train a meta-learner (Level 1) on their out-of-fold predictions as features. The meta-learner learns how to best combine base models. Unlike voting (fixed weights), stacking learns an optimal combination. Critical: base models must make predictions via cross-validation (out-of-fold) to prevent leakage — the meta-learner must not see the training data labels that the base models saw.",
    explanation:"Common stacking setup: Level 0: Random Forest, XGBoost, LinearRegression, KNN. Level 1: Ridge or Logistic Regression (simple meta-learner to avoid overfitting). StackingClassifier in sklearn handles the out-of-fold training correctly automatically.",
    tags:["toptal"] },

];
