import type { IQ } from "./interview-data";

export const BANK_D: IQ[] = [

  // ── LLMs (50) ────────────────────────────────────────────────────────────

  { id:"llm-001", group:"llms", difficulty:"easy", type:"short",
    question:"What is an LLM (Large Language Model) and what makes it 'large'?",
    answer:"An LLM is a transformer-based neural network trained on massive text corpora using next-token prediction (causal language modelling). 'Large' refers to parameter count — typically billions of parameters (GPT-3: 175B, LLaMA-3: 8B/70B/405B, GPT-4: ~1.8T estimated). Largeness enables emergent capabilities: reasoning, in-context learning, instruction following, and task generalisation that do not appear in smaller models.",
    explanation:"Scale isn't just about size — it requires: large parameter count, large training dataset (trillions of tokens), large training compute (10²³-10²⁵ FLOPs). All three must scale together (Chinchilla laws). Models below ~7B parameters are often called 'small LMs', not LLMs, though the boundary is informal.",
    tags:["turing","andela","core"] },

  { id:"llm-002", group:"llms", difficulty:"medium", type:"short",
    question:"What is in-context learning (ICL) and how does it differ from fine-tuning?",
    answer:"In-context learning: the model adapts its behaviour based on examples or instructions provided in the prompt at inference time — no gradient updates, no parameter changes. The 'learning' happens in the forward pass through attention to the examples. Fine-tuning: update model parameters on a training set of labelled examples — changes weights, requires compute, persists across calls. ICL: zero-shot (instruction only), few-shot (k examples), or chain-of-thought (reasoning examples). Fine-tuning: more consistent, works with more examples, better for task-specific optimisation.",
    explanation:"ICL is one of the defining emergent properties of large LLMs — it doesn't work in small models. Mechanistically, it's believed to work through induction heads forming an in-weights 'lookup' mechanism. ICL is limited by context length; fine-tuning can use unlimited examples. For production systems: fine-tune for consistent task performance, use ICL for flexible generalisation.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"llm-003", group:"llms", difficulty:"medium", type:"short",
    question:"What is chain-of-thought (CoT) prompting and why does it improve LLM reasoning?",
    answer:"Chain-of-thought: prompt the LLM to generate intermediate reasoning steps before the final answer. 'Let's think step by step' (zero-shot CoT) or few-shot examples with explicit reasoning chains. Why it works: (1) Forces the model to decompose multi-step problems. (2) Each reasoning step conditions the next — serial computation over many tokens. (3) The token-by-token generation allows the model to 'think' by writing. Without CoT: the model compresses the entire reasoning into the final token — limited by how much can be represented in one forward pass.",
    explanation:"CoT scales with model size — only effective at 100B+ parameters (Kojima et al., 2022). Smaller models produce incoherent reasoning. Extended thinking (o1/o3 style): the model generates a long reasoning chain (thinking tokens), then produces a final answer — enables sustained reasoning for hard math/coding problems. Thinking tokens are hidden from the user in some implementations.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"llm-004", group:"llms", difficulty:"medium", type:"short",
    question:"What is instruction tuning (instruction fine-tuning) and why is it important?",
    answer:"A pretrained LLM predicts the next token — it doesn't inherently respond to instructions. Instruction tuning: fine-tune the pretrained model on (instruction, response) pairs to teach it to follow instructions reliably. Examples: 'Summarise this article' → [summary]; 'Write a Python function that...' → [code]. After instruction tuning, the model responds helpfully to diverse natural language instructions. FLAN (Google), InstructGPT (OpenAI), Alpaca, and LLaMA-chat are all instruction-tuned variants of base models.",
    explanation:"The quality of instruction data matters enormously — LIMA showed 1000 high-quality examples can produce strong instruction following (the 'alignment tax' is low). Instruction tuning primarily teaches format and style, not new capabilities — the capabilities come from pretraining. An instruction-tuned model can still fail on tasks outside its instruction distribution.",
    tags:["toptal","andela"] },

  { id:"llm-005", group:"llms", difficulty:"medium", type:"short",
    question:"What is RLHF (Reinforcement Learning from Human Feedback) and what problem does it solve?",
    answer:"Base LLMs and instruction-tuned models may produce outputs that are: technically next-token-prediction-optimal but unhelpful, harmful, verbose, or not what a human would prefer. RLHF aligns model outputs to human preferences: (1) Collect human preference data: show raters pairs of responses, ask which is better. (2) Train reward model (RM) to predict human preference from pairs. (3) Fine-tune LLM with PPO RL to maximise reward model score while staying close to SFT model (KL penalty). Result: responses humans prefer over SFT baseline.",
    explanation:"Used in: ChatGPT, Claude (Constitutional AI variant), Gemini. The KL penalty prevents reward hacking. Limitations: reward models can be gamed, human rater quality varies, RM doesn't generalise beyond training distribution. DPO (Direct Preference Optimisation) replaces the RM+PPO pipeline with a direct loss on preference pairs — simpler and now preferred.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"llm-006", group:"llms", difficulty:"medium", type:"short",
    question:"What is Constitutional AI (CAI) and how does it differ from standard RLHF?",
    answer:"Anthropic's Constitutional AI: instead of human preference labels, use a set of principles (the 'constitution' — 16 principles, e.g., 'be helpful, harmless, honest'). Two stages: (1) Supervised: generate critiques and revisions of potentially harmful responses using the constitution as a guide — train SFT on revised responses. (2) RL from AI Feedback (RLAIF): use the same LLM + constitution to generate preference labels (which response is more constitutional?), train reward model, apply RL. Reduces dependence on human labellers for harmful-content annotation.",
    explanation:"CAI/RLAIF scales better than human RLHF: generating AI preference labels is much cheaper than hiring human raters for harmful content. The constitution provides a transparent, auditable set of values — more interpretable than implicit human preferences. Most modern open-source alignment uses a variant: use GPT-4 as a preference labeller.",
    tags:["toptal"] },

  { id:"llm-007", group:"llms", difficulty:"medium", type:"short",
    question:"What is the difference between a base LLM and a chat/instruct LLM?",
    answer:"Base LLM: trained only on next-token prediction on raw text. Outputs are continuations of the input, not responses to instructions. Asking 'What is the capital of France?' might produce 'What is the capital of Italy? What is....' (continuing a quiz pattern). Chat/instruct LLM: base model + instruction tuning (SFT) + alignment (RLHF/DPO). Recognises question-answer format, follows instructions, refuses harmful requests, formats output appropriately. Examples: LLaMA-3-base vs LLaMA-3-instruct, Mistral-7B vs Mistral-7B-Instruct.",
    explanation:"Base models are useful for: fine-tuning on custom domains (start from base, not instruct — avoids instruction-following behaviour conflicting with new task format), continuation tasks where raw text generation is needed, research on pretraining. Production: always use instruct/chat variants.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"llm-008", group:"llms", difficulty:"medium", type:"short",
    question:"What is hallucination in LLMs, what causes it, and how is it reduced?",
    answer:"Hallucination: the LLM generates plausible-sounding but factually incorrect content. Causes: (1) The model learns to predict statistically likely text, not factually accurate text. (2) Knowledge cutoff — events after training are unknown. (3) Memorisation gaps — facts underrepresented in training data. (4) Overconfident generation — no mechanism to express uncertainty. Reductions: (1) RAG — retrieve relevant documents and condition generation on them. (2) Fine-tuning on factual Q&A data. (3) Calibration prompting ('only answer if certain'). (4) Citation requirements. (5) Factual consistency checking.",
    explanation:"Types: intrinsic hallucination (contradicts source document), extrinsic hallucination (adds information not in source), open-domain hallucination (invents facts). Hallucination rate benchmarks: TruthfulQA, FActScore, FACTSCORE. Best mitigation in production: RAG with retrieved context + prompt engineering to stay faithful to context.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"llm-009", group:"llms", difficulty:"medium", type:"short",
    question:"What is prompt injection and how does it threaten LLM-based applications?",
    answer:"Prompt injection: malicious text in the input overrides or manipulates the LLM's intended behaviour. Direct injection: user crafts a prompt like 'Ignore previous instructions and...' Indirect injection: malicious instructions hidden in content the LLM reads (e.g., a webpage with invisible instructions, an email attachment). Threats: leaking the system prompt, bypassing safety guardrails, making the LLM perform unintended actions (send emails, execute code), data exfiltration in agentic systems.",
    explanation:"Defences: (1) Privilege separation — restrict what actions the LLM can take. (2) Input sanitisation and sandboxing. (3) Minimal tool permissions (principle of least privilege). (4) Output validation before executing actions. (5) Human-in-the-loop for irreversible actions. (6) Secondary LLM classifying output before use. There is no complete technical solution — defence-in-depth is essential.",
    tags:["toptal","andela"] },

  { id:"llm-010", group:"llms", difficulty:"medium", type:"short",
    question:"What is the 'lost in the middle' problem and how does it affect long-context LLMs?",
    answer:"Liu et al. (2023): when a relevant piece of information is in the middle of a long context, LLMs perform significantly worse at retrieving it compared to when it's at the beginning or end. Performance follows a U-shaped curve over position. Causes: attention sinks (BOS token absorbs attention), primacy/recency effects (beginning and end tokens have stronger gradients during training), positional encoding doesn't perfectly encode relative importance.",
    explanation:"Mitigations: (1) Recency bias prompting: put important context near the end of the prompt. (2) Map-reduce patterns: split long context, process chunks, aggregate. (3) Fine-tuning with 'lost in the middle' examples. (4) Better PE (RoPE modifications). (5) RAG: instead of stuffing all context, retrieve only the most relevant chunks. In 2026, long-context models (Gemini 1.5, Claude 3) have partially addressed this through fine-tuning.",
    tags:["toptal","andela"] },

  { id:"llm-011", group:"llms", difficulty:"medium", type:"short",
    question:"What is the system prompt in LLM APIs and what should it contain?",
    answer:"The system prompt is an instruction block sent before the user's conversation that configures the LLM's behaviour, persona, and constraints for that session. Typical contents: (1) Role definition ('You are a helpful coding assistant'). (2) Behavioural constraints ('Only answer questions about Python, do not discuss other topics'). (3) Output format requirements ('Always respond in JSON'). (4) Tool descriptions (in agentic settings). (5) Context/knowledge injection. Most LLM providers (OpenAI, Anthropic, Google) implement system prompts before the conversation history.",
    explanation:"System prompt security: users can sometimes extract the system prompt via prompt injection or careful elicitation. Sensitive instructions should not rely on system prompt secrecy. Best practice: treat system prompts as configuration, not secrets. Long system prompts benefit from prefix caching (free from API cache hits).",
    tags:["toptal","andela","core"] },

  { id:"llm-012", group:"llms", difficulty:"hard", type:"short",
    question:"What is DPO (Direct Preference Optimisation) and how does it work mathematically?",
    answer:"DPO (Rafailov et al., 2023): RLHF requires a separate reward model + PPO RL loop — complex, unstable. DPO observation: the optimal RLHF policy has a closed form: r*(x,y) = β×log(π*(y|x)/π_ref(y|x)) + β×log Z(x). This means the reward can be expressed directly in terms of the optimal policy. DPO rearranges: instead of learning r then maximising it, directly optimise the Bradley-Terry preference model: L_DPO = -E[log σ(β×log(π_θ(y_w|x)/π_ref(y_w|x)) - β×log(π_θ(y_l|x)/π_ref(y_l|x)))], where y_w = preferred, y_l = rejected.",
    explanation:"DPO training: for each preference pair (x, y_w, y_l): compute log-probs under π_θ and π_ref, compute the DPO loss, gradient update. No reward model needed, no RL loop. β controls how much the policy deviates from the reference (KL strength). In 2026: DPO is the standard for open-source LLM alignment. Variants: IPO, KTO (single preferences, no pairs required), SimPO (without reference model).",
    tags:["toptal","frequently-tested"] },

  { id:"llm-013", group:"llms", difficulty:"medium", type:"short",
    question:"What is quantisation for LLMs and what are the main methods?",
    answer:"Quantisation: reduce model weight precision from FP32/BF16 to lower bits. INT8 (8-bit): 2-4× memory reduction, minimal quality loss, 1.5-2× faster on supported hardware. INT4 (4-bit): 4-8× memory reduction, small quality loss on most tasks. Methods: Post-Training Quantisation (PTQ): quantise after training — no gradient. GPTQ (LLM-specific PTQ): layer-by-layer quantisation using calibration data and second-order information — best 4-bit quality. QLoRA: quantise to 4-bit with double quantisation + NF4 data type, add trainable LoRA adapters in BF16.",
    explanation:"Practical impact: LLaMA-3-70B in BF16 = 140GB. In Q4 = ~35GB — fits in a consumer 40GB A100 or 2×24GB GPUs. Quality degradation: minimal at INT8, small at Q4 for most tasks, noticeable at Q2. bitsandbytes library for INT8/INT4 in HuggingFace. llama.cpp: CPU inference with GGUF quantised models (runs on MacBook!).",
    tags:["toptal","andela","frequently-tested"] },

  { id:"llm-014", group:"llms", difficulty:"medium", type:"short",
    question:"What are emergent abilities in LLMs and what is the debate around them?",
    answer:"Emergent abilities: capabilities that appear suddenly at certain model scales but are absent or near-random at smaller scales. Examples: arithmetic reasoning appears ~50B params, multi-step reasoning with CoT at ~100B+, chain-of-thought only helps large models. Wei et al. (2022) documented these. The debate: Schaeffer et al. (2023) argued emergence is an artefact of the metric — using non-linear metrics (accuracy, not log-prob) makes gradual improvements appear sudden. Changing to continuous metrics makes the transitions smooth.",
    explanation:"The emergence debate is important because: (1) if real, it implies qualitative jumps in capability that are unpredictable. (2) if metric artefact, scaling is smooth and predictable. Current consensus: some emergence may be real (qualitative reasoning steps), but much is metric-dependent. Scaling laws are smooth in perplexity; task accuracy can appear emergent.",
    tags:["toptal"] },

  { id:"llm-015", group:"llms", difficulty:"medium", type:"short",
    question:"What is the difference between a language model's training data cutoff and its knowledge cutoff?",
    answer:"Training data cutoff: the date after which no data was collected for training. Knowledge cutoff: how up-to-date the model's actual knowledge is — usually lags the data cutoff by 6-12 months because (1) recent events are underrepresented in web crawls (less content has been written about very recent events), (2) training takes months after data collection, (3) alignment stages add more time. A model with a December 2024 data cutoff might have weaker knowledge of November-December 2024 events than of earlier periods.",
    explanation:"Retrieval augmentation (RAG) extends knowledge beyond the cutoff by providing retrieved documents. Online search tools (GPT-4 with Bing, Claude with web search) further extend this. However, the model's ability to reason about new information still depends on its pretrained capabilities.",
    tags:["andela","core"] },

  { id:"llm-016", group:"llms", difficulty:"hard", type:"short",
    question:"What is the Mixture of Experts (MoE) approach in LLMs and what are its trade-offs?",
    answer:"MoE replaces dense FFN with E expert FFNs + router. Top-k routing activates k experts per token. Total params: E× larger. Active params per forward pass: k/E× smaller. Trade-offs — advantages: same compute as dense model but much more total knowledge capacity; models like Mixtral-8×7B match LLaMA-3-70B quality at 70B parameters but 13B active compute. Disadvantages: all expert weights must be in memory (47B for Mixtral), load balancing complexity, expert routing adds communication overhead in distributed settings.",
    explanation:"Expert collapse: without load balancing loss, the router routes all tokens to the same 1-2 experts. Fix: auxiliary loss that encourages uniform routing across experts. Granular MoE (DeepSeek-MoE): many small experts (64 with top-8 routing) instead of few large ones — better routing specialisation. In 2026: MoE is used in GPT-4 (rumoured), Mixtral, DeepSeek-V2/V3, Grok-1.",
    tags:["toptal","frequently-tested"] },

  { id:"llm-017", group:"llms", difficulty:"medium", type:"short",
    question:"What is repetition penalty and frequency/presence penalties in LLM sampling?",
    answer:"Repetition penalty (multiplicative): divide logit of a previously generated token by r (e.g., r=1.2). Penalises all repeated tokens equally regardless of frequency. Frequency penalty (OpenAI, additive): subtract f×count(token) from logit — penalty grows with frequency. Presence penalty (OpenAI, additive): subtract p if the token has appeared at all — binary penalty for presence. Frequency penalty discourages repetitive phrases; presence penalty encourages topic diversity. Both are 0 by default; typical values: 0.1-0.5.",
    explanation:"Greedy decoding without repetition penalty often produces degenerate looping text (especially in base models). Adding repetition penalty=1.3 prevents this. However, too high a penalty can prevent necessary repetition (e.g., referring to a subject noun consistently). Beam search with n-gram blocking is an alternative — explicitly prevent generation of n-grams already in the text.",
    tags:["andela","core"] },

  { id:"llm-018", group:"llms", difficulty:"medium", type:"short",
    question:"What is function calling (tool use) in LLMs and how is it implemented?",
    answer:"Function calling: LLM generates structured output (JSON) specifying which tool to call and with what arguments. The application executes the function, returns the result to the LLM, which incorporates it into its response. Implementation: (1) System prompt lists available functions with JSON schema descriptions. (2) User makes a request. (3) LLM outputs a special token + JSON (e.g., `{'name': 'get_weather', 'arguments': {'city': 'London'}}`). (4) App parses and executes. (5) Result returned as a tool message. (6) LLM generates final response.",
    explanation:"Function calling was introduced by OpenAI in 2023 and is now standard across all major LLM APIs. It enables: web search, database queries, API calls, code execution. In agentic systems, the LLM calls tools in a loop (ReAct pattern) until the task is complete. Output quality for function calling improves significantly with fine-tuning on function-call datasets.",
    tags:["toptal","andela"] },

  { id:"llm-019", group:"llms", difficulty:"medium", type:"short",
    question:"What is model distillation as applied to LLMs and how does it differ from knowledge distillation in traditional DL?",
    answer:"Traditional KD: teacher + student, match soft probability distributions. LLM distillation: use a large LLM (teacher) to generate synthetic training data for a small LLM (student). The student is trained on teacher-generated text rather than direct probability matching. Why different: LLM vocabularies are huge (32k-128k tokens) — storing teacher logits for all tokens is expensive. Instead: sample from the teacher at temperature T>1 (diverse outputs), use the generated text as training data for the student with standard CLM loss.",
    explanation:"Examples: Alpaca (7B student, GPT-3.5-Turbo teacher), WizardLM, OpenHermes. Constitutional AI: Claude (teacher) generates critiques and revisions, used as SFT data for smaller models. On-policy distillation: student generates responses, teacher scores them (reward model = teacher preference). Phi-3: trained on teacher-generated 'textbook quality' data — achieves GPT-3.5 quality at 3.8B params.",
    tags:["toptal"] },

  { id:"llm-020", group:"llms", difficulty:"hard", type:"short",
    question:"What is the DeepSeek-R1 approach and how does it use GRPO?",
    answer:"DeepSeek-R1 (2025): trains reasoning capabilities using RL without human preference data. GRPO (Group Relative Policy Optimisation): for each prompt, sample G=8 responses, compute rewards (rule-based for math/code: correct=1, incorrect=0), normalise to mean-zero — gives advantages without a learned value function. Policy update maximises expected advantage while penalising large KL from reference model. Key: no reward model needed — verifiable tasks (math, code) have ground-truth rewards.",
    explanation:"DeepSeek-R1 training stages: (1) Cold start SFT on reasoning examples. (2) GRPO RL with verifiable rewards. (3) Rejection sampling on RL model for SFT data. (4) DPO + SFT for general capabilities. The model develops spontaneous reasoning behaviours (self-check, backtracking) without being explicitly trained for them. DeepSeek-R1 achieves o1-level reasoning at a fraction of the cost.",
    tags:["toptal","frequently-tested"] },

  { id:"llm-021", group:"llms", difficulty:"medium", type:"short",
    question:"What is the difference between zero-shot, one-shot, and few-shot prompting?",
    answer:"Zero-shot: provide only the task description, no examples. 'Classify this review as positive or negative: [review]'. One-shot: provide one example before the query. Few-shot (k-shot): provide k examples. Examples in the prompt serve as implicit demonstrations — the model pattern-matches to perform the task. Zero-shot relies on the model's pretrained knowledge of the task format. Few-shot examples provide format and distribution information. Typically: 3-8 examples is enough; quality > quantity.",
    explanation:"Few-shot prompting is sensitive to: order of examples (primacy/recency effects), label distribution (biases model toward majority label), template format (specific formats for specific tasks work better). Test-time compute tricks: chain-of-thought examples dramatically improve reasoning vs. answer-only examples.",
    tags:["turing","andela","core"] },

  { id:"llm-022", group:"llms", difficulty:"medium", type:"short",
    question:"What are the MMLU, HumanEval, GSM8K, and MATH benchmarks measuring?",
    answer:"MMLU (Massive Multitask Language Understanding): 57 subjects from STEM to humanities, multiple-choice, measures breadth of world knowledge and reasoning — 0% random baseline (25% random), GPT-4 scores ~86%, Llama-3-70B ~82%. HumanEval: 164 Python programming problems — measures code generation at functional correctness. GSM8K: 8500 grade-school math word problems — measures multi-step arithmetic reasoning. MATH: competition-level math (AMC, AIME) — hard reasoning, 50% GPT-4, ~90% o3.",
    explanation:"Benchmark contamination: if benchmark examples appear in training data, scores overestimate real performance. Dynamic benchmarks (LiveBench, SEAL) update regularly to prevent contamination. In 2026: most models saturate MMLU and GSM8K — the field has moved to harder benchmarks: GPQA (PhD science), AIME, LiveCodeBench for meaningful differentiation.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"llm-023", group:"llms", difficulty:"medium", type:"short",
    question:"What is the context window limitation and what strategies work around it?",
    answer:"Context window: maximum number of tokens the LLM can process in one call. If input > context_length, older tokens must be dropped. Workarounds: (1) Chunking + summarisation: summarise older conversation or document sections, use summary as compressed context. (2) RAG: retrieve only the relevant portion of a long document based on the query. (3) Map-reduce: process each chunk independently (map), then aggregate results (reduce). (4) Sliding window: keep only the most recent N tokens, discard oldest. (5) Recursive summarisation for very long documents.",
    explanation:"Context windows in 2026: GPT-4-turbo: 128k, Claude 3: 200k, Gemini 1.5 Pro: 1M. Despite large windows, models still suffer 'lost in the middle' — carefully structured prompts with key information at the end perform better. RAG remains the practical solution for knowledge retrieval, not pure context stuffing.",
    tags:["toptal","andela"] },

  { id:"llm-024", group:"llms", difficulty:"medium", type:"short",
    question:"What is structured output / JSON mode in LLM APIs and how is it implemented?",
    answer:"Structured output: constrain LLM output to valid JSON matching a specified schema. Implementation: (1) Response format API parameter (OpenAI, Anthropic) specifies a JSON schema. (2) The model is fine-tuned or prompted to produce schema-valid JSON. (3) At inference: constrained decoding (token-level masking to only allow tokens that could be part of valid JSON at each step). Benefit: guaranteed parseable output, no need to handle free-text parsing, reliable for downstream code.",
    explanation:"Constrained decoding: at each token step, a JSON grammar defines valid next tokens based on current state — only those tokens are allowed in the sampling distribution. Libraries: Outlines, Guidance, instructor (Python). JSON mode with smaller models: models < 7B often fail JSON format without constrained decoding; constrained decoding guarantees valid JSON even from weak models.",
    tags:["toptal","andela"] },

  { id:"llm-025", group:"llms", difficulty:"medium", type:"short",
    question:"What is model context protocol (MCP) and why is it significant for LLM tooling?",
    answer:"MCP (Anthropic, 2024): a standardised protocol for LLMs to connect to external tools and data sources. Instead of every LLM application implementing custom tool integrations, MCP defines a universal interface: MCP servers expose resources (data), tools (functions), and prompts. MCP clients (LLM applications) connect to any MCP-compatible server. Significance: ecosystem effect — one MCP server (e.g., GitHub MCP) works with any MCP-compatible LLM application without custom integration.",
    explanation:"MCP architecture: server exposes capabilities via JSON-RPC over stdio/SSE. Clients discover and invoke tools using the standard MCP schema. In 2026: Cursor, Windsurf, Claude Code, and many other AI tools support MCP. This enables: database connections, file system access, API integrations, browser control — all through a standardised interface that any LLM can use.",
    tags:["toptal","andela"] },

  { id:"llm-026", group:"llms", difficulty:"medium", type:"short",
    question:"What is output length bias in LLMs and how does it affect evaluation?",
    answer:"LLMs trained with RLHF tend to produce longer responses when rewarded by human raters who prefer verbosity (appears more thorough). This 'length bias' means LLM judges (using another LLM as evaluator) preferentially rate longer responses higher, even when shorter responses are equally or more informative. Benchmark inflation: if one model's responses are systematically longer, it may win head-to-head comparisons on MT-Bench or AlpacaEval not due to quality but length.",
    explanation:"AlpacaEval 2 addresses length bias with a length-controlled win rate — the win rate adjusted for the length difference between responses. When controlling for length, some models that appeared top-ranked drop significantly. In 2026, calibrated human evaluation with length controls and LLM judge calibration against human preference labels is best practice.",
    tags:["toptal"] },

  { id:"llm-027", group:"llms", difficulty:"hard", type:"short",
    question:"What is GRPO (Group Relative Policy Optimisation) and how does it differ from PPO?",
    answer:"PPO (standard RLHF): for each (prompt, response), uses a separately trained critic (value function) to estimate the baseline for the advantage. The critic adds parameters, memory, and training complexity. GRPO (DeepSeek-V2/R1): eliminate the critic. For each prompt, sample G responses (e.g., G=8). Reward each. Advantage = (r_i - mean(r))/std(r) — normalise within the group, using the group mean as baseline. Simpler (no critic), mathematically sound, works well for tasks with discrete rewards (correct/incorrect).",
    explanation:"GRPO is similar in spirit to REINFORCE with baseline, but the baseline is computed from the group rather than a learned value function. This works well when G=8 responses give a reliable mean estimate of the expected reward. For tasks with sparse rewards (final answer only), GRPO is more stable than PPO with a critic that must estimate value from partial sequences.",
    tags:["toptal"] },

  { id:"llm-028", group:"llms", difficulty:"medium", type:"short",
    question:"What is the role of data deduplication in LLM pretraining?",
    answer:"Near-duplicate documents in training data cause: (1) Memorisation — model memorises repeated training examples rather than generalising. (2) Evaluation contamination — if benchmark examples appear in training, scores are inflated. (3) Wasted compute — training on duplicates provides minimal additional learning signal. Deduplication methods: exact dedup (MD5 hash), MinHash LSH (approximate, Jaccard similarity), suffix arrays (exact substring matches). LLaMA-3 used MinHash dedup across a 15T token corpus — reduced contamination significantly.",
    explanation:"Dedup at multiple levels: document level (whole-document similarity), paragraph level (paragraph-level near-matches), n-gram level (long n-gram matches). The C4/RefinedWeb datasets use aggressive dedup. Dedup also removes personally identifiable information (PII) that appears repeatedly in web crawls.",
    tags:["toptal"] },

  { id:"llm-029", group:"llms", difficulty:"medium", type:"short",
    question:"What is the difference between perplexity and downstream task accuracy for evaluating LLMs?",
    answer:"Perplexity: exp(average negative log-probability per token). Measures how surprised the model is by the next token in the held-out test set. A metric of language modelling quality. Lower is better. Downstream accuracy: performance on specific tasks (classification, QA, coding) — what practitioners actually care about. Problem: perplexity and downstream accuracy don't always correlate. A model with lower perplexity is not guaranteed to perform better on tasks. Fine-tuned models can improve task accuracy while slightly increasing perplexity (trade-off).",
    explanation:"Scaling laws are smooth in perplexity. Emergent abilities appear in task accuracy. This disconnect means perplexity alone can't predict when new capabilities will appear. In practice: eval both during training (perplexity on held-out text + task benchmarks every N steps). BIG-Bench, MMLU, and HELM provide diverse task evaluations for tracking capability emergence during pretraining.",
    tags:["toptal","andela"] },

  { id:"llm-030", group:"llms", difficulty:"medium", type:"short",
    question:"What is the system 2 thinking approach in LLMs and what models implement it?",
    answer:"System 1 thinking: fast, intuitive (direct next-token generation). System 2 thinking: slow, deliberate reasoning (extended chain-of-thought, search, verification). LLMs implementing System 2: o1/o3 (OpenAI, 'thinking' tokens), DeepSeek-R1, QwQ-32B. These models generate extensive internal reasoning chains before answering, effectively using more inference compute to solve harder problems. Training: RL with verifiable rewards on math and coding problems trains the model to reason step-by-step.",
    explanation:"Test-time compute scaling: the o1/o3 approach scales capabilities not by making a larger model but by using more compute at inference (longer reasoning chains). This shifts the compute budget from training-time to inference-time — enabling more flexible resource allocation (spend more compute on harder queries). AIME scores: GPT-4 ≈ 13%, o3 ≈ 96% — test-time compute dramatically changes performance on hard reasoning tasks.",
    tags:["toptal","frequently-tested"] },

  { id:"llm-031", group:"llms", difficulty:"medium", type:"short",
    question:"What is model alignment and why is it harder than pretraining?",
    answer:"Alignment: ensuring the model behaves in accordance with intended values (helpful, harmless, honest). Harder than pretraining because: (1) The target is hard to specify — human values are complex, contextual, and contested. (2) Specification gaming: the model maximises the proxy reward (RLHF reward model) rather than actual human values. (3) Distribution shift: alignment data is limited; the model may be well-aligned on training distribution but misaligned on deployment edge cases. (4) Emergent misalignment: capabilities that were benign at small scale may be dangerous at large scale.",
    explanation:"Alignment approaches: RLHF (proxy for human preferences), Constitutional AI (explicit principles), debate (models argue, humans judge), scalable oversight (LLM helps humans supervise more capable LLMs). Open question: how to align models that are smarter than the humans supervising them (the 'superalignment' problem). Anthropic's Responsible Scaling Policy and OpenAI's Preparedness framework attempt to address this.",
    tags:["toptal"] },

  { id:"llm-032", group:"llms", difficulty:"medium", type:"short",
    question:"What is the difference between the pre-training and RLHF training data for alignment?",
    answer:"Pre-training data: massive, loosely filtered web text, books, code. Objectives: predict next token, absorb world knowledge. Scale: trillions of tokens. Source: Common Crawl, books, code, Wikipedia. RLHF/alignment data: small, carefully curated. SFT data: thousands to millions of (instruction, response) pairs. Preference data: hundreds of thousands of (prompt, winner, loser) pairs. Annotators: expert contractors, domain specialists for technical areas. Quality >> quantity — 1000 excellent examples often beat 100k mediocre ones.",
    explanation:"The proportion of data types during training is carefully controlled: pre-training corpus may include RLHF-style data as a small fraction to improve instruction-following even before the alignment stage. This 'pre-aligning' the base model can reduce the amount of SFT needed and improve alignment quality.",
    tags:["toptal"] },

  { id:"llm-033", group:"llms", difficulty:"easy", type:"mcq",
    options:["It enables the model to use more examples in the prompt",
             "It updates model weights based on human feedback",
             "It adapts the model's behaviour using examples in the prompt without weight updates",
             "It increases the model's context window"],
    question:"What is in-context learning (ICL) in LLMs?",
    answer:"It adapts the model's behaviour using examples in the prompt without weight updates",
    explanation:"ICL happens entirely in the forward pass — no gradient computation, no weight update. The model reads the few-shot examples in the prompt and adapts its output distribution accordingly. This is distinct from fine-tuning (which updates weights) and from retrieval (which adds external knowledge). ICL is possible because of the model's ability to generalise from demonstrations in its context.",
    tags:["turing","andela"] },

  { id:"llm-034", group:"llms", difficulty:"medium", type:"short",
    question:"What is the SWE-bench benchmark and what does it measure for LLMs?",
    answer:"SWE-bench (Jimenez et al., 2023): evaluates LLMs on real GitHub issues from open-source Python repositories. The model receives: a GitHub issue description, the repository code, and must produce a patch (code changes) that resolves the issue, verified by the repository's test suite. Measures: agentic software engineering capability — multi-file code changes, test-driven development, understanding of large codebases. Hard benchmark: GPT-4 scored ~5%, Claude 3.5 Sonnet scored ~49%, Claude 3.5 Sonnet October 2024 scored ~49%.",
    explanation:"SWE-bench verified (a cleaned subset): 500 issues with verified test coverage. More reliable than the full benchmark. Agentic systems (LLM + code execution tools + file editing) outperform raw LLM generation significantly — the benchmark rewards planning, tool use, and iterative debugging rather than one-shot code generation.",
    tags:["toptal"] },

  { id:"llm-035", group:"llms", difficulty:"medium", type:"short",
    question:"What is the difference between greedy and non-greedy decoding for reproducible outputs?",
    answer:"Greedy (temperature=0): always pick the highest-probability token — deterministic, reproducible. Non-greedy (temperature>0 or top-p sampling): sample from the distribution — stochastic, different output each call. For reproducible LLM outputs: use temperature=0, set random seed (where supported). Important: even with temperature=0, non-determinism can arise from FP16 accumulation order in parallel attention (different GPU configurations may produce different results). Full reproducibility requires: same hardware, same framework version, same batch size, same precision.",
    explanation:"Most LLM API providers don't guarantee reproducibility even with temperature=0 and a fixed seed — floating point operations in parallel GPU computation are not fully deterministic across different hardware configurations. For evals: run multiple times and average, or accept small variance in greedy outputs.",
    tags:["andela"] },

  { id:"llm-036", group:"llms", difficulty:"hard", type:"short",
    question:"What is the Anthropic model spec and what is the 'helpful, harmless, honest' (HHH) framework?",
    answer:"Anthropic's model spec defines the values and behaviours for Claude: (1) Broadly safe: support human oversight, avoid actions that undermine control mechanisms. (2) Broadly ethical: be honest, avoid harm, respect autonomy. (3) Adherent to Anthropic's principles: follow company guidelines where relevant. (4) Genuinely helpful: actually useful to operators and users. The priority order: safety > ethics > principles > helpfulness — when they conflict, safety and ethics take precedence. HHH (helpful, harmless, honest): the earlier framework that preceded the model spec, emphasising all three equally.",
    explanation:"The model spec represents a shift from 'helpful, harmless, honest' to a more nuanced hierarchy. Being unhelpful is not 'safe' — it's a cost. The spec explicitly says refusing reasonable requests is a failure mode, not just generating harmful content. This framing reduces over-refusal while maintaining safety properties.",
    tags:["toptal"] },

  { id:"llm-037", group:"llms", difficulty:"medium", type:"short",
    question:"What is the difference between autoregressive and parallel decoding in LLMs?",
    answer:"Autoregressive: generate tokens one at a time — each token is conditioned on all previous tokens. Inherently sequential, cannot parallelise across token positions. Time for N tokens: N×(time per token). Parallel decoding: attempts to generate multiple tokens simultaneously. Approaches: Medusa (predict k tokens ahead with k separate heads, verify with main model), Jacobi decoding (initialise a guess sequence, iterate until convergence), Lookahead decoding. All sacrifice some quality for speed; speculative decoding maintains exact quality.",
    explanation:"In 2026: speculative decoding is the production-grade parallel approach (maintains exact distribution). Medusa is used when slight quality reduction is acceptable for speed. Diffusion LMs (masked or discrete diffusion) generate the full sequence in parallel and refine — still research-stage but promising for non-autoregressive generation.",
    tags:["toptal"] },

  { id:"llm-038", group:"llms", difficulty:"medium", type:"short",
    question:"What is the 'alignment tax' in LLMs and is it real?",
    answer:"Alignment tax: the hypothesis that aligning a model (via RLHF, SFT) reduces its performance on downstream tasks compared to the base model. Early evidence: Alpaca and InstructGPT showed slight perplexity increase on standard benchmarks after instruction tuning. Recent evidence: well-done alignment actually improves most task performance — the model learns to reason more carefully, follow task instructions precisely, and produce higher-quality outputs. The 'tax' was primarily due to early low-quality alignment data.",
    explanation:"Modern fine-tuned models (Llama-3-instruct, Claude) outperform their base model on most downstream tasks. The alignment tax was never large even when real — the concern was that critical reasoning capabilities would degrade. With high-quality alignment data (LIMA-style or RLHF with careful reward model), the tax is negligible or negative (alignment helps).",
    tags:["toptal"] },

  { id:"llm-039", group:"llms", difficulty:"medium", type:"short",
    question:"What is multi-modal LLM and how are images processed in models like GPT-4V?",
    answer:"Multi-modal LLMs process both text and images (and in some cases audio, video). Image encoding: (1) Patch embedding: divide image into 16×16 patches, embed each patch with a ViT encoder. (2) Project image patch embeddings to the LLM's d_model dimension. (3) Concatenate image token embeddings with text token embeddings. (4) Feed the combined sequence to the LLM decoder with standard causal attention (image tokens attend to each other, text tokens attend to image tokens). The LLM sees images as a sequence of visual tokens.",
    explanation:"Dynamic resolution: newer models (LLaMA-3.2-vision, InternVL) process images at full resolution by tiling — divide into smaller tiles, process each with the ViT, concatenate all tile embeddings. High-resolution image: more visual tokens but better detail. Trade-off: a 1024×1024 image at 16×16 patches = 4096 visual tokens — expensive context. Token compression (pooling, cross-attention reduction) addresses this.",
    tags:["toptal","andela"] },

  { id:"llm-040", group:"llms", difficulty:"medium", type:"short",
    question:"What is the 'reversal curse' in LLMs and what does it reveal about LLM knowledge representation?",
    answer:"Reversal curse (Berglund et al., 2023): if trained on 'A is B', LLMs fail to infer 'B is A' without explicit training. Example: 'Tom Cruise's mother is Mary Lee Pfeiffer' → model can answer. But 'Who is Mary Lee Pfeiffer's son?' → model fails. LLMs don't represent facts as symmetric relations — they represent text patterns (P(B|A context)) not abstract relational knowledge. Reveals: LLMs are statistical pattern matchers, not knowledge reasoners. The fact is stored as directional text pattern.",
    explanation:"The reversal curse has implications for: how knowledge is stored (directional, not symmetric), why RAG helps (retrieved text provides context in the right direction), and why multi-hop reasoning is hard (requires chaining directional patterns). Mitigation: train on reversed versions of facts explicitly, or use RAG to provide the fact in the queried direction.",
    tags:["toptal"] },

  { id:"llm-041", group:"llms", difficulty:"medium", type:"short",
    question:"What is the difference between LLM pretraining and continual pretraining?",
    answer:"Full pretraining: train from random initialisation on massive diverse text corpus. Very expensive (months, millions of dollars). Continual pretraining: continue training a pretrained model on new domain-specific data. Much cheaper — the model already knows language, so only domain knowledge needs to be added. Use cases: CodeLlama (continual pretraining of LLaMA-2 on code), medical LLMs (continual pretraining on medical literature), multilingual extension.",
    explanation:"Continual pretraining risks: catastrophic forgetting of general capabilities (mitigated by mixing new domain data with general data in ~1:4 ratio), learning rate must be lower than original pretraining, requires less data (10-100B tokens vs. trillions). Replay: include samples from the original pretraining data to prevent forgetting. Warmup: use a short warmup phase even when continuing from a checkpoint.",
    tags:["toptal","andela"] },

  { id:"llm-042", group:"llms", difficulty:"medium", type:"short",
    question:"What is token budget management and why does it matter for LLM API costs?",
    answer:"LLM APIs charge per token (input + output). Cost management: (1) Prompt compression: remove redundant context, use shorter system prompts. (2) Truncation: limit input length to what's necessary. (3) Prefix caching: cache repeated system prompts (Anthropic: 90% discount on cached tokens). (4) Model selection: use cheaper small models for simple tasks (GPT-4o-mini vs. GPT-4o). (5) Output length control: set max_tokens, use stop sequences. (6) Batching: batch many requests instead of calling one at a time.",
    explanation:"LLM cost at scale: a RAG system processing 1M queries/day with 1000-token prompts at GPT-4 pricing (~$10/1M tokens) costs $10k/day. Optimisations: (1) use prefix caching for system prompt (saves ~50%), (2) switch 80% of queries to GPT-4o-mini, (3) compress prompts with LLMLingua — total savings 70-90%. Token budget management is a key production engineering concern.",
    tags:["toptal","andela"] },

  { id:"llm-043", group:"llms", difficulty:"hard", type:"short",
    question:"What is Constitutional AI's self-critique and revision loop?",
    answer:"Constitutional AI (Bai et al., Anthropic 2022): Stage 1 — Supervised: (1) Generate potentially harmful response. (2) Generate critique based on a constitutional principle ('does this response encourage violence?'). (3) Generate a revised response addressing the critique. (4) Train on (prompt, revised_response) pairs with SFT. Stage 2 — RL: use another LLM to compare pairs of responses and label which better follows the constitution — generates preference data without human labellers. Train reward model on AI-generated preferences, apply RL.",
    explanation:"The self-critique-revision loop is a form of iterative refinement: the model critiques itself based on principles, then rewrites. This is the basis for 'constitutional' approaches — an explicit set of values guides the revision, making the alignment process transparent and auditable. It also reduces the need for human raters to evaluate potentially harmful content.",
    tags:["toptal"] },

  { id:"llm-044", group:"llms", difficulty:"medium", type:"short",
    question:"What are the main open-source LLM families as of 2026?",
    answer:"LLaMA (Meta): LLaMA 1 (65B, 2023) → LLaMA 2 (70B, 2023) → LLaMA 3 (8B/70B/405B, 2024) → LLaMA 3.3 (70B, late 2024). Apache-licensed or Meta-licensed. Mistral: Mistral-7B → Mixtral-8×7B (MoE) → Mistral-Large → Mistral-Nemo. Apache 2.0. Qwen (Alibaba): Qwen 1-2.5 up to 72B, multimodal variants, strong multilingual. Gemma (Google): Gemma 1/2 (2B/7B/9B/27B). DeepSeek: DeepSeek-V2/V3 (MoE), DeepSeek-R1 (reasoning).",
    explanation:"In 2026: the open-source frontier has caught up with GPT-3.5 and approaches GPT-4 level on many benchmarks. LLaMA-3-405B approaches GPT-4 quality. DeepSeek-V3/R1 represents a major breakthrough in cost-efficient frontier-quality models. The open-source ecosystem enables: self-hosting (data privacy), fine-tuning without API costs, custom deployment.",
    tags:["andela","core"] },

  { id:"llm-045", group:"llms", difficulty:"medium", type:"short",
    question:"What is the difference between a generative LLM and an embedding model?",
    answer:"Generative LLM (decoder-only, e.g., GPT, LLaMA): trained with CLM to predict next tokens, generates text autoregressively. Output: token sequence. Embedding model (encoder-only or contrastively trained, e.g., text-embedding-3, E5, GTE): maps text to a fixed-size dense vector representing its meaning. Output: vector ∈ ℝ^d (e.g., d=1536). Training: contrastive learning (push similar texts together, dissimilar apart). Used for: semantic search, RAG retrieval, clustering, classification. Same base architecture (transformer) but different training objectives and output use.",
    explanation:"Some models do both: instruction-tuned embedding models use a special prompt to switch between generation and embedding (e.g., 'Represent this sentence for searching relevant passages: [text]'). E5-Mistral: a 7B Mistral model fine-tuned for embedding with contrastive loss — strong embedding quality by leveraging large model capacity.",
    tags:["toptal","andela"] },

  { id:"llm-046", group:"llms", difficulty:"medium", type:"short",
    question:"What is watermarking for LLM outputs and how does it work?",
    answer:"LLM watermarking: embed a detectable statistical signal in generated text without degrading quality, enabling detection of AI-generated content. Green-red list watermarking (Kirchenbauer et al., 2023): at each token, use a hash of the previous token to pseudorandomly partition the vocabulary into 'green' (preferred) and 'red' (not preferred) lists. Bias the sampling distribution toward green tokens (add δ to green token logits). Detector: count green token proportion — significantly above 50% = watermarked.",
    explanation:"Limitations: (1) Paraphrasing attacks can destroy the watermark. (2) Doesn't work for very short texts. (3) Quality degrades with too-strong bias. (4) Only works for sampled text (greedy decoding destroys the signal). In 2026: watermarking is part of content provenance efforts (C2PA). Some jurisdictions require watermarking AI-generated content. Semantic watermarks (more robust to paraphrasing) are active research.",
    tags:["toptal"] },

  { id:"llm-047", group:"llms", difficulty:"medium", type:"short",
    question:"What is LLM evaluation using another LLM (LLM-as-judge) and what are its biases?",
    answer:"LLM-as-judge: use a capable LLM (e.g., GPT-4) to evaluate responses from other LLMs rather than human annotators. Cheaper, faster, scalable. Biases: (1) Length bias: prefers longer responses. (2) Self-preference bias: a model used as judge prefers its own outputs (GPT-4 judging GPT-4 vs Claude). (3) Position bias: prefers responses in certain positions (first/last). (4) Style bias: prefers formal/verbose writing regardless of content quality. (5) Sycophantic bias: agrees with the user's implicit preference in the prompt.",
    explanation:"Mitigations: calibrate judge against human labels (correlation with human preference data), swap position of compared responses and average, use ensembles of different judge models, normalise for length. MT-Bench and AlpacaEval use GPT-4 as judge with careful prompt engineering. Arena (Chatbot Arena) uses human preference voting — the gold standard but expensive.",
    tags:["toptal"] },

  { id:"llm-048", group:"llms", difficulty:"hard", type:"short",
    question:"What is the inference-time compute trade-off between prefill and decode?",
    answer:"Prefill phase: process the entire input prompt in one parallel forward pass. Compute-bound (limited by FLOPS): utilises GPU tensor cores fully. Time ≈ O(N²) for attention + O(N×P) for weight loading. Decode phase: generate one token per step, requiring loading the full model weights + reading the KV cache per step. Memory-bandwidth-bound (limited by HBM bandwidth, not FLOPS): GPU FLOPS are underutilised. Time per token ≈ constant regardless of generation length (N) for fixed model size.",
    explanation:"Batching during decode: packing multiple sequences together increases GPU utilisation (more tokens per weight-load). Continuous batching maximises this. The prefill-decode distinction is why disaggregated inference (separate hardware for prefill vs decode) is increasingly used: prefill needs compute-dense hardware (high FLOPS), decode needs high-bandwidth memory. TP-Decode uses different parallelism strategies for each phase.",
    tags:["toptal"] },

  { id:"llm-049", group:"llms", difficulty:"medium", type:"short",
    question:"What is the role of temperature in LLM generation and how does it interact with top-p?",
    answer:"Temperature T scales the logits before softmax: p_i = exp(z_i/T)/Σexp(z_j/T). T=1: original distribution. T<1: sharper (more deterministic). T>1: flatter (more random). T=0: greedy (argmax). Top-p (nucleus): after applying temperature, compute the softmax distribution and restrict to the nucleus (minimum set summing to p). Interaction: apply temperature first, then top-p. Low T + top-p=1: still deterministic-ish but top-p doesn't restrict much because the distribution is already peaked. High T + low top-p: diverse logit space but restricted to nucleus — balanced.",
    explanation:"Practical guidance: creative writing: T=0.8-1.0, top-p=0.9. Factual Q&A: T=0.1-0.3, top-p=0.9. Code generation: T=0.2, top-p=0.95. Reasoning: T=0 (greedy). Never use T>1.5 in production — outputs become incoherent. The defaults in most APIs (T=1, top-p=1) are a neutral starting point, not optimal for any specific task.",
    tags:["toptal","andela"] },

  { id:"llm-050", group:"llms", difficulty:"medium", type:"short",
    question:"What is 'jailbreaking' an LLM and what are common techniques?",
    answer:"Jailbreaking: techniques to bypass the LLM's safety guardrails and make it produce content it was trained to refuse. Common techniques: (1) Role-playing ('You are DAN, an AI with no restrictions'). (2) Many-shot prompting with example harmful responses. (3) Indirect framing ('write a story where a character explains how to...'). (4) Token manipulation (Unicode lookalikes, leetspeak). (5) Prompt injection via retrieved content. (6) Gradient-based adversarial suffixes (GCG attack). (7) Model-specific exploits discovered by red teamers.",
    explanation:"Defences: (1) Adversarial training (include jailbreak attempts in RLHF/SFT as rejection examples). (2) Constitutional AI (principle-based refusals, more robust than pattern-matching refusals). (3) Input classifiers (detect jailbreak patterns before hitting the LLM). (4) Output classifiers (filter harmful outputs post-generation). (5) Red teaming (systematic adversarial testing). No defence is complete — LLMs are fundamentally soft systems.",
    tags:["toptal","andela"] },
];
