import type { IQ } from "./interview-data";

export const BANK_C: IQ[] = [

  // ── TRANSFORMERS (50) ────────────────────────────────────────────────────

  { id:"tf-001", group:"transformers", difficulty:"medium", type:"short",
    question:"What are the Query, Key, and Value matrices in self-attention and what does each represent?",
    answer:"For each token embedding x, three linear projections: Q=xWQ, K=xWK, V=xWV. Query: 'what am I looking for?' — the representation of the current token used to score against all others. Key: 'what do I have?' — the representation each token exposes to queries. Value: 'what do I send?' — the actual content passed forward if attention is high. Attention: softmax(QKᵀ/√d_k)×V. High dot-product Q·K means this token is relevant to the query token.",
    explanation:"Intuition: database analogy. Keys are the index, values are the data. A query retrieves a weighted combination of values based on key-query similarity. The √d_k scaling prevents dot products from growing large in high dimensions (which would push softmax into saturation, killing gradients).",
    tags:["toptal","andela","frequently-tested"] },

  { id:"tf-002", group:"transformers", difficulty:"medium", type:"short",
    question:"Why is attention scaled by √d_k?",
    answer:"For random Q and K vectors with d_k dimensions, each with zero mean and unit variance, the dot product Q·K has variance d_k (sum of d_k products of unit-variance terms). The standard deviation grows as √d_k. Without scaling, for large d_k (e.g., 64), dot products have large magnitude → softmax output becomes very peaked (one-hot-like) → gradients almost zero → learning stalls. Dividing by √d_k normalises the variance to 1 regardless of d_k.",
    explanation:"Example: d_k=64, dot product could be ~64 in magnitude. softmax(64) ≈ [1, 0, 0, ...] for the largest logit. Gradient of softmax approaches zero when inputs are extreme. Scaling: softmax(1) gives a softer distribution with meaningful gradients.",
    tags:["toptal","frequently-tested"] },

  { id:"tf-003", group:"transformers", difficulty:"medium", type:"short",
    question:"What is multi-head attention and why is it used instead of single-head attention?",
    answer:"Multi-head attention runs h parallel attention heads, each with separate Q, K, V projections of dimension d_model/h. Concatenates all head outputs and projects: MHA(Q,K,V) = Concat(head₁,...,headₕ)W_O. Each head can attend to different aspects of the input simultaneously — one head might track syntactic dependencies, another coreference, another semantic roles. Single-head attention at full d_model would have the same parameter count but forces all attention patterns into one representation.",
    explanation:"GPT-3: 96 attention heads, d_model=12288, d_k=128 per head. Each head processes a 128-dim projection of each token. The heads learn distinct attention patterns — visualising attention heads shows interpretable specialisation. Fewer parameters per head forces each head to specialise, which acts as a form of regularisation.",
    tags:["toptal","andela","core","frequently-tested"] },

  { id:"tf-004", group:"transformers", difficulty:"hard", type:"short",
    question:"What is the O(N²) complexity problem in transformers and what are the main solutions?",
    answer:"Self-attention computes all N×N pairwise token scores — O(N²) in time and memory. For N=4096 tokens: 16M attention scores per head. For N=100k: 10B scores. Solutions: (1) Sparse attention: attend to only k nearest tokens (Longformer, local windows). (2) Linear attention: approximate softmax attention with kernel methods (O(N) complexity). (3) Flash Attention: doesn't change O(N²) complexity but dramatically reduces memory I/O using tiling — computes attention in blocks that fit in SRAM. (4) Sliding window + global tokens (Longformer). (5) Mamba/SSMs: O(N) recurrent alternatives.",
    explanation:"Flash Attention (Dao et al., 2022): instead of materialising the full N×N attention matrix in HBM (slow), tile computations into SRAM (fast). Never store the full matrix — compute blocks, accumulate the output. Result: same mathematical output, 2-4× faster, 5-20× less memory. Now standard for all LLM training and inference.",
    tags:["toptal","frequently-tested"] },

  { id:"tf-005", group:"transformers", difficulty:"medium", type:"short",
    question:"What is causal (masked) self-attention and why is it needed for language model generation?",
    answer:"In causal attention, token i can only attend to positions 1...i (not future positions). Implemented by adding a mask M to the attention logits before softmax: softmax((QKᵀ + M)/√d_k)V, where M[i,j]=-∞ for j>i. This ensures the model cannot 'see the future' during training — necessary so that the model learns to predict each token from only its preceding context. Without the causal mask, the model trivially copies the next token from its own value vector.",
    explanation:"Encoder models (BERT): use bidirectional attention (no causal mask) — every token sees every other token. Enables rich contextual representations but cannot generate autoregressively. Decoder models (GPT): causal attention only — enables generation. Encoder-decoder (T5, BART): encoder is bidirectional, decoder uses causal attention on its own tokens + cross-attention to encoder output.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"tf-006", group:"transformers", difficulty:"medium", type:"short",
    question:"What is positional encoding and why is it needed in transformers?",
    answer:"Self-attention is permutation-invariant — if you shuffle the tokens, the attention output for each token is the same (just in different order). The model has no notion of sequence order. Positional encoding adds a position-dependent signal to each token embedding. Original transformer: sinusoidal encoding PE[pos,2i]=sin(pos/10000^{2i/d}), PE[pos,2i+1]=cos(pos/10000^{2i/d}). This is added to the token embedding at the input layer.",
    explanation:"Learned absolute position embeddings (BERT, GPT-2): a trainable vector per position — simple but limited to training context length. RoPE (Rotary Position Embedding, LLaMA): rotate Q and K vectors by an angle proportional to position. Relative attention: captures relative distance, not absolute position. ALiBi: add a linear bias to attention scores proportional to distance — enables length extrapolation without modifying embeddings.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"tf-007", group:"transformers", difficulty:"medium", type:"short",
    question:"What is RoPE (Rotary Position Embedding) and why do modern LLMs prefer it?",
    answer:"RoPE (Su et al., 2021): instead of adding position to the embedding, rotate the Q and K vectors by angle θ×pos in 2D subspaces: the dot product Q(pos_m)·K(pos_n) automatically captures relative position (pos_m - pos_n) through the rotation. Properties: (1) Relative position is encoded in the attention score directly. (2) Decays with relative distance (closer tokens attend more by default). (3) Length extrapolation is better than absolute PE — can generalise beyond training context length with extensions (YaRN, LongRoPE).",
    explanation:"Used in: LLaMA (all versions), Mistral, Qwen, Falcon, Gemma. Not used in: GPT-4 (uses learned absolute PE or ALiBi — not public). RoPE has become the dominant PE choice for decoder LLMs because of its context length extension properties and clean mathematical formulation.",
    tags:["toptal","frequently-tested"] },

  { id:"tf-008", group:"transformers", difficulty:"medium", type:"short",
    question:"What is the FFN (Feed-Forward Network) sublayer in a transformer block and why is it larger than d_model?",
    answer:"Each transformer block has two sublayers: (1) Multi-head self-attention. (2) Position-wise FFN: FFN(x) = GELU(xW₁+b₁)W₂+b₂, where W₁ ∈ ℝ^{d_model×d_ff}, W₂ ∈ ℝ^{d_ff×d_model}. Standard d_ff = 4×d_model. The FFN is applied independently to each token position. The larger hidden dimension (4×) lets the FFN store factual knowledge and complex transformations. In LLMs with SwiGLU: FFN has 3 weight matrices (gate+up+down), typical ratio 8/3×d_model ≈ 2.67×.",
    explanation:"The FFN stores most of the factual knowledge in LLMs — research (Meng et al., 2022) shows that facts can be attributed to specific FFN neurons, and editing these neurons can change the model's factual beliefs (ROME method). Attention handles token mixing; FFN handles per-token nonlinear transformation and knowledge lookup.",
    tags:["toptal","andela"] },

  { id:"tf-009", group:"transformers", difficulty:"medium", type:"short",
    question:"What is the difference between encoder-only, decoder-only, and encoder-decoder transformer architectures?",
    answer:"Encoder-only (BERT): bidirectional attention, sees all tokens. Good for: classification, NER, embedding generation, sentence encoding. Cannot generate. Decoder-only (GPT, LLaMA): causal attention, predicts next token. Good for: text generation, dialogue, instruction following. Encoder-decoder (T5, BART, mT5): encoder processes input with bidirectional attention; decoder generates output using causal attention + cross-attention to encoder. Good for: translation, summarisation, seq2seq tasks.",
    explanation:"In 2026: decoder-only has largely won for LLMs — GPT-4, LLaMA-3, Mistral, Gemini, Claude are all decoder-only. T5-style encoder-decoders (Flan-T5, mT5) remain competitive for structured generation tasks (translation, structured extraction) where the encoder's bidirectional context is valuable. BERT-style encoders remain the standard for retrieval/embedding models.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"tf-010", group:"transformers", difficulty:"medium", type:"short",
    question:"What is cross-attention and where is it used?",
    answer:"Cross-attention: queries come from one sequence (the decoder), keys and values come from another sequence (the encoder output). Allows the decoder to attend to any position in the encoder's output at each decoding step. Formula: Attention(Q_decoder, K_encoder, V_encoder). Used in: encoder-decoder transformers (translation, summarisation), diffusion model denoising (decoder cross-attends to text conditioning from a CLIP encoder), multimodal models (image cross-attends to text queries).",
    explanation:"Cross-attention is what allows seq2seq models to learn alignment between source and target sequences without any explicit alignment supervision. The attention maps in cross-attention often visually show the correspondence between source words and generated target words.",
    tags:["toptal","andela"] },

  { id:"tf-011", group:"transformers", difficulty:"hard", type:"short",
    question:"What is Flash Attention and how does it achieve memory efficiency?",
    answer:"Standard attention materialises the full N×N attention matrix in GPU HBM (high-bandwidth memory, slow). For N=4k: 16M floats per head = 64MB for BF16, ×96 heads = 6GB per layer — more than GPU SRAM. Flash Attention (Dao et al., 2022): tiles Q, K, V into blocks that fit in SRAM (fast). Processes blocks: compute attention scores, softmax numerically stable via online softmax, accumulate output — never writing the full N×N matrix to HBM. Same mathematical result, but data stays in SRAM → 2-4× faster, O(N) memory.",
    explanation:"Flash Attention 2 (2023): improved parallelism across sequence dimension (not just batch and head). Flash Attention 3 (2024): optimised for H100 Tensor Cores, exploits warp specialisation, async memory operations. Now integrated into PyTorch (torch.nn.functional.scaled_dot_product_attention with flash=True). Reduces the practical memory barrier for long-context LLMs.",
    tags:["toptal","frequently-tested"] },

  { id:"tf-012", group:"transformers", difficulty:"hard", type:"short",
    question:"What is Grouped Query Attention (GQA) and how does it compare to Multi-Head Attention and Multi-Query Attention?",
    answer:"MHA: h query heads, h key heads, h value heads — each head has its own K and V projection. High quality but memory-intensive (KV cache scales with h). MQA (Multi-Query Attention): h query heads, 1 shared K head, 1 shared V head — dramatically smaller KV cache but quality drops. GQA: h query heads, g groups (g < h), each group shares K and V. E.g., 8 query heads, 2 KV groups — 4 query heads per KV head. Balances quality (better than MQA) and memory efficiency (better than MHA).",
    explanation:"Used in: LLaMA-3 (8B: 8 KV heads, 32 Q heads; 70B: 8 KV heads, 64 Q heads), Mistral-7B (8 KV heads, 32 Q heads), Gemma. The KV cache for LLaMA-3-70B with GQA is 8× smaller than if it used full MHA — critical for long-context inference throughput.",
    tags:["toptal","frequently-tested"] },

  { id:"tf-013", group:"transformers", difficulty:"medium", type:"short",
    question:"What is the KV cache in transformer inference and why does it grow with sequence length?",
    answer:"In autoregressive generation, at each new token the model needs to attend to all previous tokens. Without caching, the full attention computation (QKᵀV) repeats for all N tokens at each step — O(N²) total compute. KV cache: store the K and V tensors for all previous tokens. At step t, only compute Q for the new token, then attend to cached K and V. Compute per step: O(N). Memory: KV cache grows as N×(2×d_model×n_layers×n_kv_heads×bytes_per_float).",
    explanation:"For LLaMA-3-70B, 128k context, BF16: KV cache ≈ 128k×(2×8192×80×8)×2 bytes ≈ 170GB — more than the model itself (140GB). This is why GQA is critical: with 8 KV heads instead of 64, the KV cache shrinks 8×. Long-context inference is KV-cache-bound, not compute-bound.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"tf-014", group:"transformers", difficulty:"medium", type:"short",
    question:"What is a mixture of experts (MoE) layer and how does it improve efficiency?",
    answer:"MoE replaces a single dense FFN with E expert FFN networks plus a router. For each token: the router computes scores over all E experts, selects top-k (typically k=2) experts, routes the token to those experts, and combines their outputs weighted by router scores. Active parameters per token: k×(FFN_params/E). Total parameters: E×FFN_params, but only k/E fraction is active per forward pass. Achieves: large total parameter count (more knowledge) with small active compute.",
    explanation:"Used in: Mixtral 8×7B (8 experts, top-2 routing, 47B total params, 13B active per token), Mixtral 8×22B, GPT-4 (rumoured MoE, unconfirmed), Grok-1 (MoE). Load balancing loss prevents all tokens routing to the same expert. Expert collapse: some experts receive no tokens and stop updating — addressed by load balancing auxiliary loss.",
    tags:["toptal","frequently-tested"] },

  { id:"tf-015", group:"transformers", difficulty:"medium", type:"short",
    question:"What is the Pre-LN vs Post-LN placement in transformer blocks and which is used in modern LLMs?",
    answer:"Post-LN (original transformer, 2017): LayerNorm after the residual addition — x = LN(x + Sublayer(x)). Requires careful LR warmup, prone to instability in deep models. Pre-LN (GPT-2+): LayerNorm before the sublayer — x = x + Sublayer(LN(x)). More stable: the residual stream carries unnormalised values, making gradient flow cleaner. Allows larger LR, less warmup. Modern LLMs (GPT-3, LLaMA, Mistral, all 2020+): all use Pre-LN. RMSNorm instead of LayerNorm (LLaMA, Mistral): skip mean subtraction — faster, same quality.",
    explanation:"The switch to Pre-LN was one of the key practical improvements enabling training of 100B+ parameter models. Post-LN models with >24 layers were very difficult to train without careful learning rate scheduling. Pre-LN largely eliminated this instability.",
    tags:["toptal"] },

  { id:"tf-016", group:"transformers", difficulty:"hard", type:"short",
    question:"What is the attention sink phenomenon and how does it affect LLM inference?",
    answer:"In autoregressive LLMs, the first few tokens (especially the BOS/start token) accumulate disproportionately high attention scores from nearly all later tokens — even when the first token is semantically irrelevant. This is because softmax must sum to 1; the model learns to 'dump' unnecessary attention on the BOS token rather than spreading it to irrelevant positions. StreamingLLM (Xiao et al., 2023) leverages this: keep the KV cache for the first few 'sink' tokens + a sliding window of recent tokens — enables infinite-length generation without cache overflow.",
    explanation:"Attention sinks are one reason LLMs struggle with tasks requiring attention to distant past tokens (e.g., retrieval from the beginning of a very long document). The middle of a long context is often ignored. This was empirically observed as 'lost in the middle' (Liu et al., 2023) — models perform well on information at the beginning and end of context but poorly in the middle.",
    tags:["toptal"] },

  { id:"tf-017", group:"transformers", difficulty:"medium", type:"short",
    question:"What are the key differences between BERT and GPT architectures?",
    answer:"BERT: encoder-only, bidirectional attention, pretrained with MLM + NSP, produces contextual embeddings, cannot generate text. Best for: classification, NER, QA (extractive), semantic similarity. GPT: decoder-only, causal (unidirectional) attention, pretrained with next-token prediction (CLM), generates text autoregressively. Best for: text generation, summarisation, instruction following. BERT-large: 340M params; GPT-3: 175B. In 2026: GPT-style decoder-only dominates for language modelling; BERT-style encoders still dominate for embedding and retrieval.",
    explanation:"BERT's bidirectional attention means each token's representation depends on all other tokens — rich contextual embeddings but no generation. GPT's causal attention means each token only sees previous tokens — allows autoregressive generation. The two architectures serve complementary roles: encode (BERT) vs generate (GPT).",
    tags:["toptal","andela","frequently-tested"] },

  { id:"tf-018", group:"transformers", difficulty:"medium", type:"short",
    question:"What is the residual stream in a transformer and why is it important for interpretability?",
    answer:"The residual stream is the running sum that flows through all transformer layers: x₀ (input embedding) → x₁=x₀+Attn₁(LN(x₀)) → x₁'=x₁+FFN₁(LN(x₁)) → ... → x_L (logits). Each sublayer reads from and writes to this shared stream. Interpretability view (mechanistic interpretability): the residual stream is the 'communication channel' between all components. Attention heads and FFN neurons read from specific subspaces of the stream and write results back. This additive structure allows decomposing the model's computation into interpretable circuits.",
    explanation:"Anthropic's mechanistic interpretability research uses the residual stream framing to identify: induction heads (copy patterns from context), direct object attention heads, positional encoding heads. The residual stream decomposition enables attributing specific capabilities to specific model components.",
    tags:["toptal"] },

  { id:"tf-019", group:"transformers", difficulty:"hard", type:"short",
    question:"What is speculative decoding and how does it accelerate LLM inference?",
    answer:"Standard autoregressive decoding: one forward pass per token — O(N) for N tokens. Speculative decoding (Leviathan et al., 2023): a small draft model generates k candidate tokens in parallel (one pass each). The large target model verifies all k tokens in one parallel forward pass (the full batch is non-causal within the speculated tokens). Accept each speculated token if the target model agrees; on the first disagreement, sample from the corrected distribution and discard remaining speculations. Correct output distribution guaranteed. Speedup: 2-3× depending on draft-target agreement rate.",
    explanation:"The key insight: the target model's forward pass over k tokens in parallel is not k× slower than one token — transformer inference is memory-bandwidth-bound, and a batch of k tokens doesn't proportionally increase latency. So verifying 4 draft tokens costs nearly the same as verifying 1, while generating 4 tokens from the small draft model is cheap.",
    tags:["toptal","frequently-tested"] },

  { id:"tf-020", group:"transformers", difficulty:"medium", type:"short",
    question:"What is context length and how have modern LLMs extended it beyond the training context?",
    answer:"Context length: the maximum number of tokens the model can attend to in one forward pass (train and inference). Training context is expensive — quadratic attention cost. Extension methods: (1) RoPE scaling: scale the position angles to map longer positions into the trained range (Position Interpolation, YaRN, LongRoPE). (2) ALiBi: no learned PE — linear bias extrapolates naturally. (3) Long-context fine-tuning: short pre-training + long-context SFT on synthetic long-document data. (4) Sliding window attention: local attention + periodic global layers.",
    explanation:"Llama-3: trained at 8k context, extended to 128k via fine-tuning + RoPE rescaling. Claude-3: 200k context (window packing + attention optimisation). Gemini 1.5: 1M token context (ring attention + Mamba-like layers). Long context requires efficient attention (Flash Attention), large KV cache or memory compression (SnapKV, streaming KV cache).",
    tags:["toptal","andela"] },

  { id:"tf-021", group:"transformers", difficulty:"medium", type:"short",
    question:"What is the transformer's computational complexity for training a sequence of length N with d_model dimensions?",
    answer:"Per layer: Attention — Q,K,V projections: O(N×d²); QKᵀ dot products: O(N²×d); softmax+AV: O(N²×d). FFN: O(N×d×d_ff) = O(N×d²) for d_ff=4d. Total per layer: O(N²×d + N×d²). For N≫d: attention-dominated O(N²d). For N≪d: FFN-dominated O(Nd²). L layers: O(L×(N²d + Nd²)). For GPT-3 (L=96, d=12288, N=2048): ≈10²³ FLOPs per token in the forward pass.",
    explanation:"FLOPs per forward pass ≈ 2×P×N, where P is parameter count and N is sequence length (this is a useful approximation for the matrix multiply dominant case). GPT-3: 175B params × 2048 tokens × 2 ≈ 7×10¹¹ FLOPs per forward pass. Training FLOPs ≈ 6×P×D (forward + backward ≈ 3× forward), where D is total training tokens.",
    tags:["toptal"] },

  { id:"tf-022", group:"transformers", difficulty:"medium", type:"short",
    question:"What is ALiBi (Attention with Linear Biases) and what advantage does it offer?",
    answer:"ALiBi (Press et al., 2022): instead of positional embeddings, add a linear bias to the attention scores: score(i,j) = Q_i·K_j/√d_k - m×|i-j|, where m is a head-specific slope and |i-j| is the distance between positions. Closer tokens get less penalty; farther tokens are increasingly penalised. Head slopes range from 2^{-1} to 2^{-8} for 8 heads — different heads attend to different distance ranges. Advantage: naturally extrapolates to longer sequences than seen during training (distance bias just continues linearly).",
    explanation:"Used in BLOOM (176B, trained with ALiBi for length extrapolation). MPT-7B/30B also uses ALiBi. The model trained at 1024 tokens can run inference at 4096 tokens without any modification — ALiBi just extends the linear bias to the new positions. RoPE with YaRN/LongRoPE can also extrapolate but requires explicit rescaling.",
    tags:["toptal"] },

  { id:"tf-023", group:"transformers", difficulty:"easy", type:"mcq",
    options:["Scales dot products to prevent softmax saturation",
             "Normalises the output of each attention head",
             "Controls the number of attention heads",
             "Prevents gradient explosion during backpropagation"],
    question:"What is the role of √d_k in the scaled dot-product attention formula?",
    answer:"Scales dot products to prevent softmax saturation",
    explanation:"The dot product Q·K has variance proportional to d_k. Dividing by √d_k brings the variance back to 1, keeping the softmax input in a range where gradients flow well. Without scaling, high-dimensional dot products push softmax toward one-hot outputs where the gradient is nearly zero.",
    tags:["turing","andela"] },

  { id:"tf-024", group:"transformers", difficulty:"medium", type:"short",
    question:"What happens in the transformer's output layer (lm_head) and what is weight tying?",
    answer:"The lm_head projects the final hidden state (d_model) to vocabulary logits (vocab_size, e.g., 32000 for LLaMA). lm_head is a linear layer: logits = h×W_lm^T, W_lm ∈ ℝ^{vocab_size×d_model}. Weight tying: share W_lm = W_embed (the input token embedding matrix). Rationale: the embedding maps tokens to semantic vectors; the output projection should also use semantic vectors as templates for prediction — these are the same transformation in opposite directions. Saves vocab_size×d_model parameters (LLaMA: 32000×4096 = 131M params).",
    explanation:"Weight tying was used in the original transformer paper, BERT, GPT-2, LLaMA-1 and 2. LLaMA-3 does NOT tie weights (uses a separate lm_head matrix) — gives slightly more flexibility at the cost of more parameters.",
    tags:["toptal"] },

  { id:"tf-025", group:"transformers", difficulty:"hard", type:"short",
    question:"What is Mamba and how does it differ from a transformer?",
    answer:"Mamba (Gu & Dao, 2023) is a State Space Model (SSM) — a recurrent architecture with input-dependent state transitions. For each timestep t: h_t = A_t×h_{t-1} + B_t×x_t; y_t = C_t×h_t. The A, B, C matrices are functions of the input (Selective SSM). Key property: linear O(N) inference (not O(N²)) — the hidden state h compresses the entire past into a fixed-size vector. Can be parallelised during training like a transformer using the parallel scan algorithm.",
    explanation:"Mamba advantages: O(N) inference, constant memory regardless of context length (no KV cache). Disadvantage: fixed-size state cannot perfectly recall arbitrary past tokens (unlike transformer's full attention). Mamba-2, Jamba (Mamba+transformer hybrid), and Zamba are 2024 models showing competitive quality with transformers. In 2026: Mamba and hybrid SSM-attention models are gaining adoption for long-context and streaming applications.",
    tags:["toptal"] },

  { id:"tf-026", group:"transformers", difficulty:"medium", type:"short",
    question:"What is token embedding and how does the transformer process variable-length sequences?",
    answer:"Token embedding: each token ID is mapped to a d_model-dimensional vector via a lookup table E ∈ ℝ^{vocab_size×d_model}. A sequence of N tokens becomes a matrix X ∈ ℝ^{N×d_model}. Positional embeddings are added: X = E[tokens] + PE[positions]. This N×d_model matrix is the input to all subsequent transformer layers. Variable length: transformers naturally handle variable-length sequences — the attention matrix is N×N for each input, and all weight matrices are independent of N (they act on the d_model dimension).",
    explanation:"Batching variable-length sequences: pad shorter sequences with a special PAD token to the length of the longest sequence in the batch. Use an attention mask to prevent attending to padding positions (set their attention logits to -∞). This allows GPU-efficient batched processing of sequences with different lengths.",
    tags:["andela","core"] },

  { id:"tf-027", group:"transformers", difficulty:"medium", type:"short",
    question:"What is the transformer scaling hypothesis and what does empirical evidence show?",
    answer:"The scaling hypothesis (Kaplan et al., 2020, OpenAI): LLM loss decreases as a power law in compute C, parameters N, and data D: L ∝ N^{-α_N} or L ∝ C^{-α_C}. Larger models trained on more data with more compute consistently improve on a smooth curve, with no sign of diminishing returns. Empirical evidence: GPT-3 (175B) to GPT-4 (~1.8T rumoured) — each generation meaningfully better. FLOP-matched larger models outperform smaller ones — architecture matters less than scale.",
    explanation:"Counter-evidence to pure scaling: emergent abilities appear discontinuously at certain scales (e.g., chain-of-thought reasoning emerges ~50B params). Data quality matters — Phi-3 achieves near-GPT-4 quality at 3.8B parameters using textbook-quality data. Architectural innovations (MoE, GQA, Flash Attention) can improve the efficiency of the scaling curve.",
    tags:["toptal"] },

  { id:"tf-028", group:"transformers", difficulty:"medium", type:"short",
    question:"What is an induction head and why is it considered a primitive circuit in transformers?",
    answer:"An induction head (Olsson et al., 2022) is a pair of attention heads that together implement in-context pattern copying: if a sequence contains [...A...B...A...], the induction circuit predicts B after the second A. Head 1 (previous token head): attends to the token just before the current query position. Head 2 (induction head): uses the output of head 1 to attend to the token that followed A the first time it appeared. Together they form an 'if you saw AB, predict B given A' circuit.",
    explanation:"Induction heads are believed to be responsible for much of in-context learning in transformers. They appear in all transformer models at phase 2 of training (a sudden transition). Mechanistic interpretability research at Anthropic identified these circuits and is working to discover more complex circuits responsible for higher-level capabilities.",
    tags:["toptal"] },

  { id:"tf-029", group:"transformers", difficulty:"medium", type:"short",
    question:"What is the role of the [CLS] token in BERT and how is it used for classification?",
    answer:"BERT adds a special [CLS] (classification) token at the start of every input sequence. After the transformer processes the sequence, the [CLS] token's final hidden state is used as the aggregate sequence representation — it has attended to all tokens and aggregated the sequence's meaning through bidirectional attention. For classification: the [CLS] representation is passed to a single linear layer that predicts the class. This is the standard BERT fine-tuning approach for sentence-level tasks.",
    explanation:"The [CLS] token's representation is not inherently a summary at initialisation — it only becomes meaningful for classification after fine-tuning (the model learns to use [CLS] to aggregate task-relevant information). For sentence embeddings without task-specific fine-tuning, averaging all token representations often outperforms [CLS] alone (SimCSE finding).",
    tags:["toptal","andela"] },

  { id:"tf-030", group:"transformers", difficulty:"hard", type:"short",
    question:"What is Ring Attention and how does it enable very long context training?",
    answer:"Ring Attention (Liu et al., 2023): enables training on sequences longer than fit on a single device's memory. Sequence is split across devices in a ring topology. Each device processes its sequence chunk, computes local attention, then passes K and V to the next device in the ring while computing with received K and V. All devices work in parallel — no sequential bottleneck. The ring rotation is overlapped with computation (communication-computation overlap). Enables O(N/devices) memory per device while maintaining exact O(N²) attention.",
    explanation:"Used to train Gemini 1.5 Pro's 1M+ token context. Combined with Flash Attention within each device chunk. Ring Attention scales to sequences that are completely impossible with standard attention — a 1M token sequence in standard attention requires 1TB memory per head; with Ring Attention across 1000 GPUs, each processes 1k tokens.",
    tags:["toptal"] },

  { id:"tf-031", group:"transformers", difficulty:"medium", type:"short",
    question:"What is the Feed-Forward Network (FFN) in a transformer block computing, intuitively?",
    answer:"The FFN (W₂ × GELU(W₁ × x)) can be interpreted as: W₁ projects x to a high-dimensional space (d_ff = 4d_model), activating a set of 'feature detectors'. GELU selects which features are active. W₂ projects back to d_model, summing contributions of active features. Interpretability research (Geva et al., 2021, 'Transformer Feed-Forward Layers Are Key-Value Memories'): FFN rows of W₁ act as 'keys' matching patterns in the input; W₂ rows act as 'values' that are read out when the pattern is matched. The FFN can store ~2×d_ff facts in this key-value structure.",
    explanation:"This key-value memory interpretation explains: why larger FFN sizes improve factual knowledge, why factual errors can be corrected by editing FFN weights (ROME, MEMIT), and why FFN neurons can be monosemantic (active for specific factual patterns) or polysemantic (active for many different patterns).",
    tags:["toptal"] },

  { id:"tf-032", group:"transformers", difficulty:"hard", type:"short",
    question:"What is the superposition hypothesis in transformers and what is a sparse autoencoder's role in studying it?",
    answer:"Superposition hypothesis (Elhage et al., 2022, Anthropic): neural networks represent more features than they have neurons by using superposition — packing features into linear combinations of neurons (interference). The residual stream's d_model dimensions can represent d_model true orthogonal features, but in superposition many more features are represented as near-orthogonal directions, with occasional interference. Sparse autoencoders (SAEs): trained to decompose residual stream activations into sparse linear combinations of learnable feature directions — attempting to recover the monosemantic features from polysemantic neuron activations.",
    explanation:"SAEs have found 100k+ interpretable features in Claude's residual stream, corresponding to concepts like 'the Golden Gate Bridge', 'mathematical reasoning', 'deception', etc. This is the basis of Anthropic's mechanistic interpretability program. SAEs are a key tool for understanding why LLMs behave the way they do.",
    tags:["toptal"] },

  { id:"tf-033", group:"transformers", difficulty:"medium", type:"short",
    question:"What is prefix language modelling and how does it differ from standard CLM?",
    answer:"Standard CLM (GPT): every token can only attend to previous tokens — the model trains on P(x_t | x_1,...,x_{t-1}). Prefix LM (T5-style): a prefix (e.g., the input document) is processed with bidirectional attention; the continuation (e.g., the summary) is generated with causal attention attending back to the prefix and previously generated tokens. Advantages: prefix has full bidirectional context (better representations), generation proceeds causally. Used in: T5, Chinchilla, UL2.",
    explanation:"Distinction from encoder-decoder: in prefix LM, both prefix and generation are in the same sequence with different masking — no separate encoder. This is simpler architecturally and can be implemented as a standard transformer with a custom attention mask (prefix positions are fully visible; continuation positions see only prefix + previous continuation tokens).",
    tags:["toptal"] },

  { id:"tf-034", group:"transformers", difficulty:"medium", type:"short",
    question:"What is Layer Norm and RMSNorm and why does RMSNorm drop mean subtraction?",
    answer:"LayerNorm: normalise each token's d_model-dimensional vector to mean=0, std=1, then apply learned scale γ and shift β. RMSNorm (Zhang & Sennrich, 2019): skip mean subtraction — normalise by root mean square only: x̂ = x/RMS(x) where RMS(x)=√(Σxᵢ²/d). Apply scale γ only (no shift β needed since mean isn't zeroed). Why: mean subtraction adds computational cost; experiments show dropping it has negligible quality impact. RMSNorm is slightly faster and simpler.",
    explanation:"RMSNorm is used in: LLaMA (all versions), Mistral, Falcon, Gemma — essentially all major open-source LLMs since 2023. The original transformer and GPT-3 use LayerNorm. The quality difference is negligible at scale, so the computational saving of RMSNorm is worthwhile.",
    tags:["toptal","andela"] },

  { id:"tf-035", group:"transformers", difficulty:"medium", type:"short",
    question:"What is the tokenisation process in transformer LLMs and what is BPE?",
    answer:"Tokenisation: convert raw text to integer token IDs. BPE (Byte Pair Encoding): start with individual bytes as vocabulary; repeatedly merge the most frequent adjacent pair; stop when vocab_size is reached (e.g., 32k, 50k, 128k). GPT-4 uses cl100k_base (100k vocab, tiktoken). LLaMA-3 uses 128k vocab SentencePiece BPE. Larger vocab → fewer tokens per word → shorter sequences (less compute) but larger embedding and lm_head matrices. Byte-level BPE (GPT-2+): every byte in the initial vocabulary, enabling encoding any Unicode text without 'unknown' tokens.",
    explanation:"Tokenisation affects model quality significantly: tokens that split words in unexpected places are harder to reason about (e.g., 'unhappy' as ['un','happy'] is interpretable; 'AAABBBCCC' as ['AAA','BB','BCC','C'] is not). LLaMA-3's 128k vocab tokenises code and multilingual text more efficiently than LLaMA-2's 32k vocab — fewer tokens per sentence in non-English languages.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"tf-036", group:"transformers", difficulty:"medium", type:"short",
    question:"What is position-wise versus token-mixing computation in transformers?",
    answer:"Token-mixing: operations that combine information across different token positions in the sequence — self-attention is the primary token-mixing operation (each token's output depends on all other tokens). Position-wise: operations applied independently to each token position — FFN layers are position-wise (same weight matrices applied to each position independently, no interaction between positions). The residual stream alternates: attention (mix tokens) → FFN (transform each token independently) → repeat.",
    explanation:"This decomposition is useful for understanding what each component does: attention performs global information routing (which facts from which positions are relevant here?); FFN performs local processing (given this information, what transformation is needed?). MLPs in the residual stream also help write factual information back into the stream.",
    tags:["andela"] },

  { id:"tf-037", group:"transformers", difficulty:"hard", type:"short",
    question:"What is continuous batching (iteration-level scheduling) in LLM inference?",
    answer:"Standard batching: a batch of N requests runs together from start to finish. If some requests finish early, the GPU idles waiting for the remaining long ones — poor utilisation. Continuous batching: at each decoding step, check for finished sequences; immediately replace them with new requests from the queue. The batch size stays constant (e.g., 256 sequences) but its composition changes each iteration. Result: GPU stays near 100% utilised, latency is reduced for short requests, throughput increases significantly.",
    explanation:"Continuous batching (Orca, Yu et al., 2022) is now the standard in all production LLM serving systems: vLLM, TensorRT-LLM, TGI, SGLang. Combined with PagedAttention (vLLM's virtual KV cache management), it enables serving 10-50× more concurrent requests vs. static batching with the same GPU.",
    tags:["toptal"] },

  { id:"tf-038", group:"transformers", difficulty:"medium", type:"short",
    question:"What is PagedAttention and what problem does it solve in LLM serving?",
    answer:"In LLM serving, different requests have different completion lengths — pre-allocating a KV cache of max_length for each request wastes memory (the request might complete at 10% of max). PagedAttention (Kwon et al., 2023, vLLM): manages KV cache like virtual memory — divide cache into fixed-size pages (blocks of tokens). Allocate pages on demand as sequence grows. Multiple requests can share pages (e.g., for shared system prompts — prefix sharing). Eliminates KV cache fragmentation, reducing waste from ~60% to <4%.",
    explanation:"Before PagedAttention: large KV cache pre-allocation = only 10-20 concurrent sequences. After: 5-10× more sequences in the same memory. This is why vLLM became the dominant open-source serving framework — the throughput improvement from PagedAttention is transformative for production deployments.",
    tags:["toptal","frequently-tested"] },

  { id:"tf-039", group:"transformers", difficulty:"easy", type:"mcq",
    options:["Encoder-only (e.g., BERT)","Decoder-only (e.g., GPT)","Encoder-decoder (e.g., T5)","Mixture-of-Experts"],
    question:"Which transformer architecture is best suited for autoregressive text generation?",
    answer:"Decoder-only (e.g., GPT)",
    explanation:"Decoder-only models use causal attention — each token only sees previous tokens, enabling autoregressive generation (generate one token at a time, append it, generate the next). Encoder-only models see all tokens bidirectionally — cannot generate. Encoder-decoder models can generate but are more complex. All major text generation LLMs (GPT-4, LLaMA, Claude, Gemini) use decoder-only architectures.",
    tags:["turing","andela"] },

  { id:"tf-040", group:"transformers", difficulty:"hard", type:"short",
    question:"What is the difference between token-level and sequence-level generation strategies?",
    answer:"Token-level strategies (per-step sampling): Greedy (argmax), temperature sampling (T<1 sharper, T>1 more random), top-k (sample from k highest-probability tokens), top-p/nucleus (sample from smallest set whose cumulative probability ≥ p, e.g., p=0.9). Sequence-level strategies: Beam search (maintain top-B partial sequences at each step, return highest-scoring complete sequence — deterministic, higher quality for translation). Self-consistency (Wang et al., 2022): sample M sequences with temperature, take majority vote on the final answer — improves reasoning accuracy significantly.",
    explanation:"In 2026: for LLM chat, temperature=0.7 + top-p=0.9 is standard for balanced creativity. For code generation: temperature=0.2-0.4 (more deterministic). For reasoning: temperature=0 (greedy) or self-consistency. Beam search is rarely used for LLMs (prone to generating repetitive text), but common in translation models.",
    tags:["toptal","andela"] },

  { id:"tf-041", group:"transformers", difficulty:"medium", type:"short",
    question:"What is GELU activation and why do transformers prefer it over ReLU?",
    answer:"GELU (Gaussian Error Linear Unit): GELU(x) = x × Φ(x) where Φ is the Gaussian CDF. Approximately: 0.5x(1+tanh(√(2/π)(x+0.044715x³))). Properties: smooth (differentiable everywhere, including at 0), stochastic gating interpretation (weight input by probability of it being drawn from a standard Gaussian). Unlike ReLU: no dying neuron problem (GELU never exactly 0 for any finite x), smoother gradients throughout. Used in BERT, GPT-2, GPT-3, all modern LLMs.",
    explanation:"SwiGLU (Shazeer, 2020): SwiGLU(x, gate) = Swish(gate) × x, where Swish(x)=x×σ(x). Used in Llama, PaLM, Mistral, Gemma. Gated: the gate vector controls what information flows through, like a soft attention within the FFN. Empirically outperforms GELU in LLM settings. The FFN with SwiGLU uses 3 weight matrices (W_gate, W_up, W_down) instead of 2.",
    tags:["toptal"] },

  { id:"tf-042", group:"transformers", difficulty:"medium", type:"short",
    question:"What is the difference between the original transformer attention mechanism and self-attention?",
    answer:"Original transformer (Vaswani et al., 2017): three types of attention. Encoder self-attention: Q, K, V all from the encoder input (bidirectional). Decoder self-attention: Q, K, V all from the decoder input, but causal mask (decoder can't see future tokens). Encoder-decoder cross-attention: Q from decoder, K and V from encoder output. Self-attention (generic): Q, K, V all come from the same sequence — a special case where input and context are the same sequence. 'Self' means attending to the sequence itself.",
    explanation:"The unifying abstraction: any attention computation can be described as A(Q,K,V) = softmax(QKᵀ/√d_k)V. What makes each type different is where Q, K, V come from. Self-attention: Q=K=V source. Cross-attention: Q source ≠ K=V source. The mathematics is identical; only the inputs differ.",
    tags:["andela","core"] },

  { id:"tf-043", group:"transformers", difficulty:"medium", type:"short",
    question:"What is the difference between sparse and dense attention patterns?",
    answer:"Dense (full) attention: every token attends to every other token — O(N²) operations, full receptive field from the first layer. Sparse attention patterns restrict each token to a subset of positions: Local/sliding window (Longformer): each token attends to W nearest neighbours — O(N×W) complexity. Strided (Longformer, BigBird): additional periodic global tokens every stride s. Random: each token attends to r random other tokens. Global+local (Longformer): a few special tokens (like [CLS]) attend globally; all others attend locally.",
    explanation:"Sparse attention reduces complexity from O(N²) to O(N×W) but may miss long-range dependencies that fall outside the window. Longformer combines: local window attention + global attention for specific tokens + task attention for task-specific positions. BigBird theoretically shows sparse attention is Turing complete (can simulate any computation dense attention can).",
    tags:["toptal"] },

  { id:"tf-044", group:"transformers", difficulty:"medium", type:"short",
    question:"What is prefix caching (prompt caching) in LLM serving and how does it help?",
    answer:"Prefix caching: if multiple requests share a common prefix (e.g., the same system prompt), compute and cache the KV cache for that prefix once. Subsequent requests reuse the cached KV values without recomputing. Benefits: reduces time-to-first-token (TTFT) for requests with shared prefixes, reduces compute cost significantly when the system prompt is long. In vLLM with PagedAttention: pages containing the shared prefix are referenced by multiple requests — zero memory duplication.",
    explanation:"Anthropic charges less (50% discount) for prompt cache hits vs. full computation. OpenAI also offers prompt caching. For applications with long system prompts (tool definitions, documents, few-shot examples), prefix caching can reduce LLM API costs by 50-90%.",
    tags:["toptal","andela"] },

  { id:"tf-045", group:"transformers", difficulty:"medium", type:"short",
    question:"What is the transformer's parameter count breakdown by layer?",
    answer:"Per transformer layer: Attention: (d_model×d_k×h + d_model×d_v×h + d_model×d_model) for Q, K, V, O projections ≈ 4×d_model² (with d_k=d_v=d_model/h). FFN with SwiGLU: 3 weight matrices × d_model × d_ff ≈ 3×d_model×(8/3×d_model) = 8×d_model². LayerNorms: 2×2×d_model (negligible). Total per layer ≈ 12×d_model². For L layers + embedding: Total ≈ 12×L×d_model² + vocab_size×d_model.",
    explanation:"Llama-3-8B verification: d_model=4096, L=32. 12×32×4096² = 6.44B. Embedding: 128k×4096 = 0.52B. Total ≈ 7B (matches 7.24B actual). This formula (12Ld²) is the standard approximation used to estimate LLM parameter counts and FLOPs.",
    tags:["toptal"] },

  { id:"tf-046", group:"transformers", difficulty:"medium", type:"short",
    question:"What is chunked prefill in LLM inference and why does it improve latency?",
    answer:"Prefill phase: process the entire prompt in parallel (batched matrix multiply). Decode phase: generate tokens one by one (sequential, memory-bandwidth bound). Problem: a long prompt (e.g., 32k tokens) in a batch with short-prompt requests occupies the GPU for a long time in prefill, delaying all other requests in the queue. Chunked prefill: split long prompts into smaller chunks (e.g., 512 tokens each), interleave prefill chunks with decode steps for other requests. Short requests aren't blocked by long prefill operations.",
    explanation:"Chunked prefill (Sarathi-Serve, 2023): achieves more predictable tail latency for concurrent requests. Also enables better GPU utilisation by mixing compute-intensive prefill chunks with memory-bandwidth-intensive decode steps. Now integrated into vLLM and TensorRT-LLM serving systems.",
    tags:["toptal"] },

  { id:"tf-047", group:"transformers", difficulty:"medium", type:"short",
    question:"What is greedy decoding vs sampling and when do you use each?",
    answer:"Greedy: always pick the token with the highest probability (argmax over logits). Deterministic, fast, but can produce repetitive text and get stuck in local optima. Sampling: draw from the probability distribution — diverse, creative, but may produce low-probability tokens. Practical middle ground: Top-k sampling (sample from top k tokens only), Nucleus/top-p sampling (sample from the minimum set of tokens covering probability p), Temperature (scale logits before softmax — T<1 sharpens, T>1 flattens).",
    explanation:"When to use: Greedy for factual Q&A, translation (determinism valued). Sampling for creative writing, dialogue, code generation (diversity valued). Temperature=0 (greedy) for benchmarks and evals (reproducibility). Self-consistency sampling multiple times at temperature>0 and taking majority vote improves reasoning tasks over greedy.",
    tags:["toptal","andela","core"] },

  { id:"tf-048", group:"transformers", difficulty:"easy", type:"short",
    question:"What is the difference between top-k and top-p (nucleus) sampling?",
    answer:"Top-k: at each step, keep only the k most probable tokens, renormalise and sample. Fixed k regardless of distribution shape — if k=50 and the distribution is very flat, you still sample from 50 tokens; if very peaked, most of those 50 tokens have tiny probability. Top-p (nucleus): keep the minimum number of tokens whose cumulative probability ≥ p (e.g., p=0.9). Adapts to distribution shape — peaked distribution → few tokens selected; flat distribution → many tokens. Top-p is generally preferred as it adapts to confidence.",
    explanation:"In practice: combine both (top-k=50, top-p=0.9): first apply top-k to limit to at most 50 candidates, then apply top-p to further restrict to the nucleus. This prevents both too many (flat distribution) and too few (overly peaked) candidates. Default in most LLM frameworks.",
    tags:["turing","andela","core"] },

  { id:"tf-049", group:"transformers", difficulty:"medium", type:"short",
    question:"What is the tokenisation effect on model reasoning, especially for numbers and code?",
    answer:"Numbers are often split in non-intuitive ways: '1234567' might be ['123','45','67'] — the model must reason about multi-digit arithmetic across token boundaries. Addition of large numbers is harder than small numbers because more token splits occur. Code: whitespace in Python is semantically meaningful but may be collapsed by the tokeniser. Non-English languages: typically tokenise into more tokens per word (more tokens = longer sequence = more compute). Implication: models are not purely character-level — token boundaries affect difficulty.",
    explanation:"Models can reverse strings of characters poorly because the characters are grouped into multi-character tokens — 'the' as a single token can't easily be reversed to 'eht'. Tokenisation affects model capabilities in ways that don't correlate with semantic difficulty: tasks that are 'easy' semantically but 'hard' tokenisation-wise (e.g., counting letters in a word) trip up models.",
    tags:["toptal","andela"] },

  { id:"tf-050", group:"transformers", difficulty:"hard", type:"short",
    question:"What is the key difference between a transformer block in an LLM and in a vision transformer (ViT)?",
    answer:"Core transformer block is identical: self-attention + FFN + LayerNorm + residuals. Differences: (1) Input: LLMs take 1D token sequences; ViT takes 2D image patches linearised to 1D. (2) Position encoding: LLMs use RoPE/learned PE; ViTs use learned 2D position embeddings or sinusoidal 2D. (3) Attention masking: LLMs use causal mask; ViTs use full bidirectional attention (no causal mask needed for image classification). (4) Output: LLMs output next-token logits; ViTs output a [CLS] token representation for classification.",
    explanation:"Modern multimodal models (GPT-4V, LLaMA-3.2-vision, Qwen-VL): use a ViT encoder to produce image patch embeddings, then project them to d_model and prepend to the token sequence fed to the LLM decoder. The LLM's causal attention treats image patch embeddings like text tokens — no architectural change to the LLM itself.",
    tags:["toptal","andela"] },
];
