import type { IQ } from "./interview-data";

export const BANK_E: IQ[] = [

  // ── RAG (50) ─────────────────────────────────────────────────────────────

  { id:"rag-001", group:"rag", difficulty:"easy", type:"short",
    question:"What is RAG (Retrieval-Augmented Generation) and why is it used?",
    answer:"RAG combines a retrieval system with an LLM: given a query, retrieve relevant documents from a knowledge base, then pass both the query and retrieved context to the LLM to generate a grounded answer. Why: (1) LLMs have a knowledge cutoff — RAG provides up-to-date information. (2) LLMs hallucinate — retrieved context grounds answers in real documents. (3) LLMs can't store all domain knowledge in weights — RAG externalises knowledge to a retrievable store. (4) Avoids fine-tuning cost — add new knowledge via document store, not retraining.",
    explanation:"RAG flow: query → embed query → vector search → retrieve top-k chunks → LLM generates answer conditioned on chunks. The LLM is prompted to answer only from the provided context ('based on the documents below, answer...') — this faithfulness instruction significantly reduces hallucination for in-context facts.",
    tags:["turing","andela","core","frequently-tested"] },

  { id:"rag-002", group:"rag", difficulty:"medium", type:"short",
    question:"What is a vector database and how does it differ from a traditional database?",
    answer:"Vector database: stores dense vector embeddings of documents and provides efficient approximate nearest neighbour (ANN) search — given a query vector, return the k most similar stored vectors. Traditional database: stores structured data, queries via exact SQL (equality, range). Vector databases support: similarity search (cosine, dot product, L2 distance), metadata filtering, hybrid search (vector + keyword). Examples: FAISS (library, not a DB), Pinecone, Weaviate, Qdrant, Chroma, pgvector (Postgres extension).",
    explanation:"Why not just Postgres? Vector similarity search on millions of embeddings requires ANN index structures (HNSW, IVF) that standard databases don't implement. Brute-force nearest neighbour is O(N×d) — too slow for N=10M+ documents. HNSW achieves O(log N) search at 95-99% recall. Vector databases implement these indices natively with persistence, metadata filtering, and CRUD operations.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"rag-003", group:"rag", difficulty:"medium", type:"short",
    question:"What is HNSW (Hierarchical Navigable Small World) and why is it the dominant ANN index?",
    answer:"HNSW is a graph-based ANN index. Build: insert each vector as a node, connect to M nearest neighbours at multiple hierarchy levels (fewer nodes at higher levels = coarser search, all nodes at level 0 = fine search). Search: start at the top level, greedily descend to nearest neighbours, move down levels, search exhaustively at level 0 around the entry point. Properties: O(log N) search, tunable recall vs. speed (M, ef_construction parameters), supports dynamic insertion and deletion, no reindexing needed.",
    explanation:"Alternatives: IVF (Inverted File Index) — cluster vectors into C buckets via k-means, search only nprobe nearest clusters — faster to build, slightly lower recall. IVF+PQ: compress vectors with Product Quantisation for 64× memory reduction (approximate). HNSW is preferred for: high recall requirements, real-time insertion, moderate dataset size. IVF+PQ for: huge datasets (100M+), memory-constrained.",
    tags:["toptal","frequently-tested"] },

  { id:"rag-004", group:"rag", difficulty:"medium", type:"short",
    question:"What is chunking in RAG and how do you choose chunk size?",
    answer:"Chunking: split documents into smaller pieces for retrieval. Too large: chunk contains irrelevant content alongside the relevant passage — retrieval is noisy. Too small: chunk lacks sufficient context for the LLM to answer — the answer may span multiple chunks. Chunk size choice depends on: (1) Embedding model's input limit (typically 512 tokens). (2) How focused queries are (specific vs. broad). (3) Document structure (use section breaks, paragraphs as natural boundaries). Typical chunk sizes: 128-512 tokens for dense retrieval, 256-1024 for broader context.",
    explanation:"Overlap: slide the chunking window by 50% overlap between consecutive chunks — prevents important sentences at chunk boundaries from being missed. Hierarchical chunking: small chunks for retrieval + larger parent chunks for context (retrieve the small chunk, but send the parent chunk to the LLM for richer context). Used in LlamaIndex's node parser.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"rag-005", group:"rag", difficulty:"medium", type:"short",
    question:"What is the difference between dense retrieval and sparse retrieval (BM25)?",
    answer:"Dense retrieval: embed query and documents to dense vectors, find nearest neighbours via cosine similarity. Captures semantic similarity — 'car' matches 'automobile' even with no word overlap. BM25 (sparse): term-frequency × inverse-document-frequency scoring, exact term matching. 'car' only matches documents containing 'car'. Fast, no GPU needed, interpretable. Hybrid retrieval: combine both scores (reciprocal rank fusion, or linear combination). Dense finds semantic matches; sparse handles keyword-specific queries (proper nouns, codes, IDs). Hybrid typically outperforms either alone.",
    explanation:"RRF (Reciprocal Rank Fusion): score_hybrid = Σ 1/(k + rank_dense) + 1/(k + rank_sparse), k=60. Simple, no learned weights, robust. BM25 is still the baseline in IR — dense retrieval only outperforms it clearly in out-of-domain settings or queries without exact keyword matches. Both together is almost always best.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"rag-006", group:"rag", difficulty:"medium", type:"short",
    question:"What is a reranker in RAG and when should you use one?",
    answer:"Retrieval: fast ANN search, returns top-k (e.g., k=100) candidates. Reranker: a cross-encoder model that jointly encodes (query, document) pairs and scores them — much more accurate than bi-encoder retrieval but too slow to run on all documents. Apply reranker to the top-k candidates, re-rank, take top-n (e.g., n=5) for the LLM. Cross-encoder: query and document are concatenated and passed through BERT-style model — all attention layers can compute cross-attention between query and document tokens. Bi-encoder: separate encodings, only similarity at the end — fast but misses inter-token interactions.",
    explanation:"Cohere Rerank, BGE-Reranker, ms-marco cross-encoders are common choices. Latency: reranking 100 candidates adds ~100-200ms but improves precision@5 by 20-40%. Worth the cost when retrieval precision is the bottleneck. Use when: the retrieval step misses relevant documents or returns too many irrelevant ones.",
    tags:["toptal","andela"] },

  { id:"rag-007", group:"rag", difficulty:"medium", type:"short",
    question:"What is query rewriting in RAG and why does it help?",
    answer:"User queries are often: short, ambiguous, conversational ('what about the second approach?'), or don't match the language of documents. Query rewriting: use the LLM to rewrite the query before retrieval. Techniques: (1) HyDE (Hypothetical Document Embedding): LLM generates a hypothetical answer, embed the answer and use that for retrieval — leverages that answers are more similar to documents than questions are. (2) Query expansion: add synonyms, related terms. (3) Step-back prompting: abstract specific query to a general question. (4) Multi-query: generate several variations, retrieve for each, union results.",
    explanation:"HyDE (Gao et al., 2022): 'What is the capital of France?' → LLM generates 'Paris is the capital of France, with...' → embed this hypothetical document → retrieve documents similar to it. Works because the vocabulary and phrasing of a generated answer matches the documents better than the question does. Significant improvement on complex domain-specific queries.",
    tags:["toptal","frequently-tested"] },

  { id:"rag-008", group:"rag", difficulty:"medium", type:"short",
    question:"What is an embedding model and which ones are commonly used for RAG?",
    answer:"An embedding model maps text to a dense vector (e.g., 1536-dim). Trained via contrastive learning on (query, relevant passage) pairs: similar text → close vectors; dissimilar → far apart. Common models: OpenAI text-embedding-3-small/large (API, fast, high quality), E5-large-instruct (open-source, instruction-tuned), BGE-M3 (multilingual, multi-granularity), Cohere Embed v3 (strong retrieval performance), GTE-large. MTEB benchmark: standard retrieval evaluation across 56 datasets.",
    explanation:"Choosing an embedding model: OpenAI embeddings for quick start (API, no GPU needed). Open-source (E5, BGE) for self-hosted, privacy-sensitive, or high-volume applications (no per-token cost). Multilingual BGE-M3 for non-English or mixed-language documents. Dimension: higher = more expressive but slower search. 1536 (OpenAI) vs 768 (BERT-size) vs 4096 (large models).",
    tags:["toptal","andela","frequently-tested"] },

  { id:"rag-009", group:"rag", difficulty:"hard", type:"short",
    question:"What is the 'context window stuffing' vs. RAG trade-off for long documents?",
    answer:"Context stuffing: put the entire document in the LLM's context window. Pros: no retrieval errors, full document available, LLM can reason globally over it. Cons: expensive (tokens cost money), slow (prefill time), 'lost in the middle' problem (LLM ignores middle of context), context window limits (can't stuff 1M-word book). RAG: retrieve only relevant chunks. Pros: cheap (only relevant tokens), fast, no context limit. Cons: retrieval errors, can't answer questions that require global document understanding, can't aggregate across many sections.",
    explanation:"Best practice: use RAG for large knowledge bases and retrieval-oriented queries; use context stuffing (or long-context models) for short documents or when global reasoning is needed. MapReduce pattern for large document analysis: divide into chunks, process each with LLM (map), aggregate LLM responses (reduce). Hybrid: RAG for retrieval + selective context stuffing of the most relevant retrieved chunks.",
    tags:["toptal","andela"] },

  { id:"rag-010", group:"rag", difficulty:"medium", type:"short",
    question:"What is RAG faithfulness and RAG relevance and how are they evaluated?",
    answer:"RAG faithfulness (groundedness): does the LLM's answer only use information from the retrieved context? A faithful answer makes no claims not supported by retrieved documents. RAG relevance: (1) Context relevance: are retrieved chunks relevant to the query? (2) Answer relevance: does the answer address the query? Evaluation frameworks: RAGAS — automated metrics: faithfulness (NLI-based, does claim appear in context?), answer relevance (cosine similarity of Q to generated question from A), context precision and recall. TruLens: LLM-based scoring of each component.",
    explanation:"RAGAS automated metrics use an LLM to score components. This makes evaluation scalable (no human labels needed) but inherits LLM biases. Human evaluation is the gold standard for faithfulness — have annotators verify each claim in the answer against the context. For production: monitor faithfulness by randomly sampling responses for human review, use automated metrics for trend detection.",
    tags:["toptal","andela"] },

  { id:"rag-011", group:"rag", difficulty:"hard", type:"short",
    question:"What is RAPTOR (Recursive Abstractive Processing for Tree-Organized Retrieval)?",
    answer:"RAPTOR (Sarthi et al., 2024): standard RAG retrieves individual chunks — misses global document themes that span many chunks. RAPTOR builds a tree: (1) Embed all chunks. (2) Cluster similar chunks (Gaussian mixture model). (3) Summarise each cluster with an LLM → creates 'summary nodes'. (4) Recursively cluster and summarise summaries. (5) Index all nodes (original chunks + all summaries) in the vector database. Retrieval: search across all levels — specific queries match original chunks; broad queries match high-level summaries.",
    explanation:"RAPTOR enables: answering high-level 'what is the main theme of this book?' questions (which require global understanding) as well as specific factual queries. The tree structure preserves both detail and abstraction. Tradeoff: expensive to build (requires many LLM summarisation calls), larger index. Best for: long-form documents (books, reports) where multi-granularity retrieval is needed.",
    tags:["toptal"] },

  { id:"rag-012", group:"rag", difficulty:"medium", type:"short",
    question:"What is the difference between naive RAG, advanced RAG, and modular RAG?",
    answer:"Naive RAG: fixed pipeline — chunk, embed, index, retrieve top-k, generate. No query refinement, no reranking, fixed chunks. Advanced RAG: adds pre-retrieval (query rewriting, HyDE), post-retrieval (reranking, compression, filtering) and better chunking strategies. Modular RAG: treats RAG as a configurable pipeline of modules — search module (dense, sparse, hybrid), summarisation module, verification module, etc. Each module can be swapped independently. Frameworks like LlamaIndex and LangChain implement modular RAG architectures.",
    explanation:"RAG evolution: Naive → better chunking → query rewriting → reranking → iterative retrieval (ask, retrieve, assess, ask again) → agentic RAG (LLM decides when and what to retrieve). Agentic RAG: LLM has tools for search, can issue multiple retrieval queries, reason over retrieved documents, and decide whether more retrieval is needed.",
    tags:["toptal","andela"] },

  { id:"rag-013", group:"rag", difficulty:"medium", type:"short",
    question:"What is iterative retrieval (multi-hop RAG) and when is it needed?",
    answer:"Single-hop RAG: one retrieval step per query — works for direct factual queries. Multi-hop/iterative: some queries require multiple retrieval steps. Example: 'What university did the author of [book] attend?' — requires: (1) Retrieve who wrote [book]. (2) Retrieve the author's university. Single retrieval cannot combine both facts. Solutions: Iterative RAG (retrieve, generate partial answer, retrieve again), ReAct (interleaved reasoning and retrieval), IRCoT (Interleaved Retrieval Chain-of-Thought).",
    explanation:"ReAct pattern for multi-hop: Thought → Action (search) → Observation (search result) → Thought → Action → ... → Final Answer. The LLM decides when to retrieve and what to search for, like a researcher iterating through references. This is the foundation of agentic RAG — the retrieval is driven by the model's reasoning, not a fixed pipeline.",
    tags:["toptal","andela"] },

  { id:"rag-014", group:"rag", difficulty:"medium", type:"short",
    question:"What is ColBERT and how does it differ from standard bi-encoder and cross-encoder retrieval?",
    answer:"Bi-encoder: embed query → one vector; embed document → one vector. Similarity: single dot product. Fast (precomputed doc vectors), less accurate. Cross-encoder: concatenate query+doc → transformer output → similarity score. Most accurate, O(N) per query (can't precompute). ColBERT: late interaction — embed query to set of token vectors Q={q₁,...,qn}; embed doc to set D={d₁,...,dm}. Score: Σᵢ max_j(qᵢ·dⱼ). Can precompute doc vectors, fast lookup via MaxSim. Quality between bi-encoder and cross-encoder.",
    explanation:"ColBERT stores one vector per token of each document — much higher storage than bi-encoder (one vector per doc) but allows fine-grained token-level matching. ColBERTv2 uses compressed representations (256-dim int8). In practice: ColBERT is niche (high storage cost), but useful for scientific/technical retrieval where precise term matching matters. Most production RAG uses bi-encoder + cross-encoder reranker.",
    tags:["toptal"] },

  { id:"rag-015", group:"rag", difficulty:"medium", type:"short",
    question:"What is sentence window retrieval and how does it improve over naive chunking?",
    answer:"Naive chunking: retrieve fixed-size chunks. Problem: the relevant sentence might be at the edge of a chunk — missing crucial surrounding context. Sentence window: embed and index individual sentences (fine granularity for retrieval). When a sentence is retrieved, expand the context by including N sentences before and after in the LLM's prompt. Result: precise retrieval of the exact relevant sentence + rich surrounding context for the LLM. Higher recall (fine-grained retrieval) + better context quality (surrounding sentences).",
    explanation:"LlamaIndex implementation: index each sentence separately, but store a reference to its source paragraph/page. Retrieval: get sentence match. Context: expand to a window of 3-5 sentences around the match. This is part of the 'small-to-big retrieval' pattern: retrieve small (sentence), use big (paragraph) for context.",
    tags:["toptal","andela"] },

  { id:"rag-016", group:"rag", difficulty:"medium", type:"short",
    question:"What is a knowledge graph RAG and when does it outperform vector RAG?",
    answer:"Knowledge graph (KG) RAG: documents are parsed into a graph of entities and relations (e.g., (Paris, capital_of, France)), stored as a graph DB (Neo4j). Retrieval: graph traversal or SPARQL query, not vector search. Advantages over vector RAG: (1) Multi-hop relations can be traversed exactly (no retrieval error). (2) Answers to relational queries are precise. (3) No hallucination for stated facts (exact graph lookup). When to use: structured domain with clear entities and relationships (medical knowledge bases, organisational charts, regulatory knowledge), multi-hop relational queries.",
    explanation:"Microsoft GraphRAG (2024): extract entities and relations from documents using an LLM, build a community structure via graph clustering, generate summaries of each community. Retrieval: for global queries (summary/theme), use community summaries; for local (specific entity), traverse entity subgraph. Outperforms naive RAG on global summarisation tasks. Expensive to build (many LLM calls for extraction).",
    tags:["toptal"] },

  { id:"rag-017", group:"rag", difficulty:"medium", type:"short",
    question:"What is semantic chunking and how does it improve over fixed-size chunking?",
    answer:"Fixed-size chunking: split every N tokens regardless of content — may split mid-sentence, mid-paragraph, mid-idea. Semantic chunking: split at natural semantic boundaries. Methods: (1) Sentence-based: split by sentence endings. (2) Paragraph-based: split at paragraph breaks. (3) Section-based: use document headers (Markdown H1/H2). (4) Embedding-based semantic chunking: compute embeddings of consecutive sentence groups, detect large cosine distance jumps (topic change) → split there. Produces more coherent chunks where each chunk covers one complete idea.",
    explanation:"Embedding-based semantic chunking (LlamaIndex SemanticSplitterNodeParser): embed 1-3 sentence windows, compute similarity to adjacent windows, split where similarity drops below a threshold. More expensive than fixed chunking (requires embedding every sentence), but produces significantly better retrieval results for well-structured documents.",
    tags:["toptal","andela"] },

  { id:"rag-018", group:"rag", difficulty:"medium", type:"short",
    question:"What is the 'needle in a haystack' test for RAG systems?",
    answer:"Needle in a haystack (NIAH): inject a specific piece of information ('the needle') into a large document at a specific position (e.g., depth 50% = halfway through). Ask the LLM to retrieve this fact. Measure recall at different document lengths and needle positions. Tests: (1) Whether the LLM can find and recall specific facts in long contexts. (2) Whether retrieval systems miss the needle at certain positions. (3) The 'lost in the middle' problem. Standard benchmarks: Paul Graham essays with injected facts, various document lengths (1k-100k tokens).",
    explanation:"NIAH results: even 128k-context models have weak spots — performance often drops at the middle of long contexts. RAG systems must be tested with the NIAH benchmark to ensure retrieval recall is high across all document positions and lengths. Failure modes: retrieval misses the needle (embedding similarity too low), or LLM ignores the retrieved needle in favour of a different answer from memory.",
    tags:["toptal"] },

  { id:"rag-019", group:"rag", difficulty:"hard", type:"short",
    question:"What is self-RAG and how does it improve faithfulness?",
    answer:"Self-RAG (Asai et al., 2023): trains the LLM to interleave generation with retrieval decisions and self-critique. Special tokens: [Retrieve] (decide whether to retrieve), [IsRel] (is this retrieved passage relevant?), [IsSup] (is this sentence supported by the retrieved passage?), [IsUse] (is this useful to answer the query?). Training: fine-tune the LLM on data annotated with these reflection tokens. Inference: the model can decide when to retrieve, which retrieved passages are relevant, and whether its own statements are grounded.",
    explanation:"Self-RAG advantages: adapts retrieval frequency to query complexity (factual queries retrieve every segment; creative queries may not retrieve at all); explicitly checks its own faithfulness. Limitations: requires fine-tuning (can't apply to any LLM via prompting), the reflection tokens add complexity to the pipeline. Achieves better faithfulness-quality tradeoff than naive RAG with fixed retrieval.",
    tags:["toptal"] },

  { id:"rag-020", group:"rag", difficulty:"medium", type:"short",
    question:"What is FAISS and what are the main index types it provides?",
    answer:"FAISS (Facebook AI Similarity Search): a C++/Python library for efficient dense vector similarity search. Main index types: IndexFlatL2/Cosine: exact brute-force search — perfect recall, O(N×d) search. IndexIVFFlat: inverted file index with k-means clusters — approximate, tunable nprobe. IndexIVFPQ: IVF + Product Quantisation for memory compression — 4-16× less memory, slightly lower recall. IndexHNSWFlat: HNSW graph search — fast, high recall, good for dynamic datasets. IndexScalarQuantizer: quantise vectors to INT8 — 4× less memory with minimal recall loss.",
    explanation:"FAISS is used as the backend in many RAG frameworks. GPU FAISS: runs on GPU for 100× faster search on large indices. Choosing: small datasets (<100k) → Flat (exact); medium (100k-10M) → HNSW or IVF; large (10M+) → IVF+PQ. Memory budget determines quantisation level. FAISS doesn't support metadata filtering or CRUD — use Qdrant, Weaviate, or Pinecone for production.",
    tags:["toptal","andela"] },

  { id:"rag-021", group:"rag", difficulty:"medium", type:"short",
    question:"What is LangChain and LlamaIndex and how do they help build RAG systems?",
    answer:"LangChain: general-purpose LLM application framework. Components: document loaders (PDF, web, DB), text splitters, embedding wrappers, vector stores, chains (RetrievalQA, ConversationalRetrievalChain), agents, memory. High abstraction, many connectors. LlamaIndex (formerly GPT Index): focused on data indexing and retrieval. Components: node parsers (chunking), document stores, vector indices, query engines, response synthesisers, retrieval post-processors. More composable, better for complex retrieval pipelines.",
    explanation:"When to use: LangChain for general agentic workflows, prompt chaining, multi-step tasks. LlamaIndex for complex RAG pipelines (hierarchical, multi-index, custom retrieval). Both support: OpenAI, Anthropic, local models, major vector databases. In 2026: many teams use LlamaIndex for the retrieval pipeline + LangChain for agentic orchestration.",
    tags:["toptal","andela","core"] },

  { id:"rag-022", group:"rag", difficulty:"medium", type:"short",
    question:"What is the difference between retrieval precision and retrieval recall in RAG?",
    answer:"Retrieval precision: of the chunks retrieved, what fraction are actually relevant? If k=5 and 3 are relevant: precision = 3/5 = 60%. Retrieval recall: of all relevant chunks in the corpus, what fraction were retrieved? If there are 8 relevant chunks total and 3 were retrieved: recall = 3/8 = 37.5%. Trade-off: increasing k improves recall (more likely to retrieve all relevant) but reduces precision (more irrelevant chunks). Reranking after high-k retrieval: retrieve k=100 (high recall), rerank to top 5 (high precision for LLM context).",
    explanation:"RAG failure modes: low recall → LLM doesn't have the information needed → 'I don't know' or hallucination. Low precision → LLM context polluted with irrelevant chunks → LLM confused or generates irrelevant answer. Measuring: RAGAS context precision and recall metrics. Practice: target recall > 90% for mission-critical applications (use large k), then maximise precision via reranking.",
    tags:["toptal","andela"] },

  { id:"rag-023", group:"rag", difficulty:"medium", type:"short",
    question:"What is document metadata filtering in RAG and when is it critical?",
    answer:"Metadata filtering: filter candidates by structured attributes before or during vector search. Example: 'date > 2024-01', 'source = annual_report', 'department = engineering'. Why critical: (1) Time-sensitive queries — avoid returning outdated documents. (2) Access control — only show documents the user is authorised to see. (3) Domain specificity — restrict search to relevant document types. Implementation: most vector databases support pre-filtering (filter before ANN search) or post-filtering (filter after ANN search — may need over-retrieval to compensate).",
    explanation:"Pre-filtering limitation: if the filtered subset is small, ANN search accuracy degrades (HNSW performs worse on small subsets). Post-filtering limitation: if many documents are filtered out, the returned count may be less than k. Segmented indices: maintain separate indices per metadata category — fast filtering, but index management overhead. Hybrid: filter coarsely pre-search, then apply fine filter post-search.",
    tags:["toptal","andela"] },

  { id:"rag-024", group:"rag", difficulty:"medium", type:"short",
    question:"What is context compression in RAG and why does it matter?",
    answer:"Retrieved chunks may contain mostly irrelevant text with a small relevant portion. Context compression: extract only the relevant parts before passing to the LLM. Methods: (1) LLMLingua/LLMLingua-2: perplexity-based token dropping — remove tokens the LLM finds predictable (low information) while preserving high-information tokens. Achieves 3-6× compression with minimal quality loss. (2) Recomp: train a compressor model to select relevant sentences. (3) Abstractive compression: summarise retrieved chunks into a shorter, focused summary. Benefits: fewer tokens → lower cost, lower latency, less distraction for LLM.",
    explanation:"Selective context (Shi et al., 2023): irrelevant context in the prompt can actually hurt LLM performance — the model is confused by distracting information. Counterintuitive finding: sometimes providing fewer, more relevant chunks is better than providing more chunks. Context compression directly addresses this by removing the distracting irrelevant portions.",
    tags:["toptal"] },

  { id:"rag-025", group:"rag", difficulty:"medium", type:"short",
    question:"What is product quantisation (PQ) in vector search and how does it reduce memory?",
    answer:"PQ (Product Quantisation): compress each d-dimensional vector by splitting it into m sub-vectors of d/m dimensions, quantising each sub-vector to one of k=256 codewords (8-bit). Storage: m bytes per vector instead of d×4 bytes for FP32 (d/m × 4× compression = 4× per sub-vector, and m sub-vectors). Example: d=128, m=8, k=256: 8 bytes instead of 512 bytes (64× compression). Distance approximation: compute approximate L2 distance using precomputed distance tables for each sub-vector's codeword — very fast (lookup table).",
    explanation:"PQ accuracy degrades with high compression: ADC (Asymmetric Distance Computation) is more accurate than symmetric (queries are not quantised, only documents). Optimised PQ (OPQ): rotate the vector space before quantisation to reduce error. PQ is essential for web-scale retrieval (billions of vectors) — the memory savings enable fitting the entire index in RAM.",
    tags:["toptal"] },

  { id:"rag-026", group:"rag", difficulty:"medium", type:"short",
    question:"What is conversational RAG and what challenges does it add?",
    answer:"Conversational RAG: multi-turn dialogue where each question builds on previous context. Challenges: (1) Pronouns and coreference: 'What about its capital?' — 'its' refers to a previously mentioned country, but the retrieval query 'its capital' won't match any document. (2) Follow-up questions: implicit context from previous turns. (3) Context accumulation: as conversation grows, the full history may exceed context limits. Solutions: (1) Query rewriting using conversation history before retrieval. (2) Conversation summary for long histories. (3) Store conversation in the RAG context alongside retrieved chunks.",
    explanation:"LangChain ConversationalRetrievalChain: uses a 'condense question' step — send the full conversation + current question to an LLM, which generates a standalone question with all context made explicit. This reformulated question is used for retrieval. Simple and effective for most conversational RAG use cases.",
    tags:["toptal","andela"] },

  { id:"rag-027", group:"rag", difficulty:"medium", type:"short",
    question:"What is the RAG pipeline evaluation framework RAGAS and what metrics does it compute?",
    answer:"RAGAS (Retrieval Augmented Generation Assessment): automated evaluation for RAG pipelines. Metrics: (1) Faithfulness: fraction of claims in the answer that are supported by the retrieved context (uses NLI or LLM to check each claim). (2) Answer relevance: does the answer address the question? (cosine similarity of answer to question inferred from answer). (3) Context precision: of retrieved chunks, what fraction are relevant to answering the question? (4) Context recall: fraction of ground-truth answer claims that are covered in retrieved context.",
    explanation:"RAGAS requires: the user question, the generated answer, the retrieved context chunks, and optionally a ground-truth answer. Uses an LLM (GPT-4 by default) to compute metrics. Correlation with human evaluation: ~0.7-0.8 for faithfulness, lower for others. Best used as a regression test — detect when RAG changes degrade metrics — not as absolute quality scores.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"rag-028", group:"rag", difficulty:"hard", type:"short",
    question:"What is the difference between retrieval and generation faithfulness, and how do you optimise each?",
    answer:"Retrieval faithfulness: do the retrieved documents contain the correct information? Optimise: improve embedding model quality, use hybrid retrieval, add reranker, tune chunk size, use document metadata filtering. Generation faithfulness: does the LLM only use information from the retrieved context (no hallucination)? Optimise: prompt engineering ('answer only from provided documents, say I don't know if unsupported'), use models known for low hallucination, fine-tune on citation-required data, add a faithfulness verification step post-generation.",
    explanation:"Decoupled evaluation is essential — if the overall system is wrong, diagnose which stage failed. A faithfulness checker: after generation, for each claim in the answer, use an NLI model or another LLM to verify: 'is this claim supported by any retrieved document?' If not, the claim is a hallucination. Automate this for production monitoring.",
    tags:["toptal","andela"] },

  { id:"rag-029", group:"rag", difficulty:"medium", type:"short",
    question:"What is parent-child chunking (parent document retrieval) and how does it address chunk size trade-offs?",
    answer:"Parent-child chunking: index small child chunks (e.g., 128 tokens) for retrieval precision, but when a child chunk matches, return its parent chunk (e.g., 512 tokens containing the child) to the LLM for richer context. Small chunks: high precision retrieval (the specific relevant sentence is retrieved). Large parent: enough surrounding context for the LLM to understand and answer. Avoids: chunking a small chunk that has perfect embedding match but insufficient context alone.",
    explanation:"LlamaIndex ParentDocumentRetriever: stores parent-child relationships in a document store. Retrieved child IDs → look up parent → send parent text to LLM. Alternative: hierarchical retrieval — retrieve paragraph, then load the full section. This pattern is one of the most effective practical improvements over naive fixed-size chunking.",
    tags:["toptal","andela"] },

  { id:"rag-030", group:"rag", difficulty:"medium", type:"short",
    question:"What is the role of BM25 in hybrid search and how is it combined with dense retrieval?",
    answer:"BM25: term frequency-inverse document frequency based scoring. Score(q,d) = Σᵢ IDF(qᵢ) × (f(qᵢ,d)×(k+1))/(f(qᵢ,d)+k×(1-b+b×|d|/avgdl)). Handles: rare terms (high IDF), exact keyword matches, proper nouns. Combined with dense: (1) Retrieve top-100 from BM25, top-100 from dense independently. (2) Fuse rankings with Reciprocal Rank Fusion. (3) Take top-50 from fused result. (4) Optionally rerank with cross-encoder. This ensemble consistently outperforms either method alone by 5-20% on retrieval benchmarks.",
    explanation:"Elasticsearch and OpenSearch provide BM25 natively. Weaviate and Qdrant support hybrid search (BM25 + vector) natively. For custom stacks: rank_bm25 (Python) for BM25 computation, FAISS for dense. The fusion weight (how much to weight BM25 vs dense) can be tuned — equal weighting (or RRF) is a good default.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"rag-031", group:"rag", difficulty:"medium", type:"short",
    question:"What is the cold start problem in RAG embedding models?",
    answer:"General-purpose embedding models (OpenAI, E5) are trained on diverse text. Domain-specific documents (medical, legal, financial, code) may use jargon or concepts underrepresented in training. Cold start: new domain vocabularies are not well-represented in embedding space — similar domain-specific documents may not have high cosine similarity, degrading retrieval. Solutions: (1) Domain-specific fine-tuning of the embedding model on in-domain (query, passage) pairs. (2) Add domain text to BM25 (works on exact terms regardless of embedding). (3) Use a larger general model (better generalisation). (4) Generate synthetic queries for fine-tuning via an LLM.",
    explanation:"Fine-tuning embedding models: use in-domain (query, positive passage, negative passage) triplets. Positive: a passage that answers the query. Hard negatives: a passage that is similar but doesn't answer. Training: InfoNCE loss. Even 1000 in-domain triplets can significantly improve retrieval recall in specialised domains.",
    tags:["toptal"] },

  { id:"rag-032", group:"rag", difficulty:"medium", type:"short",
    question:"What is table and structured data retrieval in RAG?",
    answer:"Standard text chunking and embedding works poorly for tables: a cell's meaning depends on its row header + column header, which may be in different chunks. Approaches: (1) Table-specific parsing: extract table structure, convert to natural text ('The revenue for Q1 2023 was $5.2B'). (2) Table serialisation to markdown/CSV: preserve structure in the chunk. (3) NL2SQL: LLM generates SQL from natural language question → execute against a database → return structured result. (4) Table QA models: TAPAS, TableFormer specifically trained for tabular comprehension.",
    explanation:"In practice for financial reports, annual reports: use PDF parsers with table detection (Unstructured.io, Docling, Nougat), extract tables to structured format, create one 'document' per row or per cell (with row/column context). NL2SQL is best when the database schema is stable and well-defined.",
    tags:["toptal","andela"] },

  { id:"rag-033", group:"rag", difficulty:"easy", type:"mcq",
    options:["To generate better responses without retrieving documents",
             "To retrieve relevant documents and use them as context for LLM generation",
             "To fine-tune the LLM on domain-specific data",
             "To reduce LLM hallucination by filtering training data"],
    question:"What is the primary purpose of RAG in LLM applications?",
    answer:"To retrieve relevant documents and use them as context for LLM generation",
    explanation:"RAG grounds LLM responses in retrieved documents, reducing hallucination and providing up-to-date information. The LLM uses its reasoning capabilities but anchors its answers to retrieved facts rather than generating from memory alone.",
    tags:["turing","andela"] },

  { id:"rag-034", group:"rag", difficulty:"medium", type:"short",
    question:"What is the challenge of multi-document RAG and how is it handled?",
    answer:"Multi-document RAG: the answer requires synthesising information from multiple retrieved documents (not just one passage). Challenge: (1) The LLM must identify relevant passages across documents and reconcile potentially contradictory information. (2) Different documents may use different terminology for the same concepts. (3) The order of documents in the context affects which information the LLM attends to most. Solutions: (1) Iterative retrieval and summarisation. (2) Map-reduce: summarise each document, then combine summaries. (3) Explicitly prompt the LLM to synthesise across sources with citations.",
    explanation:"Contradiction handling: prompt the LLM to note when retrieved documents conflict ('Document 1 states X, Document 2 states Y — these contradict'). For time-sensitive queries, include document dates and instruct the LLM to prefer more recent sources. Citation requirements force the LLM to attribute each claim to a specific source, making verification easier.",
    tags:["toptal","andela"] },

  { id:"rag-035", group:"rag", difficulty:"hard", type:"short",
    question:"What is FLARE (Forward-Looking Active Retrieval Augmented Generation)?",
    answer:"FLARE (Jiang et al., 2023): instead of one upfront retrieval, the LLM retrieves during generation when it's uncertain. Process: (1) LLM generates provisional text. (2) If any token has low probability (model is uncertain), pause generation. (3) Use the provisional low-confidence text as a search query. (4) Retrieve documents, continue generation conditioned on retrieved context. (5) Repeat until the full response is generated. Result: retrieval is targeted at exactly the uncertain parts, rather than a blanket retrieval for the whole query.",
    explanation:"FLARE requires access to token-level probabilities — not available in all APIs. Works best for knowledge-intensive generation where the LLM is genuinely uncertain about specific facts. Improves faithfulness for long-form knowledge-intensive text generation (biographies, technical reports) compared to one-shot retrieval.",
    tags:["toptal"] },

  { id:"rag-036", group:"rag", difficulty:"medium", type:"short",
    question:"What is chunk overlap and how does it affect retrieval quality?",
    answer:"Chunk overlap: when chunking a document with fixed size N, slide the window by (N-overlap) tokens instead of N. This ensures sentences near chunk boundaries appear in two consecutive chunks. Without overlap: a sentence at the end of chunk A and the start of chunk B are split — neither chunk alone contains the complete sentence and its context. With overlap (e.g., 20%): both chunks contain the boundary sentence, improving the chance that retrieval finds a coherent unit.",
    explanation:"Optimal overlap depends on chunk size: larger chunks → less overlap needed (more context per chunk). Typical: 10-20% overlap for 512-token chunks. Cost: more chunks in the index (N/(chunk_size×(1-overlap)) instead of N/chunk_size) — moderate storage increase. The LLM may receive slightly duplicate content if two overlapping chunks are both retrieved — deduplicate retrieved chunks before prompting.",
    tags:["toptal","andela"] },

  { id:"rag-037", group:"rag", difficulty:"medium", type:"short",
    question:"What is late chunking and how does it improve embedding quality?",
    answer:"Late chunking (JinaAI, 2024): instead of chunking text first then embedding chunks independently, embed the full document with a long-context embedding model (e.g., jina-embeddings-v2 with 8192-token context), then chunk the resulting contextual token embeddings by splitting the embedding sequence. Each chunk's embeddings contain full-document context (attention to all other tokens during encoding), unlike naive chunking where each chunk is encoded independently and loses cross-chunk context.",
    explanation:"Advantage: embeddings of chunks produced by late chunking are richer — they know about the rest of the document. For disambiguation (same word, different context): late chunking produces context-aware embeddings that naive chunking misses. Limitation: requires a long-context embedding model, more expensive to encode (full document per encoding rather than small chunks).",
    tags:["toptal"] },

  { id:"rag-038", group:"rag", difficulty:"medium", type:"short",
    question:"What is the difference between open-domain QA and closed-domain RAG?",
    answer:"Open-domain QA: the question can be about anything — the system must retrieve from a large general corpus (e.g., Wikipedia) and answer. The retrieval space is vast, queries are diverse. Closed-domain RAG: the knowledge base is restricted to a specific domain or document set (e.g., company internal docs, a specific product manual). Smaller retrieval space, more predictable query distribution. Closed-domain is easier: fewer out-of-scope queries, more consistent vocabulary, can fine-tune the embedding model on domain data.",
    explanation:"Production RAG systems are almost always closed-domain or bounded-domain. Common mistake: trying to handle 'any question' in a RAG system — better to define the scope clearly and redirect out-of-scope queries. Routing: use a classifier to route queries to the appropriate domain-specific RAG system (technical docs, HR policies, product info) before retrieval.",
    tags:["andela","core"] },

  { id:"rag-039", group:"rag", difficulty:"medium", type:"short",
    question:"What is an agentic RAG system and how does it differ from a RAG pipeline?",
    answer:"RAG pipeline: fixed sequence — retrieve → generate. The retrieval query is always the user's original question. Agentic RAG: the LLM is an agent with retrieval as a tool. The agent decides: when to retrieve, what to search for (can be different from the user's exact words), how many retrieval steps are needed, when enough information has been gathered. The agent can issue multiple queries, combine results, evaluate retrieved documents, and iterate. Enables: complex multi-hop questions, exploratory research tasks, tasks requiring synthesis from many sources.",
    explanation:"Agentic RAG frameworks: LangChain AgentExecutor with retrieval tools, LlamaIndex ReAct agent with query engines as tools, custom tool-use LLMs. Challenge: retrieval failures compound in multi-step agents (error propagation). Monitoring: log all retrieval steps, intermediate reasoning, and retrieved documents for debugging.",
    tags:["toptal","andela"] },

  { id:"rag-040", group:"rag", difficulty:"medium", type:"short",
    question:"What is an embedding model's context window limit and how does it affect RAG chunking?",
    answer:"Most embedding models have a maximum input token limit: BERT-based models: 512 tokens. OpenAI text-embedding-3: 8192 tokens. E5-large: 512 tokens. BGE-M3: 8192 tokens. Chunks longer than the model's limit are truncated — the model only encodes the first N tokens. Consequence: if important information is in the second half of a long chunk, it's invisible to the embedding model. This is a common bug in RAG systems that use large chunks with short-context embedding models. Fix: chunk size must always be ≤ embedding model's context limit (with some margin for special tokens).",
    explanation:"Choosing chunk size in practice: (1) Check embedding model's max_tokens limit. (2) Set chunk_size = max_tokens - 50 (buffer for special tokens). (3) For BERT-based models: max chunk = 512-50 = 462 tokens. (4) Validate: check the distribution of chunk lengths and ensure no truncation. (5) If documents need larger chunks, use a long-context embedding model (OpenAI, jina, BGE-M3).",
    tags:["toptal","andela"] },

  { id:"rag-041", group:"rag", difficulty:"medium", type:"short",
    question:"What is RAG vs. fine-tuning and when should you use each?",
    answer:"RAG: inject dynamic, external knowledge at inference. Fine-tuning: bake knowledge into weights during training. Use RAG when: knowledge changes frequently (news, company docs), knowledge needs to be verifiable/cited, out-of-distribution queries are expected, you need to add new knowledge cheaply. Use fine-tuning when: knowledge is static, response style/format needs to change, task requires very specific output format, the model needs to reason differently about a domain (not just know facts).",
    explanation:"Complementary: RAG + fine-tuning often works best. Fine-tune the LLM to better use retrieved context (respond only from context, format citations, handle 'I don't know'). Separately, fine-tune the embedding model on domain data for better retrieval. The base LLM's reasoning comes from pretraining; domain knowledge from RAG; specific behaviour from fine-tuning.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"rag-042", group:"rag", difficulty:"hard", type:"short",
    question:"What is the CRAG (Corrective RAG) approach and what problem does it solve?",
    answer:"CRAG (Shi et al., 2024): vanilla RAG blindly passes retrieved documents to the LLM, even if the retrieved documents are irrelevant or wrong. CRAG adds a retrieval evaluator: an LLM that classifies each retrieved document as Correct, Incorrect, or Ambiguous. For Correct docs: use them directly. For Incorrect docs: fall back to web search. For Ambiguous: decompose the knowledge into finer-grained strips, use correct strips, discard incorrect. Knowledge refinement: even for 'correct' documents, extract and strip irrelevant sentences before prompting the LLM.",
    explanation:"CRAG significantly improves robustness when the retrieval step fails (mis-hit, out-of-date documents, or topic drift). The retrieval evaluator is a smaller model or a few-shot prompted LLM that adds minimal latency. The web search fallback ensures the system degrades gracefully rather than generating hallucinations from incorrect retrieved content.",
    tags:["toptal"] },

  { id:"rag-043", group:"rag", difficulty:"medium", type:"short",
    question:"What is document ingestion and what are the main challenges for enterprise RAG?",
    answer:"Document ingestion: parsing documents into text for chunking and indexing. Challenges: (1) PDF parsing: PDFs may be scanned images (OCR needed), complex layouts (multi-column, tables, figures). Tools: PyMuPDF (fast), Unstructured.io (layout-aware), Docling (modern), PDFPlumber. (2) Format diversity: Word, PowerPoint, HTML, Excel, email. (3) Updating documents: when a source document changes, which chunks need re-embedding? (4) Access control: track document permissions to filter retrieval per user. (5) Scale: ingesting millions of documents requires batch processing pipelines.",
    explanation:"Best practice: (1) Use a document pipeline (Airflow, Prefect) for scheduled ingestion. (2) Store document → chunk mappings for update tracking. (3) Use incremental ingestion — only re-process changed documents. (4) Store document metadata (source URL, date, author, access level) alongside chunks for filtering and citation. (5) Test OCR quality on representative samples — OCR errors propagate as noise into retrieved chunks.",
    tags:["toptal","andela"] },

  { id:"rag-044", group:"rag", difficulty:"medium", type:"short",
    question:"What is the role of sparse attention and sliding window in long-document RAG?",
    answer:"When a long document must be processed as a whole (context stuffing), sparse attention reduces the O(N²) cost: sliding window attention limits each token to attending to a window of W previous tokens (W=512-2048), except for global tokens that attend to all. Result: O(N×W) instead of O(N²). Longformer uses: local sliding window + global attention for specific tokens ([CLS], key entities). This enables encoding very long documents (book-length) for embedding or generation without quadratic memory explosion.",
    explanation:"For RAG: Longformer-style encoders can embed 4096+ token chunks, preserving more document context than 512-token BERT-based models. In practice: BGE-M3 and jina-embeddings-v2 (8192 tokens) use Rotary PE + longer context training, not sparse attention — simpler and effective for most RAG use cases. Sliding window attention is more relevant for generation (Mistral uses it for efficient long-context generation).",
    tags:["toptal"] },

  { id:"rag-045", group:"rag", difficulty:"medium", type:"short",
    question:"What is an ensemble retriever and why is it more robust than a single retriever?",
    answer:"Ensemble retriever: combine multiple independent retrieval methods (dense, sparse, different embedding models) and fuse their rankings. Diversity: each retriever has different strengths — dense handles semantic similarity, BM25 handles keyword matches, a domain-specific model handles technical jargon. An ensemble is unlikely to fail on all retrievers simultaneously. RRF fusion: score = Σᵣ 1/(rank_r(doc) + k), k=60. No learning required — RRF naturally handles different retriever scales. Outperforms any single retriever by 5-20% on standard benchmarks.",
    explanation:"EnsembleRetriever in LangChain: wraps multiple retrievers, fuses results with RRF or weighted combination. Practical considerations: running multiple retrievers adds latency (can be parallelised). The marginal gain from a 3rd or 4th retriever diminishes. Start with BM25 + dense (2 retrievers), add a domain-fine-tuned model if retrieval recall is still insufficient.",
    tags:["toptal"] },

  { id:"rag-046", group:"rag", difficulty:"medium", type:"short",
    question:"What is a graph RAG vs. vector RAG and when does each excel?",
    answer:"Vector RAG: documents → chunks → embeddings → HNSW index. Retrieval: cosine similarity. Excels: semantic similarity queries, natural language questions, broad knowledge retrieval. Graph RAG: documents → entity extraction → knowledge graph (entities + relations). Retrieval: graph traversal, SPARQL, or embeddings of entity descriptions. Excels: relational queries ('who is connected to X?'), multi-hop traversal ('what company does X work for, and what did that company announce?'), structured fact lookup.",
    explanation:"Microsoft GraphRAG (2024) hybrid: uses both global community summaries (for high-level queries) and local entity subgraph (for specific queries). Significantly outperforms pure vector RAG on 'global sensemaking' queries (summarise, identify themes) while matching it on local fact queries. Build cost is higher (many LLM calls for entity extraction + graph construction).",
    tags:["toptal"] },

  { id:"rag-047", group:"rag", difficulty:"hard", type:"short",
    question:"What is the difference between DENSE PASSAGE RETRIEVAL (DPR) and sentence transformers for RAG?",
    answer:"DPR (Karpukhin et al., 2020): bi-encoder with separate BERT encoders for queries and passages — trained with in-batch negatives on QA pairs. Asymmetric: query encoder ≠ document encoder (better for asymmetric Q&A). Foundational for dense retrieval, trained specifically for open-domain QA. Sentence Transformers (SBERT): uses mean pooling of BERT token embeddings, trained with siamese network on NLI and STS pairs. Symmetric: same encoder for queries and documents. More general-purpose (semantic similarity across domains).",
    explanation:"In practice for RAG: DPR is less used directly (superseded by E5, BGE, OpenAI embeddings). SBERT-style models (E5, BGE, mxbai-embed) are the standard — trained on diverse (query, passage) pairs with instruction fine-tuning. Key difference: DPR uses two separate encoders (asymmetric), modern models use one encoder for both (symmetric) with instruction prefixes for asymmetry ('query: ...', 'passage: ...').",
    tags:["toptal"] },

  { id:"rag-048", group:"rag", difficulty:"medium", type:"short",
    question:"What is a RAG system's latency budget and how is it managed?",
    answer:"Total RAG latency = embedding_latency + retrieval_latency + reranker_latency + LLM_latency. Typical targets: p99 < 3 seconds for chat applications. Budget breakdown: embedding (query): 10-50ms (API) or 5-20ms (GPU local). Retrieval (HNSW): 10-100ms. Reranker: 100-300ms (CPU) or 20-50ms (GPU) for top-100. LLM generation: 500ms-5s (depends on response length and model). Optimisations: cache query embeddings for repeated queries, cache retrieval results, batch reranking, use faster LLM (GPT-4o-mini instead of GPT-4).",
    explanation:"Parallelise where possible: embed query and fetch from cache simultaneously, run BM25 and dense retrieval in parallel. Profile the pipeline to identify the bottleneck: most systems are bottlenecked by LLM generation latency, not retrieval. Streaming: return LLM tokens as they're generated (stream=True) so perceived latency is time-to-first-token, not full response time.",
    tags:["toptal","andela"] },

  { id:"rag-049", group:"rag", difficulty:"medium", type:"short",
    question:"What is the role of the LLM's prompt template in a RAG system?",
    answer:"The prompt template shapes how the LLM uses retrieved context. Key elements: (1) Instruction: 'Answer the question using ONLY the provided context. If the answer is not in the context, say I don't know.' (2) Context injection: 'Context:\\n{retrieved_chunks}\\n\\n'. (3) Query: 'Question: {query}\\nAnswer:'. Quality of the instruction has large impact on faithfulness and response quality. Bad instruction → LLM ignores context or answers from memory. Good instruction → LLM stays grounded in retrieved content.",
    explanation:"Prompt engineering for RAG faithfulness: (1) 'Only use information from the provided documents' (explicit constraint). (2) 'Cite your source document' (forces attribution). (3) 'If the documents don't contain enough information, say so' (graceful handling of retrieval gaps). (4) 'Do not infer or extrapolate beyond what is stated' (prevents hallucination). Template choice can improve faithfulness by 20-40% without changing the retrieval system.",
    tags:["toptal","andela"] },

  { id:"rag-050", group:"rag", difficulty:"hard", type:"short",
    question:"What is corrective retrieval and how is it implemented in production RAG?",
    answer:"Corrective retrieval: detect when retrieved documents are not sufficient to answer the query and take corrective action. Approaches: (1) Confidence-based: if the LLM's response contains 'I don't know' or uncertainty markers, re-retrieve with a reformulated query. (2) Retrieval evaluator: LLM classifies each retrieved document as relevant/irrelevant before generation — if too few relevant docs, issue a second retrieval. (3) Semantic similarity check: compute cosine similarity between query embedding and each retrieved chunk; discard chunks below a threshold. (4) Web search fallback: if local retrieval fails, fall back to a web search tool.",
    explanation:"Production implementation: use confidence calibration — track the correlation between LLM's expressed uncertainty and actual answer quality. If 'I don't know' responses have high precision (the answer really isn't in the corpus), don't trigger corrective retrieval. If they have low precision (the model says I don't know when it shouldn't), tune the retrieval or faithfulness prompt before adding a retry loop (which adds latency).",
    tags:["toptal","andela"] },
];
