import type { IQ } from "./interview-data";

export const BANK_B: IQ[] = [

  // ── NEURAL NETWORKS (50) ─────────────────────────────────────────────────

  { id:"nn-001", group:"neural-networks", difficulty:"easy", type:"short",
    question:"Why do neural networks need non-linear activation functions?",
    answer:"Without non-linearities, stacking multiple linear layers is mathematically equivalent to a single linear transformation — the network can only represent linear decision boundaries. Non-linear activations allow each layer to build progressively more complex representations. The Universal Approximation Theorem guarantees that a network with one hidden layer and a non-linear activation can approximate any continuous function given enough neurons.",
    explanation:"A 100-layer network with no activations: y = W₁₀₀...W₂W₁x = Wx. One matrix multiplication. Adding ReLU at each layer creates piecewise-linear functions of exponentially higher complexity with depth.",
    tags:["turing","andela","core"] },

  { id:"nn-002", group:"neural-networks", difficulty:"medium", type:"short",
    question:"Compare ReLU, sigmoid, tanh, GELU, and SwiGLU. When do you use each?",
    answer:"ReLU: max(0,x) — fast, no vanishing gradient for x>0, default for hidden layers in CNNs/MLPs. Sigmoid: 1/(1+e⁻ˣ) — output ∈(0,1), used for binary output layers, suffers from vanishing gradients. Tanh: output ∈(-1,1), zero-centred, used in RNN hidden states. GELU: x·Φ(x), smooth, probabilistic — used in BERT, GPT-2/3. SwiGLU: swish(W₁x)⊗(W₂x), gated — used in Llama, PaLM, Mistral FFN layers.",
    explanation:"Leaky ReLU: f(x)=max(αx,x) — prevents dying ReLU, small negative slope α≈0.01. ELU: smooth for negatives, reduces bias shift. In 2026: GELU in encoder transformers, SwiGLU in LLM FFN layers, ReLU everywhere else.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"nn-003", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is the vanishing gradient problem and which architectures are most susceptible?",
    answer:"In deep networks with sigmoid/tanh activations, backpropagated gradients shrink by the derivative at each layer (sigmoid derivative ≤0.25). After 10 layers: gradient is multiplied by ≤0.25¹⁰≈10⁻⁶ — early layers receive nearly zero gradient and stop learning. Most susceptible: deep vanilla RNNs (long sequences behave like deep networks), deep networks with sigmoid/tanh activations, networks without skip connections.",
    explanation:"Solutions: ReLU activations (gradient=1 for x>0), residual connections (direct gradient path), LSTM/GRU gates (learned gradient highways), batch normalisation (keeps activations in gradient-friendly range), proper weight initialisation.",
    tags:["toptal","frequently-tested"] },

  { id:"nn-004", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is the exploding gradient problem and how is it fixed?",
    answer:"Exploding gradients: in deep networks or long RNN sequences, gradients grow exponentially through backpropagation — weight updates become extremely large, causing the loss to diverge (NaN values). Fix: gradient clipping — cap the gradient norm: if ‖g‖>threshold, g = g×(threshold/‖g‖). Standard threshold: 1.0. Also helps: proper weight initialisation, batch normalisation, LSTM/GRU in place of vanilla RNN.",
    explanation:"In PyTorch: torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0) — called after loss.backward() and before optimizer.step(). Essential for LLM training, where loss spikes are common in early training.",
    tags:["toptal","andela"] },

  { id:"nn-005", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is weight initialisation and why do Xavier and He initialisation work?",
    answer:"Poor init → activations either saturate or explode at the start. Xavier/Glorot: σ²=2/(fan_in+fan_out) — designed for sigmoid/tanh to keep activation variance stable across layers. He/Kaiming: σ²=2/fan_in — designed for ReLU, accounts for ~50% of units being zeroed (effective fan_in halved). Both ensure the variance of activations and gradients stays approximately constant across all layers at initialisation.",
    explanation:"PyTorch defaults: Conv layers use Kaiming uniform (He), Linear layers use Kaiming uniform. Bias initialised to zero. Transformers: Xavier uniform for Q/K/V projections, scaled init (σ=0.02) for embedding and output layers.",
    tags:["toptal"] },

  { id:"nn-006", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is batch normalisation and what problem does it solve?",
    answer:"BatchNorm normalises activations within each mini-batch: x̂=(x-μ_batch)/√(σ²_batch+ε), then applies learnable scale and shift: y=γx̂+β. Solves: (1) Internal covariate shift — the distribution of layer inputs shifts as earlier layers update, slowing convergence. (2) Enables higher learning rates. (3) Acts as regularisation (batch statistics noise). At inference: uses running mean/variance accumulated during training.",
    explanation:"Limitations: behaves differently at train vs. test; degrades with small batches (use GroupNorm or LayerNorm instead). LayerNorm normalises across features per sample — no batch dependence — and is the standard for LLMs.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"nn-007", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is the difference between BatchNorm, LayerNorm, GroupNorm, and InstanceNorm?",
    answer:"BatchNorm: normalise over (N,H,W) for each channel C — depends on batch, poor for small batches. LayerNorm: normalise over (C,H,W) for each sample N — no batch dependence, standard for NLP/LLMs. InstanceNorm: normalise over (H,W) for each (N,C) — used in style transfer. GroupNorm: normalise over groups of channels for each (N,group) — best for small-batch training in vision (object detection).",
    explanation:"Memory-efficient normalisation: RMSNorm (used in Llama/Mistral) is a simplified LayerNorm that skips mean subtraction: output = x/RMS(x) × γ. Slightly faster, same quality.",
    tags:["toptal","andela"] },

  { id:"nn-008", group:"neural-networks", difficulty:"easy", type:"short",
    question:"What is dropout and how does it differ at training vs. inference time?",
    answer:"Training: each neuron is independently zeroed with probability p (typical p=0.1-0.5). Inverted dropout: divide surviving activations by (1-p) to maintain expected magnitude. Inference: no dropout applied — all neurons active with their learned weights (already scaled by (1-p) during training). In PyTorch: model.train() enables dropout; model.eval() disables it.",
    explanation:"Dropout approximates training an ensemble of 2^N sub-networks (all possible subsets of neurons). It forces neurons to be independently useful rather than co-adapting. Rates: 0.1-0.2 in transformer attention, 0.5 in large FC layers in classification heads.",
    tags:["toptal","andela","core"] },

  { id:"nn-009", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is a residual connection and why does it enable training of very deep networks?",
    answer:"Residual connection: output = F(x) + x, where F is a stack of layers. The '+x' bypasses the layers. Benefits: (1) Gradient flows directly through the identity shortcut — no vanishing gradient. (2) The network only needs to learn the residual change ΔF(x), not the full transformation — easier, especially when the optimal function is close to the identity. (3) Enables 100-1000+ layer networks (ResNet-1000+).",
    explanation:"Identity shortcut: used when input and output have the same dimensions. Projection shortcut (1×1 conv): used when dimensions differ (e.g., changing number of channels). Used in ResNet (vision), Transformers (attention+FFN blocks), DenseNet (connects all previous layers).",
    tags:["toptal","frequently-tested"] },

  { id:"nn-010", group:"neural-networks", difficulty:"medium", type:"short",
    question:"How does backpropagation work computationally?",
    answer:"Backpropagation applies the chain rule of calculus through the computational graph. Forward pass: compute activations and cache intermediate values. Backward pass: starting from the loss L, compute ∂L/∂w for each parameter by applying the chain rule: ∂L/∂wᵢ = ∂L/∂aₙ × ∂aₙ/∂aₙ₋₁ × ... × ∂aᵢ₊₁/∂wᵢ. Each layer receives the gradient from above and passes down the gradient w.r.t. its input.",
    explanation:"Autograd in PyTorch/JAX builds a dynamic computational graph during the forward pass. Each tensor operation records how to compute its gradient (the backward function). Calling loss.backward() traverses this graph in reverse, accumulating gradients in each parameter's .grad attribute.",
    tags:["toptal","andela","core"] },

  { id:"nn-011", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is the dying ReLU problem and how do you fix it?",
    answer:"A ReLU neuron 'dies' when it consistently receives negative inputs — the gradient is always zero, so the neuron never updates and permanently outputs 0. Causes: large negative bias, large negative weight updates, or very high learning rates. Fixes: Leaky ReLU (f(x)=max(0.01x,x) — small slope for negatives), ELU, GELU (smooth, no sharp cutoff at zero), He initialisation (prevents initial negative activations), lower learning rate.",
    explanation:"Dead neurons are detectable: monitor the fraction of zero activations per layer. If >90% of ReLU neurons are dead, the network has a problem. BatchNorm before ReLU helps by keeping pre-activation values centred near zero.",
    tags:["toptal","andela"] },

  { id:"nn-012", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is a convolutional layer and what are the key parameters?",
    answer:"A conv layer applies learnable filters across the input, producing feature maps. Key parameters: filter_size F (e.g., 3×3), stride S (step size), padding P (zero-padding to control output size), n_filters (number of output channels). Output size: (W-F+2P)/S+1 per spatial dimension. Parameter count: F×F×C_in×C_out + C_out (bias). Weight sharing means one 3×3 filter scans the entire image — only 9×C_in×C_out parameters regardless of image size.",
    explanation:"Padding types: 'same' (output same size as input), 'valid' (no padding, output shrinks). Standard modern CNNs use 3×3 filters exclusively (multiple 3×3 convs have the same receptive field as one 5×5 with fewer parameters and more non-linearities).",
    tags:["toptal","andela","frequently-tested"] },

  { id:"nn-013", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is the receptive field of a CNN and how is it calculated?",
    answer:"Receptive field: the region of the input image that influences a specific output neuron. Each conv layer with filter size F and stride S adds (F-1)×(product of previous strides) pixels to the receptive field per side. After k layers of 3×3 convs with stride 1: RF = 1 + 2k. Dilated convolution with rate d: each layer contributes d×(F-1), expanding RF without extra parameters.",
    explanation:"Large RF is needed for: object detection (see full objects), semantic segmentation (global context). Strategies: stack more layers, larger kernels (expensive), dilated convolutions (DeepLab), pooling/strided convolutions, attention mechanisms (global RF at every position).",
    tags:["toptal"] },

  { id:"nn-014", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is max pooling vs global average pooling and when do you use each?",
    answer:"Max pooling: takes the maximum value in each pooling window (e.g., 2×2) — captures the most salient feature, adds translation invariance, reduces spatial dimensions by 2×. Used between conv layers for spatial downsampling. Global Average Pooling (GAP): reduces each feature map to a single value (mean over all spatial positions) — replaces the large flattening+FC layers in classification heads, dramatically fewer parameters, acts as regularisation, feature maps directly interpretable as class heat maps.",
    explanation:"Modern CNNs (ResNet, EfficientNet, ViT): no max pooling except initial downsampling, GAP before final linear classifier. The shift from flattening to GAP was key to making CNNs more efficient and less prone to overfitting on the classification head.",
    tags:["andela"] },

  { id:"nn-015", group:"neural-networks", difficulty:"hard", type:"short",
    question:"What is an LSTM and what do the three gates do?",
    answer:"LSTM has a cell state cₜ (long-term memory) and hidden state hₜ. Three gates: Forget gate fₜ = σ(W_f[hₜ₋₁,xₜ]+b_f) — what fraction of cₜ₋₁ to remember. Input gate iₜ = σ(W_i[hₜ₋₁,xₜ]+b_i) — what new information to write to cell. Output gate oₜ = σ(W_o[hₜ₋₁,xₜ]+b_o) — what part of cell to expose as hidden state. Update: cₜ = fₜ⊗cₜ₋₁ + iₜ⊗tanh(W_c[hₜ₋₁,xₜ]+b_c); hₜ = oₜ⊗tanh(cₜ).",
    explanation:"The cell state is the gradient highway — it flows with only element-wise multiplication by the forget gate, no matrix multiply. This is why LSTMs can backpropagate over hundreds of timesteps (the gradient is fₜ at each step — can be ~1 if the forget gate keeps the cell). GRU: two gates (update, reset), no separate cell state — 33% fewer parameters, similar performance.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"nn-016", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is the difference between RNN, LSTM, GRU and when would you use each in 2026?",
    answer:"Vanilla RNN: simple, suffers from vanishing gradients beyond ~20 timesteps. LSTM: gates control memory flow, handles ~100-1000 timesteps, more parameters (4 weight matrices vs. 1). GRU: 2 gates, 3 weight matrices, similar to LSTM but 33% fewer params, often matches LSTM on smaller datasets. In 2026: Transformers dominate for sequence modelling (language, audio, video). LSTMs/GRUs used in: resource-constrained on-device deployment, streaming inference (transformers need full context), custom sequential state machines.",
    explanation:"Mamba (2023) and SSMs (State Space Models) are emerging as efficient alternatives to both — linear complexity vs. transformer O(N²), competitive on long sequences. They may replace LSTMs in latency-sensitive streaming applications.",
    tags:["toptal","andela"] },

  { id:"nn-017", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is an autoencoder and what are its uses?",
    answer:"Autoencoder: encoder compresses input to a low-dimensional latent vector z; decoder reconstructs input from z. Trained to minimise reconstruction error. The bottleneck forces learning of the most important features. Uses: (1) Dimensionality reduction (alternative to PCA — non-linear). (2) Anomaly detection — high reconstruction error = anomaly. (3) Denoising — train to reconstruct clean signal from corrupted input. (4) Pretraining — initialise encoder for downstream tasks.",
    explanation:"Sparse autoencoder: add L1 penalty on z to encourage sparse representations. Contractive autoencoder: penalise the Frobenius norm of the Jacobian of z w.r.t. input — robust to input perturbations. Masked Autoencoders (MAE) for images: mask 75% of patches, reconstruct — learns strong visual representations.",
    tags:["toptal","andela"] },

  { id:"nn-018", group:"neural-networks", difficulty:"hard", type:"short",
    question:"What is a VAE (Variational Autoencoder) and how does it differ from a standard autoencoder?",
    answer:"Standard autoencoder: encoder maps each input to a single point in latent space — latent space may have holes (random z vectors don't decode to valid samples). VAE: encoder maps each input to a distribution (mean μ and log-variance logσ² of a Gaussian). Sample z = μ + ε×σ (reparameterisation trick for backprop). Loss: reconstruction loss + KL divergence loss (KL(q(z|x) ‖ p(z)) — keeps posterior close to standard Gaussian prior). This ensures the latent space is continuous and dense — any z decodes to a valid sample.",
    explanation:"Reparameterisation trick: z = μ + ε×σ where ε~N(0,I) is sampled externally. Allows gradients to flow through z to μ and σ. Without it, sampling is non-differentiable. VAEs generate blurry images; diffusion models (2022+) dominate generation quality.",
    tags:["toptal"] },

  { id:"nn-019", group:"neural-networks", difficulty:"hard", type:"short",
    question:"What is a GAN and what is mode collapse?",
    answer:"GAN (Generative Adversarial Network): generator G creates fake samples; discriminator D classifies real vs. fake. Trained adversarially: G tries to fool D; D tries to catch G. At Nash equilibrium: G generates the true data distribution, D always outputs 0.5. Mode collapse: G learns to produce a small subset of the data distribution (one or a few modes) that reliably fools D — D cannot distinguish them, so G has no incentive to diversify. Fix: Wasserstein GAN (distance metric that doesn't saturate), minibatch discrimination, feature matching.",
    explanation:"GANs have been largely superseded by diffusion models for image generation (Stable Diffusion, DALL-E 3, Midjourney). Diffusion models are more stable to train, avoid mode collapse, and produce higher quality samples. GANs are still used for: video generation (temporal consistency), real-time applications (inference is one forward pass, vs. diffusion's many denoising steps).",
    tags:["toptal"] },

  { id:"nn-020", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is an embedding layer and what does it learn?",
    answer:"An embedding layer is a trainable lookup table: integer token ID → dense vector of dimension d. The embedding matrix E has shape (vocab_size, d) — one row per token. Learned end-to-end, embeddings encode semantic relationships: similar tokens (in terms of their context) cluster in embedding space. Famous property: king - man + woman ≈ queen demonstrates linear subspace structure for semantic relations.",
    explanation:"Alternatives to learned embeddings: frozen pretrained embeddings (Word2Vec, GloVe), character-level convolutions. For LLMs, the embedding layer is tied to the output projection matrix (lm_head) — the same matrix maps tokens to embeddings and embeddings back to logits. This reduces parameters significantly.",
    tags:["toptal","andela","core"] },

  { id:"nn-021", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is the Universal Approximation Theorem and what are its limits?",
    answer:"A neural network with at least one hidden layer, a non-linear activation, and sufficient neurons can approximate any continuous function on a compact domain to arbitrary precision. Limits: (1) Only guarantees existence — doesn't say gradient descent will find it. (2) Doesn't specify how many neurons are needed (can be exponentially many). (3) Says nothing about generalisation — a network that exactly approximates the true function still needs to learn it from finite data. (4) Compact domain only — not for functions on unbounded inputs.",
    explanation:"Depth efficiency theorem: a D-layer network can represent certain functions exponentially more efficiently than a 1-layer network (needs exponentially fewer neurons). This is the theoretical justification for deep learning — depth is more parameter-efficient than width for complex functions.",
    tags:["toptal","andela"] },

  { id:"nn-022", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is transfer learning in the context of deep learning and what are the two modes?",
    answer:"Transfer learning: initialise a model with weights pretrained on a large dataset, then adapt to a target task. Mode 1 — Feature extraction: freeze all pretrained layers, only train a new classification head. Use when: tasks are very similar, target dataset is tiny (<1k examples). Mode 2 — Fine-tuning: unfreeze some or all pretrained layers and train with a low learning rate. Use when: tasks differ moderately, more target data available. Fine-tuning the whole network with LR 10-100× lower than original training is the most common approach.",
    explanation:"Layer-wise learning rate decay: use lower LR for early layers (general features, don't need much updating) and higher LR for later layers (task-specific features). Common in BERT fine-tuning: LR decays from the output layer backward through the network.",
    tags:["toptal","andela"] },

  { id:"nn-023", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is the purpose of a 1×1 convolution?",
    answer:"A 1×1 conv applies a pointwise linear combination of channels — like a fully-connected layer applied to each spatial position independently. Uses: (1) Dimensionality reduction: reduce from C_in to C_out < C_in channels cheaply (used in Inception, MobileNet). (2) Dimensionality increase: expand channels. (3) Non-linear projection: when followed by an activation. (4) Channel mixing: transform the channel representation without changing spatial dimensions.",
    explanation:"ResNet uses 1×1 convolutions in shortcut connections when the number of channels changes between residual blocks. Depthwise separable convolution (MobileNet): depthwise 3×3 conv (per-channel spatial convolution) + 1×1 conv (channel mixing) — 8-9× fewer parameters than standard 3×3 conv.",
    tags:["toptal"] },

  { id:"nn-024", group:"neural-networks", difficulty:"hard", type:"short",
    question:"What is knowledge distillation and how is it applied to compress neural networks?",
    answer:"A small student network is trained to match the soft probability outputs of a large teacher network, not just hard labels. Loss = α×CE(y_hard, p_student) + (1-α)×KL(p_teacher_T, p_student_T) where T is temperature. Temperature T>1 softens the teacher's distribution, revealing inter-class similarity. Student learns the teacher's dark knowledge — not just the right answer but the relative plausibility of all answers.",
    explanation:"Applications: DistilBERT (teacher BERT-base, student 66% size, 97% performance), TinyBERT (4-layer student from 12-layer BERT), On-device models (teacher GPT-4, students run on phone). Self-distillation: later layers of the same model teach earlier layers — improves intermediate representations.",
    tags:["toptal","frequently-tested"] },

  { id:"nn-025", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is dilated (atrous) convolution and where is it used?",
    answer:"Dilated convolution inserts d-1 zeros between filter elements (dilation rate d). A 3×3 filter with d=2 has a 5×5 receptive field, with d=4 has a 9×9 RF — exponential RF growth with linear parameter count. Uses: semantic segmentation (DeepLab) — needs large RF to capture global context without downsampling (downsampling loses resolution needed for pixel-wise prediction). WaveNet (audio generation) — stacked dilated convs reach 1000+ timestep receptive field efficiently.",
    explanation:"Dilated conv stack with rates [1,2,4,8,16]: after 5 layers, RF=63 pixels using only 5×3=15 filter elements total. Achieves the same RF as a 63×63 kernel at a tiny fraction of the cost. Key for tasks needing large context without strided downsampling.",
    tags:["toptal"] },

  { id:"nn-026", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is a Vision Transformer (ViT) and how does it differ from a CNN?",
    answer:"ViT splits the image into fixed-size patches (e.g., 16×16), flattens and linearly projects each patch into a token embedding, adds positional embeddings, and feeds the sequence through a standard transformer encoder. CNNs encode inductive biases: local connectivity, translation equivariance, weight sharing. ViT has no such inductive biases — it must learn them from data. ViT needs more data than CNNs to match performance but scales better with data/compute at large scale.",
    explanation:"ViT-22B (2023): 22 billion parameters, trains on JFT-4B dataset. Outperforms CNN-based models at the same scale. Hybrid models (CNN backbone + transformer) work well for medium-scale tasks. DeiT added distillation training to make ViT data-efficient.",
    tags:["toptal","andela"] },

  { id:"nn-027", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is multi-task learning and when does it help?",
    answer:"Multi-task learning trains one model on multiple related tasks simultaneously, sharing a common backbone and using task-specific heads. When it helps: tasks share useful representations (NLP: POS tagging + NER + sentiment share syntax), tasks provide complementary supervision signals, data is scarce for one task but abundant for others. The shared backbone acts as a regulariser — it can't overfit to one task without hurting others.",
    explanation:"MTL can hurt if tasks conflict (negative transfer) or have very different learning speeds. Solutions: gradient surgery (project conflicting gradients), task-specific learning rates, uncertainty weighting (learn per-task loss weights). T5 and LLMs are extreme MTL — a single model for all NLP tasks.",
    tags:["toptal"] },

  { id:"nn-028", group:"neural-networks", difficulty:"hard", type:"short",
    question:"What is the difference between U-Net and standard encoder-decoder architectures?",
    answer:"Standard encoder-decoder: encoder progressively downsamples (losing spatial resolution), decoder upsamples from compressed representation. Information bottleneck causes blurry outputs. U-Net: adds skip connections from each encoder level directly to the corresponding decoder level — concatenates encoder feature maps with decoder feature maps at each resolution. This preserves high-resolution spatial details that the encoder would otherwise discard.",
    explanation:"U-Net was designed for medical image segmentation (2015) and remains the standard. Used in: diffusion model denoising (Stable Diffusion uses a U-Net to denoise the latent space), video segmentation, satellite image analysis. Skip connections concatenate (not add) — the decoder sees both the encoder's local detail and the bottleneck's global context.",
    tags:["toptal"] },

  { id:"nn-029", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is parameter sharing in neural networks and give two examples?",
    answer:"Parameter sharing: the same weights are reused across different parts of the input. Examples: (1) CNNs — the same filter is applied to all spatial positions (translation equivariance, massive parameter reduction vs. FC). (2) RNNs — the same weight matrices (W_h, W_x) are applied at every timestep (enables handling variable-length sequences with fixed parameter count). (3) Transformer attention — the same Q/K/V projection matrices process all sequence positions.",
    explanation:"Parameter sharing is the key to making models that generalise across positions, timesteps, and tokens. It's an inductive bias: the network assumes that the same transformation is useful across all positions (locality + stationarity). This is why CNNs generalise so well to natural images.",
    tags:["andela"] },

  { id:"nn-030", group:"neural-networks", difficulty:"medium", type:"short",
    question:"How do you compute the number of parameters in a convolutional layer?",
    answer:"Parameters = (F × F × C_in × C_out) + C_out, where F=filter size, C_in=input channels, C_out=output channels. The +C_out is for biases (one per output channel, optional). Example: 3×3 conv with 64 input channels and 128 output channels: 3×3×64×128 + 128 = 73,728 + 128 = 73,856 parameters.",
    explanation:"Depthwise separable conv has (F×F×C_in) + (C_in×C_out) parameters — for the example above: 3×3×64 + 64×128 = 576 + 8,192 = 8,768 parameters (8.4× fewer). This is why MobileNet achieves similar accuracy to VGG with 8.5× fewer parameters.",
    tags:["toptal","andela"] },

  { id:"nn-031", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is the softmax function and what is the effect of temperature scaling?",
    answer:"Softmax converts logits z to probabilities: P(k) = exp(zₖ/T) / Σⱼexp(zⱼ/T). Without temperature (T=1): standard softmax. T→0: one-hot (most likely class gets all probability mass, argmax). T→∞: uniform distribution (equal probability for all classes). T<1: sharper, more confident predictions. T>1: softer, more uncertain. Temperature scaling is used in knowledge distillation (T>1 to reveal teacher's inter-class similarities) and LLM sampling (T=0.7 for creative text).",
    explanation:"The numerical trick for stable softmax computation: subtract max(z) before exponentiation: exp(zₖ-max(z)) / Σⱼexp(zⱼ-max(z)). Prevents overflow from large logits. All deep learning frameworks implement this automatically.",
    tags:["toptal","andela"] },

  { id:"nn-032", group:"neural-networks", difficulty:"hard", type:"short",
    question:"What is DropConnect and how does it differ from Dropout?",
    answer:"Dropout: randomly zero entire neuron outputs (activations) during training. DropConnect: randomly zero individual weights (connections) during training — a more granular version. Mathematically, Dropout is a special case of DropConnect where weights in an entire row of the weight matrix are zeroed together. DropConnect is a stronger regulariser but more computationally expensive. In practice, Dropout is used almost exclusively — DropConnect's additional benefits rarely justify the cost.",
    explanation:"DropPath (Stochastic Depth): randomly skip entire residual blocks during training (set the residual output to zero, keeping the skip connection). Allows much deeper networks and is used in ViT training. Each block survives with probability p, linearly decreasing with depth.",
    tags:["toptal"] },

  { id:"nn-033", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is gradient checkpointing and when would you use it?",
    answer:"During backpropagation, activations from the forward pass are needed to compute gradients. Storing all activations requires O(L) memory for L layers. Gradient checkpointing: don't store all activations — only store activations at checkpoint layers. Recompute (repeat forward pass for) intermediate activations as needed during backprop. Tradeoff: reduces memory from O(L) to O(√L) at the cost of ~33% more compute (recomputing forward passes).",
    explanation:"Essential for: training very deep networks or long sequences where activation memory is the bottleneck. In PyTorch: torch.utils.checkpoint.checkpoint(function, inputs). Used extensively in LLM training where sequence-level activations are the primary memory consumer.",
    tags:["toptal"] },

  { id:"nn-034", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is the difference between a generative model and a discriminative model at the neural network level?",
    answer:"Discriminative neural net: learns P(y|x) — maps input features to output labels. Examples: CNN classifier, BERT for classification, logistic regression. Generative neural net: learns to model the data distribution P(x) or P(x|y). Examples: VAEs (learn P(x|z)P(z)), GANs (implicitly learn P(x)), diffusion models (learn to reverse a diffusion process), GPT (learns P(x) via next-token prediction).",
    explanation:"Energy-Based Models (EBMs): assign a scalar energy to each input; low energy = high probability. Training requires MCMC sampling. Normalising Flows: bijective transformations from simple distributions — exact likelihood computation. Both are generative but niche compared to diffusion models and autoregressive LLMs.",
    tags:["toptal","andela"] },

  { id:"nn-035", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is depthwise separable convolution and why does MobileNet use it?",
    answer:"Standard 3×3 conv on C_in→C_out channels: applies C_out different 3×3 filters across all C_in input channels simultaneously. Depthwise separable: two steps: (1) Depthwise conv: one 3×3 filter per input channel (C_in filters, each applied to one channel). (2) Pointwise conv: 1×1 conv to mix channels (C_in→C_out). Separates spatial filtering from channel mixing. Parameters reduction: factor ≈ 1/C_out + 1/F² ≈ 8-9× for 3×3 conv with C_out=64+.",
    explanation:"MobileNetV1 (2017): uses depthwise separable convs throughout — 28× fewer multiply-adds than VGG-16, similar ImageNet accuracy. This innovation enabled deep learning on mobile devices and embedded systems.",
    tags:["toptal"] },

  { id:"nn-036", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What happens if you use sigmoid activation in a deep network instead of ReLU?",
    answer:"Sigmoid: derivative = σ(x)(1-σ(x)) ≤ 0.25. After 10 layers: gradient multiplied by ≤0.25^10 ≈10^{-6} — effectively zero. Early layers stop learning (vanishing gradient). Training extremely slow or completely stalled. Additionally, sigmoid is not zero-centred (outputs in (0,1)) — all-positive inputs to downstream layers cause zig-zag gradient updates (all partial derivatives have same sign, gradient steps must zig-zag to correct direction).",
    explanation:"Tanh is zero-centred (output ∈(-1,1)) — better than sigmoid but derivative still ≤1 (max at x=0 where tanh'=1). ReLU derivative is 0 or 1 — gradient doesn't shrink for positive inputs. This is why ReLU enabled training of modern deep networks that sigmoid could not.",
    tags:["toptal","andela"] },

  { id:"nn-037", group:"neural-networks", difficulty:"hard", type:"short",
    question:"What is Neural Architecture Search (NAS) and what are the main approaches?",
    answer:"NAS: automatically search for the best neural network architecture rather than designing it by hand. Main approaches: (1) Reinforcement learning — controller RNN samples architectures, trains them and gets validation accuracy as reward (original NAS, extremely expensive — 1800 GPU days). (2) Evolutionary algorithms — mutate and crossbreed architectures, select survivors. (3) Differentiable NAS (DARTS) — relax discrete architecture choices to continuous weights, optimise via gradient descent on a shared supernet — 1000× cheaper.",
    explanation:"EfficientNet (2019) was found via NAS with compound scaling. MobileNetV3 used NAS. Once-for-All (OFA): train one supernet, query sub-networks for different device constraints without retraining. In 2026: NAS is less common — large foundation models + fine-tuning has replaced task-specific architecture search for most applications.",
    tags:["toptal"] },

  { id:"nn-038", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is the attention mechanism in the context of seq2seq models (before transformers)?",
    answer:"Classical seq2seq RNN: encoder reads all input tokens, compresses to a fixed-length context vector, decoder generates output from context. Bottleneck: all information must pass through fixed-length vector — fails for long sequences. Attention (Bahdanau, 2014): at each decoder step, the decoder attends to all encoder hidden states: αₜᵢ = softmax(score(hₜ, hᵢ)), context = Σαₜᵢhᵢ. The attention scores αₜᵢ indicate which input tokens to focus on when generating output token t.",
    explanation:"This attention mechanism predates self-attention (transformers) by 3 years and was first applied to neural machine translation (English→French). It also enables interpretability: the attention matrix shows alignment between input and output tokens.",
    tags:["toptal","andela"] },

  { id:"nn-039", group:"neural-networks", difficulty:"easy", type:"mcq",
    options:["Prevent overfitting by zeroing activations during training",
             "Prevent underfitting by adding neurons",
             "Speed up convergence by normalising gradients",
             "Initialise weights to prevent vanishing gradients"],
    question:"What is the primary purpose of dropout in neural networks?",
    answer:"Prevent overfitting by zeroing activations during training",
    explanation:"Dropout is a regularisation technique. By randomly zeroing different neurons each batch, it prevents co-adaptation (neurons relying on specific other neurons) and approximates training an ensemble of 2^N different network architectures. The effect is similar to L2 regularisation but more extreme — some neurons contribute nothing to each forward pass.",
    tags:["turing","andela"] },

  { id:"nn-040", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is the difference between a feedforward network and a recurrent network?",
    answer:"Feedforward: information flows in one direction (input → hidden → output), no cycles. Fixed input size, no memory of previous inputs. Used for: tabular data, classification, image tasks (CNNs are feedforward with weight sharing). Recurrent: has cycles — the hidden state from time t-1 is fed back as input at time t. Maintains state over a sequence. Used for: time series, NLP (before transformers), audio processing.",
    explanation:"Transformers are technically feedforward during inference — each forward pass processes the full sequence (or cached prefix) without recurrence. They achieve sequence modelling through self-attention rather than recurrent hidden states, enabling full parallelism during training.",
    tags:["andela","core"] },

  { id:"nn-041", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is weight decay and how does it relate to L2 regularisation?",
    answer:"Weight decay: multiply weights by (1-α) at each gradient step: w ← (1-α)w - η∇L. This is equivalent to L2 regularisation (adding λ‖w‖² to the loss) when using standard SGD. However, with adaptive optimisers (Adam): L2 regularisation adds λw to the gradient before adaptive scaling, which makes the effective decay non-uniform across parameters. AdamW decouples weight decay from the gradient update: w ← (1-α)w - η × adaptive_step. AdamW is the correct way to apply weight decay with Adam.",
    explanation:"The distinction matters significantly in practice: Adam with L2 regularisation (standard Adam + weight_decay argument) underperforms AdamW for LLM training because the adaptive learning rate rescales the regularisation unevenly. Transformers library defaults to AdamW.",
    tags:["toptal","frequently-tested"] },

  { id:"nn-042", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is the lottery ticket hypothesis?",
    answer:"Frankle & Carlin (2019): within a large randomly initialised neural network, there exists a small subnetwork (the 'winning ticket') which, when trained in isolation from the same initial weights, can match the full network's performance. These lucky subnetworks are identified by iterative magnitude pruning — train, prune lowest-magnitude weights, reset remaining weights to initial values, repeat. Implication: large networks are needed for training (to find the ticket) but small networks suffice for inference.",
    explanation:"The lottery ticket hypothesis motivated much research on neural network pruning and sparse training. In practice: finding winning tickets is expensive (requires training many times). Structured pruning + fine-tuning is more practical. The hypothesis helped explain why over-parameterised models train well — the excess capacity is the search space for the lucky subnetwork.",
    tags:["toptal"] },

  { id:"nn-043", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is model pruning and what are the two main types?",
    answer:"Pruning: remove weights or structures from a trained model to reduce size and inference cost. Unstructured pruning: zero out individual weights (sparsity at weight level). Produces sparse matrices — small memory footprint but doesn't speed up inference on standard hardware without sparse matrix support. Structured pruning: remove entire neurons, attention heads, or layers. Produces a smaller dense model that runs faster on standard hardware without special sparse kernels.",
    explanation:"Common pipeline: train full model → rank structures by importance (gradient magnitude, Taylor expansion, random) → prune → fine-tune (often 80-90% of original accuracy recovers). Magnitude pruning: zero out smallest |w| weights — simple, effective. SparseGPT (2023): unstructured pruning of LLMs to 50-60% sparsity with minimal accuracy loss using one-shot approximate inverse Hessian.",
    tags:["toptal"] },

  { id:"nn-044", group:"neural-networks", difficulty:"easy", type:"short",
    question:"What is the cross-entropy loss for multi-class classification?",
    answer:"For K classes: L = -Σₖ yₖ log(p̂ₖ), where yₖ is the one-hot label and p̂ₖ = softmax(zₖ) is the predicted probability. For the true class c: L = -log(p̂_c). Minimising cross-entropy is equivalent to maximising the log-likelihood of the correct class. The gradient of softmax + cross-entropy is clean: ∂L/∂zₖ = p̂ₖ - yₖ (predicted probability minus one-hot label).",
    explanation:"Numerical stability: compute log(softmax(z)) = z - log(Σexp(z)) using the log-sum-exp trick: log-sum-exp(z) = max(z) + log(Σexp(z-max(z))). PyTorch: use nn.CrossEntropyLoss() which combines log-softmax + NLL loss in a numerically stable way.",
    tags:["turing","andela","core"] },

  { id:"nn-045", group:"neural-networks", difficulty:"hard", type:"short",
    question:"What is a normalising flow and how does it generate samples?",
    answer:"A normalising flow is a sequence of invertible, differentiable transformations f = fₙ∘...∘f₁ that maps a simple distribution (N(0,I)) to a complex target distribution. Generation: sample z~N(0,I), compute x=f(z). Density evaluation: p(x) = p(z)|det(∂f/∂z)|⁻¹ using the change-of-variables formula. Training: maximise log p(x) on training data. The Jacobian determinant must be efficiently computable — this constrains architecture choices (coupling layers, autoregressive flows).",
    explanation:"Examples: RealNVP (coupling layers, split dimensions, alternating masks), Glow (invertible 1×1 convolutions + coupling layers). Advantages over GANs: exact likelihood. Advantages over VAEs: no encoder needed. Limitation: all layers must be invertible, restricting expressiveness. Largely superseded by diffusion models for generation tasks.",
    tags:["toptal"] },

  { id:"nn-046", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is zero-shot learning vs few-shot learning in the context of deep learning?",
    answer:"Zero-shot learning: model makes predictions for classes never seen during training, using only a description or attribute vector of the class. Example: recognise 'okapi' from the description 'striped legs like a zebra, neck like a giraffe, brown body'. Few-shot learning: model learns from very few labelled examples per class (1-shot: 1 example, 5-shot: 5 examples). Approaches: prototypical networks (class prototype = mean embedding), MAML (meta-learning for fast adaptation), metric learning.",
    explanation:"In LLMs, 'zero-shot' and 'few-shot' refer to the number of demonstrations in the prompt (not parameters). LLM few-shot prompting is in-context learning — no gradient updates. True few-shot learning (updating model parameters on few examples) is a separate research problem.",
    tags:["toptal","andela"] },

  { id:"nn-047", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is curriculum learning and how does it speed up training?",
    answer:"Curriculum learning: train on easy examples first, progressively increasing difficulty — analogous to how humans learn. Benefits: (1) Easier examples provide cleaner gradient signal initially. (2) Avoids early saddle points from hard noisy examples. (3) Faster convergence (fewer total epochs to reach a given accuracy). Implementation: order examples by loss, confidence, or domain-specific difficulty metric; sample from easy distribution early in training, shift toward full distribution later.",
    explanation:"Used in: LLM pretraining (start with high-quality filtered text, add noisier web text later), machine translation (start with short sentences, add longer ones), image classification (start with high-resolution sharp images, add augmented versions). Anti-curriculum (hardest first) also works in some settings.",
    tags:["toptal"] },

  { id:"nn-048", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is mixed precision training and how does it save memory?",
    answer:"Mixed precision: store a master copy of weights in FP32 (for gradient accumulation precision), but perform forward pass, backward pass, and gradient computation in FP16 or BF16. Activations and gradients stored in 16-bit: 2× less memory per tensor. Loss scaling: scale the loss up by 2^k before backprop (prevents FP16 underflow for small gradients), then scale gradients back down before weight update. Result: ~2× memory reduction, 2-3× faster matrix multiply on Tensor Core hardware.",
    explanation:"BF16 vs FP16: same memory (2 bytes) but BF16 has FP32's exponent range — no overflow risk during training. FP16 can overflow for large gradients (requires loss scaling); BF16 rarely overflows. A100/H100 support native BF16 Tensor Cores — standard for LLM training.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"nn-049", group:"neural-networks", difficulty:"medium", type:"short",
    question:"What is an Inception module and why was it innovative?",
    answer:"Inception module (GoogLeNet/InceptionNet, 2014): at each layer, apply multiple convolutions in parallel (1×1, 3×3, 5×5) plus a max pooling branch, then concatenate all outputs. The 1×1 convolutions before 3×3 and 5×5 reduce the number of input channels (bottleneck), dramatically cutting parameter count and compute. The module lets the network learn which scale is useful at each layer, rather than fixing the kernel size.",
    explanation:"InceptionV1 (GoogLeNet): 22 layers deep, 6.7M parameters vs VGG-16's 138M — 20× fewer parameters with similar ImageNet accuracy. This showed that architectural efficiency matters as much as raw size. Modern networks use simpler residual blocks, but the 1×1 bottleneck idea persists.",
    tags:["andela"] },

  { id:"nn-050", group:"neural-networks", difficulty:"hard", type:"short",
    question:"What is contrastive learning and how does SimCLR work?",
    answer:"Contrastive learning: learn representations by pulling together similar examples (positives) and pushing apart dissimilar ones (negatives) in embedding space. SimCLR (2020): for each image, apply two different random augmentations to get two views. Both views should have similar embeddings; embeddings for different images should be dissimilar. Loss: NT-Xent (normalised temperature-scaled cross-entropy). Representations learned this way transfer well to downstream tasks without labels.",
    explanation:"SimCLR requires large batch sizes (4096-8192) for enough negatives per example. MoCo addresses this with a momentum encoder and memory queue. BYOL (Bootstrap Your Own Latent) achieves similar results without negatives — preventing collapse via an online-target asymmetric architecture. Contrastive learning is the foundation of CLIP (text-image contrastive pretraining).",
    tags:["toptal"] },

  // ── TRAINING & OPTIMIZATION (50) ─────────────────────────────────────────

  { id:"tr-001", group:"training", difficulty:"easy", type:"short",
    question:"What is the difference between batch GD, SGD, and mini-batch SGD?",
    answer:"Batch GD: compute gradient over the entire dataset — accurate gradient, very slow per update, can't update until full pass through data, memory-intensive. SGD: one random sample per update — very fast per step, very noisy, good at escaping local minima. Mini-batch SGD: batch of 32-512 samples — balances accuracy and speed, enables GPU parallelism, the standard in deep learning. 'SGD' in frameworks (PyTorch, TF) means mini-batch SGD.",
    explanation:"The noise in mini-batch SGD is beneficial: it helps escape sharp local minima and find flatter minima with better generalisation (Keskar et al., 2017). Very large batches converge to sharper minima — use linear scaling rule (scale LR proportionally to batch size) and warmup to maintain quality.",
    tags:["turing","andela","core","frequently-tested"] },

  { id:"tr-002", group:"training", difficulty:"medium", type:"short",
    question:"How does momentum improve SGD training?",
    answer:"Standard SGD: θ ← θ - η∇L. Momentum SGD: v ← βv + ∇L; θ ← θ - ηv. The velocity v accumulates gradients over time — in consistent gradient directions, v grows (accelerates); in oscillating directions, terms cancel (dampens oscillations). β=0.9 means the velocity is a moving average of the past 10 gradients. Effect: faster convergence in long ravines, smoother trajectory through noisy gradients.",
    explanation:"Nesterov momentum (look-ahead): compute gradient at the anticipated next position θ - ηβv rather than current position. Converges faster than standard momentum in theory and practice: v ← βv + ∇L(θ-ηβv); θ ← θ - ηv.",
    tags:["toptal","andela"] },

  { id:"tr-003", group:"training", difficulty:"medium", type:"short",
    question:"How does the Adam optimiser work and what are its hyperparameters?",
    answer:"Adam maintains first moment (momentum) m and second moment (uncentred variance) v: m ← β₁m + (1-β₁)g; v ← β₂v + (1-β₂)g². Bias correction: m̂=m/(1-β₁ᵗ), v̂=v/(1-β₂ᵗ). Update: θ ← θ - η×m̂/(√v̂+ε). Hyperparameters: η (learning rate, typically 1e-3 to 1e-4 for LLMs), β₁=0.9 (momentum decay), β₂=0.999 (variance decay), ε=1e-8 (numerical stability).",
    explanation:"Adam adapts the learning rate per parameter: parameters with large, consistent gradients get normalised step sizes; parameters with small or noisy gradients get amplified steps. This makes Adam robust to different gradient scales across parameters — great for transformers where embedding and output layers have very different gradient magnitudes.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"tr-004", group:"training", difficulty:"medium", type:"short",
    question:"What is AdamW and why is it preferred over Adam for LLM training?",
    answer:"Standard Adam + weight_decay: adds λw to gradient before adaptive scaling — the effective decay rate varies per parameter depending on gradient magnitude. AdamW decouples weight decay from the adaptive gradient: θ ← (1-λη)θ - η×m̂/(√v̂+ε). The weight decay is applied directly to weights, uniformly across all parameters, independent of gradient scale. Results in better regularisation and generalisation for transformers.",
    explanation:"This distinction was formalised by Loshchilov & Hutter (2019). LLaMA, GPT-4, Gemini, and essentially all modern LLMs use AdamW. The default in HuggingFace Transformers is AdamW. Weight decay values for LLMs: λ=0.01-0.1.",
    tags:["toptal","frequently-tested"] },

  { id:"tr-005", group:"training", difficulty:"medium", type:"short",
    question:"What is learning rate warmup and why is it necessary for LLM training?",
    answer:"Warmup: linearly (or cosine) increase learning rate from ~0 to target value over the first N steps (typically 1-5% of total training). Reason: at initialisation, model weights are random — gradients are large and noisy. A large LR at the start causes large weight updates that destroy the random initialisation and send the model to bad regions it never escapes. Warmup ensures small initial updates, stabilising the early training phase.",
    explanation:"Typical LLM training schedule: 2000-step linear warmup → cosine decay to 10% of peak LR. Llama-3 used 2000-step warmup with peak LR 3e-4. No warmup with Adam can cause loss spikes in the first 100 steps that permanently degrade model quality.",
    tags:["toptal","frequently-tested"] },

  { id:"tr-006", group:"training", difficulty:"medium", type:"short",
    question:"What are the main learning rate schedules and when do you use each?",
    answer:"Constant: simple, requires careful selection. Step decay: halve LR every K epochs — simple, works for CNNs. Cosine annealing: smoothly decay LR following a cosine curve to min_lr — used for most deep learning. Linear warmup + cosine: standard for LLM training. OneCycleLR: linear warmup to max LR, cosine decay — enables super-convergence (train faster). ReduceLROnPlateau: reduce when validation loss plateaus — adaptive, good for fine-tuning.",
    explanation:"Cyclic learning rates (CLR): oscillate between min and max LR — helps escape local minima, can achieve good performance with fewer epochs. Cosine annealing with warm restarts (SGDR): periodically reset LR to max — allows model to explore different regions. In 2026, linear warmup + cosine decay is the default for pretraining; ReduceLROnPlateau for fine-tuning.",
    tags:["toptal","andela"] },

  { id:"tr-007", group:"training", difficulty:"medium", type:"short",
    question:"What is the cross-entropy loss and why is it used for classification instead of MSE?",
    answer:"Cross-entropy: L = -Σyₖlog(p̂ₖ). MSE: L = (y-ŷ)². For classification with softmax outputs: (1) MSE gradient can vanish when outputs are near 0 or 1 (sigmoid saturation). (2) Cross-entropy gradient is clean: ∂L/∂zₖ = p̂ₖ-yₖ — larger when prediction is wrong, smaller when correct. (3) Cross-entropy is the proper log-likelihood for categorical distributions — MSE assumes Gaussian noise (inappropriate for probabilities).",
    explanation:"MSE can still be used for classification (e.g., in distillation to match logits), but cross-entropy converges faster and more reliably. For regression: MSE is standard (assumes Gaussian noise). MAE (L1): more robust to outliers. Huber loss: MSE for small errors, MAE for large — best of both.",
    tags:["turing","andela","core"] },

  { id:"tr-008", group:"training", difficulty:"medium", type:"short",
    question:"What is gradient clipping and at what threshold should you set it?",
    answer:"Gradient clipping: if the L2 norm of the gradient vector exceeds a threshold τ, rescale: g ← g×(τ/‖g‖). Prevents gradient explosion. Typical threshold: max_norm=1.0 for LLMs. For CNNs: often not needed (BatchNorm stabilises gradients). For RNNs: essential. For LLMs: applied every step. In PyTorch: torch.nn.utils.clip_grad_norm_(params, max_norm=1.0) after loss.backward(), before optimizer.step().",
    explanation:"Monitor for gradient explosion: watch the gradient norm during training. If the norm regularly exceeds the clip threshold (>10×), you have a structural instability — reduce LR, check BatchNorm/LayerNorm placement, or improve initialisation.",
    tags:["toptal","andela"] },

  { id:"tr-009", group:"training", difficulty:"medium", type:"short",
    question:"What is focal loss and when would you use it?",
    answer:"Focal loss: FL = -αₜ(1-pₜ)^γ log(pₜ), where pₜ is the predicted probability for the true class. The factor (1-pₜ)^γ (focusing parameter, γ=2 by default) down-weights well-classified examples — the loss is small for easy, confident predictions and large for hard, uncertain ones. Addresses class imbalance without resampling by focusing training on hard examples. Developed for object detection (RetinaNet) where background vastly outnumbers objects.",
    explanation:"Vs. class-weighted CE: class weighting uniformly up-weights all minority samples; focal loss specifically focuses on hard examples regardless of class. In practice, focal loss is used when there are many 'easy negatives' (confident correct predictions) that dominate the gradient and prevent learning from rare hard cases.",
    tags:["toptal"] },

  { id:"tr-010", group:"training", difficulty:"hard", type:"short",
    question:"What is the triplet loss and what problems does it solve for embedding learning?",
    answer:"Triplet loss: L = max(0, ‖f(a)-f(p)‖² - ‖f(a)-f(n)‖² + margin), where a=anchor, p=positive (same class), n=negative (different class). Forces: d(anchor,positive) + margin < d(anchor,negative). Ensures a margin of separation between intra-class and inter-class distances. Problem solved: learns an embedding space where similar items are close and dissimilar items are far apart — suitable for face recognition, image retrieval, recommendation.",
    explanation:"Hard negative mining: random negatives are too easy (clear negatives) — model saturates with zero loss. Mine semi-hard negatives: negatives that are farther than the positive but within margin. Hard negative mining dramatically improves convergence. Alternatives: contrastive loss (pair-wise), NT-Xent (SimCLR, batch of negatives), ArcFace (margin in angular space).",
    tags:["toptal"] },

  { id:"tr-011", group:"training", difficulty:"medium", type:"short",
    question:"What is data augmentation and which techniques are used for images vs. text?",
    answer:"Images: random horizontal/vertical flips, random crop + resize, colour jitter (brightness, contrast, saturation, hue), random rotation, Gaussian blur, CutOut (random erase), MixUp (blend two images and labels), CutMix (replace a patch with one from another image). Text: back-translation (translate to another language and back), synonym replacement, random insertion/deletion/swap of words, EDA (Easy Data Augmentation). For structured data: SMOTE, Mixup.",
    explanation:"AutoAugment and RandAugment: automatically search for the best augmentation policies using RL or random search. SimCLR's data augmentation is central to its representation quality — random cropping + colour jitter is the most important combination.",
    tags:["toptal","andela"] },

  { id:"tr-012", group:"training", difficulty:"hard", type:"short",
    question:"What are the Chinchilla scaling laws and what was their key insight?",
    answer:"Hoffmann et al. (2022, DeepMind): analysed the optimal allocation of a compute budget C between model size N and training tokens D. Key finding: for compute-optimal training, both N and D should be scaled equally — N ∝ C^0.5, D ∝ C^0.5. Previous models (GPT-3: 175B params, 300B tokens) were significantly undertrained. Chinchilla (70B, 1.4T tokens) outperformed Gopher (280B, 300B tokens) at 4× less inference cost.",
    explanation:"Practical implication: a 7B model trained on 1T tokens ≈ a 30B model trained on 300B tokens at same compute. Llama-3-8B trains on 15T tokens — far past Chinchilla-optimal — because inference cost matters more than training cost when deploying to millions of users. Overtrained smaller models are cheaper to serve.",
    tags:["toptal","frequently-tested"] },

  { id:"tr-013", group:"training", difficulty:"medium", type:"short",
    question:"What is gradient accumulation and why is it used?",
    answer:"Gradient accumulation: run N mini-batches, sum gradients across all N before calling optimizer.step(). Effective batch size = micro_batch_size × accumulation_steps. Allows training with effective batch sizes much larger than GPU memory permits. Example: GPU holds batch_size=8, you want effective batch_size=128 → accumulate_steps=16. After 16 forward passes, one gradient update step.",
    explanation:"Critical for LLM training: large batch sizes improve gradient estimate quality, but a 70B model may only fit batch_size=1 on a single GPU. Gradient accumulation enables batch_size=1024+ across 64 GPUs with 16 accumulation steps. Combined with data parallelism (allreduce after accumulation).",
    tags:["toptal","andela"] },

  { id:"tr-014", group:"training", difficulty:"medium", type:"short",
    question:"What is label smoothing and what are its benefits?",
    answer:"Label smoothing: replace hard one-hot labels y with soft labels: y_smooth = (1-ε)×y + ε/K (ε=0.1 typically). Effects: (1) Prevents model from becoming overconfident — penalises predictions that are too extreme (log(p)→-∞ as p→0). (2) Improves calibration — predicted probabilities better reflect true confidence. (3) Regularisation — reduces overfitting to training labels. (4) Improves robustness to mislabelled examples.",
    explanation:"Equivalent to: adding a KL divergence term from the uniform distribution to the cross-entropy loss. At temperature T: label smoothing with ε=0.1 ≈ temperature scaling with T≈1.1. In practice: ε=0.1 is used in transformer training (original transformer paper, ViT, BERT pretraining).",
    tags:["toptal"] },

  { id:"tr-015", group:"training", difficulty:"hard", type:"short",
    question:"What is the difference between model parallelism and data parallelism?",
    answer:"Data parallelism: replicate the full model on each GPU/device, split different mini-batches across devices, synchronise gradients (allreduce) after each step. Scales throughput linearly with device count. Requires: model fits in one GPU's memory. Model parallelism: split the model itself across devices. Tensor parallelism: split individual weight matrices (each device holds a shard of each layer). Pipeline parallelism: each device holds a subset of layers (pipeline stages). Necessary when the model is too large for one GPU.",
    explanation:"Llama-3-70B training: uses all three (3D parallelism): data parallelism × tensor parallelism × pipeline parallelism. Data parallel is easy; model parallel requires careful communication and load balancing (pipeline bubbles). Megatron-LM implements 3D parallelism for efficient LLM training.",
    tags:["toptal","frequently-tested"] },

  { id:"tr-016", group:"training", difficulty:"medium", type:"short",
    question:"What is catastrophic forgetting and how is it addressed in continual learning?",
    answer:"When a model is fine-tuned on a new task, gradient updates overwrite weights that encoded old task knowledge — performance on old tasks degrades dramatically. Solutions: (1) Elastic Weight Consolidation (EWC): penalise changes to weights important for previous tasks (importance measured by Fisher information). (2) Progressive Neural Networks: freeze old networks, add new columns for new tasks with lateral connections. (3) Replay: mix new data with old examples during training. (4) LoRA fine-tuning: limits the range of weight changes, reducing forgetting.",
    explanation:"Catastrophic forgetting is why LoRA is preferred for LLM fine-tuning: the frozen pretrained weights preserve all original capabilities, while only the small low-rank matrices adapt. Full fine-tuning of all parameters risks forgetting pretraining knowledge.",
    tags:["toptal","andela"] },

  { id:"tr-017", group:"training", difficulty:"medium", type:"short",
    question:"What is the MSE vs MAE vs Huber loss for regression?",
    answer:"MSE (L2): (y-ŷ)². Penalises large errors quadratically — sensitive to outliers (one large error dominates). Derivative: 2(ŷ-y) — large gradient for large errors. MAE (L1): |y-ŷ|. Penalises errors linearly — robust to outliers. Derivative: sign(ŷ-y) — constant gradient (can cause oscillation near minimum). Huber: δ²/2×((y-ŷ)/δ)² for |y-ŷ|≤δ, δ×(|y-ŷ|-δ/2) otherwise. Quadratic near 0 (smooth gradient), linear for large errors (outlier robust). Best of both.",
    explanation:"Choose: MSE when outliers are meaningful and should be down-weighted by the model. MAE when outliers are noise and should be ignored. Huber (δ=1.0) for most practical regression — robust to outliers without losing smooth gradients. sklearn: HuberRegressor. PyTorch: nn.HuberLoss(delta=1.0).",
    tags:["toptal","andela"] },

  { id:"tr-018", group:"training", difficulty:"medium", type:"short",
    question:"What is knowledge distillation training setup step by step?",
    answer:"1. Train a large teacher model on hard labels to convergence. 2. For each training batch: compute teacher's soft outputs (probabilities at temperature T, e.g. T=4). 3. Train student on combined loss: α×CE(y_hard, p_student) + (1-α)×KL_divergence(p_teacher_T, p_student_T). Multiply KL term by T² (Hinton, 2015) — compensates for the gradient magnitude reduction from temperature scaling. 4. Evaluate student on standard (T=1) probabilities.",
    explanation:"Intermediate distillation: also match intermediate layers, not just outputs (TinyBERT matches attention maps and hidden states). Feature distillation: minimise MSE between teacher and student intermediate representations. These significantly improve distillation quality for very small students.",
    tags:["toptal"] },

  { id:"tr-019", group:"training", difficulty:"hard", type:"short",
    question:"What is the difference between online hard negative mining and offline hard negative mining?",
    answer:"Hard negative mining: focus training on examples the model finds difficult (near the decision boundary). Offline: pre-compute embeddings for all examples, find hard negatives, create a fixed mining set, train for a few steps, repeat. Expensive but globally optimal negatives. Online (in-batch): use other examples in the same mini-batch as negatives. Fast, no extra computation — just reuse the batch's embeddings. Limited to batch size for negative diversity. Hard in-batch negatives: select the hardest negative from the batch (highest similarity to anchor besides the positive).",
    explanation:"The quality of negatives fundamentally determines embedding model quality. Random negatives → easy model. Hard negatives → forces fine-grained discrimination. Too hard → false negatives (similar items incorrectly treated as negatives) harm training. ANCE (Approximate Nearest Neighbour Negative Contrastive Estimation) periodically refreshes negatives from the full corpus.",
    tags:["toptal"] },

  { id:"tr-020", group:"training", difficulty:"medium", type:"short",
    question:"What is the difference between SFT, RLHF, and DPO?",
    answer:"SFT (Supervised Fine-Tuning): train on (prompt, ideal response) pairs with standard cross-entropy. Teaches instruction following and output format. RLHF: (1) collect human preference comparisons, (2) train reward model, (3) use PPO RL loop to optimise LLM against reward + KL penalty. Complex but captures human preferences beyond demonstrations. DPO (Direct Preference Optimization): directly optimise preference pairs without a separate reward model — mathematically rearranges RLHF objective into a supervised loss on preference data.",
    explanation:"DPO advantages: no reward model, no RL training loop, simpler, more stable. DPO is now the standard for open-source LLM alignment (Llama-3, Mistral, Qwen). OpenAI still uses RLHF variants with additional stages (constitutional AI, critique-revision). RLAIF (AI feedback): use another LLM instead of humans to provide preference labels.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"tr-021", group:"training", difficulty:"medium", type:"short",
    question:"What is the batch size effect on training and generalisation?",
    answer:"Larger batch: more accurate gradient estimate (lower noise), faster per-step convergence, but converges to sharper minima with worse generalisation (sharp minima generalise less well). Smaller batch: noisier gradient, more steps to convergence, but finds flatter minima with better generalisation. Linear scaling rule: when multiplying batch size by k, multiply LR by k — keeps the expected weight update magnitude constant. Requires warmup to stabilise large-LR training.",
    explanation:"This is why most LLM training uses relatively small per-GPU batch sizes (1-8 tokens per GPU) with gradient accumulation rather than extremely large batches. The optimal batch size is problem-specific — use gradient noise scale (GNS) to find the noise threshold: below GNS, small batches are more efficient; above, large batches.",
    tags:["toptal","frequently-tested"] },

  { id:"tr-022", group:"training", difficulty:"medium", type:"short",
    question:"What is self-supervised learning and give two concrete pretraining objectives used in LLMs?",
    answer:"Self-supervised learning: derive training signal from the data itself without human labels. Objective 1 — Masked Language Modelling (MLM, BERT): randomly mask 15% of tokens, predict the masked tokens from bidirectional context. Objective 2 — Causal Language Modelling (CLM, GPT): predict the next token given all previous tokens. Both objectives create rich contextual representations from unlimited unlabelled text.",
    explanation:"Other self-supervised objectives: Next Sentence Prediction (NSP, BERT, helps sentence-pair tasks), Replaced Token Detection (ELECTRA — more efficient than MLM, generator corrupts, discriminator detects), Span corruption (T5 — mask spans of text, reconstruct). CLM scales better than MLM — GPT-4 uses CLM; BERT-style MLM has been largely superseded.",
    tags:["toptal","andela"] },

  { id:"tr-023", group:"training", difficulty:"hard", type:"short",
    question:"What is compute-optimal training vs inference-optimal training?",
    answer:"Compute-optimal (Chinchilla): for a given compute budget, equally scale model size and training tokens. Minimises training compute for a given performance level. Inference-optimal: train a smaller model on more data — costs more compute to train, but inference is cheaper (fewer parameters to load). Llama-3-8B trains on 15T tokens (Chinchilla-optimal would be ~160B params for that compute) — deliberately overtrained because serving cost matters more than training cost when deploying to millions of users.",
    explanation:"The overtrained-small-model trend (2023-2026): Llama-1 (65B), Llama-2 (70B), Llama-3 (8B and 70B) — progressively overtrained to reduce inference cost. Phi-3-mini (3.8B) matches GPT-3.5 performance by training on 3.3T tokens of carefully filtered high-quality data.",
    tags:["toptal","frequently-tested"] },

  { id:"tr-024", group:"training", difficulty:"medium", type:"short",
    question:"What is the purpose of gradient accumulation vs using a larger batch?",
    answer:"Functionally equivalent when there's no batch normalisation: accumulating gradients over N micro-batches of size B gives the same gradient as one batch of size N×B. Practical reason: GPU memory constraints. A 70B model may only fit batch_size=1 in memory. Gradient accumulation enables effective_batch_size=128 without needing 128× more GPU memory. BatchNorm is incompatible with gradient accumulation (statistics computed per micro-batch, not the full effective batch) — use SyncBatchNorm or LayerNorm instead.",
    explanation:"gradient_accumulation_steps parameter in HuggingFace Trainer. Important: call optimizer.zero_grad() and optimizer.step() only every N steps, not every micro-batch. Scale the loss by 1/N before backward to match the gradient magnitude of a single large batch.",
    tags:["andela"] },

  { id:"tr-025", group:"training", difficulty:"medium", type:"short",
    question:"What is contrastive loss (InfoNCE) and how does SimCLR use it?",
    answer:"InfoNCE (NT-Xent): for a batch of N examples, create 2N augmented views (two augmentations per example). For anchor i with positive j (other view of same image): L_i = -log[exp(sim(zᵢ,zⱼ)/τ) / Σₖ≠ᵢ exp(sim(zᵢ,zₖ)/τ)]. The 2(N-1) other views in the batch are treated as negatives. Temperature τ controls hardness of negatives. SimCLR trains the network to maximise agreement between augmented views of the same image, learning representations where augmentation-invariant structure is captured.",
    explanation:"Large batch sizes are critical for SimCLR — more negatives per batch = better representation learning. SimCLR with batch=4096 achieves 76% top-1 ImageNet accuracy with linear probe, comparable to supervised ResNet-50 at 76.5%. CLIP uses InfoNCE with (image, text) pairs instead of (image, augmented image).",
    tags:["toptal"] },

  { id:"tr-026", group:"training", difficulty:"medium", type:"short",
    question:"What is early stopping and how do you implement it without leaking validation information?",
    answer:"Early stopping: halt training when validation metric stops improving for 'patience' epochs. Implementation: monitor val_loss every epoch; save checkpoint if val_loss < best_val_loss; increment patience counter otherwise; stop and restore best checkpoint when counter reaches max_patience. Key principle: validation loss determines when to stop, never which architecture or hyperparameters to choose — those must be chosen before training begins (on a separate validation set or via cross-validation).",
    explanation:"Common mistake: choosing hyperparameters by comparing the early-stopped validation loss across runs. This is valid! Hyperparameter selection on validation loss doesn't contaminate the test set. Only the test set must never influence any decision. If early stopping selects among architecture choices, use nested cross-validation for unbiased estimate.",
    tags:["andela","core"] },

  { id:"tr-027", group:"training", difficulty:"hard", type:"short",
    question:"What is PEFT (Parameter-Efficient Fine-Tuning) and what methods does it include?",
    answer:"PEFT: adapt pretrained LLMs to new tasks by training only a small fraction of parameters. Methods: (1) LoRA: low-rank weight matrices added to frozen layers. (2) Prefix tuning: prepend trainable 'soft prompt' tokens to each layer's key-value pairs. (3) Prompt tuning: only train input embedding of soft prompt tokens (simplest). (4) Adapter layers: small bottleneck MLP modules inserted between transformer layers. (5) IA³: scale activations with learned vectors (most parameter-efficient). (6) BitFit: train only bias terms.",
    explanation:"LoRA dominates in practice because it merges into weights at inference (zero additional latency). Adapters add 8-10ms per layer at inference. QLoRA: 4-bit quantised base model + LoRA trainable adapters — fine-tune 65B models on a single A100. Most fine-tuning in 2026 uses LoRA or QLoRA.",
    tags:["toptal","frequently-tested"] },

  { id:"tr-028", group:"training", difficulty:"medium", type:"short",
    question:"What is the difference between underfitting and overfitting from a loss curve perspective?",
    answer:"Underfitting: both training loss and validation loss are high and similar. The model is too simple — even training data is not well explained. Fix: increase model capacity, add features, reduce regularisation. Overfitting: training loss is low but validation loss is significantly higher and diverging with more epochs. Fix: regularise, get more data, reduce model size, use dropout, early stopping. Correct fit: training loss and validation loss both low and similar, and validation loss still declining.",
    explanation:"Loss curves are the primary diagnostic tool for training health. Also watch: if validation loss is lower than training loss, there's a data problem (train set is harder/noisier than validation set). If validation loss bounces, reduce LR or check for NaN in training data.",
    tags:["turing","andela","core"] },

  { id:"tr-029", group:"training", difficulty:"medium", type:"short",
    question:"What is RMSProp and how does it differ from Adam?",
    answer:"RMSProp: v ← β×v + (1-β)×g²; θ ← θ - η×g/√(v+ε). Maintains exponential moving average of squared gradients to normalise the gradient. Key difference from Adam: no momentum term (no first moment m). Adam = RMSProp + momentum + bias correction. RMSProp works well for RNNs. Adam's bias correction makes it better-behaved in the first few steps. Both adapt learning rates per parameter but Adam's momentum gives smoother updates.",
    explanation:"Historically: Adagrad was first (sum of squared gradients — LR decays to zero), RMSProp fixed Adagrad's LR decay with exponential moving average. Adam added momentum and bias correction to RMSProp. AdaGrad is still used for sparse problems (embedding lookup, recommendation systems) where each embedding has few updates.",
    tags:["toptal","andela"] },

  { id:"tr-030", group:"training", difficulty:"hard", type:"short",
    question:"What is ZeRO (Zero Redundancy Optimizer) and how does it enable training large models?",
    answer:"ZeRO (Rajbhandari et al., 2020, Microsoft): standard data parallelism replicates the full model (parameters, gradients, optimiser states) on each GPU — at 16 GPUs you have 16 copies. ZeRO partitions these across devices: ZeRO-1: partition optimiser states (4× memory reduction). ZeRO-2: additionally partition gradients (8× reduction). ZeRO-3: additionally partition parameters (64× reduction for 64 GPUs). During forward/backward, parameters are gathered via allgather when needed then discarded.",
    explanation:"ZeRO is implemented in DeepSpeed (Microsoft) and FSDP (PyTorch). ZeRO-3/FSDP enables training a 175B model on 64 A100 GPUs that would otherwise require 10,000+ GPUs with standard data parallelism. The communication overhead is higher than naive data parallelism but scaling to larger models is the priority.",
    tags:["toptal"] },

  { id:"tr-031", group:"training", difficulty:"medium", type:"short",
    question:"What is the difference between train-time and test-time compute scaling?",
    answer:"Train-time scaling: more compute during training (larger models, more data, more tokens). Yields a stronger base model. Inference-time scaling: more compute at inference (chain-of-thought, self-consistency, search, thinking). Improves answer quality for hard problems without retraining. Example: o1/o3 (OpenAI 'thinking' models) — use extended inference compute on hard math/coding problems, significantly outperforming models with more training compute on benchmarks like AIME.",
    explanation:"The shift toward inference-time scaling (2024-2026) changes the deployment model: rather than always using max compute, systems can dynamically allocate more compute to harder questions (query-adaptive compute). This is analogous to how humans think harder about harder problems.",
    tags:["toptal","frequently-tested"] },

  { id:"tr-032", group:"training", difficulty:"easy", type:"mcq",
    options:["Add dropout to all layers","Increase the number of training epochs",
             "Increase model depth","Use a larger learning rate for the full training duration"],
    question:"Which of the following is NOT a strategy for preventing overfitting?",
    answer:"Increase the number of training epochs",
    explanation:"More training epochs allows the model to overfit further (training loss decreases while validation loss increases). All others either add regularisation (dropout), increase capacity in ways that can be regularised (depth + regularisation), or affect convergence speed. Early stopping is the correct way to handle epoch count — not increasing it blindly.",
    tags:["turing","andela"] },

  { id:"tr-033", group:"training", difficulty:"medium", type:"short",
    question:"What is multi-task learning loss and how are task weights set?",
    answer:"Multi-task loss: L_total = Σₖ wₖ × Lₖ. Fixed weights: set manually based on task importance or relative loss magnitudes. Uncertainty weighting (Kendall et al., 2018): learn wₖ = 1/(2σₖ²) for each task's noise level σₖ, regularised by log(σₖ) — tasks with high noise get lower weight automatically. GradNorm: dynamically adjust task weights to equalise gradient magnitudes across tasks. PCGrad: project conflicting gradients to avoid destructive interference.",
    explanation:"Task imbalance is the biggest practical challenge in MTL. If one task has much larger gradients (e.g., due to different loss scales), it will dominate training. Normalise losses by their initial values or use uncertainty weighting as the first approach.",
    tags:["toptal"] },

  { id:"tr-034", group:"training", difficulty:"medium", type:"short",
    question:"What is Supervised Fine-Tuning (SFT) data quality vs quantity tradeoff?",
    answer:"Quality > Quantity: Alpaca-GPT4 (52k high-quality GPT-4 generated instructions) significantly outperforms Alpaca (52k GPT-3.5 instructions). OpenAI's early findings: 1000 high-quality diverse demonstrations can outperform 100k low-quality ones. Key quality factors: correctness of responses, diversity of task types, length and completeness of responses, coverage of desired behaviours. LIMA (2023): 1000 carefully curated examples achieves near-GPT-4 quality on many tasks.",
    explanation:"LIMA (Less Is More for Alignment): 1000 examples from curated StackOverflow, wikiHow, Reddit posts, handwritten examples → strong GPT-3.5-level instruction following. Suggests most alignment comes from pretraining; SFT primarily teaches format/style rather than new knowledge or capabilities.",
    tags:["toptal","frequently-tested"] },

  { id:"tr-035", group:"training", difficulty:"medium", type:"short",
    question:"What is the difference between one-cycle learning rate policy and cosine annealing?",
    answer:"Cosine annealing: LR decreases following a cosine from η_max to η_min over T steps. Can restart (SGDR) or anneal once. Standard for LLM pretraining. OneCycleLR (fastai/PyTorch): two phases — linear warmup from η_max/25 to η_max (30% of training), cosine annealing from η_max to 0 (70%). Also anneals momentum inversely. Enables 'super-convergence' — reaching good performance 5-10× faster than constant LR + momentum SGD.",
    explanation:"OneCycleLR works because the high LR phase rapidly moves the model to a good basin, while the low LR phase fine-tunes within that basin. Super-convergence was discovered empirically and works best with ResNets. For LLMs, standard warmup + cosine decay remains preferred due to stability at scale.",
    tags:["andela"] },

  { id:"tr-036", group:"training", difficulty:"hard", type:"short",
    question:"What is REINFORCE and how is it used in RLHF?",
    answer:"REINFORCE (Williams, 1992): policy gradient algorithm. Policy π_θ generates actions (tokens); reward R is received after the full sequence. Gradient: ∇_θ J = E[R × Σₜ ∇_θ log π_θ(aₜ|sₜ)]. Intuition: increase probability of actions that led to high reward, decrease for low reward. In RLHF: the LLM is the policy, token sampling is the action, reward model score is R. PPO (Proximal Policy Optimization) is REINFORCE with: clipped surrogate objective (prevents too-large updates), value function baseline (reduces variance), KL penalty (prevents distribution collapse from SFT initialisation).",
    explanation:"PPO's clipped objective: L^CLIP = E[min(rₜ(θ)×Aₜ, clip(rₜ(θ), 1-ε, 1+ε)×Aₜ)] where rₜ=π_new/π_old and Aₜ is the advantage. The clip prevents the new policy from deviating too far from the old policy in a single update step, improving stability.",
    tags:["toptal"] },

  { id:"tr-037", group:"training", difficulty:"medium", type:"short",
    question:"What is the purpose of the KL penalty in RLHF training?",
    answer:"In PPO-RLHF: total reward = reward_model_score - β×KL(π_θ ‖ π_SFT), where π_SFT is the supervised fine-tuned model. The KL divergence penalty prevents the RLHF policy from deviating too far from the SFT model. Without it: the policy may 'reward hack' — discover adversarial responses that score high on the reward model but are meaningless, harmful, or just very different from normal language (reward model overoptimisation).",
    explanation:"Goodhart's Law in RLHF: 'When a measure becomes a target, it ceases to be a good measure.' The reward model is an imperfect proxy for human preferences. With no KL penalty, PPO will exploit gaps in the reward model (e.g., repeating 'great!' thousands of times might score high). The KL penalty bounds how much the model can diverge from the trusted SFT checkpoint.",
    tags:["toptal"] },

  { id:"tr-038", group:"training", difficulty:"medium", type:"short",
    question:"What is the difference between pre-training and fine-tuning loss curves?",
    answer:"Pre-training: loss starts high (random init, ~log(vocab_size) for CLM), smoothly decreases over billions of tokens, often a power-law relationship (loss ∝ N^{-α}). Fine-tuning: starts from a much lower loss (pretrained model already knows language), decreases quickly, uses far fewer steps (hundreds to thousands vs. billions). Overfitting risk is higher in fine-tuning — fewer examples, more epochs. Learning rate should be 10-100× lower than pretraining to avoid destroying pretrained representations.",
    explanation:"Loss spikes during pretraining: sudden gradient explosions from bad data batches. Common fix: gradient clipping. If spikes are frequent, filter training data more aggressively. During fine-tuning, loss spikes indicate too-high learning rate or data distribution mismatch.",
    tags:["andela"] },

  { id:"tr-039", group:"training", difficulty:"medium", type:"short",
    question:"What is the cosine similarity and how is it used as a loss in representation learning?",
    answer:"Cosine similarity: cos(u,v) = u·v/(‖u‖×‖v‖) ∈ [-1,1]. Measures the angle between vectors regardless of magnitude — direction matters, not length. Cosine loss: 1 - cos(u,v) (0 for identical directions, 2 for opposite). Used in embedding learning: push embeddings for similar items to have cos_sim→1, dissimilar items→-1. BYOL uses negative cosine similarity as its loss between online and target network representations.",
    explanation:"In RAG and semantic search: cosine similarity between query and document embeddings determines retrieval ranking. Normalise embeddings to unit norm so cosine similarity equals dot product — enabling efficient MIPS (Maximum Inner Product Search) with FAISS.",
    tags:["toptal","andela"] },

  { id:"tr-040", group:"training", difficulty:"medium", type:"short",
    question:"What is AUC-ROC as a training objective vs evaluation metric?",
    answer:"As evaluation metric: AUC-ROC is threshold-independent, differentiates between good and bad rankings. As a training objective: AUC-ROC is not differentiable (it depends on the ranking of predictions, which has step-function discontinuities). Direct optimisation is not possible with gradient descent. Workaround: train with differentiable surrogate losses (cross-entropy, focal loss) that correlate with AUC — then evaluate with AUC. Research methods: pairwise ranking losses, smooth AUC approximations, but all are more complex than cross-entropy.",
    explanation:"This is a general issue in ML: the metric you care about (AUC, BLEU, F1, accuracy) is often non-differentiable, so you train with a proxy loss (cross-entropy) that correlates with the metric. RL can directly optimise non-differentiable metrics — this is one motivation for RLHF (optimise a reward function encoding human preferences that aren't differentiable).",
    tags:["toptal"] },

  { id:"tr-041", group:"training", difficulty:"easy", type:"short",
    question:"What is an epoch and how many epochs should you train?",
    answer:"One epoch = one complete pass through the entire training dataset. Number of epochs: depends on the model, dataset size, and learning rate schedule. Rule of thumb: train until validation loss stops improving (use early stopping with patience). For LLM pretraining: 1-3 epochs over the training corpus — the corpus is so large that more epochs cause overfitting. For image classification: 90-300 epochs with cosine decay. For fine-tuning LLMs: 1-3 epochs is standard.",
    explanation:"More epochs ≠ better model after the validation loss has converged — just more overfitting. The combination of learning rate schedule and early stopping determines when to stop. With cosine annealing: the schedule ends at a minimum — stop there, regardless of epoch count.",
    tags:["turing","andela","core"] },

  { id:"tr-042", group:"training", difficulty:"medium", type:"short",
    question:"What is the role of the learning rate in gradient descent and what happens if it is too large or too small?",
    answer:"The learning rate η controls the step size: θ ← θ - η∇L. Too large: overshoots minima, oscillates or diverges — loss increases rather than decreasing, training may produce NaN. Too small: very slow convergence, may get stuck in plateaus or local minima, training takes prohibitively many steps. Optimal: fast convergence to a good solution. Finding it: use a learning rate range test (increase LR exponentially for one epoch, plot loss vs LR, pick LR just before loss starts increasing).",
    explanation:"The Smith (2015) learning rate range test: start with LR=1e-7, increase to LR=10 over one epoch. Plot loss vs LR. The optimal LR is at the steepest negative slope (just before the loss starts increasing). This is the foundation of the OneCycleLR policy.",
    tags:["turing","andela","core"] },

  { id:"tr-043", group:"training", difficulty:"hard", type:"short",
    question:"What is LoRA and what is the mathematical justification for its effectiveness?",
    answer:"LoRA (Low-Rank Adaptation): freeze pretrained weight W₀ ∈ ℝ^{d×k}, add W = W₀ + AB where A ∈ ℝ^{d×r}, B ∈ ℝ^{r×k}, r ≪ min(d,k). Only train A and B — typically 0.01-0.1% of parameters. Mathematical justification (Aghajanyan et al., 2020): fine-tuning updates have low intrinsic dimensionality — the fine-tuning task can be represented in a much lower-dimensional subspace than the full weight space. LoRA approximates this by constraining updates to rank-r matrices.",
    explanation:"LoRA hyperparameters: r (rank, typically 4-64), α (scaling factor, typically = r), target_modules (which layers to apply LoRA to — usually Q and V projections in attention, sometimes more). At inference: merge W₀+AB to get W — zero extra inference cost. QLoRA: quantise W₀ to 4-bit (frozen), train A,B in BF16.",
    tags:["toptal","andela","frequently-tested"] },

  { id:"tr-044", group:"training", difficulty:"medium", type:"short",
    question:"What is the difference between offline and online evaluation for ML systems?",
    answer:"Offline evaluation: evaluate on a fixed held-out test set before deployment. Fast, reproducible, controlled. Limitations: test set may not reflect production distribution; doesn't capture feedback loops (model's own predictions influence future data). Online evaluation: A/B testing in production — route some users to the new model, measure real-world metrics (click-through rate, conversion, retention). Gold standard for business impact. Slower, requires infrastructure, more expensive, but reflects true user experience.",
    explanation:"Shadow mode: run new model in parallel with production model, log both predictions, evaluate new model's predictions against labels — no user impact. Canary deployment: gradually route a small % of traffic to the new model, monitor metrics, roll out if stable. These bridge offline and online evaluation.",
    tags:["toptal","andela"] },

  { id:"tr-045", group:"training", difficulty:"medium", type:"short",
    question:"What is the difference between generative pretraining objectives CLM and MLM?",
    answer:"CLM (Causal Language Modelling, GPT): predict the next token given all previous tokens. Strictly left-to-right — each token only sees past tokens. Enables autoregressive generation. Pretrains a decoder-only architecture. MLM (Masked Language Modelling, BERT): randomly mask 15% of tokens, predict masked tokens from bidirectional context. Cannot generate text autoregressively (all tokens visible in both directions). Pretrains an encoder. CLM scales better — GPT-scale models outperform BERT-scale on most tasks given equivalent compute.",
    explanation:"BERT's MLM is 85% of training inefficiency: only 15% of tokens contribute to the loss (masked tokens). ELECTRA addresses this: a generator creates corrupted tokens, a discriminator classifies every token as real/replaced — 100% of tokens contribute to loss, 4× more efficient than MLM.",
    tags:["toptal","andela"] },

  { id:"tr-046", group:"training", difficulty:"medium", type:"short",
    question:"What is the cross-entropy loss for language modelling (next-token prediction)?",
    answer:"For a sequence of N tokens: L = -1/N × ΣᵢlogP(xᵢ|x₁,...,xᵢ₋₁). The average negative log probability of each token given its preceding context. Equivalently: L = -1/N × Σᵢ z_{xᵢ} - log(Σⱼ exp(zⱼ)) where z_{xᵢ} is the logit for the true token. Minimising this is equivalent to maximising the log-likelihood of the training text under the model.",
    explanation:"Perplexity = exp(L). A loss of 2.0 nats corresponds to perplexity of e^2 ≈ 7.4. Training loss trends: GPT-2 achieves ~2.85 nats on WebText; LLaMA-3-8B achieves ~1.5 nats on diverse pretraining data. The log-loss is averaged over all positions in a sequence — long sequences with more context should have lower per-token loss.",
    tags:["toptal","andela"] },

  { id:"tr-047", group:"training", difficulty:"hard", type:"short",
    question:"What are the challenges of training LLMs and how are they addressed?",
    answer:"1. Memory: 70B model in BF16 = 140GB. Solution: tensor parallelism, ZeRO, gradient checkpointing. 2. Gradient explosion: large LR + random init. Solution: gradient clipping, learning rate warmup. 3. Numerical instability: FP16 overflow. Solution: BF16, loss scaling. 4. Training instability (loss spikes): bad data batches or LR too high. Solution: data quality filtering, gradient clipping, LR warmup. 5. Slow convergence: non-optimal optimiser. Solution: AdamW, cosine schedule. 6. Evaluation: perplexity doesn't directly predict downstream task performance. Solution: evaluating on diverse downstream benchmarks throughout training.",
    explanation:"Loss spikes are the most common practical issue in LLM pretraining. Quick fix: roll back to a checkpoint before the spike, remove the offending data batch, resume. Modern LLM training pipelines include automated spike detection and rollback mechanisms.",
    tags:["toptal"] },

  { id:"tr-048", group:"training", difficulty:"medium", type:"short",
    question:"What is the difference between pre-training data quality and quantity, and which matters more?",
    answer:"Quantity: more tokens → lower perplexity (roughly follows power law). Quality: higher quality text → better downstream performance per token. Both matter, but quality becomes more important as you approach compute-optimal training. Llama-3: trained on 15T tokens with aggressive quality filtering (CommonCrawl dedup, code dedup, quality classifiers, safety filtering). Phi-3: 3.3T tokens of 'textbook quality' data — achieves comparable performance to models trained on 10× more lower-quality data.",
    explanation:"Quality dimensions: deduplication (near-duplicate removal reduces memorisation and improves generalisation), language filtering, safety filtering (NSFW, PII removal), quality scoring (using a reference model to score text quality), domain balance (code, math, science, books proportions affect capabilities).",
    tags:["toptal","frequently-tested"] },

  { id:"tr-049", group:"training", difficulty:"medium", type:"short",
    question:"What is the dead neuron problem at a batch level and how does batch norm help?",
    answer:"Without BatchNorm: if a layer's output is consistently very negative (e.g., due to large negative bias), all ReLU activations in the next layer are dead — gradient is zero, no update propagates. BatchNorm normalises layer outputs to have mean=0, std=1 before ReLU — keeps the distribution in the active range of ReLU, dramatically reducing dead neurons. It also enables higher learning rates (gradients are better conditioned), so the model can escape bad initialisation faster.",
    explanation:"This is why BatchNorm was transformative: it stabilised training of deep networks that were previously untrainable without very careful initialisation and tiny learning rates. ResNets + BatchNorm enabled training 100-1000 layer networks that were completely intractable before.",
    tags:["andela"] },

  { id:"tr-050", group:"training", difficulty:"medium", type:"short",
    question:"What is maximum likelihood estimation in the context of neural network training?",
    answer:"MLE: find parameters θ that maximise P(data|θ) = ΠᵢP(xᵢ|θ). Taking the log: maximise Σᵢ log P(xᵢ|θ). For a classifier with softmax output: log P(yᵢ=c|xᵢ,θ) = log p̂_c. Maximising log-likelihood is equivalent to minimising cross-entropy loss. For a regression model with Gaussian noise assumption: maximising log P(yᵢ|xᵢ,θ) is equivalent to minimising MSE. So standard training objectives are all MLE with different likelihood models.",
    explanation:"Connection to information theory: cross-entropy loss = H(p,q) = H(p) + KL(p‖q). Since H(p) is constant (the true data entropy), minimising cross-entropy = minimising KL divergence from model to data distribution. MLE training minimises the KL divergence between the model distribution and the data distribution.",
    tags:["toptal"] },
];
